### ISSUE TITLE
result is nil when errors are returned

### ISSUE THREAD

**Issue by haemi** [apollographql/apollo-ios#100]
I do get the following JSON back from the server:

```
{
	"data": {},
	"errors": [{
		"message": "User Token ist nicht gültig.!",
		"name": "TokenInvalidError",
		"time_thrown": "2017-06-26T06:42:23.491Z",
		"data": {}
	}]
}
```

but now in my callback `result` is `nil` and therefore `result?.errors` is nil as well. Am I missing something here?

**Comment by martijnwalraven** [comment]
What server are you using? As far as I know, this response is actually illegal according to [the GraphQL specification](https://facebook.github.io/graphql/#sec-Response-Format):
> If the operation included execution, the response map must contain a first entry with key `data`. The value of this entry is described in the “Data” section. If the operation failed before execution, due to a syntax error, missing information, or validation error, this entry must not be present.

**Comment by haemi** [comment]
great, thanks, that's it - `data` must be a valid object or not existing at all. Thanks!
