### ISSUE TITLE
Cannot assign to property: '$0' is immutable

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-ios#1005]
I have graphql object returned from server.
Iam trying to edit the values inside the object but iam getting : 
**Cannot assign to property: '$0' is immutable**
Attached an image

<img width="771" alt="Screen Shot 2020-02-07 at 2 22 28 PM" src="https://user-images.githubusercontent.com/4921874/74029405-4e501200-49b5-11ea-8604-e52870f71756.png">

How can we update data inside retrieved graphql pbject ?

**Comment by RolandasRazma** [comment]
this is more of how swift works, don't have much to do with apollo.
If you want to update on server you need to do mutation.
If you want to mutate local object you need direct access to it.
Maybe something like:

```swift
for (index, productInSection) in self.sortedSectionsp[0].products!.enumerated() {
  guard productInSection.fragments.productDetails.id == product.id else { continue }
  self.sortedSectionsp[0].products[index].fragments.productDetails.defaultImage = ""
}
```

**Comment by designatednerd** [comment]
@RolandasRazma is that mutable because you're mutating `self.sortedSections[0].products![index]` directly instead of `productInSection`? It's all structs but all the properties are `var`s so I'm not sure why it works one place and not the other

@sam961 It would help to know where you want to make the change - locally or on the server. @RolandasRazma is correct that if you want to make it on the server you need to use a `mutation`.

**Comment by RolandasRazma** [comment]
you can mutate productInSection as well, but that's wouldn't be the same as in @sam961 example

**Comment by designatednerd** [comment]
I'm still not entirely clear on why - the only difference I see is that his is filtered into a new array before the `forEach` closure, which I didn't think would make the products immutable

**Comment by RolandasRazma** [comment]
products is mutable $0 isn't

**Comment by dimmko** [comment]
forEach takes closure as argument, so input argument can't be mutated
`func forEach(_ body: (Element) throws -> Void) rethrows`

You can iterate this way
`struct Hello {
    var propery: String
}

var array = [Hello(propery: "one"), Hello(propery: "two"), Hello(propery: "three")]
for index in (0 ..< array.count) where array[index].propery == "two" {
    array[index].propery = "changed"
}
print(array)`

**Comment by designatednerd** [comment]
Ah interesting - once you lose the direct reference it becomes immutable. TIL.

**Comment by sam961** [comment]
Actually i was trying to make changes locally ...


  ```
for (sectionIndex, sectionObject) in  self.sortedSecions.enumerated() {
    for (productIndex, product) in  sectionObject.products!.enumerated() {
       if product.fragments.productDetails.id == productNotification.id {
        self.sortedSecions[sectionIndex].products![productIndex].fragments.productDetails.flashRemainingTime! = product.fragments.productDetails.flashRemainingTime!
              }
       }
}
```

This helped in updating the object locally.

The idea was the following ....

I have a tableview , each cell contain collectionview of products.
Some products has down time counter.
I think the best approach is to decrement the inital timer and update the product timer new value in the main object.

I know my question is out of the scope,
But i appreciate if some one tell me if this is the best approach.

Note : while updating the the local object locally ... The Big O for that will be NxM 
Any suggestions ?

**Comment by designatednerd** [comment]
I think it depends on how you get how much time is remaining. You should be able to fairly easily calculate remaining time locally in the cell if you have the expiration time by comparing expiration vs `Date()` (ie, now). 

That's certainly going to be easier than trying to update the cell by updating the underlying object on a timer.

**Comment by designatednerd** [comment]
@sam961 - Have we answered your question about the property being immutable? If so, I think maybe we should move further questions to [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios) since we're trying to reserve GitHub issues for problems or feature requests. Let me know if that works for you!

**Comment by sam961** [comment]
Thank you @designatednerd  and @RolandasRazma   ... yes it helped

**Comment by bilrah** [comment]
> forEach takes closure as argument, so input argument `struct` can't be mutated
> `func forEach(_ body: (Element) throws -> Void) rethrows`
> 
> You can iterate this way
> 
> ```swift
> struct Hello {
>     var propery: String
> }
> 
> var array = [Hello(propery: "one"), Hello(propery: "two"), Hello(propery: "three")]
> for index in (0 ..< array.count) where array[index].propery == "two" {
>     array[index].propery = "changed"
> }
> print(array)
> ```

Another way 
```
array.enumerated().forEach({
array[$0.offset].property = "changed"
})
