### ISSUE TITLE
Help: Best way to keep an cache a large list

### ISSUE THREAD

**Issue by jync** [apollographql/apollo-ios#101]
We have large lists of entities that we would like the Apollo client to cache. What is the recommended approach to do this?

As I understand... each query to the graph is cached by Apollo (both the entities and the list). How would this work in large lists? Would the client cache each paginated view of data?

What if we queried the list by a different set of parameters (e.g. change sort order), does the Apollo client 'merge' the list of data? Is there a way to do this at all? And what would be a recommended pattern to apply here?

**Comment by designatednerd** [comment]
@jync Does the documentation for [Caching and Watching Queries](https://www.apollographql.com/docs/ios/watching-queries/) help at all here?

**Comment by designatednerd** [comment]
Since I haven't heard back on this one in a couple weeks, I'm going to close it out. Please feel free to stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) with any further questions. Thank you!
