### ISSUE TITLE
Image Upload issue ?

### ISSUE THREAD

**Issue by DiwakarThapa** [apollographql/apollo-ios#1013]
I am having a problem with uploading an image in ios apollo client. after I upload an image I get a **GraphQlError "createReadStream is not a function"**. 
I could not figure out what has gone wrong?
**Mutation**
```
mutation UploadPhoto($input: UploadPhotoInput){
  uploadClientPhoto(input: $input){
    photo
  }
}
```
**Type Detail**

```
type UploadPhotoInput {
photo: Upload
}
type UploadPhotoResponse {
photo: String
}
```

**Following code is not working**

```
class Network {
  static let shared = Network()
 
  private lazy var networkTransport = HTTPNetworkTransport(url: URL(string: "http://192.168.10.29:5001/graphql")!, session: .init(configuration: URLSessionConfiguration.default))
   
  private(set) lazy var apolloCient = ApolloClient(networkTransport: networkTransport)
}
```
** Upload image**
```
if let data = singlePhoto.image.jpegData(compressionQuality: 0.8) {
          let name = UUID().uuidString
          let file = GraphQLFile(fieldName: "\(name)", originalName: "\(name).png",mimeType: "image/png" ,data: data)
          
          let uploadInput = UploadPhotoInput(photo: file.originalName)
          let uploadMutation = UploadPhotoMutation(input: uploadInput)

          Network.shared.apolloCient.upload(operation: uploadMutation, context: nil, files: [file]) { (result) in
            switch result {
            case .success(let success):
              print(success.data)
            case .failure(let error):
              print(error.localizedDescription)
            }
          }
          
        }

```

**Comment by designatednerd** [comment]
Hi @DiwakarThapa - there's a couple issues that jump out at me: 
- We currently only take the file at the root of the upload, rather than wrapped in another object
- The `fieldName` on the `GraphQLFile` object needs to be the name of the field it's being uploaded for, not a UUID

Please take a look at our [documentation for uploading](https://www.apollographql.com/docs/ios/mutations/#uploading-files) which has some information on the restrictions we currently have.

**Comment by DiwakarThapa** [comment]
@designatednerd thank you for a quick response. 
Can you explain it to me why **apollo-ios** is taking file at the root of the upload rather than wrapped in another object? but in **apollo-android**, it takes the file both from the root and wrapped in another object?

**Comment by designatednerd** [comment]
It's not a *good* reason but it's the real reason: This is how it was initially added, I haven't had time to dig into this as I'm working on a major rewrite to codegen (which I'm hoping I can use to address this separately).

**Comment by designatednerd** [comment]
@DiwakarThapa Keep an eye on the changelog, I'll make sure to call this out when I finally get it addressed.
