### ISSUE TITLE
Question about reuse views

### ISSUE THREAD

**Issue by XiaoxiaYao** [apollographql/apollo-ios#1018]
Hi guys,

You know that I have one table view which is being used by several pages. The table view is expecting one model. Let's say: Company model. 
However, different queries from different pages are returning "different" models. One is returning "Toprated company", another is returning "Interested companies". The "possible type" of them is all a company mode. Just different names.

Here is the problem. These brother company models are using one table view which requires only one kind of model. So the model can not be reused.
Right now, after getting responses, I am converting the brother company model into one company model. which is not cool. 

Does anyone have any idea?
![image](https://user-images.githubusercontent.com/22899096/74514655-fdf22a80-4f47-11ea-825f-33e810a97152.png)
![image](https://user-images.githubusercontent.com/22899096/74514683-0e0a0a00-4f48-11ea-9fd3-478bccee13da.png)

**Comment by designatednerd** [comment]
This would probably be a good place for fragments - [here's a basic summary of how those work](https://graphql.org/learn/queries/#fragments). They are then generated as the same type and you can use them in a homogenous array to drive your table view.

**Comment by designatednerd** [comment]
@XiaoxiaYao - Does this answer your question?

**Comment by michaelyao-eb** [comment]
Yep Thank you. I was super new to GraphQL. Sorry for the late reply

**Comment by designatednerd** [comment]
@michaelyao-eb are you the same person as @XiaoxiaYao? :)

**Comment by XiaoxiaYao** [comment]
@designatednerd Oh, man, sorry. It's me. the same guy. Sorry, I have two github accounts . Sorry for that.

**Comment by designatednerd** [comment]
Haha no worries, a lot of people do, just wanted to make sure before I closed it out 😇
