### ISSUE TITLE
Namespaced custom scalars and JSON scalar parsing

### ISSUE THREAD

**Issue by johntmcintosh** [apollographql/apollo-ios#1019]
My team has created a new query utilizing a `JSON` scalar type for passing some misc metadata with a response. For example, consider a type like:

```
type MyType {
    key: String!
    metadata: JSON
}
```

for which the actual payload coming back in the response would look like:

```
{
    "__typename": "MyType",
    "key": "stringValue",
    "metadata": {
        "dynamicKey": "value"
    }
}
```

Up until now, we have not been using the `--passthroughCustomScalars` command line option, so all other custom scalars have been coming through the codegen as Swift `String` types. When we initially tried to use the JSON type, I found that the parsing failed, because there was no way for the child dictionary to be serialized into a `String`.

A couple of questions that come up from this:

1. I know that we can add the `--passthroughCustomScalars` flag, which will pass the custom scalars through, and then we can implement custom parsing for each of them. It's probably worth us doing this long-term, but at the moment we're running into some complexity with mapping the server's `Date` type, because once we add `--passthroughCustomScalars`, that maps to a Swift `Date`, but the Swift `Date` has a time component that we don't want as part of that parsing. I suspect that the [suggestion here](https://github.com/apollographql/apollo-ios/issues/94#issuecomment-453449690) will work for us, but it also made me wonder... **when enabling the `--passthroughCustomScalars` option, would it be reasonable for the codegen to namespace all custom scalars, so that we could avoid collisions between schema types and Swift types?**

2. When not using the `--passthroughCustomScalars` flag, it's convenient that most types map through to a `String`, so that baseline functionality works, and lightweight custom parsing can be performed on those strings as needed. **What would you think about supporting an option for the [built-in `String` parsing](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/JSONStandardTypeConversions.swift#L4:L12) to support serializing a child dictionary to a JSON-formatted String?** This could be a fallback in the same way that the current logic supports mapping numeric content into a Swift `String`. Something like this:

```
extension String: JSONDecodable, JSONEncodable {
  public init(jsonValue value: JSONValue) throws {
    switch value {
    case let string as String:
        self = string
    case let int as Int:
        self = String(int)
    case let dictionary as [String: Any]:
        guard let data = try? JSONSerialization.data(withJSONObject: dictionary, options: []) else { fallthrough }
        guard let serializedJson = String(data: data, encoding: .utf8) else { fallthrough }
        self = serializedJson
    default:
        throw JSONDecodingError.couldNotConvert(value: value, to: String.self)
    }
  }

  public var jsonValue: JSONValue {
    return self
  }
}
```

Thanks!

**Comment by designatednerd** [comment]
I'd probably throw different errors rather than just dropping down to the default case with a `fallthrough`, but that does seem like it could be doable. 

I think the bigger question is: Why would you want your dictionary serialized into a string rather than still being a dictionary?

**Comment by johntmcintosh** [comment]
👍 yeah, throwing some errors there is a good call!

Ha, so it's entirely possible I'm missing a better way of thinking about what we're trying to accomplish, so if so, definitely let me know 😄 

Eventually in the code, we do want access to the contents of `metadata` as a dictionary. My impression is that the two ways of getting access to the contents of a scalar are the two approaches I outlined above. Either all scalars are exposed as strings, or all scalars need specific parsing. In our use-case, due to the need to resolve collisions in Date scalars, we were looking into ways to get access to the `metadata` `JSON` scalar without a using the `--passthroughCustomScalars` flag. 

Does that make sense, or is there any particular gap in the way we're thinking about things?

**Comment by designatednerd** [comment]
So off the top of my head I'm thinking something similar to how [extensions is working on `GraphQLError`](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/GraphQLError.swift#L32) would probably be good, but that's coded manually. 

Could you send me your schema? I'd like to try to think about how that can be generated for a type in a schema, since those normally have static fields rather than dynamic ones.

**Comment by johntmcintosh** [comment]
I'm not able to send over the full schema, but I've just emailed you a simplified version that I think should be representative of the particular query and its types that are involved with this thread. Thanks!

**Comment by designatednerd** [comment]
Something that occurred to me before looking at your schema: Have you tried `typealias JSON: [String: Any]`?

**Comment by johntmcintosh** [comment]
If I understand correctly, using that approach would be done in conjunction with passing the `--passthroughCustomScalars` flag to the codegen. If you look at the #1 question in my original post, I outline the complication that we ran into when we were first trying that. It did work for us for the JSON parsing, but raised new complications with the collision of Date types. I think the post that I link to there gives us a path to making that work, but it seemed like needing to modify the schema client-side as an input into the codegen was a workaround approach, and that it would be ideal if there was a way for clients to manage this type of situation more directly. The two approaches that I could come up with are:

1. Providing a way to namespace the default types (like `Date` into `Apollo.Date` or something), so that collisions could be managed in code.
2. The string-ified fallback of dictionary parsing (that we've been discussing).

Does the collision that I describe in the that #1 bullet point of the original post make sense? If so, do you think there'd be value in the codegen providing a way to namespace those base types?

**Comment by designatednerd** [comment]
In theory if you do a `typealias Date = String`, you can then refer to `Date` for your custom type and `Swift.Date` in places you want to use the one in the stdlib, though I think that would be annoying.

However, there's also a `--namespace` parameter you can use to pass in a namespace for your code, which wraps all types and queries in the provided namespace. I'd give that a shot next.

**Comment by johntmcintosh** [comment]
Ha, yeah we use the standard `Date` type in enough places that I wouldn't want to convert them all to `Swift.Date` to resolve the ambiguity (though it makes sense that that technically could work).

We actually are using the `--namespace` parameter already. It namespaces the types that are custom types in our schema, for example when we fetch a list of "features", each object in that response is codegen'd as `MyNamespace.Feature`. However, the more primitive types inside of that for individual properties like `String`, `Date`, `Bool` just map directly to the system types of `String` and `Date`, without the namespace being applied.

**Comment by designatednerd** [comment]
Right, I think you still have to setup `typealias Namespace.Date = String` or whatever. Or were you already doing that?

**Comment by johntmcintosh** [comment]
Ooooh, I think that just got me to realize what I was missing... 

I had previously created the aliases without namespacing, which worked for the custom types, but wouldn't work for the Date (as discussed above). However, I didn't think about scoping the alias inside an extension of the namespace:

```
public extension MyNamespace {
    typealias JSON = [String: Any]
    typealias Date = String
}
```

Because the custom types aren't declared anywhere in the namespace, the code will compile whether you typealias inside or outside of the namespace. Doing it outside the namespace has the problem with Date collision with the stdlib type, but doing the typealias _inside_ the namespace lets you map the one inside to a `String`, while still using the stdlib `Date` elsewhere.

I think that covers the needs for our use-case well. Thanks so much for all the help!

**Comment by designatednerd** [comment]
Awesome, glad you were able to work it out!

**Comment by Renish-Development** [comment]
@johntmcintosh , @designatednerd 

How to use/implement Date type custom scalar in iOS?

I'm working with GraphQL. I have successfully implement Query and Mutation in iOS app.
I'm facing issue with Date Type. As per references, I have added --passthrough-custom-scalars in Run Script BUT I'm facing compilation issue.
**I'm facing issue with "--passthrough-custom-scalars" variable. I have added below code in Run script but I'm facing an error.**

DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"
while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
exit 1
fi
DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
done
SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/apollo-ios/scripts"
if [ -z "${SCRIPT_PATH}" ]; then
echo >&2 "error: Couldn't find the CLI script in your checked out SPM packages; make sure to add the framework to your project."
exit 1
fi
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./*/.graphql --localSchemaFile="schema.json" API.swift
"${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint="endpointURL"
#custom scalars
**$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift --passthrough-custom-scalars**

**Code for Define Date Scalars**
public typealias DateTime = Date
extension DateTime: JSONDecodable, JSONEncodable {
public init(jsonValue value: JSONValue) throws {
    guard let string = value as? String else {
        throw JSONDecodingError.couldNotConvert(value: value, to: String.self)
    }
    guard let date = ISO8601DateFormatter().date(from: string) else {
        throw JSONDecodingError.couldNotConvert(value: value, to: Date.self)
    }
    self = date
}
public var jsonValue: JSONValue {
    return ISO8601DateFormatter().string(from: self)
}
}

**I have reviewed schema JSON have a Date variable but API.swift still string type.**
Here is my graphql mutation.
**### mutation AddPeriod($uid:ID!, $start_time : Date!, $flow: PeriodFlowInput){
addPeriod(uid:$uid, start_time : $start_time, flow: $flow){
id
start_time
end_time
flow{
value
flow_time
}
}
}**
How can I pass date in GraphQL mutation. Please help me. Thanks in advance
