### ISSUE TITLE
Result public enum utility from apollo

### ISSUE THREAD

**Issue by amol-c** [apollographql/apollo-ios#102]
Hi,

The Result extensions are not accessible as it is not marked public.

For now i had to copy paste the extension to make it accessible to the project.

```
extension Result {
  var value: Value? {
    switch self {
    case .success(let value):
      return value
    case .failure(_):
      return nil
    }
  }
  
  var error: Error? {
    switch self {
    case .success(_):
      return nil
    case .failure(let error):
      return error
    }
  }
  
  func valueOrError() throws -> Value {
    switch self {
    case .success(let value):
      return value
    case .failure(let error):
      throw error
    }
  }
}
```

**Comment by martijnwalraven** [comment]
The `Result` type isn't currently part of any public API. Where did you have to use this?

**Comment by amol-c** [comment]
We are using a Result external dependency. I believe Result enum in apollo is marked as public.

So, when I include Apollo and Result(external dependency) in the same file, the compiler starts throwing error because of name collision. It gets confused whether to use 'Apollo Result' or 'Result' dependency.

To avoid this we started using 'Result' from Apollo, wherever we are using graphql.

**Comment by designatednerd** [comment]
We should probably update to use Swift 5's `Result` type instead of our own custom one where possible - that would probably help reduce some of these conflicts

**Comment by designatednerd** [comment]
Swift 5 Result shipping with 0.12.0!
