### ISSUE TITLE
Xcode warning `no rule to process file` produced by .graphql files

### ISSUE THREAD

**Issue by Mol0ko** [apollographql/apollo-ios#1025]
Is it possible to fix following Xcode warning produced by .graphql files?

> no rule to process file '*.graphql' of type 'text' for architecture 'x86_64'

<img width="816" alt="screenshot" src="https://user-images.githubusercontent.com/24519478/74742837-6440bb00-5270-11ea-9b1a-22fc97266201.png">

Xcode 11.3.1
Apollo 0.22.0

**Comment by designatednerd** [comment]
Huh, never seen that before. Was the file changed in type from `.txt` to `.graphql` or something? Does this warning persist after the Derived Data Dance (close Xcode, delete Derived Data, reopen Xcode, rebuild)? 

I can also suggest our [Xcode plugin](https://github.com/apollographql/xcode-graphql), but in theory it shouldn't be necessary to avoid some kind of processing warning.

**Comment by Mol0ko** [comment]
@designatednerd you are right about changing file type, thanks!

I figured out that creating `.swift` file via Xcode "Swift File" template (or most of others templates) and renaming it extension to `.graphql` leads to such warning.

Right way is to use "Empty" file template as mentioned in tutorial.

**Comment by designatednerd** [comment]
Oh, Xcode. 

Since this has been resolved, do you mind if we close this issue out?

**Comment by Mol0ko** [comment]
> Oh, Xcode.
> 
> Since this has been resolved, do you mind if we close this issue out?

sure, problem resolved

**Comment by bigmountainstudio** [comment]
We had this warning too. 
Selecting the graphql file and looking at the **File inspector** pane revealed the project was selected in the **Target Membership** section.
Unchecking it removed the warning.
