### ISSUE TITLE
Support non-flat CodeGen output

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#1028]
My generated Swift file is now up to 90,000+ lines. Every time I try to open the file to look at something in Xcode, the entire application freezes up for 30 seconds or more. I know that for TypeScript code generation outputs multiple files for different queries, mutations, and fragments. Can we please get support for this in Swift?

**Comment by designatednerd** [comment]
Yes, this is already supported, [please check out our Advanced Codegen Tips & Tricks](https://www.apollographql.com/docs/ios/installation/#generate-multiple-files-in-a-folder-instead-of-one-giant-file).

**Comment by AnthonyMDev** [comment]
Ahh that’s awesome news! Can we get the Apollo-tooling readme updated? It definitely still looks like it’s not supported there! 
Thanks!

**Comment by designatednerd** [comment]
I'll take a look!

**Comment by designatednerd** [comment]
It's said in a slightly obtuse way but: 

```
 - For TypeScript/Flow generators with the "outputFlat" flag is set, and for the Swift generator, this specifies a 
      file or directory (absolute or relative to the current working directory) to which:
         - a file will be written for each query (if "output" is a directory)
         - all generated types will be written
```

FWIW in the Swift wrapper I just merged there's an explicit `multipleFiles` option.

**Comment by AnthonyMDev** [comment]
Ah, yeah it's there, just hard to see unless you read VERY carefully. I'd suggest some re-wording on that documentation, but thanks for the heads up!
