### ISSUE TITLE
Json conversion issue 

### ISSUE THREAD

**Issue by vineethmi** [apollographql/apollo-ios#1031]
"Error at path \"pollDataFromPost.options)\": couldNotConvert(value: {\n    1 =     {\n        colorId = 3;\n        title = Nice;\n        voted = 1;\n    };\n    2 =     {\n        colorId = 4;\n        title = good;\n        voted = 0;\n    };\n    3 =     {\n        colorId = 1;\n        title = \"SoSo!\";\n        voted = 1;\n    };\n    4 =     {\n        colorId = 2;\n        title = bad;\n        voted = 0;\n    };\n}, to: Swift.String)"

Help me by solving this as soon as possible

**Comment by designatednerd** [comment]
Hi! I'm going to need quite a bit more information than this to help. 

For starters:
-  What is the type of `options` where it's attempting to convert to `Swift.String`?  
- Are you using `--passthroughCustomScalars` when you generate your code? 

Any information you can share in terms of the query, the schema, or the generated code would also be helpful. Thank you!

**Comment by vineethmi** [comment]
""Options"" is an array of dictionary in my response if you check the below response you will get an idea 

    "options": {
                "1": {
                    "title": "Nice",
                    "voted": 4,
                    "colorId": 3
                },
                "2": {
                    "title": "good",
                    "voted": 0,
                    "colorId": 4
                },
                "3": {
                    "title": "SoSo!",
                    "voted": 1,
                    "colorId": 1
                },
                "4": {
                    "title": "bad",
                    "voted": 0,
                    "colorId": 2
                }
            }

**Comment by designatednerd** [comment]
Hey @vineethmi - I can see your JSON, I need to see the code that is generated and the schema to see what type is expected by your code.

**Comment by vineethmi** [comment]
HI @designatednerd, 
Here is my variable schema that I am facing issue when I call my endpoint

public var options: String? {
        get {
          return resultMap["options"] as? String
        }
        set {
          resultMap.updateValue(newValue, forKey: "options")
        }
      }

**Comment by designatednerd** [comment]
It looks from the generated code and the fact that you're using `--passthroughCustomScalars` like your schema has defined `options` as an optional String rather than a custom scalar. At runtime, it's handing you a dictionary, not a string. I believe for this to work, your schema will need to define the `options` as a custom scalar, and then in Swift you'll need to `typealias` that scalar to a dictionary. 

Otherwise, the parser gets confused because it's supposed to be receiving a string, but it's actually receiving a dictionary, and you'll get the "could not convert" error you ran into.

**Comment by vineethmi** [comment]
Okay @designatednerd Thank you 
I will ask my bacn end team to provide a proper schema for it

**Comment by designatednerd** [comment]
@vineethmi Do you mind if we close this issue out?
