### ISSUE TITLE
Offline cache in other app sessions

### ISSUE THREAD

**Issue by tpsantos** [apollographql/apollo-ios#1032]
I would like to have a offline cache with independent the same sessions. I know that have a cache, but this cache expire or clear in different app sessions. It's possible in Apollo?

**Comment by designatednerd** [comment]
@tpsantos I believe what you're looking for is covered by `ApolloSQLite` - it's a SQLite implementation of our `NormalizedCache`.

**Comment by tpsantos** [comment]
@designatednerd I'm using the default cache `InMemoryNormalizedCache`, but this cache clear when has a new session in the app. If I change to ApolloSQLite, this cache will be persisted offline and expire correctly respecting a http cache time?

**Comment by designatednerd** [comment]
Right now cache expiration has to be handled manually, but it will be persisted offline.

**Comment by tpsantos** [comment]
@designatednerd Do you have a recommendation of the best practice to expire this cache manually using ApolloSQLite?

**Comment by designatednerd** [comment]
We do not at this time. There is an open PR (#971) which would give more granular information about when a specific item was updated - that'd be the first step in being able to implement cache control. At this point it's going to basically be a call to `clearCache`.

**Comment by designatednerd** [comment]
@tpsantos Is there anything else I can help with here or do you mind if we close this issue out?

**Comment by tpsantos** [comment]
Ok. I will follow the PR and check this feature.

Thank you.

**Comment by tpsantos** [comment]
@designatednerd I'm using the default cache InMemoryNormalizedCache and policy .returnCacheDataElseFetch, this cache policy should expire respecting the http max-age, right?

**Comment by designatednerd** [comment]
There is not presently any handling for that, no. All handling of cache clearing at this time is manual.

**Comment by designatednerd** [comment]
Since I haven't heard anything back here in a couple weeks, I'm going to close this issue out - @tpsantos if you're still having problems feel free to reopen. Anyone else experiencing similar problems, please open a new issue. Thank you!
