### ISSUE TITLE
URLSession is sending GET request rather than POST, although in the request I can see it's POST method.

### ISSUE THREAD

**Issue by michaelyao-eb** [apollographql/apollo-ios#1034]
This is weird. Sorry, this is might not be related to Apollo, but this is an issue via using it.
I am sending some queries, however, I did NOT set useGETForQueries = true. But the HTTP I sent is with GET method in the end. 
I can see it's ready to send POST request in this figure
![image](https://user-images.githubusercontent.com/58162752/75013055-626c3700-54be-11ea-8586-b2e0290bea19.png)

However, I got the GET request from Charles:
![image](https://user-images.githubusercontent.com/58162752/75013195-a6f7d280-54be-11ea-9c08-45db9412560e.png)
This is weird, I checked Stackoverflow. No much luck...Does anyone face this before?

**Comment by michaelyao-eb** [comment]
Sorry. Solve. It's because I did not put the / in the end of the endpoint. Still don't know why...

**Comment by designatednerd** [comment]
Weird! I'm not sure why either, but thanks for sharing so if anyone else runs into this they can try your solution.
