### ISSUE TITLE
Downloading apollo.tar.gz in scripts takes ages...

### ISSUE THREAD

**Issue by michaelyao-eb** [apollographql/apollo-ios#1043]
Hi, does anyone know where I can download the specific version of CLI tarball from website? It takes me ages to download it via build phrase.
![image](https://user-images.githubusercontent.com/58162752/75308136-8c3fa800-5888-11ea-9be5-6ac90541a4c7.png)

**Comment by michaelyao-eb** [comment]
Is this here? 
https://41516-65563448-gh.circle-artifacts.com/0/oclif-pack/apollo-v2.22.1/apollo-v2.22.1-darwin-x64.tar.gz

But I tried to download it and put it into the scripts folder. It is removed and CLI will download a new one which takes forever...

**Comment by designatednerd** [comment]
The link will be in your version's `run-bundled-codegen.sh` file (or for versions after 23.0, it'll be in `CLIDownloader.swift` in the `ApolloCodegenLib`). 

One thing to watch out for is that the script is looking for a `.shasum` file that has the cached shasum of the `.zip` file to ensure you have the version of the CLI that's tied to the version of the SDK you're using. If you just download the `.zip` file, this `.shasum` file won't be created. You can create it manually if you want - this is the code we're using in Bash to access the value: 

```
SHASUM="$(/usr/bin/shasum -a 256 "${ZIP_FILE}" | /usr/bin/awk '{ print $1 }')"
```

And then you'd need to save it to a file named `.shasum`.

Unfortunately download time is more tied to the internet connection you're using than anything we're using - this drives me nuts when I'm on hotel wifi or other bad connections. 

I'll take a look at updating the Codegen lib to check for the actual downloaded zip file in addition to the `.shasum` file though, that should be reasonably easy in Swift.

**Comment by designatednerd** [comment]
Aha! This should already work with the Swift-based codegen if you change the name of the file to `apollo.tar.gz`.

**Comment by michaelyao-eb** [comment]
OMG, what can I say about you? You are a patient and brilliant developer! If I tell you I am living in China now, you won't be surprised that it takes ages for downloading the tar ball. Now, I am using the zip file from my other GraphQL projects which have the downloaded right version of the zip file. Because via VPN, it's already hard for me to download the zip from your CI server which have the zip file. So I will try your way later. Anyway, thank you so much! Have a lovely day!
