### ISSUE TITLE
Add retry request support in `HTTPNetworkTransportPreflightDelegate`

### ISSUE THREAD

**Issue by ImranRaheem** [apollographql/apollo-ios#1045]
### Problem
In some cases, it is required to stop a network request from firing and retry the request when that error is resolved (e.g. when user's access token has expired).

Currently, for a type conforming to both `HTTPNetworkTransportPreflightDelegate` and `HTTPNetworkTransportRetryDelegate`, there is no way to return an error before sending a request in order to trigger error or retry handler callback.

### Proposed solution
Similar to adapt function in `Alamofire`'s `RequestAdapter`, convert `networkTransport(_:, willSend:)` to a throwing function and allow delegates to throw an error which is passed back to `HTTPNetworkTransportRetryDelegate`'s callback function.

**Usage Example:**

If a request is refused with an error:
```
extension NetworkManager: HTTPNetworkTransportPreflightDelegate {

  func networkTransport(_ networkTransport: HTTPNetworkTransport, 
                          shouldSend request: URLRequest) -> Bool {
      return true
  }

  func networkTransport(_ networkTransport: HTTPNetworkTransport,
                          willSend request: inout URLRequest) throws {

      guard !TokenManager.shared.hasAccessTokenExpired else {
          throw AuthError.accessTokenRequired
          return
      }

      var headers = request.allHTTPHeaderFields ?? [String: String]()
      if let token = TokenManager.shared.token {
            headers["Authorization"] = "Bearer \(token)"
      }
      request.allHTTPHeaderFields = headers
   }
}
```

Handle that error and/or retry
```
extension NetworkManager: HTTPNetworkTransportRetryDelegate {
    func networkTransport(_ networkTransport: HTTPNetworkTransport,
                          receivedError error: Error,
                          for request: URLRequest,
                          response: URLResponse?,
                          retryHandler: @escaping (Bool) -> Void) {

        // handle error or retry
    }
}
```

**Comment by designatednerd** [comment]
By design, this is really something that should be handled in `shouldSend` rather than `willSend`. In `shouldSend`, you can check to make sure you have all the info you need to make your request. If you don't have that information, you can return `false` from `willSend`, and then you can handle retrying based on that result. 

Does that make sense?

**Comment by designatednerd** [comment]
@ImranRaheem Is there anything else I can help with here?

**Comment by designatednerd** [comment]
Since I haven't heard back here in a couple weeks,  I'm going to close this issue out. If @ImranRaheem has further questions, please reopen this thread. Anyone else, please open a new issue. Thank you!
