### ISSUE TITLE
SPM Codegen missing omitDeprecatedEnumCases

### ISSUE THREAD

**Issue by crabman448** [apollographql/apollo-ios#1052]
Hi 👋  

I decided to try Codegen via SPM and I think it misses argument `omitDeprecatedEnumCases` in `ApolloCodegenOptions`. Or maybe I didn't find a way to pass this option to Codegen 🤔 

Thank you :)

**Comment by designatednerd** [comment]
Aha! good catch, I think that was added to the typescript codegen after I wrote most of the stuff in the swift codegen. Will add

**Comment by designatednerd** [comment]
Merged - you can grab this on `master` right now if you want but it'll go out in the next release (probably monday or tuesday)

**Comment by crabman448** [comment]
That’s awesome, thank you 🙌🏼
