### ISSUE TITLE
Warning 'couldn't find pc file', coming from swift dependencies.

### ISSUE THREAD

**Issue by patburns** [apollographql/apollo-ios#1059]
Opening this ticket because this warning was difficult to trace and maybe I'll save someone else time who's hits this: 

If you include Apollo-ios as a swift package you'll get the follow warning during the Resolve Swift Packages steps of Xcodes automated build process:

Resolve Package Graph 'couldn't find pc file'.

This error has little context and it's unclear where the warning is coming from. We had many swift packages so to figure this out I had to remove the packages until I figured out that the warning was coming from Apollo-ios's dependencies. Well actually it's dependencies dependencies:

Apollo depends on:
   https://github.com/daltoniam/Starscream/issues/719
      Which depends on:
        https://github.com/apple/swift-nio-zlib-support/issues/3

I'm hoping we can figure out how to fix this issue at the source in swift-nio-zlib-support. 

![Screen Shot 2020-03-03 at 3 45 14 PM](https://user-images.githubusercontent.com/1105594/75830778-8a815300-5d66-11ea-9a32-f12cdb0d5d61.png)

**Comment by designatednerd** [comment]
weird! When using SPM I've generally had it grab that transient dependency without issue. What `swift-tools-version` are you using?

**Comment by patburns** [comment]
Thanks for the fast response. I suppose I have whatever xcode 11.3.1 installs by default? Are there some command line tools I need to update? Swift printed out the follow when I asked for the version:

`➜  swift -v
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.3.0
/Applications/Xcode.app/Contents/Developer/usr/bin/lldb "--repl=-enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -color-diagnostics"
Welcome to Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).`

**Comment by designatednerd** [comment]
This would be whatever you've got declared in the comment at the top of your `Package.swift` file.

**Comment by patburns** [comment]
Ah, to be honest I'm new to SwiftPM. We configured this with xcode by dropping dependencies in Xcode. So to my knowledge we don't have a top level Package.swift file. 

![Screen Shot 2020-03-03 at 4 12 16 PM](https://user-images.githubusercontent.com/1105594/75831965-d8e42100-5d69-11ea-9ce9-08a28a0120bb.png)

**Comment by designatednerd** [comment]
Ahhh, ok - makes sense that there wouldn't be a Package.swift since Xcode is handling it for you. 

I would try going to `File > Swift Packages > Reset Package Caches` - I'm not sure what's happening with the dependency resolution there, but it seems like something bumped its head on the initial fetch.

**Comment by patburns** [comment]
Thanks for the suggestion. I didn't know about that menu. Unfortunately, the error is still present.

**Comment by designatednerd** [comment]
What about a version of the SDK 0.22 or higher - I did some major renovations in 22 so that might make a couple things clearer? If it doesn't, can you please share the `Package.resolved` that lives at `[YourProject].xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`?

**Comment by patburns** [comment]
Thanks for the suggestion. I tried upping the version and the issue persisted. However, after seeing the comment on the [attached thread.](apple/swift-nio-zlib-support#3) this morning. It dawned on me that maybe I just need to install pkg-config and it will make swift-nio-zlib-support happy.

For me this was as simple as using brew to install pkg-confg: 
`brew install pkg-config`

This fixed me up. Thanks for the help on figuring this out. At least someone googling around will figure out how to silence this warning. I'm going to follow up on the thread in the [starscream thread ](https://github.com/daltoniam/Starscream/issues/719) to see if they have any ideas of how they could avoid this. I'm not sure there is much to do at your layer. Maybe add a note in your docs?

**Comment by designatednerd** [comment]
Weird! Some other tooling must have installed that on my end, it's in my `/usr/local/bin`. Do you mind if we close this thread out?

**Comment by patburns** [comment]
No problem at all! Have a nice week!

**Comment by Sparklydust** [comment]
`brew install pkg-config` hasn't solved the warning that said "couldn't find pc file" on my side. Is there anotjer way to fix it?
