### ISSUE TITLE
Does not support iOS 8 ?

### ISSUE THREAD

**Issue by amol-c** [apollographql/apollo-ios#106]
Hi,

Is there any specific reason to drop support for iOS 8?

Our app is still supporting iOS8 and it seems Apollo has dropped support for v0.6.0.

Thanks

**Comment by martijnwalraven** [comment]
I believe the only reason was that `SQLite.swift` dropped support for iOS 8, and we didn't want to be stuck depending on an older version. We could limit the iOS 9 requirement to the `ApolloSQLite` framework, but that won't work with the current CocoaPods setup. @kompfner may have a better idea of what would be involved in this.

**Comment by amol-c** [comment]
Right now I am using the beta version.

Is there a way to use with Carthage ?

**Comment by amol-c** [comment]
Any updates on this ? We are still stuck using Beta.

**Comment by designatednerd** [comment]
Sorry we weren't able to respond to this at the time of your request! 

Unfortunately, since we're now dealing with the iOS 13 betas, we will not be adding support for iOS 8 - iOS 9 will remain our minimum at this time. Please feel free to reach out to me if you have any questions or problems!
