### ISSUE TITLE
[Android] How to cancel current request 

### ISSUE THREAD

**Issue by fairlyNguyen** [apollographql/apollo-ios#1063]
Hi,
I want to cancel the current (1) request when I call the new one (2) request (The request 2 is the same as request 1)

How I init apollo client

 `apolloClient = ApolloClient.builder()
                .serverUrl(baseUrl + "graphql" + Constants.SLASH + requestType)
                .okHttpClient(okHttpClient)
                .addCustomTypeAdapter(CustomType.JSON, customTypeAdapter)
                .httpCache(new ApolloHttpCache(cacheStore))
                .build();`

**Comment by designatednerd** [comment]
@fairlyNguyen Hi! This repo is only for the iOS SDK - for Android questions, please open an issue on the `apollo-android` repo here: https://github.com/apollographql/apollo-android

**Comment by fairlyNguyen** [comment]
@designatednerd  Opps, sorry my mistake.
