### ISSUE TITLE
Bindings for Combine?

### ISSUE THREAD

**Issue by txaiwieser** [apollographql/apollo-ios#1064]
Is there a plan to add bindings for Combine? It would be great to observe subscriptions for example

**Comment by designatednerd** [comment]
Long-term, yes. This is covered in the [ROADMAP](https://github.com/apollographql/apollo-ios/blob/master/ROADMAP.md) document, but we are planning on adding this eventually. It will be after the Swift Codegen project is completed though, as it may be some changes that make evolving a wrapper like that a lot more of a pain. 

I do not have a timeline for this, though.

**Comment by designatednerd** [comment]
For anyone looking for this in the meantime there is a community library for this: https://github.com/joel-perry/ApolloCombine

**Comment by brendan-fox-shure** [comment]
Any update on this item? Was this removed from the roadmap?  Thanks
