### ISSUE TITLE
Apollo updated to v0.23.2, unable to get callback while perform/fetch

### ISSUE THREAD

**Issue by tushar666** [apollographql/apollo-ios#1073]
**My code as below**

 let apollo = self.getApolloClient()
 let checkUserMobile = UserMobileLookupMutation(mobileNumber: "8899******")
 apollo.perform(mutation: checkUserMobile) { (result) in
      print("Result here \(result)") // 
  }

My API and server is ok and working(as checked in server logs), but not getting a callback/result
this is post-update to version  v0.23.2 (i have jumped from v0.16.1)

Please help

**Comment by designatednerd** [comment]
@tushar666 Thanks for the detail on what you upgraded from -  in [`0.18.0` we fixed a retain cycle](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md#v0180), so if you're not properly retaining your instance of `ApolloClient`, it gets deallocated. If you hang on to the `apollo` variable there, that'll fix the issue.

**Comment by LukiWen** [comment]
@designatednerd I had the same problem. How hang on to the apollo variable?Can you give me an example? Thank you!

**Comment by tushar666** [comment]
@designatednerd Thanks for the reply.
In my case, I am creating the fresh apollo client instance for each and every call.
so how the retain cycle comes in the picture in this case, please explain with an example.

Thanks, buddy.

**Comment by designatednerd** [comment]
The *removal* of the retain cycle is the issue - before, there was a retain cycle, so creating a fresh `ApolloClient` would not get automatically deallocated by ARC because of that retain cycle. 

Now, with that retain cycle gone, you need something to actually hold on  to your instance, or ARC will release it before the asynchronous call completes, and your completion closure won't get called back. 

So if before  you were doing: 

```swift
class MyVC: UIViewController {
  override func viewDidLoad() {
    let apollo = (create apollo client here)
    apollo.doSomethingAsync() { result in 
      print("RESULT: \(result)")
    }
    // When this scope exits, because nothing is holding on to the apollo instance,
    // it'll get deallocated
  }
}
```

You would likely need to add a property to your VC:   

```swift
class MyVC: UIViewController {
  var apollo: ApolloClient?

  override func viewDidLoad() {
    self.apollo = (create apollo client here)
    self.apollo?.doSomethingAsync() { result in 
      print("RESULT: \(result)")
    }
    // Now that the VC is hanging on to the `apollo` instance, it won't get 
    // deallocated until the VC gets deallocated
  }
} 
```

**Comment by designatednerd** [comment]
Since I haven't heard anything back here in a couple weeks, I'm going to close this issue out - @tushar666 if you're still having problems feel free to reopen. Anyone else experiencing similar problems, please open a new issue. Thank you!

**Comment by LukiWen** [comment]
I've solved this problem by using singletons

**Comment by designatednerd** [comment]
Yeah using a singleton is a great way to make sure it's never deallocated. However, if you don't want to use a singleton, you just have to make sure that you're holding on to the instance of the client where you're using it so that ARC doesn't hammer it.
