### ISSUE TITLE
Filter-variable in .graphql-files yields to build fail in Xcode

### ISSUE THREAD

**Issue by fabriziof** [apollographql/apollo-ios#108]
Hi,

When I include a graphql-query that uses a filter-variable in my project, the project cannot build.
For example, the following query includes a variable of type 'UserFilter': 

`query User($filter: UserFilter!) {
    allUsers(filter: $filter){
        id
    }
}`

When building the project, Apollo creates the API-file that now includes all Filter-types for every type in my schema. For every struct that represents a filter, the following error shows up:

![apolloerror](https://user-images.githubusercontent.com/13252238/28138490-4457b90e-6751-11e7-8daa-1e4c86c068e4.png)

**Comment by martijnwalraven** [comment]
This should be fixed in Apollo iOS 0.6.2.

**Comment by martijnwalraven** [comment]
This should be fixed in apollo-codegen 0.16.2.
