### ISSUE TITLE
Enhancement: Handling code generation across multiple modules

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#1087]
Had a long chat with @AnthonyMDev about this issue and this is something that would be really helpful to think about as we work on updated codegen.

Right now, it's basically impossible to use our codegen across multiple modules without having some kind of base module that contains all generated code and `.graphql` files. This is fine if you only have one module for your application or a reasonably small number of modules, but if you're working on a gargantuan app, you could wind up with some absolutely enormous codegen modules that leak implementation details between different modules like a sieve. 

It would be great if we could have a way to confine graphQL files and their generated `.swift` counterparts to their own module, but still allow generation of code across modules.

This is...not straightforward, to say the least. Here are a few of the issues we need to solve: 

- How do we define where on the filesystem to look for `graphql` files for a particular module? 
- How do we determine which modules need to import which other modules? 
- Do we need to namespace per-module? 
- How do we feed all this info into the underlying typescript codegen? Comma-separated globs seems reasonable, but how does the underlying codegen react?
- How do we keep this option from overcomplicating things for people who *aren't* using modules? While this is a huge thing for people working on enormous codebases, the vast majority of our users aren't doing this, and we need to keep onboarding for them super-straightforward. 

Anthony's ~foolishly~ bravely volunteered to take a look at this while I keep working on general code generation. I'll keep throwing notes in here with further things I think of, and @AnthonyMDev, don't hesitate to use this issue to solicit feedback.

**Comment by designatednerd** [comment]
@AnthonyMDev You're gonna have to assign yourself to this one - GitHub won't let me just assign issues to non-core team members (can't imagine why not!)

**Comment by designatednerd** [comment]
This is also somewhat related to #1083, since that will allow us to output code in relative directories for fragments and operations.

**Comment by CraigSiemens** [comment]
I just wanted to add that this is starting to become an issue with our app. Until recently, the only things that were shared between modules were our custom scalars but now we're running into a case where an enum needs to be used across two separate modules.

Heres a quick summary of what our approach was.
- There is a base API framework that contains our custom scalars, creates the `ApolloClient` with our custom `NetworkTransport` for session management.
- Each other target has it's own codegen build phase that only uses the targets GraphQL files.
- The generated swift file are modified to import our API framework to get the scalars.

**Comment by AnthonyMDev** [comment]
Good to know other people want this. I'm pretty sure I should be able to have it done by the end of April.

**Comment by AnthonyMDev** [comment]
> @AnthonyMDev You're gonna have to assign yourself to this one - GitHub won't let me just assign issues to non-core team members (can't imagine why not!)

It won't let me assign it either. Seems like a setting in your GitHub org might need to be changed to allow it. But whatever, I'll work on it either way haha.

**Comment by designatednerd** [comment]
Apparently now that you've commented on it I can assign it to you 😇

**Comment by CraigSiemens** [comment]
I was just wondering if there been any updates on this? It was originally mentioned that it'd be done in April but state of the world I'd expect things may have changed.

**Comment by designatednerd** [comment]
Yeah, I know Anthony had some unexpected stuff come up at work (story of all our lives, innit). 

We are still thinking about this, though - it's definitely something that we have a number of folks interested in but there's a *ton* of stuff in flight right now.

**Comment by michaelfransen** [comment]
We are starting to implement GraphQL into our app right now and running into a wall with this. We have a GraphQL module that has a GraphQLCLient and our custom scalar types. We do not want all our feature module queries and generated code files to be in this base GraphQL module and instead want the queries and generated code to be in the feature module they belong to. Currently, we are looking at modifying the codegen script to add `import GraphQL` to our generated code files so they have access to our custom scalar types. This does not seem ideal. I am curious if any of you have come up with a better solution that manipulating the generated code file.

**Comment by CraigSiemens** [comment]
@michaelfransen Nope, that's what we do as well. We have SPM executable that does the following.
- Run the Apollo codegen at a temp location.
- Change `public` to `internal` (the `modifier` option only works with the experimental codegen).
- Add an import to our shared module that contains the scalars.
- Adds SwiftLint disable comments to the start and end of the file.
- Only move the file to the real location if the content have changed, this prevents Xcode from thinking it has to rebuild the file every time.

**Comment by michaelfransen** [comment]
Thanks so much @CraigSiemens for describing your process.

**Comment by AnthonyMDev** [comment]
We intend on making this much easier to do with the 1.0 release! An alpha version of 1.0  will be coming to you in the new couple of weeks!

**Comment by calvincestari** [comment]
Hi 👋🏻 - this issue should be resolved in 1.0. 1.0 is currently in alpha releases with a full 1.0 release in H2 2022. Please take a look at the [latest alpha](https://github.com/apollographql/apollo-ios/releases) and let us know if this is still an issue for you.

**Comment by john-twigg-ck** [comment]
@calvincestari Can you expand? 
What mechanism/keyword impacts how code-gen across multiple modules works?

**Comment by john-twigg-ck** [comment]
@AnthonyMDev Similar question
Are there any example/tests/documentation on how we can split out queries into multiple modules?

**Comment by calvincestari** [comment]
@john-twigg-ck are you looking for a way to get the generated operation 'models' to live in separate models? If I'm understanding your question correctly then I think you're wanting the `.relative(subpath)` option for [`ApolloCodegenConfiguration.FileOutput.operations`](https://github.com/apollographql/apollo-ios/blob/release/1.0/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift#L164). This will enable you to have any number of modules each with their own queries (aka operations) and all of those generation operations will import the generated schema module which contains all the required shared code related to your schema.
