### ISSUE TITLE
Allow for custom deserialization of responses

### ISSUE THREAD

**Issue by aventurella** [apollographql/apollo-ios#1098]
It seems like this is currently not allowed, I get why because it should always be fine.

in `HTTPNetworkTransport` there is a call:

```swift
let graphQLResponse = GraphQLResponse(operation: operation, body: body)
```
https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/HTTPNetworkTransport.swift#L206

https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/GraphQLResponse.swift

That pushes the response into a `GraphQLResponse` and it can't be touched after that. Now I grant you 99% of the time that's gonna be the right thing. I have a case however where I have a legacy service that's in production where it's high risk to change the mutations response. If I had the ability to control the deserialization however this would be a non-issue; but I can't. 

The main problem comes from the Apollo lib requiring `__typename` in the response. This particular mutation doesn't provide and it errors out because of:

https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/Decoding.swift#L149-L151

I just need a way to get around that error that doesn't require altering the server response, so the it seems like doing the special case in the client is the next best thing or making that one request manually and bypassing the Apollo lib all together for.

**Comment by designatednerd** [comment]
Oof. Yeah that's...not going to be super simple to fix with our current setup. 

In the swift codegen stuff i'm working on, you'll at least be able to pass a custom subclass of `JSONDecoder` in which would allow you to bypass this kind of thing (or even manually insert a typename for that particular request), but that's not going to be ready for a bit. 

I wish I had better news for ya, but I think you may want to make that one request manually if you really don't want to touch the legacy service.

**Comment by aventurella** [comment]
That's 100% ok by me. I just wanted to be sure I wasn't missing something obvious.  Thanks for taking the time to reply!

**Comment by designatednerd** [comment]
Cool - you wanna leave this issue open or close it out?

**Comment by aventurella** [comment]
I think we can close it out. It sounds like a larger issue to entertain solving at this time and likely rare that some hits it.  If they do, they know the answer is to write around it. 😄
