### ISSUE TITLE
Incorrect graphql validation

### ISSUE THREAD

**Issue by MaximusMcCann** [apollographql/apollo-ios#11]
![image](https://cloud.githubusercontent.com/assets/1643285/19739690/91eecfd2-9b81-11e6-9ec2-0913a84f0b2a.png)

Compared to GraphiQL

```
fragment _Pie on Pie {
  __typename
  id
  ... on SystemPie {
    isActive
  }
}
```

![image](https://cloud.githubusercontent.com/assets/1643285/19739723/b81ddaae-9b81-11e6-9958-706e380a0638.png)

**Comment by MaximusMcCann** [comment]
`SystemPie` and `UserPie` are of the interface type `Pie`.

The above also works in our current implementation.

**Comment by martijnwalraven** [comment]
@MaximusMcCann: Could you include the relevant part of your schema?

`apollo-codegen` uses `graphql-js` for validation, so the results should be the same as GraphiQL. Validation rules may have changed depending on `graphql-js` versions however.

When you say this works in your current implementation, what setup are you describing?

**Comment by MaximusMcCann** [comment]
The parser is incorrectly evaluating the `SystemPie` to a `UserPie` here.

Works in the sense that graphiql has no issues with determining the `SystemPie` has the `isActive` flag.  We also query this in production and the `isActive` flag is returned when the item is a `SystemPie`.

Pie = Interface
UserPie implements Pie
SystemPie implements Pie

Unfortunately, cannot copy and paste a schema portion atm.

**Comment by martijnwalraven** [comment]
I'm not sure what could be going on here, and without something reproducible (like part of a schema) it is difficult to investigate further.

`apollo-codegen` 0.9 updates `graphql-js` to the most recent version, so that might solve your issue. Could you give that a try and report back?
