### ISSUE TITLE
Automatic persisted queries does not work with mutations

### ISSUE THREAD

**Issue by DaniilSokolyuk** [apollographql/apollo-ios#1100]
Automatic persisted queries does not work with mutations, [only for query](https://github.com/apollographql/apollo-ios/blob/ae85cb0993c17d9e41214efaa968444bc55a3814/Sources/Apollo/HTTPNetworkTransport.swift#L345).

There are no restrictions in the [documention ](https://www.apollographql.com/docs/apollo-server/performance/apq/), only 
> For full-length queries and for all mutations, Apollo Client will continue to use POST requests.

**Comment by designatednerd** [comment]
It looks like when it was initially implemented it was only implemented for queries and didn't send the APQ info for mutations. Looks like there's not a *technical* limit to this, just that we're not handling that at the moment.

My bandwidth is somewhat limited at the moment, but if you're interested in doing a PR to address this I'd be happy to take a look!

**Comment by designatednerd** [comment]
Shipped with `0.25.0`. Up for SPM and Carthage, publishing to CocoaPods trunk now.
