### ISSUE TITLE
Use of unresolved identifier Upload

### ISSUE THREAD

**Issue by jessjpj** [apollographql/apollo-ios#1103]
I have a mutation like this

`mutation signup($first_name: String, $last_name: String, $email: String, $mobile: String, $password: String, $confirm_password: String, $profile_picture: Upload) {
  register(
    first_name: $first_name
    last_name: $last_name
    email: $email
    mobile: $mobile
    password: $password
    confirm_password: $confirm_password
    profile_picture: $profile_picture
  )`

But when the API.swift file is generated, the type of profile_picture is String. How can I manage this?

`public var profile_picture: String?

  public init(first_name: String? = nil, last_name: String? = nil, email: String? = nil, mobile: String? = nil, password: String? = nil, confirm_password: String? = nil, profile_picture: String? = nil)`

**Comment by designatednerd** [comment]
Since `Upload` is a custom scalar, its underlying type is `String`. If you want the name of the custom scalar passed through, you'll need to add `--passthroughCustomScalars` to your CLI command (or set `passthroughCustomScalars` to `true` on `ApolloCodegenOptions` if you're using Swift codegen)

**Comment by jessjpj** [comment]
@designatednerd  when I do like your comment above, I am getting "Use of undeclared type Upload" inside the generated file.

**Comment by designatednerd** [comment]
Outside of the generated file, add a typealias to give the compiler a hint:  

```swift
typealias Upload = String
```

Sorry I forgot that bit as part of my original instructions!

**Comment by designatednerd** [comment]
Since this has the full instructions on how to fix it and I haven't heard back in a couple weeks, I'm going to close this out - @jessjpj if you're still having trouble feel free to reopen. Anyone with similar problems, please open a new issue. Thank you!
