### ISSUE TITLE
Can't set enableSOCKSProxy true

### ISSUE THREAD

**Issue by KonstantinEfimenko** [apollographql/apollo-ios#1104]
I can't track queries by Charles Proxy. Looks like it already was solved in Starscream https://github.com/daltoniam/Starscream/pull/423/commits/b074c6c8330527b95f1ad9169b1d9ea9eea935e1, but I can't reach this property due to internal access level of websocket in WebSocketTransport

**Comment by designatednerd** [comment]
I think we're trying to keep from directly exposing the web socket, but I can probably add a property to update this.

**Comment by designatednerd** [comment]
Hey @fassko Can you think of any major wormholes I'm opening doing this? 😇

**Comment by fassko** [comment]
@designatednerd Hmm, honestly hard to say. I'm not so proficient about proxies. :)

About Starscream and Websockets our long term plan should be using Apple's provided Websocket solution anyways.

**Comment by designatednerd** [comment]
Isn't Starscream already doing that under the hood? 

Also we support back to iOS 9 so it's gonna be a WHILE before we can drop the non-apple stuff 😭

**Comment by fassko** [comment]
Maybe it does, but I have not used it myself. Currently I won't have time to look into that cause I'm dealing with all the mess going on on the planet right now.

**Comment by designatednerd** [comment]
TOTALLY fair! My productivity has been 💩the last few weeks myself.

**Comment by designatednerd** [comment]
Shipped with `0.25.0`. Up for SPM and Carthage, publishing to CocoaPods trunk now.

**Comment by Robuske** [comment]
Hey @KonstantinEfimenko , how did you setup Charles to watch for subscriptions? I tried several different configurations, but none seem to work 😞

**Comment by designatednerd** [comment]
Heads up that this has been removed in more recent versions because Starscream itself removed support for it - I have a sneaking suspicion it may have been a bit flaky.

**Comment by Robuske** [comment]
Oh... I am using an outdated version at the moment because we had no time to upgrade =/
Is there any alternative to subscription debugging @designatednerd?

**Comment by designatednerd** [comment]
Using the debugger to pause on new items or to print new data received is probably going to be your best bet.

**Comment by DanielKrofchick** [comment]
It's a bit unclear to me from the discussion above. Can someone confirm if Apollo Subscriptions can or cannot be monitored using Charles, and if so how?

**Comment by designatednerd** [comment]
It was possible before we upgraded to Starscream 4.0. Starscream 4.0 removed support for SOCKS proxying, and so we consequently had to remove support for it as well, unfortunately.
