### ISSUE TITLE
Hasura jsonb type convertion

### ISSUE THREAD

**Issue by jhpassion0621** [apollographql/apollo-ios#1118]
When I have a `jsonb` type variable, Apollo converts this to `String`. How can I convert this json object?

**Comment by designatednerd** [comment]
I'm guessing from the description `jsonb` is a custom scalar - usually you should be able go `String` -> `Data` -> `JSONSerialization` like this: 

```swift
guard let data = jsonString.data(using: .utf8) else {
    return 
}

let jsonObject = try JSONSerialization.jsonObject(with: data, options: [])
```

And then you can cast `jsonObject` to an array or dictionary depending on what you're expecting.

**Comment by designatednerd** [comment]
Since I haven't heard anything back here in a couple weeks, I'm going to close this issue out. @jhpassion0621 please feel free to reopen if you're still having problems. Anyone else with a similar problem, please open a new issue. Thank you!

**Comment by jhpassion0621** [comment]
sorry @designatednerd 
When I run `fetch` function, it returns error because I expected to get `array` from server but codegen mapped this field as `string`

**Comment by designatednerd** [comment]
So `jsonb` isn't a direct type within GraphQL, it has to be defined, either as a type, or given what you're describing, it's much more likely defined as a [Custom Scalar](https://www.apollographql.com/docs/graphql-tools/scalars/). Custom Scalars have an underlying type that has to be one of the included scalars - in this case, it seems like the underlying type is `String`. 

Because of that, you'll need to do some manual transformation from the String to JSON - that's where [my initial suggestion](https://github.com/apollographql/apollo-ios/issues/1118#issuecomment-607947565) comes in. 

Does that help?

**Comment by jhpassion0621** [comment]
@designatednerd I got your point. But before manual transformation, I am getting error from `fetch`

**Comment by designatednerd** [comment]
Can you share the error you're getting please?

**Comment by jhpassion0621** [comment]
![Screen Shot 2020-05-08 at 11 32 48 PM](https://user-images.githubusercontent.com/7741402/81421597-448ca500-9184-11ea-917d-c6873efa465f.png)

**Comment by designatednerd** [comment]
In the generated code is `products` generated as `String` or as [String]`? It might also be helpful to see some of the raw JSON you're getting from Hasura here. 

I'll also say, it's very possible that something has changed on the GraphQL schema side. I would make sure you've downloaded the most up-to-date version of your schema. If the schema's out of date, the work that's done to generate code (basically, validating that all operations are valid vs. the schema then using that to generate code for everything that's actually used) could produce incorrect code.

**Comment by designatednerd** [comment]
@jhpassion0621 Is there anything else I can help with here, or do you mind if we close this issue out?

**Comment by designatednerd** [comment]
Since I haven't heard back in a couple weeks, I'm going to close this issue out. If you're having similar problems, please open a new issue. Thank you!
