### ISSUE TITLE
Exceptional break point issue -  passing token on Header.

### ISSUE THREAD

**Issue by alvinvgeorge** [apollographql/apollo-ios#112]
this is my StudentProfile.graphql file:

```
query StudentProfile{

me{
... on Student{

profile{
 city
}

}
}
}
```
I want to make a fetch request to get data from server. After log in, I am supposed to send token as http header with the query to Get a particular student's profile details.

This is my button action:

```
@IBAction func fetchProfileClicked(_ sender: Any) {
        
        //self.fetchStudentProfileDetails()
        
        
        let configuration: URLSessionConfiguration = .default
        configuration.httpAdditionalHeaders = ["Authorization": "Bearer \(serverToken)"]
        configuration.requestCachePolicy = .reloadIgnoringLocalCacheData // To avoid 412
        
        let url = URL(string: "http://52.88.217.19/graphql")!
        let new_apollo = ApolloClient(networkTransport: HTTPNetworkTransport(url: url, configuration: configuration))
        new_apollo.cacheKeyForObject = { $0[self.currentUsedId!] }
     
        
        new_apollo.fetch(query: StudentProfileQuery()) { (result, error) in
            
            
            if let error = error {
                NSLog("Error while fetching query: \(error.localizedDescription)");
                self.profileDetailsTextView.text =  error.localizedDescription
            }
            guard let result = result else {
                NSLog("No query result");
                self.profileDetailsTextView.text = "No query result"
                return
            }
            
            if let errors = result.errors {
                NSLog("Errors in query result: \(errors)")
                
                self.profileDetailsTextView.text =  String(describing: errors)
                
            }
            
            guard let data = result.data else {
                
                NSLog("No query result data");
                
                return
            }


        }

    }
```

These are the error I get in Xcode. Any help is appreciated.
![screen shot 2017-07-19 at 12 39 27 pm](https://user-images.githubusercontent.com/9198909/28354886-3f0fe984-6c7f-11e7-8c7f-0cc6baa2e414.png)

![screen shot 2017-07-19 at 12 39 18 pm](https://user-images.githubusercontent.com/9198909/28354892-44cc0268-6c7f-11e7-98ac-187cac4e0bf5.png)

**Comment by martijnwalraven** [comment]
> new_apollo.cacheKeyForObject = { $0[self.currentUsedId!] }

`cacheKeyForObject` should be a function that returns the cache key for any object that gets passed in. Your code tries to access a field on a passed in object with the value of `self.currentUsedId!`, but that is not a field of the object. Instead, you'll want to do something like:

> new_apollo.cacheKeyForObject = { $0["id"] }

**Comment by alvinvgeorge** [comment]
How do we pass token in http header along with graphic query on Apollo.request?

**Comment by designatednerd** [comment]
@alvinvgeorge This is tied to the issues around #37 - at this point you'd need to configure a new client with the updated header query, or just set up the headers when the client is set up. 

We'll be working in that issue around getting that working better. Is there anything else we can help with here?

**Comment by designatednerd** [comment]
The updated client that allows you to set headers in preflight is now available in 0.11.0 - I'm going to close this issue out, but please feel free to open a new issue if you're still encountering any problems using that!

**Comment by ShreyanshAlchemy** [comment]
Does anyone have suggestion for how to pass access token in a header file?
My Apollo version is latest 0.15.0

**Comment by designatednerd** [comment]
@ShreyanshAlchemy [Here's our documentation on advanced client setup](https://www.apollographql.com/docs/ios/initialization/#advanced-client-creation), including an example that shows how to add information to a request header using the [`HTTPNetworkTransportPreflightDelegate`](https://github.com/apollographql/apollo-ios/blob/0b53ff292d0af939043e2af9594627365aa859f3/Sources/Apollo/HTTPNetworkTransport.swift#L7).
