### ISSUE TITLE
ApolloSQLite.xcodeproj missing project.pbxproj when compiling with Carthage

### ISSUE THREAD

**Issue by omnidynmc** [apollographql/apollo-ios#1130]
*** Building scheme "PromiseKit" in PromiseKit.xcodeproj
*** Building scheme "RxBlocking" in Rx.xcworkspace
*** Building scheme "RxRelay" in Rx.xcworkspace
*** Building scheme "RxCocoa" in Rx.xcworkspace
*** Building scheme "RxSwift" in Rx.xcworkspace
*** Building scheme "RxTest" in Rx.xcworkspace
*** Building scheme "SQLite iOS" in SQLite.xcodeproj
*** Building scheme "Starscream" in Starscream.xcodeproj
A shell task (/usr/bin/xcrun xcodebuild -project /Users/gcarter/Development/Github/Graphite2/Carthage/Checkouts/apollo-ios/ApolloSQLite.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'ApolloSQLite.xcodeproj' from folder '/Users/gcarter/Development/Github/Graphite2/Carthage/Checkouts/apollo-ios'.
	Reason: Project /Users/gcarter/Development/Github/Graphite2/Carthage/Checkouts/apollo-ios/ApolloSQLite.xcodeproj cannot be opened because it is missing its project.pbxproj file.

Cartfile
--------

github "apollographql/apollo-ios"
github "mxcl/PromiseKit"
github "ReactiveX/RxSwift"
github "stephencelis/SQLite.swift"
github "daltoniam/Starscream"

**Comment by designatednerd** [comment]
What version are you trying to use of Apollo? There've ben some changes and the current version no longer has a separate `xcodeproj` file. It sounds like maybe your build system is trying to build based on the old version, but you have a new version checked out?

**Comment by designatednerd** [comment]
Since I haven't heard anything back here in a couple weeks, I'm going to close this out - @omnidynmc please feel free to reopen if you're still having issues. Anyone else having a similar problem, please open a new issue. Thank you!
