### ISSUE TITLE
ThreadSanitizer complains about FetchQueryOperation.cancel()

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#1146]
sometimes ThreadSanitizer complains about FetchQueryOperation.cancel(). Probably worth looking into:

![Screenshot-2020-04-11-at-12 35 53](https://user-images.githubusercontent.com/1027187/79042720-db9c2680-7bf1-11ea-9747-d3eeb710dc7d.jpg)

stepping up the stack it comes to:

<img width="932" alt="Screenshot 2020-04-11 at 12 43 09" src="https://user-images.githubusercontent.com/1027187/79042743-0a1a0180-7bf2-11ea-832e-3d23200b6892.png">

and I have feeling we were already discussing it at some point but can't recall where

btw, what's the best way reporting ThreadSanitizer errors?

**Comment by RolandasRazma** [comment]
looking at possible cool prints:

https://github.com/apollographql/apollo-ios/blob/cadc61bb443530ad45f2ba6a4008817342fca47e/Sources/Apollo/ApolloClient.swift#L284

don't you need to cancel networkTask before setting new one?

**Comment by RolandasRazma** [comment]
looks like adding that cancel solves issue, will create PR

**Comment by designatednerd** [comment]
This is a fine place to report TSAN errors but be aware you're going to get a TON of them. There's some stuff around our internal promises implmentation in particular that's got some real weird threading ideas. 

Going to be rewriting a fair amount of the culprits as part of codegen / caching stuff, will have TSAN turned on for the tests for that 😇

**Comment by designatednerd** [comment]
Thanks to @martijnwalraven's hard work, all our tests are now passing with TSAN as of [version 0.38.0](https://github.com/apollographql/apollo-ios/releases/tag/0.38.0)! If you run into TSAN issues in that version or later, please open a new issue. Thank you!
