### ISSUE TITLE
ThreadSanitizer complains about GraphQLQueryWatcher.fetch(cachePolicy:)

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#1147]
![Screenshot-2020-04-11-at-12 57 52](https://user-images.githubusercontent.com/1027187/79043062-ae9d4300-7bf4-11ea-82c8-993ad3eddae4.jpg)

**Comment by designatednerd** [comment]
See my [comment on #1146](https://github.com/apollographql/apollo-ios/issues/1146#issuecomment-612691297)

**Comment by designatednerd** [comment]
Thanks to @martijnwalraven's hard work, all our tests are now passing with TSAN as of [version 0.38.0](https://github.com/apollographql/apollo-ios/releases/tag/0.38.0)! If you run into TSAN issues in that version or later, please open a new issue. Thank you!
