### ISSUE TITLE
ThreadSanitizer complains about ApolloClient.cacheKeyForObject

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#1150]
probably connected to https://github.com/apollographql/apollo-ios/issues/1147

![Screenshot-2020-04-11-at-17 05 35](https://user-images.githubusercontent.com/1027187/79048872-e9fd3900-7c17-11ea-807c-ad72f977fb86.jpg)

**Comment by designatednerd** [comment]
See my [comment on #1146](https://github.com/apollographql/apollo-ios/issues/1146#issuecomment-612691297)

**Comment by designatednerd** [comment]
Thanks to @martijnwalraven's hard work, all our tests are now passing with TSAN as of [version 0.38.0](https://github.com/apollographql/apollo-ios/releases/tag/0.38.0)! If you run into TSAN issues in that version or later, please open a new issue. Thank you!
