### ISSUE TITLE
ThreadSanitizer complains about GraphQLQueryWatcher.fetch(cachePolicy:)

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#1151]
almost sure its same problem as https://github.com/apollographql/apollo-ios/issues/1146

GraphQLQueryWatcher.refetch() was called on main thread

<img width="1680" alt="Screenshot 2020-04-11 at 17 25 13" src="https://user-images.githubusercontent.com/1027187/79049152-a0ade900-7c19-11ea-89d1-623441740781.png">

**Comment by designatednerd** [comment]
See my [comment on #1146](https://github.com/apollographql/apollo-ios/issues/1146#issuecomment-612691297)

**Comment by designatednerd** [comment]
Thanks to @martijnwalraven's hard work, all our tests are now passing with TSAN as of [version 0.38.0](https://github.com/apollographql/apollo-ios/releases/tag/0.38.0)! If you run into TSAN issues in that version or later, please open a new issue. Thank you!
