### ISSUE TITLE
Multiple issues with error on `returnCacheDataDontFetch`

### ISSUE THREAD

**Issue by nikita-leonov** [apollographql/apollo-ios#1154]
We are using Apollo version 0.21.0 and noticed a couple of interesting issues with `returnCacheDataDontFetch` behavior, as well as documentation inconsistency:
* Documentation inconsistency: https://www.apollographql.com/docs/ios/caching/ describes existing behavior of version we use by saying "This policy will return an error if cached data is not available.". https://www.apollographql.com/docs/ios/api/Apollo/enums/CachePolicy/ saying "Return data from the cache if available, else return nil."
* Error returned is `MissingValue` error. This is a legit error in case of a schema mismatch between local schema and remote response. As `GraphQLResultError` does not contain source, it is quite difficult to understand if error coming from cache or server.

I am curious to understand what is expected behavior, as the documentation does not answer one way or another. As well as discuss the possibility to introduce unique error for empty cache to differentiate parsing/response issues and not hydrated cache issues for some specific caching policy.

**Comment by designatednerd** [comment]
Thanks for pointing out the documentation inconsistency - I think this got changed in the code and I didn't realize the docs had this in there. I'll get on that. In the future, if there's ever an inconsistency in the inline documentation vs the more hand-written documentation, please a) Let me know so I can fix it, as you've done here b) assume the inline documentation is more up to date. 

I'm not quite sure what the question is from your second bullet point - can you clarify a little bit? Thank you!

**Comment by nikita-leonov** [comment]
As I see a scenario with a non-hydrated cache is a very special type of error. While it is close to the fact that complete non-optional value is not initialized, using `MissingValue` error could be too ambiguous. Especially in scenarios where logging is on a service layer where there is no awareness about what caching strategy was used etc. We currently interpret `MissingValue` errors a scheme mismatch between client and backend or complete misbehavior of backend where value was not provided. Meanwhile, this caching policy failure trying to pretend to be the same kind of error. There could be a value in making this "not hydrated cache error" to be its type, and not `MissingValue`, so they would not mix with the rest `remote only` errors. Do you think this is something possible to change, or I haven't considered some other requirement?

**Comment by designatednerd** [comment]
One thing to keep in mind is that the way GraphQL is designed, you're not supposed to ever really have to deal with a schema mismatch because [fields should only be removed after they're deprecated and metrics show people are no longer using them](https://principledgraphql.com/agility#5-use-an-agile-approach-to-schema-development). Obviously this isn't always the case in practice because backends don't always follow that rule, but the vast majority of the time the `MissingValue` error *is* going to be, in effect, an unhydrated cache. 

I think the biggest issue I see with having a separate error is trying to keep track at a low level of what's a value that's missing because it just hasn't been hydrated yet vs what's a value that's missing due to some other error. What are you thinking in terms of how you'd distinguish those two cases?

**Comment by designatednerd** [comment]
@nikita-leonov What's your thought on my most recent response?

**Comment by nikita-leonov** [comment]
@designatednerd sorry for the late response. You are right, there is a perfect world situation and there are realties engineers need to deal with. Small companies probably cover everything by a small team or even a single engineer, while in bigger companies things may get out of order easily. These two different scenarios failing for different reasons, and probably need to be escalated to different people. In one case it is a client-side engineer, in another case, it is a backend engineer. 

As of technical implementation, I do not have a straightforward answer for this. `returnCacheDataDontFetch` and cache policies, in general, have a very shallow penetration of code in the `FetchQueryOperation`'s `start` function, and I do like this design a lot. It is great that the rest of the code is agnostic to the cache. So I see the problem you described that it is not obvious yet how to differentiate these two cases in code. I originally opened this issue as "it seems concerning, and it will be nice to try to fix it"  as I didn't have a deep dive into the code by that moment. Now I see that even if we would agree on two different errors it will be not straightforward to introduce this change. I will try to take a look into code more and find some solutions, feel free to close this issue if you do not have any other follow up questions. Thanks for all the clarifications!

**Comment by designatednerd** [comment]
OK cool, thanks for letting me know - I appreciate the feedback! I'm gonna go ahead and close this out - feel free to open a new issue and reference this one if you do think of a way around it.
