### ISSUE TITLE
[Apollo.fetch] How to cancel the query.

### ISSUE THREAD

**Issue by saudongctv** [apollographql/apollo-ios#1158]
Currently, I use: 
let fetching = apollo.fetch(...) to load the data.

For some reason, i want to cancel the request from another action outside, so I try to create the object to save the result, like:
var fetchObject: Any?

... 
let fetching = apollo.fetch(...)
fetchObject = fetching

and try to call 
fetchObject.cancel() 

My issue is i don't know what kind of data type of fetchObject should I define (Cancellable just the protocol, not data type).

Please help if you have any idea!
Thank you so much

**Comment by designatednerd** [comment]
I suspect you figured this out and that's why you closed it, but for anyone who stumbles upon this in the future, `var fetchObject` should have a type of `Cancellable?` rather than `Any?`. Even though it's a protocol you can use it to define a property.
