### ISSUE TITLE
ios ApolloCacheHeaders equivalent.

### ISSUE THREAD

**Issue by pgawlowski** [apollographql/apollo-ios#1161]
In android implementation of apollo I found sth called cache headers which allows to skip query from caching. 

Is there any equivalent to handle this in iOS implementation?

**Comment by designatednerd** [comment]
We don't have this exact mechanism but we do have a couple of cache policies, including `fetchIgnoringCacheCompletely`, which will allow you to skip the cache. Please see your options here: [https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloClient.swift#L5](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloClient.swift#L5)

**Comment by designatednerd** [comment]
I'm gonna close this out since I've provided an answer and haven't heard any follow-ups here. @pgawlowski if you need more information, please feel free to reopen. Anyone else with similar questions, please open a new issue. Thank you!
