### ISSUE TITLE
how to perform mutations that take Object as input (i.e. Post having a related user)

### ISSUE THREAD

**Issue by ilahomesick** [apollographql/apollo-ios#1165]
Hi guys, I'm creating an instagram clone for iOS to build a portfolio, I've configured and did everything necessary to integrate Apollo and I even oerformed some mutations successfully.
Now the problem is the following:
I want to create a "Post" that is a db object containing description, photo and USER, that has a relation with the same User table in the db.

This is my mutation:
`mutation createPost($photo: File!, $description: String, $user: Object!) {
  createPost(
    fields: { description: $description, photo: $photo, user: $user }
  ) {
    id
  }
}
`
When i run all the scripts and update the schema the API.swift file builds directly the "user" field in String format, how do I create the request correctly?

`Network.shared.apollo.perform(mutation:
                CreatePostMutation(photo:(graphQLResult.data?.createFile.url)!, description: "", user: "znIVnA06gd"))`

I've tried passing my user id as a string but I get the following error with no additional details:

`Network.shared.apollo.perform(mutation:
                CreatePostMutation(photo:(graphQLResult.data?.createFile.url)!, description: "", user: "znIVnA06gd"))`

Thanks for helping

**Comment by designatednerd** [comment]
I'm not sure why `$user` is of type `Object!` - is that the type you have in your schema? 

Are you able to get the mutation working in GraphiQL by passing the user's ID?

**Comment by ilahomesick** [comment]
> I'm not sure why `$user` is of type `Object!` - is that the type you have in your schema?
> 
> Are you able to get the mutation working in GraphiQL by passing the user's ID?

Hi, thanks for the quick reply.
So for the db and graphQL implementation I'm using back4app that is a site that offers backend services for apps, i started following their tutorial and I used their service for free, but this shouldn't be the cause of the problem.
Having said this, you can see, in the db the type is Pointer<User>:
<img width="149" alt="Screenshot 2020-04-20 at 18 34 06" src="https://user-images.githubusercontent.com/15572597/79776661-5a9e0700-8336-11ea-85eb-c9964c6c88cc.png">

but in the mutations editor if i set any other type, I get an error saying that the type is Object, and looking at the schema the type is set to Object as well:
<img width="1448" alt="Screenshot 2020-04-20 at 18 35 01" src="https://user-images.githubusercontent.com/15572597/79776808-90db8680-8336-11ea-9fd2-93abc17e9d51.png">
<img width="281" alt="Screenshot 2020-04-20 at 18 36 45" src="https://user-images.githubusercontent.com/15572597/79776814-93d67700-8336-11ea-91de-47a30bc8c44a.png">

**Comment by ilahomesick** [comment]
> I'm not sure why `$user` is of type `Object!` - is that the type you have in your schema?
> 
> Are you able to get the mutation working in GraphiQL by passing the user's ID?

I just tried also to query the db to retrieve the user, and passing the following string in the "user" field of the mutation:
`"{\n  \"user\" : {\n    \"username\" : \"Ilario\",\n    \"__typename\" : \"User\"\n  }\n}"`

but i still get this error:

`Result<GraphQLResponse<CreatePostMutation>, Error>
  ▿ failure : GraphQLHTTPResponseError
    ▿ body : Optional<Data>
      ▿ some : 399 bytes
        - count : 399
        ▿ pointer : 0x00007facd1643200
          - pointerValue : 140380224107008
    - response : <NSHTTPURLResponse: 0x600002829fc0> { URL: https://parseapi.back4app.com/graphql } { Status Code: 400, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Content-Length" =     (
        399
    );
    "Content-Type" =     (
        "application/json; charset=utf-8"
    );
    Date =     (
        "Mon, 20 Apr 2020 17:58:19 GMT"
    );
    Etag =     (
        "W/\"18f-n+tSGzp0UoWMRFuNKDOBP+agZzk\""
    );
    Server =     (
        "nginx/1.10.1"
    );
    Via =     (
        "1.1 aa98922692c099827cdae6a16b894745.cloudfront.net (CloudFront)"
    );
    "x-amz-cf-id" =     (
        "h93LPwK1qz5IqOomJlPuUY41QtFL7auZ0jZmg_nEwE_LBvEnjsL1vA=="
    );
    "x-amz-cf-pop" =     (
        "VIE50-C1"
    );
    "x-cache" =     (
        "Error from cloudfront"
    );
    "x-powered-by" =     (
        Express
    );
} }
    - kind : Apollo.GraphQLHTTPResponseError.ErrorKind.errorResponse
    - serializationFormat : Apollo.JSONSerializationFormat`

**Comment by designatednerd** [comment]
I'm not familiar with Back4App but it looks like they've defined `Object` as a data type somewhere. The database type and the GraphQL type aren't necessarily going to be related. I would start by looking at where `Object` is defined in that schema.

**Comment by ilahomesick** [comment]
> I'm not familiar with Back4App but it looks like they've defined `Object` as a data type somewhere. The database type and the GraphQL type aren't necessarily going to be related. I would start by looking at where `Object` is defined in that schema.
Thank you, I will investigate and eventually try to set up a db and server locally without relying on back4app, but anyway what should be the correct string that i should pass from the client for the "user" field?

**Comment by designatednerd** [comment]
It depends on the schema - if the schema just wants a string with the User ID, it should define a mutation which takes that string. If it wants a whole user object, it should define a mutation which takes a user object.

**Comment by ilahomesick** [comment]
> It depends on the schema - if the schema just wants a string with the User ID, it should define a mutation which takes that string. If it wants a whole user object, it should define a mutation which takes a user object.

Yes, as i said that's the first thing that i tried but the error is the same

**Comment by designatednerd** [comment]
Right - because the schema you're using defines it as an `Object`, which is apparently defined somewhere else in the schema, and I have no idea what it is, so I can't really give you an answer beyond "Look at what exactly an `Object` is, and use that."

**Comment by designatednerd** [comment]
@ilahomesick Is there anything else I can help with here?

**Comment by designatednerd** [comment]
Gonna close this out since I haven't heard back in a while - if you have similar questions, please open a new issue. Thank you!
