### ISSUE TITLE
Could not resolve host: install.apollographql.workers.dev

### ISSUE THREAD

**Issue by dionc** [apollographql/apollo-ios#1179]
I'm getting this error when running the latest `run-bundled-codegen.sh`:

```Checking if CLI needs to be downloaded...
Downloading zip file with the CLI...
curl: (6) Could not resolve host: install.apollographql.workers.dev
Command PhaseScriptExecution failed with a nonzero exit code
```

When I run the command manually:
```
> curl -L "https://install.apollographql.com/legacy-cli/darwin/2.27.2" -o /tmp/apollo.zip
curl: (6) Could not resolve host: install.apollographql.workers.dev
```

Possibly related to https://github.com/apollographql/apollo-ios/issues/1177

**Comment by designatednerd** [comment]
We had another report of this that turned out to be [some weirdness with the `.dev` domain](https://superuser.com/questions/1413402/i-cant-visit-websites-that-have-dev-domain) - do you mind checking to see if that might be the issue here?

**Comment by dionc** [comment]
Yes that was the problem. Thanks!
