### ISSUE TITLE
v0.6.1 fires watchers later than v0.6.0-beta.1

### ISSUE THREAD

**Issue by jync** [apollographql/apollo-ios#118]
We attempted to upgrade to `0.6.1` and noticed that watcher callbacks are substantially delayed (up to 5+ sec) compared to the `0.6.0-beta.1` release.

Has there been any changes made that might be causing these issues?

What info do I need to supply to help troubleshoot this issue?

**Comment by martijnwalraven** [comment]
Hmmm, that sounds like a concurrency issue. I suspect https://github.com/apollographql/apollo-ios/commit/39efba6abe2f498c97583506c14e43e634eedb4d may be the culprit. It should actually make things faster, but it may have introduced issues in the process.

Is there any way you could reduce this to a minimal project that demonstrates the behavior you're seeing?

**Comment by jync** [comment]
Looks to be resolved in 0.6.4 for us. I'm closing this issue.
