### ISSUE TITLE
Unable to install v0.25.0+ via SPM

### ISSUE THREAD

**Issue by vitallica** [apollographql/apollo-ios#1185]
**Intended Outcome**
Able to install the latest version of Apollo iOS via Swift Package Manager.

**Actual Outcome**
Only able to install v0.24.1 or lower. Any higher version results in an Xcode build error of:
```
The package dependency graph can not be resolved; unable to find any available tag for the following requirements:
https://github.com/apollographql/apollo-ios.git — 0.25.0..<0.26.0
```

**Reproduction**
- Add https://github.com/apollographql/apollo-ios.git to Swift Package Manager, and select 0.25.0 (or higher) with either "up to next major" or "up to next minor".
- Select "Done".
- Attempt to build the project.

**Comment by designatednerd** [comment]
What version of Xcode are you using? I know there was some stuff we added to account for changes to SPM in Swift 5.2 that might make it harder to use if you haven't upgraded to Xcode 11.4 (which includes Swift 5.2)

**Comment by vitallica** [comment]
I'm using 11.3.1 at the moment because of a bug in Xcode 11.4 that causes a crash in our app's code (for which I've submitted a bug report to Apple). Thank you for clarifying! I'll try again on a future release of 11.4.

**Comment by designatednerd** [comment]
Ah was it the Property wrapper thing? I thought they fixed that in 11.4.1, but maybe not. 11.5 is on the way soonish anyway though 🙃

**Comment by vitallica** [comment]
The one I've found occurs when subscribing to a superclass's `@Published` variable when instantiating a subclass of that superclass. It works perfectly fine on 11.3.1, but ends up with a “Fatal error: Call of deleted method” runtime error on 11.4. Spent an exceptionally long time trying to refactor my code before realising it was actually an Xcode problem! Fingers crossed for 11.5 though.

**Comment by designatednerd** [comment]
Ah yeah, since `@Published` is a property wrapper I think that might be related. 

In any case, I'll leave this up until 11.5 comes out of beta and then you can double-check.

**Comment by designatednerd** [comment]
Actually I've changed my mind about leaving this open: There isn't an issue if you're on 11.4, @vitallica just can't upgrade to 11.4. @vitallica, I'm gonna close this out, but please open a new issue if you're still running into problems once 11.5 comes out. Thank you!

**Comment by vitallica** [comment]
@designatednerd confirming that this is not a problem after upgrading to Xcode 11.5. Thank you!
