### ISSUE TITLE
What is ProtocolError in subscription and how to fix this error ? 

### ISSUE THREAD

**Issue by DiwakarThapa** [apollographql/apollo-ios#1187]
I am working on application where every **2 hrs refresh token and authorization token get changed**. I had no problem with **query** and **mutation** because the token are handled using **HTTPNetworkTransportGraphQlErrorDelegate** and **HTTPNetworkTransportPreflightDelegate** but on socket response i am receiving  **WebSocketError**
 **[WebSocketError(payload: nil, error: Optional(Starscream.WSError(type: Starscream.ErrorType.protocolError, message: "", code: 1011)), kind: Apollo.WebSocketError.ErrorKind.networkError)]**. 

Same **error was on Android too**, they fix this error by setting true on **retryOnConnectionFailure(true)**. 

How can i solve this issue in IOS ? Any suggestion or tips

**Comment by designatednerd** [comment]
Looking at the [Starscream source for `ErrorType.protocolError](https://github.com/daltoniam/Starscream/blob/master/Sources/Starscream/WebSocket.swift#L28), it looks like the data coming in from the web socket can't be parsed correctly. 

I would recommend throwing a breakpoint in to `WebSocketTransport`'s `send` method to try to see if you can get more details from the original error, but the bottom line is that data is not coming across in the format the underlying websocket is expecting.

**Comment by DiwakarThapa** [comment]
@designatednerd thanks for quick response. Throwing a breakpoint is a time consuming process for my issue because **Starscream.ErrorType.protocolError** one in half and hour or 1 hour. I cannot figure out what is causing this error.

**Comment by designatednerd** [comment]
Hm...given that time interval it sounds like maybe whatever's being sent to keep the connection alive is malformatted. I would recommend working with your backend to try and figure it out - unfortunately there's not much to be done on the Apollo side.

**Comment by designatednerd** [comment]
Since this hasn't been updated in a month I'm gonna close this out. @DiwakarThapa please feel free to reopen if you're still having issues. Anyone else with a similar problem, please open a new issue so we can troubleshoot your specific problem. Thank you!

**Comment by zohairhadi** [comment]
Having this problem still.
I've subscribed to a socket like so:


```
self.subscription = self.socketClient.subscribe(subscription: subscription) { result in
	switch result {
	case .success(let response):
		// Process and send the response
		guard let data = try? result.get().data else { return }
	case .failure(let error):
		// Handle the error
		completion(.failure(error))
	}
}
```

But as soon as I subscribe I get
ApolloWebSocket.WebSocket.WSError.ErrorType.protocolError, message: \"terminated\", code: 1000)"

**Comment by zohairhadi** [comment]
Yep, its working now
