### ISSUE TITLE
Cannot downcast from 'Any' error in generated API.swift file

### ISSUE THREAD

**Issue by TancredeFx** [apollographql/apollo-ios#119]
Using the 0.0.3 version, the generated API.swift file, throws the 2 following errors. Was not the case when using Apollo-iOS 0.5.6.

- API.swift:2834:49: Cannot downcast from 'Any' to a more optional type '[Snapshot?]?'
- API.swift:2837:64: Value of optional type 'GetAccountQuery.Data.Account.Account.Patient.Observation?' not unwrapped; did you mean to use '!' or '?'?

[API.swift.txt](https://github.com/apollographql/apollo-ios/files/1184854/API.swift.txt)
[schema.json.txt](https://github.com/apollographql/apollo-ios/files/1184855/schema.json.txt)

<img width="1153" alt="error" src="https://user-images.githubusercontent.com/30191102/28743895-9ccd15de-742b-11e7-98de-4aef7e14fd11.png">

**Comment by martijnwalraven** [comment]
What versions of `apollo-codegen` and Apollo iOS are you running?

**Comment by martijnwalraven** [comment]
I've been able to confirm this is a bug related to the way codegen handles `@skip`/`@include`. I hope to have a fix for this out soon.

**Comment by TancredeFx** [comment]
apollo-ios: 0.6.2
apollo-codegen: 0.16.1

**Comment by martijnwalraven** [comment]
I just released Apollo iOS 0.7.0-alpha.1, which uses the updated codegen and should support `@skip`/`@include`. There have been quite a few changes to the codegen, so there might be slight differences in the generated code (especially for type conditions). That's one of the reasons I've labeled it alpha for now. Would be great if people could try it out and provide feedback!

**Comment by martijnwalraven** [comment]
Closing this so we can have a single issue for discussion of `@skip`/`@include` support: https://github.com/apollographql/apollo-ios/issues/74
