### ISSUE TITLE
Crash on ApolloClient init

### ISSUE THREAD

**Issue by victormihaita** [apollographql/apollo-ios#1190]
It looks like the app is still crashing with the latest version of the Pod (0.27.1) I get `signal SIGABRT`. This is the initialisation part that I use. Is crashing on the last line..:

```
let configuration = URLSessionConfiguration.default
configuration.httpAdditionalHeaders = headers

let transport = HTTPNetworkTransport(
    url: AppConfiguration.current.apiURL,
    client: URLSessionClient(sessionConfiguration: configuration))

apollo = ApolloClient(networkTransport: transport)
```

**Comment by designatednerd** [comment]
I haven't seen anything like this, so I'm going to need a little more context here: 

- Usually a `SIGABRT` prints out a stack trace in the console, do you mind sharing that stack trace and any error message that printed with it?
- Where is `apollo` being held on to here? Is it a property of whatever class you're setting this up in?

**Comment by victormihaita** [comment]
I don't get any stack trace in the console and I init the Apollo Client in a singleton.
Is crashing instantly on launching the app on simulator or phone. The only change made was updating the pod and changing how I init the transport property..(you can compare the above version with the old implementation posted below).
If I use version 0.26.0 is working correctly with the code below:

```
let configuration = URLSessionConfiguration.default
configuration.httpAdditionalHeaders = headers

let transport = HTTPNetworkTransport(
    url: AppConfiguration.current.apiURL,
    session: URLSession(configuration: configuration))

apollo = ApolloClient(networkTransport: transport)
```

**Comment by designatednerd** [comment]
Yeah I've got nothing - I also haven't seen any other reports of this. Can you try cleaning the build folder and/or [the derived data dance](http://deriveddata.dance) and see if either of them resolves this for you?

**Comment by designatednerd** [comment]
@victormihaita Were you ever able to resolve this issue?

**Comment by victormihaita** [comment]
The [dance](http://deriveddata.dance) worked. Thanks and sorry for the late reply :)
