### ISSUE TITLE
0.20.1 CLI URL Broken

### ISSUE THREAD

**Issue by T-Pham** [apollographql/apollo-ios#1198]
`https://install.apollographql.com/legacy-cli/darwin/2.21.0` is returning HTTP 500.

On Xcode:
```
Checking if CLI needs to be downloaded...
Downloading zip file with the CLI...
curl: (22) The requested URL returned error: 500 
```

I wonder if we can find out a more stable way to distribute the CLI. I know the assumption is that we would rarely have to download the CLI because it is cached, but in reality, we have had this problem [again](https://github.com/apollographql/apollo-ios/issues/962) and [again](https://github.com/apollographql/apollo-ios/issues/1177).

**Comment by mitchellporter** [comment]
+1 Experiencing the same issue.

**Comment by designatednerd** [comment]
We recently moved from Circle assets to Github based assets (behind a CDN) to address this specific issue, although we apparently did it right when Github's decided to have a bad couple of weeks. 

I was just able to download the URL you provided, can you please retry? If you are still not able to download, can you please share: 
- Where in the world are you? 
- Have you had any issues with `.dev` domains in the past (there's a redirect under the hood to a `.dev` domain? 
- Are you behind a corporate firewall?

**Comment by mitchellporter** [comment]
@designatednerd Thanks for the quick response. First time experiencing this. Lasted about 20minutes or so, but all is well and builds are working again now.

Location: Seattle, WA, USA
Haven't had any issues with .dev domains
Not behind a corporate firewall

**Comment by T-Pham** [comment]
Thanks for looking into this @designatednerd.
It was a blip. I can download the CLI now.

**Comment by designatednerd** [comment]
Great, thank you.

**Comment by michaelbina** [comment]
I'm see this problem now as well.  I don't think it's solved.

**Comment by designatednerd** [comment]
Just checked and https://install.apollographql.com/legacy-cli/darwin/2.21.0 is downloading fine here - can you please retry @michaelbina? 

FWIW we are working on moving things to a non-github storage option since it seems like Github's artifact storage is flaky as hell.

**Comment by michaelbina** [comment]
Sorry.  That was my fault.  I hadn't been on the latest version.

**Comment by designatednerd** [comment]
`0.20.1` should still work though - I specifically added that patch version (along with 7 others) for people who can't upgrade to latest.

**Comment by michaelbina** [comment]
The pod file int he project I was working on had "  pod 'Apollo', '~> 0.20'", so I guess I just missed it by 0.1 :-)
