### ISSUE TITLE
Filter from Apollo Cache

### ISSUE THREAD

**Issue by vishaldroisys** [apollographql/apollo-ios#1203]
Hello,

We have GraphQL query and we stored query response in Apollo cache.

now we want to filter some data from this cache and our filter criteria are dynamic.

Thanks in advanced.

**Comment by designatednerd** [comment]
Hi! There are a couple options: 

- You can pull the data as is from the cache and filter it after it comes out. This is pretty straightforward if you use the `returnCacheDataDontFetch` cache policy when you make your call through `ApolloClient`. 
- Have you taken a look at the [Direct Cache Access section of our documentation](https://www.apollographql.com/docs/ios/caching/#direct-cache-access)? You should be able to use the blocks within that in order to filter results. This is more complex but it does allow you to do the filtering at the point where the cache is accessed.

**Comment by vishaldroisys** [comment]
Supposed in my cache, there are bundles of records(about to 10-12 lacs) then it will be fine??
i am talking about cache only.

Thanks in advanced.

**Comment by designatednerd** [comment]
I'm not sure what you mean by that. Can you explain in a bit more detail?

**Comment by vishaldroisys** [comment]
Using ApolloClient, we fetched records approx 10-12 Lac(Using Paging) and stored in cache. now we stop the internet connection. 

In offline mode, we have to filter data from cache based on dynamic fields.

now got it??

**Comment by designatednerd** [comment]
I'm not sure what "Lac" is short for, but if you're offline and using the `returnCacheDataDontFetch` cache policy, that should fetch what's in your cache for you.

**Comment by vishaldroisys** [comment]
lac(Lakh) in terms of (100000).
yes we are using returnCacheDataDontFetch policy. but fetching thousands of records from cache then filtered data accordingly is fine approach ro not??

**Comment by designatednerd** [comment]
Ahhh, ok that makes more sense, thank you - I was vaguely familiar with `lakh` as a counting unit but not `lac` as an abbreviation for it. 

The answer of "is this an OK approach?" is basically "It depends on whether the performance is sufficient for what you need." It's not necessarily *just* that there are 100,000 records or more - are those records large or small? How many dependent fields are they fetching? There are some cases where fetching 100k records at a time may be efficient, and there are some cases where even fetching 50 records at a time might not be terribly efficient.

If you're able to get reasonable performance using just the `client` call, great. If not, you probably need to filter using the `withinReadTransaction` block.

**Comment by designatednerd** [comment]
Any further questions here, or do you mind if we close this out?

**Comment by designatednerd** [comment]
I haven't heard back in a while, so I'm going to go ahead and close this out. If you're having similar problems, please open a new issue. Thank you!
