### ISSUE TITLE
Incorrect SQLiteNormalizedCache initializer parameter type

### ISSUE THREAD

**Issue by bryanrahn** [apollographql/apollo-ios#1204]
The `SQLiteNormalizedCache` initializer takes a `URL` as a parameter, and passes the URL to the `Connection(.uri(fileURL.absoluteString), readOnly: false)` initializer. However, `Connection(.uri(String))` requires the enums associated value to be a URI filename or path (not a file URL). `fileURL.absoluteString` returns an absolute URL string, *not* a path, which leads to a `SQLITE_CANTOPEN` error.

Possible fixes include:

1. Change the `SQLiteNormalizedCache` `URL` parameter to be a `String` called path
2. Change `fileURL.absoluteString` to `fileURL.path` within `SQLiteNormalizedCache(fileURL: , shouldVacuumOnClear:)`

**Comment by designatednerd** [comment]
I have to say, I'm slightly amazed this worked at all if that's true on all platforms. Can you confirm what version of Apollo you're on and what platform/version you're using it on?

**Comment by bryanrahn** [comment]
> I have to say, I'm slightly amazed this worked at all if that's true on all platforms. Can you confirm what version of Apollo you're on and what platform/version you're using it on?

I can (and I'm sure other did as well) work around it with creating a path URL from the file URL like: `let filePathURL = URL(string: fileURL.path)`

<img width="202" alt="image" src="https://user-images.githubusercontent.com/729269/81860579-8fb00a80-952c-11ea-8796-dc1ca8df26ac.png">

**Comment by designatednerd** [comment]
Ah so to be clear, it works if you pass it in using `URL(string:)` rather than `URL(fileURLWithPath:)`?

**Comment by bryanrahn** [comment]
In order for `SQLiteNormalizedCache` to initialize properly, the URL must *not* have a `file://` prefix. In my case, we're using `FileManager` and `appendingPathComponent()` to create URLs, which have the `file://` prefix. If you use the aforementioned api, you must create a new URL from the `path` by using calling `URL(string: fileURL.path)`.

This is why I suggested:

> Possible fixes include:
> 
> 1. Change the SQLiteNormalizedCache URL parameter to be a String called path
> 2. Change fileURL.absoluteString to fileURL.path within SQLiteNormalizedCache(fileURL: , shouldVacuumOnClear:)

**Comment by designatednerd** [comment]
So we're using a similar method with `appendingPathComponent` in [our SQLite test helper to generate a temporary SQLite file](https://github.com/apollographql/apollo-ios/blob/master/Sources/ApolloSQLiteTestSupport/TestCacheProvider.swift#L24), and we have not encountered this problem with everything set up as is. If the issue were pure "File URL vs not file URL", this wouldn't work at all, which is why I'm reluctant to just apply the fix you've suggested. 

One thing I noticed when I pulled that code up to reference it: We're also creating all intermediate directories between the temporary directory and the SQLite file. Is it possible that there's an intermediate directory in your path that's not been created?

**Comment by bryanrahn** [comment]
`public static func temporarySQLiteFileURL() -> URL` will produce the same `file://` prefixed URL. 
```
let temporaryDirectoryURL = URL(fileURLWithPath: NSTemporaryDirectory())
let folder = temporaryDirectoryURL.appendingPathComponent(UUID().uuidString)
try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
let filePathURL = folder.appendingPathComponent("db.sqlite3")
let cache = try SQLiteNormalizedCache(fileURL: filePathURL)
```

The above code fails.

IMO, it doesn't make any sense to pass in a URL, that could be a file url with the prefix `file://`, since `SQLiteNormalizedCache(fileURL:)` is just a proxy to `Connection(.uri(String))`, which requires a URI formatted path string, not a URL.

**Comment by designatednerd** [comment]
It's *very* odd that's failing for you but succeeding in the tests - is it giving the same `SQLITE_CANTOPEN` error?

**Comment by bryanrahn** [comment]
> It's _very_ odd that's failing for you but succeeding in the tests - is it giving the same `SQLITE_CANTOPEN` error?

Correct. I mentioned this when I opened up this issue. `SQLITE_CANTOPEN`, error code 14.

**Comment by designatednerd** [comment]
Yes, I was asking if you are seeing that same error when trying to use the temporary directory or if you were seeing a different error. Thank you for clarifying that it is the same error.

So on my machine, I am able to get this to run as is. [Here's a zip of a database that gets created during our SQLite tests](https://github.com/apollographql/apollo-ios/files/4631345/db.sqlite3.zip).  You can use [this free SQLite browser to inspect the contents](https://sqlitebrowser.org/dl/). This file was created using a file URL that starts with `file:///`. 

Taking a look at [the documentation linked from SQLite.swift's `uri` type](https://github.com/stephencelis/SQLite.swift/blob/master/Sources/SQLite/Core/Connection.swift#L53), `URI` is noted as specifically expecting the `file` prefix in [part 3 here](https://www.sqlite.org/uri.html). 

Can you please answer a few questions to try and narrow down what might be happening here:
 
- What version of macOS are you running? 
- What version of Xcode are you running? 
- What version of Swift are you using?
- What version of what operating system are you attempting to execute this code on? 
- Are you logged into an admin account on your machine, or a non-admin account? 
- Are you able to reproduce this failure on more than one machine? 

Thank you!

**Comment by bryanrahn** [comment]
> Yes, I was asking if you are seeing that same error when trying to use the temporary directory or if you were seeing a different error. Thank you for clarifying that it is the same error.
> 
> So on my machine, I am able to get this to run as is. [Here's a zip of a database that gets created during our SQLite tests](https://github.com/apollographql/apollo-ios/files/4631345/db.sqlite3.zip). You can use [this free SQLite browser to inspect the contents](https://sqlitebrowser.org/dl/). This file was created using a file URL that starts with `file:///`.
> 
> Taking a look at [the documentation linked from SQLite.swift's `uri` type](https://github.com/stephencelis/SQLite.swift/blob/master/Sources/SQLite/Core/Connection.swift#L53), `URI` is noted as specifically expecting the `file` prefix in [part 3 here](https://www.sqlite.org/uri.html).
> 
> Can you please answer a few questions to try and narrow down what might be happening here:
> 
> * What version of macOS are you running?
> * What version of Xcode are you running?
> * What version of Swift are you using?
> * What version of what operating system are you attempting to execute this code on?
> * Are you logged into an admin account on your machine, or a non-admin account?
> * Are you able to reproduce this failure on more than one machine?
> 
> Thank you!

macOS: 10.15.4
Xcode: 11.4.1 (11E503a)
Swift 5
iPhone 11 Pro Max simulator
Admin account
I don't have another machine handy to test on.
Current projects dependencies:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/729269/82064453-6610f380-9692-11ea-813f-fc615b96905d.png">
In my project, I added some tests just for sanity.

```
    // Copied directly from https://github.com/stephencelis/SQLite.swift/blob/ed8f603f856e9f1f4adb76b63b7234547257ec5a/Tests/SQLiteTests/ConnectionTests.swift#L39
    func test_init_withURI_returnsURIConnection() {
        let path = "\(NSTemporaryDirectory())/SQLite.swift Tests.sqlite3"
        let db = try? Connection(.uri(path))
        XCTAssertEqual("\(NSTemporaryDirectory())/SQLite.swift Tests.sqlite3", db?.description)
    }

    func test_init_withAbsoluteStringURI_returnsURIConnection() {
        let temporaryDirectoryURL = URL(fileURLWithPath: NSTemporaryDirectory())
        let folder = temporaryDirectoryURL.appendingPathComponent(UUID().uuidString)
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let filePathURL = folder.appendingPathComponent("db.sqlite3")
        // Pass `filePathURL.absoluteString` since SQLiteNormalizedCache(fileURL:) does this same thing
        let db = try? Connection(.uri(filePathURL.absoluteString))
        XCTAssertEqual("\(NSTemporaryDirectory())/SQLite.swift Tests.sqlite3", db?.description)
    }

    func testApolloSQLite() {
        let temporaryDirectoryURL = URL(fileURLWithPath: NSTemporaryDirectory())
        let folder = temporaryDirectoryURL.appendingPathComponent(UUID().uuidString)
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let filePathURL = folder.appendingPathComponent("db.sqlite3")
        let cache = try? SQLiteNormalizedCache(fileURL: filePathURL)
        XCTAssertNotNil(cache)
    }
```

`test_init_withURI_returnsURIConnection` passes.
`test_init_withAbsoluteStringURI_returnsURIConnection` fails.
`testApolloSQLite` fails.

**Comment by designatednerd** [comment]
I copied and pasted your tests into the [`CachePersistenceTests`](https://github.com/apollographql/apollo-ios/blob/master/Tests/ApolloSQLiteTests/CachePersistenceTests.swift) file, imported `SQLite` and ran those three tests on an iPhone 11 Pro sim running 13.4.1. When I figured out the directory path was wrong on the 2nd test and fixed it, all three passed. In every case, `db` was non-nil. 

In the `test_init_withAbsoluteStringURI_returnsURIConnection` test you're comparing `TemporaryDirectory/UUID/db.sqlite` to `TemporaryDirectory/SQLite.swift Tests.sqlite3`, which is definitely not going to pass since the path is tied to the first test instead of how you're creating the path in that test. 

When I pulled out the UUID as a variable and changed the `XCTAssertEqual` to:

```swift
XCTAssertEqual("\(NSTemporaryDirectory())\(uuid)/db.sqlite3", db?.description)
```

then it passed on my end. If you make that same change on your end, what happens?

**Comment by bryanrahn** [comment]
Apologies; I had pasted an old copy of those tests. The second two tests should've just been checking `XCTAssertNotNil(db)`.
```
    // Copied directly from https://github.com/stephencelis/SQLite.swift/blob/ed8f603f856e9f1f4adb76b63b7234547257ec5a/Tests/SQLiteTests/ConnectionTests.swift#L39
    func test_init_withURI_returnsURIConnection() {
        let path = "\(NSTemporaryDirectory())/SQLite.swift Tests.sqlite3"
        let db = try? Connection(.uri(path))
        XCTAssertEqual("\(NSTemporaryDirectory())/SQLite.swift Tests.sqlite3", db?.description)
    }

    func test_init_withAbsoluteStringURI_returnsURIConnection() {
        let temporaryDirectoryURL = URL(fileURLWithPath: NSTemporaryDirectory())
        let folder = temporaryDirectoryURL.appendingPathComponent(UUID().uuidString)
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let filePathURL = folder.appendingPathComponent("db.sqlite3")
        // Pass `filePathURL.absoluteString` since SQLiteNormalizedCache(fileURL:) does this same thing
        let db = try? Connection(.uri(filePathURL.absoluteString))
        XCTAssertNotNil(db)
    }

    func testApolloSQLite() {
        let temporaryDirectoryURL = URL(fileURLWithPath: NSTemporaryDirectory())
        let folder = temporaryDirectoryURL.appendingPathComponent(UUID().uuidString)
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let filePathURL = folder.appendingPathComponent("db.sqlite3")
        let cache = try? SQLiteNormalizedCache(fileURL: filePathURL)
        XCTAssertNotNil(cache)
    }
```

And the last two tests fail every time.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/729269/82087251-58b93080-96b5-11ea-9772-ac7775011c02.png">

**Comment by designatednerd** [comment]
Yeah - i definitely had `XCTAssertNotNil` passing on both of those. 

What happens if you check out this repo, open `Apollo.xcodeproj`, and try to run the `ApolloSQLite` scheme's tests? 

Also, would you be willing to send me a copy of the project where this is failing for you? ellen at apollographql dot com if you are.

**Comment by designatednerd** [comment]
Hi @bryanrahn I wanted to follow up here and see if you're still running into this problem or if you can send along the project that's not working.

**Comment by designatednerd** [comment]
Since I haven't heard back in several weeks and have not been able to reproduce this issue, I'm going to close this out. @bryanrahn Feel free to reopen if you have updates. Anyone else with a similar problem, please open a new issue. Thank you!
