### ISSUE TITLE
Code generation class names defined by the query name

### ISSUE THREAD

**Issue by bryanrahn** [apollographql/apollo-ios#1207]
If I want to define my query as query MyAlerts_iOS { ... } (so we can better track specific query failures on the server logs), Codegen creates the proper operationDefinition, but the class name it generates is MyAlertsIOsQuery. It'd be great if it followed something closer name wise.

**Comment by designatednerd** [comment]
Definitely looking at having more respect for capitalization and I *think* we should be able to do underscores too in the Swift Codegen. Adding to the project.

**Comment by calvincestari** [comment]
Hi 👋🏻 - we've partially addressed this in the new 1.x codegen. We respect the name of the given operation but will always uppercase the first letter and always suffix it with Query/Mutation/Subscription. If this isn't suitable please let us know and we can discuss. Please check out the new [1.0 alpha releases](https://github.com/apollographql/apollo-ios/releases) if you haven't already.
