### ISSUE TITLE
[Apollo v 0.27.1][tvOS] Extra argument 'session' in call

### ISSUE THREAD

**Issue by WCChimiiz** [apollographql/apollo-ios#1211]
```
class Network {
    static let shared = Network()
    let apollo: ApolloClient = {
        let configuration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = [
            "x-api-key": CLIENT_AUTHORIZATION
        ]

        let url = URL(string: CLIENT_ENDPOINT)!
        return ApolloClient(
            networkTransport: HTTPNetworkTransport( url: url,
                                                    session: URLSession(configuration: configuration))
        )
    }()
}
```

I got error when I build "Extra argument 'session' in call"

<img width="1071" alt="Screen Shot 2563-05-18 at 18 16 39" src="https://user-images.githubusercontent.com/35053188/82207578-41d44180-9934-11ea-9a72-590536b5caaf.png">

**Comment by designatednerd** [comment]
Hi @WCChimiiz - please see the [release notes for 0.27.0](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md#v0270) for details about some of the changes that landed there and a link to a migration guide - the `extra argument` error is trying to tell you that the `session` parameter no longer exists.
