### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by orim55353** [apollographql/apollo-ios#1212]
Hey, im using apollo for about 6 months now, about 2 weeks ago somthing strange happened with the apollo package and the solution i found was to mark the run script only when installing, and it worked just fine until i needed to use new queries.

obviously when im building the project the api file doesnt change, so when im trying to archive it i get the result of:

Checking if CLI needs to be downloaded...
Downloading zip file with the CLI...
curl: (22) The requested URL returned error: 404 Not Found
Command PhaseScriptExecution failed with a nonzero exit code

Im really hopeless at this point, cant figure out the solution.
Im using apollo as a swift dependecy, my xcode version is 11.3.1.

thanks for any help.

**Comment by designatednerd** [comment]
Hi, what version of the library are you using? You may need to update to a new patch version, please see pinned issue #1177.

**Comment by orim55353** [comment]
@designatednerd hi, ive managed to install the pods and make it work, but now im facing a new issue, when im trying to fetch a query im getting this response: 
▿ Result<GraphQLResult<Data>, Error>
  ▿ success : GraphQLResult<Data>
    - data : nil
    ▿ errors : Optional<Array<GraphQLError>>
      ▿ some : 1 element
        ▿ 0 : GraphQL Error
          ▿ object : 4 elements
            ▿ 0 : 2 elements
              - key : "path"
              ▿ value : 1 element
                - 0 : foldersTree
            ▿ 1 : 2 elements
              - key : "extensions"
              ▿ value : 2 elements
                ▿ 0 : 2 elements
                  - key : exception
                  ▿ value : 4 elements
                    ▿ 0 : 2 elements
                      - key : status
                      - value : 401
                    ▿ 1 : 2 elements
                      - key : message
                      ▿ value : 2 elements
                        ▿ 0 : 2 elements
                          - key : error
                          - value : Unauthorized
                        ▿ 1 : 2 elements
                          - key : statusCode
                          - value : 401
                    ▿ 2 : 2 elements
                      - key : stacktrace
                      ▿ value : 11 elements
                        - 0 : Error: [object Object]
                        - 1 :     at GqlAuthGuard.handleRequest (/home/ubuntu/server/node_modules/@nestjs/passport/dist/auth.guard.js:63:30)
                        - 2 :     at /home/ubuntu/server/node_modules/@nestjs/passport/dist/auth.guard.js:47:120
                        - 3 :     at /home/ubuntu/server/node_modules/@nestjs/passport/dist/auth.guard.js:78:24
                        - 4 :     at allFailed (/home/ubuntu/server/node_modules/passport/lib/middleware/authenticate.js:107:18)
                        - 5 :     at attempt (/home/ubuntu/server/node_modules/passport/lib/middleware/authenticate.js:180:28)
                        - 6 :     at JwtStrategy.strategy.fail (/home/ubuntu/server/node_modules/passport/lib/middleware/authenticate.js:297:9)
                        - 7 :     at JwtStrategy.authenticate (/home/ubuntu/server/node_modules/passport-jwt/lib/strategy.js:96:21)
                        - 8 :     at attempt (/home/ubuntu/server/node_modules/passport/lib/middleware/authenticate.js:361:16)
                        - 9 :     at authenticate (/home/ubuntu/server/node_modules/passport/lib/middleware/authenticate.js:362:7)
                        - 10 :     at /home/ubuntu/server/node_modules/@nestjs/passport/dist/auth.guard.js:83:3
                    ▿ 3 : 2 elements
                      - key : response
                      ▿ value : 2 elements
                        ▿ 0 : 2 elements
                          - key : error
                          - value : Unauthorized
                        ▿ 1 : 2 elements
                          - key : statusCode
                          - value : 401
                ▿ 1 : 2 elements
                  - key : code
                  - value : INTERNAL_SERVER_ERROR
            ▿ 2 : 2 elements
              - key : "message"
              ▿ value : 2 elements
                ▿ 0 : 2 elements
                  - key : error
                  - value : Unauthorized
                ▿ 1 : 2 elements
                  - key : statusCode
                  - value : 401
            ▿ 3 : 2 elements
              - key : "locations"
              ▿ value : 1 element
                ▿ 0 : 2 elements
                  ▿ 0 : 2 elements
                    - key : line
                    - value : 2
                  ▿ 1 : 2 elements
                    - key : column
                    - value : 3
    - source : Apollo.GraphQLResult<V_Plans.FoldersTreeQuery.Data>.Source.server
    - dependentKeys : nil

Im certain its not and issue with the server because on older version of the app it works great

**Comment by designatednerd** [comment]
Hey Orim - the status code 401 looks like an `Unauthorized` status code. I would double-check that you are passing any authorization tokens or API keys you need either through a `URLSessionConfiguration` when initializing the `URLSessionClient`, or using a delegate. 

If that's still not working, can you please open a separate issue? I'm going to close this issue out since you were able to get everything building, and I'd like to separate build issues from runtime issues. Thanks!
