### ISSUE TITLE
ApolloCodegenLib doesn't include an equivalent option for customScalarsPrefix

### ISSUE THREAD

**Issue by CraigSiemens** [apollographql/apollo-ios#1214]
I'm trying out the codeine using SPM and I've found that the flag `--customScalarsPrefix` that we've been using is not available. 

We use the `--passthroughCustomScalars` flag to define out own types for the scalars, and `--customScalarsPrefix="Scalar."` to prevent name conflicts between scalars and Foundation types. For example `Scalar.Date` is using a custom struct for year, month, day and shouldn't conflict with `Foundation.Date`

**Comment by designatednerd** [comment]
Ah yeah, will get that added in

**Comment by designatednerd** [comment]
@CraigSiemens PR #1215 is up
