### ISSUE TITLE
Apollo generates two different types with the same name

### ISSUE THREAD

**Issue by RomanTysiachnik** [apollographql/apollo-ios#1219]
# Apollo generates two different types with the same name
### Intended outcome: 
What I have is the next query:
```graphql
query {
  languages {
    code
    name
  }
}
```
Languages has a type named `LanguageItem`, and code has an enum type `Language`.
I expect to generate the next structure:
```swift
struct LanguageItem {
  static let possibleTypes: [String] = ["LanguageItem"]
  var code: Language { ... }
  var name: String { ... }
}

enum Language {
 case eng = "ENG"
 ...
}
```
### Actual outcome: 
And here is the result
```swift
struct Language {
  static let possibleTypes: [String] = ["LanguageItem"]
  var code: Language { ... }
  var name: String { ... }
}

enum Language {
 case eng = "ENG"
 ...
}
```

Obviously, we get a compile error because of two types with the same name.

### Assumption
I feel that you have some logic that cuts that `Item` name from the type. I've checked with another type that has `Item` in the end and Apollo behaves the same way, which is kinda not what we expect.

**Comment by designatednerd** [comment]
ARGH, yeah, we do in the typescript stuff, and there's not really a super awesome workaround for it. I'm sorry, this is definitely something I'm working on making wayyyyy less aggressive in the Swift codegen but that's still very much WIP. 

Sorry, wish I had a better answer for you.

**Comment by RomanTysiachnik** [comment]
Is there any way to add some kinda toggle in codegen options to disable that behavior? To have the naming 1:1 to the scheme?

That thing really ruined my day 😁

**Comment by designatednerd** [comment]
I bet it did - unfortunately, there isn't a toggle on it. I sorely wish there was.

**Comment by RomanTysiachnik** [comment]
Is it possible to add one, or it is something that can't be extracted from the entire parsing logic?

**Comment by designatednerd** [comment]
The last time I looked it was really hard, but I'm moderately less shit at typescript now, so I'm looking into it.

**Comment by designatednerd** [comment]
So I checked in with colleagues and the way that our codegen presently works, it's the name of the field that actually generates the name of the type within a nested query, rather than the actual type itself. This is where our good friend Singularization comes in and hits `languages` with a hammer and turns it into `language`. 

A suggested workaround is to use an alias like this: 

```graphql
query {
  languageItems: languages {
    code
    name
  }
}
```

That would still get hammered by singularization, but to `LanguageItem` instead of to `Language`.

**Comment by RomanTysiachnik** [comment]
Yeah. I thought the same way, cz changing the type name on the backend didn't work :)

That's something that should be mentioned somewhere somehow cz it may take time for people to find that thread ))

**Comment by designatednerd** [comment]
Yeah I think I may add something in the tutorial about it because it'd help disambiguate something. 

Mind if we close this issue out though?

**Comment by designatednerd** [comment]
Since this has a solution and I haven't heard back for over a week, I'm going to go ahead and close this out. If you're having similar problems, please feel free to open a new issue. Thank you!
