### ISSUE TITLE
This input can only support **one** of the following types

### ISSUE THREAD

**Issue by weapon3042** [apollographql/apollo-ios#122]
Apollo codeGen 0.16.2 is generating the following swift code:

 ``` 
/// This input can only support **one** of the following types:   
 [TimeOffTimeBasedSummary, TimeOffAmountBasedSummary]
``` 

Swift Compilation error: 
 ```Expressions are not allowed at the top level ```

**Comment by martijnwalraven** [comment]
Is this an input type? Could you post the relevant part of the schema?

**Comment by weapon3042** [comment]
The relevant schema and graph are pretty complex, and Apollo iOS codeGen generates a class (API.swift) of 100K lines of swift codes, which includes the above error. Thus we will try to take care of this mutation without Apollo and close this issue for now.
