### ISSUE TITLE
RFC: Modularized GraphQL Code Generation Output

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#1223]
| Status        | Proposed       |
:-------------- |:---------------------------------------------------- |
| **Author(s)** | Anthony Miller ([AnthonyMDev@gmail.com](mailto:AnthonyMDev@gmail.com)) |
| **Updated**   | 2020-05-26 |

# Objective

To support advanced usage of Apollo for modular code bases in a format this is highly configurable and agnostic of the dependency management and build system used. This should be achieved while maintaining the streamlined process for the default usage in unified code bases.

In order to support advanced use cases, the Apollo Code Generation must be able to generate code across modules and output generated files to multiple directories. Additionally code generation must be aware of module structure so that shared types (enums & input structs) can be intelligently imported into the necessary modules.

# Motivation

Many large projects and applications utilize a modular architecture, breaking their application code into multiple, small modules. Those modules may be located in a monorepo or broken out over multiple repositories. Projects may be organized in a variety of structures and use a number of different dependency management systems (SPM, Cocoapods, Carthage, etc.).

Apollo aims to be ready for usage in every GraphQL project, big or small. Large enterprise solutions are being built using GraphQL and the Apollo Server, and they need support for advanced project structure and modularization to succeed.

## User Benefit

Both AirBnB and Salesforce are using Apollo GraphQL and have expressed the need to further utilize Apollo Code Generation with modular code bases.

# Assumptions

In order for code generation to continue to work properly in a modular code base, the following assumptions are made:

* All modules depend upon the same GraphQL schema.
    * When a schema is changed, generated files will be overwritten to use the schema file provided to the code generation tool.

# Design Proposal

In order to use modular code generation, a `ApolloConfig.json` files can be added to directories that include`.graphql` files to configure the output of generated code.

Modular code generation can occur either over multiple modules at one time or over individual modules one at a time. Multiple modules can be hosted in a single or multiple repositories. But once they are fetched into a local file system, code generation can be performed over all of them simultaneously. A default config file for all modules can be located in the root directory that contains all modules.

## Apollo Config File Format

The `ApolloConfig.json` file is either a simple JSON file with the following format:

* `output` A path for where the generated query/mutation files should be output. 
    * This can be relative to the input `.graphql` file, the config file, or an absolute path.
    * Default: The default output directory provided to the generation command.
    * Examples: 
```
    output: ''            // Relative to the .graphql file
    output: 'Generated'   // Directory relative to the .graphql file
    output: '.'           // In the directory of the Apollo.config file
    output: './Generated' // Directory relative to the Apollo.config file
    output: '/home/repo/Generated' // Absolute path
```

* `referencedTypes` An array of objects representing shared types from the scheme (enums and input structs) that may be referenced by the `.graphql` files and how to handle them.
    * Each referenced type entry has the format:
        * `type` A glob that matches the names of referenced types.
        * `output` A path for where the generated type files should be output.
            * This can be relative to the config file, or an absolute path.
        * `moduleName` (Optional) The name of the module the generated type will be included in. Generated files that require a reference to the type will include an `import {{moduleName}}` statement.
    * Examples:
```
/modules/MyModule/ApolloConfig.json
        
    referencedTypes: [
        { type: 'UserInput', output: './Types' } // -> /modules/MyModule/Types/UserInput.graphql.swift
        { type: '*Input', output: './Types/Input' } // -> /modules/MyModule/Types/Input/{{typeName}Input.graphql.swift
        { type: '*', output: '../SharedModule/InputTypes', moduleName: 'SharedModule' } // -> /modules/SharedModule/InputTypes/{{typeName}.graphql.swift
    ]
```

## Nested Configurations

Config files can be nested, overriding values from higher levels in the directory structure. If no config file is found for a directory, the default, non-modular behavior will be adopted. By nesting configurations, you can set up default rules for an entire project with granular configuration overrides in specific modules.

**Comment by designatednerd** [comment]
Thanks for putting this together @AnthonyMDev! Really appreciate your help in digging into this.

A few questions on what you've got so far to try and dig into some of the details:
 
- Would the `Generated` file format as shown as a `Directory relative to the GraphQL file` mean that each graphQL file would have its own `Generated` folder? (or at least each folder that contains graphQL files would then have its own `Generated` folder)? I'm thinking about the possibility for folders named `Generated` scattered all over a codebase. 
- Right now you're suggesting `.graphql.swift` as a pattern rather than `.swift`, which is the current default. Any particular reason for this change? 
- Why `Apollo.config` rather than `ApolloConfig.json`, which can be more easily parsed by things like quicklook plugins and GitHub? 
- If you're working in a system with multiple repos:
  - Where would you store the top-level configuration file that would be used to generate code across everything when checked out locally?
  - How would you ensure that all modules you need to have checked out locally to regenerate are checked out? 
  - How would that work for teams working in separate modules where teams either a) Don't have access to all modules or b) Find checking out all modules takes up waaaaay too much time and hard drive space? 

This is a super-awesome start and I'm excited to get this fleshed out!

**Comment by AnthonyMDev** [comment]
> Would the Generated file format as shown as a Directory relative to the GraphQL file mean that each graphQL file would have its own Generated folder? (or at least each folder that contains graphQL files would then have its own Generated folder)? I'm thinking about the possibility for folders named Generated scattered all over a codebase.

Yes, that's correct. I agree that this could lead to a ton of Generated folders all over the place. I wouldn't personally use this configuration if I was going to have my `.graphql` files in lots of places. It might make sense if I was organizing my `.graphql` files consolidated into one folder for a given module/feature area though. I proposed to include it as an option. Since we are building advanced features, I just figured make them as configurable as we can without too much additional effort, and let user's do what they want with it.

> Right now you're suggesting .graphql.swift as a pattern rather than .swift, which is the current default. Any particular reason for this change?

Oh, uhm... all of my team's generated graphql files are being generated with the extension `.graphql.swift`. Looking at our code-gen config (using the legacy JS codegen), it doesn't look like we are doing anything to make that happen? So I just assumed that was the default. Perhaps I'm not sure how this works, but that's what we're getting.

> Why Apollo.config rather than ApolloConfig.json, which can be more easily parsed by things like quicklook plugins and GitHub?

Great point. I will make that change.

> If you're working in a system with multiple repos:
> - Where would you store the top-level configuration file that would be used to generate code across everything when checked out locally?
You don't necessarily have to have one. If you are using submodules/subtrees or a mono-repo, this may make sense. In many multi-repo setups, maybe you won't have a top-level config file. 

If you have no config files at all, all files will be generated into a single folder provided as the default output directory for the entire generation command. If we make that default directory optional and you don't provide it, then it's expected that you either have a top-level config file, or every sub-module provides a config file with an `output` configuration. If we can't find a default or a config file, then the tool will need to throw an error.

This also means that, if your code generation script provides a default output directory, just a single folder in a single module could override that to, for example, output it's generated files right next to it's `.graphql` files. The rest of the files for everything else would go into a single directory.

> - How would you ensure that all modules you need to have checked out locally to regenerate are checked out?

Theoretically, you would just be able to generate the files for the stuff you do have checked out. If `referencedTypes` would be generated into a directory that doesn't exist, that directory would be created. If you are referencing types in another module with `moduleName` and haven't checked out that module, we will create the directory and generate the files, but you're not going to have anything else that makes that module really. So, when you go to build your code, it's going to give you a build error and you should realize you need to check out that module or change your config to generate those referenced types somewhere else.

I don't think we need to check this for them, nor is there a simple way to do so. It shouldn't be much of an issue. We aren't creating actual targets with an .xcproject file and linking files into targets and all of that. We are just generating our `.swift` files in the directories the config tells us to and adding the `import <moduleName>` line to those files semi-intelligently. The rest is up to the user. There are other tools out there to automate the rest of that process if they want.

- How would that work for teams working in separate modules where teams either a) Don't have access to all modules or b) Find checking out all modules takes up waaaaay too much time and hard drive space?

Yeah, this goes along with my response above. If you have shared modules for referenced types, then of course, you need to have those checked out. But for both situations a & b, the answer is the same: You can just generate the files for the modules you need/have access to.

This just means you would set up your config so you generate referencedTypes in a place you can access them. You may end up having multiple modules with their own versions of the same referencedType, but if those modules aren't supposed to know about each other, than this is probably the intended course of action for you anyways.

**Comment by designatednerd** [comment]
> Since we are building advanced features, I just figured make them as configurable as we can without too much additional effort, and let user's do what they want with it.

I'm generally in agreement with this, I just want to make sure we don't leave too many footguns lying around in advanced settings. I think this one isn't *too* bad on the surface, though, I just wanted to clarify the intention. 

> all of my team's generated graphql files are being generated with the extension .graphql.swift.

Ahhh I forgot we do this when we do multi-file output from the JS. My bad!

> If you have no config files at all, all files will be generated into a single folder provided as the default output directory for the entire generation command. If we make that default directory optional and you don't provide it, then it's expected that you either have a top-level config file, or every sub-module provides a config file with an output configuration. If we can't find a default or a config file, then the tool will need to throw an error.

I think I'm still a little confused by this scenario: How do we differentiate between "a top-level config was not provided so we should just put everything into one module" and "there's no top level config, but there are lower-level configs"? Would we need to walk the file tree to look for `ApolloConfig.json` everywhere? 

> So, when you go to build your code, it's going to give you a build error and you should realize you need to check out that module or change your config to generate those referenced types somewhere else.

We should probably put this in docs for troubleshooting advanced setups, there's plenty of people who can follow the directions to set this up but don't quite make that connection on their own.

**Comment by AnthonyMDev** [comment]
> I think I'm still a little confused by this scenario: How do we differentiate between "a top-level config was not provided so we should just put everything into one module" and "there's no top level config, but there are lower-level configs"? Would we need to walk the file tree to look for ApolloConfig.json everywhere?

I haven't gotten into the existing code enough to wrap my head around implementation, but this shouldn't be too difficult. Maybe a bit tedious...

I'm thinking that we have some utility class that parses and merges the configs for directories. As we go to generate a file, we would look at all directories in the path from the top-level to the folder containing the file. Each config file would be merged, overriding values from config files in higher level directories so that for each directory, we have a final computed config that applies to code generation for that directory's files.

If we are generating a file, we check for the config, and the directory for the source `.graphql` file has no config file anywhere in it's path, all the way to the root, then we just use the default code generation options for that file. If you provide a default output path, generated queries, mutations, and referenced types go there. Not sure if we want to allow the option to _not_ provide a default output path. If it's not required, then we would expect either one top-level config file or one for each directory, and if they didn't exist, we would throw and error.

**Comment by designatednerd** [comment]
@AnthonyMDev Hi! Have you had any opportunity to look at this further in the last month?

**Comment by AnthonyMDev** [comment]
I haven't recently. I was also hoping to get more comments and a sense of confirmation that this was the direction we wanted to head on this. But it looks like you and I are the only ones who are going to comment on this.

**Comment by designatednerd** [comment]
Ha. Yeah, I'll tweet this link out to see if we can get some more folks to contribute. 

@gsabran I remember you particularly having thoughts/questions about modularization - anything here interesting to you?

**Comment by CraigSiemens** [comment]
We’re also using Apollo with multiple modules. In our setup, each target has it’s own build phase to run the codegen with some custom options we've added to our script. In a provided solution, it'd be nice to have to following:

### Ability to run codegen on a specific module
The described structure of the config json wouldn’t allow since the following is possible:
- a module can define a type/file that will be generated in another module.
- a module can depend on another module generating a type that will be compiled in this module.

### Control the ACL per module and/or type
This is one of the custom options we’ve added to our script. Most types in modules are made internal and one module has types being left public.

### Exclude a type from being generated in a module. Add an import to another module.
This is similar to `passthrough` option that's available for scalars but with the added option to add an import to the module that will contain the type.

### Include a type in the codegen even if no operations in the module are using that type.
This would allow generating enums, input types, etc. in a shared module that doesn't have any operations that use those types.

## How it could look for our project
In a future solution for this, I picture our project would have one config file per module that uses Apollo. Each config file would have enough information to define running the codegen for that module in isolation. This would require splitting up `referencedTypes` a bit.

```js
{
  // Defines types that would normally be generated based on the graphql files but shouldn't be
  "excludedTypes": [
    // Imports SharedModule in any generated file that references this type.
    { "type": "SomeType", "import": "SharedModule" },

    // Expects the type will be available in the same module
    { "type": "SomeOtherType" }
  ],

  // Used to define additional options for specific types
  "typeOptions": [
    // Specify an ACL for a specific type
    { "type": "SharedType", "accessControl": "public" },

    // Force generating a type that isnt used in any of the operations in this module, ex. enums, input types, etc.
    // "generate": true could be implied by the type being listed here but then handling globs could become complicated
    { "type": "UnusedButSharedType", "accessControl": "public", "generate": true },

    // Apply default options to all generated types
    { "type": "*", "accessControl": "internal", "output": "./generated" }
  ]
}
```

**Comment by AnthonyMDev** [comment]
Thanks for the awesome comments @CraigSiemens!

I agree with a lot of what you would like to see here, and think that your proposed solutions seem generally pretty great! We need to do some thinking about how to integrate these properly. Specifically the stuff around allowing generation of a single module at a time.

> ### Exclude a type from being generated in a module. Add an import to another module.

Instead of having an `excludedTypes` could we just use the `moduleName` field, and if you _don't_ include the `output` field, then it doesn't generate the file? I think that's a pretty elegant and simple solution. `moduleName` indicates that all files using that type need to import that module already. And `output` indicates where to generate the file, so not providing the `output` field means you expect the file to already be generated by another module? Maybe we rename `output` to make it more clear?

> ### Ability to run codegen on a specific module
> The described structure of the config json wouldn’t allow since the following is possible:
>
> - a module can define a type/file that will be generated in another module.
> - a module can depend on another module generating a type that will be compiled in this module.

I'm not sure exactly what you mean by this. Can you elaborate? I think you're saying that if you need to generate one module, but that module has a shared type that is indirectly generated _into it by another modules generation config_ then it won't generate that file. Is that right?
Perhaps we solve that by requiring the shared types to be declared with a relative output path in the module that they will be included in. And then other modules can import that module using `moduleName` as described above. So you can't indirectly generate a type into another module, but you can import it. And you _must_ generate it by including it in the config for the module you want to generate it in? That solves your issue, but it also makes this cumbersome for many of the most basic use cases, where you want shared types to just automatically be generated if they are using in your queries...

Let's do some more thinking on this.

**Comment by john-twigg-ck** [comment]
@calvincestari 
Are there any example/tests/documentation on how we can split out queries into multiple modules?

I've seen this referenced as complete in multiple Issues but I cannot understand how to leverage it.

**Comment by AnthonyMDev** [comment]
This is supported in the 1.0 release, which is currently in Beta. It's not going to be supported in the 0.x releases, as it required a significant restructuring of the generated code. Due to it being in Beta, the documentation is not complete, but there is quite a lot of inline documentation available in the Beta version!

The basic concept is that we now generated what we call a "Schema Module" this is a module that includes all the shared generated code from your schema that all your operation models need. This includes enums, custom scalars, information on the types, interfaces and unions in your schema, etc. All of your generated models just need to import this, and they can be located anywhere in your project then.

You can configure the way we output all of this in the `ApolloCodegenConfiguration` or a config file consumed by our new codegen CLI tool.

More documentation on all of this is coming soon. We just released the beta on Friday, so we are working on docs and usage guides now!

**Comment by calvincestari** [comment]
@john-twigg-ck did that explanation help to understand our approach to modules in 1.0? I'd suggest looking at  [`ApolloCodegenConfiguration.FileOutput`](https://github.com/apollographql/apollo-ios/blob/release/1.0/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift#L160) and reading the header docs since that's where the file output configuration is defined.
