### ISSUE TITLE
URLSessionClient doesn't use custom URLSessionConfiguration

### ISSUE THREAD

**Issue by ignalonzo** [apollographql/apollo-ios#1230]
After [0.27.0](https://github.com/apollographql/apollo-ios/pull/1163) changes for HTPPNetworkTransport init to use URLSessionClient instead of URLSession, custom URLSessionConfiguration properties such as _htppAdditionalHeaders_ don't get configured.

```
    let apollo: ApolloClient = {
        let configuration = URLSessionConfiguration.default
        
        configuration.httpAdditionalHeaders = [
            "X-Parse-Application-Id": "appID",
            "X-Parse-Client-Key": "clientID"
        ]
        
        let url = URL(string: "https://parseapi.back4app.com/graphql")!
        let sessionClient = URLSessionClient(sessionConfiguration: configuration)
        
        return ApolloClient(networkTransport: HTTPNetworkTransport(url: url, client:sessionClient))
    }()
```

Previously using the same URLSessionConfiguration, the HTPPNetworkTransport class got the URLSessionClient configured accordingly and requests were sent correctly.

```
let apollo: ApolloClient = {
    let configuration = URLSessionConfiguration.default
    configuration.httpAdditionalHeaders = [
            "X-Parse-Application-Id": "appID",
            "X-Parse-Client-Key": "clientID"
    ]

    let url = URL(string: "https://parseapi.back4app.com/graphql")!

    return ApolloClient(networkTransport: HTTPNetworkTransport(url: url, configuration: configuration))
}()
```

**Comment by designatednerd** [comment]
That's...very weird. [Here's the only place the session is set up](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/URLSessionClient.swift#L42), and you can see we're passing the session configuration in directly from the parameter, which it looks like you're passing in appropriately. 

What happens if you throw in a breakpoint after you set up `sessionClient` and `po` the client's `session.configuration`?

**Comment by ignalonzo** [comment]
![image](https://user-images.githubusercontent.com/43062515/83060531-990b9d80-a029-11ea-8d99-10fef0c88c02.png)

![image](https://user-images.githubusercontent.com/43062515/83060584-ade83100-a029-11ea-9af1-937a39146291.png)

**Comment by ignalonzo** [comment]
![image](https://user-images.githubusercontent.com/43062515/83061220-a2493a00-a02a-11ea-8c58-aebd865a981c.png)

![image](https://user-images.githubusercontent.com/43062515/83061253-b12fec80-a02a-11ea-8717-1fcd6c49e2c7.png)

HTTPNetworkTransport:

![image](https://user-images.githubusercontent.com/43062515/83061319-c9077080-a02a-11ea-9403-bad865b2e622.png)

**Comment by designatednerd** [comment]
Yeah if those are there, I've got absolutely zero idea why they wouldn't be getting sent with the request. 

At what point are you seeing them not being sent with the request, after it hits the wire? Or are you getting an error indicating they're not there?

**Comment by ignalonzo** [comment]
Never mind... Everything works as expected. Sorry for the missleading bug report.

**Comment by designatednerd** [comment]
No worries, I'm just glad it actually works! 😃

**Comment by ignalonzo** [comment]
We met in last years SwiftAlps and I really admire your work that you're doing here, Ellen! 

I'm trying to dig deep now in to GraphQL with Apollo and I hope I'll be able to contribute in the future. Take care!

**Comment by designatednerd** [comment]
You too!
