### ISSUE TITLE
0.28.0 Codegen SHASUM??

### ISSUE THREAD

**Issue by sneakyness** [apollographql/apollo-ios#1231]
Trying to update from 0.27.x to 0.28, getting this as the result

```
[DEBUG - ApolloCodegenLib:CLIDownloader.swift:43] - Zip file with the CLI is already downloaded!
[DEBUG - ApolloCodegenLib:CLIExtractor.swift:39] - Apollo folder doesn't exist, extracting CLI from zip file.
SHASUM: 08c45258b7cc1d4e6e28288930428922fd7dee9ccaad6e5be17dd5b79e6b1af4
Program ended with exit code: 1
```

Normally it would extract and go from there, my only changes were `.apollo_createFolderIfNeeded(at: output)` -> `.apollo.createFolderIfNeeded(at: output)`, and removing the `passthroughCustomScalars: false` from codegen options

Looks like it's just the SHASUM not matching up? 

```
Printing description of expected:
"0b11aa7973afed9a6b66fbff8c4a09421068a3fe0f50975f7c5d4ca791236b0c"
Printing description of shasum:
"08c45258b7cc1d4e6e28288930428922fd7dee9ccaad6e5be17dd5b79e6b1af4"
```

**Comment by sneakyness** [comment]
Ok it's apparently fine now? Does github take a sec to catch up or?

**Comment by designatednerd** [comment]
Weird! Sounds like some sort of caching issue. Sometimes I have found that if something significant has changed in a point update, have to either do a `Clean Build Folder` or a [derived data dance](http://deriveddata.dance) to get it picked up.

**Comment by alexandrethsilva** [comment]
Hi there @designatednerd I've tried both cleaning the build folder and doing the dance. Nothing worked. 😢 
Do you have some suggestions on what else I could do?

To me it happened after upgrading from `0.27.1` to `0.29.0`.

**Comment by designatednerd** [comment]
@alexandrethsilva - mind opening a new issue, and clarifying if you're using the swift scripting or the shell script? Thank you!
