### ISSUE TITLE
How can we wait for result in perform mutation closure?

### ISSUE THREAD

**Issue by selin194** [apollographql/apollo-ios#1232]
Hi everyone, I try to use apollo perform mutation function. I successfully perform mutation and get result but result gets back asynchronously, which is expected. But I want to wait for result to make sure it is created successfully, and continue other steps afterwards. I already tried to use semaphore but it gave me deadlock. (Since I block main thread). I tried to execute apollo perform function in a newly created dispacth queue ut it again gave deadlock. Here is an example scenario:
The following mutation works correctly and after a while I get the result.  
``` 
 apollo.perform(mutation: UpvotePostMutation(postId: postId)) { result in
  guard let data = try? result.get().data else { return }
  self.configure(with: data.upvotePost?.fragments.postDetails)
}
```

Now lets assume I tried to assign `postDetails` parameter in the next line as follows:
``` 
let assignedPostDetails: String = ""
apollo.perform(mutation: UpvotePostMutation(postId: postId)) { result in
  guard let data = try? result.get().data else { return }
   assignedPostDetails = data.upvotePost?.fragments.postDetails
}
print("\(assignedPostDetails)") // This parameter is still empty, it is not assigned yet
```

Following are some attempted solution to wait the result in the closure body:

``` 
 let sem = DispatchSemaphore(value: 0)
 apollo.perform(mutation: UpvotePostMutation(postId: postId)) { result in
  guard let data = try? result.get().data else { 
    sem.signal()
    return 
}
   assignedPostDetails = data.upvotePost?.fragments.postDetails
   sem.signal()
}
sem.wait()
```
The above block gives, which blocks main thread I guess.
 ``` 
    Connection 1: received failure notification
    failed to connect 3:-9816, reason -1
    encountered error(3:-9816)
```
And creating new dispatch queue and giving this as parameter to the apollo perform also produces same error. 

``` 
  let queue = DispatchQueue(label: "new queue")
  let sem = DispatchSemaphore(value: 0)
queue.async {
  apollo.perform(mutation: UpvotePostMutation(postId: postId), queue: queue) { result in
  guard let data = try? result.get().data else { 
    sem.signal()
    return 
  }
   assignedPostDetails = data.upvotePost?.fragments.postDetails
   sem.signal()
 }
} 
sem.wait()
```
How can I wait for result in this scenario? Thanks for help.

**Comment by designatednerd** [comment]
I want to take a step back from the how to the why here: Can you go into detail about why you can't call a method to start the next step from the completion closure of the apollo `perform` method? 

There's a few workarounds I can suggest (partiuclarly if you're using iOS 13 and have the ability to use Combine), but the _Do thing async, get result in a completion closure, kick off more work in completion closure_ pattern is very common in iOS, so I want to better understand why that pattern doesn't work for you before I give suggestions.

**Comment by selin194** [comment]
Hey @designatednerd! Actually, I want to create a test user and after creating test user I need to use this user in e2e tests. Which opens a page, enrolls, and uses this newly created user's information automatically. So, I do not want to include all of the test case steps in the closure (since this breaks our architecture). So I want to make sure user is created before executing next lines. Each of the steps are sequential in our case.

**Comment by designatednerd** [comment]
Aha! This is much easier if you're using XCTest - there's a tool called expectations that handles this for you: 

```swift
let expectation = self.expectation(description: "user created")

apollo.perform... {
   // Expectation is not fulfilled until closure completes
   expectation.fulfill()
}

// Waits for the `fulfill()` to get called, or times out. 
self.wait(for: [expectation], timeout: 10)

// Do next step. 
```

[Apple's got some more detailed documentation that should help you there](https://developer.apple.com/documentation/xctest/asynchronous_tests_and_expectations/testing_asynchronous_operations_with_expectations).

If you're _not_ using `XCTest`...that's going to be a lot more annoying. Let me know.

**Comment by selin194** [comment]
Thank you for this suggestion! Actually our user creator class is separated from the test class. And not to break `Liskov substitution principle` I do not want to inherit `UserGenerator` class from `XCTestCase`. For the current solution however, I use your suggested solution in the test class itself, which is doing more than one work.

**Comment by designatednerd** [comment]
Cool! mind if we close this issue out then?

**Comment by selin194** [comment]
Of course, thanks for that!
