### ISSUE TITLE
'delegate' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by linkthrow** [apollographql/apollo-ios#1238]
I tried to follow the guide here (https://www.apollographql.com/docs/ios/initialization/#example-advanced-client-setup) to create an advanced Apollo client with the delagetes, however I always get the attached error, has anyone been able to implement it?

**Comment by linkthrow** [comment]
<img width="935" alt="Screenshot 2020-05-31 at 12 41 42" src="https://user-images.githubusercontent.com/16664738/83351498-7389d700-a33c-11ea-868e-f89b30a547e4.png">

**Comment by hariszaman** [comment]
Hi. Please update to latest master. The PR for this issue has already been merged. Specifically this is it :)
https://github.com/apollographql/apollo-ios/pull/990/files

**Comment by linkthrow** [comment]
Sorry, your correct @hariszaman !
