### ISSUE TITLE
Integration with Alamofire RequestInterceptor

### ISSUE THREAD

**Issue by greenmood** [apollographql/apollo-ios#1239]
Now in order to refresh OAuth token with apps using alamofire, we need to consider two cases when the token has expired:
First is when the app sends any let's say REST request. We need to refresh the token and send again failed requests. The recommended approach is based on Alamofire's RequestInterceptor.

Second is when app sends any GraphQL request using Apollo. We need to refresh the token and send again failed requests. The recommended approach is using 'HTTPNetworkTransportPreflightDelegate'.

So we'll have two places for refreshing the token, adding updated token. I think it would be great if Apollo will allow us to inject Alamofire's RequestInterceptor.  Thoughts?

**Comment by designatednerd** [comment]
Hi! So we're not planning on adding direct support for Alamofire (or any other networking library), but there is a community project, [ApolloAlamofire](https://github.com/graphql-community/ApolloAlamofire), which, while recently deprecated, can at least give you a place to start in using your own implementation of the `NetworkTransport` protocol that uses Alamofire under the hood. 

We are looking at a more interceptor-style networking lib in the medium future, but it will not be based on alamofire, and we do not have an ETA for it.

**Comment by greenmood** [comment]
Thanks, looked hopefuly.
But NetworkTransport protocol method 'send' requires Cancellable to be returned, while alamofire can't provide URLSessionTask, which conforms to cancellable, synchronously. It's property 'task: URLSessionTask', can be nil and populated later.
https://github.com/Alamofire/Alamofire/issues/3213

**Comment by designatednerd** [comment]
Hi! You could also make some kind of no-oping conformance to `Cancellable` to return while you wait for the `URLSessionTask` to be populated - it's not ideal that's part of why it's a protocol rather than a concrete object.

**Comment by jshier** [comment]
@greenmood From my brief look at `Cancellable`, it doesn't seem necessary to access the Alamofire `Request'`s underlying `URLSessionTask`. Just make `Request` conform to the protocol.

```swift
extension Request: Cancellable {}
```

`Request` already has a `cancel()` method, so it should work fine.

**Comment by greenmood** [comment]
At first glance, it should work.
Thanks, everyone! Hugely appreciated.
