### ISSUE TITLE
SQLiteNormalizedCache Example

### ISSUE THREAD

**Issue by ivoilic** [apollographql/apollo-ios#1243]
Hi,
I wanted to request that an example for setting up the client to work with a SQLiteNormalizedCache gets added to the docs. It seems odd the documentation (which is otherwise very detailed) just mentions the possibility a doesn't provide a basic example. Also more specificity regarding the fileURL parameter requirements would be super helpful. Thanks!

**Comment by designatednerd** [comment]
Yeah I think that's a totally reasonable request - I'm a little in the weeds at the moment, but I'd also be happy to look at a PR on this!

**Comment by barclayd** [comment]
This StackOverflow [post](https://stackoverflow.com/a/54742824/9961739) is a great place to start. I would definitely welcome enhanced documentation on it too, whenever time permits 😊

**Comment by designatednerd** [comment]
@ivoilic @barclayd Please check out this PR that tries to flesh this out a bunch: #1312

**Comment by barclayd** [comment]
Thank you very much @designatednerd! That's excellent 😊

**Comment by designatednerd** [comment]
#1312 is now merged, so I'm gonna close this one out. Thanks for flagging this!
