### ISSUE TITLE
Respsone timeout 

### ISSUE THREAD

**Issue by hiteshborse12** [apollographql/apollo-ios#1244]
How to set response timeout for ApolloClient.

**Comment by designatednerd** [comment]
We use whatever is on the `URLSessionConfiguration` you pass in - the property to set this is called [`timeoutIntervalForRequest`](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1408259-timeoutintervalforrequest). Per the docs:

> The default value is 60.

**Comment by hiteshborse12** [comment]
But I am not able to pass URLSessionConfiguration during ApolloClient object creation.
HTTPNetworkTransport only accepts URL as a init parameter.  

[Screenshot 2020-06-06 at 1 56 38 AM](https://user-images.githubusercontent.com/6498031/83919821-12795d80-a799-11ea-9147-b37aeb773703.png)

**Comment by hiteshborse12** [comment]
Fixed.
let url = URL(string: baseURL)!
                    let configuration = URLSessionConfiguration.default
                    configuration.timeoutIntervalForResource = 10
                    let client = URLSessionClient(sessionConfiguration: configuration)
                    let transport = HTTPNetworkTransport(url: url,
                                                         client: client)
                    return ApolloClient(networkTransport: transport)

**Comment by designatednerd** [comment]
Yep, right on. Thanks for posting the solution for future folks!
