### ISSUE TITLE
Cannot load underlying module for 'Apollo'

### ISSUE THREAD

**Issue by horaciosolorio** [apollographql/apollo-ios#125]
Install Xcode Beta 4 , please let me know how i can fix this issue.

**Comment by designatednerd** [comment]
@horaciosolorio I'm guessing this was Xcode 9 Beta given the date of this post. Obviously this was a while ago, sorry we weren't able to help you at the time!

If you are still having similar issues with Xcode 10 or 11, please open a new issue and mention: 
- Xcode version
- Operating system version
- How are you installing the Apollo framework?
