### ISSUE TITLE
Remove generated allCases for enums

### ISSUE THREAD

**Issue by vitallica** [apollographql/apollo-ios#1254]
By declaring an enum as conforming to the `CaseIterable`, `allCases` is implied without needing to explicitly define it. The functionality provided by `allCases` generated via the `enumTemplate` is identical to `allCases` implied in the `CaseIterable` conformance. Removing it from the template will decrease the amount of generated code, and allow for compatibility with any future Swift changes.

**Comment by designatednerd** [comment]
🤔 Hm...I'll have to take a look at this and how it fits in with the `omitDeprecatedEnumCases` functionality. Thanks for pointing this out.

**Comment by designatednerd** [comment]
Ahhh, right - we can't do this because all the enums have an `__unknown` case, which mostly exists to prevent crashes when a new case is added in the future. This case is omitted from `allCases`, which means it can't be auto-generated.

**Comment by vitallica** [comment]
Ah right, my apologies for missing that edge case! Closing this.
