### ISSUE TITLE
Model generation issue for fields starting with _

### ISSUE THREAD

**Issue by vinitam** [apollographql/apollo-ios#1259]
We are using the following GQL query:

```
query ProductInfoQuery() {
  product() {
     size 
     _size 
     description
    }
}
```

`size` is of type `Int` and `_size` is of type `ID`. When I try generating a model for the above query, it generates `size` of type `ID` instead of generating 2 fields `size` and `_size`.

**Comment by designatednerd** [comment]
This is a limitation of our current codegen - I would recommend aliasing the name of the underscored one like this:

```graphql
query ProductInfoQuery() {
  product() {
     size 
     moreDescriptiveName: _size 
     description
    }
}
```

Then the `_size` property will be generated with `moreDescriptiveName` instead of the two `size` types clashing. Sorry there's not a better workaround!

**Comment by vinitam** [comment]
I tried this out and it worked. Thanks for your help.

**Comment by designatednerd** [comment]
Cool - mind if we close this issue?

**Comment by vinitam** [comment]
Sure
