### ISSUE TITLE
Compile error when fragment has same name as the field

### ISSUE THREAD

**Issue by aryan-ghassemi-ck** [apollographql/apollo-ios#126]
![screen_shot_2017-08-07_at_8 50 44_am_480](https://user-images.githubusercontent.com/29413503/29044017-5e8d91ba-7b72-11e7-8e6d-ed852d609580.png)

```
fragment button on Button {
     destination {
    ...destination
  }
}
fragment destination on Destination {
   ... on First {
          discriminator
    }
   ... on Second {
          discriminator
    }
}
```

I have a field in my query which is named the same as a fragment.
In the code I posted above `Destination.self` is referring to the class it's in rather than the fragment

**Comment by calvincestari** [comment]
Hi 👋🏻 - after looking at this issue again in preparation for the upcoming 1.0 release we've decided not to take this request into 1.0. If this is important to you please let us know _in this issue_ - thank you.
