### ISSUE TITLE
Download Scripting Issue

### ISSUE THREAD

**Issue by Ian8829** [apollographql/apollo-ios#1265]
When I do as your description to download schema.json, below error message shows up.

Why this message is show up???

**Value of type 'FileManager' has no member 'apollo'**

**Comment by designatednerd** [comment]
Hi! What version of the library are you using? There were a couple things that recently got converted over from `apollo_blah` to `apollo.blah`, so you may need to upgrade to a newer version.

**Comment by designatednerd** [comment]
@Ian8829 Were you able to fix this by upgrading, or are you still having issues?

**Comment by lastneutrino** [comment]
The reference apollo issue is resolved by 29.0, but I am seeing the following in Codegen - note the return code isn't zero at the end:

% swift package clean
% swift run
lastneutrino/Test1263/Codegen/.build/checkouts/PathKit/Sources/PathKit.swift:98:14: warning: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'Path' to 'Hashable' by implementing 'hash(into:)' instead
  public var hashValue: Int {
             ^
lastneutrino/Test1263/Codegen/.build/checkouts/Stencil/Sources/Template.swift:11:3: warning: 'internal(set)' modifier is redundant for an internal property
  internal(set) var environment: Environment
  ^~~~~~~~~~~~~~
  
[63/63] Linking Codegen
[DEBUG - ApolloCodegenLib:CLIDownloader.swift:43] - Zip file with the CLI is already downloaded!
[DEBUG - ApolloCodegenLib:CLIExtractor.swift:39] - Apollo folder doesn't exist, extracting CLI from zip file.
SHASUM: 0b11aa7973afed9a6b66fbff8c4a09421068a3fe0f50975f7c5d4ca791236b0c
% echo $?
1

**Comment by designatednerd** [comment]
That warning shouldn't be affecting things - is the codegen ultimately running or no?

**Comment by designatednerd** [comment]
(if no, can you please open a separate issue, since this one is tied to a different version?)

**Comment by lastneutrino** [comment]
build doesn't complete - says script return value is non-zero

**Comment by designatednerd** [comment]
OK - please open a new issue and we'll try to figure it out.

**Comment by designatednerd** [comment]
I'm gonna close this out since I haven't heard back from OP and there have been a couple subsequent releases. If you're having similar problems, please open a new issue and indicate what version of the iOS SDK you're using. Thank you!
