### ISSUE TITLE
Multiple Xcode project targets issue

### ISSUE THREAD

**Issue by StanislavCekunov** [apollographql/apollo-ios#1269]
I have created multiple targets and schemes to handle dev, uat, release builds for my current project. However having this issues:

```
 ›   Error: Error initializing Apollo GraphQL project "Unnamed Project": Error: 
 ›   Error in "Loading schema for Unnamed Project": Error: Unable to read file 
 ›   API/NetworkLayer/GraphQL/schema.json. ENOENT: no such file or directory, 
 ›   open 'API/NetworkLayer/GraphQL/schema.json'
Command PhaseScriptExecution failed with a nonzero exit code

```

run script:
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="API/NetworkLayer/GraphQL/schema.json" API.swift
```

Anyone have experience working with apollo gql and multiple project targets?
Meanwhile I have tried changing location of "schema.json" to Absolute path and the rest. 
Though, I dont have any build errors on choosing main target and scheme.

Not able to figure out where is the issue, or maybe in general it can't handle targets (what would be very sad).

**Comment by designatednerd** [comment]
This should work with multiple targets, but you'll need to figure out what folder your files are actually in rather than using `{$TARGET_NAME}` in the `CD` since I'm going to bet you don't have all files duplicated across all target folders.

**Comment by StanislavCekunov** [comment]
Thanks @designatednerd, I decided to go for different approach. Same main target just different project schemes with dynamic Product Bundle Identifiers for each environment and AppIcons (main reasons I needed multiple targets).
