### ISSUE TITLE
Dictionary is only JSONEncodable if Value is (and if Key is String)

### ISSUE THREAD

**Issue by bkcan** [apollographql/apollo-ios#127]
I'm getting this error and it occurs at 
**Pods/Apollo/Sources/Apollo/JSONStandardTypeConversions.swift, line 121**

whenever I'm querying this:
```
query People($date: DateTime!) {
    viewer {
      id
        user {
          id
            people (filter: {
                    OR: [{
                         createdAt_gt: $date
                         }, {
                         updatedAt_gt: $date
                         }, {
                         deletedAt_gt: $date
                         }]
                    }) {
            count
                edges {
                    node {
                        id
                        createdAt
                        updatedAt
                        deletedAt
                        name
                        occupation
                        live
                    }
                }
            }
        }
    }
}
```

I'm suppose to be getting:
```
{
  "data": {
    "viewer": {
      "id": "viewer-fixed",
      "user": {
        "id": "cj62ntkn19jwa0191nez4booq",
        "people": {
          "count": 0,
          "edges": []
        }
      }
    }
  }
}
```

I can however query this and I get a successful result:
```
query AllPeople {
    viewer {
        user {
            id
            people {
                edges {
                    node {
                        id
                        createdAt
                        updatedAt
                        deletedAt
                        name
                        occupation
                        live
                    }
                }
            }
        }
    }
}
```

Then it might be the date? But the date I'm sending is: "2017-08-08T17:42:04.837Z"
So it when does this error actually happen? Before or after the query?

**Comment by jasonsilberman** [comment]
This also seems to be happening to me when I have a field that is optional and the value is null. What store/cache are you using? For me it only happened when using certain caches.

**Comment by bkcan** [comment]
@jasonsilberman I'm using `.fetchIgnoringCacheData`

**Comment by jasonsilberman** [comment]
Hmm alright, seems we are having the same issue but caused by different scenarios.

**Comment by bkcan** [comment]
You're passing different values other than `DATETIME`? And does it only occur when the values is null? 

I just tried it with the outcome of the return having data. But it still crashed.

**Comment by martijnwalraven** [comment]
@bkcan @jasonsilberman: Are you using custom scalars? If so, have you added your own Swift types or do you rely on the mapping to `String`?

**Comment by bkcan** [comment]
@martijnwalraven I'm guessing custom scalars would include `DATETIME!`. If that's the case, then I rely on the mapping to `String`

**Comment by martijnwalraven** [comment]
What version of Apollo iOS and `apollo-codegen` are you using?

**Comment by bkcan** [comment]
Apollo iOS: **0.6.2**
`apollo-codegen`: **0.16.4**

**Comment by jasonsilberman** [comment]
I think for me, this happens when it tries to encode an `NSNull()` value which is returned from `.jsonValue` on Optional. Although I don't say this with 100% confidence.

**Comment by bkcan** [comment]
In the mean time, I switched it `DateTime` to `String` in the query and now it works.

**Comment by bkcan** [comment]
I lied... 😞 **Variable '$date' of type 'String!' used in position expecting type 'DateTime'**

I saw a post about passing custom scalars when downloading the schema. So I'm considering doing that.

**Comment by sasilukr** [comment]
Is this a different issue than https://github.com/apollographql/apollo-ios/issues/97? I'm getting the same error trying to pass in INT and Bool as input arguments. If so, when will the fix be released?

**Comment by martijnwalraven** [comment]
@sasilukr: It should be a different issue, because that fix has already been released.

Could you post your query? That might in helping track this down.

(I'll be on vacation for the next week and a half, so I won't be able to respond for a while.)

**Comment by sasilukr** [comment]
@martijnwalraven 
mutation updateSomethingHere($id:Int!, $selected:Boolean!) {
    updatedData(todoSelection: [{id: $id, selected: $selected}])
}
The input is:
{"id": 3, "selected": true}

**Comment by martijnwalraven** [comment]
I'd really like to figure out what is going on here, but I haven't been able to reproduce it. Does anyone have a simple reproduction that they could share?

**Comment by Kiesco08** [comment]
I suspect the issue occurs because of the Apollo.Variable inside the dictionary passed as an OR filter. I get the same error when I try:

```
query userPostViewsForCurrentPost($postId: ID!, $profileId: ID!){
	allPostViews(filter:
	{
		AND: [
			{ post : **{ id: $postId }** }, <---- $postId causes a problem, scalar expected instead :(
			{ profile : { id: $profileId } }
		]
	}){
		id
	}
}
```

**Comment by martijnwalraven** [comment]
@Kiesco08: Thanks, that helped me figure out the issue. It turns out the problem was with variables nested in arrays.

This should be fixed in Apollo iOS 0.7.0-alpha.6.

**Comment by niraj1991** [comment]
@martijnwalraven I'm getting this error 

whenever I'm querying this:

```
`posts(workspace_id: 136, offset: 0){
    id
    workspace_id
    user_id
    can_delete
    is_bot
    unread
    content
    updated_at
    created_at
    notifiable_id
    reactionset
    reactiondata
    forwardedPost{
      id
      media{
        commentPoint{
          id
        }
      }
    }
    user {
      fullname
    }
	notification{
    notifiable_id
    notifiable_type
    id
  }
    media{
      comments{
        media_comments_point_id
        comment
      }
      commentPoint{
        id
        x
        y
      }
    }
  }
}`
```

I'm getting below response.

```
 "posts": [
      {
        "id": 4095,
        "workspace_id": 136,
        "user_id": 119,
        "can_delete": true,
        "is_bot": false,
        "unread": null,
        "content": "Tthththt",
        "updated_at": "1553774268",
        "created_at": "1553774268",
        "notifiable_id": null,
        "reactionset": {
          "thumbsup": 1
        },
        "reactiondata": {
          "thumbsup": [
            {
              "id": 40,
              "first": "Niraj",
              "last": "Gambhava",
              "is_deleted": null,
              "fullname": "Niraj Gambhava"
            }
          ]
        }
] 
```

However get a successful response. **But When I write the data in catch, Then I get this error.**

`Fatal error: Dictionary is only JSONEncodable if Value is (and if Key is String): file /Volumes/Bapu-DATA-D/Niraj/Vabotu App/Developments/vabotu-ios/Vabotu/ThirdParty/Apollo/JSONStandardTypeConversions.swift, line 121`

**If I remove the reactiondata and reactionset pram from Query It works.** 


Here is code for write the data in catch.
```
`  let promise = GraphQLManager.shardGraphQLManager.apollo.store.withinReadWriteTransaction { transaction in
            
            let query = PostsQuery.init(workspace_id: Int(self.loginCompany!.selectedWorkspaceID), filter_user_id: nil, filter_date_to: nil, filter_date_from: nil, limit: limit, offset: 0, cursor: nil, content: nil)
            
            do {
                var data = try transaction.read(
                    query: query
                )
                
                do {                    
                    let post = PostsQuery.Data.Post.init(id: Int(Date().toMillis()), user: PostsQuery.Data.Post.User.init(id: GraphQLManager.shardGraphQLManager.loginUserDetails?.fragments.userDetail.id! , first: GraphQLManager.shardGraphQLManager.loginUserDetails?.fragments.userDetail.first!, last: GraphQLManager.shardGraphQLManager.loginUserDetails?.fragments.userDetail.last!, pic: GraphQLManager.shardGraphQLManager.loginUserDetails?.fragments.userDetail.pic!, username: GraphQLManager.shardGraphQLManager.loginUserDetails?.fragments.userDetail.username!), updatedAt: nil, createdAt: nil, content: self.htmlContent, isBot: false, canDelete: true, media: nil, notification: [], forwardedPost: nil, reactionset: [:],  reactiondata: [:])

                    data.posts?.insert(post, at: 0)
                    try transaction.write(data: data, forQuery: query)
                } catch {
                    print(error)
                }
                
            } catch {
                print(error)
            }
        }
        promise.catch({ (error) in
            print(error)
        })`
```

Let me know if you need any other details, I would be happy to share you.

Please let me know if I am going wrong somewhere.

**Comment by niraj1991** [comment]
Hello @martijnwalraven 

@martijnwalraven Can you please see my above commented?
