### ISSUE TITLE
No such module 'ApolloCore'

### ISSUE THREAD

**Issue by alexjameslittle** [apollographql/apollo-ios#1272]
Getting the error message `No such module 'ApolloCore'` in `Bundle+Helpers.swift` when using the main branch. Currently using main as needed the fix for the memory leaks that has yet to be released.

**Comment by designatednerd** [comment]
What package manager are you using - SPM, Carthage, or Cocoapods?

**Comment by alexjameslittle** [comment]
Sorry, I’m using SPM

**Comment by designatednerd** [comment]
Looks like you'll need to go into "Link Binary With Libraries" and add the `ApolloCore` library for now: 

<img width="747" alt="Screen Shot 2020-06-24 at 2 44 10 PM" src="https://user-images.githubusercontent.com/1976498/85620327-3e199600-b629-11ea-9e0a-6fb80315e0dc.png">

I apparently need to update some dependencies there. Good catch!

**Comment by designatednerd** [comment]
@alexjameslittle I'm gonna close this one since it's specific to `main` - this is now merged and should be working a lot better.

**Comment by alexjameslittle** [comment]
This seems to be solved now due to a change in how our project is setup. But thank you!
