### ISSUE TITLE
How can I add the generated API.swift file to an app extension target?

### ISSUE THREAD

**Issue by Pahitos** [apollographql/apollo-ios#1276]
I'm trying to add a Widget (iOS 14 beta) extension to an existing app, and it needs to communicate with our GraphQL API to get the data.
If I directly add generrated the API.swift file to the extension target like a normal file (screenshot below), I'm getting a `Cycle in dependencies` error (the last 2 lines being the most important):

```
Cycle in dependencies between targets 'XProject' and 'XProjectWidgetExtension'; building could produce unreliable results.
Cycle path: XProject → XProjectWidgetExtension → XProject

Cycle details:
→ Target 'XProject' has copy command from 
'/Users/xxx/Library/Developer/Xcode/DerivedData/yyy/Build/Products/Debug-iphonesimulator/XProjectWidgetExtension.appex' 
to 
'/Users/xxx/Library/Developer/Xcode/DerivedData/yyy/Build/Products/Debug-iphonesimulator/XProject.app/PlugIns/XProjectWidgetExtension.appex'

○ Target 'XProject' has target dependency on Target 'XProjectWidgetExtension'
→ Target 'XProjectWidgetExtension': Ditto /Users/xxx/Library/Developer/Xcode/DerivedData/yyy/Build/Intermediates.noindex/XProject.build/Debug-iphonesimulator/XProjectWidgetExtension.build/DerivedSources/XProjectWidgetExtension-Swift.h 

/Users/xxx/Library/Developer/Xcode/DerivedData/yyy/Build/Intermediates.noindex/XProject.build/Debug-iphonesimulator/XProjectWidgetExtension.build/Objects-normal/x86_64/XProjectWidgetExtension-Swift.h

○ Target 'XProjectWidgetExtension' has compile command for Swift source files
○ That command depends on command in Target 'XProject': script phase “Generate GraphQL API”
```
This ⬇️ leads to this ⬆️ 
<img src="https://user-images.githubusercontent.com/18669007/85808649-7b624e80-b723-11ea-811c-fe6424dcf0c0.png" width="50%"/>

Any help would be appreciated :)

**Comment by designatednerd** [comment]
Good question! I think probably the best way to handle this is to use a framework that's used by both the app and the widget extension, and move the build phase run script to the framework's build phases. That way, it only has to be built once and can be used in either place.

**Comment by Pahitos** [comment]
@designatednerd oh wow, that turned out to be easier than I expected - didn't even have to move any of the files around (though I probably should, for cleanliness). Just had to create a framework, move the script from the main project to the framework, and after resolving a minor error with linking libraries, it ran successfully!
Thanks for the help 🙌

**Comment by designatednerd** [comment]
you're welcome!

**Comment by psvnanda** [comment]
@Pahitos I'm looking for the solution for the same problem. Can you please tell me how you have added the script into the shared framework from the main project.

**Comment by Pahitos** [comment]
@psvnanda when you create a framework, that adds a new target to your project. You can add the script in exactly the same way to that framework target as you would with a normal project: select your project file > your new framework target > Build Phases > add the codegen script, following Apollo documentation.
