### ISSUE TITLE
Add CachePolicy to return cache data and then fetch

### ISSUE THREAD

**Issue by jasonsilberman** [apollographql/apollo-ios#128]
Currently, I cannot find a way to hit the cache for data first, and then also always hit the network. Sometimes I want to show cached data first, but then fetch from the network to get updated data as well.

If we added a cache policy like: `returnCacheDataAndFetch` then I could do this.

Without this I often times get left with stale data in the cache that continues to be returned, but if I were to use the `fetchIgnoringCacheData` then it would not hit the cache when I am offline. Adding `returnCacheDataAndFetch` would allow developers to have both effective use of the cache and updated data from the network.

Additionally, this would increase parity with Apollo Client because it has the `FetchPolicy` option of [`cache-and-network`](http://dev.apollodata.com/react/api-queries.html#graphql-config-options-fetchPolicy) which allows developers to achieve the same thing.

**Comment by martijnwalraven** [comment]
Yep, that makes sense, and I like `returnCacheDataAndFetch`.

**Comment by jasonsilberman** [comment]
@martijnwalraven okay I think I am going to make a pull request for this, it seems like [`FetchQueryOperation.start()`](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloClient.swift#L168) is the right place to add this?

**Comment by martijnwalraven** [comment]
@jasonsilberman: That would be great! I think it should be fairly straightforward to add to `FetchQueryOperation.start()`.
