### ISSUE TITLE
Async token in preflight delegate: query vs mutation

### ISSUE THREAD

**Issue by emilioschepis** [apollographql/apollo-ios#1282]
Hi,

I'm trying to build an application that uses this library to connect to a GraphQL server.
My authentication is done through Firebase and I need to extract the current user's token to authenticate a GQL request.

In the Firebase iOS SDK the `getIDTokenResult` call is not synchronous so, reading past issues in this repository I extended the Firebase User as follows:

```swift
extension Firebase.User {
    func getIDTokenResultSync() -> String? {
        let semaphore = DispatchSemaphore(value: 0)
        var token: String?
        
        DispatchQueue.global(qos: .userInitiated).async {
            self.getIDTokenResult { result, error in
                token = result?.token
                semaphore.signal()
            }
        }
        
        semaphore.wait()
        return token
    }
}
```

Everything works fine as long as I'm only performing queries. As soon as I switch to a simple mutation the request never actually completes.

```swift
func saveToDatabase() {
    client.fetch(query: ListItemQuery()) { _ in print("Done") } // Works every time
    client.perform(mutation: CreateItemMutation(name: name)) { _ in print("Done") } // Never completes
}
```

Here's my preflight delegate:

```swift
extension GraphQL: HTTPNetworkTransportPreflightDelegate {
    func networkTransport(_ networkTransport: HTTPNetworkTransport, shouldSend request: URLRequest) -> Bool {
        true
    }
    
    func networkTransport(_ networkTransport: HTTPNetworkTransport, willSend request: inout URLRequest) {
        guard let user = Auth.auth().currentUser else { return }
        guard let token = user.getIDTokenResultSync() else { return }
        
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
    }
}
```

I am using the same client for both calls. Could anyone guide me in the right direction?
Thanks.

**Comment by designatednerd** [comment]
Weird! There's not any reason I can think of that those two should be different - they both ultimately call `NetworkTransport`'s `send` method, which in the case of `HTTPNetworkTransport` goes through to [this private `send` that doesn't seem to distinguish at all between mutations and queries](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/HTTPNetworkTransport.swift#L145). 

Couple thoughts: 
- Can you tell through breakpointing or debug-printing whether `getIDTokenResultSync` is finishing in roughly the same amount of time as it was before? 
- How is your `apolloClient` instance set up? I know in the past we've seen that if it's not a singleton or being hung onto by a property somewhere, ARC will hammer it and the callback will never get called because of that.

**Comment by emilioschepis** [comment]
Turns out I was mistaken: the query was only able to finish because it hit the cache. Using a different `cachePolicy` shows that the error also happens in queries.

I was able to boil it down to
```swift
let semaphore = DispatchSemaphore(value: 0)
var token: String?

Auth.auth().currentUser?.getIDToken { firebaseToken, error in
    token = firebaseToken
    semaphore.signal()
}

semaphore.wait()
print("Token is \(token)")
```

The weird thing is that if the semaphore has a timeout, the Firebase closure will complete right after the timeout expires (no matter what the timeout is, 1sec or 10secs). Maybe the semaphore is blocking that code too?
I can see that the Firebase SDK executes this call in its own global queue but I'm not expert enough in multi-threading to debug this issue on my own. I will be opening an issue on their repository.

This, however, means that the problem is not with the Apollo client at all so this issue can be closed.
Thank you for your help.

(By the way I love your talks!)

**Comment by designatednerd** [comment]
aw, thanks! 

Yeah if the semaphore is on the same thread as the call to `Auth` is executing on, that would prevent the call from starting / finishing, so when the semaphore times out, the call would become unblocked and execute immediately. 

Also for what it's worth I'm working on future plans to bring something that will make it a *lot* easier to do this with async calls - no timeline but I do know it's a feature that's wanted. 

I'll close this out per your request, though. Thanks for letting me know!
