### ISSUE TITLE
0.29.0 SHASUM 

### ISSUE THREAD

**Issue by alexandrethsilva** [apollographql/apollo-ios#1286]
Hi @designatednerd, here's more details on the issue I mentioned before on #1231.

After upgrading from `0.27.1` to `0.29.0`, I am unable to successfully run the **Swift scripting** to either download or generate a schema, as it fails the checksum.

The output message I'm getting seems related to a number of similar previous reports on #1231, #1265, #1285, #1177 and #1192.

**The log output**

```
ApolloCodegenLib:CLIDownloader.swift:43] - Zip file with the CLI is already downloaded!
[DEBUG - ApolloCodegenLib:CLIExtractor.swift:39] - Apollo folder doesn't exist, extracting CLI from zip file.
SHASUM: 08c45258b7cc1d4e6e28288930428922fd7dee9ccaad6e5be17dd5b79e6b1af4
Failed to Generate the Code
Program ended with exit code: 1
``` 

Even though I believe the problem is most likely related to caching, as [this comment](https://github.com/apollographql/apollo-ios/issues/1192#issuecomment-624440811) on #1192 seems to confirm, I am still unable to successfully use the script _even after cleaning the build folder and deleting the derived data_, so I'm not sure what else to do.

The problem occurs on both Xcode `11.4 (11E146)` and `12.0 beta (12A6159)`. Even though I imagine only `11.4 (11E146)` is actually considered for support, I need to run the build against the beta as well to verify things are still working on iOS 14, so it may be worth mentioning.

Also, thanks for the time you invest in supporting the community with this project! If you need more details, let me know.

**Comment by designatednerd** [comment]
This appears to be related to #1284 - working on additional commits to that to make sure it works well

**Comment by designatednerd** [comment]
Fix for this issue has gone out with `0.29.1` - the problem wasn't that the CLI is wrong, it's that linter failures were silent and that the CLI's SHASUM was the last thing that got printed out before that failure occurred. 

I'm gonna close this one out, if you continue to have problems with the new version, please file a new issue. Thank you!

**Comment by alexandrethsilva** [comment]
Thanks! I'll try it out and follow up in case problems still arise.

**Comment by amadeu01** [comment]
@designatednerd I'm facing the same problem with `0.29.1`

**Comment by alexandrethsilva** [comment]
@amadeu01 since my `0.29.1` update things have been running smoothly on my side. Did you try resetting the package caches and deleting the derived data to make sure it's not related to Xcode's cache?

To delete the package caches, go to `File > Swift Packages > Reset Package Caches`. Of course, that only applies if you're using the Swift Package. For Cocoapods you can remove the `Pods` folder and the `Pods.lock` before re-running `pod install` as well.

I never used Carthage, so I wouldn't know what to suggest for that case.

**Comment by amadeu01** [comment]
I did `rm -rf Carthage/Checkouts/apollo-ios/scripts/apollo` and then attempt to run again. It worked thanks @alexandrethsilva
