### ISSUE TITLE
Memory leaks appearing after release 0.29.1

### ISSUE THREAD

**Issue by alexjameslittle** [apollographql/apollo-ios#1292]
Using SPM, version 0.29.1.

We are seeing more memory leaks coming through from this library. This comes after the fixes were released in version 0.29 for the small memory leaks

Please see images of the root causes of two of the memory leaks

![image](https://user-images.githubusercontent.com/25927944/86767043-4c14e100-c043-11ea-8f9e-6b2f9aa7ba6d.png)
![image](https://user-images.githubusercontent.com/25927944/86767057-5505b280-c043-11ea-91a6-6cd8e3917c6b.png)

**Comment by designatednerd** [comment]
So those areas were not actually touched in the changes for `0.29.x`, the leaks referenced in that change were from the generated API files using `static let` for a bunch of stuff that would get allocated immediately and then just sort of float in space. Thanks for filing a new issue, this seems like a different problem.

Couple questions to try and figure this out: 
- What version did you upgrade from? 
- Can you check whether `0.28.x` also has these same leaks? 
- Where is the client generated by the `buildClient` function held on to?

**Comment by alexjameslittle** [comment]
I did just try going back to the 0.28.0 and it was still an issue there too, so it wasn’t introduced in the latest versions I’m pretty sure. 

The client from buildClient function is stored in a property on a singleton that handles the GraphQL requests

**Comment by designatednerd** [comment]
OK, good to know - that makes sense. 

Two other questions: 
- What dependency manager are you using? 
- Is there a chance you could either send me your project or put together a small repro of this? It'd be really helpful for trying to figure out why things are leaking - my email is ellen at apollographql dot com.

**Comment by alexjameslittle** [comment]
I’m using SPM.

I will have to throw together a separate project. Will send it over to your email once I’ve managed to replicate in another project

Thanks

**Comment by designatednerd** [comment]
Great - my thought is you'll probably only have to pull over the singleton setup and then something that calls it.

**Comment by designatednerd** [comment]
Hi @alexjameslittle, have you had any luck pulling this into a sample project?

**Comment by alexjameslittle** [comment]
Hi @designatednerd I haven't had chance yet, will get this over to you as quick as possible

**Comment by designatednerd** [comment]
@alexjameslittle I definitely fixed a leak in #1366 that I think is this same one - I'm not sure why it'd show up in a singleton but I'd appreciate you giving that branch a try to let me know how it works for you

**Comment by designatednerd** [comment]
This has shipped with `0.31.0` - if you're still having issues with that version, please open a new issue and we'll try to figure it out. Thank you!
