### ISSUE TITLE
Get underlying error from URLSessionClientError

### ISSUE THREAD

**Issue by asengmany** [apollographql/apollo-ios#1293]
Hi, I'm trying to handle errors when internet connection is off
I was wondering how can we get the localized description of the underlying error from ` func networkTransport(_ networkTransport: HTTPNetworkTransport, receivedError error: Error, for request: URLRequest, response: URLResponse?, continueHandler: @escaping (HTTPNetworkTransport.ContinueAction) -> Void)`

Because when printing the `error.localizedDescription` from this delegate function we get the message `The operation couldn’t be completed. (Apollo.URLSessionClient.URLSessionClientError error 2.)"` which is not a great message to display to users.

**Comment by designatednerd** [comment]
Ah i need to add some `LocalizedError` support to that in general, but you should be able to `switch` on the various cases of [`URLSessionClientError`](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/URLSessionClient.swift#L16) to figure out which error you're getting there.

**Comment by designatednerd** [comment]
(Note that even with the `URLSessionClientError` getting error descriptions, I'd still recommend switching on the error you get, because each of the error types comes with additional details, like an exact error returned by the system and/or data returned from your server)

**Comment by asengmany** [comment]
Thank you, by switching on the error I got what I wanted :). 

```
switch error {
case URLSessionClient.URLSessionClientError.networkError(let data, let response, let underlying):
   continueHandler(.fail(underlying))
default:
   continueHandler(.fail(error))
}
```

**Comment by designatednerd** [comment]
Cool - I'll close this out then, and the updated strings will ship with the next release. Thanks for pointing this out!
