### ISSUE TITLE
通过CocoaPods导入Apollo,无法使用

### ISSUE THREAD

**Issue by tanchendong1992** [apollographql/apollo-ios#1298]
通过CocoaPods导入Apollo,无法使用
在 Podfile 文件中添加 pod 'Apollo' 然后执行 pod install 成功将 Apollo库添加的工程中
Apollo 版本为: 0.29.0
<img width="973" alt="WeChat284af48949092fd37921ed2d51d52cff" src="https://user-images.githubusercontent.com/10558372/86865813-5518b780-c102-11ea-91ae-ee09824e5895.png">

**Comment by designatednerd** [comment]
Hi! I don't speak Chinese, but here's what Google Translate gave me for your question: 

> Importing Apollo via CocoaPods, cannot be used 
> Import Apollo via CocoaPods, cannot be used
> Add pod'Apollo' in the Podfile file and execute pod install to successfully add the Apollo library to the project
> Apollo version is: 0.29.0

I can't see what the error is in the screenshot you shared, it looks like it's probably that the Apollo lib can't be found. I would recommend a) Cleaning the build folder and if that doesn't work b) doing the [derived data dance](http://deriveddata.dance) to force CocoaPods to recompile all pods. 

If that solves it, please feel free to close this issue out. If you are still having problems with that after, please let me know what is happening. Thank you!

**Comment by tanchendong1992** [comment]
> derived data dance

提示 "No such module 'Apollo'"

**Comment by tanchendong1992** [comment]
> Hi! I don't speak Chinese, but here's what Google Translate gave me for your question:
> 
> > Importing Apollo via CocoaPods, cannot be used
> > Import Apollo via CocoaPods, cannot be used
> > Add pod'Apollo' in the Podfile file and execute pod install to successfully add the Apollo library to the project
> > Apollo version is: 0.29.0
> 
> I can't see what the error is in the screenshot you shared, it looks like it's probably that the Apollo lib can't be found. I would recommend a) Cleaning the build folder and if that doesn't work b) doing the [derived data dance](http://deriveddata.dance) to force CocoaPods to recompile all pods.
> 
> If that solves it, please feel free to close this issue out. If you are still having problems with that after, please let me know what is happening. Thank you!

<img width="554" alt="WeChat180868d07a599dedc7d100881486cd72" src="https://user-images.githubusercontent.com/10558372/86875517-48518f00-c115-11ea-8381-62c8bfad0291.png">
<img width="573" alt="WeChate1d3d977ab2dc2601c212b91d11303a5" src="https://user-images.githubusercontent.com/10558372/86875520-4a1b5280-c115-11ea-99a1-d8d073752632.png">
<img width="951" alt="WeChatfac8e717bdc589eddd27c62013f20854" src="https://user-images.githubusercontent.com/10558372/86875523-4b4c7f80-c115-11ea-9632-7dab9ec0c34b.png">

**Comment by designatednerd** [comment]
Hi, please see my response to #1303 for an answer to this.
