### ISSUE TITLE
通过 Swift Package Manager Install 导入 Apollo 后,在其他电脑上拉取代码后无法正常运行?

### ISSUE THREAD

**Issue by tanchendong1992** [apollographql/apollo-ios#1299]
通过 Swift Package Manager Install 导入 Apollo 后,在其他电脑上拉取代码后无法正常运行?
打开代码后,会自动 Fetching Apollo...

**Comment by designatednerd** [comment]
Again with Google Translate as I don't speak chinese: 

> After importing Apollo through Swift Package Manager Install, it cannot work properly after pulling code on other computers?
> After opening the code, it will automatically Fetching Apollo...

Yes, swift package manager will automatically check out the Apollo repo along with the other dependencies mentioned in it. This may take several minutes (or possibly longer, depending on the speed of your internet connection). This is done automatically for you in versions 11 and higher of Xcode. 

Does that answer your question?

**Comment by tanchendong1992** [comment]
> 再次使用Google翻译，因为我不会说中文：
> 
> > 通过Swift Package Manager安装导入Apollo之后，在其他计算机上提取代码后它无法正常工作吗？
> > 打开代码后，它将自动获取Apollo ...
> 
> 是的，swift软件包管理器将自动检出Apollo存储库以及其中提到的其他依赖项。这可能需要几分钟（或更长的时间，具体取决于Internet连接的速度）。Xcode 11及更高版本会自动为您完成此操作。
> 
> 这是否回答你的问题？

在其他电脑上打开是需要重新 检出依赖库的么? 那种方法可以在不用所有设备都检出包的,例如 pod 引入一样呢,我通过 pod 引入 Apollo 库后 ApolloWebSocket 无法找到 是为什么呢

**Comment by designatednerd** [comment]
Google translated: 

> Is it necessary to check out the dependent library again when opening it on other computers? The method can check out the package without using all devices. For example, the introduction of pods is the same. After I import the Apollo library through pods, ApolloWebSocket cannot be found. Why?

The pods question is addressed in my response to #1303. 

With Swift Package Manager, yes, the dependent library has to be checked out on other computers. There's not really a great way to check in dependencies for SPM unless you've got a custom Derived Data location, and even that relies on some undocumented setup which can be broken at any time. With CocoaPods you can easily check in dependencies using the `Pods` folder.  If checking in dependencies is a requirement for you, I would recommend using CocoaPods.
