### ISSUE TITLE
Variable type RxSwift name clashes

### ISSUE THREAD

**Issue by slashmo** [apollographql/apollo-ios#130]
This is a rather small issue, but I discovered that by using **apollo-ios** alongside [**RxSwift**](https://github.com/reactivex/RxSwift) you get naming clashes with the `Variable` type which is implemented in both frameworks. My current workaround is to use `RxSwift.Variable` everytime I want to create a RxSwift `Variable`, but that's just a bit inconvenient. 😬 

How about changing the **apollo-ios** `Variable` to `GraphQLVariable`?

**Comment by martijnwalraven** [comment]
This has been changed in Apollo iOS 0.70, currently in alpha.
