### ISSUE TITLE
通过 CocoaPods 导入 Apollo 丢失 WebSocket

### ISSUE THREAD

**Issue by tanchendong1992** [apollographql/apollo-ios#1303]
通过 CocoaPods 导入 Apollo 丢失 WebSocket
Podfile 文件中添加 pod 'Apollo', '~> 0.29.0'  执行pod install  完成后 在工程 Pods 中 只有 Apollo/Core 文件 无法找到 Apollo/WebSocket 
引用 import ApolloWebSocket 报错 " No such module 'ApolloWebSocket' "

如下图:
Podfile文件:
<img width="697" alt="WeChatf75880a9f15d2f78d3d97ec0cd4bc4d9" src="https://user-images.githubusercontent.com/10558372/86881431-eac33f80-c120-11ea-936d-3523e8861d25.png">

pod search Apollo
<img width="573" alt="pod_search_apollo" src="https://user-images.githubusercontent.com/10558372/86881554-2a8a2700-c121-11ea-9aeb-2b823275b8e5.png">

pod install 完成后
<img width="554" alt="pod_install" src="https://user-images.githubusercontent.com/10558372/86881586-3a097000-c121-11ea-810b-fb6c3d255f32.png">

使用代码
<img width="951" alt="code" src="https://user-images.githubusercontent.com/10558372/86881602-455c9b80-c121-11ea-8d9a-214c3480803e.png">

**Comment by designatednerd** [comment]
Google translated:

> Importing Apollo via CocoaPods loses WebSocket
> Add pod'Apollo' in the Podfile file,'~> 0.29.0' After executing pod install, only Apollo/Core files cannot be found in the project Pods.
> Quoting import ApolloWebSocket reports error "No such module'ApolloWebSocket'"
>
> As shown below:
> Podfile

You need to add the `Apollo/WebSocket` subspec in order to access the WebSocket library - it is not included by default, only the core libraries are included by default. So your podfile should look like this if you want to use the web socket library: 

```
pod 'Apollo', '~>0.29.0'
pod 'Apollo/WebSocket', '~>0.29.0'
```

**Comment by tanchendong1992** [comment]
ok
