### ISSUE TITLE
How Can I set authorisation header for Apollo Client?

### ISSUE THREAD

**Issue by Prathap-iOS** [apollographql/apollo-ios#1313]
I am using Apollo Client. I got the access token after login. I have set the access token as authorisation header like this.

func setApolloClient(accessToken: String) {
        self.apolloClient = {
            let authPayloads = ["Authorization": "Bearer \(accessToken)"]
            let configuration = URLSessionConfiguration.default
            configuration.httpAdditionalHeaders = authPayloads
            configuration.requestCachePolicy = .reloadIgnoringLocalCacheData
            let endpointURL = URL(string: graphEndpoint)!
            return ApolloClient(networkTransport: HTTPNetworkTransport(url: endpointURL))
            }()
    }

I am sending this authorisation header to a query to get the user details. It return success. But, I have no idea where it went wrong. I am not getting user details. I am getting Try again later. @designatednerd  Is there any other way to set authorisation header?

**Comment by designatednerd** [comment]
I suspect 

```swift
let authPayloads = ["Authorization": "Bearer (accessToken)"]
``` 

should be 

```swift
let authPayloads = ["Authorization": "Bearer \(accessToken)"]`
```

Otherwise you're sending the literal string `(accessToken)` as your access token rather than using string interpolation, which looks like what you want to do. 

If that's not the issue, let me know and I can dig deeper - other than that your setup seems pretty straightforward.

**Comment by Prathap-iOS** [comment]
@designatednerd I used let authPayloads = ["Authorization": "Bearer \(accessToken)"]. But this one also not working.

**Comment by designatednerd** [comment]
You still need the `\` before the first paren in `(accessToken)`, otherwise it'll be sent as a string literal. 

Are you able to use a proxy tool like [Charles](https://www.charlesproxy.com/) or [MiTM Proxy](https://mitmproxy.org/) to see what the final headers going out over the network are?

**Comment by Prathap-iOS** [comment]
Yeah I used let authPayloads = ["Authorization": "Bearer \(accessToken)"]. But There is no proper result. I am not using any proxies.

**Comment by designatednerd** [comment]
I was asking if you could try using a proxy to see if you can see what the final headers are - that way you can see exactly what's going over the network. 

I would also double check with your backend that they take the token as a `Bearer` token - that's standard practice, but I've definitely seen a lot of backends that don't adhere to that.

**Comment by Prathap-iOS** [comment]
@designatednerd my backend team is following the same standard. They taken token as **Bearer** token.

**Comment by designatednerd** [comment]
OK I was double checking what you're doing, and I missed the most obvious thing: The `URLSessionConfiguration` is not being passed into anything, so the configuration you're correctly setting up is not being given to anything to be used. Instead of this at the very end: 

```swift
return ApolloClient(networkTransport: HTTPNetworkTransport(url: endpointURL))
```

try this: 

```swift
let client = URLSessionClient(sessionConfiguration: configuration)
return ApolloClient(networkTransport: HTTPNetworkTransport(url: endpointURL), client: client)
```

**Comment by Prathap-iOS** [comment]
@designatednerd Thanks. It's working fine. 

Here is my working code for setting up authorization header.

          `let tokenValue = SessionManager.shared.getToken().TokenValue
            let authPayloads = ["Authorization": "Bearer \(tokenValue)"]
            let configuration = URLSessionConfiguration.default
            configuration.httpAdditionalHeaders = authPayloads
            configuration.requestCachePolicy = .reloadIgnoringLocalCacheData
            let client = URLSessionClient(sessionConfiguration: configuration)
            let endpointURL = URL(string: graphEndpoint)!
            return ApolloClient(networkTransport: HTTPNetworkTransport(url: endpointURL, client: client))`

**Comment by designatednerd** [comment]
@Prathap-iOS great! Mind if we close this out?

**Comment by designatednerd** [comment]
Since @Prathap-iOS has noted that solution works, I'm going to go ahead and close this out. If you're having a similar problem, please open a new issue. Thank you!
