### ISSUE TITLE
 Getting 'No operations found to generate` error when trying to use `ID` in query

### ISSUE THREAD

**Issue by dpatel-git** [apollographql/apollo-ios#1320]
I am working on an iOS application to communicate with our GraphQL backend using Apollo's GraphQL library. With the query below, I am able to generate Swift code that I can use to query backend.

`query mobileApp {
      app(id: "content/mobileApp") {
        title
     } 
}`

I am using the following commands to generate Swift code

`../../Pods/Apollo/scripts/apollo/bin/run client:codegen --target=swift --includes ../app.graphql --localSchemaFile=./downloaded_schema.json API.swift`

However, if I replace the string literal passed into the app(...) with ID like this

`query mobileApp {
  app(id: ID!) {
    title
  } 
}`

running the same codegen command fails with the following error.

`Generating query files with 'swift' target
    → No operations or fragments found to generate code for.
Error: No operations or fragments found to generate code for.
    at write (~/Downloads/ios-app/Pods/Apollo/scripts/apollo/lib/commands/client/codegen.js:65:39)
    at Task.task (~/Downloads/ios-app/Pods/Apollo/scripts/apollo/lib/commands/client/codegen.js:90:46)`

It seems that the script is not able to find a declaration of ID.  Hoping that someone can point me in the right direction, thanks

**Comment by designatednerd** [comment]
I'm not sure why it's saying there are no operations rather than there's an error in your declaration, but there's an error in your declaration. 

To pass in a parameter, you need to declare that parameter in the query's declaration, then pass it into the query itself: 

```graphql
query mobileApp($id: ID!) { 
  app(id: $id) {
    title
  }
}
```

Hope that gets you going!

**Comment by dpatel-git** [comment]
I think codegen script could be defaulting to `No Operations ...` error if it's able to come to a conclusion. 

Anyways, making the changes you suggested fixed the error.

Super thanks.
