### ISSUE TITLE
Fragments imported into multiple graphql queries

### ISSUE THREAD

**Issue by piv199** [apollographql/apollo-ios#1322]
Hi, quite new to graphql and trying to establish best practices in the project.

Have found an article about fragments: https://www.apollographql.com/docs/ios/fragments/

I wonder whether there is an ability to import Fragment.graphql (which defines fragment only) into another graphql file with query that uses that fragment?

```
Fragment.graphql
fragment A { }
```

```
Query.grapqhl
query {
   property {
       ...A
   }
}
```

**Comment by designatednerd** [comment]
Yep, as long as they're in the same module you should be able to do that!

**Comment by designatednerd** [comment]
(you won't need to import fragment.graphql, the codegen should be able to see all fragments defined in the module)

**Comment by piv199** [comment]
@designatednerd Thanks! Sorry for opening the issue... I did all right but the problem was in fragment naming - it was the same as model entity thus I had segmentation fault and not found errors... Thanks for help!
