### ISSUE TITLE
Keys with nil values are removed

### ISSUE THREAD

**Issue by docallag** [apollographql/apollo-ios#1323]
Hi,
I'm just wondering why keys with nil values are removed on queries/mutations? 

Specifically the **withNilValuesRemoved** extension method in **GraphQLInputValue.swift**

Thanks,
Dave

**Comment by designatednerd** [comment]
Good question! So you can see a little bit of why in [this test](https://github.com/apollographql/apollo-ios/blob/main/Tests/ApolloTests/InputValueEncodingTests.swift#L74) and [this test](https://github.com/apollographql/apollo-ios/blob/main/Tests/ApolloTests/InputValueEncodingTests.swift#L80). 

For input values, passing `nil` and passing `.some(nil)` have different meanings. Passing `nil` means "I am not providing a value here." Passing `.some(nil)` means "I am providing a value, and it is explicitly nil." The `nil`s are filtered out, the `.some(nil)`s are not.

This has effects on the server side: If you send `null` to the server, it will overwrite whatever was already in your server-side database with `null`. If you don't send anything to the server, anything which was already there and isn't explicitly being changed will remain untouched. 

In the swift Codegen stuff I'm working on there's going to be a [`GraphQLOptional`](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCore/GraphQLOptional.swift#L3) type that should capture this a bit more clearly than the current codegen, but unfortunately that's still a ways out (😭). 

Does that make more sense?

**Comment by docallag** [comment]
Oh that's perfect! I can use `.some(nil)` to stop it being filtered out.

Thanks so much for the quick reply 🤩
