### ISSUE TITLE
Does every table need an "id" or "_id" field for its data to be cached properly?

### ISSUE THREAD

**Issue by joshuarobs** [apollographql/apollo-ios#1326]
According to Apollo Client React here: https://www.apollographql.com/docs/react/caching/cache-configuration/#generating-unique-identifiers the way data is identified and if any changes have been made is as described:

````
To do so, it combines the object's __typename with its id or _id field (whichever is defined).
These two values are separated by a colon (:).
````

There seems to be an option for React where a different field other than `id` can be used, especially if there is another field set as the primary key on the db.

Is there a way to do this for Apollo iOS? If not, does that mean we have to make all tables in our database have some sort of `id` or `_id` field?

**Comment by designatednerd** [comment]
Hi! This is handled rather differently on iOS at the moment. Here's [a detailed doc about our caching on iOS](https://www.apollographql.com/docs/ios/caching/). 

The short answer of how to set a custom key is to take a look at the [Controlling Normalization section](https://www.apollographql.com/docs/ios/caching/#controlling-normalization), where you can find information about the `cacheKeyForObject` function you can use to set custom cache keys on iOS. 

Does that answer your question?

**Comment by joshuarobs** [comment]
Yes it does, thanks!

**Comment by joshuarobs** [comment]
@designatednerd Also, forgot to ask one more quick question: is `cacheKeyForObject` set only once throughout the whole Apollo object? That is, if we set it to `id`, does that mean every table that ever gets queried needs to have an `id` field? What about if we have most tables with a unique `id` but some tables don't have it and use other primary keys?

**Comment by designatednerd** [comment]
There is only one closure per store (set through the client), but you can do some stuff by extracting the value of `__typename` from the JSON you get in order to have it work differently for different things. 

You also can just return `nil` if `id` is nil, and a default cache key based on the path of the request will be generated.
