### ISSUE TITLE
ReadTransaction Memory Leak in 0.6.2

### ISSUE THREAD

**Issue by ephemer** [apollographql/apollo-ios#133]
At the moment every Apollo query is leaked by `ReadTransaction`. We have queries attached to UICollectionView items which are recycled on scroll, meaning we end up with thousands of leaked queries (10s or even 100s of MB RAM).

You can see the leak in any app using 0.6.2 by shooting off some (probably any) queries and then clicking on Xcode's memory graph view and then clicking "Show Only Leaked Blocks" at the bottom-right of the left sidebar. You will see a bunch of leaks relating to DataLoader, locks, Promises etc.

The reason for the leak appears to be a circular reference in ApolloStore.swift's `ReadTransaction` class:

```
    fileprivate lazy var executor: GraphQLExecutor = {
      let executor = GraphQLExecutor { object, info in
        let value = object[info.cacheKeyForField]
        return self.complete(value: value)    // <------------------------- here
        //        ^^^^ self has a reference to executor, which  
        //        in turn has a reference to self
      }
      
      executor.dispatchDataLoads = self.loader.dispatch
      executor.cacheKeyForObject = self.cacheKeyForObject
      return executor
    }()
```

If we change the above code to the following, the cycle is broken and memory is no longer leaked:

```
    fileprivate lazy var executor: GraphQLExecutor = {
      let executor = GraphQLExecutor { [weak self] object, info in
        let value = object[info.cacheKeyForField]
        return self?.complete(value: value) ?? .result(.success(value))
      }
      
      executor.dispatchDataLoads = self.loader.dispatch
      executor.cacheKeyForObject = self.cacheKeyForObject
      return executor
    }()
```

I'm just not sure what self.complete is doing in this case, and what is expected of the returned data. So I'm pretty sure this isn't Pull Request-worthy as is.

Another option would be to make `GraphQLResolver` return an optional result, or to otherwise remove the circular reference. This would require more understanding of what's going on than we have.

**Comment by ephemer** [comment]
@martijnwalraven this is the issue I mentioned to you on the Slack channel

**Comment by martijnwalraven** [comment]
@ephemer: Thanks for tracking this down! That's a pretty obvious bug. I think we can get away with using `[unowned self]` here instead of `weak`, because the resolver will only be invoked when the executor is alive.

**Comment by martijnwalraven** [comment]
This turned out to be a little more complicated than I thought, because `ReadTransaction` does need to be kept alive while the query is executing, potentially asynchronously, so we can't use `[unowned self]` (or `[weak self]`). But I believe I fixed the memory leak by not storing `executor` as an instance variable.

Could you give 0.6.3 a try in your app?

**Comment by ephemer** [comment]
Hey Martijn, sorry about the very late reply on this one. I’ve been sick and off work.

The fix looks like it’ll fix the issue. As far as I understand we’ve gone with a JavaScript Apollo client for now but good to know we’ll be leak free if we need to go back to native!
