### ISSUE TITLE
Apollo Codegen generates different Operation IDs than Apollo Server

### ISSUE THREAD

**Issue by Nickersoft** [apollographql/apollo-ios#1334]
Hey all,

Tonight I noticed that the operation ID Apollo Codegen creates when generating Swift code for your schema is slightly different than what the Apollo Server expects, causing APQs to fail and throw a `provided sha does not match query` error. 

Basically the SHA that Apollo Codegen creates adds line breaks between each GraphQL operation before it calculates the SHA of the string (seen [here](https://github.com/apollographql/apollo-tooling/blob/8e78c50a21c17a071f7b6890de446b4582e8d04a/packages/apollo-codegen-core/src/compiler/visitors/generateOperationId.ts#L26)). However, when Apollo iOS sends queries to the server, it does so without any line breaks using Swift's `.appending()` method. Then when the server calculates the SHA, due to the lack of line breaks, the operation ID is different and the error is thrown. Strangely enough, however, I noticed the StarWars API actually [manually adds line breaks](https://github.com/apollographql/apollo-ios/blob/06c357b7e98fb7abcddc02ca8aeb96cc8475d263/Sources/StarWarsAPI/API.swift#L1051) in its generated code, which mine doesn't. 

I believe I'm using the latest version of Apollo Codegen and Apollo iOS. I'm happy to patch a fix – it's just a matter of what needs to be changed. I'm afraid touching `apollo-tooling` would affect more repos that might depend on it, so I thought it'd be safer to open an issue here and propose adding the line breaks to the generated Swift.

**Comment by Nickersoft** [comment]
Closing, as it looks like the `apollo-tooling` upstream does add a line break during Swift Codegen, but the CLI on my system may be out of date. Will reopen if cannot find a resolution.

**Comment by designatednerd** [comment]
@Nickersoft I would strongly recommend using the version the SDK downloads - it's set up to make sure you don't have to fight with node and mess with "which version of the CLI works with which version of the SDK?". You can check out the most recent version of our [installation docs](https://www.apollographql.com/docs/ios/installation/) or our new [Swift scripting docs](https://www.apollographql.com/docs/ios/swift-scripting/) to see how to set this up. 

I'd also recommend using version `0.29.x` of the iOS SDK - this includes some fixes that ensure the hash that you get from your iOS operation matches what's generated by the CLI, even with Fragments.

**Comment by Nickersoft** [comment]
@designatednerd Hey, thanks for the comment despite me opening an issue a little prematurely haha – I didn't realize the Apollo version set in the Codegen `Package.swift` affects the version of the CLI it downloads, and sure enough, I was on 0.28.x when the newline fix was pushed on 0.30.x. Updating it to download the new CLI fixed the problem :)

**Comment by designatednerd** [comment]
Yeah you bet - thought it would be helpful for anyone who stumbles across this via google :P
