### ISSUE TITLE
Serialize/Deserialize GraphQLQuery

### ISSUE THREAD

**Issue by flohei** [apollographql/apollo-ios#134]
Is there any way to serialize/deserialize a custom `GraphQLQuery` object into and from a file? I'd like to keep a few in files and restore them for my Unit Tests to make sure our converter/parser works as expected.

Thanks!

**Comment by martijnwalraven** [comment]
@flohei: Can you explain in more detail what you're trying to do here? If you're looking for a way to initialize a query result from parsed JSON, you should be able to use the `<...>Query.Data(jsonObject: ...)` initializer.

**Comment by flohei** [comment]
I wanted to take one of our API answers and serialize it into a file so that I could use this example in my Unit Tests to verify that my parser works correctly. I think I don't have access to the raw JSON that comes back from the API endpoint, do I? I poked around in the callback and all I got there was the already converted data.

**Comment by martijnwalraven** [comment]
@flohei: You should be able to call `.jsonObject` on the result data.

Out of curiosity, what does your converter/parser do?

**Comment by flohei** [comment]
Okay, thank you! I'll give that another shot.

The parser – or converter, rather – converts the objects we get here into the data structure our app used before for compatibility's sake. We're currently evaluating GraphQL for a small segment of our app and wanted to keep the friction as low as possible for now.

**Comment by flohei** [comment]
@martijnwalraven: I can't access `.jsonObject` because it's internal. So I guess it's not meant for use by third parties, right?

**Comment by martijnwalraven** [comment]
@flohei: Ah, I didn't realize that because I only use it in tests and import `Apollo` as `@testable`. But it probably makes sense to make these methods public. Should be fixed in 0.6.4.

**Comment by flohei** [comment]
Ah nice, thank you! Once it's accessible for me I'll try it again. Does it automatically translate sub-properties of your custom types into simple JSON as well, then?

**Comment by martijnwalraven** [comment]
Yes, it should give you the complete tree. I hope it works :)

**Comment by flohei** [comment]
It works just nicely. Thank you very much for your assistance! :)

**Comment by martijnwalraven** [comment]
Good to hear!
