### ISSUE TITLE
Getting "The request timed out." sometimes while calling query and mutation.

### ISSUE THREAD

**Issue by DiwakarThapa** [apollographql/apollo-ios#1346]
Hello!!! 
Sometimes when I open the app I cannot get the **response of the first query** it requests rather I get the following **timeout error message** on Xcode debug console. I tried every possible solution found on StackOverflow but could find any effective solution and also could not figure out why **"The request timed out."** has occurred in the first place. Our Android team is also experiencing similar issues. On the **server-side**, the timeout interval is **65 seconds**. so, I set request timeout interval **65 seconds** but it didn't work. 

**Console Error**
```
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2103, NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1874F8BE-FA0F-45E1-8A51-96F290D85883>.<2>, NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1874F8BE-FA0F-45E1-8A51-96F290D85883>.<2>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://example.graphql, NSErrorFailingURLKey=https://example.graphql, _kCFStreamErrorDomainKey=4}
```
**Is this apollo-ios terminating the request itself or server-side error?**

**Comment by designatednerd** [comment]
This is an error from Apple's URL loading system, the timeout is happening there. Are you saying that the timeout is happening before the 65 seconds that you set it to? Or just that it's still happening? The fact that your Android app is also having a similar problem points pretty squarely at your server.

Also am I correct in assuming that the url string here `https://example.graphql` is a placeholder for your real URL?

**Comment by DiwakarThapa** [comment]
Thanks for response!! 
`https://example.graphql` is a placeholder for our real URL? I don't know whether the timeout is happening before the 65 seconds but whenever the error appears the API processing time is around 66 to 69 sec.

**Comment by designatednerd** [comment]
Yeah that sounds like the request timeout is working as expected and the issue is that the request is, in fact, timing out, and that the issue is most likely going to be on your server side.

**Comment by DiwakarThapa** [comment]
thank @designatednerd

**Comment by DiwakarThapa** [comment]
@designatednerd I forget to mention one thing, on graphql playground if we request the same query or mutation the response appears without "The request timed out. " error but on the app side error appears. why is that?

**Comment by designatednerd** [comment]
GraphQL playground generally runs on your the same server as your endpoint, so in theory it's just making local calls. It's also possible that there's some kind of credential that is available through the web that's not going through to mobile. I wish I could narrow it down for you but unfortunately there are about a zillion things that could go wrong here.

**Comment by DaTebe** [comment]
@DiwakarThapa did you find a solution for your Problem? In our application, we have the same behaviour. Sometimes we run into a timeout, but the GraphQL Playground is always working.

**Comment by vishalverma-mk062** [comment]
For **Swift 3.x** / **Swift 4.0** / **Swift 5.0** users with **Alamofire >= 5.0**

Used request modifier to increase and decrease the timeout interval.

**Alamofire's** request creation methods offer the most common parameters for customization but sometimes those just aren't enough. The URLRequests created from the passed values can be modified by using a RequestModifier closure when creating requests. For example, to set the **URLRequest's** **timeoutInterval** to 120 seconds, modify the request in the closure.

    var manager = Session.default
     manager.request(urlString, method: method, parameters: dict, headers: headers, requestModifier: { $0.timeoutInterval = 120 }).validate().responseJSON { response in


**OR**

RequestModifiers also work with trailing closure syntax.

    var manager = Session.default
         manager.request("https://httpbin.org/get") { urlRequest in
        urlRequest.timeoutInterval = 60
        urlRequest.allowsConstrainedNetworkAccess = false
    }
    .response(...)

**Comment by designatednerd** [comment]
Alamofire probably won't help here, it's not really being used. You can set a `defaultTimeoutInterval` on a `URLSessionConfiguration`, which you then pass into `URLSessionClient`. 

Again, GraphQL playground not timing out is because there's basically zero time between sending the request and receiving the response because it runs on the same server. For real requests on a device or a simulator, things do occasionally time out.

**Comment by DaTebe** [comment]
The thing is, while developing my software, everything is running locally. There should be no timeout at all. I do not have queries that take more than a glimps of a second normally. But sometimes it seems as if my requests are just going lost.

I think I just need to dig deeper into network communication. A lot of services in the backend are running in a docker environment. Maybe something is wrong there.
