### ISSUE TITLE
extensions property on GraphQLResult

### ISSUE THREAD

**Issue by paulkite** [apollographql/apollo-ios#1348]
Hello! Curious if there are any plans to implement the `extensions` hash map support on `GraphQLResult`. I see the Android implementation has this and would love to be able to have the same ability to use this as well.

Thanks!

**Comment by designatednerd** [comment]
This [is implemented on `GraphQLError`](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/GraphQLError.swift#L33) on our end. Are you using it in a non-error capacity?

**Comment by paulkite** [comment]
Yes. Our team sends non-error information through `extensions`.

**Comment by designatednerd** [comment]
OK - looking at [the spec](https://spec.graphql.org/June2018/#sec-Response-Format) it does appear `extensions` is allowed at the root of the response. 

I'm somewhat swamped at the moment - if you want to make a PR you're more than welcome to (just make sure to add tests!) but I'll try to get to it as I can if not.

**Comment by paulkite** [comment]
Thank you so much for the response!

**Comment by paulkite** [comment]
@designatednerd Just curious, what's the usual turnaround on PRs from the community to getting into a release?

**Comment by designatednerd** [comment]
Usually fairly quick if they're small. It'd almost certainly be faster than waiting for me to have bandwidth 😛

**Comment by designatednerd** [comment]
This shipped as part of 0.32.0!
