### ISSUE TITLE
Cache and queries, unable to fetch record by ID.

### ISSUE THREAD

**Issue by pgawlowski** [apollographql/apollo-ios#1350]
So let's start with sth like this. Fetch and cache using SQLite normalized cache.
```
query Sync {
	viewer {
		things {
			nodes {
				id
      }
    }
  }
}

```
Here is our cacheKeyForObject

 ```
       client.cacheKeyForObject = { (object) in
          if
            let id = object["id"] as? String,
            let type = object["__typename"] as? String {
              return [id, type]
          }
          // No id or typename, don't do caching
          return nil
        }        

```
I also tried the basic one 
`client.cacheKeyForObject = { $0["id"] }`

We've got (or at least out backend claims that we've got) unique ID's.
Next I want to perform query with cachePolicy: `.returnCacheDataDontFetch`.

```
query ThingActionConnection($thingId: ID!) {
  thing: node(id: $thingId) {
    ...on Thing {
      id
    }
  }
} 
```

Result is `GraphQLResultError(path: thing, underlying: Apollo.JSONDecodingError.missingValue)`
The more I dig down into apollo and caching the less I know how exactly this supposed to work. 

Network call is giving us correct results. What is more I checked local sqliteDB and there is a results with this particular `$thingId`. 

Android developer is getting results with ease. On our side, JSONDecodingError. 
I am nearly 100% sure that the problem is with cacheKeyForObject or ios apollo is unable to handle nodes here?

@edit
Same goes for 
```

query ThingActionTest($thingId: ID!) {
  viewer {
    thing(id: $thingId) {
      id
    }
  }
}

```

@edit 2:

Interesting fact is - direct cache access with same id works totally fine.

```
  apolloClient.store.withinReadTransaction({ transaction in
            do {
                let variables = ["isReady": false]
                let data = try transaction.readObject(ofType: ThingAction.self, withKey: actionId, variables: variables)
                print(data)
            } catch {
                print(error.localizedDescription)
            }
        })
```
This is only giving me more confusion about query execution on cache.

I also noticed that direct cache access using query is giving me some confusing error.
`Error at path "thing)": missingValue`
Why it is printing ')' character there? 
@edit ok it's just a typo in GraphqlExecutor.swift line 36.

**Comment by designatednerd** [comment]
> The more I dig down into apollo and caching the less I know how exactly this supposed to work.

Welcome to my last year, my friend 🙃. And also to why I'm planning to simplify a bunch of stuff in the Cache as part of phases 2-3 of the swift codegen rewrite if it's at all possible.

I can tell you for sure that iOS and Android have no cache compatibility guarantees right now, and that I *think* the issue is that you're using a fragment on a node, and that you don't have the `id` on the node itself - that means that the node won't have an ID, and it won't go into the cache.

**Comment by pgawlowski** [comment]
I finally figured it out. The problem was missing variables. 

However what I noticed is that sometimes when I am asking for data one by one I am getting
`GraphQLResultError(path: lock.id, underlying: Apollo.JSONDecodingError.missingValue)` without any particular reason. Because starting exactly the same `withinReadTransaction` few seconds later is giving me correct response.

**Comment by designatednerd** [comment]
Is it giving you that error maybe because the data has not yet been populated?

**Comment by pgawlowski** [comment]
Data is populated. 
I am executing exactly the same load and it can give a results like:
"I've got data."
"I've got data."
"I've got data."
GraphQLResultError(path: lock.id, underlying: Apollo.JSONDecodingError.missingValue)
GraphQLResultError(path: lock.id, underlying: Apollo.JSONDecodingError.missingValue)
"I've got data."

No fetching or repopulating cache in between.
User is offline and no cache manupulations are happening. I just wondered if there is a chance of some sort data access race here?

I digged down ino the sql file and found that when I am getting this error the reference ID of one object is missing and right after getting data back there is a new one, different than previous (before missing value) one.

**Comment by designatednerd** [comment]
There is definitely a possibility of a data race, there are some known issues with threading in the cache at the moment.

I'd really need to see your exact code to figure out what's going on with your references - the reference ID should be stable, but any number of things could be happening here to mess that up.

**Comment by designatednerd** [comment]
@pgawlowski Were you ever able to resolve this issue? Anything I can do to help here or do you mind if I close this out?

**Comment by pgawlowski** [comment]
Hey @designatednerd 
Actually yes. The main problem was old cache + messed id's. 
Thank you for your help.
