### ISSUE TITLE
How to download schema.json with apollo client for an endpoint with url params and multi headers?

### ISSUE THREAD

**Issue by XiaoxiaYao** [apollographql/apollo-ios#1358]
Hi,

I am trying to download a schema.json file from an endpoint. However, I don't know how to config the the url params and multi headers? Please check the pic below:
![image](https://user-images.githubusercontent.com/22899096/89851786-e5de2980-dbbf-11ea-9a36-1c3499af4dc2.png)
I am able to use graphql in graphiql. But don't know how to config in terminal. I tried:
`apollo client:download-schema --endpoint=https://xxxxxxxxxxx/graphql/ --header='xxxxx-API-Key:xxxx;xxxxx-k:xxxxxx' --data='co=US'`
However still no luck. Can anyone help me with this? I did not any doc about this ...so I am here. I don't know how to specify co=US and how to separate the headers with ,(comma) or ; (semi comma)     Thank you in advance. Thanks.

**Comment by designatednerd** [comment]
Hi! Each header must be passed in separately like so: `--header="Header-Key: Header Value" --header="Header-Key-2: Header Value 2"`

There is also a way to set this up using the [Swift Scripting lib](https://www.apollographql.com/docs/ios/swift-scripting) using the [`ApolloSchemaDownloader`](https://www.apollographql.com/docs/ios/swift-scripting/#downloading-a-schema).

**Comment by XiaoxiaYao** [comment]
> Hi! Each header must be passed in separately like so: `--header="Header-Key: Header Value" --header="Header-Key-2: Header Value 2"`
> 
> There is also a way to set this up using the [Swift Scripting lib](https://www.apollographql.com/docs/ios/swift-scripting) using the [`ApolloSchemaDownloader`](https://www.apollographql.com/docs/ios/swift-scripting/#downloading-a-schema).

Thank you. Sorry, one more thing. Do you know how to deal with url params? co=US? How should I set it?

**Comment by designatednerd** [comment]
URL params should just be the same as a normal URL - `https://example.com?paramName=paramValue&param2name=param2Value`

**Comment by XiaoxiaYao** [comment]
Cool. I will have a try. Thank you @designatednerd. Have a nice day!

**Comment by designatednerd** [comment]
@XiaoxiaYao Mind if we close this issue out then?

**Comment by designatednerd** [comment]
I'm gonna close this out - @XiaoxiaYao  if you have further problems please reopen. Anyone else experiencing similar problems, please open a new issue. Thank you!
