### ISSUE TITLE
Cancel current query

### ISSUE THREAD

**Issue by horaciosolorio** [apollographql/apollo-ios#136]
Hello i really like a lot Apollo thanks for the support.

I need your feedback,  i am make some apollo.fetch(query: request),  but i some times i need to cancel current fetch and make a new one, how can i cancel current fetch.

Please help me with this issue.

**Comment by martijnwalraven** [comment]
Thanks, glad you find it useful! The result of `apollo.fetch()` should be [`Cancellable`](https://github.com/apollographql/apollo-ios/blob/a9de121be64f621379fe5ea7373fed27e7f7dfad/Sources/Apollo/ApolloClient.swift#L3-L7), so you can call `cancel()` on it.

**Comment by horaciosolorio** [comment]
Can you give a example please i dont have clear how can i cancel inside of apollo.fetch(), i was thinking there any way of call some metod like apollo.cancel().

**Comment by martijnwalraven** [comment]
You can call `cancel()` on the return value of `apollo.fetch()`, so:
```swift
let fetching = apollo.fetch(...)
...
fetching.cancel()
```

**Comment by horaciosolorio** [comment]
Dear martin i have this query 

let fetching = apollo.fetch(query: request) { (result: GraphQLResult?, error: Error?) in
            if let error = error {
                print("Error")
                return
            }
            guard let lugares = result?.data?.place else {
                print("Error")
                return
            }
            print("Done"
        }


And xcode give a warning fetching:
Constant 'fetching infered to have type '()', whicmay be unexpected

and also 

feching.cancel() 

give me error of: Value of tuple '()' as no member cancel.

Sorry i know look your solution is very simple but i dont catch where i have error.

**Comment by horaciosolorio** [comment]
Dear martin i have this query 

let fetching = apollo.fetch(query: request) { (result: GraphQLResult?, error: Error?) in
            if let error = error {
                print("Error")
                return
            }
            guard let lugares = result?.data?.place else {
                print("Error")
                return
            }
            print("Done"
        }


And xcode give a warning fetching:
Constant 'fetching infered to have type '()', which may be unexpected

and also 

feching.cancel() 

give me error of: Value of tuple '()' as no member cancel.

Sorry i know look your solution is very simple but i dont catch where i have error.

**Comment by martijnwalraven** [comment]
It's pretty hard to read your code without formatting, but it looks ok. What version of Apollo iOS are you using?

**Comment by horaciosolorio** [comment]
I am using pod for installation 

pod 'Apollo', '~> 0.6.0'

**Comment by designatednerd** [comment]
Since @horaciosolorio indicated this issue was resolved, I'm going to close this issue. Please feel free to reopen if you're still having issues here. Thanks!
