### ISSUE TITLE
Cannot load underlying module for 'Apollo' for unit test target

### ISSUE THREAD

**Issue by dpatel-git** [apollographql/apollo-ios#1363]
Hello folks,

I have following setup.

Xcode 11.3.1 (also tried on 11.6 without success)
Apollo 0.29.1
Cocoapods 1.9.2

I am able to compile and run my application, but get the following error when I try to compile the unit test target

```<unknown>:0: error: cannot load underlying module for 'Apollo'```

Here is how I have declared the app and test targets in podfile

```
target 'MyApp' do
    pod 'Apollo', Apollo
    target 'MyAppTests' do
      pod 'OHHTTPStubs', OHHTTPStubs
    end
end
```
I have set `MyApp` as host application for the test target

Any help is appreciated, thanks

**Comment by designatednerd** [comment]
It looks like your `MyAppTests` is missing an `inherit! :search_paths`. See the 2nd example [in the Podfile docs](https://guides.cocoapods.org/using/the-podfile.html).

**Comment by dpatel-git** [comment]
Thanks, that fixed the issue.
