### ISSUE TITLE
GraphQLQueryWatcher doesn't update its dependent keys

### ISSUE THREAD

**Issue by teodorpenkov** [apollographql/apollo-ios#1365]
With the `0.23.0` release Apollo changed the way it stores keys in the `QueryWatcher` https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/GraphQLQueryWatcher.swift#L73-L83

The problem with this is that the watcher doesn't update its `dependentKeys` like it should. There is a commit that does that but I couldn't follow why it was changed:
https://github.com/apollographql/apollo-ios/commit/2b07e69e71a0621795b7089fda84c0ca744ba202

The problem that we are experiencing is that we are updating a query in the store with `ReadWriteTransaction` and in the previous versions the updated query captured the newly dependent keys, therefore when a change occured it was propagated to the result handler and now it's not.

What's the reason behind this change and how can we workaround this? Was there a problem with the previous implementation in 0.22.0 https://github.com/apollographql/apollo-ios/blob/0.22.0/Sources/Apollo/GraphQLQueryWatcher.swift#L66-L68

**Comment by designatednerd** [comment]
Hi, the commit you referenced was part of #1156 which went out with `0.28.0`, not `0.23.0`. You can see a detailed explanation of the bug in #1155. 

What version are you actually on right now?

**Comment by teodorpenkov** [comment]
I'd either suggest reverting to `0.22.0`'s implementation https://github.com/apollographql/apollo-ios/blob/0.22.0/Sources/Apollo/GraphQLQueryWatcher.swift#L66-L68

or adding `self.dependentKeys = graphQLresult.dependentKeys` before this line https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/GraphQLQueryWatcher.swift#L79

If you don't see problem with that I'm happy to open a PR.

**Comment by teodorpenkov** [comment]
Hmm, actually I think the problem is somewhere else, I'll spend more time this week to figure it out.

**Comment by teodorpenkov** [comment]
@designatednerd thanks for the links that you shared.  I've check therm and I found the root cause of the problem.

<img width="917" alt="Screen Shot 2020-08-25 at 17 05 17" src="https://user-images.githubusercontent.com/5622288/91184760-a5b99380-e6f5-11ea-8611-75a66b6313ee.png">

I'm pretty sure that if we bring back those lines it wouldn't break anything.

**Comment by designatednerd** [comment]
Hi! Sorry, I was on vacation last week. 

I read [your explanation](https://github.com/apollographql/apollo-ios/pull/1156#discussion_r476476875) here and I think I get it. I'll take a look at this today or tomorrow and see what I can figure out.
