### ISSUE TITLE
Ambiguous for type lookup in this context error

### ISSUE THREAD

**Issue by Shiaulis** [apollographql/apollo-ios#1368]
Hey hey! Another question from my side :) 
In our backend response contains 2 data fields `userCompanies` and `userCompany` that share type. 
![image](https://user-images.githubusercontent.com/13601748/90987179-b81abc80-e591-11ea-9e96-ded615f5630e.png)
The problem is that code generation creates 2 totally equal structures:
![image](https://user-images.githubusercontent.com/13601748/90987269-573fb400-e592-11ea-8292-1a365a37b737.png)

In documentation explorer in GraphiQL I don't see any issues:
![image](https://user-images.githubusercontent.com/13601748/90987304-9837c880-e592-11ea-9f5f-af004aa50ca8.png)

So should I still look for a fix on backend side? Is there any way to explain that these data fields share type?

**Comment by kylebrowning** [comment]
Im getting the exact same problem.

```swift
public struct Author: GraphQLSelectionSet {
                public static let possibleTypes: [String] = ["Staff", "Customer"]
public struct Author: GraphQLSelectionSet {
                public static let possibleTypes: [String] = ["ArticleAuthor"]
```

**Comment by designatednerd** [comment]
Yeah - this is where the depluralization for type names we're using in the typescript codegen kind of falls apart. The workaround is to use field aliases:

```graphql
query MyQuery {
   user {
      id
      userCompany: company // <-- alias
      userCompanies
   }
}
```

This way the type for `userCompany` will be `Company` and the type for `userCompanies` will be `UserCompany`.

**Comment by designatednerd** [comment]
@Shiaulis did that work? If so, can we close this out?

**Comment by kylebrowning** [comment]
Worked for us.

**Comment by Shiaulis** [comment]
Thanks, let's close it
