### ISSUE TITLE
Error: Unable to read file  ›    schema.json. ENOENT: no such file or directory, open 'schema.json'

### ISSUE THREAD

**Issue by fatma95** [apollographql/apollo-ios#1374]
I followed all the correct steps in the document, schema.json and graphql files are on the right places however I always get this error and build fails please help.

**Comment by designatednerd** [comment]
Hi! So I'll need a bit more information to help diagnose this. Can you answer a few questions: 

- Have you confirmed that `schema.json` is downloaded and exists where you think it is on your filesystem? 
- Are you using the Swift Scripting wrapper or the shell script? 
- Can you paste a link to the set of instructions you are following? 

Thank you!

**Comment by designatednerd** [comment]
Hi! I haven't heard back on this issue in over a week so I'm going to close it out - @fatma95 please reopen if you still need help, anyone else with a similar problem, please open a new issue. Thank you!
