### ISSUE TITLE
Crash at runtime when upgrading to 0.31.0 on URLSessionClient.swift, line 95

### ISSUE THREAD

**Issue by benoitletondor** [apollographql/apollo-ios#1377]
Hey guys,

So I have an app that works perfectly with 0.30.0 but when upgrading to 0.31.0 I get a crash soon after the app launches:

```
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/XXX/Library/Developer/Xcode/DerivedData/XXX-bzyicfzsqzelixabxktyzmboxbaj/SourcePackages/checkouts/apollo-ios/Sources/Apollo/URLSessionClient.swift, line 95
```

The issue is one this line :

```
let task = self.session.dataTask(with: request)
```

here `session` is nil.

Let me know if you need anything else as I can reproduce the crash 100% of the time. Many thanks

**Comment by designatednerd** [comment]
Hi! That's awfully weird, since the session is instantiated in the initializer. Can you share the code you're using to create your client, as well as where in the app lifecycle that's happening?

**Comment by designatednerd** [comment]
Something that occurred to me is that in `0.31.0` we added a mechanism to make sure the `URLSession` is properly terminated so as not to create a retain cycle - you can probably throw a breakpoint in [here](https://github.com/apollographql/apollo-ios/blob/d95b4463f78a15fba7e3de2017817a391e9714f0/Sources/Apollo/URLSessionClient.swift#L63) to see if that's getting hit before you get to whatever's creating the data task.

**Comment by benoitletondor** [comment]
Hey @designatednerd !

First, thank you very much for answering so quickly, appreciate it :)

I think your guess of adding a breakpoint into the `invalidate` method of `URLSessionClient` was a good idea. It turns out that when our app starts, we are initializing an `HTTPNetworkTransport` to use into a `SplitNetworkTransport` without any authentication, and when we authenticate (a few seconds after the app starts) we replace that `HTTPNetworkTransport` with a new one, simply by dereferencing the old one and keeping a pointer on a new `SplitNetworkTransport` that contains this new client.

I think that what may happen is that the first client may have started some work in background, and when it gets destroyed this work hasn't finished, leading to this crash as the `session` is already nil. Could that be possible?

**Comment by designatednerd** [comment]
That's possible - I've added some code in #1383 that should cancel any inflight operations on a `URLSessionClient` when `invalidate()` gets called, but I'm not sure if it'll address this crash since it's happening before the task is even added, which means `invalidate` has probably been called on a different thread.

Definitely sounds like a race condition is happening here - out of curiosity why are you fully replacing the client rather than using one of the delegate methods to handle authentication?

**Comment by benoitletondor** [comment]
@designatednerd Just tested, still crashing.

I'm not 100% sure why we are replacing the client as I'm not the one who wrote that code, but as far as I understand it's because we are using `SplitNetworkTransport` and we are recreating the websocket so we need to also recreate the http client.

**Comment by designatednerd** [comment]
From here, I see a couple of workaround options: 

- Hanging on to the instance of `HTTPNetworkTransport` and using that when you have to recreate the web socket rather than creating a fully new transport
- Taking a look at recent changes to the web socket transport, particularly around disconnecting and reconnecting, and seeing if any of those will prevent you from having to recreate.

**Comment by benoitletondor** [comment]
I took the first option which works, so ok for me now but I guess you still have a race condition somewhere. Thank you very much for your help

**Comment by designatednerd** [comment]
Yeah for sure - I'm going to have to dig deeper into this but a lot of things are changing with the updated networking stack, so I'd like to get that out before digging back into this.

**Comment by designatednerd** [comment]
@benoitletondor We've just shipped something that will allow you to delay starting the websocket after initialization, which in theory should allow you to not have to replace the `SplitNetworkClient`. Do you mind pulling `0.36.0` and letting me know if that gets you to where you need to be?

**Comment by benoitletondor** [comment]
Hey @designatednerd ,

Thank you for your help on that. Indeed, it would work for my use case as we can avoid starting the websocket until we have a proper authentication. As I said last time I already followed your advice of keeping the `HTTPNetworkTransport` instance so it's not really needed anymore on my side.

Thanks

**Comment by designatednerd** [comment]
@benoitletondor Do you mind if I close out this issue then?

**Comment by benoitletondor** [comment]
Be my guest ;)
