### ISSUE TITLE
ApolloCodegen.run does not throw error when validation of GraphQL query document fails

### ISSUE THREAD

**Issue by michaelxbarrett** [apollographql/apollo-ios#1378]
From the tutorial:
```
do {
    // Actually attempt to generate code.
    try ApolloCodegen.run(from: targetRootURL,
                          with: cliFolderURL,
                          options: codegenOptions)
} catch {
    // This makes the error message in Xcode a lot more legible.
    exit(1)
}
```

When there is an error in the query, the message `Validation of GraphQL query document failed` is logged and outputted to the console with a stacktrace, but no error is thrown in this case.

Stack trace:
```
Validation of GraphQL query document failed
    at Object.validateQueryDocument (Codegen/ApolloCLI/apollo/node_modules/apollo-language-server/lib/errors/validation.js:35:38)
    at Object.generate [as default] (Codegen/ApolloCLI/apollo/lib/generate.js:23:18)
    at write (Codegen/ApolloCLI/apollo/lib/commands/client/codegen.js:84:54)
    at Task.task (Codegen/ApolloCLI/apollo/lib/commands/client/codegen.js:104:46)
```

**Comment by designatednerd** [comment]
To clarify: Do you mean that the `exit(1)` is not called because no error is thrown from `run` itself, or that `exit(1)` does not constitute throwing an error?

**Comment by designatednerd** [comment]
Also, what version of the SDK are you using? I think there was an issue a couple versions back with our JS CLI where it wouldn't throw errors properly on failure, which should be resolved now.

**Comment by designatednerd** [comment]
@michaelxbarrett Were you able to address this by updating?

**Comment by designatednerd** [comment]
Since I haven't heard back in 3 weeks, I'm going to close this out. @michaelxbarrett Please reopen if you're still experiencing problems. Anyone else with similar problems, please open a new issue. Thank you!
