### ISSUE TITLE
Query watcher not being called when cache is updated on an element of a collection that is added after calling watch

### ISSUE THREAD

**Issue by benoitletondor** [apollographql/apollo-ios#1379]
Hi everyone,

I've been trying a lot of things on that one and wasn't able to find a way to fix my problem. So in my app I'm having a list of conversations, so I'm creating a `watch` on a query that returns the list of conversations, this is something like that:

```
user {
    uuid
    firstName
    lastName
    conversations {
        uuid
        unreadMessagesCount
    }
}
```

> In the app we use the `uuid` key to handle cache, so we make sure to always pass `uuid` in our queries to automatically handle cache update.

So the role of the watcher I'm talking about is both to update existing conversations and also be able to catch when a new conversation is created (it can happen and not be initiated by the user, we then trigger an event from the backend that is listen from a subscription in the app). When this event happens it returns something like that

```
event {
     newConversation {
          conversation {
               uuid
               unreadMessagesCount
               // This is the part that adds the new conversation to the existing ones of the users in the cache
               user {
                    uuid
                    conversations {
                          uuid
                          unreadMessagesCount
                    }
               } 
          }
     }
}
```

It works great, meaning that when this event happens, the watcher is being called with the newly created conversation, but the issue is that any new cache update for that specific conversation doesn't trigger the watcher again.

After investigating a bit, I realised that the cache is being updated because if I'm adding 3 new messages into the new conversation (setting the `unreadMessagesCount` to 3), the watcher doesn't get called but then if I add 1 new message into an old one, the watcher is being called with both the new message on the old conversation and the 3 new on the new one. 

So it really seems like `watch` is not being called again for changes on an item that wasn't in a collection when the `watch` was initially made. I've also take a look at https://github.com/apollographql/apollo-ios/issues/281 and making a `fetch` on the same query again after the event doesn't fix the issue.

Let me know if I'm not clear on something as the whole thing is a bit complicated to explain.

**Comment by designatednerd** [comment]
Hi! Can you take a look at v0.32.0 - I fixed something in query watchers in terms of updating dependent keys that I *think* should help with this. If it doesn't, let me know. Thank you!

**Comment by benoitletondor** [comment]
Hey @designatednerd 

Sure, if #1377 is resolved too I will be able to test that tomorrow. If that's not the case I guess I won't be able

**Comment by benoitletondor** [comment]
Hey @designatednerd 

I tested and I can confirm 0.32.0 fixes the issue, thank you very much for your help.

**Comment by benoitletondor** [comment]
Reopening this one as the bug seems to be back with 0.34.0 :/ Let me know if you need help on my side

**Comment by benoitletondor** [comment]
@designatednerd I haven't tested 0.33.0 so I'm not sure when the regression happened

**Comment by designatednerd** [comment]
That's odd, because the test added is passing - I actually spent quite a bit of time making it pass. 🙃 Do you mind opening a new issue with a link to this one since it's in a different version?

**Comment by benoitletondor** [comment]
Sure
