### ISSUE TITLE
Availability of framework with Xcode 12 and iOS version 8

### ISSUE THREAD

**Issue by novinfard** [apollographql/apollo-ios#1384]
Is it possible to use the framework with Xcode 12 and iOS version 8? Currently it asks me to upgrade to iOS version 9 with Xcode 12

**Comment by designatednerd** [comment]
iOS 9 is our minimum supported version regardless of Xcode version.

**Comment by designatednerd** [comment]
@novinfard Any further questions or do you mind if I close this issue out?
