### ISSUE TITLE
Crash while checking graphQLResult with 0.32 and 0.32.1

### ISSUE THREAD

**Issue by jsm174** [apollographql/apollo-ios#1385]
Hello. Yesterday I upgraded to 0.32 and immediately started getting crashes anytime one of our services is checking a `graphQLResult`:

```
case let .success(graphQLResult):
```

I downgraded to 0.31 and it started working again. I saw that 0.32.1 was released and figured I'd give it a try, but I'm seeing the same behavior.

I know this isn't much to go on, but:

![Screen Shot 2020-09-11 at 9 36 16 AM](https://user-images.githubusercontent.com/1197137/92932578-14476280-f413-11ea-9b8a-02df220cfcfd.png)

(FWIW, that first preflight is just refreshing oauth tokens if necessary)

**Comment by jsm174** [comment]
So, I apologize but I think it is working after all. 

I think maybe after I did a pod update, it never actually rebuilt apollo.

I will close this.

**Comment by designatednerd** [comment]
No worries, that can definitely happen. Thanks for the update!
