### ISSUE TITLE
It expected a JSON schema introspection result, but got an HTML response instead.

### ISSUE THREAD

**Issue by tapannathvani** [apollographql/apollo-ios#1400]
Hello,

I am trying to run a script first time but i am receiving below error. 

**Unexpected token < in JSON at position 0
    Error: Apollo tried to introspect a running GraphQL service at 
    http://10.10.10.10/graphql
    It expected a JSON schema introspection result, but got an HTML response 
    instead.
    You may need to add headers to your request or adjust your endpoint url.**

Here is my Script

       # Type a script or drag a script file from your workspace to insert its path.
       # Go to the build root and search up the chain to find the Derived Data Path where the source packages are checked out.
       DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"

       while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
           if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
           echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
           exit 1
        fi

            DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
           done

            # Grab a reference to the directory where scripts are checked out
            SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/apollo-ios/scripts"

             if [ -z "${SCRIPT_PATH}" ]; then
                   echo >&2 "error: Couldn't find the CLI script in your checked out SPM packages; make sure to add the framework           to your project."
                   exit 1
             fi

            #cd "${SRCROOT}/${TARGET_NAME}"
            #"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift

            SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
            cd "${SRCROOT}/${TARGET_NAME}"
           "${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint=http://<serverURL>/graphql schema.json

XCode Version : 11.3.1
Apollo : 0.24.1
Installed Apollo pod.

**Comment by designatednerd** [comment]
Hi, it looks like the endpoint hasn't had the `<serverURL>` placeholder replaced yet - the `http:///graphql` in your error message makes it look like that's just being stripped out entirely by the CLI. 

Unrelated to your immediate issue, I would strongly recommend running `schema:download` before running `codegen:generate` since codegen uses the result of downloading the schema.

**Comment by tapannathvani** [comment]
As of now i am trying to download schema.json from CLI with the following command.

`apollo schema:download --endpoint=http://<my server url>/graphql schema.json
`

But still i am getting the same error. I didnt get <serverurl> placeholder (in your comment, can you please clarify)

**Comment by tapannathvani** [comment]
Hey I am able to download schema.json file from other public graphql url.

But now i am facing another error. I am using POD for apollo now.

Run Script : 

`SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
`

Error :

Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
Generating query files with 'swift' target [failed]
→ Apollo does not support anonymous operations
    GraphQLError: Apollo does not support anonymous operations
Command PhaseScriptExecution failed with a nonzero exit code


If its not legal then can i raise new issue with this error and close this one

**Comment by designatednerd** [comment]
You need to make sure you give your query a name - otherwise the codegen won't know what name to give the class containing the query. 

So it has to look like this: 

```graphql
FetchUser($id: ID!) {
  user(id: $id) {
     name
     [etc]
  }
}
```

**Comment by tapannathvani** [comment]
Thanks.. this works.

**Comment by tapannathvani** [comment]
Hello, 

I am receiving this error right now.

ERROR : Received error response: Field "country" argument "code" of type "ID!" is required, but it was not provided.

GraphQL : https://countries.trevorblades.com/graphql

Query : 

         query AllCountry {
              country {
                    name
              }
           }

iOS Swift Code : 

        NetworkClient.sharedInstance().apollo.fetch(query: AllCountryQuery()) { result in
            
            switch result {
            case .success(let GraphQLResult) :
                print(GraphQLResult.data?.country as Any)
                
            
            
            case .failure(let error) :
                print("ERROR :", error.localizedDescription)
        }
        }

**Comment by designatednerd** [comment]
I think the error is telling you exactly what the problem is: `Field "country" argument "code" of type "ID!" is required, but it was not provided.`  You need to make sure you're passing in a country code for this query.

**Comment by tapannathvani** [comment]
Fixed. Thanks
