### ISSUE TITLE
Download Schema.json but server has CSRF Token protection

### ISSUE THREAD

**Issue by tapannathvani** [apollographql/apollo-ios#1406]
Hello,

I want to download a schema.json file but our server is protected with CSRF Token so which command i need to use to download a schema file and how can i send --header with CSRF token (From where i can get CSRF token means from our server guy or is apollo-client give/generate for downloading schema & passing in --header)

**Comment by designatednerd** [comment]
Hi! Please check out the instructions for [doing this in Bash](https://www.apollographql.com/docs/ios/downloading-schema/) and/or [doing this with the Swift Scripting tools](https://www.apollographql.com/docs/ios/swift-scripting/#downloading-a-schema). Do those docs answer your questions?

**Comment by designatednerd** [comment]
Hi! Since this is pretty clearly documented and I haven't heard anything back in a week, I'm going to close this out - @tapannathvani if you're still having problems please reopen. Anyone else having similar problems, please open a new issue. Thank you!
