### ISSUE TITLE
is apollo provide internet check class?

### ISSUE THREAD

**Issue by tapannathvani** [apollographql/apollo-ios#1407]
I am trying to check internet connection in my project.. and looking in apollo-ios library also like if you guys providing any reachability type class so without adding any other library or framework i can use your class to check connection

If yes then please provide documentation link and if not then please let me know how can i achieve this? and can i check internet connectivity in HTTPNetworkTransportPreflightDelegate (will send) method or in should send method?

**Comment by designatednerd** [comment]
We do not provide an internet check class, nor do we have plans to do so. 

If you're using iOS 12 and above, the recommend way of doing things is [using `NWPathMonitor`](https://medium.com/@rwbutler/nwpathmonitor-the-new-reachability-de101a5a8835). If you're storing the most recent result from `NWPathMonitor` the preflight delegate would be a reasonable place to check it. 

Please note that the Preflight delegate will be going away with `0.34.0` - you can check out the updated networking beta in #1386, and the PR has links to updated documentation. It would probably be fairly easy to add an interceptor that does that network check in the new networking stack.

**Comment by tapannathvani** [comment]
Can we know when can we have 0.34.0?

**Comment by designatednerd** [comment]
Release candidate 2 is available now, gonna let it bake over the weekend and put it out monday night (US-Central time) if I don't hear any major showstoppers.

**Comment by tapannathvani** [comment]
Thanks for the quick response.
