### ISSUE TITLE
How to inject HTTP headers before fetching a query

### ISSUE THREAD

**Issue by angelu25** [apollographql/apollo-ios#1414]
Do you know a mechanism to do that?

**Comment by designatednerd** [comment]
This is covered in the [Advanced Client Creation](https://www.apollographql.com/docs/ios/initialization/) section of our docs. 

Fair warning that this will be changing significantly very soon with the release of what's now in RC for #1386 (which I'm hoping to release tonight). The PR has a link to the updated docs for advanced client creation as well.
