### ISSUE TITLE
Overwrite whole cache after fetch.

### ISSUE THREAD

**Issue by pgawlowski** [apollographql/apollo-ios#1416]
Hello again.

My application is trying to archive offline first mode.
We are using BigQuery to fetch all the data required for app to be usable and focus on offline cache mutations with custom made syc feature. 

The problem is that after synchronization we are trying to refresh whole cache data. Some of our tasks can fail, most will be successful.
To avoid too much noise with cache handling, right after syc we are refetching BigQuery once again. 
And here is our problem. Mutations we performed in offline mode are still present, no matter the fact of success of failure during sync it is because backend is creating it's own unique ID's here and we are just generating UUID as a placeholder. The source of truth is server. So in case of BigQuery fetch I would like to totally teardown current cache and recreate it with BigQuery result.

Calling clearCache before BigQuery seems to be a little bit risky. I mean there is a risk of loosing data if sth goes wrong with BigQuery.

Any ideas how to handle?

**Comment by designatednerd** [comment]
Oof, that's a tough one. This is part of why sync is so hard (and frankly why I have zero interest in handling it on our end). 

The first thing that jumps to mind is making a second instance of whatever cache you're using, swapping in a store with that cache, and then putting the old one back if things fail. I won't say that won't be a giant pain, but off the top of my head that's at least something that will keep the old data in case your `BigQuery` fails. 

Like I said though, sync is really hard. I don't think there's going to be a simple, straightforward solution to this problem.

**Comment by designatednerd** [comment]
@pgawlowski Anything else I can help with here or do you mind if I close this out?

**Comment by designatednerd** [comment]
Since I haven't heard back in a week, I'm going to close this out. @pgawlowski feel free to reopen if you have more questions - anyone else with similar problems, please open a separate issue. Thank you!
