### ISSUE TITLE
Question about ApolloInterceptor

### ISSUE THREAD

**Issue by dchohfi** [apollographql/apollo-ios#1418]
Hey, amazing rewrite of the http architecture, good naming and nice usage of open/close principles.

Just one stuff, I'm not sure how many times the `interceptAsync` method gets called, as it receives both request and an option response, I think this will be called twice, I'm correct?

If this is correct, talking about an interceptor that adds authentication token to the request, might be better to check if we don't have the response yet? Should I only add the token if the response is nil?

**Comment by designatednerd** [comment]
Each interceptor is called once - they're called in sequence based on the order of the array passed in from the `InterceptorProvider`.

**Comment by dchohfi** [comment]
So the interceptor isn't called before each request and after each response?

**Comment by dchohfi** [comment]
Oh, I see. They get called in order depending on how you declare at your own implementation of `NetworkInterceptorProvider`.

Following the documentation it says:
```swift
import Foundation
import Apollo

class NetworkInterceptorProvider: LegacyInterceptorProvider {
    override func interceptors<Operation: GraphQLOperation>(for operation: Operation) -> [ApolloInterceptor] {
        var interceptors = super.interceptors(for: operation)
        interceptors.insert(TokenAddingInterceptor(), at: 0)
        return interceptors
    }
}
```

By doing this, we are adding the token interceptor at the end of the chain, so after all the requests are done, does it make sense to add the token interceptor after the request is made?

**Comment by dchohfi** [comment]
Thank your for your response! Now I get it, sorry about that.
