### ISSUE TITLE
Why the response is not being triggered and no interceptors are dispatched?

### ISSUE THREAD

**Issue by angelu25** [apollographql/apollo-ios#1424]
I'm building the client like this:
![image](https://user-images.githubusercontent.com/6308120/94703838-90143b00-033f-11eb-8033-3f2727a09fbe.png)
This is my Interceptor Provider:
![image](https://user-images.githubusercontent.com/6308120/94703879-9c989380-033f-11eb-8fab-ea802d571565.png)
And this is an example of the query fetch:
![image](https://user-images.githubusercontent.com/6308120/94703946-aae6af80-033f-11eb-93aa-b7670cb5c41d.png)
It is never stopping at result or at any interceptor, but console is dispatching:
![image](https://user-images.githubusercontent.com/6308120/94704042-c81b7e00-033f-11eb-9ca7-ad9b833251b2.png)

Do you have any idea what is wrong there?

**Comment by designatednerd** [comment]
You are not actually including anything that calls the network, it looks like. You will need to include the `NetworkFetchInterceptor`, probably between request and response logging interceptors. 

I don't know why the response logging interceptor would be showing a 200 response when there's nothing that came through, because the request never went out to the network.

**Comment by angelu25** [comment]
Worked ;)

**Comment by angelu25** [comment]
It can now fetch the data, response is received:
![image](https://user-images.githubusercontent.com/6308120/94791351-cac9b200-03d7-11eb-9d99-78a0bacddbcf.png)
But when handling it:
![image](https://user-images.githubusercontent.com/6308120/94791434-e92fad80-03d7-11eb-934b-7777241fbad7.png)
It is entering the failure, but with a totally separate error:
![image](https://user-images.githubusercontent.com/6308120/94791471-f8166000-03d7-11eb-8e70-c9a48d108e87.png)
Even with just the Network Interceptor:
![image](https://user-images.githubusercontent.com/6308120/94791498-02d0f500-03d8-11eb-8877-bc49dd33a64e.png)

Could you help there?
