### ISSUE TITLE
Enum generation with `INIT` case

### ISSUE THREAD

**Issue by bezoadam** [apollographql/apollo-ios#1427]
## Bug report

Hi, enum is declared like this:
![Snímka obrazovky 2020-10-01 o 8 26 56](https://user-images.githubusercontent.com/25613125/94775340-ede86780-03bf-11eb-9f4e-f9cb5bc9f5a0.png)

and generated code throws these errors:
![Snímka obrazovky 2020-10-01 o 8 27 08](https://user-images.githubusercontent.com/25613125/94775447-18d2bb80-03c0-11eb-9fe5-b6f6d12420ef.png)

It looks like there is problem with `INIT` case when using enum.

## Versions

- `apollo-ios` SDK version: 0.34.1
- Xcode version: 12.0.1
- Swift version: 5

## Steps to reproduce

Generate code with `init` in enum case.

Is it problem on my side or bug in apollo codegen. Any possible fixes?
Thanks.

**Comment by designatednerd** [comment]
It's the codegen - it's not properly escaping the case named `init`, which is a reserved Swift keyword. Upcoming codegen should handle this better but it's gonna be a bit - is this schema already public or is it still being evolved?

**Comment by bezoadam** [comment]
Schema is partially public but I think there is not chance that there will be some changes. Anyway if I change `.init` to ``.init`` on lines where error is triggered, it disappears. But of course on next build code is regenerated. So I think this should be fixed in codegen.

**Comment by designatednerd** [comment]
Yeah, absolutely - fixing the current codegen is a pain (which is why it's being rewritten) so I was trying to make sure it was necessary before diving into it. 🙃

**Comment by bezoadam** [comment]
Thank you 👍

**Comment by designatednerd** [comment]
You'd need to make it

```swift
`.init`
```

 rather than `".init"`, but if you're ok with that, I'm very OK with not diving into typsecript hell 😇. If that's cool with you, mind if we close this one out?

**Comment by bezoadam** [comment]
Yes closed. We fixed `SecuritySystemStateStatus` enum `INIT` to `INITIAL` 😎 but I think in future you should fix it :)

**Comment by designatednerd** [comment]
Yeah we're definitely planning to fix this in new codegen.
