### ISSUE TITLE
Failed codegen when using GitHub GraphQL schema

### ISSUE THREAD

**Issue by mattia** [apollographql/apollo-ios#1433]
## Bug report

While trying to use the [Swift scripting codegen tooling](https://www.apollographql.com/docs/ios/swift-scripting/) I was not able to generate the `API.swift` file given the corresponding schema file.

An error like this is generated 

> Field "AcceptEnterpriseAdministratorInvitationInput.clientMutationId" already exists in the schema. It cannot also be defined in this type extension.

But using the GraphQL verification tool available in the [same repo](https://github.com/octokit/graphql-schema) it passes. (running `npm start validate:ts`)

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.34.1
- Xcode version:  12.2 beta 2 (12B5025f)
- Swift version: 5.3

## Steps to reproduce

Set up the project as described in the [Swift scripting guide](https://www.apollographql.com/docs/ios/swift-scripting/) and use the GitHub schema definition with the following files:
 - [schema.graphql](https://raw.githubusercontent.com/octokit/graphql-schema/master/schema.graphql)
 - [schema.json](https://raw.githubusercontent.com/octokit/graphql-schema/master/schema.json)

## Further details

<details>
  <summary>Example `main.swift`</summary>
  
```swift
import ApolloCodegenLib

// Grab the parent folder of this file on the filesystem
let parentFolderOfScriptFile = FileFinder.findParentFolder()

// Use that to calculate the source root of both the
let sourceRootURL = parentFolderOfScriptFile
    .apollo.parentFolderURL() // Sources
    .apollo.parentFolderURL() // Codegen
    .apollo.parentFolderURL() // My Project

// From the source root, figure out where your target
// root is within your main project
let targetRootURL = sourceRootURL
    .apollo.childFolderURL(folderName: "My Project")

// Set up the URL you want to use to download the project
let endpoint = URL(string: "https://api.github.com/graphql")!

// Create an options object for downloading the schema
let schemaDownloadOptions = ApolloSchemaOptions(
  endpointURL: endpoint,
  headers: ["Authorization: Bearer XXXXXXXXX"],
  outputFolderURL: targetRootURL
)

// Calculate where you want to create the folder where the CLI will
// be downloaded by the ApolloCodegenLib framework.
let cliFolderURL = sourceRootURL
    .apollo.childFolderURL(folderName: "Codegen")
    .apollo.childFolderURL(folderName: "ApolloCLI")

do {
  // Actually attempt to download the schema.
  try ApolloSchemaDownloader.run(with: cliFolderURL,
                                 options: schemaDownloadOptions)
} catch {
  // This makes the error message in Xcode a lot more legible,
  // and prevents the script from continuing to try to generate
  // code if the schema download failed.
  exit(1)
}

// Create the default Codegen options object (assumes schema.json
// is in the target root folder, all queries are in some kind
// of subfolder of the target folder and will output as a
// single file to API.swift in the target folder)
let codegenOptions = ApolloCodegenOptions(targetRootURL: targetRootURL)

do {
    // Actually attempt to generate code.
    try ApolloCodegen.run(from: targetRootURL,
                          with: cliFolderURL,
                          options: codegenOptions)
} catch {
    // This makes the error message in Xcode a lot more legible.
    exit(1)
}
```
</details>

Please let me know if I can help debug this. Also I am new to GraphQL, so I may be doing something wrong.

Thank you for this library!

**Comment by designatednerd** [comment]
I've definitely seen this from the `.graphql` version of the GitHub schema before, but it looks from the code like you're downloading the JSON version of it. Can you please confirm that and attach a copy of the schema you're getting from GitHub so I can take a look? Thank you!

**Comment by mattia** [comment]
> I've definitely seen this from the `.graphql` version of the GitHub schema before, but it looks from the code like you're downloading the JSON version of it. Can you please confirm that and attach a copy of the schema you're getting from GitHub so I can take a look? Thank you!

Yes, of course. The schema I'm downloading is from the [octokit repo](https://github.com/octokit/graphql-schema).
The files are:
 - [schema.graphql](https://gist.github.com/mattia/d2cc50fdbfc1a90e58c4c35716677052)
 - [schema.json](https://gist.github.com/mattia/4545c6371577d3a7c7c17722bf7266f2).

Thank you and have a nice day!

**Comment by designatednerd** [comment]
OK looks like I had it backwards, it's the JSON that's giving the weird error and the SDL that seems to be working fine. If you update your schema download options to downloading SDL instead of the default JSON option, that should work: 

```swift
// Create an options object for downloading the schema
let schemaDownloadOptions = ApolloSchemaOptions(
  schemaFileType: .schemaDefinitionLanguage,
  endpointURL: endpoint,
  headers: ["Authorization: Bearer XXXXXXXXX"],
  outputFolderURL: targetRootURL
)
```

**Comment by mattia** [comment]
Thanks for the reply. I've been real busy these days but I will try to come back to you in the next few days after trying your suggestion.

Thanks again! Have a nice day

**Comment by designatednerd** [comment]
OK cool - I'm going to close this issue out for now, please let us know if using the Schema Definition Language version of their schema doesn't work by reopening this issue. 

Anyone else having a similar problem, please open a new issue. Thank you!
