### ISSUE TITLE
Is it okay to git ignore API.swift?

### ISSUE THREAD

**Issue by prateek3255** [apollographql/apollo-ios#1434]
## Question

Since API.swift is auto-generated, is it good practice to add it to `.gitignore`?

We tried adding it to `.gitignore` but whenever someone new clones the repo, the code fails to compile because of a broken reference to API.swift, and hence we have to manually pass it for the very first time.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.32.1
- Xcode version: 11.4
- Swift version: 5.1

**Comment by designatednerd** [comment]
This is not a recommended practice - the exact problem you're having illustrates why this isn't a good idea.

**Comment by prateek3255** [comment]
Okay, thanks for the clarification
