### ISSUE TITLE
Mismatched stores for ApolloClient/LegacyInterceptorProvider

### ISSUE THREAD

**Issue by danpalmer** [apollographql/apollo-ios#1438]
## Bug report

Caveat: this isn't quite a bug, perhaps more of a design bug, but we nearly shipped a bug in our app because of it. Also, I may just be missing things!

There are two ways to set up an `ApolloStore` for the networking in Apollo, and unless both are done, in the same way, I believe there can be inconsistencies.

For example, we previously did this in our `ApolloClient` setup:

```swift
let networkTransport = HTTPNetworkTransport(url: baseURL)
let cache = InMemoryNormalizedCache()
let store = ApolloStore(cache: cache)
let client = ApolloClient(networkTransport: networkTransport, store: store)
```

When upgrading to the newest version of Apollo, we originally re-wrote this as:

```swift
let provider = LegacyInterceptorProvider()
let networkTransport = RequestChainNetworkTransport(interceptorProvider: provider, endpointURL: baseURL)
let cache = InMemoryNormalizedCache()
let store = ApolloStore(cache: cache)
let client = ApolloClient(networkTransport: networkTransport, store: store)
```

As far as I can tell (please tell me if I'm wrong!) this has set up a store that is now not being used at all. We can still call `client.clearCache()` or `client.cacheKeyForObject` and it will use the store that we created, but this would _not_ affect the store being used by the interceptors.

Similarly, we could have configured a more complex cache setup, but that would not be used by the interceptors.

If we corrected this in the following way...

```swift
let cache = InMemoryNormalizedCache()
let store = ApolloStore(cache: cache)
let provider = LegacyInterceptorProvider(store: store)
let networkTransport = RequestChainNetworkTransport(interceptorProvider: provider, endpointURL: baseURL)
let client = ApolloClient(networkTransport: networkTransport)
```

...this would also introduce bugs because while our correct store is being used for the networking, `client.clearCache` or `client.cacheKeyForObject` are pointing to the `ApolloClient`'s default store from its init method.

## Versions

- `apollo-ios` SDK version: 0.34.1
- Xcode version: 12.0
- Swift version: 5.3

## Steps to reproduce

See above for the process that can lead to incorrect use. This is roughly the steps that we took while upgrading Apollo to 0.34.x – i.e. we went through two invalid implementations before reaching one that we believe is valid.

## Further details

As mentioned above, this isn't really a bug, but I think it's a design issue that could be improved. My recommendation would be to eliminate the store from the `ApolloClient` entirely, and leave it up to the user to coordinate the store with their interceptor provider. Potentially the store could become part of the interceptor provider protocol so that the client could still back `cacheKeyForObject`/`clearCache` onto the provider's store.

An alternative would be to eliminate the store from the interceptor provider, and ensure that in the client the store is set correctly on the provider so that they always line up.

Lastly, if maintaining backwards compatibility is key, the store from the provider and the store from the client could be compared at the end of the client initialiser, and an error raised if they are not exactly the same object.

**Comment by designatednerd** [comment]
Is there a particular using you're not passing in the `store` parameter for `client` on that last version? eg: 

```swift
let cache = InMemoryNormalizedCache()
let store = ApolloStore(cache: cache)
let provider = LegacyInterceptorProvider(store: store)
let networkTransport = RequestChainNetworkTransport(interceptorProvider: provider, endpointURL: baseURL)
let client = ApolloClient(networkTransport: networkTransport, store: store)
```

That would ensure you have the same store in all places. 

I do agree it's a little overcomplicated at the moment - I do plan to keep evolving this, and I appreciate the feedback.

**Comment by danpalmer** [comment]
> Is there a particular using you're not passing in the store parameter for client on that last version? eg:

Not particularly, but we did go through this stage on the way to our fully working version, which is pretty much what you have in your example. The fact that there were multiple opportunities for human error in getting to that working solution suggests there's a better design possible.

Ideally these would be caught by the type system, or made un-representable, as I don't believe they are states of the system with valid use-cases.

Would you accept a PR to address this? If so, what's your preferred approach out of those options I outlined, or is there another way you'd like to solve this?

**Comment by designatednerd** [comment]
If you're not using a custom interceptor provider, the default initializer for `ApolloClient` initializes all this stuff for you - is that more what you're thinking?

**Comment by danpalmer** [comment]
> If you're not using a custom interceptor provider, the default initializer for ApolloClient initializes all this stuff for you - is that more what you're thinking?

I think that route is safe.

We were transitioning from the legacy networking stack where we used `HTTPNetworkTransportPreflightDelegate` though. To maintain compatibility we decided to use `LegacyInterceptorProvider` and add an additional interceptor that did what our preflight delegate implementation had previously done, hence ending up with needing to pass the store into two different places, and this getting out of sync in two different ways before we realised the implicit dependency between those two places.

Also, just realised that the 3rd code example in the issue body is roughly what's in `Network.swift` in the docs here: https://www.apollographql.com/docs/ios/tutorial/tutorial-mutations/ – following the docs here will result in an invalid construction of the networking stack I think.

Having thought about this a bit more, I think there's a more common way this could also be done incorrectly:

```swift
let provider = LegacyInterceptorProvider()
let networkTransport = RequestChainNetworkTransport(interceptorProvider: provider, endpointURL: baseURL)
let client = ApolloClient(networkTransport: networkTransport, store: store)
```

If not manually constructing a store at all, but instantiating a custom interceptor provider, there are two different stores being used and therefore it's impossible to clear the cache of the "real" one, but no error would be raised clearing the cache of the unused one.

It's possible I've missed somewhere that the stores get "joined up" – I'm new to Swift and don't know much about the Apollo codebase and may not understand the intention here. Apologies if that's the case!

- - -

I think there are 3 possible options here (although very open to more suggestions!):

1. Eliminate the store from the ApolloClient entirely, leave it up to the user to coordinate the store with their interceptor provider. User will need to hold a reference to it for setting/getting the cache key, or clearing the cache.

2. Eliminate the store from the interceptor provider init, have the client inject it into the interceptor provider. This way the user only has one place to pass it in, and if they don't the default one is still the same.

3. If maintaining backwards compatibility is key, the store from the provider and the store from the client could be compared at the end of the client initialiser, and an error raised if they are not exactly the same object.

**Comment by danpalmer** [comment]
> There are (rare) instances where someone intentionally wants to use different stores, but you're right that most of the time, that's not the case.

Interesting! I'm not sure I quite understand what the use-case is for the client to have a different store to the interceptor provider? I can't see how that client store gets used apart from by the user... which means if I've understood correctly, it's not plugged in to the Apollo internals?

**Comment by designatednerd** [comment]
basically there are some people who use multiple clients with multiple stores, and there are some...odd ways people make that work.

**Comment by designatednerd** [comment]
I've shipped the PR removing the default stores with `0.36.0` - I took a couple swipes at doing something else besides that, but everything I tried wound up *far* more complicated than "actually make people select what store they're passing". 

Going to close this one out, please open a new issue if you think you've got a better suggestion!

**Comment by danpalmer** [comment]
Nice one! PRs look good. Straightforward approach sounds good – I can't see myself making the mistakes above if this was in place. Better API ergonomics can come later if they're needed at all.
