### ISSUE TITLE
Can not find 'GenericScalar' in scope

### ISSUE THREAD

**Issue by tapannathvani** [apollographql/apollo-ios#1439]
## Bug report

Backend is JWT and when i'll try to execute a mutation for tokenVerification it gives me an error. We have Payload (Scalar Type) as response it in. I have added --passthroughCustomScalars in run script also.

`SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" --passthroughCustomScalars API.swift
`

## Versions

- `apollo-ios` SDK version: POD 0.34.0
- Xcode version: XCode 12
- Swift version: Swift 5

## Steps to reproduce

Please add Scalar type response in mutation/query and try to build the project (first clear build folder)

## Further details

I have tried to do Type Conversion using this help : https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/JSONStandardTypeConversions.swift

But its not working as we are using swift 5 i think.

**Comment by designatednerd** [comment]
Hi! Can you clarify a bit: 

- What is the name of your custom scalar type, `Payload` or `GenericScalar`? 
- What is the underlying type of your custom scalar? It sounds like it's a string containing the JWT, I just want to double check
- Have you tried using a `typealias` to define the scalar type?

**Comment by designatednerd** [comment]
@tapannathvani Hi, do you have answers to any of the questions I asked?

**Comment by tapannathvani** [comment]
Closing this issue as i am not using Payload response data now.
