### ISSUE TITLE
Swift 3.2 / 4 support

### ISSUE THREAD

**Issue by Plnda** [apollographql/apollo-ios#144]
Currently the project does not compile under swift 3.2 or 4.0

**Comment by martijnwalraven** [comment]
I checked with Xcode 9 GM, and the project compiled with warnings in Swift 3.2 mode for me. The warnings are about redundant conditional conformances, and I didn't want to remove them without understanding what was going on and how it would affect earlier versions. But the project should be fully functional. Do you receive other errors?

**Comment by nbonatsakis** [comment]
Are there plans to support Swift 4.0? Have found this library to be very useful, would love to use it in my latest project.

**Comment by Plnda** [comment]
@martijnwalraven what cocoa pods version do you use?

**Comment by martijnwalraven** [comment]
@Plnda: I haven't used the CocoaPods version, but all the tests pass in the latest alpha from the Xcode  project. What error messages do you get when using the pod?

**Comment by Plnda** [comment]
https://imgur.com/a/PLU23

**Comment by martijnwalraven** [comment]
@Plnda: I get those errors as well when compiling with Swift 4, but not Swift 3.2. I'm looking into these issues right now, but do you get these same errors with Swift 3.2?

**Comment by Plnda** [comment]
@martijnwalraven I only get them on swift 4

**Comment by martijnwalraven** [comment]
I believe Apollo iOS 0.7.0-alpha.2 should work with both Swift 3.2 and 4.0. Let me know if you encounter any difficulties!

**Comment by Plnda** [comment]
@martijnwalraven you can close this issue, got it working :)

**Comment by martijnwalraven** [comment]
@Plnda: Good to hear!

**Comment by Alienbash** [comment]
@martijnwalraven i am having the same issues as @Plnda with Swift 4 and did not get it working yet, so it would be appreciated if you could share a solution.

**Comment by martijnwalraven** [comment]
@Alienbash: Which version are you running? It should work with the latest 0.7.0 alphas.

**Comment by Alienbash** [comment]
@martijnwalraven Thanks for responding! I am currently running 0.6.5. Now it's running.
