### ISSUE TITLE
Am running to this error `Cannot find 'HTTPNetworkTransport' in scope` and `Cannot find type 'HTTPNetworkTransportDelegate' in scope` when am trying to make calls, ApolloClient Version 0.34.1

### ISSUE THREAD

**Issue by gbrigens** [apollographql/apollo-ios#1446]
Am running to this error `Cannot find 'HTTPNetworkTransport' in scope` and `Cannot find type 'HTTPNetworkTransportDelegate' in scope` when am trying to make calls, ApolloClient Version 0.34.1

Here is my code;
```
final class Network {
    static let shared = Network()
    private lazy var networkTransport: NetworkTransport = {
        
        let transport = HTTPNetworkTransport(url: URL(string: "https://exampe.com/grapghql")!)
        transport.delegate = self
        
        return transport
    }()
    
    private(set) lazy var apollo = ApolloClient(networkTransport: self.networkTransport)
}

extension Network: HTTPNetworkTransportDelegate {
    func networkTransport(_ networkTransport: NetworkTransport, shouldSend request: URLRequest) -> Bool {
        return true
    }
    
    func networkTransport(_ networkTransport: NetworkTransport, willSend request: inout URLRequest) {
        
        let token = ""
        var headers = request.allHTTPHeaderFields ?? [String: String]()
        headers["Authorization"] = "Bearer \(token)"
        
        request.allHTTPHeaderFields = headers
    }
}
```
I appreciate your feedback.

_Originally posted by @gbrigens in https://github.com/apollographql/apollo-ios/issues/909#issuecomment-706535757_

**Comment by designatednerd** [comment]
Hi! In 0.34.0 after an RFC and multiple betas, we released an updated networking stack which removed these methods in favor of a `RequestChainNetworkTransport`. Please see the [0.34.0 release notes](https://github.com/apollographql/apollo-ios/releases/tag/0.34.0) for links to updated documentation.

**Comment by gbrigens** [comment]
@designatednerd this is my first time working with Apolloclient and GraphQL. I have ted the one from the link still running into errors `Cannot find 'NetworkInterceptorProvider' in scope`... Do you have an example that shows passing authorization headers?

**Comment by designatednerd** [comment]
Yes, the [tutorial bit on additional mutations](https://www.apollographql.com/docs/ios/tutorial/tutorial-mutations/) has an example

**Comment by gbrigens** [comment]
@designatednerd thank you for your help, hope in future there will be more tutorials on iOS. I have been searching for content online and there isn't much compared to Android.

**Comment by designatednerd** [comment]
Yes, definitely in the long term plan to beef that up.

**Comment by tristangemus** [comment]
Definitely needs to be beefed up :)
