### ISSUE TITLE
run-bundled-codegen.sh: No such file or directory

### ISSUE THREAD

**Issue by mobile-simformsolutions** [apollographql/apollo-ios#1451]
## run-bundled-codegen.sh: No such file or directory

i'm implementing this demo as per the documentation (https://www.apollographql.com/docs/ios/tutorial/tutorial-obtain-schema) but after adding script into build phase it will showing me this error:

**Command PhaseScriptExecution failed with a nonzero exit code**
**Script-3E447D9625386A88004AD507.sh: line 10: /run-bundled-codegen.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code**

![Screenshot 2020-10-16 at 10 32 30 AM](https://user-images.githubusercontent.com/63225913/96215184-e8337a00-0f9a-11eb-8a38-b02591340731.png)

## Versions
0.34.1

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.34.1
- Xcode version: 12.0.1
- Swift version: 5

**Comment by designatednerd** [comment]
It looks like you may have skipped step 6, in which you add the build script where the script path is retrieved. It links to [these instructions](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) which are separated out by package manager.

**Comment by mobile-simformsolutions** [comment]
got it thanks but one suggestion for documentation please make one section where whole script was there.

**Comment by designatednerd** [comment]
Appreciate the feedback - for what it's worth the reason it's linked is because those instructions had been changing enough that having it in two places meant that it was going to constantly get out of sync.
