### ISSUE TITLE
Swift scripting error with xcode 12

### ISSUE THREAD

**Issue by jdevng** [apollographql/apollo-ios#1453]
## Bug report

Initialization of Codegen directory at 

https://www.apollographql.com/docs/ios/swift-scripting/

results in error.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.35
- Xcode version:  12.0.1
- Swift version: Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)

## Steps to reproduce
```

% swift packet init --type executable
error: unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-packet (No such file or directory)
```

## Further details

Please replace this line with any further details or context necessary to understand the problem. Delete this section if you don't have anything further to add.

**Comment by designatednerd** [comment]
I think you mean `swift package --init` rather than `swift packet --init`

**Comment by jdevng** [comment]
I'm blind. Will delete :) Thank you. Should learn to copy!
