### ISSUE TITLE
set the timeout of the ApolloCodegenLib

### ISSUE THREAD

**Issue by wongzigii** [apollographql/apollo-ios#1456]
I am following the guide to download zip file with CLI.
How can I set the timeout of the ApolloCodegenLib:CLIDownloader ?
My network is so bad :(

```
swift run
[DEBUG - ApolloCodegenLib:CLIDownloader.swift:72] - Downloading zip file with the CLI...
downloadTimedOut(after: 30.0)
```

**Comment by designatednerd** [comment]
For anyone stumbling across this, all of the methods to call into the codegen lib should have a `timeout` parameter.

**Comment by sinkcup** [comment]
This bug have not be fixed...

I find the HACK way:

```
vi ApolloCodegen/.build/checkouts/apollo-ios/Sources/ApolloCodegenLib/CLIDownloader.swift
```

change `timeout: timeout` to `timeout: 600`

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/4971414/187190361-3ec9e635-d57e-453a-a31d-892365705071.png">
