### ISSUE TITLE
Create WebsocketTransport without connecting automatically

### ISSUE THREAD

**Issue by winstondu** [apollographql/apollo-ios#1457]
## Feature request

Currently, the designated initializer for the WebSocketTransport[ immediately connects the websocket. ](https://github.com/apollographql/apollo-ios/blob/cf537701e407bed1a13df6dd6288d641abdda42a/Sources/ApolloWebSocket/WebSocketTransport.swift#L128)

We wish to manually control when it does its first connection.

## Motivation

We want to our app's webservers to able to handle load, and at high traffic times we actually want the ability to disable automatic websocket connections to our server at app startup.

## Proposed solution

Add a parameter to the [designated initializer](https://github.com/apollographql/apollo-ios/blob/cf537701e407bed1a13df6dd6288d641abdda42a/Sources/ApolloWebSocket/WebSocketTransport.swift#L128) on whether the websocket should connect immediately on initialization. In otherwords, wrap the `websocket.connect()` call in an `if` statement.

Additional notes:  
Because the mutex-locked `reconnect` parameter only comes into play after the the first disconnection (which can only happen after the first connection), that parameter does not affect things.
  
## Outstanding Questions
- It is up to the implementor to decide whether there should be a separate api for the first websocket connection, or if the developer can just call `reconnectWebSocket()`

**Comment by designatednerd** [comment]
Seems like a reasonable request, and thank you for adding a PR! I'll keep feedback over on the PR just for the sake of clarity.
