### ISSUE TITLE
allowSpecificHTTPSCertificateForHost warning in iOS 14

### ISSUE THREAD

**Issue by DiwakarThapa** [apollographql/apollo-ios#1459]
I started receiving following warning on Xcode after I update my iPhone to iOS 14. How to fix this warning? 
 ## Warning
nil host used in call to allowSpecificHTTPSCertificateForHost: 
nil host used in call to allowAnyHTTPSCertificateForHost:
nil host used in call to allowSpecificHTTPSCertificateForHost: 
nil host used in call to allowAnyHTTPSCertificateForHost:

## Network Transport 
private  var networkTransport: HTTPNetworkTransport  {
        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForResource = 65
        configuration.timeoutIntervalForRequest = 65
        let client = URLSessionClient(sessionConfiguration: configuration)
        let transport = HTTPNetworkTransport(url: URL(string: self.baseUrl)!, client: client)
        transport.delegate = self
        return transport
    }
## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.30.0
- Xcode version: 11.2.1
- Swift version:  5

**Comment by designatednerd** [comment]
Wow, weird! Never seen that before. We're not doing anything that I'm aware of that should be calling any of those methods. 

Would be curious if this is still happening in versions `0.34.0` and above - we made some pretty significant changes to the networking stack there.

**Comment by designatednerd** [comment]
@DiwakarThapa Is there any further information you can share here?

**Comment by designatednerd** [comment]
Since I haven't heard back in a couple weeks, I'm going to close this out - @DiwakarThapa if you get more info feel free to reopen. Anyone else with a similar problem, please open a new issue. Thank you!
