### ISSUE TITLE
graphql file with description

### ISSUE THREAD

**Issue by wongzigii** [apollographql/apollo-ios#1462]
Any way to add description to graphql file? This results in errors in compile time.

A good example would be:

```
"""
A simple GraphQL schema which is well described.
"""
schema {
  query: Query
}
```

http://spec.graphql.org/draft/#sec-Descriptions

**Comment by designatednerd** [comment]
In theory that should not result in errors - can you give an example of a file where this is resulting in errors, along with the errors? Any information around your setup would also be really helpful.

**Comment by wongzigii** [comment]
Just add 

    """
    A simple GraphQL schema which is well described.
    """

to the first line of any .graphql file and you will see the error

    Showing Recent Messages
    Error: Syntax error in 

    file:///Users/mac/a.graphql: Syntax 

    Error: Unexpected Name "query".

**Comment by designatednerd** [comment]
Are you trying to add this to your operation graphQL files, or to the Schema graphQL file? This syntax is intended for the schema - you can see an example in [the version of the GitHub Schema we're using for some tests](https://github.com/apollographql/apollo-ios/blob/main/Sources/GitHubAPI/schema.docs.graphql). 

If you were to try to add this to an operation's graphQL file like: 

```graphQL
"""
A simple GraphQL schema which is well described.
"""
query UserInfo($id: ID!) {
  user(id: $id) {
    name
  }
}
```

That would not compile. Does that help?

**Comment by designatednerd** [comment]
@wongzigii Any thoughts on my response?

**Comment by wongzigii** [comment]
Good to know! Thanks @designatednerd
