### ISSUE TITLE
Using same query with different set of fields

### ISSUE THREAD

**Issue by vani2** [apollographql/apollo-ios#1477]
## Question

I have query of `draftProfile` and `profile`

```GraphQL
query fetchProfile {
    draftProfile {
        firstName
        secondName
    },
    profile {
        firstName
        secondName 
    }
}
```

Later I need to make the same query but only `profile` object.

```GraphQL
query fetchProfile {
    profile {
        firstName
        secondName 
    }
}
``` 

If I declare these two queries I get the error `There are multiple definitions for the `fetchProfile` operation. Please rename or remove all operations with the duplicated name before continuing.`.

How I can make it possible? 

## Versions

- `apollo-ios` SDK version: 0.35
- Xcode version: 12.0
- Swift version: 5.3

**Comment by designatednerd** [comment]
You need to give the two queries different names. Maybe `FetchProfileWithDraft` for that top one?

**Comment by vani2** [comment]
Oh, yes, that's easy. Thanks.
