### ISSUE TITLE
Accessing and setting cookies on requests

### ISSUE THREAD

**Issue by gabek** [apollographql/apollo-ios#148]
Is there currently a way to get cookies that a server has set when making a query?  Alternately, is there a way to set cookie and/or header values on a per-request basis?

Thanks!

**Comment by designatednerd** [comment]
This is now possible in v0.11.0 - use the `HTTPNetworkTransportTaskCompletedDelegate` to grab info your server has returned and use `HTTPNetworkTransportPreflightDelegate` to set the cookie on an outgoing query.
