### ISSUE TITLE
Race condition when unsubscribing

### ISSUE THREAD

**Issue by marioradonic** [apollographql/apollo-ios#1486]
## Bug report

I've been randomly (but often) getting `.unprocessedMessage` errors in my `.subscribe(...` handlers. I had a look at the code and it seems to me that there is a possible race condition.

When [unsubscribing](https://github.com/apollographql/apollo-ios/blob/e0f65fee8c197239dbefbf1386b8e7f83b684f25/Sources/ApolloWebSocket/WebSocketTransport.swift#L301) from a subscribe task websocket message is sent requesting the subscription to stop and handler is released. It might be possible that a message is received from the socket with the update before the backend has time process this stop message and stop sending the messages. So in the [processMessage](https://github.com/apollographql/apollo-ios/blob/e0f65fee8c197239dbefbf1386b8e7f83b684f25/Sources/ApolloWebSocket/WebSocketTransport.swift#L146) method we end up in [this clause](https://github.com/apollographql/apollo-ios/blob/e0f65fee8c197239dbefbf1386b8e7f83b684f25/Sources/ApolloWebSocket/WebSocketTransport.swift#L177) because there is no subscription handlers any more. And then **all** the other handlers are notified about this error. This doesn't seem right to me as there was nothing wrong with other subscriptions.

I'm not an expert in web sockets, so I don't know what the best solution would be. Maybe wait for the ack message from backend? But then the subscriber might get a message after cancelling the task, which is not nice. Maybe keep an intermittent array of task ids whose cancellation hasn't been acknowledged by the backend and ignore messages for those subscribers? That is if there is a stop acknowledge message from backend.

I don't mind creating a PR if someone suggests the approach on how to fix this.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.35.0
- Xcode version: 12.1
- Swift version: 5.3

## Steps to reproduce

I have a rx code in format of:
`subscribeSomething().flatMapLatest { subscribeSomethingElse(using: $0) }`

When the first subscription updates the second one is cancelled and new one is created.

## Further details

I can probably restructure my query so it's all done in one subscription, which would fix my issue but the underlying problem will still be there although it might happen less often.

**Comment by fassko** [comment]
I was using GraphQL subscriptions with just one subscription. Otherwise, you can run into these weird side effects that you explained.

**Comment by designatednerd** [comment]
@fassko Well, it was worth a shot 🙃

@marioradonic - Are you subscribing to the same `subscription` from your schema multiple times, or are there different `subscription`s defined that you're using? Basically, are your multiple subscriptions all returning the same information, or different information?

**Comment by marioradonic** [comment]
@designatednerd I am using multiple. Basically, I am subscribing to entity A, and when it updates I subscribe to entity B, cancelling the previous B subscription if there was any. (this cancelled subscription causes the problem - if the message comes from the backend with the cancelled subscription id the first entity A subscriber and the new B subscriber get the error message.

I had another look at the websocket connection and it seems there is no closing acknowledgment message from the backend upon closing the subscription. So I'm not sure at which point should an unhandled message be considered an internal error. In any case I don't think it's a good API design that all the other subscribers get the error message, since nothing is wrong with their subscriptions. Maybe there could be a global error handler for these kinds of errors?

**Comment by designatednerd** [comment]
>cancelling the previous B subscription if there was any. 

In theory you shouldn't have to cancel any existing subscription to entity B - if you've already got a running subscription it should continue to get all updates.

It may help me understand a bit better if you can give a concrete example of what entity A and entity B are representing. To take an example from our sample code, if you've subscribed to all reviews of Star Wars episodes, then as soon as you get a review of _Return of the Jedi_ kick off a second subscription that only handles _Jedi_ reviews, any further reviews that come in on that first subscription for _Jedi_ would also come in on the second subscription, without needing to stop and restart.

**Comment by designatednerd** [comment]
@marioradonic Can you share some examples of what's happening?

**Comment by designatednerd** [comment]
Since I haven't heard back on examples in a few weeks, I'm going to close this out. @marioradonic if you have some examples please feel free to reopen. If anyone else has a similar problem, please open a new issue. Thank you!
