### ISSUE TITLE
Add support for `internal` generated types

### ISSUE THREAD

**Issue by rjchatfield** [apollographql/apollo-ios#149]
The generated code currently assumes `public` access for all classes and methods.

```swift
public final class IssueCommentsQuery: GraphQLQuery {
  public static let operationString =
  ...
```

It would be good to have the ability to change that to `internal` using a flag.

```swift
internal final class IssueCommentsQuery: GraphQLQuery {
  internal static let operationString =
  ...
```

The compiler (with -WMO) doesn't help much with optimising public Types. If we made it internal, it will help with the compile times for both the my framework and the users of my framework.

Suggestion:

`apollo-codegen generate --swift-access-public false`

**Comment by martijnwalraven** [comment]
Yeah, I definitely think this makes sense as an option.

**Comment by mhays118** [comment]
I just recently ran into the need to make this change, and it is pretty easy to do if you add 

`sed -i '' 's/public/internal/g' YOUR_GENERATED_FILENAME.swift`  

at the end of your current apollo run script in Xcode. 

The sed command will go through the swift file and replace every instance of `public` with `internal`.

**Comment by designatednerd** [comment]
Support added for Swift Codegen only in #1072 - this is not backwards compatible to our typescript codegen.

**Comment by designatednerd** [comment]
Marking this as closed and completed since this is actually written. This will ship with the [Swift Code Generation Phase 1 Alpha Milestione](https://github.com/apollographql/apollo-ios/milestone/23) - please follow that milestone to see when this will ship.
