### ISSUE TITLE
How to fix that error?

### ISSUE THREAD

**Issue by zinminphyo** [apollographql/apollo-ios#1495]
## Bug report

Please replace this line with a short description of the problem. Make sure you've read `CHANGELOG.md` in the root of the repo to make sure a new version hasn't already addressed your problem!

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.34.1
- Xcode version: 12.0
- Swift version: 5
<img width="1440" alt="Screen Shot 2020-11-04 at 11 15 54" src="https://user-images.githubusercontent.com/33368347/98070409-7f4f6b80-1e8f-11eb-8a83-0e96e4de9321.png">

- Package manager:

## Steps to reproduce

Please replace this line with steps to reproduce the problem.

## Further details

Please replace this line with any further details or context necessary to understand the problem. Delete this section if you don't have anything further to add.

**Comment by designatednerd** [comment]
@zinminphyo Can you please share more details about when and how this happened? It's not something I can necessarily tell you why it's happening without more detail.

**Comment by designatednerd** [comment]
Since I haven't gotten any further details here, I'm going to close this out. @zinminphyo Please reopen with further details if you have them. Anyone else with a similar problem, please open a new issue. Thank you!
