### ISSUE TITLE
Generate Apollo GraphQL Api Bitrise issue

### ISSUE THREAD

**Issue by Kevin94singh** [apollographql/apollo-ios#1496]
Hi,

When building on a local machine with Fastlane, everything works ok. However, when I try to upload my build with Bitrise, I'm getting an error: 

```
- ▸ Running script 'Generate Apollo GraphQL API'
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution Generate\ Apollo\ GraphQL\ API /Users/vagrant/Library/Developer/Xcode/DerivedData/project_name-asogvanbfzdyhybkhoculdmlwwfk/Build/Intermediates.noindex/ArchiveIntermediates/project_name_beta/IntermediateBuildFilesPath/project_name.build/Release-iphoneos/project_name_beta/Script-7A325491234C77FE003B1AE2.sh
(1 failure)
[11:36:34]: Exit status: 65
```
**Our Generate Apollo GraphQL API script**

```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/ProjectName"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
```

| - project_folder
    | project.xcodeproj
    | - target_folder 
        | schema.json
        | AppDelegate.swift
        | ViewController.swift
        | etc...
    | - another_folders
        | etc...

**Apollo version: 0.30, iOS, Bitrise Fastlane version 2.7.x ** We have two targets (prod and beta), currently trying to build for Beta.

I think that there might be an issue with NPM. In our workflow on Bitrise, I've set `run npm command`- `install -g apollo@2.25` - the version I have on my machine. But this step doesn't help.

**Comment by designatednerd** [comment]
If you're using `run-bundled-codegen` it shouldn't be an issue with NPM - the bundled codegen downloads Node and all dependencies as a workaround because we were having *so* many problems with NPM.  It certainly seems like another issue is happening that's causing the code generation to fail but isn't spitting out a reason correctly. 

I take it things build correctly when you try to run this locally?

**Comment by Kevin94singh** [comment]
> If you're using `run-bundled-codegen` it shouldn't be an issue with NPM - the bundled codegen downloads Node and all dependencies as a workaround because we were having _so_ many problems with NPM. It certainly seems like another issue is happening that's causing the code generation to fail but isn't spitting out a reason correctly.
> 
> I take it things build correctly when you try to run this locally?

Yes, when I run this locally with Fastlane, it builds correctly.

**Comment by designatednerd** [comment]
Weird - and are you using Fastlane on bitrise as well, or something else?

**Comment by Kevin94singh** [comment]
Yes, we are using Fastlane. Our steps for a workflow are Activate SSH Key, Git Clone repository, and Fastlane (set to a version 2.x.x, that is currently 2.7.1).

**Comment by designatednerd** [comment]
Cool, thanks for clarifying - how are you setting things to "beta" - using a Scheme or a build configuration or some combination thereof?

**Comment by Kevin94singh** [comment]
We have two schemes - "beta" and "prod". Each has its own target. The script is implemented in both targets .

**Comment by designatednerd** [comment]
And am I correct in assuming the `.graphql` files and `API.swift` output are in the same folder (under `"${SRCROOT}/ProjectName"`), just shared between both targets? 

Honestly, if it's working locally and the only error info you're getting from Bitrise is a generic exit code 65, I'm not sure how much help I can be - you may want to reach out to them to see if you can get more detailed logs about what's not building on your beta version. 

One thing I have tried in the past when something's building locally but not on CI for me is to check it back out in a separate folder and try from there - I've definitely found issues where there's some kind of local config not checked into version control that means it works in your main working directory, but not for anyone else (including CI) that checks it out. Probably worth a shot just to rule that out as a cause.

**Comment by Kevin94singh** [comment]
Yes, it is shared between both targets. Prod build shows the same failure as a beta. 

I'll try to get more detailed logs and let you know. Thank you for your time! 😊

**Comment by designatednerd** [comment]
@Kevin94singh any luck getting more details?

**Comment by Kevin94singh** [comment]
@designatednerd  Hey, I'm in touch with a Bitrise team. We haven't resolved the issue yet.

**Comment by designatednerd** [comment]
@Kevin94singh any progress?

**Comment by Kevin94singh** [comment]
Hey @designatednerd, 

just got it working! I had to add a script before the Fastlane step and change stacks on Bitrise.

script:

```
cd Pods/Apollo/scripts
rm -f apollo.tar.gz
rm -rf apollo
```

**Comment by designatednerd** [comment]
weird! I wonder why you had to do that given that the script should be automatically deleting old versions. In any case, I'm glad to hear you got it figured out. Mind if we close this out?

**Comment by Lizard381** [comment]
We're also having a problem with apollo client: check in bitrise all of a sudden, where it isn't finding the graphql files. We switched to using npm for apollo when we moved to SPM, if we were to use run-bundled-codegen, where does that live in an SPM world @designatednerd?

**Comment by designatednerd** [comment]
@Lizard381 Check out the [SPM run script in this section of the setup docs](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step)

**Comment by Lizard381** [comment]
I haven't been able to get the SPM run script to work from the terminal, it just hangs, which means it won't work in bitrise either.

**Comment by designatednerd** [comment]
So the script is not designed to be run directly from the terminal since it depends on several variables that are passed through from the Xcode project to figure out where the derived data is. It should be run as part of a Run Script Build Phase. 

Not 100% sure why it would sit and spin instead of just erroring out, though.

**Comment by alexisbronchart** [comment]
I just ran into the same issue, using apollo-ios 0.41 with cocoapods. Were there any further developments on this?
@Kevin94singh what made it work for you? only the script or the change of bitrise stack? Also which stack are you using? I'm running on Xcode 12.4.x, on macOS 10.15.7.

> Hey @designatednerd,
> 
> just got it working! I had to add a script before the Fastlane step and change stacks on Bitrise.
> 
> script:
> 
> ```
> cd Pods/Apollo/scripts
> rm -f apollo.tar.gz
> rm -rf apollo
> ```

**Comment by designatednerd** [comment]
I hadn't heard anything more here so I was getting ready to close this out - if removing the `apollo.tar.gz` and `apollo` folder fixed it, it sounds like there's something going on with the bitrise cache. @alexisbronchart have you tried that?

**Comment by alexisbronchart** [comment]
@designatednerd I tried indeed and it doesn't work (why would it because it failed from the start for me and I don't have any caching enabled in bitrise). Trying to get a more verbose output.

**Comment by designatednerd** [comment]
OK @alexisbronchart it sounds like you're having a separate issue - do you mind opening a new issue so we can focus on the problem that you're having? It'd help to know some of the same info shared here: What's your generation script, what is the exact error you're getting, what's the structure of your project.

**Comment by alexisbronchart** [comment]
@designatednerd I'm OK to open another issue but it looks very much the same than this one.
Generation script:
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="../../schema.json" GraphQL/API
```

Error in bitrise logs:

```
The following build commands failed:
	PhaseScriptExecution Generate\ GraphQL\ API /Users/vagrant/Library/Developer/Xcode/DerivedData/EliumMobile-aappjanzzrvmovbictmdiertaibi/Build/Intermediates.noindex/ArchiveIntermediates/Elium.release/IntermediateBuildFilesPath/EliumMobile.build/Release-iphoneos/ShareExtension.build/Script-0C1D177B259B235800BB67E1.sh
(1 failure)
[10:06:55]: Exit status: 65
```

I still haven't figured out how to get the actual console output of the script. I guess it would be more helpful. Any suggestion?
LMK if you still want me to make another issue.

**Comment by designatednerd** [comment]
Yes, I would still like you to make another issue since the thing that solved @Kevin94singh's issue did not solve yours, so even if it has similar symptoms it's almost certainly a different problem. 

I would reach out to the Bitrise folks to find out how they recommend getting the full outlook - I haven't worked with Bitrise enough to tell you how that would work.

**Comment by alexisbronchart** [comment]
> Yes, I would still like you to make another issue since the thing that solved @Kevin94singh's issue did not solve yours, so even if it has similar symptoms it's almost certainly a different problem.
> 
> I would reach out to the Bitrise folks to find out how they recommend getting the full outlook - I haven't worked with Bitrise enough to tell you how that would work.

Allright I opened https://github.com/apollographql/apollo-ios/issues/1684 
I'll talk to bitrise folks and post my findings there. Thanks!

**Comment by designatednerd** [comment]
OK, I'm gonna go ahead and close this one out since @Kevin94singh found a workaround. If you're having similar symptoms and his workaround doesn't work, please file a new issue. Thank you!
