### ISSUE TITLE
callbackQueue is not used in WebSocketTransport

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#1504]
## Bug report

https://github.com/apollographql/apollo-ios/blob/185d6b784538691b5a4287c25df9cae140abec02/Sources/ApolloWebSocket/WebSocketTransport.swift#L361 callbackQueue is unused

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.36.0

## Steps to reproduce

subscribe using any callbackQueue, callback is done on some internal one

**Comment by designatednerd** [comment]
Welp, that's embarrassing. Fix is up in #1507.

**Comment by RolandasRazma** [comment]
thanks

**Comment by designatednerd** [comment]
Thank YOU for catching it
