### ISSUE TITLE
WebSocketTransport.send completionHandler is called in non escaping manner in case of error

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#1505]
## Bug report

https://github.com/apollographql/apollo-ios/blob/185d6b784538691b5a4287c25df9cae140abec02/Sources/ApolloWebSocket/WebSocketTransport.swift#L364

completionHandler is called in non escaping manner in case of error

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.36.0

**Comment by designatednerd** [comment]
Do you mean it's not called on the callback queue?

**Comment by RolandasRazma** [comment]
Was thinking about @escaping but yes, calling it on callback cue would fix that

**Comment by designatednerd** [comment]
It's declared as [`@escaping` here](https://github.com/apollographql/apollo-ios/blob/185d6b784538691b5a4287c25df9cae140abec02/Sources/ApolloWebSocket/WebSocketTransport.swift#L362) - declaring escaping does not require it to escape, though.

**Comment by RolandasRazma** [comment]
sure, but it might break flow depending on what's happening internally

```swift
WebSocketTransport.send {
   print("a")
}

print("b")
```

what order will be output depends on internal state and that's not great.

In any case, closing as https://github.com/apollographql/apollo-ios/pull/1507 fixes it
