### ISSUE TITLE
Compatibility issues on Linux with CommonCrypto

### ISSUE THREAD

**Issue by abdimaye** [apollographql/apollo-ios#1506]
## Feature request

The CommonCrypto module is only available in Xcode 10+. It would be nice to have this replaced with an open source module such that the apollo client can run on other platforms.

## Motivation

We are currently trying to run parts of our codebase on Linux.

## Proposed solution

Replace CommonCrypto with an open source library. There are only two files in ApolloCore that use it and the diff wouldn't be that big. 

I was looking at `swift-crypto` https://swift.org/blog/crypto/ but there are compatibility issues where it requires mocos 10.15 and apollo requires 10.10.

**Comment by designatednerd** [comment]
We don't *officially* support Linux, but I would very much like to. My thought is that we could make some kind of protocol that uses `swift-crypto` for Linux band still uses `CommonCrypto` on iOS etc. Would be more than open to a PR if you have some time, I'm buried at the moment.

**Comment by abdimaye** [comment]
I started on these changes a couple of weeks ago but got sidetracked on other things... I'll create a draft PR now for visibility as there are more changes required than expected 😣.

**Comment by AnthonyMDev** [comment]
Linux support is something we are still considering for some time in the future. I'm going to close this inactive outdated issue though.
