### ISSUE TITLE
Xcode crashes b/c API.swift is too large :/

### ISSUE THREAD

**Issue by MaximusMcCann** [apollographql/apollo-ios#151]
Please, this needs to be split into multiple files.  ours is > 40,000 lines now and Xcode freezes every time.

Xcode 9 (9A235)

**Comment by martijnwalraven** [comment]
I agree we should split `API.swift` into multiple files, but I'd like to find a way that doesn't force you to manually add a `.swift` file to your project for every `.graphql`. We may be able to use an automatic file type mapping between input and output files (also see https://github.com/apollographql/apollo-ios/issues/147), but it isn't clear to me how you'd set up something like that.

For now, https://github.com/apollographql/apollo-ios/issues/152 suggests the Swift compiler's handling of string concatenation might have a significant impact on the compile time. Could you try Apollo iOS 0.7.0-alpha.5 and see if that makes a difference?

**Comment by Sherlouk** [comment]
Definitely not an ideal solution especially as it introduces a new dependency but I wonder if [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) could be used to automatically add the necessary files?

While the fix in alpha 5 may help a little bit, most of Apple's issues I find are to do with file sizes which new lines are not a major issue.

**Comment by martijnwalraven** [comment]
I've added experimental support for generating multiple files to `apollo-codegen`, available in Apollo iOS 0.7.0-alpha.7. 

If you specify a directory instead of a file as `--output`, it will generate matching `.graphql.swift` files for every `.graphql` file. In addition, it will generate `Types.graphql.swift` with shared types used in the input files.

Would be great to get feedback and see if this helps improve compilation speed. 

I would still like to find a better way to integrate this with Xcode, so you don't have to manually add `.graphql.swift` files to your project. I'm hoping Xcode build rules may help us get there, but there are some rough edges. Let's continue that discussion in #147.

**Comment by martijnwalraven** [comment]
@MaximusMcCann: Have you had a chance to test whether outputting multiple files helps solve your Xcode performance issues?

**Comment by MaximusMcCann** [comment]
Hey Martijn, not yet, but I will have time this week to 👍. Cheers

בתאריך יום ד׳, 4 באוק׳ 2017 ב-9:17 מאת Martijn Walraven <
notifications@github.com>:

**Comment by MaximusMcCann** [comment]
@martijnwalraven Opening the generated files does not crash Xcode now :)
`0.7.0-alpha.8`.  Looking fwd to the work on #147!

**Comment by julien1619** [comment]
Hi! I'm using Apollo too and I've noticed that in Xcode 9 CoreData generates its files in the DerivedSources folder `$DERIVED_SOURCES_DIR` and they are kept cached here.

So I was wondering if there wasn't any way to use it the same way that CoreData does?

If I follow the build process, these files do not appear in the Sources files list at first. Just before compiling, just after the apollo-codegen script, xcdatamodel generate these files if needed and, automagically, they appear in the list that will be compiled. I think, the question is, how are they passed to the compiler and made accessible to Xcode autocompletion?

**Comment by martijnwalraven** [comment]
Yeah, that's exactly how I would like to get things working. Unfortunately, there is no supported way to do this, and Core Data relies on APIs that are not available to the current Xcode plugin mechanism. I've been able to reverse engineer some of the Xcode machinery to define a custom compiler and build rule, but I'm hitting a wall getting it to recognize multiple output files.

**Comment by martijnwalraven** [comment]
@julien1619: I [opened a PR](https://github.com/apollographql/xcode-graphql/pull/6) with some of the reverse engineering experiments I did, but unfortunately it seems we need to look at other solutions.

Closing this issue in favor of #147, so we can discuss further there.
