### ISSUE TITLE
Query variables escapes forward slash

### ISSUE THREAD

**Issue by fnky** [apollographql/apollo-ios#1517]
## Bug report

Query variable values escapes forward slash from `foo/bar` to `foo\/bar`.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.36.0
- Xcode version: 12.2 (12B45b)
- Swift version: 5.3.1
- Package manager: SwiftPM

## Steps to reproduce

1. Define a query with variables:
    ```graphql
    query ExampleQuery($variable: String) {
        someQuery(variable: $variable) { ... }
    }
    ```
2. Fetch the query with the variable set to a string, including one or more forward slashes, e.g. `foo/bar/baz`.
3. Log the request object (see example interceptor below)
4. See the variable value be escaped as `foo\/bar\/baz`.

## Further details

Here's the interceptor I use to log out the request JSON data:

```swift
extension Data {
    var prettyPrintedJSONString: NSString? { /// NSString gives us a nice sanitized debugDescription
        guard let object = try? JSONSerialization.jsonObject(with: self, options: []),
              let data = try? JSONSerialization.data(withJSONObject: object, options: [.prettyPrinted]),
              let prettyPrintedString = NSString(data: data, encoding: String.Encoding.utf8.rawValue) else { return nil }

        return prettyPrintedString
    }
}

class RequestLoggingInterceptor: ApolloInterceptor {
    func interceptAsync<Operation: GraphQLOperation>(
        chain: RequestChain,
        request: HTTPRequest<Operation>,
        response: HTTPResponse<Operation>?,
        completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void
    ) {
        print("debug: Outgoing request: \(request)")

        do {
            let urlRequest = try request.toURLRequest()
            if let body = urlRequest.httpBody {
                print("Body: \(body.prettyPrintedJSONString ?? "<none>")")
            }
        } catch {
            print("Couldn't get URL request.")
        }

        chain.proceedAsync(request: request,
                           response: response,
                           completion: completion)
    }
}
```

**Comment by fnky** [comment]
Not sure if this is actually an issue.

**Comment by designatednerd** [comment]
Yeah I would definitely say it's worth trying this with an actual server - my recollection is that escaping strings is a requirement of JSON itself that's done by `NSJSONSerialization`, and that should be handled by the receiving server.
