### ISSUE TITLE
Error decoding Array while using custom scalars in iOS swift

### ISSUE THREAD

**Issue by Trupti-nayak** [apollographql/apollo-ios#1523]
### Apollo graphQL doesn't convert json array. 

I have schema as show below. Here question_r is an array of dictionaries received as Json. I am facing issue converting it. Is there any way i can successfully decode it?

**This is the error:** couldNotConvert(value: <__NSSingleObjectArrayI ... to: Swift.Dictionary<Swift.String, Swift.Optional<Any>>)"

**This is the response in playground:** 

```
"questionR": [
                              {
                                "identifier": "123",
                                "skills": {
                                  "primary_skill": "vocabulary",
                                  "secondary_skill": "reading",
                                }
                              }
                            ]
```

```
**This is the schema.json**
 {
            "name": "question_r",
            "description": "",
            "args": [],
            "type": {
              "kind": "SCALAR",
              "name": "Json",
              "ofType": null
            },
            "isDeprecated": false,
            "deprecationReason": null
          }

```

**My script looks like this:**

SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --passthroughCustomScalars --localSchemaFile="schema.json" API.swift

I was able to get custom scalars working for dictionary but not array using this issue link:

[Link]https://github.com/apollographql/apollo-ios/issues/36

**Comment by designatednerd** [comment]
OK, you are using `passthroughCustomScalars` - can i see the code where you're defining the `Json` type to make it conform to Apollo's `JSONDecodable` protocol?

**Comment by Trupti-nayak** [comment]
Here i am defining the type
```
public typealias Json = [String:Any?]

extension Dictionary: JSONDecodable {
    public init(jsonValue value: JSONValue) throws {
        guard let dictionary = value as? Dictionary else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Dictionary.self)
        }
        self = dictionary
    }
}
```

**Comment by designatednerd** [comment]
So is `Json` always guaranteed to have an outer `[String: Any?]` dictionary? If it's not, then you probably need to typealias to `Any` instead, since otherwise that typealias will fail for an array. 

I'm not positive what else you'd need to do in order to get it to work from there, though - maybe see if just changing the typealias works?

**Comment by Trupti-nayak** [comment]
I tried using Any it shows errors. But according to this comment is Any supported as custom scalars. 
[link]https://github.com/apollographql/apollo-ios/issues/23

**Comment by Trupti-nayak** [comment]
<img width="822" alt="Screenshot 2020-11-17 at 10 57 59 AM" src="https://user-images.githubusercontent.com/25178032/99350179-c3952f80-28c3-11eb-832c-98b7fdace4b3.png">

**Comment by designatednerd** [comment]
It would be really helpful to see what those errors are.

**Comment by Trupti-nayak** [comment]
<img width="814" alt="Screenshot 2020-11-17 at 12 03 09 PM" src="https://user-images.githubusercontent.com/25178032/99354661-de1fd680-28cc-11eb-96c6-ee0ba7d475d8.png">

**Comment by Trupti-nayak** [comment]
Should there be a change in Schema.json 
```
        {
            "name": "question_r",
            "description": "",
            "args": [],
            "type": {
              "kind": "SCALAR",
              "name": "Json",
              "ofType": null
            },
            "isDeprecated": false,
            "deprecationReason": null
          }
```

**Comment by designatednerd** [comment]
It's not a question of the definition in the schema, it's more a question of what your server is doing under the hood to create that scalar and what its underlying type is - a dictionary or an array. If it can return either, that makes generating a type for it much more difficult since at that point it's basically `Any`. 

I would give a shot to doing an `extension Json: JSONDecodable` that tries to determine if you can turn the returned objects into the appropriate types of dictionary, but you're seeing here why having arbitrary JSON returned isn't really super-helpful when it comes to dealing with a typed language.

**Comment by Trupti-nayak** [comment]
thank you i got it working by assuming Json to be an array and converting a dictionary to array. 

```
public typealias Json = [[String:Any?]]

extension Json: JSONDecodable{
 
    public init(jsonValue value: JSONValue) throws{
        guard let array = value as? Array else {
            guard let dict = value as? Dictionary<String, Any> else { throw JSONDecodingError.couldNotConvert(value: value, to: Dictionary<String, Any>.self)
            }
            self = .init(arrayLiteral: dict)
            return
        }
        self = array
    }
}
```

Although this would be a temp solution.

**Comment by designatednerd** [comment]
I think it might be clearer to have the inner array initializer it be `self = [dict]`, and this doesn't cover the situation where an array wraps another array. 

However, if you can guarantee that you either have a root dictionary _OR_ an array that wraps a dictionary, this should work longer-term. There's probably something recursive you can set up to make it work, but honestly, GraphQL isn't super-designed to return arbitrary JSON.

**Comment by alkincakiralar1996** [comment]
We had a similar problem above and we managed to solve it with the code below.

But because our api.swift file is rebuilt every time, typealias we defined freezes back to string.

```
typealias Coordinates = [[[Double]]]

extension Array: JSONDecodable {
  /// Custom `init` extension so Apollo can decode custom scalar type `CurrentMissionChallenge `
  public init(jsonValue value: JSONValue) throws {
    guard let array = value as? Array else {
      throw JSONDecodingError.couldNotConvert(value: value, to: Array.self)
    }
    self = array
  }
}
```

How do we ensure that it stays the typealias we define every time ?

**Comment by designatednerd** [comment]
Definitely put it in a different file than `API.swift` - as you said, `API.swift` is constantly overwritten.

**Comment by Thecrazyskull** [comment]
I'm having a similar problem. Although @Trupti-nayak's fix works, it's not a good fix because it assumes that the JSON structure will be an array. What if I have an object (with key:value structure in the root). I would have to change the type in the server, which too, is not a good solution. How would you suggest handling a case where the returned JSON can both be an object and an array at the same time? @designatednerd

**Comment by Trupti-nayak** [comment]
Hi i have tried creating my own type and using it like this.

```
public typealias Json = AnyType
public struct AnyType: JSONDecodable{
    var value: Any
    public init(jsonValue value: JSONValue) throws {
        self.value = value
    }
}
```

Although this has not be tested for all types. Any improvements/suggestions are welcome @designatednerd @Thecrazyskull

**Comment by designatednerd** [comment]
OK, gave this a think and representing it as an enum should at least help a bit in terms of being able to stay kiiiinda type safe: 

```swift
public typealias Json = JSONType
public enum JSONType: JSONDecodable {
    case dictionary([String: Any])
    case array([Any])
    
    public init(jsonValue value: JSONValue) throws {
        switch value {
        case let dictionary as [String: Any]:
            self = .dictionary(dictionary)
        case let array as [Any]:
            self = .array(array)
        default:
            throw JSONDecodingError.couldNotConvert(value: value, to: JSONType.self)
        }
    }
}


func whatAmI(_ json: JSONType) {
    switch json {
    case .array(let array):
        print("Array: \(array)")
    case .dictionary(let dictionary):
        print("Dictionary: \(dictionary)")
    }
}

let first = try JSONType(jsonValue: ["first item", "second item"])
whatAmI(first)
// prints "Array: ["first item", "second item"]"

let second = try JSONType(jsonValue: [ "key" : "value" ])
whatAmI(second)
// prints "Dictionary: ["key": "value"]"
```

I've definitely got some things I want to be able to add if we can get things annotated locally long term, but that's unfortunately part of the codegen stuff which is taking me forever 😭

**Comment by designatednerd** [comment]
@Trupti-nayak @Thecrazyskull did that help?

**Comment by AnthonyMDev** [comment]
I believe the provided solution should work for this. Since we have not gotten any more feedback, I'm closing this issue now.

**Comment by nayooti** [comment]
> OK, gave this a think and representing it as an enum should at least help a bit in terms of being able to stay kiiiinda type safe:
> 
> ```swift
> public typealias Json = JSONType
> public enum JSONType: JSONDecodable {
>     case dictionary([String: Any])
>     case array([Any])
>     
>     public init(jsonValue value: JSONValue) throws {
>         switch value {
>         case let dictionary as [String: Any]:
>             self = .dictionary(dictionary)
>         case let array as [Any]:
>             self = .array(array)
>         default:
>             throw JSONDecodingError.couldNotConvert(value: value, to: JSONType.self)
>         }
>     }
> }
> 
> 
> func whatAmI(_ json: JSONType) {
>     switch json {
>     case .array(let array):
>         print("Array: \(array)")
>     case .dictionary(let dictionary):
>         print("Dictionary: \(dictionary)")
>     }
> }
> 
> let first = try JSONType(jsonValue: ["first item", "second item"])
> whatAmI(first)
> // prints "Array: ["first item", "second item"]"
> 
> let second = try JSONType(jsonValue: [ "key" : "value" ])
> whatAmI(second)
> // prints "Dictionary: ["key": "value"]"
> ```
> 
> I've definitely got some things I want to be able to add if we can get things annotated locally long term, but that's unfortunately part of the codegen stuff which is taking me forever 😭

I had to make JSONType conform to the Apollo.JSONEncodable-Protocol to make the autogenerated API.swift compile.

```
extension JSONType: JSONEncodable {
    public var jsonValue: Apollo.JSONValue {
        switch self {
        case let .dictionary(dict):
            return dict
        case let .array(array):
            return array
        }
    }
}
```
