### ISSUE TITLE
Avoid force casting in the generated Swift code

### ISSUE THREAD

**Issue by vandadnptv4** [apollographql/apollo-ios#154]
Hello,

We use SwiftLint and in our code base we avoid using `as!` that have caused many crashes previously in our application. It's everybody's responsibility to get rid of as many `as!` force casts as possible, we believe.

In the generated API code for Apollo, we see many lines of generated code such as the following:

```swift
public var strategy: String? {
  get {
    return snapshot["strategy"]! as! String?
  }
  set {
    snapshot.updateValue(newValue, forKey: "strategy")
  }
}
```

Please note how the computed property is expecting an optional `String?` but the force casting, and the explicitly unwrapped optional is forcing the data to be of a certain type AND for that data to exist in the dictionary, all the while the return value of this property doesn't expect any of that.

A more elegant code would be as follows:

```swift
public var strategy: String? {
  get {
    return snapshot["strategy"] as? String
  }
  set {
    snapshot.updateValue(newValue, forKey: "strategy")
  }
}
```

Note:

- the removal of force unwrapping of the "strategy" key's value: benefit is to avoid crashes
- the removal of the force casting of the value of the  "strategy" key to String, benefit is cleaner code and avoiding possible crashes

Please could this be fixed to generate a cleaner code that is less-forceful and intrusive and crash prone?

Thank you and have a nice day,
/v

**Comment by martijnwalraven** [comment]
Crashes shouldn't be an issue, because the snapshot is checked at construction time, and missing values will result in an error there. The reason for the force cast was because it might lead to slighter better performance, but to be honest that's unlikely to matter in practice.

This has actually already been changed in the latest alphas, to properly support conditional inclusion (`@skip`/`@include` directives). So if you try Apollo iOS 0.7.0-alpha.5, the generated code should use a conditional cast.

**Comment by vandadnptv4** [comment]
Hi and thank you for your response

> The reason for the force cast was because it might lead to slighter better performance, but to be honest that's unlikely to matter in practice.

I agree with you. Where is this documented that force casting has better performance than optional casting?

> So if you try Apollo iOS 0.7.0-alpha.5, the generated code should use a conditional cast.

Great thank you. I will wait until the prod version is out and use it in our application.

Have a nice day
/v
