### ISSUE TITLE
apollo-tooling codegen: Struct name inconsistently generated

### ISSUE THREAD

**Issue by cltnschlosser** [apollographql/apollo-ios#1548]
Creating issue here for visibility, fix is https://github.com/apollographql/apollo-tooling/pull/2170

**Comment by designatednerd** [comment]
Thanks for the heads up - I'll leave this issue open until that gets merged into tooling and we get a release out with the new tooling version. I'll leave the discussion of the actual problem over in `apollo-tooling`.

**Comment by designatednerd** [comment]
Updated CLI with your changes is shipped as part of 0.38.1! Thanks for your help!
