### ISSUE TITLE
Cannot query field "Access" on type "RootQueryType".

### ISSUE THREAD

**Issue by rs658726** [apollographql/apollo-ios#1550]
Hello,

I'm fairly new to apollo and graphQL and I followed the tutorial but I'm getting an error when compiling:
`Queries.graphql:2: error: Cannot query field "access" on type "RootQueryType".`

My query looks like this in Xcode:
```
query AudioAccess($audioUuid: String) {
    access(audioUuid: $audioUuid) {
        audioToken {
            __typename
            token
            status
        }
        track {
            __typename
        }
    }
}
```

And this is what it looks like on our backend:
```
    QUERY = """
        query {
            access (audioUuid: "%s") {
                audioToken {
                    __typename
                    token
                    status
                }
                track {
                    __typename
                }
            }
        }
    """

```
I'm really not sure what I'm doing wrong. Any help would be appreciated.

**Comment by designatednerd** [comment]
Hi! It'd help to know what tutorial you're working with, as this code doesn't appear to be from anything we've put out for iOS at Apollo. 

It'd also help to see the full schema. I'd want to look and see if your list of queries includes that `access(audioUuid)` bit - if a query isn't defined, you can't just ask for things by their ID.

**Comment by designatednerd** [comment]
I'm going to move this to Discussions since this is more of a question than an issue with the SDK itself
