### ISSUE TITLE
Unable to use v0.38.1 with Swift Package Manager

### ISSUE THREAD

**Issue by ejensen** [apollographql/apollo-ios#1556]
## Bug report

When attempting to use Apollo v0.38.1 as a Swift Package, the package resolution fails due to the newly added unversioned inflectorkit dependency

> because package apollo-ios is required using a version-based requirement and it depends on unversion package inflectorkit and root depends on apollo-ios 0.38.1, version solving failed.

<img width="1540" alt="error" src="https://user-images.githubusercontent.com/915431/101100360-3b798000-357b-11eb-8595-515db610ef10.png">

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.38.1
- Xcode version: 12.2 (12B45b)
- Swift version: 5.3
- Package manager: Swift Package Manager

## Steps to reproduce

Attempt to use Apollo 0.38.1 as a Swift Package dependency
Example: 
```swift
dependencies: [
    .package(
        name: "Apollo",
        url: "https://github.com/apollographql/apollo-ios.git",
        .exact("0.38.1")
    )
]
```

**Comment by joel-perry** [comment]
Was just on my way here to put this in.

**Comment by designatednerd** [comment]
what the....argh. Why on earth didn't I get this warning when I tried this with our SPM project 😡

On it.

**Comment by designatednerd** [comment]
ahhhh i see why I didn't - my SPM test project is pointed at `main` since I want to tag versions _after_ testing them, and because I wasn't using a version there, it didn't matter that `InflectorKit` wasn't using a version. Sneaky!

**Comment by designatednerd** [comment]
OK, pushed out `0.38.2`, this should now be updated.
