### ISSUE TITLE
fyi - https://github.com/Shopify/graphql_swift_gen.git

### ISSUE THREAD

**Issue by johndpope** [apollographql/apollo-ios#157]
this successfully generates entire models from schema

**Comment by martijnwalraven** [comment]
Yep, I know the project. If generating models from the schema and using a query builder instead of `.graphql` files works for you, that definitely seems like a good choice. It's a pretty different approach than Apollo iOS, but I can see the pros and cons of both.

**Comment by johndpope** [comment]
will close this - for my use case - I'm consuming an SDK that's still being built - so it's not entirely fleshed out and there's a duplication around efforts to get models / parsers up and working so I can build out views. 
One spanner in the works is persisted queries / how they fit in the mix with code generation.
presumably - you didn't have to worry about this....

**Comment by martijnwalraven** [comment]
Persisted queries are actually a pretty good match for the type of code generation Apollo iOS does, and we support generating `operationId`s specifically for that use case (Airbnb contributed it and uses it).

If you're relying on a query builder, it's much harder to guarantee static queries and extract stable IDs.
