### ISSUE TITLE
/bin/sh emitted errors but did not return a nonzero exit code to indicate failure

### ISSUE THREAD

**Issue by freedoom1984** [apollographql/apollo-ios#158]
I add this run script on my swift3 project

`APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate '**/*.graphql' --schema schema.json --output API.swift
`
When I build I look this error:
find: /Users/userName/Documents/Swift: No such file or directory
find: Apps/appName/appName: No such file or directory
find: /Users/userName/Documents/Swift: No such file or directory
find: Apps/appName/Carthage/Build/iOS: No such file or directory
++ exec apollo-codegen generate '**/*.graphql' --schema schema.json --output API.swift
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

Thanks

**Comment by martijnwalraven** [comment]
It looks like your `$FRAMEWORK_SEARCH_PATHS` contains non-existing directories, like ` /Users/userName/Documents/Swift` or `Apps/appName/appName`?

Also, `'/*.graphql'` is probably not what you mean, because it would only select `.graphql` files in your root directory.

**Comment by freedoom1984** [comment]
In Framework search paths I have:
$(PROJECT_DIR)/AppName
$(PROJECT_DIR)/Carthage/Build/iOS
$(inherited)

Thanks

**Comment by martijnwalraven** [comment]
I don't think you need to add these to your `$FRAMEWORK_SEARCH_PATHS`, because Xcode can manage framework dependencies for you. These non-existing directories only result in warnings however, so they are not the main cause of the issue you're seeing.

Have you tried removing the `/` from `'/*.graphql'`?

**Comment by freedoom1984** [comment]
I try with
cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate '***.graphql' --schema schema.json --output API.swift

and I look the same error
thanks

**Comment by martijnwalraven** [comment]
I think you mean `'**/*.graphql'`?

**Comment by freedoom1984** [comment]
Yes ;)

**Comment by martijnwalraven** [comment]
So is there any error output when you expand the build output in Xcode (by pressing the icon in the top right)?

<img width="641" alt="screen shot 2017-10-10 at 11 35 22" src="https://user-images.githubusercontent.com/54485/31379648-2ee9b2a8-adaf-11e7-8ce2-e758b7ee4fdb.png">

**Comment by freedoom1984** [comment]
<img width="725" alt="schermata 2017-10-10 alle 11 40 42" src="https://user-images.githubusercontent.com/223940/31379862-de5d5f32-adaf-11e7-8e45-580a71ed3f04.png">

**Comment by martijnwalraven** [comment]
Could you try changing the script invocation to `$(find $APOLLO_FRAMEWORK_PATH -name 'check-and-run-apollo-codegen.sh') generate`?

**Comment by freedoom1984** [comment]
I try with this but I have the same errors

cd "${SRCROOT}/${TARGET_NAME}"
$(find $APOLLO_FRAMEWORK_PATH -name 'check-and-run-apollo-codegen.sh') generate '**/*.graphql' --schema schema.json --output API.swift

**Comment by martijnwalraven** [comment]
Without more error output it's hard to know what could be going on. Do you have Node installed? Have you tried manually installing `apollo-codegen`? What version are you running?

**Comment by freedoom1984** [comment]
I have installed Node and Apollo work correctly on my project but I have the compile errors.
<img width="856" alt="schermata 2017-10-10 alle 12 42 01" src="https://user-images.githubusercontent.com/223940/31382568-6d5edf64-adb8-11e7-812b-c90db03d157a.png">

**Comment by martijnwalraven** [comment]
The errors you're seeing are related to non-existing directories in your `$FRAMEWORK_SEARCH_PATHS`, so you should remove those. I thought there were additional errors coming from the `apollo-codegen` invocation, but maybe the `emitting errors` message just refers to the `Find` errors.

Does `API.swift` get generated even with these errors?

**Comment by freedoom1984** [comment]
Yes the file Api.swift is correctly generated

**Comment by designatednerd** [comment]
@freedoom1984 Can you please try the updated build script in 0.11.0? There's definitely still going to be some issues that aren't fully logged out due to them being in our TypeScript code gen, but it could help with some of the issues here.

**Comment by designatednerd** [comment]
Since we haven't heard back in a couple weeks, I'm going to close this out. Please open a new issue if you're still running into problems. Thank you!
