### ISSUE TITLE
init Input with json/dictionary

### ISSUE THREAD

**Issue by MaximusMcCann** [apollographql/apollo-ios#160]
Would like to be able to initialize an `input` object with a `Dictionary<String, Any?>`

perhaps:
```
init?(_ dict: [String: Any?]) {
// do magic, handle nesting
}
```

We have a very large `input` object that has multiple nested levels.  We have all these values returned as JSON (Dictionary; has to be this way). Any way to init an `input` struct this way?

Cheers!

**Comment by MaximusMcCann** [comment]
or somehow to set `GraphQLMap` with a json object

**Comment by martijnwalraven** [comment]
Hmmm, I can definitely see the use case, but it's not trivial to do in a safe way. We'd need to check the contents of the dictionary to make sure it contains the expected fields, and if they have the right types. If we set `GraphQLMap` directly, we'd open ourselves up to crashes on the client and errors on the server.

**Comment by MaximusMcCann** [comment]
Certainly understand, my spaghetti string right now just looks gross, ha

**Comment by designatednerd** [comment]
We're not planning on supporting this at this time, so I'll close this out. We may revisit when we start looking at some architecture stuff later on, but for now, this is not on our priority list.
