### ISSUE TITLE
Ability to clear Apollo Cache

### ISSUE THREAD

**Issue by aryan-ghassemi-ck** [apollographql/apollo-ios#161]
It would be great to add the ability to clear the cache on Apollo client

**Comment by ethansinjin** [comment]
This would be great. Currently, in an app setting, if a user logs out, it's sometimes important that sensitive information is cleared from the cache.

**Comment by aryan-ghassemi-ck** [comment]
The workaround for now is to re-instantiate the client; the default cache is just a dictionary on ApolloStore

**Comment by ethansinjin** [comment]
This will work if an SQL cache is not being used, but if cached requests are being saved to disk, more work is required.

Thanks for the comment though!

**Comment by aryan-ghassemi-ck** [comment]
correct, that's what I meant by `the default cache` :)

**Comment by ethansinjin** [comment]
Now that #204 has been merged, can this be closed? @aryan-ghassemi-ck
