### ISSUE TITLE
Can't make any request

### ISSUE THREAD

**Issue by MarcoCarnevali** [apollographql/apollo-ios#1616]
## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.39.0
- Xcode version: 12.3
- Package manager: SPM

## Steps to reproduce
Attempting to create a new request after the session has been invalidated!
1. Follow Apollo start guide: 
```
class GraphQL {
    
    private let url: URL(string: "<my_url>")!
    
    var client: ApolloClient
    
    init(authToken token: String) {
        self.client = ApolloClient(url: url)
    }
    
    public func callAPI() {
        let query = GetStats()
        client.fetch(query: query) { result in
            switch result {
            case .success(let result):
                print("JSON: ", result.data.jsonValue)
            case .failure(let error):
                print("ERROR: ",error.localizedDescription)
            }
        }
    }
}
```
2. run the `callAPI` function
3. You will see an error on the console:
`ERROR:  Attempting to create a new request after the session has been invalidated!`

**Comment by designatednerd** [comment]
You'll need to hang on to the `GraphQL` class somewhere, or it'll get hammered by ARC and the underlying session will be invalidated when it `deinit`s. 

This is why in the tutorial it's set up as a singleton, but as long as you've got somewhere you're hanging on to it, you should be good to go.

**Comment by MarcoCarnevali** [comment]
@designatednerd I'll try that and let you know... thank you !

**Comment by designatednerd** [comment]
@MarcoCarnevali Any progress here?

**Comment by designatednerd** [comment]
Since I haven't heard back in a week and it very much seems like an ARC issue, I'm going to close this issue out. @MarcoCarnevali feel free to reopen with more detail if you're still having trouble; anyone else experiencing a similar problem that's not able to resolve it by checking that `ApolloClient` is actually being retained somewhere, please open a new issue.

**Comment by amitk-virtueinfo** [comment]
Can you check, your ApolloClient object, it should be create once, so it should be declared somewhere globally like in AppDelegate

import Apollo

let apollo = ApolloClient(url: URL(string: "https://vi-module.herokuapp.com/v1/graphql")!)

@main
class AppDelegate: UIResponder, UIApplicationDelegate {
