### ISSUE TITLE
graphql-ws Protocol Support

### ISSUE THREAD

**Issue by casey-chow** [apollographql/apollo-ios#1622]
## Feature request

Enable support for the [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) protocol so servers can leverage the security and maintenance improvements.

## Motivation

subscriptions-transport-ws has fallen into disrepair in recent years, and its successor, graphql-ws, introduces a completely new [protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) which would need to be implemented for compatibility. I've been seeing a lot of issues with the server library and would like not to fork subscriptions-transport-ws 😅

**Comment by designatednerd** [comment]
Can you help me understand what changes to our existing websocket library would be necessary for this? I know we're working on trying to figure some things out with WebSockets, but I think if there's a way to make this doable without having to build a completely parallel architecture we should at least consider it.

If it _does_ require a completely parallel architecture that's a bit of a different question, though.

**Comment by casey-chow** [comment]
Here's a quick'n'dirty mapping of the two protocols based on their protocol documents:

| Direction        | subscriptions-transport-ws                                                                                                                                                                                                                                          | graphql-ws                                                                                          |
|------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| client -> server | [`GQL_CONNECTION_INIT`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_init)                                                                                                                                    | [`connection_init`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#connectioninit) |
| server -> client | [`GQL_CONNECTION_ACK`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#connectionack)                                                                                                                                                               | [`connection_ack`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#connectionack)   |
| server -> client | [`GQL_CONNECTION_ERROR`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_error)                                                                                                                                  | Closes the socket.                                                                                  |
| client -> server | [`GQL_START`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_start)                                                                                                                                                        | [`subscribe`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#subscribe)            |
| server -> client | [`GQL_DATA`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_data)                                                                                                                                                          | [`next`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#next)                      |
| server -> client | [`GQL_ERROR`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_error)                                                                                                                                                        | [`error`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#error)                    |
| bidirectional    | [`GQL_COMPLETE`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_complete) (server -> client) [`GQL_STOP`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_stop) (client -> server) | [`complete`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#complete)              |
| server -> client | [`GQL_CONNECTION_KEEP_ALIVE`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_keep_alive)                                                                                                                        | Native websocket ping/pong.                                                                         |

I think a lot of the differences are in the nuances--graphql-ws tries to be more robust in its protocol design so there are definitely details not included here, but for the most part the protocols are fairly similar.

**Comment by designatednerd** [comment]
OK. The next step would probably be finding a `GraphQL-ws` server we can write tests against, since our sample server is using Apollo Server and therefore `subscriptions-transport-ws`. Do you have any thoughts on how that would work to set up?

**Comment by casey-chow** [comment]
If you point me towards the existing server I'd be more than happy to put together the `graphql-ws` version in a fork!

**Comment by designatednerd** [comment]
Here ya go: https://github.com/apollographql/starwars-server

**Comment by danabrooks** [comment]
Has there been any progress on this? I am very interested in graphql-ws support for Apollo on iOS.

**Comment by designatednerd** [comment]
I'm dealing with other stuff at the moment - @casey-chow Were you ever able to get a look at this?

**Comment by designatednerd** [comment]
Hi @dchappelle, I'd recommend [checking out the Android repo's issues](https://github.com/apollographql/apollo-android/issues) and opening an issue if you can't find one - this is the iOS repo 😇.

**Comment by VladMelnik** [comment]
Has there been any progress on graphql-ws support for Apollo on iOS?

**Comment by phanikavi** [comment]
Any updates on this feature? 

It works for me with these basic changes.  [graphql-ws-patch.txt](https://github.com/apollographql/apollo-ios/files/6912014/graphql-ws-patch.txt)

Apollo Android seems to have already implemented it in v3.0.0-alpha01 release.

**Comment by calvincestari** [comment]
Hi 👋🏻
* graphql-ws support is not something we're directly working on for the [1.0 release](https://github.com/apollographql/apollo-ios/blob/main/ROADMAP.md)
* we are always happy to review community contributions though so if you've got a working solution please consider submitting a PR and the team will review it

**Comment by phanikavi** [comment]
Hi @calvincestari ,  We have been using the changes in the [patch](https://github.com/apollographql/apollo-ios/files/6912014/graphql-ws-patch.txt)   that I mentioned [earlier](https://github.com/apollographql/apollo-ios/issues/1622#issuecomment-890426819) to support graphql-ws and it is working fine. Please let me know if you need any help in verifying your changes.

**Comment by calvincestari** [comment]
> I see that this feature is now scheduled for 0.51.0 milestone. Please let me know if you need any help in verifying your changes.

That's correct @phanikavi. We're storming towards an imminent 1.0 alpha release so the graphql-ws work is slightly delayed. I think the patch will be a great starting point though. We'll get to it next week, thanks for the offer to verify changes.

**Comment by phanikavi** [comment]
awesome, @calvincestari these changes work fine in our environment.

**Comment by CureleaAndrei** [comment]
I think that the `GQL_STOP` is not mapped to `complete`  

CONTEXT:
I've been implementing in our app the new `graphql_transport_ws` but encountered the following error when terminating a subscription:
` "websocket is disconnected: WSError(type: Apollo.WebSocket.WSError.ErrorType.protocolError, message: \"Invalid message received\", code: 4400)"`

After digging in I saw that the server get's a message of `type: stop` but in the `graphql_ws` protocol it should be `complete`. I think that the issue lies inside WebSocketTransport `unsubscribe` method which always sends an `OperationMessage` of type `stop`. Shouldn't it check the protocol and send it with type `stop` or `complete` depending on the protocol used ?

**Comment by calvincestari** [comment]
I'll dig into this this week @CureleaAndrei.

**Comment by CureleaAndrei** [comment]
Thanks!

**Comment by calvincestari** [comment]
@CureleaAndrei, sorry this took a bit longer than I had planned. PR #2320 is up which should fix the behaviour. Please give it a test if you've got the time - thanks.
