### ISSUE TITLE
Make operationName a Type property

### ISSUE THREAD

**Issue by scfonowy** [apollographql/apollo-ios#1645]
## Feature request

We would like to be able to access the `operationName` of a GraphQL operation given just the type of the operation. We're happy to spend time creating a PR for this, but want to make sure it makes sense as a feature request. 😄 

## Motivation

- Our understanding is that `operationName` will be the same across all instances of a `GraphQLOperation`, so we think it would be a good candidate for a type property.
- We currently (indirectly) use the `operationName` to map e.g. some metadata to GraphQL operations to be sent with requests, or map mock responses to GraphQL operations. Right now we just hardcode the operation names in these places (e.g. `operationName: "MyQuery"`), but this is brittle:
  - If `MyQuery`'s operation name changes, but the type name does not change, and we neglect to update the string for these mappings, we will fail at runtime. With this change, we can reference `MyQuery.operationName` instead of hardcoding the string, so it will stay up to date.
  - If `MyQuery`'s operation _and_ type name changes, we still fail at runtime. With this change, our reference to `MyQuery.operationName` will fail the build (since `MyQuery` will no longer be a valid type), which is preferable to failing at runtime.

## Outstanding Questions

- Are there cases where `operationName` is different between instances of the same `GraphQLOperation`?

**Comment by designatednerd** [comment]
🤔 I believe the operation name is always generated as a raw string without any kind of interpolation, so I don't think there's any real reason for this not to work. 

Fair warning that to make this work at the moment you'd need to dive into [the typescript codegen](https://github.com/apollographql/apollo-tooling/tree/master/packages/apollo-codegen-swift) which is...in the process of being replaced. If you're down to do that we'd be more than happy to look at the results!

**Comment by AnthonyMDev** [comment]
I'm adding this to be completed on the new version of Codegen we are working on!

**Comment by AnthonyMDev** [comment]
Hi :wave::skin-tone-2: - this issue should be resolved in 1.0. 1.0 is currently in alpha releases with a full 1.0 release in H2 2022. Please take a look at the [latest alpha](https://github.com/apollographql/apollo-ios/releases) and let us know if this is still an issue for you.

This was completed and will be in the next alpha release (1.0 Alpha 6). We try to release alpha versions pretty frequently, so it shouldn't be long! You can always update to use the `release/1.0` branch which has the latest development changes to the Alpha in the mean time!
