### ISSUE TITLE
How does this caching works with subscription and mutation?

### ISSUE THREAD

**Issue by pavm035** [apollographql/apollo-ios#1647]
## Question

Hi i'm new to this graphql and apollo client SDK, 
Platform: iOS

I'm trying to use SQLite caching to store the server data in my disk so when user launch the app again we need to show the cached data immediately followed by api calls through subscriptions, but i'm not sure how to fetch cached data for subscriptions i went through apollo documentation but i didn't see anything specific to subscriptions and also i have few questions too

1. When we subscribe for subscription will it automatically fetch from Cache followed by API call or is there any way to control?
2. When we delete item in server subscription handler is calling but it seems recored not being updated in local DB, is there any way to automate this? (i think deleted record not coming from sever hence it's leave that record in DB)
3. In general our requirement is to show cached data first followed by API call in background?

Right now without cache app is working fine like subscription handles being called automatically when there is any change or update in graphql server, also i'm not sure is it good idea to have local DB(sqlite as mentioned above) along with one in server anyways which we get data through subscriptions and also maintenance cost for local DB, please share your idea or suggestion on this

**Comment by designatednerd** [comment]
Converting to discussion since this is a question!
