### ISSUE TITLE
Problem with input objects which contain property with name 'private'

### ISSUE THREAD

**Issue by IvanovDeveloper** [apollographql/apollo-ios#166]
I have mutation

`
mutation createWheelChatMessage($input: createWheelChatMessageInput!) {
    createWheelChatMessage(input: $input) {
        message {
            ...WeelChatMessageObject
        }
    }
}
`

input  **'createWheelChatMessageInput'** have property **'private'**

![screen shot 2017-10-18 at 2 45 38 pm](https://user-images.githubusercontent.com/14201895/31717045-10de87f6-b413-11e7-9edc-a7987cbe0478.png)

When I generate code, at API file, I see errors

![screen shot 2017-10-18 at 2 42 56 pm](https://user-images.githubusercontent.com/14201895/31717094-416affbc-b413-11e7-9e46-dd366571be9f.png)

Xcode can't open API file, this causes the program to hang

As far as I understand, when the generation of an object occurs, then the name is called the original name 'private', and 'privat' it is reserved word for swift.

**How I can set alias for input object?**

**Comment by IvanovDeveloper** [comment]
![screen shot 2017-10-18 at 2 56 54 pm](https://user-images.githubusercontent.com/14201895/31717494-cc0add08-b414-11e7-8593-ba32759939d6.png)

**Comment by IvanovDeveloper** [comment]
Could you help me please?! I still have this issue.

**Comment by martijnwalraven** [comment]
@IvanovDeveloper: This should be fixed in `apollo-codegen` 0.17.1. Can you update (`npm install -g apollo-codegen`) and try again?

**Comment by IvanovDeveloper** [comment]
Ok, thanks. I will try

**Comment by IvanovDeveloper** [comment]
I checked the new version, and it is working for me now
