### ISSUE TITLE
Naming Convention in Fragment

### ISSUE THREAD

**Issue by mustafaysil** [apollographql/apollo-ios#1671]
## Question
Is it possible manually customising coding keys or naming convention fragment in variable name ? 

I want to customize fragment in variable name. There are many different naming convention our backend team but I just want to use one naming convention.

For example: 

```
fragment UserDetail on User {
   _lastName
    gender
}
```
as you can see in the example **_lastName** has an prefix an underscore. How can i change it to **lastName** ? I want to call with this name.

i mentioned it before Coding keys, i share for it be an example 
```

struct User : Codable {
    var lastName: String
    var gender: Int

    private enum CodingKeys : String, CodingKey {
        case gender, lastName = "_lastName"
    }
}
```

We were use to Apollo 0.10.0 version, we migrated to 0.40.0 version. This situation occurred after the update, in fact the old version was automatically generated I wanted.

All the best!

**Comment by designatednerd** [comment]
Migrating to a discussion since this is a question rather than an issue
