### ISSUE TITLE
Requests Time Out on iOS 11 and 12

### ISSUE THREAD

**Issue by bartjacobs** [apollographql/apollo-ios#1672]
## Bug report

We are in the middle of updating Apollo from version **0.19.1** to version **0.39.0**. Since the minimum deployment target of the project is set to **iOS 11**, we are not able to upgrade to version **0.40.0** or later.

We are experiencing timeouts (error code **-1001**) on **iOS 11 and 12**, not on **iOS 13 and 14**. Requests complete successfully on iOS 11 and 12 up until the client passes an authorization header with each request. It happens that a few authorized requests succeed, but soon after signing in requests consistently time out on iOS 11 and 12. The Apollo client isn't able to recover once it enters this state.

Charles Proxy confirms that the client receives a response from the server despite the requests timing out. I tested this in multiple environment (development and production).

### Questions

- Could this be related to certificate pinning? We currently use `URLSessionClient` as is (no subclass).
- Is this or has this been an issue? I wasn't able to find an issue that reports a similar problem.

## Versions

- `apollo-ios` SDK version: 0.39.0
- Xcode version: 12.3
- Swift version: 5.3.2
- Package manager: N/A

## Steps to reproduce

I'm not able to share the project to reproduce the problem, but these are the steps we use to consistently reproduce the problem.

- run the application
- verify that data is fetched successfully and displayed to the user
- sign in
- perform some actions that cause data to be fetched

Soon after signing in, requests consistently time out on iOS 11 and 12.

## Further details

This snippet shows how the Apollo client is initialized.

```language-swift
let store = ApolloStore(cache: InMemoryNormalizedCache())
let interceptorProvider = NetworkInterceptorProvider(store: store, client: URLSessionClient())
let networkTransport = RequestChainNetworkTransport(interceptorProvider: interceptorProvider, endpointURL: endpointURL)
let apolloClient = ApolloClient(networkTransport: networkTransport, store: store)
```

This is the implementation of `NetworkInterceptorProvider`.

```swift
import Apollo

internal struct NetworkInterceptorProvider: InterceptorProvider {

    // MARK: - Properties
    
    private let store: ApolloStore
    private let client: URLSessionClient
    
    // MARK: -
    
    private let bundle: Bundle
    private let device: UIDevice
    
    // MARK: - Initialization

    init(store: ApolloStore, client: URLSessionClient, bundle: Bundle = .main, device: UIDevice = .current) {
        self.store = store
        self.client = client
        self.bundle = bundle
        self.device = device
    }
    
    // MARK: - Interceptor Provider
    
    func interceptors<Operation: GraphQLOperation>(for operation: Operation) -> [ApolloInterceptor] {
        [
            MaxRetryInterceptor(),
            LegacyCacheReadInterceptor(store: store),
            HeadersInterceptor(bundle: bundle, device: device),
            NetworkFetchInterceptor(client: client),
            ResponseCodeInterceptor(),
            LegacyParsingInterceptor(cacheKeyForObject: store.cacheKeyForObject),
            AutomaticPersistedQueryInterceptor(),
            LegacyCacheWriteInterceptor(store: store)
        ]
    }

}
```

The `HeadersInterceptor` class adds the required headers to each request, including the authorization header if the user is signed in.

```swift
import Apollo
import KeychainAccess

internal final class HeadersInterceptor: ApolloInterceptor {
    
    // MARK: - Initialization

    private let bundle: Bundle
    private let device: UIDevice
    
    // MARK: - Initialization
    
    init(bundle: Bundle, device: UIDevice) {
        self.bundle = bundle
        self.device = device
    }
    
    // MARK: - Apollo Interceptor
    
    func interceptAsync<Operation: GraphQLOperation>(chain: RequestChain,
                                                     request: HTTPRequest<Operation>,
                                                     response: HTTPResponse<Operation>?,
                                                     completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void) {
        // Add Headers to Request
        
        chain.proceedAsync(request: request,
                           response: response,
                           completion: completion)
    }

}
```

**Comment by designatednerd** [comment]
For what it's worth every device that can run iOS 11 can also run iOS 12 - this is why we dropped 11 support (and also why Apple annoys you every time there's an Xcode update to make your min SDK 12).

So yes, this behavior is quite weird, I haven't heard of anything remotely similar. There's not any cert pinning by default in `URLSessionClient` so I don't think that's going to be the issue. I'm not seeing anything in the code you've shared that would explain this issue. 

Is this something happening on device only, sim only, or both sim and device?

**Comment by bartjacobs** [comment]
Thanks for your response. I appreciate it.

> Is this something happening on device only, sim only, or both sim and device?

The issue occurs on device and simulator.

**Comment by designatednerd** [comment]
Very, very odd. You said that you can see the response coming back via Charles proxy - is there anything weird happening with the response in terms of it being marked as a multipart response or something? 

Probably also worth throwing some breakpoints into `didReceive response` and `didReceive data` to see if maybe there's something where you're getting a response or data but there isn't something that matches the task identifier. Again, wish I could be more help but there's definitely something v weird going on here.

**Comment by spookyd** [comment]
> For what it's worth every device that can run iOS 11 can also run iOS 12 - this is why we dropped 11 support 

@designatednerd by this are you suggesting anyone that wants to use Apollo should also raise their minimum support to iOS 12? Or, are you referring to something else like a build setting?

**Comment by designatednerd** [comment]
Basically the assumption was if you had an existing project, you could go up to 12 without much issue since you would theoretically not have to leave any customers behind, and if you were starting a new project, 12 could be a pretty easy baseline.

[I talked a little more about it in this discussion, including the stats that led to that decision](https://github.com/apollographql/apollo-ios/discussions/1680).

**Comment by spookyd** [comment]
Makes sense. Thanks for clarifying 👍

**Comment by bartjacobs** [comment]
@designatednerd I've made some progress on this issue. There is one query that consistently times out and that causes any other queries to fail. Disabling the query resolves the issue on iOS 11 and 12.

Because the endpoint requires authorization, it seemed as if the issue was related to the presence/absence of an authorization header. This isn't true based on my findings.

It is unclear why the query fails, but I think it is due to the size of the response. The response is the largest of the queries the client performs.

The logs indicate that `urlSession(_:didReceive:completionHandler:)` is executed once, which is expected, and `urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)` is executed for every request. No other `URLSessionDelegate`, `URLSessionTaskDelegate`, or `URLSessionDataDelegate` methods are called.

Everything works as expected using Apollo **v0.19.1**, which doesn't use the `URLSession` delegate APIs if I remember correctly.

**Comment by designatednerd** [comment]
> Apollo v0.19.1, which doesn't use the URLSession delegate APIs if I remember correctly.

That is correct, we were using the closure-based API for that but we switched to the delegate APIs to enable people to use things in the background. 

How big is the response you're getting?

**Comment by bartjacobs** [comment]
It's just under 100KB.

**Comment by designatednerd** [comment]
Hm, that's not _that_ big - we've definitely seen things choke with multiple megabytes of info but 100k should be easier to handle.

> The logs indicate that urlSession(_:didReceive:completionHandler:) is executed once, which is expected, and urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:) is executed for every request. No other URLSessionDelegate, URLSessionTaskDelegate, or URLSessionDataDelegate methods are called.

That's *really* interesting - `didReceive data` isn't called at all? That would certainly explain the reason the request isn't completing. The `didSendBodyData` method should theoretically be called as the request is sent out, not as the response is received. When is that getting called?

**Comment by bartjacobs** [comment]
> The didSendBodyData method should theoretically be called as the request is sent out, not as the response is received. When is that getting called?

Correct. It is called when the body is sent out, but it isn't followed by a delegate method that indicates the `URLSessionClient` instance received data.

**Comment by designatednerd** [comment]
It's weird as hell that you're seeing the response come through to Charles but `didReceive data` is never called. Unfortunately, I think this does indicate a problem more at an iOS level than an Apollo level. 

Something you can try as a workaround is to replace the `NetworkFetchInterceptor` with a custom one that just uses `URLSession`'s closure API directly rather than `URLSessionClient`, which uses the delegate API, since it sounds like that worked for you in the past.

Would be curious to hear what you wind up doing and what works!

**Comment by bartjacobs** [comment]
> Something you can try as a workaround is to replace the NetworkFetchInterceptor with a custom one that just uses URLSession's closure API directly rather than URLSessionClient, which uses the delegate API, since it sounds like that worked for you in the past.

Surprise or no surprise, but that works! This is an option I can further explore and test. Thanks for your help.

```swift
internal final class DataTaskInterceptor: ApolloInterceptor, Cancellable {

    // MARK: - Properties
    
    private let session: URLSession
    
    // MARK: -
    
    private var currentTask: Atomic<URLSessionTask?> = Atomic(nil)
    
    // MARK: - Initialization

    init(session: URLSession) {
        self.session = session
    }
    
    // MARK: - Apollo Interceptor
    
    func interceptAsync<Operation: GraphQLOperation>(chain: RequestChain,
                                                     request: HTTPRequest<Operation>,
                                                     response: HTTPResponse<Operation>?,
                                                     completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void) {
        let urlRequest: URLRequest
        
        do {
            urlRequest = try request.toURLRequest()
        } catch {
            chain.handleErrorAsync(error,
                                   request: request,
                                   response: response,
                                   completion: completion)
            
            return
        }
        
        let task = session.dataTask(with: urlRequest) { [weak self] data, urlResponse, error in
            defer {
                self?.currentTask.mutate { $0 = nil }
            }
            
            guard chain.isNotCancelled else {
                return
            }
            
            if let data = data, let httpURLResponse = urlResponse as? HTTPURLResponse {
                let response = HTTPResponse<Operation>(response: httpURLResponse,
                                                       rawData: data,
                                                       parsedResponse: nil)
                
                chain.proceedAsync(request: request,
                                   response: response,
                                   completion: completion)
            } else if let error = error {
                chain.handleErrorAsync(error,
                                       request: request,
                                       response: response,
                                       completion: completion)
            }
        }
        
        task.resume()
        
        currentTask.mutate { $0 = task }
    }
    
    // MARK: - Cancellable
    
    func cancel() {
        currentTask.value?.cancel()
        currentTask.mutate { $0 = nil }
    }

}
```

**Comment by designatednerd** [comment]
Glad the workaround worked! Mind if we close this out?

**Comment by bartjacobs** [comment]
Yes. Thanks!
