### ISSUE TITLE
Generate GraphQL API build phase fails on Bitrise

### ISSUE THREAD

**Issue by alexisbronchart** [apollographql/apollo-ios#1684]
## Bug report

The "Generate GraphQL API" build phase works fine when building locally but fails on Bitrise.

Generation script:
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="../../schema.json" GraphQL/API
```

Error in bitrise logs:
```
The following build commands failed:
	PhaseScriptExecution Generate\ GraphQL\ API /Users/vagrant/Library/Developer/Xcode/DerivedData/EliumMobile-aappjanzzrvmovbictmdiertaibi/Build/Intermediates.noindex/ArchiveIntermediates/Elium.release/IntermediateBuildFilesPath/EliumMobile.build/Release-iphoneos/ShareExtension.build/Script-0C1D177B259B235800BB67E1.sh
(1 failure)
[10:06:55]: Exit status: 65
```

I still haven't figured out how to get the actual console output of the script. I guess it would be more helpful. Any suggestion?

Also, apollo 0.41.0, Xcode 12.4, using the gql generation build phase only in a share extension target (swift), the main app target doesn't have it (and shouldn't need it since it doesn't use apollo).

## Versions

- `apollo-ios` SDK version: 0.41.0
- Xcode version: 12.4
- Swift version: 5.3
- Package manager: cocoapods

**Comment by designatednerd** [comment]
The logs would be very helpful, for sure - obviously not having anything other than exit status 65 isn't super helpful since that could basically mean any failure in the script. 

Are you able to build locally with the same commands as you're running on bitrise? Meaning, if you're using fastlane, it builds correctly locally, if you're using some kind of script, that script works.

**Comment by alexisbronchart** [comment]
I finally managed to get the output of the script. Trivial cause 🙄, totally unrelated to apollo. Closing this.

**Comment by designatednerd** [comment]
Out of curiosity and for the future reference of people who come across this, what was the underlying cause?
