### ISSUE TITLE
Code generation not compilable (alpha 11)

### ISSUE THREAD

**Issue by MaximusMcCann** [apollographql/apollo-ios#169]
The following, post code generation, does not compile.  It's a return one-or-the-other scenario, in this case for news.
```
query News($securityId: ID!, $isMarkets: Boolean!, $after: String, $first: Int) {
  Security: node(id: $securityId) @skip(if: $isMarkets) {
    ... on Security {
      id
      type
      news(after: $after, first: $first) {
        ...ApolloNewsConnection
      }
    }
  }
  Markets: viewer @include(if: $isMarkets) {
    markets {
      news(after: $after, first: $first) {
        ...ApolloNewsConnection
      }
    }
  }
}
```

Compilation error, optional not unwrapped:
```
    public init(security: Security? = nil, markets: Market? = nil) {
      self.init(snapshot: ["__typename": "Query", "Security": security.flatMap { $0.snapshot }, "Markets": markets.snapshot])
    }
```
![image](https://user-images.githubusercontent.com/1643285/31967845-bd95a1d0-b8d4-11e7-83a1-2f68dc9c7e41.png)

**Comment by designatednerd** [comment]
@MaximusMcCann Any idea what version this was? I'd love to add that for future reference. 

Am I correct in assuming this has been fixed or is this still an issue?

**Comment by designatednerd** [comment]
Since I haven't heard back from anyone on this issue in two weeks, I'm going to close it out as stale. Please open a new issue if this is still a problem. Thank you!
