### ISSUE TITLE
Downloading schema from Apollo Studio without introspection is not supported for Swift Scripting setup

### ISSUE THREAD

**Issue by kimroen** [apollographql/apollo-ios#1690]
## Bug report

It is currently not possible to download a schema from Apollo Studio using the Swift Scripting package solution. You can pass in an api key, but there is no way to specify a variant, and the `endpointURL` argument is required.

## Versions

- `apollo-ios` SDK version: 0.41
- Xcode version: N/A
- Swift version: N/A
- Package manager: N/A

_Originally posted by @kimroen in https://github.com/apollographql/apollo-ios/discussions/1689_

**Comment by designatednerd** [comment]
Yep, this is my bad - there's also no way to supply a graph ID.

**Comment by kimroen** [comment]
> Yep, this is my bad - there's also no way to supply a graph ID.

That's fair! It's in the token, so I just assumed it would figure it out I suppose.

**Comment by designatednerd** [comment]
This will go out later this week with our next release but you can pull from `main` if you need it right away

**Comment by kimroen** [comment]
It works 🎉
