### ISSUE TITLE
Dynamic types are auto generated as `Any` when --passthroughCustomScalar is used

### ISSUE THREAD

**Issue by chrisvoronin** [apollographql/apollo-ios#1694]
## Bug report

Some of our models have custom data, meaning it can be a string or int or dictionary, etc...  And by default code gen turns everything into a string.  So it's impossible to perform mutations or queries on it when that field is not a string.  So we tried doing --passThroughCustomScalars.  However that seems to generate code with a non existent data type of `Any` <-- including the non standard apostrophes and we are not sure how to handle this because we can't run a mutation on it.

Even if we create an extesion
public typealias `Any` = String
When we need this in a mutation, mutation will still only take a string, not a dictionary or integer that we sometimes need.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.39.0
- Xcode version: Version 12.4 (12D4e)
- Swift version: latest
- Package manager: n/a

## Steps to reproduce

1) Run code gen with --passthroughCustomScalars flag on a model where some data is dynamic, aka can be a string, or int, or dictionary or array

SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" --passthroughCustomScalars API.swift 

Auto generated code contains invented type of `Any`  making mutations and queries not even compile.

Please replace this line with steps to reproduce the problem.

## Further details

Please replace this line with any further details or context necessary to understand the problem. Delete this section if you don't have anything further to add.

**Comment by designatednerd** [comment]
What should happen is that the name of the custom scalar is passed through - so if the scalar is called `SomeType` in your schema, then that should be the name of the type, and then you can create a typealias for it. What is the name of the type in your schema?

**Comment by chrisvoronin** [comment]
> What should happen is that the name of the custom scalar is passed through - so if the scalar is called `SomeType` in your schema, then that should be the name of the type, and then you can create a typealias for it. What is the name of the type in your schema?

here is one of the parts of schema that translates into `Any`, should this be defined as something else in schema?  Sometimes they are always going to be dictionaries, in other cases they'll be dynamic like literally anything from int to array to dictionary.

{
                "name": "location",
                "description": "",
                "type": {
                  "kind": "SCALAR",
                  "name": "Any",
                  "ofType": null
                },
                "defaultValue": null,
                "isDeprecated": false,
                "deprecationReason": null
              }


So far the work around I found, which feels like a gigantic hack is creating a class called CustomScalar:

public typealias `Any` = CustomScalar

public struct CustomScalar: JSONDecodable, JSONEncodable {
    
    var value:Any?
    
    public init(val:Any?) {
        self.value = val
    }
    
    public init(jsonValue value: JSONValue) throws {
        self.value = value
        switch value {
        case let string as String:
            self.value = string
        case let int as Int:
            self.value = String(int)
        case let int as Int64:
            self.value = String(int)
        case let date as Date:
            self.value = String(date.millisecondsSince1970)
        case let dictionary as [String: Any]:
            guard let data = try? JSONSerialization.data(withJSONObject: dictionary, options: []) else { fallthrough }
            guard let serializedJson = String(data: data, encoding: .utf8) else { fallthrough }
            self.value = serializedJson
        default:
            throw JSONDecodingError.couldNotConvert(value: value, to: String.self)
        }
    }
        
    public var jsonValue: JSONValue {
        switch self.value {
        case let date as Date:
            return date.millisecondsSince1970
        case let string as String:
            return string
        case let int as Int64:
            return int
        case let int as Int:
            return int
        case let dictionary as [String:Any]:
            return dictionary
        default:
            return NSNull()
        }
    }
}

public typealias Map = Dictionary<String, Any>

**Comment by designatednerd** [comment]
Yeah if the `name` property of the scalar is `Any`, so the code being generated is correct. 

Your workaround is also basically correct. Not sure what the `Map` typealias is for but this is essentially, with different naming, what I was going to suggest.

**Comment by chrisvoronin** [comment]
> Yeah if the `name` property of the scalar is `Any`, so the code being generated is correct. Honestly I think if there's any way to change the name, that'd probably confuse the compiler quite a bit less.
> 
> Your workaround is also basically correct. Not sure what the `Map` typealias is for but this is essentially, with different naming, what I was going to suggest.

thanks.  Map type alias is because some things in the schema are named as "Map" and compiler generates it that way, but it's dictionary basically.  I just needed to add a typealias to make it work.  I'll pass the naming feedback to the server team, they are in charge of schema, maybe they can update some names.  Thanks for all the help guys!
