### ISSUE TITLE
Uploading single file as array cause Error 422

### ISSUE THREAD

**Issue by CheShengSu** [apollographql/apollo-ios#1707]
## Bug report
Uploading single file as array cause Error:

 

```
invalidResponseCode(response: Optional(<NSHTTPURLResponse: 0x2831a7940> { URL: http://api.myurl/query } { Status Code: 422, Headers {
    Connection =     (
        "keep-alive"
    );
    "Content-Length" =     (
        425
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Thu, 11 Mar 2021 05:13:40 GMT"
    );
} }), rawData: Optional(425 bytes))
```
with localizedDescription:

```
Received a 422 error. Data returned as a String was: {
  "errors":[{
    "message":"must be an array",
    "path":["variable","files"],
    "extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}
  }],
  "data":null,
  "extensions": {"tracing": {
    "version":1,
    "startTime":"2021-03-11T05:13:40.766313717Z",
    "endTime":"2021-03-11T05:13:40.766443628Z",
    "duration":129934,
    "parsing":{"startOffset":57159,"duration":10839},
    "validation":{"startOffset":69228,"duration":-9223372036854775808},
    "execution":  {"resolvers":null}
  }}
}
```
## Versions
- `apollo-ios` SDK version: 0.42.0
- Xcode version: 12.4
- Swift version: 5.3.2
- Package manager: pod 1.9.3

## Steps to reproduce
The `upload.graphql` file:
```
mutation TestUpload($files: [Upload!]!) {
    multiUpload1(files: $files) {
        name
    }
}
```
The server API:
```
multiUpload1(
  files: [Upload!]
): [UploadFile!]!

type UploadFile {
  name: String!
}
```
The swift code:
```
static private func upload0<M: GraphQLMutation>(mutation: M, files: [GraphQLFile], err: @escaping () -> Void, handler: @escaping (M.Data) -> Void) {
    apollo.upload(operation: mutation, files: files) {result in
        switch result {
        case .success(let r):
            if let errs = r.errors {
                err()
            } else if let data = r.data {handler(data)}
        case .failure(let err):
            print("upload Err \(err)\r\n", err.localizedDescription)
        }
    }
}
func testUpload() {
    let url = Bundle.main.url(forAuxiliaryExecutable: "a.txt")!
    let file = try! GraphQLFile(fieldName: "files", originalName: "aa", fileURL: url)
    upload0(mutation: TestUploadMutation(files: ["b"]), files: [file], err: {}, handler: {d in print("success \(d)")})
}
```
## Further details
Only uploading 1 file will cause the error. Uploading 2 files, 0 file, 3 files all success.
For example, the following success!
```
func testUpload() {
    let url = Bundle.main.url(forAuxiliaryExecutable: "a.txt")!
    let file = try! GraphQLFile(fieldName: "files", originalName: "aa", fileURL: url)
    let url2 = Bundle.main.url(forAuxiliaryExecutable: "a2.txt")!
    let file2 = try! GraphQLFile(fieldName: "files", originalName: "aa2", fileURL: url2)
    upload0(mutation: TestUploadMutation(files: ["b", "b2"]), files: [file, file2], err: {}, handler: {d in print("success \(d)")})
}
```
with message `success Data(resultMap: ["multiUpload1": Optional([Optional(["name": Optional("aa"), "__typename": Optional("UploadFile")]), Optional(["__typename": Optional("UploadFile"), "name": Optional("aa2")])])])
`

**Comment by designatednerd** [comment]
So we do have [a test case covering this](https://github.com/apollographql/apollo-ios/blob/5026e7bc69c8ad4de7f5407676a0d56605e754dc/Tests/ApolloTests/UploadTests.swift#L202). Comparing and contrasting with that, it looks like you're using different strings for the `files` array you pass into the mutation than for the `originalName`. What happens if you make those strings the same? 

Another thing that jumps out at me is you're using `url(forAuxiliaryExecutable)` on `Bundle` to load a file. Generally, that's not used to load files on iOS. I would recommend using [`url(forResource:withExtension:)`](https://developer.apple.com/documentation/foundation/bundle/1411540-url). It does look like it's working since your other uploads are working, but it's definitely not a best practice if you're not actually loading an executable file.

**Comment by CheShengSu** [comment]
I tried the modified function:
```
static func testUpload() {
    let url = Bundle.main.url(forResource: "a", withExtension: "txt")!
    upload0(mutation: TestUploadMutation(files: ["a"]), files: [try! GraphQLFile(fieldName: "files", originalName: "a", fileURL: url)], err: {}, handler: {d in print("success \(d)")})
}
```
But I got the same error message:
`Received a 422 error. Data returned as a String was: {"errors":[{"message":"must be an array","path":["variable","files"],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null,"extensions":{"tracing":{"version":1,"startTime":"2021-03-13T00:12:22.657389476Z","endTime":"2021-03-13T00:12:22.657558795Z","duration":169284,"parsing":{"startOffset":104798,"duration":16726},"validation":{"startOffset":122798,"duration":-9223372036854775808},"execution":{"resolvers":null}}}}
`
