### ISSUE TITLE
Map_String_StringScalar to JSON in query variables

### ISSUE THREAD

**Issue by greenmood** [apollographql/apollo-ios#1708]
Hi, our server expects **filter** variable to be passed as JSON with the following query:
`query getFiltersById($limit: Int!, $offset: Int!, *$filter: Map_String_StringScalar!*, $sort: SortInput, $queryParams: Map_String_StringScalar!) `

```
"variables": {  	
		"filter": {
			"id": "00000000-0000-0000-0000-000000000003"
		},
}
```
But in API.swift, filter is a string variable. So passing the following won't work, server returns with 
`Variable 'filter' has an invalid value. Expected type 'Map' but was 'String'`
```
"variables": {
		"filter": "{\"id\":\"00000000-0000-0000-0000-000000000003\"}",
	}
```

I've tried defining a custom scalar JSON, but passing it as variable type, instead of  Map_String_StringScalar, didn't work.

How can we pass a JSON as query variable?

**Comment by designatednerd** [comment]
You'd have to define the custom JSON with a typealias to `Map_String_StringScalar`, _and_ use `passthroughCustomScalars`, otherwise the type system will freak out.

**Comment by greenmood** [comment]
Creating a custom JSON struct in swift required it to conform to JSONEncodable, so I thought I can give a try to JSONObject
`public typealias Map_String_StringScalar = JSONObject` 

Can't say if that worked now since right after `passthroughCustomScalars`, I got tons of `Cannot find type 'InstantScalar' in scope` with `Long` or `ObjectScalar` sometimes instead of `InstantScalar`.

**Comment by designatednerd** [comment]
It sounds like using `passthroughCustomScalars` revealed a couple other custom scalars you were using without realizing it. If you `typealias` those to `String` that should help. 

I don't know if just typealiasing to `JSONObject` will work - You'll probably need to do some implementations of Apollo's `JSONEncodable` and `JSONDecodable` protocols. I'd recommend taking a look at our [playground page on custom scalars](https://github.com/apollographql/apollo-ios/blob/main/Playgrounds/ApolloMacPlayground.playground/Pages/CustomScalars.xcplaygroundpage/Contents.swift) for an example.

**Comment by greenmood** [comment]
Man, thank you and your family. You saved my release! Sending rays of unicorns from Ukraine.
