### ISSUE TITLE
API reference on Cocoapods is broken

### ISSUE THREAD

**Issue by julien1619** [apollographql/apollo-ios#171]
Since the last update, the API reference on Cocoapods seems to be broken.

> Error Parsing Pod
[http://cocoadocs.org/docsets/Apollo/](http://cocoadocs.org/docsets/Apollo/)

You can still navigate through the previous versions anyway.

**Comment by iki** [comment]
Confirmed, the latest working is 0.6.5.
All 0.7.0 are broken: `Could not find Objective-C Classes.`
And 0.9.0 is missing completely.

**Comment by martijnwalraven** [comment]
[Cocoapods no longer generates documentation](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/), so we'd need to do this ourselves.

**Comment by designatednerd** [comment]
Going to close this one out in favor of #622 - in #618 I've at least removed the reference to CocoaDocs  so people don't get pointed in the wrong direction.
