### ISSUE TITLE
Unable to serialize JSON custom scalar type-aliased as String dictionary

### ISSUE THREAD

**Issue by Apocryphon** [apollographql/apollo-ios#1714]
## Bug report

Working off [this discussion](https://github.com/apollographql/apollo-ios/discussions/1711):

The deserialization works with the changes described. However, `JSON` custom scalar being type-aliased as `[String: Any]?` is not able to be serialized now for a submission mutation- that is, instead of previously allowing me to turn the local Swift dictionary into a JSON string that can be sent to the server, it forces me to send the dictionary itself, which the server cannot read. Is there any way to apply different logic for custom scalars between deserialization and serialization?

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.33.0
- Xcode version: 12.4
- Swift version: 
- Package manager: Cocoapods

## Steps to reproduce

Implement client-side consumption of a JSON custom scalar type as per [this discussion](https://github.com/apollographql/apollo-ios/discussions/1711).

## Further details

What are the best practices for creating custom scalars for nested types?

**Comment by Apocryphon** [comment]
I should note that type-aliasing `JSON` to `String` doesn't work, because Apollo isn't able to deserialize it as a JSON string; it must be deserialized as a dictionary. If there's a workaround for this, it would probably be preferable for it to be type-aliased as `String` for both deserialization and serialization.

**Comment by Apocryphon** [comment]
Some further details.

Our custom JSON scalar in the schema:
```
        {
          "kind": "SCALAR",
          "name": "JSON",
          "description": null,
          "fields": null,
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        },
```

Our API call returns a `Problem`, which is a JSON object and would be consumed by Apollo as a `[String: Any]`, presumably.

```
      "problem": {
        "label": "...",
        "type": "...",
        "solutions": [
          {
            "id_1": "Do this",
            }
]
```

By following the official custom type scalar documentation, were able to override `JSONDecoding` and return `Problem` as a String dictionary that we could convert to Swift model structs. (For some reason, we had to type-alias it to an optional, because type-aliasing it as dictionary would draw a compiler complaint about `Conformance of 'Dictionary<Key, Value>' to protocol 'JSONDecodable' conflicts` - it's discussed in detail in [this](https://github.com/apollographql/apollo-ios/discussions/1711) discussion.

However, it breaks our `Solution` API, which previously required us to send solutions as JSON `String`s.

`"solutions": "{\"id_1\":[\"Do this\"],\"id_A\":[\"Do that\"],\"foo\":[\"bar\"]}"`

If we try to send it as a `Dictionary`/JSON object instead of a JSON string, an error results:

```
solutions": {
			"id_1": ["Do this"],
			"foo": ["bar"],
...
}
```

Error:

```
"errors": [{
		"message": "no implicit conversion of ActionController::Parameters into String",
		"extensions": {
			"code": "INTERNAL_SERVER_ERROR"
		}
	}],
```

So why is there inconsistent behavior between receiving and sending `JSON` objects? Is there any way at all to type-alias as both a `Dictionary` **and** a `String`?

**Comment by designatednerd** [comment]
I would suggest starting [here](https://github.com/apollographql/apollo-ios/discussions/1650#discussioncomment-333222) - if you don't know type something's going to be, setting it up as an enum of its possible types and then adding conformance for that to `JSONDecodable` is probably the best way to go. 

Also, please do not open multiple issues and discussions on the same topic - if you feel like we've missed something, please re-ping us on the original issue. I'll cop to it being slightly annoying for maintainers to deal with multiple threads, but the main reason to do it that way is that it's way better for search engines to only have one item to index with a particular answer so that other people looking for a similar answer can find it in one place. Thank you!

**Comment by Apocryphon** [comment]
Thanks for confirming that the `enum` approach is the way to go. I'm actually trying to adapt your [full approach](https://github.com/apollographql/apollo-ios/issues/1523#issuecomment-744766938).

**Comment by Apocryphon** [comment]
@designatednerd It works! We had to override `JSONEncodable` as well, but creating a `JSONType` `enum` really helps.

I think it'd be really helpful if the sample approach above was added to the documentation. Good to know that it's the recommended way to deal with this situation.

Any idea about the compiler warning and error mentioned in the earlier discussion?

**Comment by designatednerd** [comment]
> For some reason, we had to type-alias it to an optional, because type-aliasing it as dictionary would draw a compiler complaint about Conformance of 'Dictionary<Key, Value>' to protocol 'JSONDecodable' conflicts

I believe it'd run into [this definition](https://github.com/apollographql/apollo-ios/blob/d1369d43cd38896547278f147a8654146e864448/Sources/Apollo/JSONStandardTypeConversions.swift#L122). 

I am planning to add this suggestion to the docs. Is there anything else I can help with here?

**Comment by Apocryphon** [comment]
I think we're good on this blocker for now, thanks!

**Comment by designatednerd** [comment]
This was added to the docs in #1720 as well. Thanks!
