### ISSUE TITLE
Unable to read a JSON data type using Apollo - iOS client

### ISSUE THREAD

**Issue by rajeshmani27** [apollographql/apollo-ios#1726]
## Bug report

I have a JSON data type for one of the fields in my query response that gives an error when extracting the attribute value of that field in Apollo iOS swift query response.  I don't run into this issue with Apollo React client

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.42
- Xcode version: 12.4
- Swift version: 5.0
- Package manager: swift package manager (

## Steps to reproduce
I have a JSON data type that is generated using Hasura Graphql server on a Postgres table with JSONB field.
However, when I create the API.swift using the build script, the data type shows as a 
         GraphQLField("data", type: .nonNull(.scalar(String.self)))

When I make the query, it gives an error
```
Error:GraphQLResultError(path: upload_file.0.data, underlying: Apollo.JSONDecodingError.couldNotConvert(value: {
    key1 = "val1";
    key2 = "val2";
    key3 =     {
        "key3.1 = "val3.1";
        "key3.2 = "val3.2";
        };
}, to: Swift.String))
```

I am looking for guidance on how to ensure I can read a JSON data type in query responses in swift.

**Comment by designatednerd** [comment]
Good timing, we now have [docs about this](https://www.apollographql.com/docs/ios/fetching-queries/#json-and-other-custom-scalars-with-multiple-return-types) that I added earlier this week.

**Comment by rajeshmani27** [comment]
Thanks for the pointer. I am trying to implement per the referenced document link and did the following, but running into build issues:
1) Included passthroughscalar in the script as follows:
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --passthroughCustomScalars 
--includes=./**/*.graphql --localSchemaFile="schema.json" GraphQL/API.swift

2) Created a new file (APIExtension.swift) in the same folder as API.swift with the following code:
import Foundation
import Apollo

enum CustomJSON {
  case dictionary([String: Any])
  case array([Any])
}

extension CustomJSON: JSONDecodable {
  init(jsonValue value: JSONValue) throws {
    if let dict = value as? [String: Any] {
      self = .dictionary(dict)
    } else if let array = value as? [Any] {
      self = .array(array)
    } else {
      throw JSONDecodingError.couldNotConvert(value: value, to: CustomJSON.self)
    }
  }
}

3) As soon as I ran the build I get a bunch of issues on original API.swift 
  "cannot find 'uuid', 'jsonb', 'numeric' ..." in scope

Can you share the sequence to go through for the build to be successful and read the custom JSON data type (I have one level of json nesting as outlined above) is read properly

Thanks.

**Comment by designatednerd** [comment]
So you will need to change the name from `CustomJSON` to whatever the name is for `jsonb` type. 

It sounds like you had a few other custom scalars that came through - most of those you should be able to just do something like `typealias uuid = String`, or whatever the underlying type was, to get that compiling again.

**Comment by trant** [comment]
I am actually having a similar issue but my `metadata` type is being generated as :

```

**Comment by AnthonyMDev** [comment]
@rajeshmani27 Did this resolve the issue for you? We'd like to close this out if it is resolved! Thanks!

**Comment by AnthonyMDev** [comment]
Since we haven't received any more comments on this issue, I'm going to close this out. Feel free to comment here if you need this re-opened or create a new issue!
