### ISSUE TITLE
Add support for unknown enum values

### ISSUE THREAD

**Issue by abhisood** [apollographql/apollo-ios#174]
Problem: whenever server returns new unsupported by client enum value it's a breaking change, as we force cast the raw string value to appropriate generated enum constant.

Simillar to https://github.com/apollographql/apollo-android/pull/712 on Android

**Comment by JustinDSN** [comment]
This should resolved by #177, and https://github.com/apollographql/apollo-codegen/pull/290. Please let us know your results and close the issue.

**Comment by abhisood** [comment]
@JustinDSN - This is perfect! Thanks!
