### ISSUE TITLE
Exponential web socket reconnections leads to exhaustion of file descriptors, device heat, and application crash

### ISSUE THREAD

**Issue by groue** [apollographql/apollo-ios#1753]
## Bug report

`WebSocketTransport` attempts at reconnecting whenever Starscream outputs an error:

- https://github.com/apollographql/apollo-ios/blob/0.42.0/Sources/ApolloWebSocket/WebSocketTransport.swift#L408-L420
- https://github.com/apollographql/apollo-ios/blob/0.42.0/Sources/ApolloWebSocket/WebSocketTransport.swift#L448-L453

On iOS 14.2.2, a device on airplane mode has the underlying Foundation web socket stream output 2 errors NSPOSIXErrorDomain code 50 "Network is down", which are both notified by Starscream. This has Apollo attempts 2 reconnections. Which have Starscream create two new sockets, which generate two errors each, and now we have four reconnections. Then 8, 16, etc. With the default reconnection interval of 0.5, this goes pretty fast. Eventually file descriptors are exhausted, device turns hot, and application crashes.

`WebSocketTransport` is not making sure the number of reconnections is kept under control.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.42.0
- Xcode version: 12.4
- Swift version: 5.3
- Package manager: Xcode's

## Steps to reproduce

```swift
let cache = InMemoryNormalizedCache()
let store = ApolloStore(cache: cache)
let client = URLSessionClient()
let provider = NetworkInterceptorProvider(store: store, client: client)
let requestChainTransport = RequestChainNetworkTransport(interceptorProvider: provider, endpointURL: httpURL)
let webSocketTransport = WebSocketTransport(request: URLRequest(url: webSocketURL), connectingPayload: [:])
let splitNetworkTransport = SplitNetworkTransport(
    uploadingNetworkTransport: requestChainTransport,
    webSocketNetworkTransport: webSocketTransport
)
let apollo = ApolloClient(networkTransport: splitNetworkTransport, store: store)
```

And then turn airplane mode on.

It's delicate to setup a demo project, since my server is private.

**Comment by groue** [comment]
> a device on airplane mode has the underlying Foundation web socket stream output 2 errors NSPOSIXErrorDomain code 50 "Network is down"

For the record, I can witness Starscream handle two `NSStreamEventErrorOccurred` events for the same `__NSCFInputStream` instance in its `stream(_:handle:)` implementation.

Maybe this issue should be reported to Starscream as well, although its raw reporting of all Foundation events can be seen as an actual feature. I mainly think that Apollo should be ready to handle multiple error notification gracefully (its inner state machine should avoid reconnecting several times).

I'll try to gather a pull request.

**Comment by groue** [comment]
> Maybe this issue should be reported to Starscream as well

Done in https://github.com/daltoniam/Starscream/issues/881

**Comment by designatednerd** [comment]
Ouch! Thanks for filing with StarScream, but you're right that we shouldn't be just reconnecting blindly. Are you still interested in putting together a PR?

**Comment by groue** [comment]
> Are you still interested in putting together a PR?

I could avoid this bug in https://github.com/fairjungle/apollo-ios/commit/ce9f82015a08e187c55660b089ef7963a7731453, and this helped me moving forward.

But I'm really not versed in the subtleties of web socket states, and I think my commit breaks `.reconnectSuggested` handling, because `attemptReconnectionIfDesired()` [no longer reconnects if already connected](https://github.com/fairjungle/apollo-ios/commit/ce9f82015a08e187c55660b089ef7963a7731453#diff-95d7d9cab8f093ee9c07adb8bf4d855dab21b792b791c791b8b91397707dd786R486).

I admit I'd prefer if one of Apollo WS gurus would settle this for good, if this is not too much to ask.

---

I'm surprised I could not see more bug reports about this. Do you think I could do something wrong? When the bug expresses itself, the console is flooded with error logs:

```
2021-04-15 09:14:00.484152+0200 xxx[3267:769101] [connection] nw_connection_get_connected_socket [C56] Client called nw_connection_get_connected_socket on unconnected nw_connection
2021-04-15 09:14:00.484385+0200 xxx[3267:769101] TCP Conn 0x2801106e0 Failed : error 0:50 [50]
2021-04-15 09:14:00.485035+0200 xxx[3267:769105] [connection] nw_connection_get_connected_socket [C57] Client called nw_connection_get_connected_socket on unconnected nw_connection
2021-04-15 09:14:00.485273+0200 xxx[3267:769105] TCP Conn 0x28010cc60 Failed : error 0:50 [50]
```

**Comment by groue** [comment]
> I'm surprised I could not see more bug reports about this.

Maybe related: https://spectrum.chat/apollo/apollo-ios/tcp-conn-failed-error-0-50~d9c036be-1395-47e9-a324-175d59953c6b

It would be disappointing if responsibility was muddled between Apollo and StarScream: for better or for worse, applications link to Apollo.

**Comment by siliconprime-hungnguyen** [comment]
I have same issue

**Comment by NiaFan0128** [comment]
Same issue here. Wait for the update.

**Comment by groue** [comment]
Hello @designatednerd, may I ask how this issue should move forward?

As you can see, one week after the initial report, we do not have much feedback from other users except vague "same issue" comments. But did you or someone at Apollo try to reproduce the problem (websockets + airplane mode, basically)?

Do you 100% rely on pull requests in order to solve issues like this one? I admit this would sound concerning to me, because unless someone has both 1. the issue 2. the skills to fix it, this sounds like a recipe for issues that eventually get closed due to lack of activity (as other issues in this repo). Meanwhile the bug remains. Here we are talking about a severe bug that prevents the use of WebSocket-based GraphQL subscriptions.

Is it possible for get some feedback about this particular issue, and maybe some clarification on your bug-fixing process?

**Comment by designatednerd** [comment]
Hey @groue, thanks for the poke.

We do not rely solely on pull requests. As a team of 2, we do very much appreciate pull requests when you find something that helps. (You’ll be happy to hear that [we’re hiring another iOS dev](https://www.apollographql.com/careers/job?id=d5f9daf2-14a5-46b8-b337-af16ff56e1b7) in order to help get more hands on deck.) I'd honestly thought I'd already asked you to open a PR with your workaround, so let me do that here: Can you please open a PR with your workaround? 

I’ll also add that the Starscream integration was contributed before I started, so I want to be clear that we are not “web socket gurus”. We’re using Starscream precisely because we _don’t_ have web socket experts. This obviously is a case where we needed more testing around how we were using Starscream, which will be added as I look into the fix here.

**Comment by groue** [comment]
All right, I'll do my best.

**Comment by groue** [comment]
Pull request submitted in https://github.com/apollographql/apollo-ios/pull/1762
