### ISSUE TITLE
Unable to complete tutorial in current XCode - no table view is present

### ISSUE THREAD

**Issue by nmalancea** [apollographql/apollo-ios#1758]
## Bug report

I was following the tutorial and got stuck on the fact that new Swift projects in XCode do not have a table view present by default. Since I'm somewhat new to SwiftUI moving forward in the tutorial is quite a challenge. Would you please update the tutorial to work with the latest versions of XCode?

Also the tutorial references 0.19.0 of apollo-ios when the latest is much newer - 0.42.0.

## Versions
- `apollo-ios` SDK version: 0.42.0
- Xcode version: 12.4 (12D4e)
- Swift version: 5

## Steps to reproduce
Follow the tutorial at https://www.apollographql.com/docs/ios/tutorial/tutorial-create-project. The issues start in the 2nd step of part 1. "Master-Detail App" is no longer available as a template in XCode.

**Comment by nmalancea** [comment]
I found a simpler [tutorial](https://levelup.gitconnected.com/use-apollo-graphql-in-swiftui-6eec1495dea1) which only covers queries (no mutations) and I was able to get set up with that one, but it would still be very nice to fix the one here. Thanks.

**Comment by designatednerd** [comment]
Oof, thanks for the heads up! The current tutorial doesn't use SwiftUI, it uses Storyboards, though I'm hoping to update that soon. 

For now, if you set your Interface to `Storyboard` in new project creation, you should be able to use the storyboard UI to bring in a table view controller: 

<img width="462" alt="Screen Shot 2021-04-16 at 2 01 14 PM" src="https://user-images.githubusercontent.com/1976498/115071726-37ac2180-9ebc-11eb-90e1-7ce2c9ee3bc8.png">

**Comment by designatednerd** [comment]
We just published an update today that switches to a starter version of the app which we provide that has a lot more stuff already built out, and doesn't rely on Apple to not change things between minor versions of Xcode 😇 It also uses Apollo Studio Sandbox and Xcode 13. 

Thank you very much for your patience, and sorry this took so danged long!
