### ISSUE TITLE
Unexpected types aren't supported on interfaces fragments

### ISSUE THREAD

**Issue by GraemeHarrison** [apollographql/apollo-ios#1760]
## Bug report
The codegen doesn’t support unexpected future types when the interface is a fragment, which removes the benefit of using interfaces in the first place.

**Related issues:** [#1727](https://github.com/apollographql/apollo-ios/pull/1727) & [#720](https://github.com/apollographql/apollo-ios/issues/720)

## Versions
- `apollo-ios` SDK version: 0.41.0
- Xcode version: 12.4
- Swift version: Swift 5
- Package manager: Carthage

## Steps to reproduce
Example
```
query HanSolo {
  character(id: 1002) {
    name
    ... on LightsaberWielders {
        lightsaberColor
    }
  }
}
```
Let’s say `LightsaberWielders` was an interface that was only implemented by type `Jedi`. If at some point in the future a new type called `Sith` was added on the backend, which also implemented `LightsaberWielders`, the schema would have to be updated to support getting the `lightsaberColor`  from it.

It seems that the issue may be in [Decoding.swift](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/Decoding.swift), with this switch case that lumps unions and interfaces together:
```
for selection in selections {
    switch selection {
    case let field as GraphQLField:
      ...
    case let fragmentSpread as GraphQLFragmentSpread:
      let fragment = fragmentSpread.fragment
      if let runtimeType = runtimeType, fragment.possibleTypes.contains(runtimeType) {
        try collectFields(from: fragment.selections,
                          forRuntimeType: runtimeType,
                          into: &groupedFields,
                          variables: variables)
      }
    case let typeCase as GraphQLTypeCase:
      ...
    default:
      preconditionFailure()
    }
  }
}
```
Here `GraphQLFragmentSpread` is used for both concrete types and types implementing an interface. Checking for the runtime type makes sense for concrete types. For an interface type, it should only care whether it can collect the needed fields from the returned object, regardless of what the type returned from the server is.

If there was a way to distinguish between union types and interfaces, instead of treating them both as a `GraphQLFragmentSpread`, then  we could remove the runtimeType check for interfaces, which is currently prohibiting the fields to be collected.

Another issue this causes is with the property name of the fragment. Instead of using the interface name (ie. `asLightsaberWielders`), which would be expected, the codegen creates a name that combines all of the concrete types. In this case it would generate the property name `asJediOrSith`,  which isn’t terrible when there are only two types, but it can easily get out of hand as more types are added.

**Comment by AnthonyMDev** [comment]
I definitely agree that this isn't ideal. As you called out, this seems to be very closely related to #1727, to the point of almost being a duplicate. We are planning on handling this much better with the new version of CodeGen we are working on. That issue has pretty thorough discussion of this.

I'm going to close this, and we can continue and discussion on #1727. Thank you for the feedback though! It is going to be addressed I promise you!
