### ISSUE TITLE
GraphQLExecutor bugging out? 

### ISSUE THREAD

**Issue by mtodd90** [apollographql/apollo-ios#1768]
I've installed Apollo with cocoapods in my project, added a schema.json, .graphql file with 1 query, script above Compile Sources - essentially everything from installation docs - and tried to build it and I got the following bugs:
in ApolloStore.swift: 
 - line 196:
Cannot invoke initializer for type 'GraphQLExecutor' with an argument list of type '(@escaping ([String : JSONValue], GraphQLResolveInfo) -> JSONValue?)'
1. Expected an argument list of type '(resolver: @escaping GraphQLFieldResolver, resolveReference: ReferenceResolver?)' (if this is solution I don't know how to successfully apply it) 
- line 198:
Closure expression is unused 
Consecutive statements on a line must be separated by ';'
Expected expression
Unable to infer closure type in the current context
Use of unresolved identifier 'resolveReference'
- line 275:
Cannot invoke initializer for type 'GraphQLExecutor' with an argument list of type '(@escaping ([String : JSONValue], GraphQLResolveInfo) -> JSONValue?)' 

in GraphQLResponse.swift same thing:
- line 49:
Cannot invoke initializer for type 'GraphQLExecutor' with an argument list of type '(@escaping ([String : JSONValue], GraphQLResolveInfo) -> JSONValue?)' 

I'm fairly new to coding, and figured this isn't a mistake on my end, but I've tried uninstalling and re-installing apollo (my app works without it, with some other pods installed), making sure all targets are correct everywhere but nothing helped. 
Any help is appreciated.

**Comment by designatednerd** [comment]
Hi! Can you clarify a couple things here: 

- What version of Xcode are you using? 
- What version of the Apollo iOS SDK are you using? 
- Have you tried going to `Product > Clean Build Folder` and  then rebuilding? 

Thank you!

**Comment by mtodd90** [comment]
So, I thought I had the newest version of Xcode, but I did not. My bad, I've updated it and it's working. 
Thanks for the help!

**Comment by designatednerd** [comment]
Cool - I'm gonna close this out then!

**Comment by Vannevelj** [comment]
For reference to others: it appears these breaking changes were introduced in 0.38.0. If you're like me stuck on Xcode 11, **0.37.0** is the last version that will work.

The feature in question is _Multiple Trailing Closures_: https://github.com/apple/swift-evolution/blob/main/proposals/0279-multiple-trailing-closures.md
