### ISSUE TITLE
Codecov breach

### ISSUE THREAD

**Issue by taiho-nordstrom** [apollographql/apollo-ios#1774]
Hello Apollo team,

In response to a[ recent breach of Codecov](https://about.codecov.io/security-update/), my team did a quick research and found out that one of the dependencies in ApolloCLI does use that affected command - `bash <(curl -s https://codecov.io/bash)`

```bash
$ grep "https://codecov.io/bash" -R .
./Codegen/ApolloCLI/apollo/node_modules/es-abstract/.travis.yml:  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage && bash <(curl -s https://codecov.io/bash) -f coverage/*.json; fi'
```

I am surprised that the Travis CI config file was included in the release bundles. Is there anything your team can do to not expose the yml file that has that affected command

**Comment by designatednerd** [comment]
Hey @taiho-nordstrom  - can you please open an issue on the CLI repo here: https://github.com/apollographql/apollo-tooling

**Comment by taiho-nordstrom** [comment]
Sure, I just opened one https://github.com/apollographql/apollo-tooling/issues/2304.

Closing this
