### ISSUE TITLE
File generated with Swift Scripting is several times bigger

### ISSUE THREAD

**Issue by wow-such-amazing** [apollographql/apollo-ios#1792]
## Bug report

Hey 🙂 

First of all thank you for all the hard work you are doing! The library improved a lot over time 🤩 

I recently decided to try Swift Scripting for the code generation and I faced an issue where new generated file contains ~420k lines instead of previously ~65k. Plus the size of the file increased from ~2.5 mb to ~15 mb. Where do you think this issue may come from? Maybe I misconfigured something 🤔 

Also I switched to using this approach and my generated file is 65k lines again 🕺 So I guess there is some bug in swift scripting 🤔 

<img width="564" alt="Screenshot 2021-05-14 at 12 42 36" src="https://user-images.githubusercontent.com/7022709/118252833-de7ee000-b4b1-11eb-93b3-32ec0e1e1c02.png">

**Old approach**

Build phase:
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --omitDeprecatedEnumCases --target=swift --includes=./**/*.graphql --localSchemaFile="ApiServices/Apollo/schema.json" ApiServices/Apollo/ApolloAPI.swift
```

**New approach**

Build phase:
```
cd "${SRCROOT}/../Codegen"
xcrun -sdk macosx swift run Codegen generate
```

Codegen:
```
struct GenerateCode: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "generate",
        abstract: "Generates swift code from your schema + your operations based on information set up in the `GenerateCode` command."
    )

    mutating func run() throws {
        let fileStructure = try FileStructure()

        CodegenLogger.log("\nFile structure:\n\(fileStructure)")

        let schemaFileUrl = try fileStructure.coreFolderUrl.apollo.childFileURL(fileName: "schema.json")
        let apiFileUrl = try fileStructure.coreFolderUrl.apollo.childFileURL(fileName: "API.swift")

        let codegenOptions = ApolloCodegenOptions(
            includes: "../../**/*.graphql",
            omitDeprecatedEnumCases: true,
            outputFormat: .singleFile(atFileURL: apiFileUrl),
            urlToSchemaFile: schemaFileUrl,
            downloadTimeout: 60.0
        )

        try ApolloCodegen.run(
            from: fileStructure.coreFolderUrl,
            with: fileStructure.cliFolderUrl,
            options: codegenOptions
        )
    }
}
```

## Versions

- `apollo-ios` SDK version: 0.43
- Xcode version: 12.5
- Swift version: 5
- Package manager: 5.4

**Comment by AnthonyMDev** [comment]
Thanks for the thorough bug report! You'll want to set the `mergeInFieldsFromFragmentSpreads` option to false to get the behavior you are looking for. On the old codegen, the default for that was false, and we changed it to true by default now.

It makes your generated code easier to use, but also much larger. (We're looking to dramatically reduce the code size with the new version of the Code Gen we are working on!)

**Comment by wow-such-amazing** [comment]
Thank you for the response! I will check it some time soon. I guess we can close the issue for now. I will re-open it later if something doesn't work for me :) 

Looking forward to new code generation, especially to auto-generated input/output files 😍
