### ISSUE TITLE
Support Batch Query

### ISSUE THREAD

**Issue by mlight3** [apollographql/apollo-ios#1795]
## Feature request

Support Batch Query

## Motivation

I would like to send a batch query to execute multiple queries. I made a 'BatchQuery' class to implement this feature, but because of returning `GraphQLMap` form `RequestBodyCreator` it didn't work. Finally, I need to create my own `NetworkTransport` for this.

## Proposed solution

Add function to return `[JSONEncodable]` type in `RequestBodyCreator` protocl

**Comment by designatednerd** [comment]
@mlight3 I'd be interested in seeing more of your solution, we've certainly wanted to do this for a while, but there's only so many fish we've been able to fry at once. We'd certainly be happy to work with you on a PR!

**Comment by calvincestari** [comment]
Closing - will track this in #192
