### ISSUE TITLE
Protocol conformance URLSessionClient to help with unit testing

### ISSUE THREAD

**Issue by dallasjohnson** [apollographql/apollo-ios#1796]
## Feature request
Firstly, great work on Apollo iOS client 👏 . It's a pleasure to work with and the new RequestChain architecture is great.  I feel I have just scratched the surface with what it is capable of.

**My request:** Create a protocol that `URLSessionClient` conforms to that can be mocked with custom mock objects to help with unit testing.

## Motivation
The change in ApolloClient to include a request chain with `ApolloInterceptor` types is very powerful and flexible but also means there is potentially more custom logic in this area of my network stack that requires more unit tests. By having the `URLSessionClient` (and `ApolloStore` while I'm here) conform to a protocol then it's trivial to write a MockURLSessionClient conforming to the same protocol for tests.

## Proposed solution

I started created a protocol double based on the generated header file for URSSessionClient as below but soon hit a blocker because the built in interceptors expect a `URLSessionClient.` Therefore to this cleanly it would be changed in the Apollo framework code.

```swift
/// A completion block to be called when the raw task has completed, with the raw information from the session
public typealias RawCompletion = (Data?, HTTPURLResponse?, Error?) -> Void

/// A completion block returning a result. On `.success` it will contain a tuple with non-nil `Data` and its corresponding `HTTPURLResponse`. On `.failure` it will contain an error.
public typealias Completion = (Result<(Data, HTTPURLResponse), Error>) -> Void

protocol URLSessionClientType {
    func invalidate()
    func clear(task identifier: Int)
    func clearAllTasks()
    func sendRequest(_ request: URLRequest, rawTaskCompletionHandler: RawCompletion?, completion: @escaping Completion) -> URLSessionTask
    func cancel(task: URLSessionTask)
    func urlSession(_ session: URLSession, didBecomeInvalidWithError error: Error?)
    func urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics)
    func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)
    func urlSessionDidFinishEvents(forBackgroundURLSession session: URLSession)
    func urlSession(_ session: URLSession, task: URLSessionTask, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)
    func urlSession(_ session: URLSession, taskIsWaitingForConnectivity task: URLSessionTask)
    func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?)
    func urlSession(_ session: URLSession, task: URLSessionTask, needNewBodyStream completionHandler: @escaping (InputStream?) -> Void)
    func urlSession(_ session: URLSession, task: URLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64)
    func urlSession(_ session: URLSession, task: URLSessionTask, willBeginDelayedRequest request: URLRequest, completionHandler: @escaping (URLSession.DelayedRequestDisposition, URLRequest?) -> Void)
    func urlSession(_ session: URLSession, task: URLSessionTask, willPerformHTTPRedirection response: HTTPURLResponse, newRequest request: URLRequest, completionHandler: @escaping (URLRequest?) -> Void)
    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data)
    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didBecome streamTask: URLSessionStreamTask)
    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didBecome downloadTask: URLSessionDownloadTask)
    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, willCacheResponse proposedResponse: CachedURLResponse, completionHandler: @escaping (CachedURLResponse?) -> Void)
    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive response: URLResponse, completionHandler: @escaping (URLSession.ResponseDisposition) -> Void)
}
```

and then get the existing URLSessionClient to conform to this with:

```swift
extension URLSessionClient: URLSessionClientType {}

```

And then change the built-in interceptors (eg. `NetworkFetchInterceptor`) to use the protocol rather than the concrete `URLSessionClient` type.

## Outstanding Questions

I've only just started to do this protocol doubling approach for Apollo Networking code and this was the first blocker I hit so perhaps there are other Apollo types that could benefit from this change to increase testability of the code consuming Apollo client. `AtomicStore` looks like it could too.

**Comment by AnthonyMDev** [comment]
Thanks for the proposal! The `URLSessionClient` was made open intentionally so you can subclass it for unit testing. You can see our implementation of `MockURLSessionClient` that we use for testing in the `ApolloTestSupport` package in this repo.

Would subclassing work for your needs, or is there some better functionality provided by using a protocol here?

**Comment by dallasjohnson** [comment]
Thanks for the quick response. I must admit I hadn't considered subclassing for the mocks because I have always pushed for and implemented protocol doubles myself for my own testing. 
The reasons for the protocol approach are:
* I don't need to override everything in the subclass to avoid unintentional behaviour from super class
* I don't need to worry about potential instantiating a heavy super class for every test which could slow down my tests.

I have managed to achieve what I wanted so far with my own protocol and retrospective conformance to the protocol with `extension URLSessionClient: URLSessionClientType {}` but that also meant I needed to customise the default `VBPNetworkFetchInterceptor` to use the protocol, which is not ideal.
There may still be other issues I will encounter since I'm still working on writing my tests.
Perhaps the subclass approach may also do everything I need as a pragmatic path forward.

While I personally prefer the protocol double approach, I'm not blocked without it so I can adapt to your preference without too much trouble.


I just did a quick google for articles to support or refute my ideas on this and this came up as food for thought.
https://www.swiftbysundell.com/articles/mocking-in-swift/ 

Thanks for all your great work on this.

**Comment by AnthonyMDev** [comment]
I agree in general. I prefer protocols for dependency inversion and for making mocks easier whenever possible. @designatednerd mentioned that this needed to be done with a subclass because of something to do with the way `URLSessionDelegate` works. I'm not clear on the details, but she is on vacation now, so perhaps she can elaborate when she gets back!

But at least you aren't blocked on this for now. I'm going to close the issue, as migrating this to protocols may not be possible, and if it is, perhaps we will do it in the future, but it's not blocking anyone for the time being.

Thanks for the issue @dallasjohnson
