### ISSUE TITLE
Package.resolved being reset after checking out a branch with updates to Apollo

### ISSUE THREAD

**Issue by CraigSiemens** [apollographql/apollo-ios#1799]
## Bug report

I'll preface this with the fact that I'm not sure whether this is a SPM bug or an Apollo one, but since I can only reproduce it with Apollo, I figured I'd post here as well.

We have an SPM cli tool that has a subcommand for running the Apollo codegen. When switching branches in our repo to one that has updated the Apollo version in the `Package.resolved` and running `swift build`, `Package.resolved` gets reset back to contain the version of Apollo and it's dependencies that are currently checked out in the `.build` folder.

## Versions

- `apollo-ios` SDK version: 0.43.0
- Xcode version: 12.5
- Swift version: 5.4
- Package manager: SPM

### Sample package
I've made a sample package/repo attached to the [bug report here](https://bugs.swift.org/browse/SR-14647?filter=-2).

1. `cd SomePackage`
2. `git checkout main`
3. `swift build`
4. `git checkout update-dependencies`
5. `swift build`

### From scratch
1. Make a new swift package
2. Add Apollo as a dependency where there version is set to be exactly some previous version (I used 0.41.0)
3. `swift build`
4. Change the apollo dependency version from being exact to being to be `from` the older version
5. `swift build` to confirm that nothing changed
6. Commit the changes
7. Create a new branch
8. `swift package update apollo-ios`
9. Confirm that `Package.resolved` has been updated.
10. Commit the changes
11. Switch back to the first branch and run `swift package reset && swift build`
12. Confirm there are no changes to the repo
13. Switch to the branch that updated Apollo
14. `swift build`

### Expected behaviour

It should build the updated dependencies based on what's in `Package.resolved`

### Actual behaviour

The `Package.resolved` is updated to match the version of the dependencies that is currently checked out.

Running `swift package reset` before `swift build` uses the dependency versions from `Package.resolved`

### Additional notes

- There is a warning cause Apollo isn't added to a target, this is just to speed up building. Adding the dependency as a dependency of a target has no affect.
- There is a warning about `swift-nio-zlib-support` but I was unable to reproduce the issue with just `swift-nio-zlib-support` or `Starscream` (the subdependecy that pulls in `swift-nio-zlib-support`)
- I've filed a bug report with Swift as well.
  https://bugs.swift.org/browse/SR-14647?filter=-2

**Comment by AnthonyMDev** [comment]
Hmmm. I also have no idea if this is an Apollo bug or an SPM bug. If @mattt could get someone on the SPM team to take a look at this, I will personally send his team an edible arrangements! (Is bribing Apple engineers with food some sort of ethics violation? 😨 )

**Comment by mattt** [comment]
@CraigSiemens Try passing `--disable-automatic-resolution`. Context: https://twitter.com/NeoNacho/status/1395397509669736458

**Comment by CraigSiemens** [comment]
Interesting, that works. Thanks @mattt!

I guess it's not a bug if it's the intended behaviour. But it's certainly not what I expected the default behaviour to be. I figured `Package.resolved` would be followed be default unless you were doing something like `swift package update`.

@AnthonyMDev Feel free to close this or keep it open if you're curious why it only seems to happen with Apollo and plan on looking into it some more.

**Comment by mattt** [comment]
> I guess it's not a bug if it's the intended behaviour. But it's certainly not what I expected the default behaviour to be. I figured `Package.resolved` would be followed be default unless you were doing something like `swift package update`.

You're not the only one surprised by that. To me at least, the inverse — not updating `Package.resolved` by default, and enabling with `--enable-automatic-resolution` would seem to make more sense.

**Comment by AnthonyMDev** [comment]
Thanks so much for the info @mattt. I agree that it would make more sense to invert the default behavior here.

Glad this is working for you now @CraigSiemens! I'll close this issue out.

**Comment by yodagamaheshan** [comment]
https://stackoverflow.com/a/69793517/9440709

**Comment by calvincestari** [comment]
@yodagamaheshan - are you saying that the default SPM behaviour has changed with Xcode 13 or suggesting a change to apollo-ios?
