### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by conradwt** [apollographql/apollo-ios#1806]
## Bug report

After following the tutorial to get things setup, I'm getting the following error message:

```
Command PhaseScriptExecution failed with a nonzero exit code
```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.43.0
- Xcode version: 12.5
- Swift version: 5.4
- Apollo CLI (npm): apollo/2.33.2 darwin-x64 node-v14.17.0
- Package manager: 

## Steps to reproduce

1. Created a multiplatform project with Xcode 12.5

2. Downloaded the schema.json

```zsh
apollo schema:download --endpoint=http://localhost:4000/graphql schema.json
```

3. moved the `schema.json` to the `Shared` directory in Xcode

4. On your application target's Build Phases settings tab, click the + icon and choose New Run Script Phase.

5. In the created Run Script, change its name to Generate Apollo GraphQL API

6. Drag this new run script just above Compile Sources in your list of Build Phases so that it executes before your code is compiled.

7. Copy run script for Swift Package Manager

    Note:  Updated 2nd to the last line as follows because `schema.json` is located in the `Shared` directory:

```bash
cd "${SRCROOT}/Shared"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
```

8. Command + B

## Further details

Here's the error that I'm seeing with Xcode when trying the build application:

```text
Have you tried our new Swift Package Manager wrapper around codegen? It's now out of beta and ready to go! See docs at https://www.apollographql.com/docs/ios/swift-scripting/. This Bash script will be deprecated soon, so give it a try today!

Checking if CLI needs to be downloaded...

Zip file already downloaded!

Correct version of the CLI tarball is downloaded locally, checking if it's already been extracted...

Current verson of CLI is already extracted!

 ›   Warning: apollo update available from 2.32.1 to 2.33.2.

Apollo CLI Information: apollo/2.32.1 darwin-x64 node-v10.23.1

+ /Users/conradwt/Library/Developer/Xcode/DerivedData/Flix-fmkqiqhjtebmxzadfdtntkcqpopx/SourcePackages/checkouts/apollo-ios/scripts/apollo/bin/run codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.json API.swift

 ›   Warning: apollo update available from 2.32.1 to 2.33.2.

Loading Apollo Project [started]

Loading Apollo Project [completed]

Generating query files [started]

Generating query files with 'swift' target [title changed]

Generating query files with 'swift' target [failed]

→ No operations or fragments found to generate code for.

    Error: No operations or fragments found to generate code for.

Command PhaseScriptExecution failed with a nonzero exit code
```

Reference:

- https://www.apollographql.com/docs/ios/installation

**Comment by AnthonyMDev** [comment]
```
→ No operations or fragments found to generate code for.

    Error: No operations or fragments found to generate code for.
```
This error means that it's not finding any `.graphql` files to generate code for. Have you written any of your query operations yet? You can't run this step with nothing to generate.

**Comment by conradwt** [comment]
@AnthonyMDev I have 4 `.graphql ` in the project.

**Comment by AnthonyMDev** [comment]
Okay. The CLI is not picking them up for some reason. You'll want to make sure they are in a directory path that is picked up by your command's `include` glob parameter. You are using `--includes=./**/*.graphql` currently. And you are running that after calling `cd "${SRCROOT}/Shared"` so those `.graphql` files need to be in a directory nested inside your `Shared` directory to be found given your current setup.

Is that where they are located?

**Comment by conradwt** [comment]
@AnthonyMDev Yes, `.graphql` and `schema.json` files are located in `${SRCROOT}/Shared`.

**Comment by AnthonyMDev** [comment]
And your `.graphql` files include valid query operations right? I'm just sanity checking because at this point, I'm not sure what could be causing this. There is some digging and debugging you're going to have to do here to figure out why the files aren't being picked up. @designatednerd anything I could be missing here that we?

**Comment by conradwt** [comment]
Is there a GraphQL static analyzer for validating GraphQL documents?  In any case, I have tested each of the 4 GraphQL documents against a live server.  Then I simply copied and pasted the GraphQL document from GraphiQL to the associated `.graphql` file in Xcode.

**Comment by AnthonyMDev** [comment]
The code gen tool uses an analyzer and should have a different, more specific validation error if the queries were invalid. I was just checking to make sure. But if they are working in GraphiQL they should be fine.

It definitely looks like those files aren't being picked up by the cli tool. I wonder if it's a file permissions error? That's unlikely.

**Comment by designatednerd** [comment]
I would try echoing out what `$SRCROOT/Shared` is to make sure it is where you think it is - that's the one thing that jumps out from me in this conversation. The CLI is definitely not seeing your files or you wouldn't be getting the "no operations found" error, so my hunch is it's looking in a different place than you think it's looking. Probably worth it to validate, and you may need to update your glob if it's in a different directory.

**Comment by conradwt** [comment]
After reentering the `.graphql` files into Xcode and switching to the Swift ApolloCodegen, I believe that I have something compiling with errors but it's not generating the API.swift within Xcode.  However, I'm seeing the file from `Terminal`.  Is this the expected behavior?  BTW, my Runscript looks as follows:

```
cd "${SRCROOT}"/ApolloCodegen
xcrun -sdk macosx swift run ApolloCodegen generate
```

I wasn't totally sure if I needed to include the other bits from the `Bash` implementation of the runscript.

**Comment by conradwt** [comment]
I'm going to close this issue for now as I was able to get things kind of working with the Swift codegen.

**Comment by AnthonyMDev** [comment]
Glad you got this working!

> it's not generating the API.swift where it's visible within Xcode. However, I'm seeing the file listed within Terminal. Is this the expected behavior? 

Yes, once you generate it for the first time, you'll just need to add the file to your Xcode project manually. After that, any additional runs of code gen will edit the existing file and it will stay hooked in to your Xcode project!

**Comment by EMammie** [comment]
> I'm going to close this issue for now as I was able to get things kind of working with the Swift codegen.

@conradwt 

Would like to know if you remember what changes you made to finally resolve the problem.
Dealing with what seems to be a similar issue where CLI is not finding .graphql queries and the same issue when switching to swift scripting as well

**Comment by conradwt** [comment]
@AnthonyMDev I definitely agree with your assessment here.  Thus, where can one locate the updated documentation for Apollo iOS 1.0?

**Comment by conradwt** [comment]
> > I'm going to close this issue for now as I was able to get things kind of working with the Swift codegen.
> 
> @conradwt
> 
> Would like to know if you remember what changes you made to finally resolve the problem. Dealing with what seems to be a similar issue where CLI is not finding .graphql queries and the same issue when switching to swift scripting as well

Wow, it has definitely been a while since I looked at Apollo iOS and I really don't remember what I did to get things working!!!!  Thus, I would recommend following @AnthonyMDev recommendation from above.

**Comment by AnthonyMDev** [comment]
@conradwt @EMammie 

The documentation for 1.0 is currently under construction, so a lot of it is not completed or is outdated.

That being said, the current in-progress docs are available here: https://www.apollographql.com/docs/ios/v1/
I recommend starting with that intro and then the ["Get Started"](https://www.apollographql.com/docs/ios/v1/get-started) page. These two pages are updated and totally accurate (though possibly not 100% comprehensive).

The entire section of the docs under "Fetching" and the "Custom Scalars" page are also done. The rest is still in progress.

This should definitely get you started! And as I said, we are going to have docs finished and the stable 1.0 release published Friday (before GraphQL Summit starts next week!)

**Comment by EMammie** [comment]
> @conradwt @EMammie
> 
> The documentation for 1.0 is currently under construction, so a lot of it is not completed or is outdated.
> 
> That being said, the current in-progress docs are available here: https://www.apollographql.com/docs/ios/v1/ I recommend starting with that intro and then the ["Get Started"](https://www.apollographql.com/docs/ios/v1/get-started) page. These two pages are updated and totally accurate (though possibly not 100% comprehensive).
> 
> The entire section of the docs under "Fetching" and the "Custom Scalars" page are also done. The rest is still in progress.
> 
> This should definitely get you started! And as I said, we are going to have docs finished and the stable 1.0 release published Friday (before GraphQL Summit starts next week!)

Thanks for this welcome update. 
I will continue to investigate the underlying cause. and upgrade to the stable 1.0 release this week
