### ISSUE TITLE
[Swift] Code bloat caused by duplicative types when using fragments

### ISSUE THREAD

**Issue by JaviSoto** [apollographql/apollo-ios#181]
I searched for similar issues and couldn't find one, but please excuse me if this has been reported before.

There may be something I'm missing and this may be by design, but I'm hoping that this is a possible optimization that can be made, and that it's still good timing (given that we're before v1.0), since this would be a breaking change.

When making queries like:

```graphql
fragment UserFragment on User {
  name
}

query MyQuery {
  user {
    ...UserFragment
 }
}

query MyQuery2 {
  user {
    ...UserFragment
 }
}
```

A type will be generated for `UserFragment`. Both the data model for `MyQuery` and `MyQuery2` will have members to access the data in that fragment.
However, they will also have their own copies of all of the members in that fragment (in this case, `name`), and accessors to retrieve those fields.

With small queries, and few of them, this is not an issue. But when you have many queries, all of them using the same fragments, with large numbers of fields, this introduces a huge amount of code bloat that could be avoided.
We wouldn't be concerned about the size of this code if it wasn't because Swift is notoriously slow at compiling, and the more code we have, the more our compile-times will suffer, the more queries we have.

I would love to explore if this is something that can be changed, and if it is, I would be happy to contribute a fix :)

Thanks in advance!

**Comment by martijnwalraven** [comment]
There is a bit of a tradeoff here, and we're still exploring options, but in the current version you can avoid this by passing `--merge-in-fields-from-fragment-spreads false` to `apollo-codegen`.

**Comment by JaviSoto** [comment]
Ah! I missed that option. That's absolutely perfect. Being able to conditionally turn that on definitely works for us 👍  I'll go ahead and close this. Thank you so much!
