### ISSUE TITLE
Wrong type in generated code

### ISSUE THREAD

**Issue by conradwt** [apollographql/apollo-ios#1813]
## Bug report

In my GraphQL server, I have a `field` defined as follows:

```elixir
field :total_gross, non_null(:decimal)
```

However, I'm seeing the following in the generated code:

```swift
GraphQLField("totalGross", type: .nonNull(.scalar(String.self))),
```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.42.0
- Xcode version: 12.5
- Swift version: 5.4
- Package manager: 

## Steps to reproduce

1. define a field as a `decimal` using the Absinthe package
2. swift run ApolloCodegen downloadSchema
3. Command + B

## Further details

I'm using SwiftUI and Phoenix/Elixir for the GraphQL server.  If you require any additional information, please do let me know.

**Comment by designatednerd** [comment]
Hi! This is something you can set as an option in code generation - if you're using the Swift codegen you can set `customScalarFormat` to `.passthrough` and if you're still using Bash you can add the `--passthroughCustomScalars` flag. These are not enabled by default. 

Please let us know if that works - if it doesn't, that's a bug.

**Comment by conradwt** [comment]
@designatednerd I'm guessing that I would set it as follows:

In `main.swift`:

```swift
let codegenOptions = ApolloCodegenOptions(targetRootURL: targetRootURL, customScalarFormat: .passThrough)
```

Does the CLI not accept options at this time?

**Comment by conradwt** [comment]
@designatednerd I was unable to do the above because the designated initializer doesn't take the `customScalarFormat` parameter at this time.  Next, I tried to edit `ApolloCodeGenOptions.swift` but this file is set to `read-only` at this time.  Please advise because I'm guessing that I shouldn't be changing permissions on project files.

**Comment by AnthonyMDev** [comment]
You can make a fork or Apollo and contribute a pull request to add that parameter if you'd like. The other initializer does include that parameter. It looks like you are using the convenience initializer.

**Comment by conradwt** [comment]
@designatednerd @AnthonyMDev I'm going to close this issue because you two provided a solution. 🙏🏾🙏🏾

**Comment by AnthonyMDev** [comment]
Thanks. Would be happy to merge a pull request if you add that parameter!

**Comment by conradwt** [comment]
@AnthonyMDev Are you referring to the CLI?  If so, I would definitely like to do something similar to `Bash`.  For example,

```zsh
xcrun -sdk macosx swift run ApolloCodegen generate -passthroughCustomScalars
```

Do you recommend filing another issue as a feature request for this functionality?

**Comment by designatednerd** [comment]
This _is_ available on [this initializer](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/ApolloCodegenOptions.swift#L98), which is the designated initializer. The initializer you're working with is [this initializer](https://github.com/apollographql/apollo-ios/blob/3d8e15bc7f37482528d55eebcb34b70f678047f6/Sources/ApolloCodegenLib/ApolloCodegenOptions.swift#L139), which is a convenience initailizer.
