### ISSUE TITLE
Build phase script: No such file or directory error

### ISSUE THREAD

**Issue by siegesmund** [apollographql/apollo-ios#182]
When I try to compile using the build phase script in the guide, I get the following error:

`
.../Build/Products/Debug/Apollo/Apollo.framework/check-and-run-apollo-codegen.sh: No such file or directory
`

If I change the path in the build script from:

`$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift
`
to:

`$APOLLO_FRAMEWORK_PATH/Versions/Current/Resources/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift
`

It builds without error.

**Comment by martijnwalraven** [comment]
Ah, is this with a Mac target by any chance? The framework directory structure is different between iOS and Mac, so that would explain this.

**Comment by siegesmund** [comment]
Yep, absolutely. That makes sense. It's working fine with the workaround above. Any reason you know of why I shouldn't leave it like that?

**Comment by martijnwalraven** [comment]
No reason at all! This is how it is supposed to be set up on Mac. In fact, this should really be in the documentation.

**Comment by siegesmund** [comment]
Super! Thanks for the lightning quick reply!

**Comment by cczufish** [comment]
I have a problem when I add build phase script ,

/Apollo/Apollo.framework/check-and-run-apollo-codegen.sh: No such file or directory

why

**Comment by martijnwalraven** [comment]
@cczufish The script has been renamed after codegen has been incorporated into the new Apollo CLI. See [here](
https://www.apollographql.com/docs/ios/installation.html#adding-build-step) for the correct build phase script.

**Comment by TuanLeo92** [comment]
@cczufish 
Expand Generate Apollo GraphQL API in Build Phases
Replace ["${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift]
to ["${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift]

**Comment by MrMatten** [comment]
I have just updated and changed it but get a `line 4: /Apollo/scripts/run-bundled-codegen.sh: No such file or directory`.
I have checked and the file is there.
