### ISSUE TITLE
issue with API.o when i try to upload the app to app store

### ISSUE THREAD

**Issue by iishabrawy** [apollographql/apollo-ios#183]
after complete my app .
try to upload it to app store and in every time i try to upload it xcode say 
![screen shot 2017-11-21 at 9 40 01 am](https://user-images.githubusercontent.com/6254386/33060627-8eeb9852-cea1-11e7-9322-09346b300865.png)

and try to remove the pod and install it again . the error exist every time i try 
and remove the CFBundleExecutable for Apollo and the error exist

**Comment by designatednerd** [comment]
@iishabrawy Were you ever able to find a solution for this? I'd like to close this as outdated, but I'd like to confirm that you were able to find a solution. Thanks!

**Comment by designatednerd** [comment]
Given that I haven't heard back in a couple of weeks, I'm going to close this out as outdated. Please open a new issue if you're still having problems with this!
