### ISSUE TITLE
"The Network connection was lost" error when app goes from background to foreground

### ISSUE THREAD

**Issue by mustafaysil** [apollographql/apollo-ios#1841]
Hi @designatednerd, 
I have a recursive method for listening to payment status. When application redirect to another application for pay transaction user there complete transaction after than redirect to my application.
I get an "The Network connection was lost" error when app goes from background to foreground 
I'm pretty sure I don't have a problem with the internet .
```
Task <E45C7913-3201-4565-941A-1D85614B3593>.<21> finished with error [-1005]
 Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." 
 UserInfo={_kCFStreamErrorCodeKey=53,
 NSUnderlyingError=0x283a20cc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" 
 UserInfo={NSErrorPeerAddressKey=<CFData 0x2817f94a0 [0x1ffe21b20]>{length = 16, capacity = 16,
  bytes = 0x100201bb36e69d800000000000000000}, _kCFStreamErrorCodeKey=53,
   _kCFStreamErrorDomainKey=1}}, 
   _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask
    <E45C7913-3201-4565-941A-1D85614B3593>.<21>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
  "LocalDataTask <E45C7913-3201-4565-941A-1D85614B3593>.<21>"
), NSLocalizedDescription=The network connection was lost.,
 NSErrorFailingURLStringKey=https://API_DOMAIN/, 
 NSErrorFailingURLKey=https://API_DOMAIN/, _kCFStreamErrorDomainKey=1}
```
Thank you for helping 🙏🏼

**Comment by designatednerd** [comment]
Generally if you have a URL request that's continuing as your app goes to the background, Apple will kill it. I'd have thought it would get a different error, but it's probably worth looking at the timing of your requests as they work to kick things to the other app and then come back as a place to start.

**Comment by mustafaysil** [comment]
@designatednerd Thank you so much for your answer.
I understood that this error is caused by apple.
My problem is solved when I run my recursive method inside a background task 
```
func sendDataToServer( data : NSData ) {
   // Perform the task on a background queue.
   DispatchQueue.global().async {
      // Request the task assertion and save the ID.
      self.backgroundTaskID = UIApplication.shared.
                 beginBackgroundTask (withName: "Finish Network Tasks") {
         // End the task if time expires.
         UIApplication.shared.endBackgroundTask(self.backgroundTaskID!)
         self.backgroundTaskID = UIBackgroundTaskInvalid
      }
            
      // Send the data synchronously.
      self.sendAppDataToServer( data: data)
            
      // End the task assertion.
      UIApplication.shared.endBackgroundTask(self.backgroundTaskID!)
      self.backgroundTaskID = UIBackgroundTaskInvalid
   }
}
```
https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/extending_your_app_s_background_execution_time

**Comment by designatednerd** [comment]
Awesome, thank you for sharing your solution as well!
