### ISSUE TITLE
Optional fields are handled differently compared to Android

### ISSUE THREAD

**Issue by tonythebully** [apollographql/apollo-ios#185]
In a call where the schema has an optional field, when I perform the operation with apollo where a field is optional, the request would be sent with the field within the JSON, but with null as the value of the said optional field.

However, on Android, that field would simply be removed from the JSON entirely, is this an expected behaviour?

This is causing some issues with type checking when the JSON is received on the server side.

**Comment by martijnwalraven** [comment]
GraphQL actually differentiates between an input value not being present and a value being set to `null` (http://facebook.github.io/graphql/October2016/#sec-Null-Value). In a mutation that updates an object for example, not providing a value for a field could mean not modifying that field, while `null` would clear the current value.

We already use double optionals for input object fields, which allows you to do:

```swift
input.caption = "foo"
input.caption = nil // don't include field
input.caption = .some(nil) // include explicit null
```

We should probably use double optionals for optional field arguments as well.

Can you give an example of the type of operation you're thinking of to see if this would solve it?

**Comment by tonythebully** [comment]
Ah I see, so basically i need to figure out how the null should be handled before performing the mutation call whether it is with the field as an argument of the method (which sets it as null), or call the mutation method without the argument (which removes the field from the post entirely)?

For my current use case, I effectively have a page where it shows the user all the details about an object: 
1.So going into the page, it first gets the the object and displays everything about it.
2.User changes something on the UI, I change the object stored from the initial query, then send the whole object back

From you answer I suppose I can look through my whole object and decide on how i should call the method towards the end based on which field contains a null? Am i understanding this right?

**Comment by tonythebully** [comment]
Maybe this would be more clear:
I have this object
```
Object {
   field1
   field2
   field3
}
```
when I query the above object, I get:
```
"Object": {
   "field1": foo,
   "field2": bar,
   "field3": null
}
```
user then change field 2 to something else:
```
"Object": {
   "field1": foo,
   "field2": somethingElse,
   "field3": null
}```

**Comment by martijnwalraven** [comment]
> so I would be looking at maybe 20 different ways the call the same method based on the amount of optional fields within optional nested fields

I'm not sure I understand what you mean by that. 

If the mutation takes an input object, you would only set the fields that you actually wanted to change. So in your example:

```swift
inputObject.field2 = "somethingElse"
```

That would send `{ "field2": "somethingElse" }` to the server. 

If you wanted to explicitly set a field to `null`, you would do:

```swift
inputObject.field2 = "somethingElse"
inputObject.field3 = .some(nil)
```

Which would send `{ "field2": "somethingElse", "field3": null }` to the server.

**Comment by tonythebully** [comment]
Ok I actually get it now, thanks for clarifying
