### ISSUE TITLE
Reconnect failed after restart server

### ISSUE THREAD

**Issue by zibozeng** [apollographql/apollo-ios#1850]
## Bug report

After restarting server, the reconnection of client sent via the method "resumeWebSocketConnection(autoReconnect: true)" can't be made. I also tried closeConnection of client, but still.

btw, it was works on version 0.42, in which i don't need to manually call that resume method, cause i used "updateHeaderValues" to reconnect. Not sure whether this causes the problem..

## Versions

- `apollo-ios` SDK version: 0.44
- Xcode version:  12.51
- Swift version:  5

**Comment by zibozeng** [comment]
just found the solution. my bad not noticing that

**Comment by designatednerd** [comment]
Hi - can you share a couple more details please? 

- What happens when you try to reconnect - absolutely nothing, an error, or something else? 
- When you say "restarting server", do you mean that somewhere someone rebooted your server? If this is what you mean, are you able to make an initial connection with a different client (for example, you can't reconnect with the already-running simulator but you can make a new connection with a newly launched simulator after the reboot).

**Comment by zibozeng** [comment]
> Hi - can you share a couple more details please?
> 
> * What happens when you try to reconnect - absolutely nothing, an error, or something else?
> * When you say "restarting server", do you mean that somewhere someone rebooted your server? If this is what you mean, are you able to make an initial connection with a different client (for example, you can't reconnect with the already-running simulator but you can make a new connection with a newly launched simulator after the reboot).

first question: it seems absolutely nothing happened, I tried debug it, and what i found is when i call this method "resumeWebSocketConnection(autoReconnect: true)" for reconnection, it did call the connect function in Starscream instance,  but nothing received, which is supposed to receive something, error or whatever if it fails, but nothing got.

second question: Yes, I manually restart my nodeJS server after I modify it, reconnection works at version 0.42, but after I updated it to the latests in which i found it's been added couple lines for that method mentioned above，the issue occurs.  And i think, whenever need to reconnect, it will work if i re-init a new instance of client, and connect it. But it's not elegant right?  So i hope the reconnecting will be working as before.

**Comment by designatednerd** [comment]
Hm...I'm not entirely sure of the under-the-hood workings of Starscream but it does occur to me that if you're trying to restart a connection, there may be some kind of assumption that the server hasn't rebooted. Are you calling `websocket.disconnect()` when you reboot the server, or just waiting for the connection to error out?

**Comment by zibozeng** [comment]
i called websocket.closeConnection() before reconnect. And there is no way to call websocket.disconnect(), as it wasn't been exposed. Actually, because you just mentioned that Starscream doesn't assume the server reboot, I choose to re factor the codes of this part. Sorry for bothering because of my bad knowledge of backend. So every time client loses it connection, the client should establish a new connection with a new instance of websocket client? or is there any way to detect whether the disconnection is due to the server restart, so the client end could made decision which way to go to reconnect?

**Comment by zibozeng** [comment]
i did notice that IOS will reconnect automatically after i restart server for about like 3 seconds. but the oxs will not.

**Comment by designatednerd** [comment]
I'll be honest, I've got no idea why macOS would behave differently in this way than in iOS, it's almost certainly something under the hood with Starscream. For what it's worth we're going to be reverting to an older version of Starscream because folks have had a _lot_ of problems since we switched to the 4.x branch.

**Comment by zibozeng** [comment]
> I'll be honest, I've got no idea why macOS would behave differently in this way than in iOS, it's almost certainly something under the hood with Starscream. For what it's worth we're going to be reverting to an older version of Starscream because folks have had a _lot_ of problems since we switched to the 4.x branch.

OK.
