### ISSUE TITLE
Input struct parameters with a default value should be generated with the default value

### ISSUE THREAD

**Issue by hiltonc** [apollographql/apollo-ios#1853]
## Bug report

Input struct parameters are generated differently on iOS vs. Android. If the meaning of the default value is "this is what the server will assume if you provide no value", the iOS behavior seems correct. If the meaning is "this is the value the client should provide by default", the Android behavior seems correct.

## Versions

- `apollo-ios` SDK version: 0.44.0
- Xcode version: 12.5.1
- Swift version: 5.4
- Package manager: 5.2

## Steps to reproduce

We have the following (abbreviated) in our `schema.json`:

```
{
  "kind": "INPUT_OBJECT",
  "name": "AuthenticateInput",
  "description": null,
  "fields": null,
  "inputFields": [
    {
      "name": "email",
      ...
    },
    {
      "name": "password",
      ...
    },
    {
      "name": "udid",
      ...
    },
    {
      "name": "rememberMe",
      "description": null,
      "type": {
        "kind": "SCALAR",
        "name": "Boolean",
        "ofType": null
      },
      "defaultValue": "false"
    }
  ],
  "interfaces": null,
  "enumValues": null,
  "possibleTypes": null
}
```

This is the initializer of the `AuthenticateInput` struct on iOS. Notice that the default value for `rememberMe` is `nil` (even though the schema specifies `false`).

```
public init(email: String, password: String, udid: String, rememberMe: Swift.Optional<Bool?> = nil) {
```

This is the initializer of the `AuthenticateInput` data class on Android. Notice here that the default value for `rememberMe` is `Input.optional(false)` (essentially `false`).

```
data class AuthenticateInput(
  val email: String,
  val password: String,
  val udid: String,
  val rememberMe: Input<Boolean> = Input.optional(false)
) : InputType {
```

The behavior appears to be inconsistent.

## Further details

I would prefer the iOS behavior because it causes fewer issues in our setup with staging and production environments when a new parameter is added to an old input with a default value. Either way I'm hoping for consistency.

**Comment by hiltonc** [comment]
Cross-posted at https://github.com/apollographql/apollo-android/issues/3194

**Comment by calvincestari** [comment]
Hi @hiltonc 👋🏻 - I've read through the [cross-posted conversation in apollo-android](https://github.com/apollographql/apollo-android/issues/3194) and it seems like there isn't any action to take here in apollo-ios. Is that correct, did you get the answers you're looking for?

**Comment by hiltonc** [comment]
Yes, it looks like Android will change behavior, so we're good on iOS. Thank you!

**Comment by martinbonnin** [comment]
👍  Indeed, we will update that behaviour for Apollo Android 3.0
