### ISSUE TITLE
Handle an unexpected message/event with incorrect identifier

### ISSUE THREAD

**Issue by gondar-lvovich** [apollographql/apollo-ios#1860]
When receive message (in _processMessage_ in _WebSocketTransport_) function checks identifier in subscribers
and sends exception to '_notifyErrorAllHandlers(websocketError)_' and all subscriptions become invalid
Why? It seems better way just ignore message which have incorrect identifier. In this case we have bad relation with server side. One incorrect message could trigger a lot of errors in valid subscriptions 
So my question is 'why do you keep this logic for subscriptions with unexpected identifiers?'
Thanks

**Comment by AnthonyMDev** [comment]
@designatednerd Do you have any idea why this is set up as it currently is? I don't have a ton of context on this, but could/should we send this error to a new `WebSocketTransportDelegate` function that handles generic errors that are not tied to a specific subscription?

I don't think we want to suppress this completely, but does it make sense for it to terminate all running subscriptions?

**Comment by designatednerd** [comment]
@gondar-lvovich can you link to the specific line you're talking about here? I _think_ it's [here](https://github.com/apollographql/apollo-ios/blob/b17ae4cef6e78d60913b33b821ff6ec32ce38c38/Sources/ApolloWebSocket/WebSocketTransport.swift#L161) but I would like to be sure before I go into a more thorough answer. 

As far as I can see, `notifyErrorAllHandlers` only actually [_notifies_ the error handlers](https://github.com/apollographql/apollo-ios/blob/b17ae4cef6e78d60913b33b821ff6ec32ce38c38/Sources/ApolloWebSocket/WebSocketTransport.swift#L197), it doesn't actually cause the subscription to become invalid unless you're invalidating on error in your handler.

**Comment by gondar-lvovich** [comment]
@designatednerd Hi. Yes, it is correct.
I mean that every subscription has own error handler with specific logic and in my case problem is usage of RxApollo.
If one of subscriptions handle error, current logic will send it to handler and 'on error' rx framework trigger dispose

So I see that problem is that Apollo sends errors on unexpected message and on framework side everything is correct but if there is step for handle could be problems.Subscription receives an error that is not relevant

At this point, there are no more questions. Thanks a lot! As a solution now for me is an additional custom implementation of rx with the apollo

**Comment by designatednerd** [comment]
OK cool - to be clear we do not have a directly supported Rx implementation, but I would definitely recommend checking what the error is before just dumping off to `dispose`.
