### ISSUE TITLE
Update ROADMAP.md

### ISSUE THREAD

**Issue by jefflopes** [apollographql/apollo-ios#1863]
@designatednerd Following the instructions in the document and requesting an update to the roadmap. I'm particularly interested in where some of the caching improvements stand. Thanks for all your great work!

**Comment by designatednerd** [comment]
Good timing on the checkin, we're meeting on this this week!

**Comment by jefflopes** [comment]
Great thanks!

**Comment by calvincestari** [comment]
@jefflopes, [the roadmap](https://github.com/apollographql/apollo-ios/blob/main/ROADMAP.md) has been updated.
