### ISSUE TITLE
Crash when logging a request response for a custom scalar without `JSONEncodable` conformance

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#1870]
Moving to its own issue from #1255: 

From @groue: 
> I got this "Optional is only JSONEncodable if Wrapped is" fatal error in the following scenario:
>
> - The build phase generates Swift code with the --passthroughCustomScalars option
> - One of my custom scalars is a type that implements Apollo.JSONDecodable
> - Apollo crashes as it is logging a request response 💣
> A fix is to also add the JSONEncodable conformance to the custom scalar (so that it can be logged).
> 
> Feature request: please have the SDK learn how to log types that do not adopt JSONEncodable. I do not need this functionality in my custom scalar type.

The custom scalar code in question: 

```swift
extension GraphQL {
    public struct Base64: JSONDecodable {
        public let data: Data
        public init(jsonValue value: JSONValue) throws {
            let string = try String(jsonValue: value)
            guard let data = Data(base64Encoded: string) else {
                throw JSONDecodingError.couldNotConvert(value: value, to: Base64.self)
            }
            self.data = data
        }
    }
}
```

**Comment by designatednerd** [comment]
@groue Could please you help me understand what you mean when you say this is getting logged? Right now all of our explicit logging is confined to our `ApolloCodegenLib` library, but it sounds like you're hitting this with our main library. Thank you!

**Comment by AnthonyMDev** [comment]
I was looking at this today and I’m pretty sure I know what’s going on here. Thinking about how to tackle this one right now. Will update in a day or two.

**Comment by AnthonyMDev** [comment]
Yeah, I don't think this is actually entirely related to what I was looking at. @groue we need more information on what your logging code looks like.

**Comment by groue** [comment]
Hello @AnthonyMDev, @designatednerd,

The crash is indeed in my app, since there is the code that requests JSON serialization of operation results:

```swift
private func logGraphQLOperation<Operation: GraphQLOperation>(_ operation: Operation, requestUUID: String, success data: Operation.Data) {
    // Strip "__" prefixed keys
    func cleanup(_ value: AnyObject) -> AnyObject {
        if let array = value as? [AnyObject] {
            return array.map { cleanup($0) } as AnyObject
        } else if let dict = value as? [String: AnyObject] {
            return Dictionary(uniqueKeysWithValues: dict.compactMap({ (key: String, value: AnyObject) -> (key: String, value: AnyObject)? in
                if key.hasPrefix("__") { return nil }
                return (key: key, value: cleanup(value))
            })) as AnyObject
        } else {
            return value
        }
    }
    
    var dataRepresentation: String?
    if
        // Turn GraphQL input (contains weird objects) into JSON data
        let jsonData = try? JSONSerializationFormat.serialize(value: data.resultMap),
        // Turn JSON data into a regular dictionary
        let rawValue = try? JSONSerialization.jsonObject(with: jsonData, options: []),
        // Cleanup the regular dictionary from "__" prefixed keys
        case let cleanValue = cleanup(rawValue as AnyObject),
        // Turn clean dictionary into JSON data
        let cleanJSON = try? JSONSerialization.data(withJSONObject: cleanValue, options: [.sortedKeys])
    {
        // Turn JSON data into JSON string
        dataRepresentation = String(data: cleanJSON, encoding: .utf8)
    }
    
    os_log(
        "✅ %{public}@ %@", log: log, type: .debug,
        requestUUID,
        dataRepresentation ?? "")
}
```

I'm sorry: Apollo is not responsible for this crash.

**Comment by calvincestari** [comment]
Thanks for following up @groue.
