### ISSUE TITLE
Allow GET requests

### ISSUE THREAD

**Issue by kishinmanglani** [apollographql/apollo-ios#189]
GraphQL allows requests to be served over GET and POST. Seems like apollo-ios only supports POST

**Comment by deveniro** [comment]
Hi @kishinmanglani, 
I'm interacting with an external GraphQL server and I'm getting an error message saying: "HTTP 405 Method Not Allowed", possibly it's related to your problem. The external server probably supports only GET requests, but it seems I can't change the method type in apollo. Have you managed to overcome this issue?

**Comment by designatednerd** [comment]
@kishinmanglani Would #572 address this for you?

**Comment by kishinmanglani** [comment]
I was able to accomplish this by using a custom `NetworkTransport`, but looks like `FetchOptions` would make that a lot easier!

**Comment by designatednerd** [comment]
Support for this has been added in v0.11.0 - just pass in the parameter to `useGETForQueries` when setting up your `HTTPNetworkTransport`!
