### ISSUE TITLE
Can I read mutation response from cache ??

### ISSUE THREAD

**Issue by Saranya-Siva** [apollographql/apollo-ios#1890]
### Discussed in https://github.com/apollographql/apollo-ios/discussions/1888

<div type='discussions-op-text'>

<sup>Originally posted by **Saranya-Siva** August  2, 2021</sup>
I am trying to read mutation response from cache using a custom interceptor. But Mutation response is not caching properly when the query variables has a email id parameter in it. When I check db for the records, it's not updating the MUTATION_ROOT key's value.</div>

**Comment by designatednerd** [comment]
Pretty sure this is essentially a duplicate of #1071 - if it's a valid email, it's got a `.` in the `blah.com`, and that's going to make the cache key get split weirdly. Solution is still probably for us to add a way to use an alternative cache key separator.

**Comment by calvincestari** [comment]
This should be fixed in the latest main release - [0.51.2](https://github.com/apollographql/apollo-ios/releases/tag/0.51.2). Please let us know if it is still an issue for you - thanks.
