### ISSUE TITLE
Distribute Apollo using .xcframework(s) instead of Swift Package Manager

### ISSUE THREAD

**Issue by chris-h-mox** [apollographql/apollo-ios#1895]
## Feature request

Hi, would you consider providing an option to integrate Apollo using one or more .xcframework's instead of SPM?

## Motivation

SPM can be generally unreliable

## Proposed solution

Distribute Apollo using .xcframework as well as SPM

Thankyou very much for your time :)

**Comment by calvincestari** [comment]
> SPM can be generally unreliable

@chris-h-mox would you mind sharing some of the frustrations you've had with SPM.

**Comment by chris-h-mox** [comment]
Thanks @calvincestari :) I find i have to delete my DerivedData folder quite regularly to keep SPM functioning. Many friends and colleagues report similar issues. This is no fault of Apollo, this is simply Xcode being a bit immature in this area.

**Comment by AnthonyMDev** [comment]
@chris-h-mox Apollo currently supports [Carthage](https://github.com/Carthage/Carthage), which I believe is basically what you are asking for.

Please look into that and let us know if it serves your purpose. If not, maybe we can get a better understanding of how you would prefer to see Apollo distributed for your needs.

**Comment by chris-h-mox** [comment]
Thanks for the suggestion @AnthonyMDev I'll look into that, i see Carthage is mentioned here: https://www.apollographql.com/docs/ios/installation/#installing-the-apollo-framework

**Comment by chris-h-mox** [comment]
Thanks @AnthonyMDev I roughly followed the instructions (changed a little to reflect more modern Carthage usage) and it worked perfectly. For future reference, this worked:
