### ISSUE TITLE
Cannot query field {field} on type "Mutation". (Codegen)

### ISSUE THREAD

**Issue by ghattrell** [apollographql/apollo-ios#1896]
## Bug report

Codegen is failing for me, claiming that I cannot make a mutation that is specified in my GraphQL schema. The mutation runs perfectly fine in the graphQL playground, and I have downloaded the latest version of the schema and can see the mutation in the schema.json file.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.45.0
- Xcode version: 12.5.1
- Swift version: 5
- Package manager: Swift package manager

## Steps to reproduce

Simply rebuild the project with the mutation added to the .grahql file and the build fails with a GraphQL validation error.

<img width="1394" alt="Screenshot 2021-08-06 at 10 35 47" src="https://user-images.githubusercontent.com/8737504/128491764-5b82a9a5-d20c-4528-8a5e-f81f22a23a4f.png">

Here is the query running perfectly well in the GraphQL playground

![Screenshot 2021-08-06 at 10 29 24](https://user-images.githubusercontent.com/8737504/128490934-36edb761-4f0a-4c74-ac20-f3115d6f0a94.png)

Here is the mutation in the schema.

<img width="1788" alt="Screenshot 2021-08-06 at 10 39 06" src="https://user-images.githubusercontent.com/8737504/128491490-6dbddd12-dde4-4324-86cb-b3eaa408c10d.png">

And finally the build config which shows it targeting that schema.

<img width="1077" alt="Screenshot 2021-08-06 at 10 41 54" src="https://user-images.githubusercontent.com/8737504/128491554-0987fd99-beb7-4dda-8aa4-11cb02ae54ad.png">

**Comment by calvincestari** [comment]
@ghattrell are you able to share the `idapp.graphql` file referenced in the error? Line 75 is where the error is being highlighted.

**Comment by ghattrell** [comment]
Yes absolutely.

![Screenshot 2021-08-06 at 17 44 37](https://user-images.githubusercontent.com/8737504/128544970-32db3024-1c78-431a-8592-b23bcb9e57e0.png)

**Comment by AnthonyMDev** [comment]
Everything looks in order here. I'm not sure what's going wrong... This is more of an issue with the apollo-tooling or even possibly graphql-js itself. I'll see if I can pull someone else in to help us look into this more.

**Comment by calvincestari** [comment]
Is this still an issue for you @ghattrell, did you manage to find the problem?

**Comment by ghattrell** [comment]
Sorry, was on holiday! Yes it is still a problem for me, I can't work it out, but have just moved on to other tickets for the moment.

**Comment by ghattrell** [comment]
Thank you for looking into it for me.

**Comment by calvincestari** [comment]
@ghattrell - please try the latest 1.0 alpha release and check whether this is still an issue for you. If it is then please provide us with the full schema so we can debug - thanks.
