### ISSUE TITLE
Xcode not finding apollo-codegen in Run Script phase

### ISSUE THREAD

**Issue by bmunge** [apollographql/apollo-ios#190]
Not sure if this is a real issue or a problem with my node setup. Anyways, whenever the script phase would run I received an error that it couldn't find apollo-codegen. I was able to execute it fine in terminal, but not in Xcode. I resolved it by adding this to the start of the script phase so Xcode could locate my node-modules.

`source ~/.bash_profile`

Thanks!

**Comment by designatednerd** [comment]
Yeah this seems like it could be helpful for a couple issues people are running into on CI as well.

**Comment by designatednerd** [comment]
I've added this note to our docs in #708 - I'll close this out once that's merged.

**Comment by designatednerd** [comment]
Merged!
