### ISSUE TITLE
ApolloClient doesn't use the provided callbackQueue in clearCache.

### ISSUE THREAD

**Issue by isaacressler** [apollographql/apollo-ios#1900]
## Bug report

The `ApolloClient`'s implementation of `clearCache(callbackQueue:completion:)` from `ApolloClientProtocol` does not use the callbackQueue.

It is currently implemented like this:
```Swift
public func clearCache(callbackQueue: DispatchQueue = .main,
                       completion: ((Result<Void, Error>) -> Void)? = nil) {
  self.store.clearCache(completion: completion)
}
```

Which drops the callbackQueue without ever using it.

I would expect the implementation to be like this:
```Swift
public func clearCache(callbackQueue: DispatchQueue = .main,
                       completion: ((Result<Void, Error>) -> Void)? = nil) {
  self.store.clearCache(callbackQueue: callbackQueue, completion: completion)
}
```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.45.0 (But wasn't changed in 0.46.0 from what I can see)
- Xcode version: All
- Swift version: All
- Package manager: SPM

## Steps to reproduce

Call
```Swift
ApolloStore.clearCache(callbackQueue:completion:)
```
with a callbackQueue that is not `.main`.

## Further details

If this is correct and I'm not missing anything I'm happy to submit a PR with my proposed change (or something different if I'm missing a better solution).

**Comment by calvincestari** [comment]
@isaacressler - thanks for raising this issue. Your corrected implementation looks correct; if you're happy to submit a PR we can merge it in. I'm trying to figure out how we can get a test in to ensure we've got this covered in the future.

**Comment by calvincestari** [comment]
@isaacressler - here's a [PR to introduce tests for this](https://github.com/apollographql/apollo-ios/pull/1901). I'll rebase once the fix PR is merged.
