### ISSUE TITLE
Upload file with progress

### ISSUE THREAD

**Issue by wongzigii** [apollographql/apollo-ios#1902]
How to upload file with progress? The upload function in ApolloClient doesn't have a progress closure.

**Comment by AnthonyMDev** [comment]
We highly recommend uploading files using another mechanism and then setting up your mutations to take an identifier to access the uploaded data elsewhere. See: https://www.apollographql.com/docs/ios/mutations/#an-important-caveat-about-file-uploads

File uploads with GraphQL are overly complicated currently, and for clients, it's easier to bypass them. Our file upload API is not very strong right now, and we do not have a progress closure included currently.

We would be very happy to look at a PR to merge this functionality if you would like to look into building it, but it's not on our roadmap at the moment to work on this anytime soon. Perhaps after we finish the 1.0 release, we could look into this, but if you need it sooner, we'd love to have you contribute to apollo!

**Comment by ypleskach** [comment]
Is the recommendation to use another mechanism for file upload still applicable?
Just wondering whether file upload with progress is added to the roadmap.
