### ISSUE TITLE
Can't update to 0.47.0 using CocoaPods

### ISSUE THREAD

**Issue by CureleaAndrei** [apollographql/apollo-ios#1910]
Hello, i tried updating to 0.47.0 (from 0.46.0) but cocoa can't find this version. I cleaned my cocoa cache, i tried installing in a new project and it is still not working. I did a pod search command but 0.46.0 is the last version that i can find.
When i force the version using pod 'Apollo', '~> 0.47.0' i get the following error : 

-------------
[!] CocoaPods could not find compatible versions for pod "Apollo":
  In Podfile:
    Apollo (~> 0.47.0)

None of your spec sources contain a spec satisfying the dependency: `Apollo (~> 0.47.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
-------------

Notes: It's not a typo in my podfile.

Also when searching on https://cocoapods.org for Apollo it shows 0.46.0 as the last version, until you actually click it, then it opens a page with 0.47.0. 

Can you check it out? Have I done something wrong? Or it is a bug ?

Thanks and I look forward to hearing from you!

**Comment by SzymonMatysik** [comment]
I have the same issue.

**Comment by calvincestari** [comment]
Hi 👋🏻 - thanks for letting us know there is an issue with this. We're busy looking into the Cocoapods release last night and see the same thing as you've noticed.
* Searching for Apollo from cocoapods.org shows **0.46.0**
* The pod page shows **0.47.0** (https://cocoapods.org/pods/Apollo)
* The repo spec shows 0.47.0 (https://github.com/CocoaPods/Specs/blob/master/Specs/a/6/c/Apollo/0.47.0/Apollo.podspec.json)

Could require a local spec repo update.

**Comment by designatednerd** [comment]
There's definitely something fishy going on here - when I do `pod outdated`, I'm told the latest version is 0.46.0, even after doing a `pod repo update`. Reaching out to the CP folks to see if anyone knows what's gone wrong here.

**Comment by CureleaAndrei** [comment]
Yeah, pod repo update is still not working, but I've noticed something: when doing pod repo update, in the process in terminal  it shows that the HEAD is at the correct version 0.47.0. But still cannot install it. 

Also noticed that using pod try Apollo seems to download the correct version for trying it.

**Comment by calvincestari** [comment]
A workaround is to instruct cocoapods to go directly to the apollo-ios repo and avoid the cocoapods spec/CDN infrastructure. I've tried this in a fresh iOS project and it fetches `0.47.0` as expected. You will need to change your `pod 'Apollo'` line to be 
```
pod 'Apollo', :git => 'https://github.com/apollographql/apollo-ios.git'
```

I view this as a temporary solution until we've figured out what is wrong with the standard way of pulling in a pod. If you commit this to your project repo don't forget to keep checking back here for a full resolution.

**Comment by AnthonyMDev** [comment]
It also works if you use the direct spec repository via git rather than the CDN. This is really slow on the initial download of the spec repo though.

Adding `source 'https://github.com/CocoaPods/Specs.git'` at the top of your pod file will do this. And then `pod Apollo` will download version `0.47.0`

This is also a temporary workaround. We have reached out to the Cocoapods team about how to resolve the CDN issue.

**Comment by CureleaAndrei** [comment]
Thanks for the fast responses, it works as you said in a project. My use case is that i use Apollo inside a private pod as a dependency where i cannot use :git => 'https://github.com/apollographql/apollo-ios.git'. I tried specifying source 'https://github.com/apollographql/apollo-ios.git' inside the project podfile where i test my library and it still not worked. I am trying the second suggested workaround using source 'https://github.com/CocoaPods/Specs.git' inside project podfile, but as you said it is really slow and i am still waiting.

If you have any suggested approach for using this inside a private pod, I would be gratefully. Thanks!

P.S: I would edit this if it works with the source 'https://github.com/CocoaPods/Specs.git'.

**Comment by AnthonyMDev** [comment]
Looks like the Cocoapods team found the issue on their end and are sorting it out now also! We Also need to push a new patch anyways, since we made a minor error in the podspec. I'm getting on that now!

**Comment by AnthonyMDev** [comment]
Looks like the CDN is working again now! Thanks @orta!

**Comment by SzymonMatysik** [comment]
Is this just me or the same issue exist on 0.47.1?

**Comment by CureleaAndrei** [comment]
Hi, I was about to ask you about the missing files from the ApolloWebSocket, but i see you fixed them in the new release. The 0.47.0 is now working with cocoapods, but the new version 0.47.1 is not. I assume that there is some propagation delay in cocoapods ? or the issue still persist ? Still trying on my end.

**Comment by AnthonyMDev** [comment]
@SzymonMatysik Try it again now. The CDN might have taken a little time to propagate the new version. If it's still a problem let us know ASAP.

**Comment by SzymonMatysik** [comment]
@AnthonyMDev Everything working fine now! Thanks!
