### ISSUE TITLE
Provide Type Erasure for GraphQLOperation

### ISSUE THREAD

**Issue by racer1988** [apollographql/apollo-ios#1915]
## Feature request

Following https://community.apollographql.com/t/how-to-wrap-apolloclient-in-a-network-facade-while-graphqloperation-has-associatedtype-requirements/1163

I realized that the main limitation of `GraphQLOperation` is the impossibility to type erase it.

I would like to able to use `GraphQLOperation`s in a mapper, factory or switch with the possibility to send a generic request to the network. 

## Motivation

See https://community.apollographql.com/t/how-to-wrap-apolloclient-in-a-network-facade-while-graphqloperation-has-associatedtype-requirements/1163 for a very detailed motivation of the feature request.

It's currently impossible to not use concrete types of Operations.

## Proposed solution

I don't know the reasoning behind the current choice but at the moment the associatedType `Data` is satisfied in the concrete class by the following:

`public struct Data: GraphQLSelectionSet {`

which is not even used directly in the Operation itself, but used to map the `GraphQLResult`

```
public struct GraphQLResult<Data>: Parseable {
  /// The typed result data, or `nil` if an error was encountered that prevented a valid response.
  public let data: Data?
```

I would like to know if it would be possible to restructure this (I don't have a working solution) in order to avoid the associatedType obligation of the request

```
public protocol GraphQLOperation: class {
  var operationType: GraphQLOperationType { get }

  var operationDefinition: String { get }
  var operationIdentifier: String? { get }
  var operationName: String { get }

  var queryDocument: String { get }

  var variables: GraphQLMap? { get }

  associatedtype Data: GraphQLSelectionSet
    
    // Insert Data as part of the protocol
    var returnType: Data.Type { get }
}
```

so that it would be possible to type erase the operation

```
class AnyGraphQLOperation<U>: GraphQLOperation {
    typealias Data = U
    
    private let _returnType: U.Type
    
    
    init<Base: GraphQLOperation>(base : Base) where Base.Data == U {
        _returnType = base.returnType
        
        operationDefinition = base.operationDefinition
        operationType = base.operationType
        operationIdentifier = base.operationIdentifier
        operationName = base.operationName
        queryDocument = base.queryDocument
        variables = base.variables
    }
    
    var operationType: GraphQLOperationType
    
    var operationDefinition: String
    var operationIdentifier: String?
    var operationName: String
    
    var queryDocument: String
    
    var variables: GraphQLMap?
    
}
```

## Outstanding Questions

I am also happy with an explanation on how to avoid this issue altogether.
I currently I don't see a solution to choose across multiple Operations in a Generic way:

even this is not possible right now:

```
let operation: GraphQLOperation
        
        if true {
            operation = AllCommentsQuery(collectionId: "123")
        } else {
            operation = AddCommentToCollectionMutation(collectionId: "123", commentText: "asd")
        }
        
        transport.send(operation: operation, completionHandler: completion)
```

because:

`Protocol 'GraphQLOperation' can only be used as a generic constraint because it has Self or associated type requirements`

and

`Protocol 'GraphQLOperation' as a type cannot conform to the protocol itself`

I know that associatedType protocols cannot be used as protocols directly due to the compiler being unable to figure out the underlying type at runtime, but right now there is no workaround for a non-concrete use of GraphQL requests

**Comment by AnthonyMDev** [comment]
Thanks for the conversation starter. I'm not sure what your exact use case is here, but trying to use the protocol directly is usually not the best approach. Though it may seem more simple and direct, it often leads to more unsafe code at your call sites and less ability for the compiler to optimize your code.

Depending on your use case, making your factory methods generic themselves might work out. Though it rarely actually provides value, you might also try experimenting with [Opaque Return Types](https://www.swiftbysundell.com/articles/opaque-return-types-in-swift/) to see if that can help you solve the problem.

FWIW, you don't need the `returnType` variable on the protocol in order to make your `AnyGraphQLOperation`. This code should compile just fine.

```swift
class AnyGraphQLOperation<U: GraphQLSelectionSet>: GraphQLOperation {
    typealias Data = U

    init<Base: GraphQLOperation>(base : Base) where Base.Data == U {
        operationDefinition = base.operationDefinition
        operationType = base.operationType
        operationIdentifier = base.operationIdentifier
        operationName = base.operationName
        queryDocument = base.queryDocument
        variables = base.variables
    }

    var operationType: GraphQLOperationType

    var operationDefinition: String
    var operationIdentifier: String?
    var operationName: String

    var queryDocument: String

    var variables: GraphQLMap?

}
```

**Comment by racer1988** [comment]
Please see the forum post for a very detailed explanation on what is the
use case.

In short:  a network facade mapping over multiple clients and tech

**Comment by AnthonyMDev** [comment]
I just replied with a possible solution for you on the forum post! Hope that helps. I don't think we intend to add baked in type erasure structures to the library, so I'm going to close this issue. But I am happy to continue helping you figure out the right solution for your problem in the Discord forum post.

**Comment by racer1988** [comment]
@AnthonyMDev I added more info on the forum post.

Basically could you explain me how to use Apollo SDK without using `ApolloClient` everywhere in my app as a singleton?
Currently is impossible to use Apollo SDK without exposing your whole SDK to the entire Application or am I wrong


Example

```
class MyNetwork {

    private let apollo: ApolloClient = ApolloClient(...)

   func send(request: ???????) {
      apollo.fetch(request)
   }

}

**Comment by racer1988** [comment]
basically what the SDK is missing is a way to generate a usable protocol from a `GraphQLOperation` in the same way as Alamofire does [here](https://github.com/Alamofire/Alamofire/blob/c38feeb32cd728928da82ecec6fca43f398dfe22/Source/URLConvertible%2BURLRequestConvertible.swift#L74)

(which i get, since they don't have a compiled return type, as it's done in the associatedType.

but this limits completely wrapping the SDK anywhere
