### ISSUE TITLE
URLSessionClient should be used via protocol

### ISSUE THREAD

**Issue by m1entus** [apollographql/apollo-ios#1924]
## Feature request

Hey, i would like to implement custom URLSessionClient just to not override it to avoid future version implementation from Apollo wich will suprise me + seems `invalidate` method should be `open` insted of `public` to be able to override all methods.

## Proposed solution

Create protocol `ApolloURLSessionClient` which will have:

```swift
protocol ApolloURLSessionClient {
    func invalidate()
    func func sendRequest(_ request: URLRequest,
                        rawTaskCompletionHandler: RawCompletion?,
                        completion: @escaping Completion) -> URLSessionTask
}
```

**Comment by designatednerd** [comment]
@m1entus The main reason we're overriding and asking consumers to override is to allow handling of background sessions. Because of the way they're set up, you can't really do that realistically without having something that is the delegate for all the `URLSession` delegate methods. 

Can you talk a little bit about what you're trying to accomplish that isn't covered by the current setup?

**Comment by m1entus** [comment]
@designatednerd Thanka for reply, actually i need it for background session inplementation, but not sure you know dataTasks are not working in background when used in background session so i need to use downloadTask, all would be okay but atill i cannot override one method for session invalidating so i cannot do inside subclass what you are doing for session invalidating

**Comment by designatednerd** [comment]
@m1entus I'm a little confused - as long as you pass in a background session configuration when you instantiate the `URLSessionClient` (which you should get from your `AppDelegate`), I believe you should be able to use `URLSessionDataTask` or `URLSessionDownloadTask`. 

Also, is the method you can't override a delegate method, or is it `invalidate` itself? If it's `invalidate` itself, what do you need to invalidate that's not covered by the current implementation?

**Comment by m1entus** [comment]
Hey, so `invalidate` is called by `LegacyInterceptorProvider` on `deinit`, but it is `public`, so in current implementation it is not possible to handle it, keep in mind that `URLSessionDownloadTask` needs different delegate method handle which is `func urlSession(_ session: URLSession, downloadTask task: URLSessionDownloadTask, didFinishDownloadingTo location: URL)` and i am not able to use your `private var tasks = Atomic<[Int: TaskData]>([:])` because it is private, so i am not able to `invalidate` my downloadTasks when is called on deinit without implementing my own `InterceptorProvider` which is sad because `open` insted of `public` would help in that case.

**Comment by designatednerd** [comment]
Hm - my recollection is that when this happens, in addition to the `URLSessionDownloadDelegate` methods, you should also get calls to `URLSessionTaskDelegate` like `urlSession(_:, task, didCompleteWithError)` when each call finishes, so the tasks should get cleared in that method without you needing to actually handle this manually. Can you try throwing a breakpoint in to confirm that this is the case? 

If it's not, I'd love it if you could share a small reproduction project so we can do some testing on our end.

**Comment by m1entus** [comment]
Hey, because i was already done workaround and i have one instance per app - it is not super required for my use case have the feature which i requested and i unfortunately not able to spend more time on it - so i am closing issue for now
