### ISSUE TITLE
How to avoid the fatalError in Dictionary.jsonObject

### ISSUE THREAD

**Issue by JohnnyXplor** [apollographql/apollo-ios#1936]
## Question

Hey fallows, first of all, awesome work!

I encounter one problem that, I have one model that has a property with type `[String: Any]`. When I handle the query response, app crashes at this point - `Dictionary.jsonObject`. 

I understand that `Any` is not `JSONEncodable`, but just wondering how it should be handled. Context: 
- following condition (JSONStandardTypeConversions.swift)
`if case let (key as String, value as JSONEncodable) = (key, value) {
        jsonObject[key] = value.jsonValue
 }` 
will be false, therefore it throws the fatalError.

- the value(a String value in a Dictionary type) here doesn't have quotes around it while others(regular String type) do. I am not sure if it has anything to do with the issue nor why it happens.

My current workaround is to cast value to String before casting it to `JSONEncodable`
`else if let keyString = key as? String, let newValue = (value as? String) as? JSONEncodable {
          jsonObject[keyString] = newValue.jsonValue
 }`
which doesn't look a good solution. Any suggestions?

**Comment by designatednerd** [comment]
`String` conforms to `JSONEncodable` due to [this extension](https://github.com/apollographql/apollo-ios/blob/9761c809a151f73203bd93345cc8259658fbf922/Sources/Apollo/JSONStandardTypeConversions.swift#L3). 

In theory as long as everything in a Dictionary conforms to `JSONEncodable`, it should also conform to `JSONEncodable`. I think it would probably be a good idea to try `po` ing whatever the value is that's causing everything to fail - it sounds like it's probably not actually a String under the hood, and that's causing the type system to flip out.

**Comment by JohnnyXplor** [comment]
> `String` conforms to `JSONEncodable` due to [this extension](https://github.com/apollographql/apollo-ios/blob/9761c809a151f73203bd93345cc8259658fbf922/Sources/Apollo/JSONStandardTypeConversions.swift#L3).
> 
> In theory as long as everything in a Dictionary conforms to `JSONEncodable`, it should also conform to `JSONEncodable`. I think it would probably be a good idea to try `po` ing whatever the value is that's causing everything to fail - it sounds like it's probably not actually a String under the hood, and that's causing the type system to flip out.

**Comment by JohnnyXplor** [comment]
@designatednerd Thanks for the fast response! Ye the value doesn't have quotes around that's the only thing odd to me (normal String type does have quotes). Our backend dev confirmed that it's sent out as regular String. However if we have no known issue with Dictionary property encoding in `ios-apollo` I will double check with our backend team.

**Comment by JohnnyXplor** [comment]
Sorry I accidentally closed it (was trying to delete a comment). Reopened now.

**Comment by AnthonyMDev** [comment]
This is really odd. I don't have any idea what is going on here without getting my hands on the code and debugging it. Any chance you can provide a reproduction case we can run and check this out?

**Comment by JohnnyXplor** [comment]
@AnthonyMDev Hey! A fyi, I am using an old version of apollo-ios 0.27.1. My project is on Swift 4.2 so cannot use latest of `apllo-ios` that uses Swift 5 features. I will definitely test it again once we migrate to Swift 5.

From what I can see. my problem occured when it called `jsonValue`, the objects were some private classes or types that failed to cast them into Swift types. 

Here's a sample workaround I use in my forked branch - the same applied to Dictionary extension:

```
extension Array: JSONEncodable {
  public var jsonValue: JSONValue {
    return map() { element -> (JSONValue) in
      if case let element as JSONEncodable = element {
        return element.jsonValue
      } else {
        var castedValue: JSONEncodable? = element as? [String: Any]
        if castedValue == nil {
          castedValue = element as? [Any]
        }
        if castedValue == nil {
          castedValue = element as? String
        }
        if castedValue == nil {
          castedValue = element as? Int
        }
        if castedValue == nil {
          castedValue = element as? Double
        }
        return castedValue!.jsonValue
      }
    }
  }
}
```

**Comment by JohnnyXplor** [comment]
I am closing it for now. Will check again once we migrate to Swift 5 and latest Apollo. Thanks  @AnthonyMDev and @designatednerd for giving advises here.
