### ISSUE TITLE
Update tutorial for Apollo Studio Explorer Sandbox

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#1944]
We should update the tutorial steps [2](https://www.apollographql.com/docs/ios/tutorial/tutorial-obtain-schema/), [3](https://www.apollographql.com/docs/ios/tutorial/tutorial-execute-query/), [6](https://www.apollographql.com/docs/ios/tutorial/tutorial-detail-view/), [7](https://www.apollographql.com/docs/ios/tutorial/tutorial-authentication/) and [8](https://www.apollographql.com/docs/ios/tutorial/tutorial-mutations/) to replace the recommendation of using GraphiQL with Apollo Studio Explorer Sandbox.

**Comment by designatednerd** [comment]
Yep this is definitely on my todo list for updating the tutorial, which will happen well before we cut the 1.0

**Comment by designatednerd** [comment]
This has been published!
