### ISSUE TITLE
Codegen version mismatches between local and CI box

### ISSUE THREAD

**Issue by MaximusMcCann** [apollographql/apollo-ios#195]
Need a way to force the local to use the latest `apollo-codegen` or at least throw a warning...

the `check-and-run-apollo-codegen.sh` script only checks for `0.17` and does not look for the latest.  Seems like a versioning mismatch or so due to the -alpha.13

remote:
```
bash-3.2$ apollo-codegen --version
0.17.2
```

local:
```
apollo-codegen --version
0.17.0-alpha.13
```

Came across this b/c there are major code gen differences between those 2 versions

**Comment by martijnwalraven** [comment]
The script only checks for minor version differences, but it will install the latest version when it can't find a compatible version. If you uninstall it from your local machine (`npm uninstall apollo-codegen -g`) it should install the latest version (or you can do that yourself of course).

**Comment by MaximusMcCann** [comment]
I got it working, cheers.  

A side note:
0.17.0-alpha.13 is not compatible with 0.17.2.  The enums generate differently and leave code in an uncompilable state due to the `unknown` add.

**Comment by rqueue** [comment]
@martijnwalraven is there any reason the script doesn't also install an older version if required? For example, we have upgraded to a version of `apollo-ios` that uses `apollo-codegen 0.18`, but still build against commits that use an older version of `apollo-ios` that require `apollo-codegen 0.10`. In this case, the script will update `apollo-codegen` from `0.10 -> 0.18` when needed, but it doesn't downgrade from `0.18 -> 0.10` when needed.

**Comment by designatednerd** [comment]
Since @MaximusMcCann noted he got this working, I'll close this out. Please open a new issue if you run into anything similar with newer versions!
