### ISSUE TITLE
Xcode 13 support for  swift-tools-version:5.5.0 Resolving graph failed

### ISSUE THREAD

**Issue by neha275** [apollographql/apollo-ios#1951]
## Bug report

update the Xcode 13 
the manifest is missing a Swift tools version specification; consider prepending to the manifest '// swift-tools-version:5.5.0' to specify the current Swift toolchain version as the lowest Swift version supported by the project; if such a specification already exists, consider moving it to the top of the manifest, or prepending it with '//' to help Swift Package Manager find it
## Versions

Please fill in the versions you're currently using: 
![Screenshot 2021-09-22 at 10 34 02 AM](https://user-images.githubusercontent.com/26864742/134286259-1ca89799-207b-4544-aeab-bf02f8ae4a42.png)

- `apollo-ios` SDK version:
- Xcode version:  13
- Swift version:  5.5.0
- Package manager: github.com/apollographql/apollo-ios.git
![Screenshot 2021-09-22 at 10 35 23 AM](https://user-images.githubusercontent.com/26864742/134286377-f1374527-39ec-43d7-aa9d-938d94731012.png)

**Comment by calvincestari** [comment]
Hi @neha275 👋🏻 

I think this is an Xcode 13 issue and nothing is misconfigured in the apollo-ios [Package.swift](https://github.com/apollographql/apollo-ios/blob/main/Package.swift) file. Particularly I think Xcode 13 is not correctly reading the tag versions for frameworks that are below `1.0`, i.e: any framework that is still in Major version zero `0.y.z`.

That error message is correct..for `0.3.0` - this [diff](https://github.com/apollographql/apollo-ios/compare/v0.3.0...0.3.1) shows that Package.swift was added in `0.3.1`. If you look in the top-right of the screenshot you sent you'll see that Xcode 13 has defaulted to wanting to use version `0.3.0`, which is very old. If you change that to use a base version of `0.49.0`, which is the latest release, Xcode will successfully add the dependency to your project.

<img width="459" alt="Screen Shot 2021-09-22 at 1 31 23 PM" src="https://user-images.githubusercontent.com/146856/134417364-c227ec14-5ea7-4c0f-a7c3-81280c70752f.png">

I tried this on a couple other frameworks that are also still Major version zero and Xcode also has problems using the correct and latest tag.
* using [SQLite.swift](https://github.com/stephencelis/SQLite.swift) Xcode 13 defaults to `0.9.2` even though the latest available is `0.13.0`
* using [SwiftLint](https://github.com/realm/SwiftLint) Xcode 13 defaults to `0.9.2` even though the latest available is `0.44.0`

I'm going to close this issue and submit the bug to Apple using Feedback Assistant. It may help to get increased focus on the bug if you did the same.
