### ISSUE TITLE
As an iOS developer, I would like to have builders generators so that I can generate mock objects on my tests.

### ISSUE THREAD

**Issue by erneestoc** [apollographql/apollo-ios#1955]
## Feature request

Builders for the models in our schema.

## Motivation

When doing unit tests, in some cases I would like to inject some data to a controller, which as of now requires instantiating a struct, and some times the only argument this initializers take is an unsafe map which is not type safe and prone to errors.

## Proposed solution

Give the codegen tool an extra argument the user can specify which would be used to generate a bunch of builders for all of the models generated in apollo.

By doing this, I would be able to write type safe data generator in my tests, without having to keep a bunch of json files or manually creating maps in my tests.

## Outstanding Questions

On my end, I would like direction of where/how to implement this if it gets traction.

**Comment by AnthonyMDev** [comment]
This is absolutely in the plan for the 1.0 release. We are re-writing the entire codegen engine and the generated code is going to look quite different in 1.0.

The ability to cleanly and easily create mock objects has been a known problem with Apollo iOS for a long time. This is not a blind spot for us. It will be greatly improved when 1.0 comes out.

**Comment by bricker** [comment]
@papanton

**Comment by calvincestari** [comment]
Related to #2187.

**Comment by AnthonyMDev** [comment]
Let's keep one of these open and close the other as duplicate?

**Comment by calvincestari** [comment]
Going to close out this one and keep the most recent issue directly related to v1.0 alpha. This issue will obviously inform any new testing behaviour/functionality.
