### ISSUE TITLE
As an iOS developer, I would like to have an optional way of creating inputs and objects equatables for my tests.

### ISSUE THREAD

**Issue by erneestoc** [apollographql/apollo-ios#1956]
## Feature request

Give the tool the ability to create equatable extensions of my objects and inputs, maybe even on a different folder if you don't want to ship this to the app store.

## Motivation

The swift way of doing unit testing a lot of times requires using protocols to swap implementations on runtime. There are actually a lot of different libraries that do code generation of mocks using the protocols in your projects (ex: [mockingbird](https://github.com/birdrides/mockingbird), [cuckoo](https://github.com/Brightify/Cuckoo), [swiftymocky](https://github.com/MakeAWishFoundation/SwiftyMocky)). When doing that I would like to assert my network interface is receiving a correctly built input, which currently requires me to write manual conformance to equatable on my test just to check if an input was correctly built.

## Proposed solution

Give the tool the ability to generate equatables of your inputs.

## Outstanding Questions

I would need feedback to check what the solution looks like.

**Comment by designatednerd** [comment]
@AnthonyMDev I believe this is going to be part of New Codegen correct?

**Comment by AnthonyMDev** [comment]
It's something I want to do, but there are complications that make this not so straight forward. It's definitely on my radar, and we will do what we can to make this easier. Hopefully it's completely automated. You may have to write your own `Equatable` implementation for custom scalars or something to make it work. But it should be easier than it is today.

**Comment by AnthonyMDev** [comment]
Hi :wave::skin-tone-2: - this issue should be resolved in 1.0. 1.0 is currently in alpha releases with a full 1.0 release in H2 2022. Please take a look at the [latest alpha](https://github.com/apollographql/apollo-ios/releases) and let us know if this is still an issue for you.

This was completed and will be in the next alpha release (1.0 Alpha 6). We try to release alpha versions pretty frequently, so it shouldn't be long! You can always update to use the `release/1.0` branch which has the latest development changes to the Alpha in the mean time!

I ended up making the underling data storage for `SelectionSet` and `InputObject` convertible to `AnyHashable` so they are now able to be `Hashable` and `Equatable` just based on their underlying data without additional generated `Equatable` functions!

You can still override the `Equatable` and `Hashable` conformances for any individual `SelectionSet` if you need to for some reason in an extension.
