### ISSUE TITLE
Replace codegen workflow recommendation of Apollo CLI with Swift scripting

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#1957]
Update this docs page - https://www.apollographql.com/docs/ios/downloading-schema/

**Comment by morgz** [comment]
I'm having an issue with swift scripting on Xcode 13 GM https://github.com/apollographql/iOSCodegenTemplate/issues/4

May be worth waiting until this project is fixed and out of beta? I've switched back to the CLI for now.

**Comment by BowlingX** [comment]
Looks like it's fixed in `PathKit` now.

**Comment by calvincestari** [comment]
The new codegen documentation has a section detailing both - https://www.apollographql.com/docs/ios/code-generation/introduction#running-code-generation.
