### ISSUE TITLE
Struct initialiser for ApolloSchemaDownloadConfiguration.HTTPHeader is internal

### ISSUE THREAD

**Issue by nsivertsen** [apollographql/apollo-ios#1961]
## Bug report

The initialiser for the struct `ApolloSchemaDownloadConfiguration.HTTPHeader` is internal, which means that custom HTTP headers cannot be added to a `ApolloSchemaDownloadConfiguration`.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.49.0
- Xcode version: Version 13.0 beta 5
- Swift version: 5.5.0
- Package manager: Swift Package Manager

## Steps to reproduce

Add the [iOS Codegen Template](ApolloSchemaDownloadConfiguration.HTTPHeader) to a project and attempt to define and pass custom HTTP headers for the `downloadSchema` command:

```swift
let headers = [
  ApolloSchemaDownloadConfiguration.HTTPHeader(key: "Authorization", value: "Bearer MY_TOKEN"),
]

let schemaDownloadOptions = ApolloSchemaDownloadConfiguration(using: .introspection(endpointURL: endpoint),
                                                              headers: headers,
                                                              outputFolderURL: folderForDownloadedSchema)

```

Running the `downloadSchema` command then gives this error:

```
error: 'ApolloSchemaDownloadConfiguration.HTTPHeader' initializer is inaccessible due to 'internal' protection level
```

**Comment by calvincestari** [comment]
The fix for this will be released in `0.49.1` shortly.
