### ISSUE TITLE
ApolloSchemaDownloadConfiguration.HTTPHeader doesn't have public init

### ISSUE THREAD

**Issue by adamnagydev** [apollographql/apollo-ios#1966]
## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.49.0
- Xcode version: 13.0
- Swift version: 5.5

## Steps to reproduce

Try to add a header for fetching a schema.

**Comment by calvincestari** [comment]
Thanks @adamnagydev, this was fixed in https://github.com/apollographql/apollo-ios/pull/1962 and will be released in `0.49.1` shortly.

**Comment by adamnagydev** [comment]
Thank you @calvincestari !
