### ISSUE TITLE
Build Error on path kit for xcode 13

### ISSUE THREAD

**Issue by stshelton** [apollographql/apollo-ios#1980]
## Bug report
Updated Xcode to 13.0 and when building receiving this build error within path kit
`value of optional type 'UnsafeMutablePointer<CChar>?' (aka 'Optional<UnsafeMutablePointer<Int8>>') must be unwrapped to a value of type 'UnsafeMutablePointer<CChar>' (aka 'UnsafeMutablePointer<Int8>')`.

I see that it's been addressed here and that your dependency versioning will pull correct new version with path kit fix. But I'm on the latest version of apollo 0.49.1 and I'm still receiving this error when building.
https://issueexplorer.com/issue/apollographql/iOSCodegenTemplate/4

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.49.1
- Xcode version: 13
- Swift version: 5
- Package manager: Yes

**Comment by designatednerd** [comment]
Hi! Which package manager are you using: Swift Package Manager, Cocoapods, or Carthage?

**Comment by stshelton** [comment]
Swift Package Manger

**Comment by designatednerd** [comment]
Can you check both your project's package dependencies and the `Package.swift` of your checked-out iOS Codegen Template and make sure both are using `.upToNextMinor(from: "0.49.0")`  (which would pull 0.49.1)?
