### ISSUE TITLE
GET option for ApolloSchemaDownloader

### ISSUE THREAD

**Issue by mikepitre** [apollographql/apollo-ios#1981]
## Feature request

It would be great if we had an option to use a GET http method for schema downloading/introspection as part of the ApolloCodegenLib.

## Motivation

A 3rd party CMS we're using only supports GET requests against their GraphQL API. They expect a GET request and the IntrospectionQuery passed as a query param.

**Comment by designatednerd** [comment]
Out of sheer curiosity, what CMS is it?

**Comment by mikepitre** [comment]
haha np, it's Prismic

**Comment by calvincestari** [comment]
@mikepitre - this is now merged. Thanks for contribution! We'll get it out in the next release which should happen in the next week or so.

**Comment by mikepitre** [comment]
@calvincestari great! Thanks for your help and sorry I couldn't dedicate more time to this at the moment. I really like the modifications you made!
