### ISSUE TITLE
Override UploadRequest -> requestMultipartFormData() function

### ISSUE THREAD

**Issue by victormihaita** [apollographql/apollo-ios#1988]
## Question

I would like to know if is possible to override the `requestMultipartFormData()` function of `UploadRequest` class in order to make it search for the image in a an object and not just in the root of a mutation. We. don't try to make a generic function that works with any scenario.. We just need to make it custom, to search for some specific keys that we use (we have the mutation that we need to make it work below).. 

I have tried to make an extension of the UploadRequest class, and override the `requestMultipartFormData()` function but that doesn't  seem to let me do that..

We are limited with the changes from the API and we first want to see if this approach would work.

 @designatednerd  Could you let me know if what we are trying to achieve is a good idea, and if yes, how can we override that function?
Thank you. 

- This is the mutation that we use: 
```
mutation CreateUserArtwork($data: NewArtworkDataInput!) {
    createUserArtwork(data: $data) {
        id
    }
}
```

- This is the object that we want to send: 
```
input NewArtworkDataInput {
    id: String
    title: String
    ...
    featuredImage: Upload!
    additionalImages: [Upload!]
}
```

- I also had to make this typealias in order to make the schema generation work: 
`public typealias Upload = String`

**Comment by victormihaita** [comment]
I was trying to override it in an extension so I won't have to make a new subclass. 
If I make a subclass, then I need to override also the `RequestChainNetworkTransport `-> `constructUploadRequest<Operation: GraphQLOperation>` in order to use the new subclass. But how should I do that?

**Comment by victormihaita** [comment]
I was trying like this: 

```
extension UploadRequest {
    open func requestMultipartFormData() throws -> MultipartFormData {
       ....
    }
}
```

**Comment by designatednerd** [comment]
Also for what it's worth, we really [don't recommend using `Upload` if you can avoid it](https://www.apollographql.com/docs/ios/mutations/#an-important-caveat-about-file-uploads), but I understand that may not be possible.
