### ISSUE TITLE
Generic parameter 'Query' could not be inferred

### ISSUE THREAD

**Issue by farice** [apollographql/apollo-ios#199]
```Swift
let apollo = ApolloClient(url: URL(string: "http://localhost:4000/graphql")!)
        
        apollo.fetch(query: HelloWorldQuery) { (result, error) in
            guard let data = result?.data else { return }
            print(data?.hello) // "Hello world!"
        }
```

with *.graphql

```Javascript
query HelloWorld($rolls: Int!)
{
getDie(numSides: 6) {
roll(numRolls: $rolls)
}
}

```

gives

> Generic parameter 'Query' could not be inferred

Any ideas? Swift 4 + Xcode 9

**Comment by martijnwalraven** [comment]
You'll need to instantiate `HelloWorldQuery`, so you should pass something like `HelloWorldQuery(rolls: 1)`.

**Comment by farice** [comment]
Realized this shortly after and forgot to close the issue :)

Thank you

**Comment by JulienLevallois** [comment]
I got the same error.. do you know why ?

<img width="1215" alt="capture d ecran 2018-10-17 a 13 15 26" src="https://user-images.githubusercontent.com/5727223/47104324-24e30400-d20f-11e8-827c-36b399f9cf5d.png">

**Comment by ankushkushwaha** [comment]
For those who still don't understand what to do just change 

`apolloClient?.fetch(query: query,
                            cachePolicy: .fetchIgnoringCacheData,
                            context: nil,
                            queue: DispatchQueue.main,
                            resultHandler: { result, error in

                                switch result {
                                case .success(let graphQLResult):
                                    print("Success! Result: \(graphQLResult)")

                                case .failure(let error):
                                    print("error!: \(error)")
                                }`


to 

`apolloClient?.fetch(query: query,
                            cachePolicy: .fetchIgnoringCacheData,
                            context: nil,
                            queue: DispatchQueue.main,
                            resultHandler: { result in

                                switch result {
                                case .success(let graphQLResult):
                                    print("Success! Result: \(graphQLResult)")

                                case .failure(let error):
                                    print("error!: \(error)")
                                }`
