### ISSUE TITLE
[Doc] Get Started can be pretty vague if no *.graphql is added to the starter project: ` No operations or fragments found to generate code for.`

### ISSUE THREAD

**Issue by MikeChongCan** [apollographql/apollo-ios#1994]
In this page <https://www.apollographql.com/docs/ios/tutorial/tutorial-add-sdk/>, it said
> Next, before you can use the SDK, you need to obtain a local copy of your GraphQL schema.

However, the page being pointed out is mainly about:

```bash
"${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint="https://apollo-fullstack-tutorial.herokuapp.com/"
```

which is different from downloading a `*.graphql` file (necessary for the codegen step)

I got stuck here for about 20 mins even if I knew GraphQL well for years.

In addition, `comment out the last line of the script you pasted and add the following line below it` could also be very vague. Better if we can add the whole script for this tutorial.

**Comment by imWildCat** [comment]
Sorry, I should have been clear.

"it wasn't clear that the schema and a `.graphql` file aren't the same thing". Yeah, it could be better to explicitly say these two kinds of files are needed
