### ISSUE TITLE
Custom requestMultipartFormData() to accept nested Upload file

### ISSUE THREAD

**Issue by victormihaita** [apollographql/apollo-ios#2007]
I am trying to override the `requestMultipartFormData()` of the `UploadRequest` class in order to accept nested Upload files in the mutation. I managed to override the class but my issue now is that I am not setting correctly the field for the file to null in the nested object, and in the request to the server, instead setting that attribute to null, is just removed completely. It looks like all the CustomScalars scalars that are null are not sent to the server at all. 

This is my change which I am not sure if I am doing it right.. @designatednerd Could you please let me know if I should do something different here?
The `NewArtworkDataInput` is the object that I am trying to send, and it includes an attribute `featuredImage` of type `Upload`

```
        for fieldName in fieldsForFiles {
            if
                let value = variables[fieldName],
                let arrayValue = value as? [JSONEncodable] {
                let arrayOfNils: [JSONEncodable?] = arrayValue.map { _ in nil }
                variables.updateValue(arrayOfNils, forKey: fieldName)
            } else {
                variables.updateValue(nil, forKey: fieldName)
            }
 <<<<<<<<<<<<
            if var data = variables["data"], var artworkInput = data as? NewArtworkDataInput {
                if fieldName == "featuredImage" {
                    artworkInput.featuredImage = nil
                    artworkInput.graphQLMap["featuredImage"] = nil
                }

                data = artworkInput
                variables.updateValue(data, forKey: "data")
            }
        }
>>>>>>>>>>>>>
```

From my understanding when I serialise, the null fields are remove and they shouldn't be. Is that correct?

**Comment by Marcopt98** [comment]
@victormihaita can you kindly share a bit more of the changes that you had to make to make it work? Thank you so much
