### ISSUE TITLE
Refactor PathError

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2008]
Needs to resolve https://github.com/apollographql/apollo-ios/pull/1999/files#r737795101.

* Refactor `PathError` to be scoped for `ApolloCodegenLib` reusable across all of code generation
* Should allow for extension of supporting properties, such as `recoverySuggestion` where needed.
* See [this comment](https://github.com/apollographql/apollo-ios/pull/1999#discussion_r738689875) too.

**Comment by AnthonyMDev** [comment]
Closed with #2362
