### ISSUE TITLE
Can use Apollo in a SPM module?

### ISSUE THREAD

**Issue by djardon** [apollographql/apollo-ios#2013]
## Question

I try to import Apollo library into a SPM module, but always have a build error.

I have the follow declaration into a **Package** file:
```
.package(url: "https://github.com/apollographql/apollo-ios.git",
                 .branch("main"))
....
dependencies: ["apollo-ios"]

```

But when I put Apollo as a dependency I have the next build error:

`product 'apollo-ios' required by package 'ModuleName' target 'TargetName' not found.
`

How can use Apollo inside a SPM module? It's possible?

**Comment by joel-perry** [comment]
This is the declaration I use in ApolloCombine. Just change the target name to your package. Also, I think using `.upToNextMajor` or `.upToNextMinor` is safer than `.branch`, but I'm willing to be wrong about that.

```
dependencies: [
    .package(name: "Apollo",
             url: "https://github.com/apollographql/apollo-ios.git",
             .upToNextMajor(from: "0.43.0"))
  ],
  targets: [
    .target(name: "ApolloCombine", dependencies: [.product(name: "Apollo", package: "Apollo")])
  ]

**Comment by designatednerd** [comment]
My recollection is you can't use `branch` or other git-based ones for Swift packages that are published with a version number. IIRC it basically turns dependency resolution into a complete nightmare, so it's just not supported. 

Definitely recommend `upToNextMinor` as we will continue to have breaking changes in minor releases until we release 1.0.

**Comment by joel-perry** [comment]
@designatednerd And that is why you make the big bucks! I decided to go with `.upToNextMajor` so I wouldn't have to update every time apollo-ios makes a minor update. This strategy only works because my interface to apollo-ios is so narrow, though.
