### ISSUE TITLE
Can anyone give me the latest code of add Authorise Headers 

### ISSUE THREAD

**Issue by Wolverine-X-man** [apollographql/apollo-ios#2019]
## How to add header in Apollo GraphQL 0.49.1 for iOS

Here is my question.. https://stackoverflow.com/q/69787174/13133228

I do lots of try but i cannot find solution for this.

@designatednerd

**Comment by designatednerd** [comment]
Hi! Looks like you're using some code from an older version of the Apollo lib. [Here's the doc for the newer setup](https://www.apollographql.com/docs/ios/initialization/#advanced-client-creation) - the short version is that you're going to want to use an interceptor to add the headers.

**Comment by CemYil03** [comment]
In my understanding it is necessary to always add all the default Interceptors manually. So maybe something to point out specifically in the documentation.
