### ISSUE TITLE
Update to latest version of Apollo CLI

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2027]
This is to get https://github.com/apollographql/apollo-tooling/pull/2473 into codegen and align with the output from `client:push` for safelisting/whitelisting operations.

**Comment by AnthonyMDev** [comment]
I'm going to need a spec for this safelisting functionality for the new codegen also. Just something that I can convert into unit tests to confirm that the new codegen has parity here.

**Comment by calvincestari** [comment]
I wonder if a better test for the new codegen would be to leave a CI test that downloads the tooling and generates output we can compare to.

**Comment by AnthonyMDev** [comment]
The output is going to be so wildly different that comparing them would be difficult. We aren’t comparing the to be the same, we are only looking for one specific piece of behavior to be correct. (Not necessarily the same, just correct behavior).

Unless I’m misunderstanding something!

**Comment by designatednerd** [comment]
The output on our end would be the raw query which gets sent to the server, with `__typename` added wherever it needs to be. That's what gets hashed and compared for safelisting.

**Comment by calvincestari** [comment]
> The output on our end would be the raw query which gets sent to the server, with `__typename` added wherever it needs to be. That's what gets hashed and compared for safelisting.

Correct - the [operationIDs.json](https://github.com/apollographql/apollo-ios/pull/2028/files#diff-24df291130b927a33841446ff3fe656cea0b0259359c05fe8aa2ea06819913cd) file is the output we'd need for comparison no?

**Comment by designatednerd** [comment]
Ideally yes

**Comment by AnthonyMDev** [comment]
I still don't think that comparison to the old codegen output is the appropriate way to test this. 

If at some point we need to alter the expected output again because of another unforeseen problem, then the outputs are going to deviate. Unit tests should directly and exclusively test the actual behavior you expect to have, not direct parity with an unmaintained legacy system.

We can revisit the conversation about that when we go to actually implement this though.

**Comment by calvincestari** [comment]
> I still don't think that comparison to the old codegen output is the appropriate way to test this.

It's not about the "old codegen" and instead about the external code that registers the queries for safelisting; that just happens to be the same CLI tooling. The operationIDs.json output is the simplest form of what we'd need for comparison, I don't think `client:push` outputs the formatted query anywhere we could compare to.

> If at some point we need to alter the expected output again because of another unforeseen problem, then the outputs are going to deviate. Unit tests should directly and exclusively test the actual behavior you expect to have, not direct parity with an unmaintained legacy system.

Correct - this isn't a unit test. We'll have unit tests to ensure that `__typename` is being added where we expect it to and in addition to that I'm suggesting an integration test that ensures our expectation matches what is happening elsewhere because if we aren't proactive about catching a mismatch the outcome impacts users.

> We can revisit the conversation about that when we go to actually implement this though.

👍🏻 - I've created https://github.com/apollographql/apollo-ios/issues/2029 as a TODO so we don't miss it.
