### ISSUE TITLE
No such module ApolloUtils

### ISSUE THREAD

**Issue by gantaa** [apollographql/apollo-ios#2047]
## Bug report

Using the latest version of Apollo as a CocoaPod in a linked library is yielding a build error in the Apollo project:

No such module 'ApolloUtils'

in Bundle+Helpers.swift
```
#if !COCOAPODS
import ApolloUtils
#endif
```

The import has a comment around it checking for cocoapods but the error happens anyways even though I am using cocoapods and it appears this import statement should be skipped.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.50.0
- Xcode version: 13.1
- Swift version: 5.5.1
- Package manager: Cocoapods 1.11.2

## Steps to reproduce

Build a project using latest Apollo from cocoapods

**Comment by designatednerd** [comment]
Hi! That's quite odd that it's hitting that if you're using CocoaPods - if the `#if !COCOAPODS` gate were failing altogether, you'd likely see a LOT more errors. We also have an internal CP test app that is building without issue using the same versions.

I would recommend doing the [Derived Data Dance](http://deriveddata.dance) and re-compiling - it seems like something's gotten a bit out of whack in your cache.

**Comment by gantaa** [comment]
Thank you.  Yes its very strange.  Its only one error.

In this particular case, I WAS using Swift Package Manager... and Apollo was working just fine in my project.  But, now i am Archiving with custom Configuration names in my project, and SPM barfs with custom names.  So i JUST switched to CocoaPods again for this package...  mayve this is somehow mucking with the COCOAPODS gate somehow somewhere...

Thus...it was a good suggestion trying the Derived data dance.  But after completing that, and clean building again, the same error still occurs.  It could be left over from something stale when using SPM but im not sure what other caches or data folders there are to clear

**Comment by gantaa** [comment]
Removed pods from projects completely and reinstalled.  Same problem

**Comment by designatednerd** [comment]
Yeah so Cocoapods pulls everything into a single `Apollo` framework rather than allowing us to use multiple sub-frameworks as both SPM and Carthage do. That's why this is set up the way that it is, because then at that point you no longer need to import the sub-framework (and actually can't becuase as far as CocoaPods knows, it doesn't exist), so that's why we've got that if statement only for CocoaPods and why it would have been working fine with SPM. 

It definitely seems like something has gotten vastly out of whack in your cache from switching package managers, but if blowing away derived data didn't fix it, there might be something else going on. I would definitely try it again, and make sure you've quit Xcode (sometimes I'll restart my laptop before nuking derived data just to be sure there's no silent background processes running or anything), but if that doesn't work, I'd start looking at your git log to see what CocoaPods changed in your `xcodeproj` file when you installed it. My hunch is something in there got screwed up if a second derived data dance doesn't change it.

**Comment by calvincestari** [comment]
Out of curiosity @gantaa, if you add some intentionally failing code in your own app logic surrounded by the `#if !COCOAPODS` directive what is the outcome? Maybe it's the `COCOAPODS` value definition that's not correct.

**Comment by gantaa** [comment]
I tried switching the apollo pod to a common pod installed in all my projects, rather than only on the library project that was using it in SPM before

Now the import error is on the Apollo import itself.  I'll have to keep playing with podfile, pod installs, framework search paths 

@calvincestari in one of my controllers i did try adding a bogus import statement wrapped in #if !COCOAPODS gate

There is no error on my bogus import when i do that but I'm not sure if the dependency errors are stopping the build before getting there

@designatednerd i will try the xcode project diff if i keep hitting dead end. My wifes birthday today so its a job for tomorrow

Thanks for the suggestions! Patience with ios builds is a virtue

**Comment by designatednerd** [comment]
It sounds from this most recent post like you're using a combination of SPM and CocoaPods. Can you share a basic description of the frameworks you're using, and which ones you're using CocoaPods for vs. SPM?

**Comment by gantaa** [comment]
I have 2 Apps in an xcworkspace that share a custom framework, also in that workspace.  I am attempting to use Cocoapods only now that I have had trouble with SPM building packages while using custom configuration names.  I WAS using SPM for Apollo and Keychain Swift, and now i'm attempting to use Cocoapods for all packages.

Here is an example of my Podfile

```
 Uncomment this line to define a global platform for your project
platform :ios, '13.0'
# Uncomment this line if you're using Swift
use_frameworks!

workspace 'transact-ios'

project 'NerkleKit/NerkleKit.xcodeproj'
project 'App1/App1.xcodeproj'
project 'App2/App2.xcodeproj'

def common_pods
    $awsVersion = '~> 2.15.0'
    pod 'AWSCore', $awsVersion
    pod 'AWSCognitoIdentityProvider', $awsVersion
    pod 'GooglePlaces', '~> 3.10.0'
    pod 'Apollo', '~> 0.50.0'
    pod 'KeychainSwift', '~> 19.0.0'
end

target 'NerkleKit' do
    project 'NerkleKit/NerkleKit.xcodeproj'
    common_pods
end

target 'App1' do
    project 'App1/App1.xcodeproj'
    common_pods
    pod 'Floaty', '~> 4.2.0'
end

target 'App2' do
    project 'App2/App2.xcodeproj'
    common_pods
end

```

When I removed my dependencies (Apollo and KeychainSwift) as SPM packages, and added them to the NerkleKit target in my podfile, Apollo module could be found but I got no suck module ApolloUtils (with the broken cocopod gate).  Most recently, I moved Apollo to the common pods section, deintegrate and reinstall pods, and now I am receiving 'Apollo' module not found

**Comment by gantaa** [comment]
Ok.  I'm getting a little closer..  There are TWO places where you need to remove Swift packages.  I only removed them from the target's "Frameworks and Libraries".   But I also have to go to the project "Package Dependencies" and remove them from there as well.

This is presumably why my `#if ! COCOAPODS` gate was not working before

In addition, I had to remember to go back to your [docs](https://www.apollographql.com/docs/ios/installation/) and grab the COCOAPODS run script rather than the SPM run script that I had in there before.

Sadly.  After another derived data dance, clean build folder.  Pod deintegrate all targets, pod setup, pod install, and build... am still receiving 

`no such module 'Apollo'`

**Comment by gantaa** [comment]
For what its worth.  I commit, and push my xcworkspace to github.  My developer tries it on his machine, and the build works..

He is using Xcode 12.5.1 and I am on Xcode 13.1

**Comment by calvincestari** [comment]
Hmm, that's odd but it might be worth a try to clone your repo to a different directory and see if that fixes anything for you. Alternatively try Xcode 12.5.1 on your machine to see if you get the same results as your co-worker.

At Apollo we're all on Xcode 13.1, including CI builds.

**Comment by gantaa** [comment]
Ok.  So a new cloned repo, fresh pod install ends up with same error.  `No such module 'Apollo'`

I tried downgrading to 12.5.1, but I cannot.  My OS is Monterey and it only runs XCode 13+

I might switch back to SPM now.  Who knows..  I'll keep you posted still

**Comment by gantaa** [comment]
Ok.  I have found the problem.  The custom configuration names that I changed for my apps needed to be exactly the same in the shared Framework.  This caused the shared framework to build successfully on its own, however caused the Framework build to fail with `no such module 'Apollo'` whenever I tried building one of the App targets in which the framework is used.  Once I matched up all configuration names across both my apps, and my framework, all dependencies (whether I use CocoaPods or SPM) are able to build.

I am still going to Cocoapods for now for my final solution because SPM does not play nicely with custom configuration names without additional scripting... And it appears this has been an issue for a couple years now.

Thanks for the suggestions.  As expected it wasn't an apollo-ios issue.  However, I hope this thread helps others switching back and forth between SPM and Cocoapods, particularly those using custom build configurations and custom frameworks.  

And remember, with apollo-ios to use the appropriate run script for your chosen package manager from the [docs](https://www.apollographql.com/docs/ios/installation/)

**Comment by calvincestari** [comment]
Thanks for circling back to share the fix @gantaa. 👍🏻

**Comment by icecrystal23** [comment]
I'm having a similar issue, but only on our CICD system which is quite confusing. The same line is failing the same way

    <pathtoproj>/Pods/Apollo/Sources/Apollo/Bundle+Helpers.swift:3:8: error: no such module 'ApolloUtils'
    import ApolloUtils
           ^

I wonder if switching the conditional from `#if !COCOAPODS` to `#if SWIFT_PACKAGE` might be an okay workaround?

FWIW I have no idea why it's failing to compile. The build command contains the following, so in theory COCOAPODS is defined...

    -Xcc -DPOD_CONFIGURATION_RELEASE\=1 -Xcc -DCOCOAPODS\=1

**Comment by designatednerd** [comment]
`#if SWIFT_PACKAGE` isn't a great solution because this import only needs to be disabled for CocoaPods - if you're using Carthage or Git Submodules (which...based on personal experience I don't recommend, but is a thing some people do), you'd still need to have that import work. 

What version of CocoaPods are you using where you're seeing this issue? And is it the same version both locally and on CI?

**Comment by icecrystal23** [comment]
The build system reports using CocoaPods version 1.11.0, Xcode version 13.2, and these versions of Apollo in our Podfile.lock. My local CocoaPods is 1.11.2.

```
  - Apollo (0.50.0):
    - Apollo/Core (= 0.50.0)
  - Apollo/Core (0.50.0)
```

**Comment by icecrystal23** [comment]
I think I've root caused this to fastlane's `analyze_build_time` option accidentally clobbering `OTHER_SWIFT_FLAGS`. I'm verifying that today and will update here when I know for sure.

**Comment by icecrystal23** [comment]
Confirmed. See related PR on fastlane: https://github.com/fastlane/fastlane/pull/19737

**Comment by designatednerd** [comment]
That explains A LOT. Thank you very much for digging into this!

**Comment by joshdholtz** [comment]
Just stopping by in this issue to say hi to @designatednerd 👋 

And thank you to @icecrystal23 for submitting that _fastlane_ PR! ❤️
