### ISSUE TITLE
No operations or fragments found to generate code for

### ISSUE THREAD

**Issue by luckyMehndiratta2525** [apollographql/apollo-ios#2099]
I  am not able to run this script

"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift

[no](![Screenshot 2022-01-16 at 7 00 56 PM](https://user-images.githubusercontent.com/95231907/149662083-0cb08182-754f-4798-9ccb-bebbe87c8608.png))

**Comment by calvincestari** [comment]
Hi @luckyMehndiratta2525 👋🏻 - generating Swift code essentially boils down to `schema + operation = code`. The error you're getting means the `operation` part is missing.

Looking at the command that is being executed I can see it is looking for a schema file with the parameter `--localSchemaFile=schema.json` and the operation/fragment files with the parameter `--includes=./**/*.graphql`.

This means:
* the GraphQL schema file must be named `schema.json` and in the root path of your project
* somewhere in the project folder hierarchy there must be operation/fragment files named with the `.graphql` extension, e.g.: `operation1.graphql`

When you satisfy both these parameters the code generation engine will attempt to generate code for you.

**Comment by luckyMehndiratta2525** [comment]
[
![Screenshot 2022-01-19 at 12 01 31 AM](https://user-images.githubusercontent.com/95231907/149997500-2544d4aa-6689-4d40-a1f9-9030e6f3fa97.png)
](url)

**Comment by luckyMehndiratta2525** [comment]
Hi @calvincestari  this is the project structure

**Comment by calvincestari** [comment]
That project structure appears to be good. It looks like you've got Xcode configured to hide all file extensions; another thing to check is that the `testHelp.graphql` file doesn't have any other extension on disk. As an example if it were named `testHelp.graphql.txt` on disk you would still only see `testHelp.graphql` in Xcode but the codegen script wouldn't be able to find it.

**Comment by calvincestari** [comment]
I can replicate the error you're experiencing if `testHelp.graphql` is named something else on disk.

```
Have you tried our new Swift Package Manager wrapper around codegen? It's now out of beta and ready to go! See docs at https://www.apollographql.com/docs/ios/swift-scripting/. This Bash script will be deprecated soon, so give it a try today!
Checking if CLI needs to be downloaded...
Zip file already downloaded!
Correct version of the CLI tarball is downloaded locally, checking if it's already been extracted...
Current verson of CLI is already extracted!
Apollo CLI Information: apollo/2.33.9 darwin-x64 node-v12.22.7
+ /Users/calvincestari/Projects/apolloTest/Pods/Apollo/scripts/apollo/bin/run codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.graphqls API.swift
⚠️  It looks like there are 0 files associated with this Apollo Project. This may be because you don't have any files yet, or your includes/excludes fields are configured incorrectly, and Apollo can't find your files. For help configuring Apollo projects, see this guide: https://go.apollo.dev/t/config
Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
Generating query files with 'swift' target [failed]
→ No operations or fragments found to generate code for.
    Error: No operations or fragments found to generate code for.
Command PhaseScriptExecution failed with a nonzero exit code
```

<img width="547" alt="Screen Shot 2022-01-18 at 11 49 42 AM" src="https://user-images.githubusercontent.com/146856/150008367-21d6e67d-0e93-4e0c-91b9-48fce62f6d56.png">

**Comment by luckyMehndiratta2525** [comment]
Thank you @calvincestari. Now working. The problem is same as you mentioned

**Comment by calvincestari** [comment]
Awesome, glad that worked!
