### ISSUE TITLE
Implement the output of `ApolloCodegenConfiguration`

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2101]
The work here is to ensure that all configuration properties of `ApolloCodegenConfiguration` affect the output in the desired way.

- [x] `queryStringLiteralFormat`
- [x] `deprecatedEnumCases` (done in #2303)
- [x] `schemaDocumentation`
- [x] `apqs`
  - [x]  `FileOutput.operationIdentifiersPath`
- [x] `additionalInflectionRules`
- [x] `warningsOnDeprecatedUsage`

_This was prompted by https://github.com/apollographql/apollo-ios/pull/2098#issuecomment-1016073269._

**Comment by AnthonyMDev** [comment]
- `queryStringLiteralFormat`
  - `singleLine`:
```swift
public static let document: DocumentType = .notPersisted(
    definition: .init(
      "query AllAnimalsQuery { allAnimals {__typename height { __typename feet inches } ...HeightInMeters ...WarmBloodedDetails species skinCovering ...",
      fragments: [HeightInMeters.self, WarmBloodedDetails.self, PetDetails.self]
    ))
```

**Comment by AnthonyMDev** [comment]
- `apq`
  - `persistedOperationsOnly`
```swift
public static let document: DocumentType = .persistedOperationsOnly(
    operationIdentifier: "a121309ofsah80j")))
```

**Comment by AnthonyMDev** [comment]
- `schemaDocumentation`
  - SelectionSet Headers
```swift
/// AllAnimal.Predator
///
/// Parent Type: `Animal`
  public struct Predator: AnimalKingdomAPI.SelectionSet {
  public let data: DataDict
  public init(data: DataDict) { self.data = data }

  public static var __parentType: ParentType { .Interface(AnimalKingdomAPI.Animal.self) }
```

**Comment by calvincestari** [comment]
`warningsOnDeprecatedUsage` - from https://github.com/apollographql/apollo-ios/pull/2303#discussion_r893846978

> For deprecated cases, we probably should have the deprecated annotation to provide a deprecation warning as well. https://stackoverflow.com/questions/71354470/deprecate-enum-value-in-swift
> 
> That warning should also apply to fields marked as deprecated in the schema.
> 
> Though some people may not want those warning clogging up their project, even when things are deprecated... So we should add another configuration option for this. Maybe add public let warningsOnDeprecatedUsage: Composition. This would add the @available(*, deprecated, message: "Deprecated: \(deprecationReason)") to enum cases and deprecated fields if set to .include`.
