### ISSUE TITLE
Receiving `Apollo.JSONDecodingError.missingValue` error when parsing nullable value

### ISSUE THREAD

**Issue by tapi** [apollographql/apollo-ios#211]
Im not 100% sure how this arose since an earlier less complex version of this query had no issues. However it looks like im hitting an issue in `private func execute<Accumulator: GraphQLResultAccumulator>(fields: [GraphQLField], on object: JSONObject, info: GraphQLResolveInfo, accumulator: Accumulator) throws -> ResultOrPromise<Accumulator.FieldEntry>` `GraphQLExecutor.swift:214` where it looks like nil values always trigger an error without any checks to see if the type being parse is optional or not. 

Replacing
```swift
guard let value = value else {
        throw JSONDecodingError.missingValue
}
```

with 
```swift
guard let value = value else {
        return try self.complete(value: NSNull(), ofType: firstField.type, info: info, accumulator: accumulator)
}
```

Seems to solve the issue but I don't know if i understand the codebase well enough to understand any possible side effects.

Appears as though this may be a regression of #56

**ApolloClient Version:** 0.7.0
**Schema fragment:**
```json
{
        "name": "manualDescription",
        "description": null,
        "args": [],
        "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
        },
        "isDeprecated": false,
        "deprecationReason": null
},
```

**Error:**
```
(lldb) po error
▿ Optional<Error>
  ▿ some : GraphQLResultError
    ▿ path : 8 elements
      - 0 : "leagues"
      - 1 : "0"
      - 2 : "currentSeason"
      - 3 : "events"
      - 4 : "edges"
      - 5 : "0"
      - 6 : "node"
      - 7 : "manualDescription"
    - underlying : Apollo.JSONDecodingError.missingValue
```

**Comment by tapi** [comment]
Sorry, errant keyboard strokes.

**Comment by tapi** [comment]
Apologies, It looks as though our backend may actually be omitting this value in the response

**Comment by gsp100677** [comment]
I'm seeing this error too but having a hard time tracking down the cause.

I have a query with a handful of nullable fields in a fragment such as:
```
fragment fieldSet on item {
  itemName
  itemId
  object {
    objectName
    objectId
  }
}
```

All fields above except the ID's are optional in the graph ql schema.json file, and can legitimately return null. I'm seeing basically the exact error as described in the original post.

But using a different client (e.g. Insomnia) doesn't lead to any errors.

I've tried:
- checking schema.json file is fully up to date
- comparing with other optional OBJECT type fields in the same fragment that don't cause this error but can't see any difference.

Is anyone able to offer possible avenues of further investigation?

**Comment by tapi** [comment]
Does the response contain all the fields specified in the query? For me I believe the issue was that the field was not returned in the response in cases where the value was `null`.

Put another way I don't think that because the value is nullable it is possible to omit the field in the response.

**Comment by gsp100677** [comment]
It was being returned, but with a null value (correctly).

Turns out it was an Apollo bug that is fixed in the latest version - updating the pod resolved it.
