### ISSUE TITLE
[Code Gen] Do not output a swift file if there are no changes

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#2110]
## Feature request

When running code gen script, the modified at date for the generated files always changes making Xcode recompile everything that uses any of the files. Instead, of rewriting all files, we should only write a new file if there are any changes, this will lead to faster compile times after the code generation is run

## Motivation

It would help with compile times when running code gen

**Comment by calvincestari** [comment]
Hi @tahirmt, thanks for the feature request. You'll be pleased to know that this is something we intend to build into 1.0 - [tracking issue](https://github.com/apollographql/apollo-ios/issues/2049).

For now the best option is to use the 'Input Files' feature of Xcode for custom build phases. This will give Xcode the additional context it needs to know whether the custom build phase needs to be executed.

**Comment by calvincestari** [comment]
Closing this and tracking in #2049
