### ISSUE TITLE
Codegen throws errors but doesn't return non-zero exit code

### ISSUE THREAD

**Issue by philfi** [apollographql/apollo-ios#2111]
## Bug report

Following the instructions for setting up [Swift Scripting](https://www.apollographql.com/docs/ios/swift-scripting/) the codegen build phase isn't failing even if code generation encounters an error. This leads to errors showing up in XCode but builds may still succeed. I attempted to resolve this by adding a catch block that would exit with the error but it doesn't seem to actually be throwing the exception at that level even though the output indicates it has encountered an error. `Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure`

![image](https://user-images.githubusercontent.com/39564615/151015783-e2f182ef-c4d3-4777-9d33-5e39ad3e970b.png)

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.50.0
- Xcode version: 13.2
- Swift version: 5.3
- Package manager: SPM

## Steps to reproduce

Add a .graphql file with an error in it i.e. a misnamed query argument `beforeCursor` that is called `cursor` in the source schema. 

Update the end of Swift Scripting Code generation (as provided in the [tutorial](https://www.apollographql.com/docs/ios/swift-scripting/)) with a do/try/catch and some logging.
```
do {
    try ApolloCodegen.run(
        from: targetRootURL,
        with: fileStructure.cliFolderURL,
        options: options
    )
    CodegenLogger.log("ApolloCodegen succeeded without error", logLevel: .debug)
} catch {
    CodegenLogger.log("ApolloCodegen failed with error: \(error.localizedDescription)", logLevel: .error)
    SwiftScript.GenerateCode.exit(withError: error)
}
```

Run the generate command `swift run ApolloCodegen generate`

Output will look something like this indicating that no exception was thrown by the call to `ApolloCodegen.run` even though it failed to validate the query document.
```
[DEBUG - ApolloCodegenLib:Basher.swift:59] - apollo/2.33.9 darwin-x64 node-v16.13.2
+ /Users/phil/development/ios/ApolloCodegen/ApolloCLI/apollo/bin/run codegen:generate --target=swift --addTypename '--includes=./**/*.graphql' --localSchemaFile=/Users/phil/development/ios/Fi/schema.graphqls --passthroughCustomScalars --mergeInFieldsFromFragmentSpreads /Users/phil/development/ios/Fi/API.swift
Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
.../Fi/GraphQL/SomeExample.graphql: Unknown argument "beforeCursor" on field "Pet.queryName".
Validation of GraphQL query document failed
    at Object.validateQueryDocument (/Users/phil/development/ios/ApolloCodegen/ApolloCLI/apollo/node_modules/apollo-language-server/lib/errors/validation.js:40:38)
    at Object.generate [as default] (/Users/phil/development/ios/ApolloCodegen/ApolloCLI/apollo/lib/generate.js:23:18)
    at write (/Users/phil/development/ios/ApolloCodegen/ApolloCLI/apollo/lib/commands/client/codegen.js:83:54)
    at Task.task (/Users/phil/development/ios/ApolloCodegen/ApolloCLI/apollo/lib/commands/client/codegen.js:103:46)
Generating query files with 'swift' target - wrote 1 files [title changed]
Generating query files with 'swift' target - wrote 1 files [completed]

[DEBUG - ApolloCodegenLib:main.swift:81] - ApolloCodegen succeeded without error
```

## Further details

Recently updated from an older version of apollo-ios so could be the expected behavior here has changed or I'm missing something but seems like there's an issue propagating errors/exceptions.

**Comment by designatednerd** [comment]
I suspect it's not throwing an error because it does generate the rest of the code, so what you're seeing about the unknown argument is probably a warning rather than an error. I'm not sure _why_ that's a warning rather than an error, but it'd at least explain why you're not getting a failure. 

If you attempt to use an invalid field name in one of your queries (rather than an unknown argument), does that fail? Ex if your query should be:

```graphql
query User {
   user {
      name
      email
   }
}
```

Try something like

```graphql
query User {
   user {
      fame
      email
   }
}
```

LMK what you get with something like that.

**Comment by philfi** [comment]
Hey I apparently forgot to follow up here, that was exactly the distinction just warning vs error. IMHO it should be an error but that's just my two cents. Thanks for the assistance @designatednerd !
