### ISSUE TITLE
Test compatibility of `.utf8` data format used for file generator output

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2115]
> We should probably be wary of how this affects things for character-based languages like Japanese and Chinese which take heavy advantages of UTF-16. Not sure exactly how to test it but definitely worth at least making an issue on it

See https://github.com/apollographql/apollo-ios/pull/2112#discussion_r792158860.

**Comment by AnthonyMDev** [comment]
We're not going to handle this for 1.0. If user feedback is that there are problems here in the future, we will consider implementing at that point.
