### ISSUE TITLE
Fix SwiftScripts

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2118]
We broke a bunch of stuff to get it generating code, the task here is to go back and fix that. See https://github.com/apollographql/apollo-ios/pull/2117/commits/d3b0e44e64a294a065fcbee99106b2a8d4da8117.

**Comment by calvincestari** [comment]
We this is left down to the GitHub API schema generation.

**Comment by AnthonyMDev** [comment]
Moving this to Beta, as it's not necessary in order to get to feature complete. This is important clean-up that needs to be done, but we can push it to Beta for sure.

**Comment by calvincestari** [comment]
This is complete with the merging of #2384.
