### ISSUE TITLE
Post-Alpha release questions

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2119]
Things to revisit, questions to answer, decisions to make - post Alpha.

- [x] Should generated operation files have the operation type appended, i.e.: `class AllAnimals: GraphQLQuery` or `class AllAnimalsQuery: GraphQLQuery`. Android has a configuration option (`useSemanticNaming`) that defaults to `true`.
- [x] Should we make File Generators have `static func` instead of being initialized? Better for performance (negligibly).
- [x] Change ApolloAPI to ApolloInternal??
    * Not sure if this is right. Users may need to import this. More research needed
- [x] Input data stored differently in `InputObject` vs Operation Variables. Should we align these?

**Comment by AnthonyMDev** [comment]
>  Should we make File Generators have static func instead of being initialized? Better for performance (negligibly).
Looking at it now and I don't think there is value there. Its going to increase the complexity, decrease cleanliness and ease of use, and not really give any noticeable performance benefits.

**Comment by AnthonyMDev** [comment]
> Change ApolloAPI to ApolloInternal??

I've thought more about this, and it's not actually just internal stuff. People are going to need to import it sometimes. When working with Apollo infrastructure and generated models, but not needing to do an actual query operation, we do need to import this. So I'm fine leaving the name.

**Comment by AnthonyMDev** [comment]
All questions have been considered. Closing this issue!
