### ISSUE TITLE
#warning follow-ups

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2138]
This is a collection of `#warning` directives that were in the `release/1.0-alpha-incubating` branch prior to the 1.0 Alpha release. We removed them from the codebase to avoid problems with any project that doesn't tolerate warnings. We will follow up on these as we progress through Alpha/Beta/RC releases.

These all originated in the diff of PR https://github.com/apollographql/apollo-ios/pull/2139.

1. `Sources/Apollo/GraphQLExecutor.swift`
  - [x] #2498
2. `Sources/Apollo/JSONRequest.swift`
  - [x] #2496
3. `Sources/ApolloAPI/FragmentProtocols.swift`
  - [x] #2497

4. `Sources/ApolloAPI/InputValue.swift`
  - [x] [TODO: It might be more performant to just use the raw values like before commit: e7a9b2c27f9d01764943f1aa7ff9d759d8762bff - We should run performance tests and try reverting and see what performance is like.](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-8c4cd59fabe7e1fba4343d4c845e66556457a869ed25035d6e47e47343faae40L3)
5. `Sources/ApolloAPI/JSONStandardTypeConversions.swift`
  - [x] [might be able to remove these since we are using EnumType](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-638484fd98781fb0e35b2b2510f22ed442501e078de1558aad850eab4c63d199L76)
6. `Sources/ApolloAPI/ScalarTypes.swift`
  - [x] [TODO: do we really need to have both scalar and custom scalar?](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-2885069143a21597da77c0a6a47230ee730df443657a61b36e59cac7aa103f95L25)
7. `Sources/ApolloCodegenLib/Frontend/CompilationResult.swift`
  - [x] [TODO: Compute this from source + referenced fragments](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-a64feaebdd2c40e43b5dd7a75e17df8e41828f57316ef7eeb7581333477b5dd2L27)
8. `Sources/ApolloCodegenLib/IR/ScopedSelectionSetHashable.swift`
  - [x] [What if there is a field with the same name as a type? Do we get a conflict? Write a test for this.](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-b5d4fed8b1c0c8e5fada44ab08537102cd3a296562465f22efba27e6072a9b9cL17)
9. `Sources/ApolloCodegenLib/IR/TypeScopeDescriptor.swift`
  - [x] [Do we need to recursively form union with each interfaces other interfaces? Test this.](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-46ee76ecad43b3dbcb6c05f6d512e79a3da61e58a898410dd85dc3ab20d7d614L78)
10. `Tests/ApolloCodegenTests/AnimalKingdomAPI/AnimalKingdomIRCreationTests.swift`
  - [x] [TODO: height is redundant, but is redeclared, do we include or omit it? It's nested fields are not redundant though, so I'm pretty sure we keep it...?](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-72054b352509415a4d36eb2ce159a5dbe2c33cc97bf297260138e41aaf6ed4b8L418)
  - [x] [TODO: ...WarmBloodedDetails is redundant, but is redeclared, do we include or omit it?](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-72054b352509415a4d36eb2ce159a5dbe2c33cc97bf297260138e41aaf6ed4b8L550)
  - [x] [TODO: This is the same as AllAnimal.AsPet.AsWarmBlooded.Height. Should we inherit that object instead?](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-72054b352509415a4d36eb2ce159a5dbe2c33cc97bf297260138e41aaf6ed4b8L756)
  - [x] [TODO: This is the same as AllAnimal.AsPet.Height. Should we inherit that object instead?](https://github.com/apollographql/apollo-ios/pull/2139/files#diff-72054b352509415a4d36eb2ce159a5dbe2c33cc97bf297260138e41aaf6ed4b8L946)
11. `Tests/ApolloCodegenTests/ApolloCodegenTests.swift`
  - [x] #2499
  - We've decided to do this as multiple files. Need to write a test for this to verify behavior.

**Comment by AnthonyMDev** [comment]
All remaining work has been converted to separate issues.
