### ISSUE TITLE
v 0.8.0 with codegen v0.18.6 does not compile :/

### ISSUE THREAD

**Issue by MaximusMcCann** [apollographql/apollo-ios#214]
![image](https://user-images.githubusercontent.com/1643285/36549396-b47eee8a-17c0-11e8-84a5-2dc8ba5dd697.png)

condensed code snippet:
```
fragment ApolloDetailedPie on Pie {
    ....//more things
    oneYearQuote: historicalPerformance(range: {length: {amount: 1, unit: YEARS}}, interval: WEEK) {
      ...ApolloHistoricalPiePerformance
    }
}

...//later
fragment ApolloHistoricalPiePerformance on HistoricalPiePerformance {
  date
  value
}

```

**Comment by MaximusMcCann** [comment]
Revert to v0.7.0 works fine.  With this generated code:
![image](https://user-images.githubusercontent.com/1643285/36549663-55ea58f4-17c1-11e8-88d8-d0aefb8ed34c.png)

**Comment by piemonte** [comment]
i'm encountering the same codegen issue.

**Comment by martijnwalraven** [comment]
This should have been solved in `apollo-codegen` 0.18.7.

**Comment by piemonte** [comment]
@martijnwalraven ah thanks, apologies, i've got 0.18.6 installed and didn't update.

**Comment by piemonte** [comment]
will 0.18.7 be published through npm soon too?

https://www.npmjs.com/package/apollo-codegen

**Comment by martijnwalraven** [comment]
Oh, I'm sorry, it was supposed to have been published but something seems to have gone wrong. Just tried again and I think it should be there now.

**Comment by piemonte** [comment]
np – thanks much! was able to install and compile successfully, appreciate the help!

**Comment by MaximusMcCann** [comment]
Compiling here now, cheers
