### ISSUE TITLE
[v1.0.0 Alpha] 'Sendable' class 'JavaScriptError' cannot inherit from another class other than 'NSObject'

### ISSUE THREAD

**Issue by TizianoCoroneo** [apollographql/apollo-ios#2146]
## Bug report

I'm trying out the new alpha version for v1.0.0 using Xcode 13.3 beta. I encountered this error while trying to run the codegen using Swift Scripting.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: v1.0.0-alpha-1
- Xcode version: 13.3 beta 1
- Swift version: 5.6
- Package manager: SPM

## Steps to reproduce

Try to run a Swift Scripting setup of the Apollo codegen.

<img width="1073" alt="Screen Shot 2022-02-09 at 12 20 22" src="https://user-images.githubusercontent.com/15340382/153190574-16cc92d7-e2a7-4a77-8bdd-6215df75da74.png">

**Comment by calvincestari** [comment]
Thanks for digging into the alpha so quickly @TizianoCoroneo and for the PR, much appreciated.

**Comment by TimoWaelischIdealo** [comment]
The issue already exists on v0.5.0 with Xcode 13.3 beta 1.

**Comment by Jerrot** [comment]
The issue already exists on v0.5.0 with Xcode 13.3 beta 1.

**Comment by calvincestari** [comment]
@Jerrot - this is now fixed in `main`, it will go out in release `0.51.0` if you need a tagged release.
@TizianoCoroneo - I've also merged `main` into `release/1.0` so the alpha has the fix too.

**Comment by Jerrot** [comment]
Great, thanks @calvincestari

**Comment by deepcodingios** [comment]
I could see this error getting resolved but I am facing "**Missing package product 'ApolloCore'**" error now.

**Comment by andyBettis** [comment]
I'm seeing this issue with Xcode 13.3 (13E113) using 0.41.0. If I move up to 0.51.0 I get a whole bunch of errors. Any advice?

**Comment by TimoWaelischIdealo** [comment]
> I'm seeing this issue with Xcode 13.3 (13E113) using 0.41.0. If I move up to 0.51.0 I get a whole bunch of errors. Any advice?
The latest release is 0.51.2, maybe try that first. Works just fine here with Xcode 13.3.

**Comment by calvincestari** [comment]
@andyBettis it really depends on what those errors are. There are a lot of breaking changes between `0.41.0` and `0.51.0`.

**Comment by andyBettis** [comment]
Yes, all sorted, I just had to follow the changes. Thanks for your help.

**Comment by jcwoodard-chwy** [comment]
I am still getting this issue after upgrading to 0.51.2 and I'm using Xcode 13.3.  What is causing this?

error: 'Sendable' class 'JavaScriptError' cannot inherit from another class other than 'NSObject'

**Comment by calvincestari** [comment]
I'm really not sure @jwoodard4-chwy. Take a look at the code in your dependency version of `apollo-ios/Sources/ApolloCodegenLib/Frontend/JavaScriptBridge.swift`. Verify that you've got `@unchecked Sendable` in the definition of `JavaScriptError`.

**Comment by strahinja-mem** [comment]
> 

I'm having the same problem here. I did check `JavaScriptBridge.swift` and I do have `@unchecked Sendable`.

**Comment by calvincestari** [comment]
Are you able to replicate this in a standalone sample project you could share with me? I'm not able to reproduce the error on the latest version.

**Comment by donnywdavis** [comment]
We just updated to from version 0.39.0 to 0.51.2 and I am seeing this error now. We are still using Xcode 13.1. The weird thing for us, is that I only see this error in our CI environment, but everything works fine locally. 🤔

**Comment by strahinja-mem** [comment]
> Are you able to replicate this in a standalone sample project you could share with me? I'm not able to reproduce the error on the latest version.

I invited you to a sample project, you can take a look. 👍🏻

**Comment by calvincestari** [comment]
The latest release is [2.34.0](https://github.com/apollographql/apollo-tooling/releases/tag/apollo%402.34.0) however apollo-ios is [pinned to use 2.33.9](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/CLIDownloader.swift#L9).

@strahinja-mem it would be worth it to try again removing any interim build, I've found that to be the most problematic.

**Comment by strahinja-mem** [comment]
> The latest release is [2.34.0](https://github.com/apollographql/apollo-tooling/releases/tag/apollo%402.34.0) however apollo-ios is [pinned to use 2.33.9](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/CLIDownloader.swift#L9).
> 
> @strahinja-mem it would be worth it to try again removing any interim build, I've found that to be the most problematic.

Sure, I can try that - What do you mean by interim build?

**Comment by calvincestari** [comment]
The prebuilt artifacts that the compiler uses to speed up compilations between builds. In an Xcode project these are probably in the DerivedData folder and on an SPM project they're in the `.build/` and `.swiftpm/` folders.

**Comment by strahinja-mem** [comment]
I delete `/DerivedData` at least once a month, and I did try removing `~/Library/Caches/org.swift.swiftpm/` now, unfortunately, no luck. 😕

**Comment by strahinja-mem** [comment]
I don't see those, tried searching too.

<img width="390" alt="Screenshot 2022-06-19 at 7 35 35 PM" src="https://user-images.githubusercontent.com/89936597/174493482-4c4bd486-ebbe-4e96-ba51-132e6a376d7b.png">

**Comment by calvincestari** [comment]
@strahinja-mem are you able to replicate this build error in a new standalone project?

**Comment by strahinja-mem** [comment]
I tried running the same project on a different Mac, and it worked, so yeah, this has something to do with my cache. The question is, which cache since I tried both reinstalling the Xcode and re-cloning the repo. 🤔

**Comment by ahaTB** [comment]
@strahinja-mem Any updates on this issue?

**Comment by strahinja-mem** [comment]
No unfortunately, I still run the script from my older Mac.
