### ISSUE TITLE
errors from GraphQLResult is always nil

### ISSUE THREAD

**Issue by ramonilho** [apollographql/apollo-ios#216]
I'm trying to treat some errors that I've customized, following the pattern below.
```
{  
   "errors":[  
      {  
         "message":"NOT FOUND",
         "locations":[  
            {  
               "line":2,
               "column":3
            }
         ],
         "path":[  
            "user"
         ],
         "code":404
      }
   ],
   "data":null
}
```
When I perform a mutation, my resultHandler have `response:
 <GraphQLResult<GraphQLSelectionSet>?>` and `error:<Error?>`. In cases that I get an error from server, the only way that I have is by reading `error.localizedDescription`, because my `response?.errors` is always nil. Which is really bad because I need to get each attribute (like `code`, `message`) separately. Is that a bug? Or there is another way of doing it?

**Comment by martijnwalraven** [comment]
Even if `data` is `null`, you should still get the errors as part of the result. So I'm not sure why `result?.errors` would be `nil`. What version of Apollo iOS are you running?

**Comment by martijnwalraven** [comment]
Oh wait, are you maybe setting the HTTP status code to a non-success code?

**Comment by ramonilho** [comment]
@martijnwalraven I'm using Apollo `0.7.0`. When we get errors, GraphQL returns http status code `500`, and we put our backend http status in that `code` attribute.

**Comment by martijnwalraven** [comment]
Hmmm, I think we currently don't attempt to parse the response unless the status code is successful, see [here](https://github.com/apollographql/apollo-ios/blob/2fedfb2fef698ce3e5325046de3ffef186355e62/Sources/Apollo/HTTPNetworkTransport.swift#L89).

**Comment by designatednerd** [comment]
Since this involves a pretty old version of our SDK, I'm going to close this out as outdated. If you're still having issues around this, please open a new issue and I'll get a look at it!
