### ISSUE TITLE
HTTPNetworkTransport reference on jazzy

### ISSUE THREAD

**Issue by amadeu01** [apollographql/apollo-ios#2165]
`HTTPNetworkTransport` was removed [here](https://github.com/apollographql/apollo-ios/commit/5a23ee81198ade46b2c7dd483666a64299ee9581)

However, it is still referenced on  _jazzy_
https://github.com/apollographql/apollo-ios/blob/f409e810c908c374aa1466ae16cd9ebfcabf1b77/.jazzy.yaml#L32

Should we remove it from `.jazzy.yaml`?

**Comment by calvincestari** [comment]
Hi @amadeu01, I'm not certain we even support Jazzy anymore. Given i[ts last update](https://github.com/apollographql/apollo-ios/commits/main/.jazzy.yaml) and a [PR to change to Markdown style docs](https://github.com/apollographql/apollo-ios/issues/622) was more recent I suspect that entire yaml file is out-of-date.

**Comment by calvincestari** [comment]
cf713c1d removes the jazzy yaml file. It predates my time at Apollo but I've asked around it seems like apollo-ios does not support Jazzy for documentation. There is also no other reference to Jazzy in the codebase either, besides that yaml file. I'm closing this issue for now but if you believe this is a mistake please let me know.
