### ISSUE TITLE
Codegen CLI

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-ios#2166]
- Swift command line tool
  - JSON file input
  - JSON file string
  - arguments (from convenience initializers
- Parameters
  - JSON input path
    - Default is path of execution
  - High level convenience parameters
    - Too many parameters to provide for all config options. _Full config is supported via the JSON input file._
- Command to dump standard configuration to json file
  - Let user specify output path 
- Available via Homebrew and GitHub Releases
  - _See if CI can handle this workflow_
- Refactor ApolloCodegenConfiguration options into the following groups
  - Input / output / rules / experimental
    - _Need a better name than 'rules'_
  - Verify that the passing around of config is efficient in ApolloCodegen with the new groups
- Compile the Apollo codegen lib with optimization (`-O unchecked`)
- Can we use Package Manager Extensive Build Tools ([SE-0303](https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md)).

**Comment by calvincestari** [comment]
#2166 is the bulk of this work. Still to do is refining the build configuration for release builds and creating a Formula for getting the executable added to Homebrew.

**Comment by hwillson** [comment]
Done (excluding homebrew work broken out in https://github.com/apollographql/apollo-ios/issues/2305). Thanks!
