### ISSUE TITLE
Experimental Client Controlled Nullability support

### ISSUE THREAD

**Issue by twof** [apollographql/apollo-ios#2171]
## Feature request

Support for [Client Controlled Nullability](https://github.com/graphql/graphql-js/pull/3418).
Spec: https://github.com/graphql/graphql-spec/pull/895
Client Controlled Nullability (CCN) is still in Stage 1 of the RFC process, but has gotten the go-ahead to be released on an experimental basis. I would be happy to begin doing the integration for Apollo iOS.

## Motivation

CCN is a highly requested feature. Apollo Android introduced @required which is basically an equivalent. The intent is to get early feedback from real world use cases. 

## Proposed solution

CCN is going to be introduced in parts as they go through review, starting with code for parsing and validation, which is enough to do code generation. The feature is available behind [a parameter](https://github.com/graphql/graphql-js/pull/3418/files#diff-297a41e54c25bbd5c846bb55d7acaaca9f2c9f5fa654b19004da4efbf9a88154R123) so it can be turned off and on as needed. It's being released in the form of unstable canary releases, so there is no guarantee with regards to breaking changes. CCN is likely to evolve as aspects of it fall in and out of favor with the GraphQL working group. 

With the current implementation, code generation should more or less work out of the box. Decisions will need to be made around caching behaviour.

## Outstanding Questions

Should we branch off of the WIP 1.0 branch? Could CCN support be a part of 1.0?
Tagging @AnthonyMDev since he said [we should talk when we were ready to start integrating.](https://github.com/apollographql/apollo-ios/pull/1876#issuecomment-989053888)

**Comment by AnthonyMDev** [comment]
Really excited about this! I think it would only make sense to add it in 1.0. You can branch off the `1.0-alpha-incubating` branch to being work on this. We'll be merging things into that branch pretty regularly as we work on 1.0, so rebasing will need to be frequent. It's not a stable branch yet (hence alpha), so I don't want to create too much churn for you on the implementation as things change on our side.

I'm happy to help explain anything about what we are doing or how the code for 1.0 works. I suspect the bulk of the work for this is going to be in Code Generation engine, which is quite a complex beast.

**Comment by calvincestari** [comment]
Excited to see this progress, thanks for championing it!

**Comment by twof** [comment]
I think I've got the parsing step working: https://github.com/apollographql/apollo-ios/pull/2172

I've got it throwing errors if you try to use CCN syntax without CCN enabled, and generating something otherwise, although it looks like it's generating stuff with the wrong nullability. I'll keep debugging later.

**Comment by twof** [comment]
@AnthonyMDev @calvincestari 
I’m going to try and hold a vote on which behavior to move forwards with tomorrow at the working group meeting. If you’d like to have a say, please attend. 

I’ll allow proxy votes for people in the same org on the behalf of anyone who has already participated in CCN discussion, so a representative from Apollo can submit votes on the behalf of Anthony Miller, Martin Bonnin, Brian Kim, Ivan Goncharov and Hugh Willson.

I’ve linked discussions for the behavior we’ll be voting on in the meeting agenda here: https://github.com/graphql/graphql-wg/blob/main/agendas/2022/2022-03-03.md

**Comment by twof** [comment]
CCN Support added in Alpha 4 via https://github.com/apollographql/apollo-ios/pull/2178
