### ISSUE TITLE
Facing issues with fragments generated code and queryDocument: String

### ISSUE THREAD

**Issue by cbruns1985** [apollographql/apollo-ios#2180]
## Bug report

We are trying to use fragments. Unfortunately the generated code contains issues, which do not allow to compile.

Actually the generated code looks like this:
```
public var queryDocument: String {
    var document: String = operationDefinition
    document.append("
" + OurFragmentType.fragmentDefinition)
    return document
  }
```
the new line within the empty string resolves in this issue.

Actually we noticed that in the definition the string starts with `\n`, which seems to be wrongly escaped.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.50.0
- Xcode version: 13.2.1
- Swift version: 5
- Package manager: Apple Native Dependency Manager

## Steps to reproduce

```
fragment OurType on OurType {
  name
}

query OurQuery() {
  funcDefinition() {
    something {
      ...OurType
    }
  }
}
```
## Further details

Please replace this line with any further details or context necessary to understand the problem. Delete this section if you don't have anything further to add.

**Comment by AnthonyMDev** [comment]
It is insane to me that this issue has never come up before now. Haha. Thank you for the report.

If you change your query at all, does it change this? This has been working until now perfectly for everyone, and we haven't changed the code generation in anyway. Trying to deduce the cause of this issue.

We are actively in the process of re-writing the entire code generation engine in Native swift, so this won't be a problem when that releases. The 1.0 Alpha releases that are up currently use the new code generation engine.

**Comment by cbruns1985** [comment]
Actually we were not able to fix this issue by changing anything in the query, depth or something similar. Currently we are using a post script, which solves the issue. Previously we had just no fragments but a lot of wrappers in our code ;-).

Actually we were wondering as well, why nobody noticed - or nobody reported.

Thank you for your fast response. Seems like you are able to see the issue and/or reproduce it.

**Comment by calvincestari** [comment]
>Thank you for your fast response. Seems like you are able to see the issue and/or reproduce it.

@cbruns1985 I'm not able to reproduce any compilation error. I can reproduce the same generated code for `queryDocument` but it builds fine. Could you share more details about the compile error please - thanks.

**Comment by AnthonyMDev** [comment]
Yes, sorry if there was confusion, I am NOT able to reproduce the error either.

**Comment by cbruns1985** [comment]
The compilation error is explicitly related with the generated code.

Xcode cannot build an unterminated string literal.

Means our API.swift is generated but cannot be used without manual updates.

**Comment by calvincestari** [comment]
@cbruns1985 are you using any other tooling in your build process? I can replicate the generated code with a new sample project except mine is not an actual new line, it contains `"\n"`, the same as the [generated code we have within the project](https://github.com/apollographql/apollo-ios/search?q=%22document.append%28%22&type=code).

I agree with @AnthonyMDev that it's very odd this has never been reported before. Is there anything else in your build pipeline that could be contributing to this?

**Comment by cbruns1985** [comment]
I asked my colleagues yesterday, which told me this cannot be related. Had a look my self. Somebody modified with echo and cat - therefore the interpretation of the "\n" was used within the file.

Thank you for your help.
