### ISSUE TITLE
Add Apollo iOS graphql-ws example to the main repo README

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-ios#2186]
See: https://github.com/enisdenjo/graphql-ws/issues/325

**Comment by calvincestari** [comment]
The PR is up at https://github.com/enisdenjo/graphql-ws/pull/335.

**Comment by calvincestari** [comment]
Closing this issue with https://github.com/enisdenjo/graphql-ws/pull/335 now merged. 🎉 

cc. @glasser
