### ISSUE TITLE
Support better mocking of generated selection sets

### ISSUE THREAD

**Issue by klanchman** [apollographql/apollo-ios#2187]
## Feature request

Add a memberwise initializer for generated `SelectionSet` types.

## Motivation

Apollo v0.x created memberwise initializers for selection sets, but the v1 alpha does not. The old behavior was useful to me for setting up mock data for using Xcode Previews.

A lot of UI components I write have parameters that are `SelectionSet`s or that contain `SelectionSet`s. Lately I've been adding Xcode Previews to new UI components so I can quickly verify that the component renders how I expect. Having a memberwise initializer for `SelectionSet` allows me to have a mock instance of my data to pass to the component for previewing.

While I think it'd be possible for me to use the `init(data:)` initializer to accomplish this, doing so would be hard to maintain.

**Comment by AnthonyMDev** [comment]
Thanks for the request @klanchman. The member-wise initializers were pretty messy and didn't make it super easy to create mocks. While they were better than using `init(data:)`, it was still really clunky. We're trying to come up with a better way to create mock objects for 1.0. It's not built yet, but there will be something that makes this easier for you prior to the 1.0 official release!

**Comment by klanchman** [comment]
That sounds nice! My selections are pretty small, relatively speaking, so the memberwise was usually good enough, but very interested to see what you come up with.
I’ll leave it up to you how to handle this issue, i.e. close it versus rename to reflect the new approach 👍

**Comment by AnthonyMDev** [comment]
1.0 Alpha 5 was just released which provides support for better mocking! We'd love feedback on how that works out for you!
