### ISSUE TITLE
ApolloCodegenLib support Authorization Header for token to download package

### ISSUE THREAD

**Issue by wmalloc** [apollographql/apollo-ios#2189]
## Feature request

Provide a way to add an authorization header to URL to download the schema

## Motivation
We have a private repository that requires authentication to download the schema,

## Proposed solution

I would like to propose either take a URLRequest as an argument instead of URL or provide arguments to pass in header items

**Comment by Mycro1ce** [comment]
@wmalloc there are already support for httpHeaders.

`let header = ApolloSchemaDownloadConfiguration.HTTPHeader(key: "key", value: "value")`
      
`let schemaDownloadOptions = ApolloSchemaDownloadConfiguration(using: .introspection(endpointURL: endpoint), headers: [header], outputFolderURL: folderForDownloadedSchema)`

**Comment by calvincestari** [comment]
Thanks for the support @Mycro1ce, I'm going to close this issue since the ability already exists.
