### ISSUE TITLE
The latest released version of apollo-codegen doesn't work with the latest released version of apollo-ios

### ISSUE THREAD

**Issue by x1024** [apollographql/apollo-ios#221]
I used apollo-ios 0.8.0 and apollo-codegen 0.19.0

Steps to reproduce:
* Create an iOS project that uses Apollo
* Follow the instructions for Apollo Codegen by using the "introspect-schema" and then "generate" command
* The resulting iOS project will not compile.

The problem stems from a recent change that apparently renames the "Snapshot" typealias to "ResultMap".  

The change was done simultaneously in both projects 6 days ago, and a new NPM package was released for apollo-codegen. However, the latest apollo-ios tag was created 18 days ago.

I was able to get the code to compile by loading a specific commit - I used dd478b2, but others could work as well.

**Comment by martijnwalraven** [comment]
Hmmm, if you use Apollo iOS 0.8.0, the required version of `apollo-codegen` should still be set to 0.18.x, this was only [changed to 0.19.x](https://github.com/apollographql/apollo-ios/commit/fa7b951bbf1bbf830812cd2dd5ac1966890e2663) after.

Are you using the `check-and-run-apollo-codegen.sh`script as instructed, or are you running `apollo-codegen` manually? The script was designed to make sure the version you're running is compatible with the Apollo iOS framework version in your project.

**Comment by x1024** [comment]
I am not using check-and-run-apollo-codegen.sh

Unfortunately, the text in the README gives instructions to install apollo-codegen via NPM, and doesn't mention that script: https://github.com/apollographql/apollo-ios#apollo-codegen

(I would also note that when using a package manager, that script isn't in a place where it can be seen by a user that isn't actively looking for it)

**Comment by martijnwalraven** [comment]
Ah, you're right, we should update the documentation. The script used to only check the version installed, but it will now also download the right version when needed.

[This](https://www.apollographql.com/docs/ios/installation.html#adding-build-step) is the step that invokes `check-and-run-apollo-codegen.sh`.

Regardless of how you install `apollo-codegen`, I would advise to always use that script, because it ensures you're running a compatible version.

**Comment by x1024** [comment]
Thank you, I will.

Given that the current version of the iOS code seems stable, perhaps it
would be a good idea to also add a tag for a new version of apollo-ios?
And perhaps it would be a good idea to keep the (major and/or minor)
version numbers between the two tools in sync, so there's no confusion as
to which version of one repo works with which version of the other one?

Fixing the README is probably enough, but I just thought I'd give my 2c.

**Comment by abdullahumer** [comment]
I am facing a build error:

```
++ exec apollo-codegen generate --schema schema.json --output API.swift
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/usr/local/lib/node_modules/apollo-codegen/src/cli.js:186:17)
    at Object.runCommand (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/apollo-codegen/lib/cli.js:197:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
Command /bin/sh failed with exit code 1

```

Is this because of this same issue?

**Comment by Shieghtun** [comment]
@abdullahumer Looks like you are not providing any .graphql files, that's why you are facing your  issue. But still your issue is different.

**Comment by dearprakash** [comment]
@Shieghtun Is it mandatory to provide .graphql file in this step?

**Comment by dearprakash** [comment]
I learnt: Without .graphql files (query or mutation), there is no code to generate, so Yes.
