### ISSUE TITLE
Missing package product 'ApolloCore'

### ISSUE THREAD

**Issue by deepcodingios** [apollographql/apollo-ios#2213]
## Versions

0.51.0

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.51.0
- Xcode version: 13.3
- Swift version: Swift 5
- Package manager: SPM

## Steps to reproduce

Updated the SPM to 0.51.0 from 0.43.0. I am getting this error after updating.

**Comment by calvincestari** [comment]
Hi @deepcodingios-  👋🏻

The missing package `ApolloCore` is correct, it was split in `0.44.0`. It is detailed as a breaking change in the [release notes](https://github.com/apollographql/apollo-ios/releases/tag/0.44.0).

tl;dr
> BREAKING: Split `ApolloCore` into two more granular libraries, `ApolloAPI` (which will contain the parts necessary to compile generated code) and `ApolloUtils` (which will contain code shared between `Apollo` and `ApolloCodegenLib`). If you were previously importing `ApolloCore`, in most places you will need to import `ApolloUtils`. If you're using Carthage, you will need to remove the old `ApolloCore` xcframework and replace it with the two `ApolloAPI` and `ApolloUtils` frameworks. (https://github.com/apollographql/apollo-ios/pull/1817)
