### ISSUE TITLE
How to get response object from GraphQLOperation?

### ISSUE THREAD

**Issue by ghost** [apollographql/apollo-ios#222]
Is there any way to get a reference to response object? I would like to read a custom HTTP header from that objects.

**Comment by djriefler** [comment]
Any update here? I am running into a similar problem

**Comment by martijnwalraven** [comment]
See the discussion on https://github.com/apollographql/apollo-ios/pull/223.

**Comment by designatednerd** [comment]
This is now supported via the `HTTPNetworkTransportTaskCompletedDelegate` released in 0.11.0 - you can hook in through that and access your headers from there.
