### ISSUE TITLE
Unable to generate code with non-nullable value

### ISSUE THREAD

**Issue by cheif** [apollographql/apollo-ios#2220]
Hi! When trying out the new codegen on our project I get a crash when trying to generate code for an `INPUT_OBJECT`, the object looks like this:
```
{
  "kind": "INPUT_OBJECT",
  "name": "MyInput",
  "description": null,
  "fields": null,
  "inputFields": [
    {
      "name": "thisIsTheId",
      "description": null,
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "SCALAR",
          "name": "UUID",
          "ofType": null
        }
      },
      "defaultValue": null
    }
  ],
  "interfaces": null,
  "enumValues": null,
  "possibleTypes": null
}
``` 

What happens is that I get a crash on [`JavaScriptBridge.swift:200`](https://github.com/apollographql/apollo-ios/blob/9729f7431c6003b2b61e694e1bf94b8038069cb6/Sources/ApolloCodegenLib/Frontend/JavaScriptBridge.swift#L200), saying that `jsValue` is `undefined`. Tracing the crash back a bit it seems to be because we're trying to resolve the default value (although using a field called [`astNode`](https://github.com/apollographql/apollo-ios/blob/9729f7431c6003b2b61e694e1bf94b8038069cb6/Sources/ApolloCodegenLib/Frontend/GraphQLSchema.swift#L78)), but this is undefined.
Going even further up this seems to be called because [`isSwiftOptional`](https://github.com/apollographql/apollo-ios/blob/9729f7431c6003b2b61e694e1bf94b8038069cb6/Sources/ApolloCodegenLib/Templates/RenderingHelpers/GraphQLInputField%2BRendered.swift#L8) returns true for this `INPUT_OBJECT`.

With my limited understanding it seems like maybe `isSwiftOptional` is the culprit here, and maybe the conditional has gotten mixed up.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0-alpha.2
- Xcode version: XCode 13.3
- Swift version: 5.6
- Package manager: SPM

## Steps to reproduce

Run new codegen on a schema defining optional values, but I assume this just happens in some cases.

**Comment by calvincestari** [comment]
Thanks for letting us know @cheif, we'll look into it.

**Comment by AnthonyMDev** [comment]
Really really appreciate this bug report! Thank you for testing the Alpha. We will definitely get this sorted out for a soon to come alpha release!

**Comment by AnthonyMDev** [comment]
I'm pretty sure this is fixed in the new Alpha 3 that just went live! Please test the new version and let us know if you are still encountering this issue!

**Comment by cheif** [comment]
Hey!

I just tried this out with Alpha 3, and I think this might be fixed, at least I'm not getting an error at that line any more.

Instead I'm getting `Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value` at [SelectionSetTemplate.swift:400](https://github.com/apollographql/apollo-ios/blob/1.0/alpha-3/Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift#L400), but I'm not really sure why (the `next` that's force-unwrapped on that line is `nil` though). I tried to reduce it down to something to share with you, but I was unsuccessful. I think it might have something to do with nested fragments though, if that's something that you already know?

**Comment by calvincestari** [comment]
@cheif can you check whether this is still an issue for you on the latest alpha release - alpha 5 at the moment.

**Comment by cheif** [comment]
@calvincestari I've tested this out now, and it's indeed still a problem. I dug some more into it, and it seems to be related to us having an `interface` that we're then querying using `fragments`, something that works with the old codegen.

I managed to reproduce it in a testcase here: https://github.com/cheif/apollo-ios/tree/codegen/interface-containing-fragments, maybe that'll give you some more insights?

**Comment by AnthonyMDev** [comment]
Thank you so so much for giving us a test case! We will get this fixed in an Alpha release coming soon!

**Comment by calvincestari** [comment]
That test case was super helpful, thanks again @cheif! 🥇

**Comment by cheif** [comment]
Great! I've verified that this works for our codebase now as well 😄
