### ISSUE TITLE
Swift Scriptings Pauses Automatic Previews

### ISSUE THREAD

**Issue by asbhat** [apollographql/apollo-ios#2256]
## Bug report

When using [swift scripting](https://www.apollographql.com/docs/ios/swift-scripting) to generate code, after adding it to the [build phase](https://www.apollographql.com/docs/ios/swift-scripting#running-code-generation-from-your-main-project) of the target, SwiftUI previews will continuously be paused.

<img width="726" alt="auto-preview-paused" src="https://user-images.githubusercontent.com/3885798/164875305-38191bfd-e474-4998-8970-42d802f2a3ba.png">

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: `v0.51.2`
- Xcode version: `v13.3.1`
- Swift version: `v5.6`
- Package manager: SPM

## Steps to reproduce

1. Install and setup [Swift scripting](https://www.apollographql.com/docs/ios/swift-scripting)
2. Make sure `$ swift run ApolloCodegen generate` runs successfully
3. Add a run script to the build phase, as detailed [here](https://www.apollographql.com/docs/ios/swift-scripting#running-code-generation-from-your-main-project)
4. Notice SwiftUI previews will continue to pause themselves

**Comment by calvincestari** [comment]
Thanks for raising the issue @asbhat, let's keep the conversation in the PR for now - #2257
