### ISSUE TITLE
GraphQL Cache policy in swift not working

### ISSUE THREAD

**Issue by dikenshah1212** [apollographql/apollo-ios#226]
**CachePolicy.returnCacheDataAndFetch not working**

In my application, I am using graphQL using Apollo client framework. An application has offline support and for this, I am using "returnCacheDataAndFetch" cache policy but unfortunately, It's not working in the app. Below is my query string.

```
query fetchCompanyUsers {
    company {
        id
        users {
            totalCount
            edges {
                node {
                    id
                    firstName
                    lastName
                }
            }
        }
    }
}
```
When I debug code It always fetch data from network not from cache. Below is my code of initialize apolloclient object

```
let apollo = ApolloClient(url: URL(string: graphQLEndpoint)!)
apollo.cacheKeyForObject = { $0["id"] }
```
But every time it fetch from server not from cache. I am stuck in this issue but no luck found.

Thank you.

**Comment by martijnwalraven** [comment]
It seems you haven't actually configured the SQLite store. The default cache is in memory only.

**Comment by dikenshah1212** [comment]
Thanks for your quick reply. 

I am very thankful ro you if you share demo or link how to configure Sqlitestore in ios swift using apollow client.

**Comment by dikenshah1212** [comment]
I have tried with below code but got same result

```
let store = ApolloStore(cache: InMemoryNormalizedCache())
        store.cacheKeyForObject = { $0["id"] }
        let configuration = URLSessionConfiguration.default
        
        let apollo = ApolloClient(networkTransport: HTTPNetworkTransport(url: URL(string: graphQLEndpoint)!, configuration: configuration), store: store)
```
Please let me know if I missed something.

**Comment by martijnwalraven** [comment]
You're still using the `InMemoryNormalizedCache`, so you'd want that to be [`SQLiteNormalizedCache`](https://github.com/apollographql/apollo-ios/blob/master/Sources/ApolloSQLite/SQLiteNormalizedCache.swift). Depending on your installation method, you may have to add `pod 'Apollo/SQLite'` or `ApolloSQLite` framework.

Note that I consider the SQLIte cache experimental because it hasn't been worked on in a long time. People are using it, but you should probably be prepared to fix issues yourself if you run into them.

**Comment by designatednerd** [comment]
I'm going to close this out since it appears the issue was with configuration. If you're still having problems, please open a new issue (although be aware that the SQLite stuff needs a bit of love at the moment).
