### ISSUE TITLE
[v1.0.0 alpha] Inline fragment "asType" converters can pick the wrong type

### ISSUE THREAD

**Issue by klanchman** [apollographql/apollo-ios#2261]
## Bug report

When using inline fragments on a union type, the generated `asSomeType` properties can return a non-nil value in situations where I expect nil.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0-alpha.4
- Xcode version: Version 13.3 (13E113)
- Swift version: 5.6.1
- Package manager: SPM

## Steps to reproduce

1. Query a field that is a union type, and use inline fragments to get the data that you want. In my case, the members of the union all have similar data, with a couple fields specific to each type.
2. Attempt to figure out what kind of item you're looking at by using the `asSomeType` properties
3. Access a type-specific field

Expected: on step 2, if the type of the item is not `SomeType` (according to its `__typename`), the property is `nil`

Actual: on step 2, `SomeType` is returned even if the `__typename` indicates it is actually `SomeOtherType`. This causes the type-specific field in step 3 to always be `nil` if the field is nullable, or crash if the field is not nullable.

Pre-v1.0 behaved as expected.

## Further details

Here's the API I'm using: https://anilist.co/graphiql
I'm querying `Page.notifications`, which returns an array of `NotificationUnion`.
Apollo generates something like this for the response:

```swift
public struct Data: AniListAPI.SelectionSet {
    public struct Page: AniListAPI.SelectionSet {
        public struct Notification: AniListAPI.SelectionSet {
            public var asActivityLikeNotification: AsActivityLikeNotification? { _asInlineFragment() }
            public var asActivityReplyNotification: AsActivityReplyNotification? { _asInlineFragment() }
            // and other Activity-related things...
            public var asMediaDataChangeNotification: AsMediaDataChangeNotification? { _asInlineFragment() }
            // and so on...
        }
    }
}
```

Later, I try to use these `asSomeType` properties to clean up the data and display it. That code looks something like this:

```swift
init?(
    rawNotification: GetNotificationsQuery.Data.Page.Notification
) {
    if let rawNotification = rawNotification.asActivityLikeNotification {
        // rawNotification now has `activity` property,
        // and I know someone liked it
    } else if let rawNotification = rawNotification.asActivityReplyNotification {
        // rawNotification now has `activity` property,
        // and I know someone replied to it
    } else if /* other Activity-related ones... */ {
    } else if let rawNotification = rawNotification.asMediaDataChangeNotification {
        // rawNotification now has `mediaId` property,
        // and never an `activity` property
    } else if /* and so on... */ {
    }
}
```

The issue I'm seeing is that I could looking at an `ActivityReplyNotification`, but `asActivityLikeNotification` returns a non-nil value, so I enter the wrong branch.

Here's an example item:

```json5
{
  "__typename": "ActivityReplyNotification",
  "activity": {
    "__typename": "MessageActivity",
    "id": 247640517,
    "siteUrl": "https://anilist.co/activity/247640517"
  },
  // and other stuff...
}
```

This item—despite being an `ActivityReplyNotification`—has a non-nil value for `asActivityLikeNotification` and even `asMediaDataChangeNotification`:

```
(lldb) po rawNotification.__typename
"ActivityReplyNotification"

(lldb) po rawNotification.asMediaDataChangeNotification == nil
false
```

Worse, entering the wrong branch and accessing a type-specific non-nullable field causes a crash (`mediaId` is an `Int!` in the schema):

```
(lldb) po rawNotification.asMediaDataChangeNotification?.mediaId
Could not cast value of type 'Swift.Optional<Any>' (0x1dea1d1d8) to 'Swift.Int' (0x1dea185d0).
2022-04-30 19:01:35.391158-0400 Ryuusei[37814:2674522] Could not cast value of type 'Swift.Optional<Any>' (0x1dea1d1d8) to 'Swift.Int' (0x1dea185d0).
error: Execution was interrupted, reason: signal SIGABRT.
The process has been returned to the state before expression evaluation.
```

I would expect all properties to return nil other than `asActivityReplyNotification`, since that's the type of the item I'm looking at.

**Comment by klanchman** [comment]
Separate but related, part of the work this code is doing is converting the result to an enum. I'd love if Apollo gave me the result as an enum to start, since the `asSomeType` checks are error prone. (I found a bug in my app recently where I accidentally repeated the same type twice and omitted a type 😓)

Apollo generated code for `NotificationUnion` as an enum, but I'm not sure how I can get something similar for my query result. Is that something that's available in v1 that I'm just not aware of, or should I open a feature request?

**Comment by AnthonyMDev** [comment]
This is an awesome bug report! Looking into this now! Thank you for the info.

**Comment by AnthonyMDev** [comment]
As for your second question about the enum, it is a planned feature we want to add in the near future to allow you to configure unions to generate an enum as you are describing! Probably won't make it into 1.0.0, but will be added after for a 1.1 or 1.2.

**Comment by AnthonyMDev** [comment]
I've verified this behavior is broken. It was working up until I broke it while implementing include/skip. This has surfaced a gap in our testing though. I'm writing some tests for this behavior and fixing the broken code. I'll be pushing a fix to the `release/1.0` branch soon.

**Comment by AnthonyMDev** [comment]
This should be fixed in the release branch now! It will get pushed with the next alpha release. In the mean time, you can point your dependency to the `release/1.0` branch to get the most up to date changes.

**Comment by klanchman** [comment]
Looks like that worked for me, thanks for the quick fix @AnthonyMDev 😄 

Great to hear about the planned enum option, that'll be nice to have!
