### ISSUE TITLE
Add folder structure to files generated into `Operations` folder

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2285]
We can do better by adding sub-categories to the generated files in the Operations folder.
- `--` is existing, `++` is new to add.
- Note that `Fragments` is on the same level as `Operations`, no longer within it.

```
-- Operations
   ++ Queries
   ++ Mutations
   ++ Subscriptions
   ++ LocalMutations
++ Fragments
```

**Comment by AnthonyMDev** [comment]
Note that this is only true for `inSchemaModule`.

For `absolute`, we should do:
```
{absolutePath}
   ++ Queries
   ++ Mutations
   ++ Subscriptions
   ++ LocalMutations
   ++ Fragments
```

Where Fragments are just in the same folder as the operations.

For relative, no changes are needed, as your generated files will be next to the associated `.graphql` file.

**Comment by calvincestari** [comment]
This is done with the merging of #2331
