### ISSUE TITLE
Publish CLI via homebrew

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-ios#2305]
Broken out from https://github.com/apollographql/apollo-ios/issues/2166.

**Comment by calvincestari** [comment]
Following up here that this is complete but we will only be able to submit the formula to Homebrew/core once 1.0.0-alpha.8 is released.

**Comment by calvincestari** [comment]
With the work to be done in #2381 there is a good chance we don't need to distribute the CLI via Homebrew and this issue can then be closed. I'll keep it open for now until #2381 is done.

**Comment by hwillson** [comment]
We aiming for the solution proposed in https://github.com/apollographql/apollo-ios/issues/2381 instead, so we'll close this off.
