### ISSUE TITLE
Using Apollo From Vapor App

### ISSUE THREAD

**Issue by danhalliday** [apollographql/apollo-ios#2314]
## Bug report

Is this library intended to work on macOS from a Vapor app? My use case is quite simple — some of the endpoints in my Vapor app make GraphQL calls to another API ([Dato CMS](https://www.datocms.com/docs/content-delivery-api/api-endpoints)) and process and return the data from it.

What I’m seeing is that the client’s `fetch(query:)` call never calls its completion handler. The same client setup and query code works perfectly when I copy and paste it into a blank iOS app.

I get the following logs in Xcode’s console:

<details open>
<summary>SecTask Failure Logs</summary>
<pre>
2022-06-14 11:14:39.466116+0100 Run[87152:1122325] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=87152
2022-06-14 11:14:39.466249+0100 Run[87152:1122325] SecTaskCopyDebugDescription: Run[87152]/0#-1 LF=0
2022-06-14 11:14:39.466285+0100 Run[87152:1122325] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=87152
2022-06-14 11:14:39.466414+0100 Run[87152:1122325] SecTaskCopyDebugDescription: Run[87152]/0#-1 LF=0
</pre>
</details>

And a minute or so later I see evidence the request has failed:

<details>
<summary>TLS Failure Logs</summary>
<pre>
2022-06-14 11:14:54.511903+0100 Run[87152:1122329] Connection 1: received failure notification
2022-06-14 11:14:54.511987+0100 Run[87152:1122329] Connection 1: failed to connect 3:-9816, reason -1
2022-06-14 11:14:54.512021+0100 Run[87152:1122329] Connection 1: encountered error(3:-9816)
2022-06-14 11:15:09.543388+0100 Run[87152:1122329] Connection 2: received failure notification
2022-06-14 11:15:09.543456+0100 Run[87152:1122329] Connection 2: failed to connect 3:-9816, reason -1
2022-06-14 11:15:09.543489+0100 Run[87152:1122329] Connection 2: encountered error(3:-9816)
2022-06-14 11:15:09.578828+0100 Run[87152:1122329] [boringssl] boringssl_context_handle_fatal_alert(1967) [C3.1:2][0x102d8ed20] read alert, level: fatal, description: protocol version
2022-06-14 11:15:09.579100+0100 Run[87152:1122329] [boringssl] boringssl_session_handshake_incomplete(86) [C3.1:2][0x102d8ed20] SSL library error
2022-06-14 11:15:09.579142+0100 Run[87152:1122329] [boringssl] boringssl_session_handshake_error_print(41) [C3.1:2][0x102d8ed20] Error: 4342730504:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:/AppleInternal/Library/BuildRoots/66382bca-8bca-11ec-aade-6613bcf0e2ee/Library/Caches/com.apple.xbs/Sources/boringssl/ssl/tls_record.cc:594:SSL alert number 70
2022-06-14 11:15:09.579206+0100 Run[87152:1122329] [boringssl] nw_protocol_boringssl_handshake_negotiate_proceed(757) [C3.1:2][0x102d8ed20] handshake failed at state 12288: not completed
2022-06-14 11:15:09.579605+0100 Run[87152:1122329] Connection 3: received failure notification
2022-06-14 11:15:09.579648+0100 Run[87152:1122329] Connection 3: failed to connect 3:-9836, reason -1
2022-06-14 11:15:09.579668+0100 Run[87152:1122329] Connection 3: encountered error(3:-9836)
2022-06-14 11:15:09.580044+0100 Run[87152:1122329] Task <0451811C-8E37-4A62-B8E5-1F4FC3187E73>.<1> HTTP load failed, 0/0 bytes (error code: -1200 [3:-9836])
</pre>
</details>

## Versions

- `apollo-ios` SDK version: `0.51.2`
- Xcode version: `Version 13.4.1 (13F100)`
- Swift version: `5.6.1`
- Package manager: `5.6.0`

## Steps to reproduce

- Create a Vapor app
- Add some generated queries and code to setup an Apollo client
- In one of your Vapor routes, try and perform a fetch (`apollo.fetch(query: MyQuery()) { result in ... }`)
- Observe console errors and no completion callback

## Further details

Here’s my client setup code, though I don’t believe the specifics to be relevant as it works on iOS.

```swift
let apollo: ApolloClient = {
    let url = URL(string: "https://graphql.datocms.com")!
    let configuration = URLSessionConfiguration.ephemeral
    configuration.httpAdditionalHeaders = [
        "Authorization": "Bearer 12345"
    ]

    let store = ApolloStore(cache: InMemoryNormalizedCache())
    let client = URLSessionClient(sessionConfiguration: configuration, callbackQueue: .main)
    let provider = DefaultInterceptorProvider(client: client, store: store)
    let transport = RequestChainNetworkTransport(interceptorProvider: provider,
                                               endpointURL: url,
                                               additionalHeaders: ["Authorization": "Bearer 12345"],
                                               useGETForQueries: true)
    return ApolloClient(networkTransport: transport, store: store)
}()
```

I should also mention that if I take the raw request URL that Apollo generates (of the form `https://graphql.datocms.com?operationName=MyQuery&query=query%MyQuery%20%7B%0A%20%20...`) and manually fetch that using a regular data task, that works fine within the same project.

**Comment by jpvajda** [comment]
@danhalliday thanks for letting us know about this issue. I was curious what your vapor application does? Could you share the use cases?

**Comment by AnthonyMDev** [comment]
This is super exciting to me! As of now, we have not officially supported server side usage of apollo-ios, but I'd be happy to help you figure out what's going on here and make it work for your use case. I'm hoping we can provide better support for Vapor in the future.

My first guess here would be that something in the interceptor chain that is built for iOS isn't working right in your setup. Nto sure if that's a Vapor issue a macOS issue, or a combination of the two. In order to figure out where the problem is occuring, I'd need some more debugging done.

If you can provide a sample project that reproduces this issue, I'd be happy to debug it myself. Otherwise, if you can put some breakpoints down and verify if the request is making its way through the entire interceptor chain, that would be a good start. If you look at `DefaultInterceptorProvider:34-40` there are a number of interceptors the request goes through.

Each interceptor should call `chain.proceedAsync()` after it finishes it's job, which should start the next interceptor. Can you  figure out if it's going wrong somewhere in that process?

**Comment by danhalliday** [comment]
> @danhalliday thanks for letting us know about this issue. I was curious what your vapor application does? Could you share the use cases?

Sure, I’m using a headless CMS (Dato) to organise and edit my project’s content. They provide a GraphQL API to retrieve content.

I can consume this direct from my client iOS app if I want (and I probably will). But right now I’m building a backend using Vapor to handle user accounts and a few other duties. In that backend, I also want access to the content from the CMS. I could put all the content management in the Vapor app, but that’s a lot of work and there are a bunch of benefits to pulling from an off-the-shelf headless CMS (even if you’re just pulling to another backend system).

My vision eventually (this could end up being misguided in several levels) was to have a Swift package that wraps up my CMS GraphQL setup and useful queries, that I can import into my client iOS app and other backend systems.

**Comment by danhalliday** [comment]
> Each interceptor should call `chain.proceedAsync()` after it finishes it's job, which should start the next interceptor. Can you figure out if it's going wrong somewhere in that process?

Sure I’ll try and take a look at this. If memory serves I recall the network fetching one did actually complete so it would be further down the chain. I gave up then as my head was still spinning from having also struggled with all the other aspects of the library such as the code gen tools and how to integrate with SPM. But now I have a handle on the rest I can reason about this.

My gut feeling is some aspect of caching or perhaps TLS resolution is trying to write to disk in a way that’s not allowed when running a bare Swift package in Xcode (ie. no entitlements or project file etc).

**Comment by AnthonyMDev** [comment]
> I gave up then as my head was still spinning from having also struggled with all the other aspects of the library such as the code gen tools and how to integrate with SPM. But now I have a handle on the rest I can reason about this.

Totally fair. If this project isn't shipping quite yet, I'd highly recommend that you move over to using our Alpha of the 1.0 release. The generated code is very significantly better than the 0.51 version. The setup for codegen is all done in swift scripting instead of an npm package, also! We just finished building a CLI to wrap the swift codegen scripts so you don't have to write your own Swift scripts (unless you wanna do something very advanced and custom with it). That CLI is working now and will hopefully be published on Homebrew by the end of the week, which should cure some of your headache!

We are seeking to move from Alpha to Beta by July 1st, so things are getting pretty close to stable there. For a new project, I'd recommend it.

**Comment by danhalliday** [comment]
Great thanks, yeah I did see that but thought I’d stick with what I had until I solved my main issue.

FWIW as a possibly useful data point for y’all, this is what I came up with in a few hours as a GraphQL novice after I started to figure out how the tools were organised. The thing that took me the most time was trying to get the order of the arguments right 😂

```shell
# Download Dato’s GraphQL schema and generate a Swift interface.

.build/checkouts/apollo-ios/scripts/run-bundled-codegen.sh schema:download \
  "Sources/App/Dato/DatoSchema.json" \
  --endpoint="https://graphql.datocms.com/" \
  --header="Authorization: Bearer 12345"

.build/checkouts/apollo-ios/scripts/run-bundled-codegen.sh codegen:generate \
  --target=swift \
  --includes=./**/*.graphql \
  --localSchemaFile="Sources/App/Dato/DatoSchema.json" "Sources/App/Dato/DatoQueries.swift"
```

**Comment by AnthonyMDev** [comment]
Yeahhh that looks right, but it's brutal that it took you so long to make it work. That whole system is being scrapped though for 1.0.

**Comment by danhalliday** [comment]
Alright, here’s a sample project. Just `swift run` it and hit `localhost:8080` and watch the console.

- https://github.com/danhalliday/VaporApolloSample

**Comment by AnthonyMDev** [comment]
Thanks for that! I think I see the issue. The completion block gets called on the `callbackQueue` you provide to the client asynchronously. You're providing `.main` which is the main thread. But `Vapor` owns the main thread of your application and it's got a lock on it. So nothing dispatched to the main thread is going to ever actually get executed! 

Just make a background thread and set up your client with that. Let me know if it's still not working!

**Comment by danhalliday** [comment]
Many thanks @AnthonyMDev. This indeed solves the issue in the sample project and is a great insight for this use case!

Unfortunately having got past that I discovered my sample project was oversimplified and there’s another underlying issue. In the sample I create the Apollo client inline in the request. If you use a more standard setup that all the docs show, that’s when you get the security error logs. Perhaps this reveals something worth knowing?

To reproduce, move out the client init to a global. I don’t think my additional headers stuff is relevant.

```swift
// Network.swift

struct Network {
    static var shared = Network()
    let queue = DispatchQueue(label: "network", qos: .background)

    private(set) lazy var apollo: ApolloClient = {
        let url = URL(string: "https://graphql.datocms.com")!

        let configuration = URLSessionConfiguration.ephemeral
        configuration.httpAdditionalHeaders = [
            "Authorization": "Bearer 12345"
        ]

        let store = ApolloStore(cache: InMemoryNormalizedCache())
        let client = URLSessionClient(sessionConfiguration: configuration, callbackQueue: .main)
        let provider = DefaultInterceptorProvider(client: client, store: store)
        let transport = RequestChainNetworkTransport(interceptorProvider: provider,
                                                   endpointURL: url,
                                                   additionalHeaders: ["Authorization": "Bearer 12345"],
                                                   useGETForQueries: true)
        return ApolloClient(networkTransport: transport, store: store)
    }()

}
```

```swift
// routes.swift

await withCheckedContinuation { continuation in
    Network.shared.apollo.fetch(query: ListInstrumentsQuery(), queue: Network.shared.queue) { result in
        continuation.resume(returning: ...) // Never called, shows security console logs
    }
}
```

**Comment by danhalliday** [comment]
Oh wait, the above only 'works' in the sense that its callback is called. But the client instance is deinited instantly and results in a `Apollo.URLSessionClient.URLSessionClientError.sessionInvalidated`. So I’ve been following a few dead ends there.

I’ve updated the sample so it now gives exactly the errors I was originally seeing.

- https://github.com/danhalliday/VaporApolloSample/blob/main/Sources/App/routes.swift

**Comment by AnthonyMDev** [comment]
You need to also setup the OperationQueue for the `URLSessionClient` to use a background queue.

I just tried this, and it's working for me! 

```swift
import Vapor
import Apollo

struct Network {
    static var shared = Network()

    private(set) lazy var apollo: ApolloClient = {
        let url = URL(string: "https://api.spacex.land/graphql/")!
        let configuration = URLSessionConfiguration.ephemeral
        let store = ApolloStore(cache: InMemoryNormalizedCache())
        let client = URLSessionClient(sessionConfiguration: configuration, callbackQueue: .apollo)
        let provider = DefaultInterceptorProvider(client: client, store: store)
        let transport = RequestChainNetworkTransport(interceptorProvider: provider, endpointURL: url)

        return ApolloClient(networkTransport: transport, store: store)
    }()
}

extension OperationQueue {
  static let apollo: OperationQueue = {
    let queue =  OperationQueue()
    queue.qualityOfService = .background
    queue.maxConcurrentOperationCount = 10
    return queue
  }()
}

extension DispatchQueue {
    static let apollo = DispatchQueue(label: "apollo")
}

func routes(_ app: Application) throws {
    app.get { req async throws -> String in
        return await withCheckedContinuation { continuation in
            print("Servicing request")

            Network.shared.apollo.fetch(query: LaunchesQuery(), queue: .apollo) { response in
                print("Returning response")
                continuation.resume(returning: "Hello World!")
            }
        }
    }
}
```

I haven't seen the Security errors that you're seeing coming up in my Xcode console though, so I'm not sure what is going on there.

--- 
FWIW, we already know that this API is a mess right now. After we release 1.0, the next step for us is rewriting the entire networking API and implementation to improve upon this dramatically. At which point, this should be a lot easier.

We will try to take the Vapor use case into account when we do so. It shouldn't be this hard to get it working, and we are going to do better.

For now, this should work for you. Vapor is not officially supported by apollo-ios at the moment, so I can't guarantee you won't run into other troubles. Since we don't support Linux yet, it's not high priority as most Vapor servers are going to run on Linux, not macOS. It's all future work we want to do though!

If you want to contribute PRs to assist with any bugs you have while trying to work with Vapor, we'd love to have them! Thanks @danhalliday

**Comment by danhalliday** [comment]
Aha, nice! Many thanks for your help @AnthonyMDev. I actually did try playing with the operation queue, just not with that and the fetch queue at the same time. The explanation and solution seem obvious now, but as a newcomer I was certainly scratching my head to start with!

I’ll certainly keep an eye out for any other interesting non-ios issues.
