### ISSUE TITLE
Is it possible to print/debug the actual GraphQL request string sent?

### ISSUE THREAD

**Issue by attheodo** [apollographql/apollo-ios#232]
Is it somehow possible to do this, including the variables? Sometimes it's helpful in communications with the backend developers.

**Comment by nicolasg-playster** [comment]
+1

This is very much needed. Debugging GraphQL calls is a nightmare on iOS at the moment.

**Comment by oliviertouron-playster** [comment]
+1

I try to display it but the property is protected...
result?.dependentKeys

Please can you change it??

Thx

**Comment by danwkennedy** [comment]
I've found that Netfox is a good way for debugging all network requests (not just GraphQL):
https://github.com/kasketis/netfox

**Comment by crabman448** [comment]
I created this extension. But you can actually add more properties that you want to print in the console.
```
extension GraphQLOperation {
    var description: String {
        let operation = "------Oper------:\n" + "\(String(describing: self))"
        let variables = "------Vars------:\n" + "\(self.variables as AnyObject)"
        return operation + variables
    }
}
```

**Comment by designatednerd** [comment]
You should be able to use the new `HTTPNetworkTransportTaskCompletedDelegate` inspect both the request as it went out (which would include the body) and the response. Docs are now up as #618. 

I'm going to close this out, if there's further issues you think aren't addressed by that, please open a new issue. Thank you!

**Comment by maxcan** [comment]
And this is a great way to get a cURL command matching the request for more debugging:

https://gist.github.com/peterprokop/16790dfa1320211b20c94a3f4dd95464
