### ISSUE TITLE
iOS 1.0 Release Documentation Updates

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-ios#2344]
### Description

As part of our GA release of iOS 1.0 we will need to do a pretty large update to our [iOS client documentation](https://www.apollographql.com/docs/ios/v1) in order to document the new code gen capabilities as well as re-structure the documentation for a better documentation user experience.  Most of the iOS documentation will need updating. 

Below are some general tasks we need to consider. 

### Docs Tasks

- [x] Review our current iOS docs and consider impacts of v1  
- [x] Determine what approach we will take to completing the documentation updates.  Should we take a first pass through the docs updates  and have them provide feedback? Or do they want to take the lead on the first pass?

Discuss with the Apollo Docs Team if:

- [x] They have opinions on the formatting and organization structure of the V1 docs.
- [x] ~Determine if they want to provide an outline or structure of navigation for the v1 docs.~ _Structure can come after based on what content is available._
- [x] ~Consider if we'd benefit from a `migration to v1 doc` [Similar to Kotlin.](https://www.apollographql.com/docs/kotlin/migration/3.0)~ _Added to TODOs_
- [x] Since new codegen capabilities are a significant part of this release, consider how that should be documented. 

### Documentation TODOs
- [ ] ApolloAPI.Object.cacheKeyProvider: Add reference to cache key computation usage guide (once written)
- [ ] ApolloAPI.CustomScalarType: Add reference to custom scalar usage guide (once written)
- [ ] Add better usage examples for `ApolloAPI.GraphQLEnum`
- [ ] Add better usage examples for `ApolloAPI.GraphQLNullable`
- [ ] Add better usage examples for Custom Scalars
- [x] https://github.com/apollographql/apollo-ios/pull/2698
- [x] #1957
- [ ] How to stub and mock generated code models (https://github.com/apollographql/apollo-ios/issues/2344#issuecomment-1173843555)

**Comment by jpvajda** [comment]
@rkoron007 said we can chat about these docs needs soon, and I suggested we provide her team an outline of what we think will need to change, I'll setup some time for all of us to chat in Mid July

**Comment by kimdv** [comment]
Hi! 

A little wish from me, some documentation on how to stub and mock the different parts would be nice. 👏
https://community.apollographql.com/t/mocking-apolloclientprotocol-in-ios-sdk-beta-1/3920

**Comment by jpvajda** [comment]
@kimdv Good suggestion! We do accept PRs for our documentation, if you had some time and wanted to contribute that would be great. We'd be happy to review whatever you come up with. 😄
