### ISSUE TITLE
1.0 Documentation Rewrite

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2365]
The kickoff for this work is https://apollographql.quip.com/JoDZAUzvnPs4/iOS-10-GA-Public-Documentation which will outline the desired structure for the 1.0 documentation. From there this issue will be broken up into smaller issues that can be completed per section/topic/example/etc.

**Comment by hwillson** [comment]
We'll track this in https://github.com/apollographql/apollo-ios/issues/2344.
