### ISSUE TITLE
Adds tests to validate cache key resolution behavior

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2390]
Ensure that users can implement cache key resolution [as described in the 1.0 Codegen Proposal](https://github.com/apollographql/apollo-ios/blob/release/1.0/CodegenProposal.md#cache-key-resolution).

**Comment by calvincestari** [comment]
What started off as simply adding tests highlighted implementation problems with the cache key resolution mechanism in the codegn proposal. We've put this issue on hold until we conclude discussions about potential changes to the schema object models.

**Comment by AnthonyMDev** [comment]
Closed by #2430
