### ISSUE TITLE
Apollo 1.0 Beta: Destination paths should not need to exist.

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#2404]
## Bug report

When you are missing certain directories in output paths, it fails codegen with missing file system path errors. Based on working with other similar tools, my expectation is that Codegen creates the output paths in their entirety.

**Comment by jimisaacs** [comment]
```zsh
 ❯ swift run                                                                                                                                                                                                      
'codegen': error: Source files for target MyApolloCodeGen should be located under 'Sources/MyApolloCodeGen', or a custom sources path can be set with the 'path' property in Package.swift
```

**Comment by calvincestari** [comment]
Thanks for raising this issue @jimisaacs. For a while now I've waffled back and forth on the value of validation in the initial steps of code generation. To be honest I'm not opposed to getting rid of the validation step entirely and moving those potential errors inline as it goes through code generation.

**Comment by AnthonyMDev** [comment]
More so than just getting rid of validation, I agree with jimi, this shouldn't be an error, if the directory doesn't exist, lets just create it!

**Comment by calvincestari** [comment]
> More so than just getting rid of validation, I agree with jimi, this shouldn't be an error, if the directory doesn't exist, lets just create it!

Yes - when I said "moving those potential errors inline" I don't mean keeping the validation as-is-just-somewhere-else. The logic will change to building the paths as it creates the output files instead of requiring the output paths to be there before.

**Comment by calvincestari** [comment]
This is done with the merging of #2408.
