### ISSUE TITLE
feat: Clean up old code generated files

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2407]
Code generation is designed to only add or overwrite files; any files that were generated from previous code generation runs but are no longer used/needed will not be cleaned up. This places a burden on the user to know which files they can safely remove.

* The implementation for this feature should clean up any previously generated but no longer required files.
* A consideration is whether it should leave user-generated files that are in the output paths?

**Comment by AnthonyMDev** [comment]
Should we consider prioritizing this to get it in the 1.0 release? This is a pretty significant Developer Experience issue currently.

**Comment by calvincestari** [comment]
IMO this is not a 1.0 must-do issue - I agree it's an annoyance to have to manually remove the old unnecessary file but not doing this _should_ not impact the ability to use apollo-ios. Unless there was a change that caused types to appear in both the old and new generated files and depending on the module type (`.embeddedInTarget` or `.other`) they might end up having both files linked to the project still.

Either way this automatically gets resolved once we implement this feature with no breaking change.

**Comment by calvincestari** [comment]
This is complete with the merging of https://github.com/apollographql/apollo-ios/pull/2486.
