### ISSUE TITLE
Automate versioning of CodegenCLI

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2409]
Updating the version number of the CodegenCLI is still a manual process, as [#2408 shows](https://github.com/apollographql/apollo-ios/pull/2408/files#diff-fe06a8767ad16606b64ccd610d8dc82b8288cdfc91b1be5312a5ee68c74a2fe5R8). It needs to be automated and linked with the versioning of apollo-ios.

**Comment by hwillson** [comment]
We're now tracking this in https://github.com/apollographql/apollo-ios/issues/2381.
