### ISSUE TITLE
Apollo 1.0 Beta: Xcode 14 error

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#2415]
## Bug report

Regarding apollo-ios 1.0 and Xcode 14, we're blocked on an error here:
<img width="979" alt="Screen Shot 2022-08-02 at 12 17 48 PM" src="https://user-images.githubusercontent.com/299156/182423620-ba5f58cf-ac8c-4a8c-b3a3-789f3bc579ee.png">

I do not currently understand how to fix this error otherwise I would make a PR.

If you help me with a suggestion, I can give it a try.

This error is blocking us from using the Beta anywhere outside of a feature branch, because we always have automation with the new Xcode to verify our builds, and Apollo 1.0 would currently fail that automation.

**Comment by axiel7** [comment]
Duplicated #2360

**Comment by AnthonyMDev** [comment]
Yeah, this is on our list. We'll get to it as soon as we can!

**Comment by AnthonyMDev** [comment]
Closing as duplicate
