### ISSUE TITLE
How to get message from ApolloError in Error object. 

### ISSUE THREAD

**Issue by namanAstapartners** [apollographql/apollo-ios#2419]
```
NetworkManager.shared.apollo.perform(mutation: someMutation){ result in
            switch result {
            case .success(_):
            case .failure(let error):
                print("Error: \(error.localizedDescription)")
                // "Received a 400 error. Data returned as a String was: {\"errors\":[{\"message\":\"this email belongs to a someone else\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"someMutation\"],\"extensions\":{\"code\":\"400\"}}],\"data\":{\"someMutation\":null}}\n"
            }
        }
```
        

in this I want to display **message** parameter which is **this email belongs to a someone else** on swift.
        
"Received a 400 error. Data returned as a String was: {\"errors\":[{\"message\":\"this email belongs to a someone else\",\"locations\":[{\"line\":2,\"column\":3}],\"path\":[\"someMutation\"],\"extensions\":{\"code\":\"400\"}}],\"data\":{\"someMutation\":null}}\n"

**Comment by AnthonyMDev** [comment]
It looks like the error is being provided to you correctly by Apollo. The error is actually a `GraphQLError`, which exposes the `message` field to you. You just need to cast your error as `GraphQLError`.

**Comment by namanAstapartners** [comment]
![Screenshot 2022-08-04 at 11 24 34 PM](https://user-images.githubusercontent.com/53220262/182918287-08ce64f4-e87d-4340-92a4-e97488779b7e.png)
![Screenshot 2022-08-04 at 11 24 53 PM](https://user-images.githubusercontent.com/53220262/182918294-9586ca09-e35e-4964-8ca8-385079ceef02.png)

@AnthonyMDev  not sure but error is not being casted.

**Comment by AnthonyMDev** [comment]
what type is the error you're getting? Set a breakpoint and look at the type of the `error` property in the debugger.

**Comment by namanAstapartners** [comment]
![Screenshot 2022-08-04 at 11 37 24 PM](https://user-images.githubusercontent.com/53220262/182920550-9525df50-5933-4100-aec3-51f557645ddd.png)

**Comment by AnthonyMDev** [comment]
Ah okay, it's a `ResponseCodeError` so try this:
```swift
if case let ResponseCodeInterceptor.ResponseCodeError.invalidResponseCode(_, errorData) = error {
  let errorDict = try? JSONSerialization.jsonObject(with: errorData, options: []) as? [String: Any]
  let errors = errorDict?["errors"] as? [[String: Any]]
  let message = errors?[0]["message"] as? String
}
```

We should do some work to make that `ResponseCodeError` more user friendly. I'll make an issue for us to get around to that eventually. But I think that code snippet should get you moving for now!
