### ISSUE TITLE
Prepare 1.0.0-beta.2 release

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2421]
Here's the [current diff](https://github.com/apollographql/apollo-ios/compare/1.0.0-beta.1...release/1.0) of what would go out in this release.

Issues to resolve for this beta:
[ ] #2424 
[x] #2405
[ ] #2403
[ ] #2418 (maybe, unclear on the issue here still)
[ ] #2420

**Comment by hwillson** [comment]
Beta 2 was published 🎉.
