### ISSUE TITLE
Improve ResponseCodeError API

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#2426]
This error is really difficult to parse information from. See #2419 for more info.

**Comment by dfperry5** [comment]
@AnthonyMDev  Any chance this is still an open issue? :) I wouldn't mind taking it on. This would be my first time contributing to Apollo iOS though.

**Comment by AnthonyMDev** [comment]
I'd be happy to have you work on this @dfperry5! Thanks for offering to contribute.

It actually looks like the data does contain a spec compliant `GraphQLError` response. So we should probably be exposing that data as a `GraphQLError` struct.

The _right_ way to do this would involve separating the JSON serialization interceptor from the parsing of the actual GraphQL result, but that is going to require a lot of restructuring of our network APIs that we are going to do in the 2.0 release.

But in order to improve this for now without breaking things, I think the right approach would be for us to:

- Add a new optional computed property `graphQLError: GraphQLError?` to `ResponseCodeError`.
  - This computer property would deserialize the JSON itself and if it is able to parse then parse the error from that into a `GraphQLError` struct if it exists.

**Comment by dfperry5** [comment]
Awesome! @AnthonyMDev  - I will give it a try!

**Comment by dfperry5** [comment]
@AnthonyMDev  - could you take a peak at this? https://github.com/apollographql/apollo-ios/compare/main...dfperry5:apollo-ios:Issue-2426-Improve-ResponseCodeError-API?expand=1


It's my first pass, I'm not overly thrilled with it :P Not sure if there is something more obvious I am missing.

**Comment by AnthonyMDev** [comment]
This looks like what we want right now. If you can just add another test that an error that doesn't have a GraphQLError returns `nil` from `error.graphQLError` and then add a line of documentation to the `graphQLError` property this should be ready for a PR!

Thanks so much for doing this!

**Comment by dfperry5** [comment]
https://github.com/apollographql/apollo-ios/pull/3123 :) Thanks for guiding me! Let me know if there are any chances.
