### ISSUE TITLE
Cache policy is ignored for mutation

### ISSUE THREAD

**Issue by MatthewHendy** [apollographql/apollo-ios#2427]
## Bug report

Mutation sends even when cache policy is set to .fetchIgnoringCacheCompletely

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.50.0
- Xcode version: 13.4.1
- Swift version: 5
- Package manager: 

## Steps to reproduce

Turn device to airplane mode
attempt to send mutation with cache policy set to .fetchIgnoringCacheCompletely
wait for failure
turn airplane mode off and reestablish connection
mutation sends

**Comment by calvincestari** [comment]
Hi 👋🏻 - The defined behaviour for `. fetchIgnoringCacheCompletely` is `///  Always fetch results from the server, and don't store these in the cache.`. which indicates it will always attempt to communicate with the server. I'm not sure what behaviour you're expecting with that cache policy, can you provide a bit more detail.

**Comment by MatthewHendy** [comment]
The call has failed due to no connection. Why does it send once the connection becomes reestablished? I do not want this behavior at all.

**Comment by jimisaacs** [comment]
I also do not understand your expectation. The cache policy means to fetch from the server, so doesn't it make sense that it does that when the connection is reestablished? What do you want? A fetch to go out and fail immediately? The cache policy has nothing to do with the network connection handling, something else must be doing that.

It sounds like the behavior would be in the networking code, though I can't find anything [here](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/NetworkFetchInterceptor.swift) that would indicate that Apollo is doing anything to wait for a connection. This is all of the [apollo built ins](https://www.apollographql.com/docs/ios/request-pipeline#built-in-interceptors). There you can see there are 2 interceptors that use cache policy, [CacheReadInterceptor](https://www.apollographql.com/docs/ios/request-pipeline#cachereadinterceptor) and [CacheWriteInterceptor](https://www.apollographql.com/docs/ios/request-pipeline#cachewriteinterceptor).

I'd think something related to Reachability would be implemented in [NetworkFetchInterceptor](https://www.apollographql.com/docs/ios/request-pipeline#networkfetchinterceptor), but again I do not see it.

Are you sure this isn't something your code is doing, or maybe even iOS these days?

**Comment by MatthewHendy** [comment]
I'm pretty sure it is not our code. It could be an iOS issue I suppose, maybe it has some kind of internal network cache.

The expectation is simple: if a call is made when no internet connection is present, that call fails and is not automatically retried once connection is re-established.

**Comment by TizianoCoroneo** [comment]
This sounds like `URLSession.waitsForConnectivity = true`, are you sure you're not using this line in your project?

https://developer.apple.com/documentation/foundation/urlsessionconfiguration/2908812-waitsforconnectivity

![Screen Shot 2022-08-09 at 10 01 08](https://user-images.githubusercontent.com/15340382/183597039-58768844-01bd-4f96-92b1-cf21198b57b1.png)

**Comment by MatthewHendy** [comment]
That line is not in our project nor is "waitsForConnectivity" at all.

**Comment by calvincestari** [comment]
Are you able to replicate this behaviour in a standalone project?

**Comment by AnthonyMDev** [comment]
@MatthewHendy, have you found any additional information on what could be causing this. It seems unlikely that this an issue with Apollo itself.

**Comment by AnthonyMDev** [comment]
Closed due to inactivity.
