### ISSUE TITLE
continuously calling Apollo fetch requests on time interval is not fetching data updates

### ISSUE THREAD

**Issue by hazzaldo** [apollographql/apollo-ios#243]
**continuously calling Apollo fetch requests on time interval is not fetching data updates**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

I have data that is constantly changing on the server, such as a football match time duration, where we're required to display the remaining minutes of the match to the user. So I make continuous calls to Apollo fetch request on a time interval, using NSTimer (or Timer). However, I noticed (using print statements) the data being fetched is not changing. It seems that Apollo client is simply fetching the same data. 
Is this a known issue? Do I need to fetch data, on a time interval, differently to how I normally call Apollo fetch request? 

Thanks in advance

**Comment by martijnwalraven** [comment]
What kind of cache policy are you using for the fetch call? You probably want `.fetchIgnoringCacheData`.

**Comment by hazzaldo** [comment]
Yep that worked. :) I've also checked the code in Apollo framework and the comments. Should've checked there first. 

Many thanks :)
