### ISSUE TITLE
Retain Cycle in 1.0.0 Beta GraphQLExcecutor <-> ReadTransaction

### ISSUE THREAD

**Issue by lorraine-hatch** [apollographql/apollo-ios#2437]
## Bug report

After sending a few queries, there are a lot of retain cycles between `GraphQLExcecutor` and `ReadTransaction`. See screen shots below. 👇 

Help would be appreciated! Thank you 🙏

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: beta 1.0.0
- Xcode version: 13.4.1
- Swift version: 5
- Package manager: SPM

## Steps to reproduce

- Send some queries through the Apollo client (I only made about 5-6 queries)
- Go to memory debugger
- Find memory warnings by `GraphQLExcecutor` and `ReadTransaction`. Is there supposed to be 28 instances of each? 

## Further details

<img width="200" alt="CleanShot 2022-08-15 at 14 21 51@2x" src="https://user-images.githubusercontent.com/105568068/184711949-bb676449-2544-4186-8c77-463fb189a36f.png">
<img width="200" alt="CleanShot 2022-08-15 at 14 22 21@2x" src="https://user-images.githubusercontent.com/105568068/184711966-25194909-aff3-4381-89d8-d954650ed3a9.png">
<img width="200" alt="CleanShot 2022-08-15 at 14 22 00@2x" src="https://user-images.githubusercontent.com/105568068/184711976-b86a292f-986e-44de-8476-c83218298ecd.png">

**Comment by calvincestari** [comment]
Thanks for the bug report @lorraine-hatch, we'll take a look into this asap.

**Comment by lorraine-hatch** [comment]
Thanks!

**Comment by lorraine-hatch** [comment]
@calvincestari I think I've found the solution to this, can I make a pull request?

**Comment by calvincestari** [comment]
@lorraine-hatch yes certainly! We'll gladly review your PR, thanks.

**Comment by lorraine-hatch** [comment]
@calvincestari Here ya go! https://github.com/apollographql/apollo-ios/pull/2475

**Comment by AnthonyMDev** [comment]
Thank you! Fixed in #2476. More details at this comment: https://github.com/apollographql/apollo-ios/pull/2475#issuecomment-1232157290

**Comment by calvincestari** [comment]
Thanks for the contribution @lorraine-hatch, glad you managed to track that down. I was away last week, thanks @AnthonyMDev for reviewing and merging.
