### ISSUE TITLE
Apollo 1.0 Beta: fragments that are not capitalized seems to cause issues

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#2441]
## Bug report

If you have a fragment like this:
```
fragment myThing on Thing {
   stuff
}
```

Apollo codegen seems to be confused as to what to call it and reference it.

It is generated with a type `MyThing`, but it seems to be referenced as `myThing.self`.

**Comment by AnthonyMDev** [comment]
This should be automatically capitalized. Working on this while fixing #2405 as well. Fix should be out shortly.

**Comment by AnthonyMDev** [comment]
Fixed with #2443
