### ISSUE TITLE
How to unit test case for QraphQL apis. 

### ISSUE THREAD

**Issue by Minna** [apollographql/apollo-ios#2444]
How to read json file from local and parse as graphql response

**Comment by calvincestari** [comment]
Hi @Minna - `ApolloPerformanceTests` has an [example](https://github.com/apollographql/apollo-ios/blob/main/Tests/ApolloPerformanceTests/ParsingPerformanceTests.swift#L40) of how we do this in our tests. Hope that helps - thanks!
