### ISSUE TITLE
Apollo 1.0 Beta: implementing cacheForKey isn't working

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#2445]
## Bug report

Implementing:
```swift
@inlinable static func cacheKeyInfo(
      for type: Object,
      object: JSONObject
) -> CacheKeyInfo?
```

On the generated `Schema` object isn't working.
I put a breakpoint on the default implementation in the protocol and it is working.
The stacktrace shows that `cacheForKey` is invoked on the protocol which means it will never make it to my implementation.

**Comment by AnthonyMDev** [comment]
I thought I fixed that issue... I was aware it was happening, but then I fixed it. My unit tests must be flawed somehow... will look into it. Might have to remove the default implementation and just generate an implementation on the generated schema config object!

**Comment by AnthonyMDev** [comment]
I am completely unable to reproduce this issue on Beta 2, even in a separate example project.

Can you try removing the default implementation of `cacheKeyInfo` from the protocol extension in `SchemaConfiguration.swift` and see if that causes any compilation errors? I'm wondering if the function signature is off in some way.

Thinking we may need to consider how to make this more foolproof going forward though if that's the case.

**Comment by jimisaacs** [comment]
This is the exact implementation without the body:
```
extension Schema {
    @inlinable public static func cacheKeyInfo(for type: Object, object: JSONObject) -> CacheKeyInfo? {
    ```
I've tried various iterations of this.

**Comment by AnthonyMDev** [comment]
This is resolved now. We realized this issue only occurred when the extension was not in the same target as the generated schema. #2454 is going to generate this extension for you, so it will always be in the right place.

You'll be able to edit the generated extension and if you want to implement the logic for it in another target, you'll need to use Dependency Injection of some sort to do so.
