### ISSUE TITLE
How can detect statusCode in error when fetch data from GraphQL API

### ISSUE THREAD

**Issue by duydtdev** [apollographql/apollo-ios#245]
Please help tell me `How can detect statusCode in error when fetch data from GraphQL API`. Below is my code in error scope:
```
let apollo = ApolloClient(networkTransport: HTTPNetworkTransport(url: url, configuration: configuration))
      
      apollo.fetch(query: query) { (result, error) in
        if let error = error {
          /// FAILURE
          print("[Error] Got errors when call request: \(error)")
          /// Check error response. If status code equals 401 should request new authenticate with current credential
        } else {
          /// SUCCESS
        .........
```
Many thanks

**Comment by martijnwalraven** [comment]
You'll have to (conditionally) cast it to a `GraphQLHTTPResponseError`, and that allows you to access `response`, which is a `HTTPURLResponse`.

**Comment by duydtdev** [comment]
Thanks @martijnwalraven 
I casted it to `GraphQLHTTPResponseError`. And my code work fine, many thanks. Below is my code:
```apollo.fetch(query: query) { (result, error) in
        if let error = error {
          /// FAILURE
          if let errorResponse = error as? GraphQLHTTPResponseError {
            
if errorResponse.response.statusCode == 401 {
              /// Check error response. If status code equals 401 should request new authenticate with current credential
              print("[Error] Got 401 errors when call request: \(error)")
            } else
            {
              print("[Error] Got other GraphQL errors when call request: \(error)")
            }
          } else {
            print("[Error] Got errors when call request: \(error)")
          }
        } else {
          /// SUCCESS
         ............
```

But I don't think this code is good (professional). Do you have other ways?

**Comment by designatednerd** [comment]
I'm definitely looking at switching to the `Swift.Result` which allows you to more easily see if there's an error or a result from a particular request. But until I do that, what you've got should work!

I'm going to close this out. If you have further questions, please drop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) and fire away!
