### ISSUE TITLE
Object not getting

### ISSUE THREAD

**Issue by Rushabh5** [apollographql/apollo-ios#2456]
Hello,

I am trying to call one query but unfortunately, one object is not getting in the response while the same query I am using in the postman and in that I received a whole response so any solution for that?

**Comment by calvincestari** [comment]
Hi @Rushabh5, as long as your query is valid there is nothing in apollo-ios to hide that field from the response. Have you tried to use a proxy to see what data is actually returned from the server? I would suggest using a proxy to compare the two requests and the two responses to see what the differences might be.

**Comment by Rushabh5** [comment]
Hello @calvincestari ,

Thanks for the quick response. I am new in graphql so can you please explain proxy and how can I check?

**Comment by calvincestari** [comment]
Charles Proxy has a guide for getting started - https://www.charlesproxy.com/documentation/getting-started/. You can also use [Apollo Studio](https://studio.apollographql.com/) to check that your query is returning the results you expect.

I'm going to close this as it's not really an issue with apollo-ios. You might also have luck looking through the [Apollo GraphQL forums](https://community.apollographql.com/) to see if there is a similar topic that can help too.
