### ISSUE TITLE
Latest beta: Doesn't have `run-bundled-codegen`, has `run-codegen` which does nothing

### ISSUE THREAD

**Issue by kroussevrb** [apollographql/apollo-ios#2458]
## Bug report

There is no `run-bundled-codegen` script anymore, there is a `run-codegen` one which does nothing (i.e. doesn't generate `API.swift` and it doesn't spit out any errors)

## Versions

- `apollo-ios` SDK version: 1.0.0-beta.2
- Xcode version:  13.4.1
- Swift version: 5.x
- Package manager: SPM

## Steps to reproduce

1. Upgrade to latest beta
2. The file is not there

**Comment by kroussevrb** [comment]
@calvincestari

**Comment by calvincestari** [comment]
Hi @kroussevrb - that script was removed intentionally. If you look at the script, which is still active in [0.53.0](https://github.com/apollographql/apollo-ios/blob/0.53.0/scripts/run-bundled-codegen.sh#L14), you'll see it was built around the legacy codegen tooling.

1.0 doesn't use that tooling anymore and we're moving away from the recommendation of generating code on each build, therefore no need for the build script. We do have a [modern CLI tool](https://github.com/apollographql/apollo-ios/tree/release/1.0/Sources/CodegenCLI) that will do a far better job and I'm currently working on a SPM Plugin for the CLI too. I recommend trying it out, you can build just the CLI locally with the `make build-cli` command.

**Comment by calvincestari** [comment]
I'm going to close this as it's not bug; we're simply providing alternative ways to execute code generation.

**Comment by kroussevrb** [comment]
Alright, thank you. I found no documentation/explanation for it so I thought it was a bug. Going to try to understand what you wrote in the post above and try to find a way to regenerate my `API.swift` file.

**Comment by calvincestari** [comment]
> Alright, thank you. I found no documentation/explanation for it so I thought it was a bug. 

Yes - I apologize, we're definitely behind on documentation for the betas.

> Alright, thank you. I found no documentation/explanation for it so I thought it was a bug. Going to try to understand what you wrote in the post above and try to find a way to regenerate my API.swift file.

If you checkout the `release/1.0` branch or the `1.0.0-beta.2` tag and run the `make build-cli` command, SPM will build the `apollo-ios-cli` executable, which then functions as the [README](https://github.com/apollographql/apollo-ios/tree/release/1.0/Sources/CodegenCLI) states. Once the executable is built you can likely find it at `.build/release/apollo-ios-cli`. So an example command to print a new configuration file to the screen would be `.build/release/apollo-ios-cli init --print`

**Comment by kroussevrb** [comment]
Awesome!
