### ISSUE TITLE
Large numbers from custom scalars are not interpreted correctly

### ISSUE THREAD

**Issue by Almaz5200** [apollographql/apollo-ios#2469]
## Bug report
*This is v1.0 issue*

Large numbers stored in custom scalar is parsed incorrectly
For example: my schema has "TimeSecond" type that is actually a timestamp. Swift JSON Parsing interprets it as Int64 number, which currently can't be converted to String by apollo.

Current version of apollo (0.53) is not affected by this because there is `switch value` on line 13 instead of `switch value.base` with 1.0 version

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0-beta.2
- Xcode version: 13.4
- Swift version: 5.6
- Package manager: SPM

## Further details

I've fixed it in #2463, but I thought it might be a good idea to reflect that in issues as well

**Comment by AnthonyMDev** [comment]
Closed with PR #2463, thank you!
