### ISSUE TITLE
Codegen: Nested fragment types not getting capitalized

### ISSUE THREAD

**Issue by cshadek** [apollographql/apollo-ios#2479]
## Bug report

Codegen is not always generating nested fragments properly.  It sometimes doesn't capitalize the type of the nested fragment, and as a result the code doesn't compile.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version:  1.0.0-beta.3
- Xcode version: 13.4.1
- Swift version: 5.6
- Package manager: SPM

## Steps to reproduce

I'm using codegen with OperationsFileOutput of `.inSchemaModule` and SchemaTypesFileOutput.moduleType of `.swiftPackageManager`.

Sometimes Codegen doesn't generate nested fragments properly.  See below:

<img width="1087" alt="Screen Shot 2022-09-06 at 8 23 40 PM" src="https://user-images.githubusercontent.com/13188849/188768547-4e3d0789-e035-439e-aa0d-ba3f632ebcc2.png">

My understanding is that codegen should generate the following code instead:

<img width="660" alt="Screen Shot 2022-09-06 at 8 34 19 PM" src="https://user-images.githubusercontent.com/13188849/188769292-bca5eb0c-25dc-41d1-897b-d929d7dfa591.png">

So it seems the issue is that the type of the nested fragment is not getting capitalized.

**Comment by AnthonyMDev** [comment]
This is actually already fixed on `release/1.0`! It will be in the next beta, or if you depend on the release branch, you'll have the fix now!
