### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by LykaMali** [apollographql/apollo-ios#2482]
My query =>
```graphql
query MeRequest {
	me {
		id
		given_name
		family_name
		user_avatar
		email
		gender
		avatar
		workspaces
		agora_user_id
		invites
	}
}
```

----------------

I am trying to gettin my data with this query. But apollo throw this error;
```
an error occured:  Error at path "me.user_avatar)": couldNotConvert(value: {
    id = "4bada84a-a649-4ff2-822b-ec939980ec33";
    url = "https://werkapp.s3.eu-central-1.amazonaws.com/werk/images/ad13cb61bf7d7e3907a0e87fb942ae79.jpeg";
}, to: Swift.Dictionary<Swift.String, Swift.Optional<Apollo.JSONDecodable>>)
```

---------------

if I delete me.user_avatar apollo throw another decode error.

---------------

My jsonb typealias => public typealias jsonb = Dictionary<String, JSONDecodable?>
I am trying to this type alias to => public typealias jsonb = [String: Any?]

---------------
Please help me :(
Thank you...

**Comment by calvincestari** [comment]
Difficult to debug without knowing more about the schema but do you maybe need to select the fields on user_avatar? `user_avatar { id, url }`

**Comment by LykaMali** [comment]
Actually user avatar is jsonb, I mean [String: Any?] or Dicrionary<String, Any?>

**Comment by AnthonyMDev** [comment]
It should be `[String: Any]` not `[String: Any?]`. `Optional` is already encompassed in `Any` and by using `Any?` you are saying that **all** values must be wrapped in an optional, even when they are present. The JSON Serialization doesn't wrap them in optional by default, which may be why you are getting a conversion error.

**Comment by LykaMali** [comment]
Solved!, please check this command line.
---------
public typealias jsonb = [[String:Any?]]

extension jsonb: JSONDecodable{
 
    public init(jsonValue value: JSONValue) throws{
        guard let array = value as? Array else {
            guard let dict = value as? Dictionary<String, Any> else { throw JSONDecodingError.couldNotConvert(value: value, to: Dictionary<String, Any>.self)
            }
            self = .init(arrayLiteral: dict)
            return
        }
        self = array
    }
}
----------------------
Thank you.

**Comment by calvincestari** [comment]
Glad you got it working.
