### ISSUE TITLE
iOS : Cannot convert value of type <Custom Scalar> to expected dictionary value type JSONEncodable.

### ISSUE THREAD

**Issue by bhaveshlsamcom** [apollographql/apollo-ios#2490]
Not able to use the scalars function, I want to set the date using mutation. 

Hello Folks, 
Greetings for the day!

Please help on this, thanks in advanced.

 I added the “--passthroughCustomScalars” in my run script. And once build is successful its automatically generate the “API.Swift” file.

This is code I added in my run script.
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql, --passthroughCustomScalars --localSchemaFile="schema.json" API.swift

And It’s changed the API.swift file as per the mutation wrote in .graphql file. Below is code for mutation which I wrote in graphql file.
![Screenshot 2022-09-12 at 10 38 10 AM](https://user-images.githubusercontent.com/75381167/189578169-45f5dc60-756f-405d-b306-099f383814a6.png)

But its gives error, and asking for json parsing in “API.Swift”  file. Please check below error and screenshot.
Error: Cannot convert value of type 'Date' to expected dictionary value type 'JSONEncodable?'

![Screenshot 2022-09-12 at 10 20 54 AM](https://user-images.githubusercontent.com/75381167/189578222-e738983d-5f30-4479-b8b6-0cef4a422b31.png)

So after that I added the pod for “pod 'JSONValue'” but still it’s not working. Also added extension but not worked. Please refer below screenshot.
![Screenshot 2022-09-12 at 10 23 34 AM](https://user-images.githubusercontent.com/75381167/189578282-cae562ad-2785-403d-8d6d-8e01abc32721.png)
![Screenshot 2022-09-12 at 10 24 16 AM](https://user-images.githubusercontent.com/75381167/189578288-2e781dc8-fe98-43d1-812f-ea86bbb3f1b6.png)  

Thank you.

**Comment by calvincestari** [comment]
Hi, we have a [Swift Playground](https://github.com/apollographql/apollo-client-swift-playground) that has a pretty good [example on working with Custom Scalars](https://github.com/apollographql/apollo-client-swift-playground/blob/main/Apollo.playground/Pages/CustomScalars.xcplaygroundpage/Contents.swift). There is also the [Apollo GraphQL Forum](https://community.apollographql.com/tag/mobile) which has loads of useful questions and answers too.
