### ISSUE TITLE
Audit all _ prefixed things to see if they should be available using ApolloExtension.

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#2497]
- [x] `SelectionSet.schema` -> `__schema`
- [x] `SelectionSet.selection` -> `__selection`
- [x] `JSONEncodable.jsonValue` -> `_jsonValue`
  - [x] Add public `jsonValue` to `CustomScalar` with extension to convert to `_jsonValue`
  - [x] `JSONEncodable.jsonValue` -> `_jsonEncodableValue`
- [x] `JSONDecodable.init(jsonValue:)` -> init(_jsonValue:)
- [x] `AnyHashableConvertible.asAnyHashable` -> `AnyHashableConvertible._asAnyHashable`
- [x] `OutputTypeConvertible.asOutputType` -> `OutputTypeConvertible._asOutputType`
- [x] `GraphQLOperation.variables` -> `GraphQLOperation._variables`
  - [x] Same for `LocalCacheMutation.variables`

**Comment by calvincestari** [comment]
This is complete with the merging of #2509
