### ISSUE TITLE
Codegen generate command fails

### ISSUE THREAD

**Issue by alexisbronchart** [apollographql/apollo-ios#2505]
## Bug report

I updated to 1.0.0-beta.4 and also the ApolloCodegen files and now getting this error when I run the `generate` command.
```
Error: Syntax Error: Expected Name, found "[".

/[path_to_project]/ApolloCodegen/.build/checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/graphql/ccnGraphql/ClassroomPetsCCN.graphql:2:16
1 | query ClassroomPetsCCN {
2 |   classroomPets[!]? {
  |                ^
3 |     ...ClassroomPetDetailsCCN

```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0-beta.4
- Xcode version: 14
- Swift version: 5.7
- Package manager: spm

## Steps to reproduce

Use ApolloCodegen as a sub package in project and run the generate command from cli.

## Further info

It seems like the command is matching way too many graphql files. Looking at [this function](https://github.com/apollographql/iOSCodegenTemplate/blob/4534127a133a7fbc5807cc262ac20bc033c3c43d/ApolloCodegen/Sources/ApolloCodegen/main.swift#L91) I don't see where the `targetRootUrl` is actually passed to the configuration or the `ApolloCodegen.build` call.

**Comment by AnthonyMDev** [comment]
Thanks for that! I went ahead and merged your PR into the template. Though you are right, we are going to be deprecating that template soon. Calling into the ApolloCodegen programmatically in your own scripts will always be available, but with 1.0, we are going to be recommending people use the new CLI that @calvincestari built. It works really well and is much easier to get moving with.

We are going to be starting updates to the documentation next week. But that CLI is already distributed with both SPM and Cocoapods installs of Apollo 1.0!
