### ISSUE TITLE
Add `contextIdentifier: UUID?` parameter to `perform(mutation:...)` method on ApolloClient

### ISSUE THREAD

**Issue by marsn-ext** [apollographql/apollo-ios#2514]
Hello!

## Feature request

I'd like to add an optional parameter on `ApolloClient`'s `perform(mutation:...)` method for the `contextIdentiifer: UUID?` of the request. This parameter is already present in the client's `fetch(query:...)` method, but unfortunately missing from  `perform(mutation:...)`. 

## Motivation

I'm interested in a similar functionality described by this other issue https://github.com/apollographql/apollo-ios/issues/2283. In short, I need to add certain headers to specific request instances. Using the `contextIdentifier` helps with this, but this option is not available on mutations.

In the short term, adding the parameter should offer this flexibility for mutations while the H2 networking stack overhaul comes through (as mentioned in the other issue).

## Proposed solution

Add optional `contextIdentifier: UUID?` to `ApolloClient`'s `perform(mutation:...)` method.

## Outstanding Questions

The only potential conflict this PR could add is if integrators have created their own implementation against `ApolloClientProtocol`. In those cases, they will have to repair the conformance since the change is a breaking change on the protocol.

**Comment by marsn-ext** [comment]
I'm happy to draft up a PR for this if this change proposal sounds reasonable 👍

**Comment by calvincestari** [comment]
Hi @marsn-ext, apologies for taking so long to get back to you. At first glance I'm not opposed to adding `contextIdentifier` to the `perform(mutation: .. )` protocol signature. It seems you're aware of the networking stack being the next target for development so if this provides short-term gain without severe downsides I'm fine with it.

@AnthonyMDev - do you have any objection to this addition?

**Comment by vincentisambart** [comment]
It seems this can be closed as the parameter has been added to [1.9.1](https://github.com/apollographql/apollo-ios/releases/tag/1.9.1):
> Feature/ContextIdentifier for the mutate queries (https://github.com/apollographql/apollo-ios-dev/pull/281): Mutation operations can now be given a context identifier to be used later in the request.

**Comment by calvincestari** [comment]
Thanks @vincentisambart, I'd long forgotten that we had an issue for that PR change.
