### ISSUE TITLE
Concurrent downloads of node binary can result in deadlock on `cliFolderURL`

### ISSUE THREAD

**Issue by johnliedtke** [apollographql/apollo-ios#2515]
## Bug report

If multiple processes are attempting to code-generate using the node binary, a deadlock can occur if the process owning the `NSDistributedLock` is killed before it can release the lock on `cliFolderURL`. The only remedy for resolving the deadlock is to manually release/break the lock yourself (e.g. type `NSDistributedLock(...).break()` in `lldb`) or by restarting your computer.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.53.0
- Xcode version: 13.4.1
- Swift version: 5.6
- Package manager: 5.5

## Steps to reproduce

You can reproduce the deadlock in the debugger by placing a breakpoint on this [line](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/ApolloCLI.swift#L23) and manually killing the process (e.g. command + .). When you run the code-gen the next time with the same `cliFolder`, the process will not be able to obtain the `lock` because it was never _released_ by the previous owner.

## Further details

Apple also documents this behavior in some of their [documentation](http://class.ece.iastate.edu/cpre388/Fall2011/lecture/Multithreading.pdf). Below is the relevant snippet:

> Because it is implemented using the file system, an NSDistributedLock object is not released unless the
> owner explicitly releases it. If your application crashes while holding a distributed lock, other clients will be
> unable to access the protected resource. In this situation, you can use the breakLock method to break the
> existing lock so that you can acquire it. Breaking locks should generally be avoided, though, unless you are
> certain the owning process died and cannot release the lock.

Possible solutions:

1. Implement a signal handler that releases the lock if the process is killed from SIGKILL, SIGINT, etc when the process _owns_ the lock. 
2. `break()` the lock if the "download timeout" exceeds the elapsed time between the current date and [lockDate](https://developer.apple.com/documentation/foundation/nsdistributedlock/1413773-lockdate). Or maybe a combination of this and a signal handler (1)? 
3. Ditch the `NSDistributedLock` and enforce a precondition that dependencies are downloaded before attempting to code-generate

I believe (3) is the correct solution as I find it odd and untenable that the Xcode build process is dependent on dependencies being downloaded during the build-process. This also aligns with how other dependencies are managed in iOS, e.g. Carthage, Cocoapods, and SPM all require dependencies be downloaded _before_ kicking off a build—not during the actual build.

**Comment by calvincestari** [comment]
Thanks for the bug report @johnliedtke. We appreciate you taking the time to investigate and recommend a solution but the great news is that v1.0 GA-release is imminent and we can finally stop relying on the legacy CLI tooling. Very soon the `release/1.0` branch will be merged into `main` and this bug report will no longer be relevant.

If you haven't yet tried the new 1.0 release I strongly encourage you to try it. I can keep this issue open until 1.0 is released but in all honesty we won't be supporting the old CLI tooling at that point.

**Comment by johnliedtke** [comment]
@calvincestari, thanks for the quick update! I found the debugging a pleasant change from my day-to-day.

We'll plan on moving to 1.0 soon—in the interim, we have a workaround :D

**Comment by jpvajda** [comment]
@johnliedtke Thanks for updating this issue, it sounds like we can close this one out now?

**Comment by johnliedtke** [comment]
1.0 resolves this issue. CLOSED
