### ISSUE TITLE
No operations or fragments found  - Code Generation during build phase not locating .graphql files in project 

### ISSUE THREAD

**Issue by EMammie** [apollographql/apollo-ios#2522]
## Build Issue

When setting up an iMessage app with Apollo package ver 0.53.0 
during setting up code generation both the Swift Package Manager and Swift Scripting 
encountered this issue:

```
+ '/Users/Person/Desktop/Development_Work/AreYouComing?/ApolloCodegen/ApolloCLI/apollo/bin/run' codegen:generate --target=swift --addTypename '--includes=./**/*.graphql' '--localSchemaFile=/Users/Person/Desktop/Development_Work/AreYouComing?/AreYouComing?/schema.graphqls' '--operationIdsPath=/Users/Person/Desktop/Development_Work/AreYouComing?/AreYouComing?/operationIDs.json' --mergeInFieldsFromFragmentSpreads '/Users/Person/Desktop/Development_Work/AreYouComing?/AreYouComing?/API.swift'

```

```
No operations or fragments found to generate code for.

    Error: No operations or fragments found to generate code for.
```
 Due to  looking at similar build issues [#1](https://github.com/apollographql/apollo-ios/issues/2099)
 
 Things Ive Tried

1.  checking .graphql files are in folder dont contain syntax 
2. checking that .graphql files are saved as .graphql on disk
3. Checking Project Structure / Moving a schema file to different files within the Project

Project Structure
MyProject                  // Source root
├─ MyProject.xcodeproj
├─ MyProject/       //Where  schema.graphals is downloaded too  + Query.graphql
├─ MyProject MessageExtension/              
├─ ApolloCodegen/         
  

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.53.0
- Xcode version: 14.0
- Swift version:  Swift version 5.7

## Steps to reproduce
using the code generation from the apollographql tutorial (tried both Swift Package Manager + Swift Scripting Tutorials)

**Comment by calvincestari** [comment]
Hi @EMammie 👋🏻 - try the command with the `--includes` parameter set to `--includes=/Users/Person/Desktop/Development_Work/AreYouComing?/AreYouComing?/**/*.graphql`. I suspect it's looking in the `/Users/Person/Desktop/Development_Work/AreYouComing?/ApolloCodegen/ApolloCLI/apollo/bin/run` folder because of the relative folder path `./**/*.graphql`.

**Comment by EMammie** [comment]
> Hi @EMammie 👋🏻 - try the command with the `--includes` parameter set to `--includes=/Users/Person/Desktop/Development_Work/AreYouComing?/AreYouComing?/**/*.graphql`. I suspect it's looking in the `/Users/Person/Desktop/Development_Work/AreYouComing?/ApolloCodegen/ApolloCLI/apollo/bin/run` folder because of the relative folder path `./**/*.graphql`.

Hey @calvincestari I am suspecting you theory might be accurate. 
 Im hoping version 1.0 Prod release and installation I will remedy the problem.
 But Ill try to use that absolute path and report back
As of now the way I know how to change that --includes param within the swift scripting flow is to through the designated init of [ApolloCodeGenOptions](https://www.apollographql.com/docs/ios/api/ApolloCodegenLib/structs/ApolloCodegenOptions/) .
Note: Scanning through issues i found a similar issue in #1806

**Comment by calvincestari** [comment]
> Im hoping version 1.0 Prod release and installation I will remedy the problem.

v1.0 has much improved codegen configuration and execution. I'm confident it's a better experience but would love to hear your feedback once you've tried it.

**Comment by AnthonyMDev** [comment]
Closed due to inactivity. Please try migrating to the 1.0 version and open a new issue if you are still having trouble.
