### ISSUE TITLE
apollo-fetch-schema hostname error

### ISSUE THREAD

**Issue by andykent** [apollographql/apollo-ios#2528]
Hi,

I am upgrading from an earlier Alpha to 1.0 rc1 and all has gone fairly smoothly except I am struggling to figure out how schema downloading is supposed to work. I appreciate docs are WIP, I have muddled my way through by guessing at the config but I am now not sure if I have hit a bug or user error at this point.

I am running:

```
swift package --allow-writing-to-package-directory apollo-fetch-schema
```

And I am hitting the error:

```
Error: A server with the specified hostname could not be found.
```

I originally thought this might be some sandboxing weirdness with localhost URLs or non-https URLs so I setup an `ngrok` tunnel and used an https URL that resolves publicly but still no joy.

I include my config below in the hope that it is a silly user error on my part.

```json
{
  "schemaName": "API",
  "schemaDownloadConfiguration": {
    "downloadMethod": {
      "introspection": {
        "endpointURL": "https://foobar.eu.ngrok.io/gql",
        "httpMethod": { "POST": {} },
        "outputFormat": "SDL",
        "includeDeprecatedInputValues": false
      }
    },
    "outputPath": "./schema.graphqls"
  },
  "input": {
    "operationSearchPaths": ["./Sources/FooBar/Queries/*.graphql"],
    "schemaSearchPaths": ["./schema.graphqls"]
  },
  "output": {
    "testMocks": {
      "none": {}
    },
    "schemaTypes": {
      "path": "./Sources/API",
      "moduleType": {
        "other": {}
      }
    },
    "operations": {
      "relative": {}
    }
  }
}
```

**Comment by andykent** [comment]
Ah, so I think it's a sandboxing issue, I was able to make it work with 

```
swift package --disable-sandbox  apollo-fetch-schema
```

I will close this as it was user error on my part but would be good to have in the docs I think.

**Comment by calvincestari** [comment]
Glad you got it working. We're updating the docs this week in preparation of the 1.0 GA release.
