### ISSUE TITLE
extraneous whitespace in generated query

### ISSUE THREAD

**Issue by kluufger** [apollographql/apollo-ios#254]
👋

After generating `API.swift`, I see 
```swift
  public static let operationString =
    "query UserSearch($query: String!) {\n  userSearch(query: $query) {\n    __typename\n    id\n    name\n  }\n}"
    // ...
```
there.

Is this the query that gets sent to the backend? Could all whitespace and `\n` be stripped from it?

**Comment by martijnwalraven** [comment]
Yes, this is the query that gets sent to the backend. It's just how the AST is printed by `graphql-js`. Why are you concerned about the whitespace?

**Comment by kluufger** [comment]
> Why are you concerned about the whitespace?

I'm afraid it would affect my bandwidth bills ...

**Comment by martijnwalraven** [comment]
To be honest, I don't think whitespace will have much effect on bandwidth. The query itself may have a sizable impact however. So if you're concerned about bandwidth, a much better solution would be to use persisted queries. Support for [automatic persisted queries](https://dev-blog.apollodata.com/improve-graphql-performance-with-automatic-persisted-queries-c31d27b8e6ea) in particular would be much welcomed!

**Comment by designatednerd** [comment]
I'm going to close this one out - we've got a few folks taking stabs at APQs, and we're probably going to be switching to a multiline literal for these queries that'll make it easier to see exactly what's in there.
