### ISSUE TITLE
Generated Swift files couldn't find myScheme name related files

### ISSUE THREAD

**Issue by indama** [apollographql/apollo-ios#2557]

**Comment by AnthonyMDev** [comment]
Thanks for the report. In order to better help, could you show us your codegen configuration?

**Comment by AnthonyMDev** [comment]
This may be related to #2546

**Comment by calvincestari** [comment]
Could be related to #2546

**Comment by indama** [comment]
Thank you very much. i was using default configuration: 

> {
>   "schemaName" : "MySchema",
>   "options" : {
>     "cocoapodsCompatibleImportStatements" : true
>   },
>   "input" : {
>     "operationSearchPaths" : [
>       "**/*.graphql"
>     ],
>     "schemaSearchPaths" : [
>       "**/*.graphqls"
>     ]
>   },
>   
>   "output" : {
>     "testMocks" : {
>       "none" : {
>       }
>     },
>     "schemaTypes": {
>             "moduleType": {
>                 "other": {}
>             },
>             "path": "./generated/schema/"
>         },
>     "operations" : {
>       "relative" : {
>       }
>     }
>   }
> }
>

**Comment by AnthonyMDev** [comment]
Very confused here. The title of the post and the config file reference "MySchema" as the schema name, but your screenshot shows `import Graphql` as the offending line. Can you give us a little more information? Where did the name `Graphql` come from?

**Comment by indama** [comment]
I am sorry. I had changed my schema and forget to check the screenshot. Please check below details. First one my configuration file: 

<img width="762" alt="image" src="https://user-images.githubusercontent.com/4445931/195773929-3fa7cd00-27be-4256-8dcf-619e600f5716.png">

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/4445931/195774021-b6cbcf8c-bb8b-4e20-8435-cf283114ad34.png">

<img width="728" alt="image" src="https://user-images.githubusercontent.com/4445931/195774117-5c25041e-8143-4a17-8ce6-44e19651a475.png">

**Comment by AnthonyMDev** [comment]
Ah okay! This is a known issue (#2546) that is being worked on right now. A fix for this will be out ASAP!

**Comment by AnthonyMDev** [comment]
Closing as duplicate. Please follow #2546 for the resolution of this.
