### ISSUE TITLE
Add xcode-select reset to troubleshooting docs

### ISSUE THREAD

**Issue by DanDolog** [apollographql/apollo-ios#2558]
## Bug report
<img width="762" alt="Screen Shot 2022-10-10 at 16 23 52" src="https://user-images.githubusercontent.com/56874498/194865623-dcf6793b-f301-48a1-8537-323509bf233a.png">

Hello, I can't install the latest release (1.0.0) via CocoaPods. Installation fails with error: no such module 'PackageDescription'. Thanks for help!

## Versions
- `apollo-ios` SDK version: 1.0.0
- Xcode version: 14.0.1
- Swift version: 5.7

**Comment by AnthonyMDev** [comment]
Thanks for the report! Odd that no one else has been seeing this yet... Can you provide a few more details please:

1. CocoaPods version
2. MacOS Version
3. CPU type (M1 or Intel)

I'm going to try to reproduce this today some more. Will get back to you soon!

**Comment by calvincestari** [comment]
We had a previous report of this kind of error in #2543 - [see this comment](https://github.com/apollographql/apollo-ios/issues/2543#issuecomment-1267691776). That [user had to do a manual reset](https://github.com/apollographql/apollo-ios/issues/2543#issuecomment-1268446856) to get things working but I think it's definitely related to package dependency weirdness.

**Comment by AnthonyMDev** [comment]
Thanks for the info @calvincestari. Can you check and see if `sudo xcode-select --reset` resolves this issue?

If so, we'll add something to help with this to the Docs!

**Comment by DanDolog** [comment]
Hello! Sorry for a late answer. The problem is really solved by `sudo xcode-select --reset`. Thanks for help!

**Comment by AnthonyMDev** [comment]
Thanks for the followup. We'll get this added to docs.

**Comment by calvincestari** [comment]
I'm going to close this issue as the larger 'troubleshooting guide' issue (https://github.com/apollographql/apollo-ios/issues/2566) will include this.
