### ISSUE TITLE
Lowercase all letters in field names when all capitalized

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#2570]

**Comment by AnthonyMDev** [comment]
I'm thinking this should be in 1.1 instead of 1.0.1 since it is a minor breaking change.

**Comment by calvincestari** [comment]
Sure, sounds good.

**Comment by calvincestari** [comment]
In the same area as https://github.com/apollographql/apollo-ios/issues/2641.

**Comment by BobaFetters** [comment]
Pretty sure this is covered by the work done for #2738
