### ISSUE TITLE
The generated code does not have swift lint directive and causing linting failure

### ISSUE THREAD

**Issue by otusweb** [apollographql/apollo-ios#2573]
## Feature request

Add swift lint directive in generated code 

## Motivation

to not get warnings/error on generated code

## Proposed solution

add `// swiftlint:disable all` at the top of generated files

**Comment by AnthonyMDev** [comment]
I'd recommend you just add an exclusion rule in your swift lint config for files ending in `.graphql.swift`. 

Unless absolutely necessary, we don't want to add generated lines to all of our files that are specifically linked to usage of other 3rd party libraries, even ones as popular as SwiftLint`.

If an exclusion rule will not resolve this issue for you, let us know why now and we can re-open this to consider alternatives.
