### ISSUE TITLE
When using the test mock, touching a GraphQLEnum property will cause a crash

### ISSUE THREAD

**Issue by asapo** [apollographql/apollo-ios#2582]
## Bug report

Like this:

```swift
let mock = Mock<Dog>(type: GraphQLEnum.case(.strong))
let dog = DogFragment.from(mock)

// Crash here:
// Could not cast value of type 'Swift.AnyHashable' to 'ApolloAPI.GraphQLEnum<MySchemaModule.MyEnum>'
dog.type
```

(Actually, crash at this line)
https://github.com/apollographql/apollo-ios/blob/29d42fb5b17a2c1823ec0750af8e628067e43b4c/Sources/ApolloAPI/DataDict.swift#L16

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.1
- Xcode version: 14.0.1
- Swift version: 5.7
- Package manager: 5.7

## Steps to reproduce

- Generate a model that has an enum property.
- Generate test mocks.
- Initialize a model by using `Model.from(Mock())` method.
- Touch an enum property.

**Comment by AnthonyMDev** [comment]
Thanks for the report! We will look into this and have a fix out ASAP.

**Comment by AnthonyMDev** [comment]
PR to fix this is up. Anticipating cutting a release with this included by end of week.

**Comment by asapo** [comment]
Thank you for the quick fix!
