### ISSUE TITLE
Test Mocks: Crashes when touching array of object (Reproduced in main branch)

### ISSUE THREAD

**Issue by konomae** [apollographql/apollo-ios#2588]
## Bug report

Test Mocks: Crashes when touching array of object (Reproduced in main branch)

## Versions

- `apollo-ios` SDK version: main (1045d8ce7ebcfa4485f7022e1afdaf9de1d8404c)
- Xcode version: 14.0
- Swift version: 5.7
- Package manager: 5.7

### 1. Generate schema and test mocks

schema

```graphql
type Dog {
    id: ID!
}

type Query {
    dogs: [Dog!]!
}
```

query

```graphql
query Dogs {
    dogs {
        id
    }
}
```

### 2. Run tests

```swift
class DemoTests: XCTestCase {
    func test_crash() {
        let mock = Mock<Query>(dogs: [])
        DogsQuery.Data.from(mock).dogs // ok
        
        mock.dogs = [Mock(id: "dog-1")]
        // Thread 1: Fatal error: Dog expected data for entity.
        DogsQuery.Data.from(mock).dogs // crash
    }
}
```

<img width="780" alt="screenshot" src="https://user-images.githubusercontent.com/1920783/196413752-c4de9c58-a2f6-44cb-905a-012c13ab117f.png">

## Further details

- Released version `1.0.1` does not have this problem

**Comment by AnthonyMDev** [comment]
Oooof. This must have regressed when I fixed the other crash. I thought we have a test for this, but I will check again and fix this before the 1.0.2 release! Thanks for the report.

Aside from this issue, I'd love to hear feedback on how your experience with Test Mocks has been so far.

**Comment by konomae** [comment]
Thank you for the fix!
I tried `test-mock-list-fix` branch and this crash was solved. 🎉

> Aside from this issue, I'd love to hear feedback on how your experience with Test Mocks has been so far.

So far, it is helpful for migration from 0.x to 1.0. Since it only requires a small rewrite of existing code. 👍

```diff
-let data = MyQuery.Data(
+let data = MyQuery.Data.from(Mock(
     dogs = .init(id: "id")
     // more properties
-)
+))
```

**Comment by AnthonyMDev** [comment]
Glad to hear! Fix in the the main branch now and will be in the 1.0.2 release!
