### ISSUE TITLE
Migrate from 0.x(legacy) 10 1.*

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-ios#2590]
Why we cannot see a migration guide ?
I have been struggling with the new implementation 
Can we find direct steps for that ?

**Comment by calvincestari** [comment]
@sam961 there is no migration guide yet. We're have https://github.com/apollographql/apollo-ios/issues/2576 to get that done.

**Comment by sam961** [comment]
Thank you!

**Comment by bohan-v** [comment]
Looking forward to read a migration guide! We are using 0.48.0, and want to migrate to 1.x.

**Comment by AnthonyMDev** [comment]
I just put up the PR to include the migration guide! Should be up shortly!
