### ISSUE TITLE
Crash in Mock when mocking a type with property that is an array of optional values

### ISSUE THREAD

**Issue by bdunay3** [apollographql/apollo-ios#2593]
## Bug report

We have a query in our graph that can return an array of optional values. When we generate the Swift code from this query we get a property like this:

```swift
var blocks: [Block?] { __data["blocks"] }
```

In our unit tests when we use the `Mock` type to mock the graph data and we put a nil in the that array we get a crash in `SelectionSet`.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0
- Xcode version: 14.0.1
- Swift version: 5.7
- Package manager: 5.7

## Steps to reproduce

Here's a snippet of our unit test code that reproduces the issue:

We define the following mock instance:
```swift
let mockCategoryExperience = Mock<BlockContainer>(blocks: [
    mockBlockDataa,
    nil
])
```

Then when we run the unit test we get a crash in this code from TestMock.swift in the ApolloTestSupport library:
```swift
// MARK: - Selection Set Conversion

public extension SelectionSet {
  static func from(
    _ mock: any AnyMock,
    withVariables variables: GraphQLOperation.Variables? = nil
  ) -> Self {
    Self.init(data: DataDict(mock._jsonObject, variables: variables))
  }
}
```

**Comment by calvincestari** [comment]
Hi @bdunay3, I think your issue is resolved by https://github.com/apollographql/apollo-ios/pull/2591. It hasn't gone out in a release yet, it will be included in `1.0.2`. So if you target `main` for your dependency you should get the fix in the interim.

**Comment by AnthonyMDev** [comment]
Please let us know if this is not fixed in `main` ASAP! I've got a unit test that verifies that this should work right now, but if we're missing something, we'd love to know before the patch release goes out.

**Comment by bdunay3** [comment]
Apologies I couldn't try this before you all shipped the update. But I did just try this with the official 1.0.2 release and it's not crashing any more. Thank you for the quick turn around!!
