### ISSUE TITLE
How to use Codegen CLI with SPM in iOS project

### ISSUE THREAD

**Issue by enheit** [apollographql/apollo-ios#2601]
I tried to follow [The Codegen CLI](https://www.apollographql.com/docs/ios/code-generation/codegen-cli) documentation to be able to initialize, fetch and generate GraphQL types in my iOS project. Unfortunately, step 2 (fetch) and step 3 (generate) don't work for me.

I'm new to iOS and Xcode especially and may not know all the things that should be done.

Here is the list of the steps that I tried to do to make it work:

1. Upon right click on my "project name" I select "Add packages..."
<img width="325" alt="Screenshot 2022-10-22 at 19 48 04" src="https://user-images.githubusercontent.com/8645216/197352445-636ddca6-9522-4cb6-a3f3-c2c22dafa75e.png">

2. Next, I find "apollo-ios" package and specify a concrete version of the package (at this moment it is "1.0.2")
<img width="837" alt="Screenshot 2022-10-22 at 19 49 00" src="https://user-images.githubusercontent.com/8645216/197352480-84972064-ef58-4c09-8547-198f139924f1.png">

3. In the appeared window I select the following options
<img width="641" alt="Screenshot 2022-10-22 at 19 51 09" src="https://user-images.githubusercontent.com/8645216/197352568-d419957a-0a45-4e8a-bec6-5ac56825de06.png">

4. Next, I again right click the "project name" and select "ApolloCodegenPlugin-Initialize"

<img width="383" alt="Screenshot 2022-10-22 at 19 52 39" src="https://user-images.githubusercontent.com/8645216/197352628-9b77450e-03b4-4a79-a24a-c05efeb4818e.png">

5. In the next window I add arguments "--schema-name MyLovelySchema" which is required according to the documentation
<img width="533" alt="Screenshot 2022-10-22 at 19 54 45" src="https://user-images.githubusercontent.com/8645216/197352686-e87baf80-f76a-4f07-bf1e-756acc266487.png">

6. It generates a file ("apollo-codegen-config.json"), but not visible in my project tree. I add this file using the "Add files to "MyProject" button

7. Files appeared in my project tree with following content

```
{
  "schemaName" : "MyLovelySchema",
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "**/*.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : "./MyLovelySchema",
      "moduleType" : {
        "swiftPackageManager" : {
        }
      }
    },
    "operations" : {
      "relative" : {
      }
    }
  }
}
```

8. As far as I am not able to fetch the schema from my backend I added it manually to the project and put it at the same level as "apollo-codegen-config.json" file

<img width="432" alt="Screenshot 2022-10-22 at 19 59 51" src="https://user-images.githubusercontent.com/8645216/197352909-97068bcf-9633-4da9-9c93-856a4f2daa30.png">

9. Now "schema.graphqls" contains my GraphQL types (SDL)
10. I created a test query which is part of my GraphQL and put it under GraphQL folder

<img width="426" alt="Screenshot 2022-10-22 at 20 01 11" src="https://user-images.githubusercontent.com/8645216/197352954-53a6eb12-dc64-4b0a-9840-713764cf228e.png">

11. At this moment I have a configuration file, my schema and query. At this moment I expect to run generator and to see my types generated in the project.

12. I right-click the project name and select "ApolloCodegenPlugin-Generate" button and click "Run" without providing any arguments.

<img width="535" alt="Screenshot 2022-10-22 at 20 03 00" src="https://user-images.githubusercontent.com/8645216/197353035-30c5332f-e241-4fad-be41-9f577eeab6f2.png">

13. In the appeared window I select "Allow Command to Change Files"

<img width="276" alt="Screenshot 2022-10-22 at 20 03 35" src="https://user-images.githubusercontent.com/8645216/197353063-8b6f5200-abe9-48c4-8277-7991eccde969.png">

14. It shows build succeeded in the top right corner

<img width="207" alt="Screenshot 2022-10-22 at 20 04 01" src="https://user-images.githubusercontent.com/8645216/197353083-32736f2b-6343-4629-80ca-7fa8a71a9537.png">

15. I investigate the files of my project and can't find generated files.

<img width="714" alt="Screenshot 2022-10-22 at 20 04 35" src="https://user-images.githubusercontent.com/8645216/197353105-a96b5119-2a1a-4abb-be7b-f3c018ec03c5.png">

I'm not sure if my steps are correct, but this is how I understand the documentation.

Could you help me to understand what I'm doing wrong? And what do I need to do to make it work correctly? 

P.S. There are no tutorials (at least I couldn't find it after Googling it) on how to do it step by step.

---

Information that may be helpful 

macOS: 12.6 (M1)
Xcode: 14.0.1 (14A400)

**Comment by enheit** [comment]
At some point (suddenly), it started to work. I'm able to generate a schema from the `schema.graphqls` file located in my project.

The only problem that remains is Step 2 (from Apollo CLI doc) - Fetching. I loaded my schema in `studio.apollo.graphql` and want to fetch it from there by using [this approach - Apollo Server Registry](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#1-apollo-server-registry). 

Unfortunately, there is only one example of how to fetch a schema, and its for local schema retrospection.

```json
"schemaDownloadConfiguration": {
    "downloadMethod": {
        "introspection": {
            "endpointURL": "https://server.com",
            "httpMethod": {
                "POST": {}
            },
            "includeDeprecatedInputValues": false,
            "outputFormat": "SDL"
        }
    },
    "downloadTimeout": 60,
    "headers": [],
    "outputPath": "./graphql/"
}
```

Could you please provide a short example of how to configure `apollo-codegen-config.json` for fetching schema from `studio.apollographql.com`?

I know what these options (`apiKey`,  `graphID`, `variant`) are but how to use them in the config this is the question

**Comment by calvincestari** [comment]
Hi @enheit  👋🏻 - some answers below:

> 3. In the appeared window I select the following options

You shouldn't include ApolloCodegenLib in an iOS target. [It is for macOS only](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/ApolloCodegen.swift#L5) and will not build in an iOS target.

> 6. It generates a file ("apollo-codegen-config.json"), but not visible in my project tree. I add this file using the "Add files to "MyProject" button

This is correct, we don't change your Xcode project file. You must do this manually.

> 15. I investigate the files of my project and can't find generated files.

Look inside the GraphQL folder for the generated operation file but I think you might be encountering https://github.com/apollographql/apollo-ios/issues/2552 and generation is failing silently. I suggest you try:
1. Move `schema.graphqls` into the `Icelook/GraphQL` folder
2. Change `operationSearchPaths` to `"./Icelook/GraphQL/**/*.graphql"`
3. Change `schemaSearchPaths ` to `"./Icelook/GraphQL/**/*.graphqls"`

> Could you please provide a short example of how to configure apollo-codegen-config.json for fetching schema from studio.apollographql.com?

Here's a sample JSON configuration for downloading from the Apollo Registry:
```
	"schemaDownloadConfiguration": {
		"downloadMethod": {
			"apolloRegistry": {
				"_0": {
					"graphID": "graph_id",
					"apiKey": "your_key",
					"variant": "variant_identifier"
				}
			}
		},
		"headers": [],
		"outputPath": "ServerSchema.graphqls",
		"downloadTimeout": 30
	},
```

**Comment by enheit** [comment]
Hey @calvincestari I changed my config file to this

```json
{
  "schemaName": "IcelookSchema",
  "input": {
    "operationSearchPaths": [
      "./Icelook/GraphQL/**/*.graphql"
    ],
    "schemaSearchPaths": [
      "./Icelook/GraphQL/**/*.graphqls"
    ]
  },
  "output": {
    "testMocks": {
      "none": {}
    },
    "schemaTypes": {
      "path": "./IcelookSchema",
      "moduleType": {
        "swiftPackageManager": {}
      }
    },
    "operations": {
      "relative": {}
    }
  },
  "schemaDownloadConfiguration": {
    "downloadMethod": {
      "apolloRegistry": {
        "_0": {
        "graphID": "icelook-dev-6szijc",
        "apiKey": "service:icelook-dev-6szijc:HbZAcODQEJx6BTsS_VBMog",
        "variant": "current"
        }
      }
    },
    "outputPath": "./test_folder/schema.graphqls",
  }
}
```

and fetching doesn't work :( It creates a folder `test_folder` but does not contain `schema.graphqls` file. I'm not sure if the `variant` option is correct. I took it from the title on the site

<img width="341" alt="Screenshot 2022-10-25 at 01 28 51" src="https://user-images.githubusercontent.com/8645216/197641793-5561c9ae-716e-43af-b15d-9aed818970c6.png">


P.S. `graphID` and `apiKey` are fake.

**Comment by calvincestari** [comment]
If you're doing it through the Xcode menu then it's probably not working because fetching a schema requires the `--disable-sandbox` option because fetching a schema involves a network request. We have not found a solution to this yet and adding it as an argument in the Xcode window does not work because it needs to a SwiftPM argument and not a plugin argument. 

We're strongly considering removing the plugins because the experience is not mature enough yet.

**Comment by enheit** [comment]
@calvincestari Yes, I currently use this menu (image below) to Init, Build and Fetch (doesn't work) graphql schema. I'm not sure how can I do this without this menu. Should I just open a terminal in the same folder where my `apollo-codegen-config.json` is located and run [this commands](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#fetch-schema)?

I can't find `--disable-sandbox` flag in apollo documentation. 

<img width="325" alt="Screenshot 2022-10-25 at 01 48 13" src="https://user-images.githubusercontent.com/8645216/197644271-16fa522a-db8e-43dd-a0f4-2be8fc8f87de.png">

**Comment by calvincestari** [comment]
> Yes, I currently use this menu (image below) to Init, Build and Fetch (doesn't work) graphql schema. I'm not sure how can I do this without this menu. Should I just open a terminal in the same folder where my apollo-codegen-config.json is located and run [these commands](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#fetch-schema)?

Yes, you will need to run it from the command line.

> As far as I understand that --disable-sandbox is your "internal" command that you need to use.

No, it's a Swift Package Manager parameter that let's our plugin make network requests. The whole command will be something like `swift package --disable-sandbox plugin apollo-generate`.

> Is there any step by step guide on how to use a Apollo Codegen CLI? I just tried to call apollo-ios-cli manually by following [the documentation](https://www.apollographql.com/docs/ios/code-generation/codegen-cli) (Manual Installation) and it is not so smooth as I expected

That's the correct steps for manually building and using the CLI. It looks like you need to reset the Xcode package cache. Use `sudo xcode-select --reset ` and try to rebuild the CLI with `make build-cli` again.

**Comment by calvincestari** [comment]
`--disable-sandbox` is only needed if you're fetching the schema with the `apollo-fetch-schema` command or as a step in the `generate` command. If you're only generating code then you won't need it.

**Comment by calvincestari** [comment]
@enheit does your configuration using a `moduleType` of `swiftPackageManager` result in a Swift package within a Swift package? I think I've bumped into this today and it might be the cause of the `no such module 'PackageDescription'
import PackageDescription` error.

**Comment by enheit** [comment]
@calvincestari I skipped this step of getting the schema because the experience is not as smooth as I expected (errors, hard-to-navigate docs for beginners). I manually put the `schema.graphqls` file into my project.
