### ISSUE TITLE
If response parameter is JSON Field: Couldn't convert ... to Swift.String

### ISSUE THREAD

**Issue by indama** [apollographql/apollo-ios#2604]
Could you please any suggestion to avoid this parsing error. Should I write any customization to generated Model?

<img width="765" alt="image" src="https://user-images.githubusercontent.com/4445931/197595598-268d10f2-67ba-4f93-93c3-b1a1107195a0.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/4445931/197595432-abec5d38-7523-4f83-8142-6cb0a7f79b34.png">

<img width="998" alt="image" src="https://user-images.githubusercontent.com/4445931/197596563-c11f8b34-2aa9-4bff-ac32-c90be2eb768f.png">

**Comment by calvincestari** [comment]
@indama it looks like you need to implement a custom scalar, [you can find the documentation on that here](https://www.apollographql.com/docs/ios/custom-scalars).

> By default, each custom scalar is treated as a Swift String, but you can customize the type of all of your custom scalars with Apollo iOS!

**Comment by indama** [comment]
> treated

Thank you very much!
