### ISSUE TITLE
No such module "Ordered Collections" when importing Apollo SPM on Xcode 14.

### ISSUE THREAD

**Issue by SraavanChevireddy** [apollographql/apollo-ios#2611]
## Bug report

I'm trying to add `apollo-ios` using SPM. I added the required dependencies which I need. They are

1. Apollo
2. ApolloAPI
3. ApolloSqLite
4. ApolloTestSupport
5. ApolloCodeGen
6. ApolloWebSocket
7. Apollo-CLI

When I'm trying to build the Application, It says No Such Module Ordered Collection. I tried adding the actual Ordered Collection package that comes from Apple. And, it's still the same.

I tried using only Apollo as a dependency, It gives an error saying all other packages.

![Screen Shot 2022-10-26 at 11 31 25 PM](https://user-images.githubusercontent.com/63583829/198101897-3ac98571-c613-4868-8588-775d3320f21b.png)

## Versions

- `apollo-ios` SDK version: 1.0.2
- Xcode version: 14.0
- Package manager:  SPM

Its an empty project and nothing is added there except Apollo SPM. Only after adding the Apollo from SPM, it is failing. Can you please fix this? Or any other help will be very much helpful! Thank you.

**Comment by calvincestari** [comment]
Thanks for the bug report @SraavanChevireddy, I can replicate this issue and I'll have to take a deeper look into it.

Please note though that `ApolloCodegenLib` is a macOS only target, so if your project is deployed to iOS it won't build. You also probably don't need to link to the `apollo-ios-cli` target either.

**Comment by calvincestari** [comment]
+1 for this from https://github.com/apollographql/apollo-ios/issues/2632.

**Comment by bakhirevp** [comment]
> Thanks for the bug report @SraavanChevireddy, I can replicate this issue and I'll have to take a deeper look into it.
> 
> Please note though that `ApolloCodegenLib` is a macOS only target, so if your project is deployed to iOS it won't build. You also probably don't need to link to the `apollo-ios-cli` target either.

Without **ApolloCodegenLib** and **apollo-ios-cli** I had the error:

clang: error: no such file or directory: '.../Build/Products/Debug-iphonesimulator/PackageFrameworks/Apollo-Dynamic.framework/Apollo-Dynamic'

**Comment by AnthonyMDev** [comment]
Just to add more explanation for anyone encountering this issue: It looks like you're trying to use the `ApolloCodegenLib` from an iOS target. This isn't actually supported. @calvincestari and I just talked about how we probably need to restructure the `Package.swift` file to make this more apparent.

The `ApolloCodegenLib`, is used to _run_ codegen, which you only need to do from a MacOS target. The generated models themselves can be included in your `iOS` project, and they link to the `ApolloAPI` target which contains all the necessary SDK objects.

You also don't really need to ever include `ApolloCodegenLib` unless you want to [run codegen within your own Swift script target as described in our docs here.](https://www.apollographql.com/docs/ios/code-generation/run-codegen-in-swift-code) This is an advanced use case. For most users, you can just use the codegen CLI, and ignore `ApolloCodegenLib` completely.

--- 
@bakhirevp 
> Without ApolloCodegenLib and apollo-ios-cli I had the error:

> clang: error: no such file or directory: '.../Build/Products/Debug-iphonesimulator/PackageFrameworks/Apollo-Dynamic.framework/Apollo-Dynamic'

You shouldn't need to link `Apollo-Dynamic` either, try removing that one also.

**Comment by calvincestari** [comment]
I'm closing this as a non issue related to linking the ApolloCodegenLib library to a non-macOS target.
