### ISSUE TITLE
apollo-codegen-configuration.json requires "moduleType" to be populated.

### ISSUE THREAD

**Issue by markckim** [apollographql/apollo-ios#2612]
## Bug report

Configuring `apollo-codegen-configuration.json` requires filling out  "moduleType". "moduleType" seems to determine what gets imported in the generated graphql files when you run `./apollo-ios-cli generate`, but this does not seem necessary since the graphql files are part of my project. 

Removing "moduleType" from the config json file produces an error when running the generate script.

Setting "moduleType" to my project ("xphealth_ios") results in the following warning within all of my generated graphql files:

> `import xphealth_ios`
> File 'xxx.graphql.swift' is part of module 'xphealth_ios'; ignoring import'

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.2
- Xcode version: 14.0 (14A309)
- Swift version: 5.7
- Package manager: 

## Steps to reproduce

1. Within `apollo-codegen-configuration.json`, set "moduleType" to my project "xphealth_ios"
```
...
    "schemaTypes" : {
      "path": "./Graphqlschema",
      "moduleType": {
          "embeddedInTarget": {
              "name": "xphealth_ios"
          }
      },
    },
...
```
2. run `./apollo-ios-cli generate` to generate graphql files
3. generated graphql files produce a warning for unnecessary import: `import xphealth_ios`

## Further details

I would like the ability to remove the `import` requirement from the config json file.

I'm also open to other ideas, especially if I'm using the script incorrectly.

## Atachments

![Screen Shot 2022-10-25 at 4 08 24 PM](https://user-images.githubusercontent.com/1800538/198104863-3578b028-1f43-4cd9-9fd4-633f91140ecb.png)

![Screen Shot 2022-10-26 at 10 50 01 AM](https://user-images.githubusercontent.com/1800538/198104875-6b6c9ba8-02e1-4c85-b480-8fcd9191c89b.png)

**Comment by calvincestari** [comment]
Hi @markckim 👋🏻 - this is by-design and required. All configuration options are documented [here](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration), let me know if you think there is information lacking and how the documentation can be improved.

> but this does not seem necessary since the graphql files are part of my project.

Apollo iOS cannot determine whether the files are part of a project nor how that project is configured. That's why we need you to configure the code generation engine so the correct import statements and module structure are produced.

My hunch is that you have [`operations`](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#operations) configured as `.relative(subpath:)` or `.absolute(path:)`. Try `.inSchemaModule` and the import statements _shouldn't_ be generated.

**Comment by calvincestari** [comment]
I've just tried a new project with the same configuration and I do not get an import statement referencing the embeddedInTarget name.

Be aware that `.inSchemaModule` will generate the files into the same location as the schema types, which from your configuration looks like `./Graphqlschema`. Make sure you're not possibly looking at the older generated files before changing to `.inSchemaModule`.

**Comment by markckim** [comment]
@calvincestari -- thanks for your help! I think I figured it out. Using `.inSchemaModule`, I was able to remove `import xphealth_ios` from the generated files.

The final issue that was causing build issues was that the generated graphql structs were wrapped inside `public extension Graphqlschema { ...`, so I had to prefix my existing graphql variables with `"Graphqlschema"`.

I assume this is because the config json file contains:

`"schemaName" : "Graphqlschema"`

Screenshot of generated file:

![Screen Shot 2022-10-26 at 6 18 14 PM](https://user-images.githubusercontent.com/1800538/198168682-db332964-6b43-4f2c-928e-4b6d9927684c.png)

Thanks again for your help! It was very much appreciated.

**Comment by calvincestari** [comment]
Glad it's now working for you.

> Using .inSchemaModule, I was able to remove import xphealth_ios from the generated files.

Do you mean the generated code no longer has it or you have to manually remove it?

> The final issue that was causing build issues was that the generated graphql structs were wrapped inside public extension Graphqlschema { ..., so I had to prefix my existing usage of graphql variables with "Graphqlschema".

When using `.embeddedInTarget(name:)` we namespace all the generated code in a caseless enum to prevent any conflict of type names that you may already have in your existing target. The documentation notes this behaviour in the [Embedded in target](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#embedded-in-target) section.
> No module will be created for the schema types. Instead, generated schema types will be enclosed in a [caseless namespace enum](https://www.swiftbysundell.com/articles/powerful-ways-to-use-swift-enums/#namespaces-and-non-initializable-types).

**Comment by markckim** [comment]
> Do you mean the generated code no longer has it or you have to manually remove it?

Yup, it worked the way you mentioned earlier. The generated code no longer had the import.

Makes sense on the namespacing and it’s a good idea from your guys’ end. Thanks for pointing me to the relevant documentation!
