### ISSUE TITLE
SPM w/ Xcode leads to inconsistent package state

### ISSUE THREAD

**Issue by lleadbet** [apollographql/apollo-ios#2621]
## Bug report

SPM w/ Xcode seems to not load local packages properly when not nested within a project folder. 

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.2 & main branch
- Xcode version:  14.0.1
- Swift version: 5.7
- Package manager: SPM via Xcode

## Steps to reproduce

Run through the doc-noted setup to initialize a new codegen file, and add your GraphQL schema + operations in your source. 

![Screen Shot 2022-10-28 at 10 34 13 AM](https://user-images.githubusercontent.com/5595530/198651280-248b6991-49c3-4636-ade5-9d192ac90c87.png)

After generation using the default file, add the package (as noted) as a local package. Note that the RocketReserver folder here is the actual iOS application source folder. 

![image](https://user-images.githubusercontent.com/5595530/198652021-384194e4-006e-4d7c-9016-6880c63a7db1.png)

It shows up under packages as a folder instead of as a package: 

![Screen Shot 2022-10-28 at 10 35 06 AM](https://user-images.githubusercontent.com/5595530/198652235-3f7b1886-5d6f-4ea4-9ff4-d69966ff252e.png)

Resulting in it not being listed as a framework to add for use within the application: 

![Screen Shot 2022-10-28 at 10 35 31 AM](https://user-images.githubusercontent.com/5595530/198652433-bf687700-90eb-4693-aeb1-1aeebbea4c05.png)

This can be resolved by running `xcodebuild -resolvePackageDependencies` w/in the folder containing the `.xcodeproj` file and reloading Xcode.

**Comment by calvincestari** [comment]
This is a pretty interesting bug, thanks for creating this issue @lleadbet. I'm not quite sure how to resolve it just yet though.

**Comment by AnthonyMDev** [comment]
You can also re-resolve package dependencies from the menu `File > Packages > Resolve Package Versions`.

This seems to be an Xcode bug that will hopefully be resolved in future versions. But there isn't anything we can do about it really, and the workaround is just to manually re-resolve package versions. Going to close this issue
