### ISSUE TITLE
Add back mergeInFieldsFromFragmentSpreads functionality.

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#2625]
## Feature request

Add back `mergeInFieldsFromFragmentSpreads` functionality. Based on the text here, it sounds like it is possible https://github.com/apollographql/apollo-ios/blob/main/CodegenProposal.md#fragment-fields-are-always-merged-in.

## Motivation

There is a part of our supergraph where the use of `mergeInFieldsFromFragmentSpreads`  is very much a mitigation. Now after the Apollo 1.0 upgrade, we are not really seeing a reduction in codegen size over time, but maybe even an increase. For example, there was just a few lines of GraphQL at the top-level added, but it had many fragment depths which altogether increased codegen by 2206 lines.

## Proposed solution

Implement what is suggested here https://github.com/apollographql/apollo-ios/blob/main/CodegenProposal.md#fragment-fields-are-always-merged-in

**Comment by calvincestari** [comment]
Hiya @jimisaacs - we're aware of the issue and are tracking it's progress in https://github.com/apollographql/apollo-ios/issues/2560 - see [this comment](https://github.com/apollographql/apollo-ios/issues/2560#issuecomment-1276442846). I'm going to close this issue as a duplicate but link to it in #2560 so we know it has increased priority.
