### ISSUE TITLE
Infinite reconnection cycle when internet connection is lost

### ISSUE THREAD

**Issue by psi-gh** [apollographql/apollo-ios#264]
This method leads to endless loop when internet on device is missing (if you turn on airplane mode for example)

```
  public func websocketDidDisconnect(socket: WebSocketClient, error: Error?) {
    
    // report any error to all subscribers
    if let error = error {
      self.error = WebSocketError(payload: nil, error: error, kind: .networkError)
      for (_,responseHandler) in subscribers {
        responseHandler(nil,error)
      }
    } else {
      self.error = nil
    }
    
    acked = false // need new connect and ack before sending
    
    if (reconnect) {
      websocket?.connect();
    }
    
  }
```

While internet is not available i got tons of this messages in log in deadloop. CPU loading at this moment is 90%

    2018-04-16 18:52:36.892058+0300 xxx[11800:3587084] [] nw_connection_get_connected_socket 15 Connection has no connected handler
    2018-04-16 18:52:36.892139+0300 xxx[11800:3587084] TCP Conn 0x1c8170c80 Failed : error 0:50 [50]

**Comment by psi-gh** [comment]
Probably good solution will be hook up to https://github.com/ashleymills/Reachability.swift when reconnecting.
Still not very clear for me what to do if server shutted down (but internet connection is available). Maybe need attempts to reconnect with exponential backoff.

**Comment by psi-gh** [comment]
Temporary fixed by adding time interval between reconnections. Was

```      
websocket?.connect();
```

Now: 

```
DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {self.websocket?.connect()})
```

**Comment by designatednerd** [comment]
Closing this out as the PR with the fix has been merged 🎉
