### ISSUE TITLE
Generated MockObjects sometimes cause an infinite recursion warning

### ISSUE THREAD

**Issue by bdunay3** [apollographql/apollo-ios#2654]
## Bug report

When generating mock object types with the code generation tool we are seeing cases where the extension on the `Mock` type will create a convenience init that takes no parameters and calls `self.init()` thus resulting the compiler warning "Function call causes an infinite recursion."

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.2
- Xcode version: 14.1
- Swift version: 5.7
- Package manager: 5.7

## Steps to reproduce

We are seeing this when we generate code for a query that doesn't ask for an entire sub-object type. For example say in our schema we define a type in our schema that has this kind of property graph:

Stuff
  id: Int!
  title: String
  ValuePropLink
    url: String!
    id: Int!
    
And we write a query that's something like:

```
query getStuff() {
    Stuff() {
        id
        title
    }
}
```

When we run the code generation tool configuring it to generate mock object we would expect that no mock type would be generated for ValuePropLink. But instead we see this file created:
```swift
import ApolloTestSupport
import SharedGraphTypes

public class ValuePropLink: MockObject {
  public static let objectType: Object = FederatedGraphSharedTypes.Objects.ValuePropLink
  public static let _mockFields = MockFields()
  public typealias MockValueCollectionType = Array<Mock<ValuePropLink>>

  public struct MockFields {
  }
}

public extension Mock where O == ValuePropLink {
  convenience init(
  ) {
    self.init()
  }
}
```

As you can see, if one where to call the convenience init where `O` is `ValuePropLink` it would just call itself recursively until the system runs out of stack memory.

What we would expect to see is the mock type would be generated. Looking through the code It appears that the mock code generator isn't checking to see if the field list is empty before writing the mock code template out to disk.

**Comment by calvincestari** [comment]
Hi @bdunay3 👋🏻 - good news! This is already fixed with https://github.com/apollographql/apollo-ios/pull/2634, which is merged into `main` but not yet in a release. It will go out in `1.0.4` soon.
