### ISSUE TITLE
need held while installing apollo (version 1.0.3) Via cocoapods ,getting error as follows.

### ISSUE THREAD

**Issue by bhushanrocks412** [apollographql/apollo-ios#2655]
Hi i am getting following error in terminal while installing Apollo version '1.0.3' via cocoapods in my ios swift application,
can anyone help me with this. Thanks 
---------------------------------------------------
pod install
Analyzing dependencies
Downloading dependencies
Installing Apollo (1.0.3)
[!] /bin/bash -c 
set -e
make clean build-cli-for-cocoapods
cp .build/release/apollo-ios-cli apollo-ios-cli
chmod +x apollo-ios-cli

swift package clean
swift build --product apollo-ios-cli -c release -Xswiftc -DCOCOAPODS
/Users/bhushandeshmukh/Library/Caches/CocoaPods/Pods/Release/Apollo/1.0.3-936d4: error: package at '/Users/bhushandeshmukh/Library/Caches/CocoaPods/Pods/Release/Apollo/1.0.3-936d4' is using Swift tools version 5.6.0 but the installed version is 5.5.0
make: *** [build-cli-for-cocoapods] Error 1
-----------------------------------------------------

**Comment by calvincestari** [comment]
I see that the podspec spec does allow for specifying a minimum Swift version using [`swift_versions`](https://guides.cocoapods.org/syntax/podspec.html), I think we should consider adding this to our podspec to avoid this kind of mismatch in the future.

**Comment by bhushanrocks412** [comment]
Thanks @calvincestari & @AnthonyMDev ... after upgrading Xcode to latest version, issue is now resolved. appreciate your response. there was no reason to not upgrade to latest Xcode version.
