### ISSUE TITLE
codegen `Value of type 'InputDict' has no member 'xxxxx'`

### ISSUE THREAD

**Issue by mattia-lau** [apollographql/apollo-ios#2660]
Having `Value of type 'InputDict' has no member 'xxxxx'` issue.

<img width="887" alt="Screenshot 2022-11-12 at 10 43 04 AM" src="https://user-images.githubusercontent.com/56153201/201452957-a653393a-be3f-4e2f-8552-2be65b72fcfb.png">

To reproduct the issue:
1. apollo-ios-cli fetch-schema
2. apollo-ios-cli generate
3. Add packages -> Add local -> Select generated package
4. Add generated package to `Frameworks, Libraries, and Embedded Content`
5. Build.

## apollo-codegen-config.json
```json
{
  "schemaName" : "Test",
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "./graphql/schema.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
        "moduleType": {
            "swiftPackageManager": {}
        },
        "path": "./generated/schema/"
    },
    "operations" : {
      "relative" : {
      }
    }
  },
  "schemaDownloadConfiguration": {
      "downloadMethod": {
          "introspection": {
              "endpointURL": "http://localhost:4000/graphql",
              "httpMethod": {
                  "POST": {}
              },
              "includeDeprecatedInputValues": false,
              "outputFormat": "SDL"
          }
      },
      "downloadTimeout": 60,
      "headers": [],
      "outputPath": "./graphql/schema.graphqls"
  }
}

```

**Comment by gawen** [comment]
@mattia-lau I'm facing the same issue. How did you sort it out? Thanks.

**Comment by calvincestari** [comment]
> EDIT: I was using an outdated CLI apollo-ios-cli. Upgraded to from 1.0.0 to 1.0.3 and it worked.

The next release, `1.0.4`, will have warnings to detect when you're using an outdated CLI to generate the code.
