### ISSUE TITLE
No value associated with key CodingKeys when passing authorization in headers in codegen-config file

### ISSUE THREAD

**Issue by nikitrivedii** [apollographql/apollo-ios#2661]
## Bug report

I am trying to upgrade apollo SDK to 1.0.2 version.

when configuring codegen-config file I need to pass headers and bearer token as dict key value.

I am getting following error

<img width="730" alt="Screenshot 2022-11-14 at 1 05 51 PM" src="https://user-images.githubusercontent.com/47881759/201602037-b7513ac7-31c6-471e-b80d-de49760787d8.png">

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.2
- Xcode version: 14.1
- Swift version: 5
- Package manager: SPM

## Steps to reproduce

```
{
  "schemaName" : "My Schema",
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "**/*.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : "./mySchema",
      "moduleType" : {
        "swiftPackageManager" : {
        }
      }
    },
    "operations" : {
      "relative" : {
      }
    },
    "operationIdentifiersPath": "./Generated/"
  },
  "schemaDownloadConfiguration": {
      "downloadMethod": {
          "introspection": {
              "endpointURL": "my url",
              "httpMethod": {
                  "POST": {}
              },
              "includeDeprecatedInputValues": false,
              "outputFormat": "SDL"
          }
      },
      "downloadTimeout": 60,
      "headers": [{"Authorization":"Bearer  my token"}],
      "outputPath": "./GraphQL/"
  }
}
```

My shell script is

```
./apollo-ios-cli fetch-schema 
    
./apollo-ios-cli generate
```

Try to fetch the schema

**Comment by calvincestari** [comment]
Hi @nikitrivedii, thanks for the issue. The JSON data you've got there looks correct, we'll take a deeper look into the decoding.

**Comment by pavelmarchuk** [comment]
The following snippet works (not very intuitive though):
```
"headers": [ 
        {
          "key": "Authorization",
          "value": "Bearer TOKEN"
        }
      ]
```

**Comment by calvincestari** [comment]
I agree, it's not intuitive at all. I'm going to explore whether I can get decoding working with the more intuitive `"headers": [{"Authorization":"Bearer  my token"}]`.

**Comment by Akhil-P41** [comment]
Hi, @calvincestari any update on this issue? The @pavelmarchuk workaround is not working for me and getting the same error as @nikitrivedii.

```
 "headers": [ 
  {
    "key": "Authorization",
     "value": "Bearer TOKEN"
  }
]
```
Error:
![image](https://user-images.githubusercontent.com/96172451/205626245-70eaeec2-36f6-4bd6-b72b-5cc7ac029c2f.png)

**Comment by calvincestari** [comment]
Hi @Akhil-P41 👋🏻 - no progress on this issue yet. Your issue is not related to this though; you're using the wrong command parameters.

The [`generate` command help menu](https://github.com/apollographql/apollo-ios/tree/main/Sources/apollo-ios-cli#generate) states that `-s` (short format for `--string`) will override `-p` (short format for `--path`). What's happening is that the is CLI is trying to interpret `"Schema-name"` as your configuration JSON. Drop the `-s` parameter and the command should work for you.

**Comment by calvincestari** [comment]
Hi @nikitrivedii, this is fixed and will go out in the next patch release - `1.0.7`.
