### ISSUE TITLE
Namespace collision when using Schema for schemaName

### ISSUE THREAD

**Issue by StarLard** [apollographql/apollo-ios#2664]
## Bug report

When you pass `schema` for `schemaName` to generate types using the `swiftPackageManager` , the generated code will not compile because the generated module collides with an Apollo `Schema` type. It would be great if we document invalid `schemaName` values somewhere or use explicit namespacing in Apollo to avoid this.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version: 14.0.1
- Swift version: 5.7
- Package manager: SPM

## Steps to reproduce

1. Generate code using the `swiftPackageManager` module type using `schema` for `schemaName`
2. Add generated Swift Package to target
3. Attempt to build project
4. Observe error

**Comment by StarLard** [comment]
For context I ran into this issue because my schema is named `schema.graphqls` and I was attempting to pass the name of my schema file; I think https://github.com/apollographql/apollo-ios/issues/2642 would also help avoid this issue.

**Comment by calvincestari** [comment]
Thanks for reporting this @StarLard. We'll take a look into this and see what we can do about it.
