### ISSUE TITLE
Generated mocks are not namespaced properly

### ISSUE THREAD

**Issue by scottasoutherland** [apollographql/apollo-ios#2669]
## Bug report

In our graphQL schema, we have custom scalars "Date" and "URL" . The generated code for these is 

```
public typealias Date = String
public typealias URL = String
```

Perhaps these were poor name choices, but they have existed for sometime. 

This is fine, we get some issues in our code about collisions, but that's fine because we can specify either Foundation.Date or OUR_NAMSPACE.Date. And the usages in the actual generated code for queries are namespaced properly as OUR_NAMESPACE.Date. However, when we generate the mocks using `testMocks` on our `FileOutput` , the types are *not* namespaced. This means we get compiler errors on our generated code like:

`'URL' is ambiguous for type lookup in this context`

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version: 13.4
- Swift version: 5.6
- Package manager:  Codegen uses SPM, but our apps use Cocoapods 1.11.3

## Steps to reproduce

- Create a schema with custom scalars `Date` or `URL`
- Run codegen with `testMocks`
- Try compile test mocks. 

## Further details

N/A

**Comment by CraigSiemens** [comment]
I think our codebase will have a similar issue. We have multiple modules in out app so we previously used the option `customScalarFormat: .passthroughWithPrefix("Scalar.")` so that we could have one lower level module define the scalars for the generated code to use.

**Comment by scottasoutherland** [comment]
Taking a look at the code, it *seems* like this should be happening already, but isn't , it's unclear why to me so far: 

https://github.com/apollographql/apollo-ios/blob/bbe936249a3b2f042ade1c7b855846b8faea0543/Sources/ApolloCodegenLib/Templates/RenderingHelpers/GraphQLType%2BRendered.swift#L113

**Comment by calvincestari** [comment]
Thanks for reporting the issue, I'll take a look into it.

**Comment by scottasoutherland** [comment]
So it seems like perhaps i've just misunderstood. Seems like settting my SchemaTypesFileOutput.moduleType to be `embeddedInTarget` does namespace it properly.
