### ISSUE TITLE
Quotes in operation identifiers are not escaped

### ISSUE THREAD

**Issue by StarLard** [apollographql/apollo-ios#2671]
## Bug report

Code generated when using the `operationIdentifiersPath` output option which contains String values with escaped quotes in in the associated operation id JSON map file does not correctly escape the quotes in the generated code; which consequently, causes the generated code to fail compilation.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version: 14.0.1
- Swift version: 5.7
- Package manager: SPM

## Steps to reproduce

1. Generate code for an operation which contains a string literal value, like `"query Sections($id: String!, platform: \"ios\")"`
2. Add generated code to project
3. Attempt to build project
4. Observe compiler error; generated code will contain String with non-escaped quotes like `"query Sections($id: String!, platform: "ios")"`

**Comment by calvincestari** [comment]
Thanks for reporting this @StarLard, I'll need to take a deeper look and get back to you.

**Comment by StarLard** [comment]
Appreciate it! I believe this is our team's last blocker on updating to 1.0.

**Comment by calvincestari** [comment]
Looking into this it appears it's only an issue when using `QueryStringLiteralFormat.singleLine` as the `options.queryStringLiteralFormat` value. `QueryStringLiteralFormat.multiline` works as expected because inner quotes are not a problem with multiline string literals in Swift.

Seems like an easy fix though, should have it sorted soon.

**Comment by calvincestari** [comment]
@StarLard, this is now fixed and available in `main`; it will go out in the next release.
