### ISSUE TITLE
The apollo-ios-cli tool does not support Intel   CPU

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [apollographql/apollo-ios#2680]
Hi, team. Does it make sense that only M1 based client tool released?
What about the Intel one?

https://github.com/apollographql/apollo-ios/releases/download/1.0.4/apollo-ios-cli.tar.gz

**Comment by calvincestari** [comment]
It's a mistake. We'll get it fixed.

**Comment by calvincestari** [comment]
It should be fixed now, for both `1.0.4` and `1.0.3`
```
❯ curl -LO https://github.com/apollographql/apollo-ios/releases/download/1.0.4/apollo-ios-cli.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2621k  100 2621k    0     0  3528k      0 --:--:-- --:--:-- --:--:-- 12.8M
❯ tar -xf apollo-ios-cli.tar.gz
❯ ./apollo-ios-cli --version
1.0.4
❯ lipo -info apollo-ios-cli
Architectures in the fat file: apollo-ios-cli are: x86_64 arm64
```

**Comment by jinaiyuanbaojie** [comment]
> It's a mistake. We'll get it fixed.

Thanks for your quickly response, man.

I just want to know could you build a Intel one on M1 Macbook?
Or you build them separately and then combine them with lipo

**Comment by calvincestari** [comment]
It's one command to build both - `swift build --product apollo-ios-cli -c release --arch arm64 --arch x86_64`

**Comment by jinaiyuanbaojie** [comment]
> It's one command to build both - `swift build --product apollo-ios-cli -c release --arch arm64 --arch x86_64`

@calvincestari Good day.
Could you build the released client tool with an official apple provision profile?

**Comment by calvincestari** [comment]
> Could you build the released client tool with an official apple provision profile?

Is there a particular reason you need that? I'm not sure that's even possible with just an executable binary; I think it would need to be packaged in a `.app` container for that all to work?
