### ISSUE TITLE
GitHubAPI exports Star Wars API version variables instead of its own version

### ISSUE THREAD

**Issue by AndreyBozhko** [apollographql/apollo-ios#2689]
## Bug report

It looks like GitHubAPI.h file was copy-pasted from StarWarsAPI.h:

https://github.com/apollographql/apollo-ios/blob/014660b14262df15f0d2c7b7e973d0a53be27b7e/Sources/GitHubAPI/GitHubAPI.h#L3-L7

**Comment by calvincestari** [comment]
Hi @AndreyBozhko, thanks for creating this issue. I wouldn't class this as a bug though since it's not in any production code that would ship in an app. PR #2692 will get rid of them.
