### ISSUE TITLE
Empty Files/Folder/Codefiles generated when `moduleType` is set to `embeddedInTarget`

### ISSUE THREAD

**Issue by elviva404** [apollographql/apollo-ios#2694]
## Bug report

I replaced `moduleType` from packageManager to `embeddedInTarget` and when I later run code generation, the generated files are empty, ie they do not contain generated artefacts(objects, enums, custom scalars, etc)

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: main
- Xcode version: 14.0
- Swift version: 5.7
- Package manager: N/A

## Steps to reproduce

1. In the `apollo-codegen-config`, set `"moduleType"` in the `schemaTypes` object to `"embeddedInTarget" : { "name": "checkout-ios-sdk"}`

2. Run `swift package --allow-writing-to-package-directory apollo-generate --path 'apollo-codegen-config.json' -v`

I followed @AnthonyMDev of deleting my `GenSchema` folder, unfortunately the issue still occurs.

<img width="846" alt="Screenshot 2022-11-29 at 7 30 09 PM" src="https://user-images.githubusercontent.com/33577593/204637226-0ecc8c99-cd9f-4602-903a-d294dfa32ef4.png">
<img width="1311" alt="Screenshot 2022-11-29 at 7 32 30 PM" src="https://user-images.githubusercontent.com/33577593/204637234-3896824b-511a-40c9-9444-322c21ac2abe.png">
<img width="488" alt="Screenshot 2022-11-29 at 8 09 55 PM" src="https://user-images.githubusercontent.com/33577593/204637576-0edbd772-0a7d-49d5-90c7-a89ca3b7a7c6.png">

**Comment by AnthonyMDev** [comment]
It sounds like maybe your schema files aren't being picked up correctly. In the latest patch version, we've added some better validation and error messages around this to help debug.

Please try updating to `1.0.6` and see what you get. In this version we've removed the SPM plugin, as it was causing a bunch of issues. So you'll want to check out the new installation directions here: https://www.apollographql.com/docs/ios/get-started/#4-setup-and-run-code-generation.

--- 

I also see that you have `cocoapodsCompatibleImportStatements` set to `true`. That certainly isn't related to this problem, but if you are using SPM, that should likely be `false`. If, once you get files generating properly, you are getting import errors for missing types, try changing that.

😃

**Comment by elviva404** [comment]
Awesome thanks will try your recommendations and give you feedback

**Comment by calvincestari** [comment]
> One more issue please, my schema namespace is CheckoutSchema, and when I try to access its content Xcode tells me "This enum is not available in this context"

Are you correctly importing the schema types module into the file where you're trying to use the namespace?

**Comment by elviva404** [comment]
@calvincestari , do you mean am I setting the right target in the `apollo-codegen-config file` ? if yes,I think I am. Attached a screenshot for confirmation. 
Regards.

<img width="327" alt="Screenshot 2022-11-30 at 10 45 16 PM" src="https://user-images.githubusercontent.com/33577593/204924417-3ccc619d-251c-4c35-a094-2c0fbdc02a10.png">
<img width="352" alt="Screenshot 2022-11-30 at 10 46 51 PM" src="https://user-images.githubusercontent.com/33577593/204924609-d6e10372-ab14-49f9-905c-fd2bd0c6b8eb.png">

**Comment by calvincestari** [comment]
I'm not sure. Have you tried replicating this in a sample project? That may help you narrow down on the issue if that sample project doesn't exhibit the same build error.

**Comment by elviva404** [comment]
Okay, not done that yet. trying that, will let you know how it goes..Thanks.

**Comment by AnthonyMDev** [comment]
Any update on this issue @elviva404?

**Comment by elviva404** [comment]
It has been resolved. Thanks
