### ISSUE TITLE
Code generation build script errors 

### ISSUE THREAD

**Issue by zoufishanmehdi** [apollographql/apollo-ios#270]
Hi, I'm following the installation steps on Apollo iOS Guide. So far I have installed cocoapods, added code generation build step, added a schema file and built the project. Upon building the project, I get the following error: 

`++ exec apollo-codegen generate '**/*.graphql' --schema schema.json --output API.swift
SyntaxError: /Users/zoufmehdi/Projects/Healthie/NewHealthie/healthie-master/healthie_ios/Healthie/schema.json: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.loadSchema (/usr/local/lib/node_modules/apollo-codegen/src/loading.ts:24:22)
    at Object.generate (/usr/local/lib/node_modules/apollo-codegen/src/generate.ts:34:7)
    at Object.yargs.command.command.command.argv [as handler] (/usr/local/lib/node_modules/apollo-codegen/src/cli.js:207:7)
Command /bin/sh failed with exit code 1`

Any idea? I copied the following run script from Apollo iOS Guide so I'm not sure what the issue is: 

`APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"
if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
  echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
  exit 1
fi
cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift`

**Comment by martijnwalraven** [comment]
It seems your `schema.json` contains invalid characters. Are you sure this is actually an introspection query result?

**Comment by zoufishanmehdi** [comment]
My schema.json file contains the following code: 
`apollo-codegen download-schema http://localhost:8080/graphql --output schema.json`

I just replaced `http://localhost:8080/graphql` with my server

**Comment by martijnwalraven** [comment]
Oh, that is the code you execute to generate your `schema.json`, not the content you should put in that file itself.

**Comment by zoufishanmehdi** [comment]
Oh, didn't realize this is a terminal command. I'm getting this error when I run `apollo-codegen download-schema http://localhost:8080/graphql --output schema.json` in the terminal: `error: Cannot find GraphQL schema file: http://localhost:8080/graphql`

Does this mean schema.json needs to be setup on the backend?

**Comment by martijnwalraven** [comment]
You need to be running your GraphQL server, and the `download-schema` command will perform an introspection query to get the schema.
