### ISSUE TITLE
Cannot find type 'graphQLSchema' in scope. 

### ISSUE THREAD

**Issue by iAmericanBoy** [apollographql/apollo-ios#2705]
## Bug report

I followed the new migration guide coming with 1.0.6 and it helped me finally generate all the correct files for our queries and mutations. Thank you for the detailed guide! 

However after dragging the swift package into our Xcode I'm running into some circular dependencies and Xcode errors around not being able to find the schema package in the source files. Are there plans to add more documentation of how to use the new Package integration? 

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.5
- Xcode version: 14.1
- Swift version: 5
- Package manager: SPM

## Steps to reproduce

generate code with this configuration file. and dragged the package into our Xcode project
```json
{
  "schemaName" : "graphQLSchema",
  "input" : {
    "operationSearchPaths" : [
      ".../Apollo/**/*.graphql"
    ],
    "schemaSearchPaths" : [
      ".../ios/graphQLSchema.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : ".../Apollo/GraphQLSchema",
      "moduleType" : {
        "swiftPackageManager" : {
        }
      }
    },
    "operations" : {
      "inSchemaModule" : {
      }
    }
  }
}
```
## Further details
Here is the error we are seeing in the generated files: 
<img width="799" alt="Screenshot 2022-12-07 at 9 58 50 AM" src="https://user-images.githubusercontent.com/32912858/206213168-6afffd09-c858-493d-b2d3-a508e84609d1.png">

**Comment by calvincestari** [comment]
Hi @iAmericanBoy - this looks like a casing problem. The correct casing of the schema namespace is shown on line 19 in that screenshot. I believe if you were to capitalize it to `GraphQLSchema` it would build as expected. Why it's not capitalized is the real question?!

Are you able to replicate this behaviour in a sample project? Is `ApolloBorrowDisclosure` a fragment?

**Comment by calvincestari** [comment]
Can you also confirm whether this bug occurs even after deleting all previously generated files and regenerating using the latest version?

**Comment by iAmericanBoy** [comment]
Correct `ApolloBorrowDisclosure` is one of our fragments. I was seeing the same error message in many files though. 

`"path" : ".../Apollo/GraphQLSchema"` I capitalized it here since that is a folder path but our schema is a file so it's lowercase. Correct all the old files are deleted. I have not checked if this happens in a sample project

**Comment by calvincestari** [comment]
> Correct ApolloBorrowDisclosure is one of our fragments.

OK, I can try replicate this error using fragments, I was not able to earlier with just a very simple test schema.

> "path" : ".../Apollo/GraphQLSchema" I capitalized it here since that is a folder path but our schema is a file so it's lowercase. Correct all the old files are deleted.

No, I wasn't clear enough earlier with my message "if you were to capitalize it to GraphQLSchema it would build as expected". I meant on line 6 where you're getting the compilation error; if that were capitalized it should build as expected. It shouldn't matter what your schema file is named, rather the schema name you use in the codegen configuration and there is logic to always capitalize that so I'm confused why it's being generated with the first character lowercased here.

**Comment by iAmericanBoy** [comment]
your right if I change the schema name to this in the configuration json it builds correctly. 
`  "schemaName" : "GraphQLSchema",`

**Comment by calvincestari** [comment]
Oh that's weird, but it points to a place where I suspect the schema name is not being capitalized correctly - thanks!

**Comment by calvincestari** [comment]
@iAmericanBoy I've got a fix up for this in PR https://github.com/apollographql/apollo-ios/pull/2730. It'll get merged to `main` soon and be generally available in the next release. Thanks for the help narrowing down on the issue.

**Comment by iAmericanBoy** [comment]
Thank you for that quick fix!
