### ISSUE TITLE
Code Gen - Add support for custom SPM package paths

### ISSUE THREAD

**Issue by PatrickDanino** [apollographql/apollo-ios#2709]
## Feature request

The current code generator allows you to specify an SPM output, but does not currently let you configure that package. Due to legal requirements, we cannot take a dependency on an external package that potentially gets downloaded every time we build. 

## Motivation

Rather than depend on an external URL, we instead clone packages locally and use those instead.

## Proposed solution

An optional input to `ModuleType.swiftPackageManager` which would allow us to customize the package file that gets generated.

**Comment by calvincestari** [comment]
Thanks for the suggestion @PatrickDanino - @AnthonyMDev and I have spoken about building a way for projects to have a custom pass over all generated output before being written to files. There's quite a few other use cases for that too but it's not work that we've scoped for any particular milestone yet.

**Comment by calvincestari** [comment]
A temporary workaround is to manually configure the Swift package in combination with an output module of `.other` which will them just place the files in the expected location but not create the Swift package for you. This means you're free to construct the `Package.swift` file in any way you need without having it overwritten by the next execution of code generation.

**Comment by AnthonyMDev** [comment]
What @calvincestari has said is accurate. Using `.other` you can create your own `Package.swift` file, and I think that's the best bet for your use case!

> Due to legal requirements, we cannot take a dependency on an external package that potentially gets downloaded every time we build.
>
> Rather than depend on an external URL, we instead clone packages locally and use those instead.

Unrelated to your Apollo usage, you may want to look into creating a private [swift package registry](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md).
