### ISSUE TITLE
Naming collision with DocumentType in generated mock code

### ISSUE THREAD

**Issue by dafurman** [apollographql/apollo-ios#2719]
## Bug report

This is similar to https://github.com/apollographql/apollo-ios/issues/2708 but it only concerns mocks, so it seemed worth treating as a separate issue.

I have a enum type `DocumentType` that conflicts with `ApolloAPI.DocumentType` in generated mock code.
Would it be possible to prefix generated types in mocks with the schemaName they're living in to resolve ambiguity?

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.5
- Xcode version: 14.1
- Swift version: 5.7
- Package manager: Swift Package Manager

## Steps to reproduce

To reproduce this you will have to use a scheme that defines `DocumentType` as an enum type.

## Further details

![Screen Shot 2022-12-09 at 6 02 50 PM](https://user-images.githubusercontent.com/10556242/206823409-761d4b52-15fd-4ab5-86f2-ca697f2aa5dc.png)

https://github.com/apollographql/apollo-ios/pull/2679 seemed to fix this issue for the main generated code, but I'm still experiencing this issue for generated mocks.
If I manually specify the type as coming from my generated package - `GQLTypes`, I can get the mocks compiling successfully:
```swift
public struct MockFields {
    @Field<GraphQLEnum<GQLTypes.DocumentType>>("documentType") public var documentType
}
```

**Comment by calvincestari** [comment]
Thanks for creating the issue @dafurman. @AnthonyMDev and I are working on resolving these type name conflicts once and for all. We'll get these resolved.

**Comment by calvincestari** [comment]
@dafurman, apologies for the delay in this issue but it is now fixed, merged and will go out in the next release.
