### ISSUE TITLE
__unknown case not generated for enums

### ISSUE THREAD

**Issue by rebekkaorth** [apollographql/apollo-ios#2731]
### Summary

When generating an `Enum` the `__unknown`-case is not generated with the enum 

Sample schema

```JSON
{
        "kind": "ENUM",
        "name": "EnumName",
        "description": null,
        "fields": null,
        "inputFields": null,
        "interfaces": null,
        "enumValues": [
          {
            "name": "Case_Name_1",
            "description": null,
            "isDeprecated": false,
            "deprecationReason": null
          },
          {
            "name": "Case_Name_2",
            "description": null,
            "isDeprecated": false,
            "deprecationReason": null
          }
   ]
} 
``` 

Sample generated enum
```Swift
public extension SchemaName {
  enum EnumName: String, EnumType {
    case caseName1 = "Case_Name_1"
    case caseName2 = "Case_Name_2"
  }
}
```

### Version

1.0.5

### Steps to reproduce the behavior

- Add enum type to schema
- generate files
- check resulting enum

### Anything else?

Documentation mentioning `__unknown` case: https://www.apollographql.com/docs/ios/api/ApolloAPI/enums/GraphQLEnum/#__unknown_

**Comment by tahirmt** [comment]
It conforms to `EnumType` and `GraphQLEnum<EnumName>` should be the type that shows up wherever you use it and `unknown` is a case of `GraphQLEnum` not your enum with Apollo 1.0. At least that's what I've noticed.

**Comment by AnthonyMDev** [comment]
@tahirmt is correct, this is intended behavior and not a but. Your enums are not generated with `__unknown` case in 1.0, rather your generated models will expose them wrapped in a generic `GraphQLEnum` that has the `__unknown` case.

If this is causing usage problems for you in some way, please let us know what problem you are facing and we can address fixing that! Thanks!
