### ISSUE TITLE
Can we prevent SchemaConfiguration from getting overwritten?

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#2735]
### Question

Whenever I run codegen it overwrites the `SchemaConfiguration.swift` file returning `nil` for `cacheKeyInfo` function. Is there any way I can prevent that from happening? I want it to retain the implementation across code-gens

**Comment by AnthonyMDev** [comment]
The codegen engine was written with the intention that the `SchemaConfiguration` file is never overwritten, so this should not be happening. And we haven't had any reports of this problem yet, so I'm guessing this is a bug caused by some edge case in your configuration.

I'd love to see a reproduction case for this, but if you can't provide a full example project, a copy of your codegen configuration file would be helpful for starters!

**Comment by tahirmt** [comment]
@AnthonyMDev I'm using the `ApolloCodegenLib` and have a command line tool instead of using the configuration file it looks something like this.

```swift
let config = ApolloCodegenConfiguration(
            schemaName: schemaName,
            input: .init(schemaPath: schemaPath, operationSearchPaths: [graphqlFilesPath]),
            output: ApolloCodegenConfiguration.FileOutput(
                schemaTypes: .init(
                    path: outputFilePath,
                    moduleType: .other
                ),
                operations: .inSchemaModule,
                testMocks: mockOutputFilePath,
                operationIdentifiersPath: manifestPath
            ),
            options: ApolloCodegenConfiguration.OutputOptions(
                deprecatedEnumCases: .include,
                apqs: .automaticallyPersist,
                cocoapodsCompatibleImportStatements: true
            ),
            schemaDownloadConfiguration: ApolloSchemaDownloadConfiguration(
                using: .introspection(endpointURL: endpointURL),
                headers: headers,
                outputPath: folderForDownloadedSchema
            )
        )
```

**Comment by tahirmt** [comment]
Oh I'm sorry for this. Looks like someone had a delete code before calling out to the command line tool to run codegen. This is not an issue.
