### ISSUE TITLE
Running ./apollo-ios-cli init get error

### ISSUE THREAD

**Issue by Santiago0412** [apollographql/apollo-ios#2736]
### Summary

try to run init before Codegen, but get an error: 
_zsh: number expected_
here is what I run:
./apollo-ios-cli init --schema-name 'MyProject' --module-type embeddedInTarget(name:'MyProject')

### Version

1.0.0

### Steps to reproduce the behavior

run this after install the Apollo CLI 
> ./apollo-ios-cli init --schema-name 'MyProject' --module-type embeddedInTarget(name:'MyProject')
get error:
zsh: number expected

**Comment by calvincestari** [comment]
You need to use the command as it is [documented](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#initialize) - `apollo-ios-cli init [--schema-name <schema name>] [--module-type <module type>] [--target-name <target name>]`

```
./apollo-ios-cli init --schema-name 'MyProject' --module-type embeddedInTarget --target-name `MyProject`
```
