### ISSUE TITLE
Add casing strategies for property names

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2738]
### Use case

I created a new issue for this feature request since we closed #2641.

The gist is to provide casing strategies for other parts of generated code, such as fields, similar to the current option for enums.

**Comment by emily-discz** [comment]
Are there any updates on this issue? Our team is waiting for this to be in before we update our pod

**Comment by calvincestari** [comment]
No updates @emily-discz. It's also not scheduled for any particular minor release yet, just in the list of future minor releases. We're always willing to accept PRs that help get the work done.

**Comment by iDylanK** [comment]
Any updates on this?

**Comment by BobaFetters** [comment]
@iDylanK No more new updates since @calvincestari comment on May 31, still not currently scheduled into any particular minor release.

**Comment by iDylanK** [comment]
Same for our company.

**Comment by moonzhao** [comment]
also needed from my company

**Comment by BobaFetters** [comment]
This is now available in the 1.4.0 release
