### ISSUE TITLE
How to add the generated code to the project?

### ISSUE THREAD

**Issue by vinamelody** [apollographql/apollo-ios#2742]
### Question

Hi, I'm confused when following the documentation guide.
https://www.apollographql.com/docs/ios/tutorial/codegen-getting-started

> Create a new directory to work in
Which path? from the Xcode root project?

Once the files are generated, I have this project structure. How do you add it to Xcode the right way? I tried adding the folder but Xcode can't find the class that I want to use `GetScheduleSubscription`
Here's my code https://github.com/vinamelody/rocket

<img width="1037" alt="Screenshot 2022-12-20 at 10 23 02 AM" src="https://user-images.githubusercontent.com/990511/208567000-626dcb99-297b-4dc4-8f37-9eefc2a6f92d.png">

**Comment by calvincestari** [comment]
Hi @vinamelody 👋🏻 

> Create a new directory to work in
> Which path? from the Xcode root project?

It _can_ be anywhere on your computer but it makes the most sense to place it somewhere in the project path so the project is grouped together by the root folder.

> Once the files are generated, I have this project structure. How do you add it to Xcode the right way? I tried adding the folder but Xcode can't find the class that I want to use `GetScheduleSubscription`.

Your configuration is set up to generate a Swift package, so you must add the generated package in the same way that you added Apollo iOS as a dependency to your project except this time it is a _local_ package. Once you've added the dependency you will then need to link the library to your application target.

**Comment by calvincestari** [comment]
I'm going to close this issue but we can continue the discussion to get you started on your project.

**Comment by vinamelody** [comment]
Hi @calvincestari thanks for the pointer. I've added a local package to the main target but Xcode is still throwing an error: can't find `GetScheduleSubscription`

<img width="1512" alt="Screenshot 2022-12-20 at 1 58 17 PM" src="https://user-images.githubusercontent.com/990511/208594755-5ab516d5-e87e-4dc8-b061-209b2b3e32d8.png">

**Comment by calvincestari** [comment]
Hmm, when it's added as a package it should get the box icon like the Package Dependencies at the bottom. Right now it looks like it's just another folder. I'd try remove that and re-add.

**Comment by vinamelody** [comment]
hmm.. weird i tried many times still the same @calvincestari something amiss. is this step described in the tutorial?

**Comment by vinamelody** [comment]
Hi @calvincestari I downgraded to Xcode 14.0 and the package is imported correctly. I used Xcode 14.2  for the screenshot above.

But I have a new error for the subscription, do you have any idea on where to look at? code is updated at https://github.com/vinamelody/rocket :)

```
"websocket is disconnected: WSError(type: ApolloWebSocket.WebSocket.WSError.ErrorType.upgradeError, message: \"Invalid HTTP upgrade\", code: 308)"
```
![Screenshot 2022-12-20 at 11 22 56 PM](https://user-images.githubusercontent.com/990511/208705235-0f8339b7-3980-49a6-9165-a1c9a200bdf8.png)

**Comment by calvincestari** [comment]
> I downgraded to Xcode 14.0 and the package is imported correctly. I used Xcode 14.2 for the screenshot above.

Xcode version shouldn't matter; I use 14.2 myself.

> But I have a new error for the subscription, do you have any idea on where to look at?

You need to be using the `wss` protocol; that server wants it to be a secure websocket connection. Change your websocket endpoint to `"wss://api.iosconf.sg/v1/graphql"` and it should work.

**Comment by vinamelody** [comment]
@calvincestari whoa you're right! wss works! i've very sure previously on Heroku's Hasura + apollo ios < 1.0.0, wss didn't work. my heroku instance got deleted and i moved to digitalocean. i guess now it must be wss!

For some reason, I added the app as a package in Xcode 14.0 and then once it works, I use 14.2 to continue the development.

**Comment by calvincestari** [comment]
I haven't tested it fully myself but I suspect there is a difference in 14.2 with it automatically linking libraries. Maybe it's a bug in 14.2 or just new behaviour, I don't know.
