### ISSUE TITLE
Undefined Symbol error

### ISSUE THREAD

**Issue by Rohan-diy** [apollographql/apollo-ios#2743]
### Summary

Getting the following errors when I run the app:
<img width="307" alt="Screenshot 2022-12-20 at 4 54 25 PM" src="https://user-images.githubusercontent.com/111349956/208655995-ebfe0e3c-8dcd-47af-b4d0-3a1a35231678.png">

Xcode version: 14.2
apollo-ios -> 1.0.0 - Next Major

### Version

1.0.0 - Next Major

### Steps to reproduce the behavior

Build the app

**Comment by calvincestari** [comment]
Hi @Rohan-diy 👋🏻 

This looks like a linking error. You'll have to share more about how you're trying to use the generated code; SPM, CocoaPods, etc.

I would check that you've correctly added the generated files, or package, to your project and then linked the library with your application target.

**Comment by Rohan-diy** [comment]
Hi @calvincestari, I have used SPM for the apollo-ios library. I generated the code using the `embedintarget` type. I manually added the generated code to the target folder.

**Comment by calvincestari** [comment]
I can only reproduce this error when the libraries are not correctly linked with the application target. Check that your target is linking to both the `Apollo` and `ApolloAPI` libraries.

<img width="707" alt="Screen Shot 2022-12-21 at 12 21 06 AM" src="https://user-images.githubusercontent.com/146856/208855404-d5e701b8-ee9c-46c9-9603-6914f034521f.png">

**Comment by Rohan-diy** [comment]
I tried pod, but still the same error. I am following the [Getting Started guide](https://www.apollographql.com/docs/ios/get-started/)

**Comment by Rohan-diy** [comment]
And I checked target, Apollo and Apollo API are added 
<img width="553" alt="Screenshot 2022-12-21 at 6 56 49 PM" src="https://user-images.githubusercontent.com/111349956/208916835-6f5c1527-1523-4798-9ced-413c51d314b8.png">

**Comment by calvincestari** [comment]
Is this a production app or test/learning example? If you're able to share it with me I could take a look and work out what the problem is.

**Comment by Rohan-diy** [comment]
It's a production app. Unfortunately I won't be able to share the codebase. I tried pod also and manually added the apollo and apollo api packages to the targets, but still it won't work

**Comment by calvincestari** [comment]
OK. I think it's definitely a linking error but I don't know what else to suggest other than to re-check all the linking related build settings. If you're able to reproduce the build error in a standalone sample app I could take a look at that instead?

**Comment by AnthonyMDev** [comment]
@Rohan-diy have you been able to resolve or reproduce this issue in another project yet?

**Comment by bignimbus** [comment]
Closed due to inactivity
