### ISSUE TITLE
How to rename type name when codegen is executed without changing schema.

### ISSUE THREAD

**Issue by zzdravkin** [apollographql/apollo-ios#2746]
### Question

I have type in schema Any, and when running "apollo-ios-cli generate".

1. Typealias Any is created
2. I've renamed that because conflict with swift foundation type Any
3. autogenerated files still using Any
4. I need to change Any to my custom typealias ( step 2)  everytime I run "apollo-ios-cli generate"

Is there a way I can specified typename mapping when "apollo-ios-cli generate" is run?

Thank's

**Comment by munakata-hisashi** [comment]
The generated code uses the schemaName in apollo-codegen-configuration.json as namespace, so I think there is no need to rename it.

What code is being generated?

**Comment by zzdravkin** [comment]
scalar type is Any, and when auto code is generated is using Any as well in swift which is the type used by the Foundation framework, I found a workaround by the running script to change the name in schema.json file
