### ISSUE TITLE
ApolloCodegenLib - No such module 'OrderedCollections'

### ISSUE THREAD

**Issue by lkitllab** [apollographql/apollo-ios#2748]
### Question

I've added Apollo via SPM to a new clean project with ApolloCodegenLib. When I try to build a project I got error -  No such module 'OrderedCollections (ApolloCodegen.swift). This is really strange because swift-collections package is added automatically.

Apollo 1.0.5, Xcode 14.2

How to fix this issue? 

Tnanks!

**Comment by calvincestari** [comment]
Is your project for iOS? ApolloCodegenLib is macOS only.

**Comment by lkitllab** [comment]
I've tried both of them, still the same error.

**Comment by calvincestari** [comment]
If you can provide a sample macOS project that replicates the error we can take a look. I've only managed to reproduce the error in an iOS project, which is expected and not a bug.

**Comment by lkitllab** [comment]
https://github.com/lkitllab/ApolloTest.git

**Comment by calvincestari** [comment]
Remove `apollo-ios-cli` from the linked Frameworks, Libraries, and Embedded Content and your project will build. It's a [distributed executable target](https://github.com/apollographql/apollo-ios/blob/main/Package.swift#L22), I don't know why Xcode lets a project link to it - I consider it an Xcode bug.

**Comment by lkitllab** [comment]
Great! Thanks
