### ISSUE TITLE
errors in generated files after integrating apollo using cocoapods.

### ISSUE THREAD

**Issue by arsh94deep** [apollographql/apollo-ios#2750]
### Summary

I integrated apollo iOS using cocoapods
I then generated the codegen files and imported them in my project directory and are facing multiple issues.
not able to compile the project.
Please help.
<img width="1624" alt="Screenshot 2023-01-04 at 2 26 44 PM" src="https://user-images.githubusercontent.com/23209353/210519131-77ae5387-d1eb-47ee-8fac-ffcebd7184fa.png">

### Version

1.0.5

### Steps to reproduce the behavior

i am using these latest docs from apollo
https://www.apollographql.com/docs/ios/get-started

I integrated apollo iOS using cocoapods

i downloaded the schema file and dropped it in my project directory (.graphqls)

I have created a Queries.graphql file with a simple Query.

I created a config file from terminal using the command -> ./Pods/Apollo/apollo-ios-cli init --schema-name EquilibertySchema.graphqls --module-type embeddedInTarget --target-name Equiliberty

I then generated the codegen files and imported them in my project directory and are facing multiple issues.

not able to compile the project.

Please help.
<img width="1624" alt="Screenshot 2023-01-04 at 2 07 08 PM" src="https://user-images.githubusercontent.com/23209353/210519245-59a60ebd-ce74-4f12-9499-3cd3381793ea.png">

### Anything else?

the docs that i am following

https://www.apollographql.com/docs/ios/get-started

**Comment by calvincestari** [comment]
Hi @arsh94deep - 👋🏻 

> I created a config file from terminal using the command -> ./Pods/Apollo/apollo-ios-cli init --schema-name EquilibertySchema.graphqls --module-type embeddedInTarget --target-name Equiliberty

It looks like you're using the schema filename for `--schema-name`, it should be the _namespace_ you want to use for your GraphQL schema. From the [documentation](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#options-1):
> The name you would like to be used as the namespace for your generated schema files.

Change that to something like `EquilibertySchema`, re-run code generation and it should all build correctly.

**Comment by arsh94deep** [comment]
Hi @calvincestari ,
thanx for your reply.
But now that I have changed the name still I can't call the Query Object created from my written query.

i have changed the name of the schema to - AppSchema.
<img width="1624" alt="Screenshot 2023-01-06 at 10 01 29 AM" src
<img width="1624" alt="Screenshot 2023-01-06 at 10 04 02 AM" src="https://user-images.githubusercontent.com/23209353/210930733-f4094d68-094c-47d6-bc14-6e82d22b9ca7.png">
="https://user-images.githubusercontent.com/23209353/210930672-da6f86cd-6371-455f-bcea-4bd5b9b792bb.png">
<img width="1624" alt="Screenshot 2023-01-06 at 10 01 15 AM" src="https://user-images.githubusercontent.com/23209353/210930695-9918e837-88a9-4d3e-af4c-cd089678f766.png">

**Comment by calvincestari** [comment]
Looks like you probably need to import the `AppSchema` module into `NetworkProvider` and then it will be in scope.

**Comment by arsh94deep** [comment]
Hi @calvincestari ,
Thanx for helping me out previously.

I have successfully compiled the project but  I want to know how we can add an authorization header in apollo ios v1.0.?
like :-

["Bearer":"sdfiwyegfigh22423ry8932ryirwhejfb98"]

in the header of all the requests.

**Comment by calvincestari** [comment]
@arsh94deep - I [answered](https://github.com/apollographql/apollo-ios/issues/2782#issuecomment-1385828934) in #2782.
