### ISSUE TITLE
Unnamed fields in schema results in broken generated Swift code

### ISSUE THREAD

**Issue by neakor** [apollographql/apollo-ios#2753]
### Summary

In a schema with unnamed fields such as:
```
input MyInput {
  _: Boolean
}
```
the resulting generated code is broken as:
```
__data = InputDict([
  "_": _
])

public var _: GraphQLNullable<Bool> {
  get { __data["_"] }
  set { __data["_"] = newValue }
}
```

### Version

1.0.5

### Steps to reproduce the behavior

1. Create a schema with an unnamed field.
2. Run CLI to generate code.
3. Observe the generated Swift code does not compile.

**Comment by calvincestari** [comment]
Thanks for the bug report @neakor, we'll get this fixed in an upcoming patch release.
