### ISSUE TITLE
Interfaces implemented by schema root are not generated

### ISSUE THREAD

**Issue by litso** [apollographql/apollo-ios#2756]
### Summary

Interfaces that are implemented on the root note of a schema are not generated. Code generation does not produce any errors or warning but the generated code will not compile due to the missing interface.
I tried to produce a minimal schema and example query to illustrate the problem below.

The previous (non-swift) code generation tool did not have this issue.

### Version

1.0.5

### Steps to reproduce the behavior

Consider the following schema

```graphql
interface MissingInterface {
  missingInterfaceString: String!
}

type Query implements MissingInterface {
  missingInterfaceString: String!
}
```

We have a one simple query defined in our project:
```graphql
query fetchMyString {
  missingInterfaceString
}
```

After building and running the code generation tool for release `1.0.5` the generated query looks correct but in our Query type we are referencing an interface that was never generated causing a compilation error:

```swift
// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  static let Query = Object(
    typename: "Query",
    implementedInterfaces: [Interfaces.MissingInterface.self] // <--- Compilation error since MissingInterface not generated
  )
}
```

**Comment by AnthonyMDev** [comment]
Hahah, what a cool bug! This should be an easy fix. Thanks for reporting it!

This is likely due some bug causing the JS frontend not collecting interfaces implemented by root types into the `referencedTypes`!

**Comment by calvincestari** [comment]
Hi @litso - this is fixed and will go out in the next patch release, `1.0.7`.
