### ISSUE TITLE
Error on generate code

### ISSUE THREAD

**Issue by EdzonBolivar11** [apollographql/apollo-ios#2758]
### Question

I have a couple days trying to integrate apollo in ios project, I'm using "SPM with Xcode project" but when I tried to use "./apollo-ios-cli generate" its saying this 
<img width="714" alt="Screenshot 2023-01-07 at 12 29 32" src="https://user-images.githubusercontent.com/51150676/211165361-65cd889b-4902-4641-9c19-6948aa711b79.png">
I already move several times the file and did different things, really I don't know what I'm doing wrong.

**Comment by calvincestari** [comment]
Hi @EdzonBolivar11 - 👋

The error is that the code generation engine cannot find your schema file. What do you have in the schema search path in your config file and what is the name of your file?

**Comment by EdzonBolivar11** [comment]
Hi  @calvincestari 

I have my files like this
 
<img width="280" alt="Screenshot 2023-01-07 at 12 52 32" src="https://user-images.githubusercontent.com/51150676/211166159-34537d58-86d4-4983-8d79-d4c9721ba82f.png">

<img width="529" alt="Screenshot 2023-01-07 at 12 53 10" src="https://user-images.githubusercontent.com/51150676/211166186-21abc68d-c835-4846-a357-ec526062ade2.png">

Is the answer to your question?

**Comment by calvincestari** [comment]
In your config file you have the schema search path looking for files with the graphqls extension but you have a json extension file. That's why it's not finding anything.

Change schemaSearchPath to "**\*.json" and it will find your schema file.

**Comment by EdzonBolivar11** [comment]
ohh nice, that worked but know I have this

<img width="1370" alt="Screenshot 2023-01-07 at 13 05 58" src="https://user-images.githubusercontent.com/51150676/211166603-b2f8990d-834e-48c4-b602-de9373df0f87.png">

**Comment by EdzonBolivar11** [comment]
Mmm I did it but now is taking Contents.json

<img width="1109" alt="Screenshot 2023-01-07 at 14 14 53" src="https://user-images.githubusercontent.com/51150676/211168813-cda0fb8f-d52f-4414-8c99-2c050b1ab486.png">

<img width="717" alt="Screenshot 2023-01-07 at 14 15 27" src="https://user-images.githubusercontent.com/51150676/211168829-12148b18-45bc-4b60-99f9-4ca00174d736.png">

<img width="300" alt="Screenshot 2023-01-07 at 14 15 47" src="https://user-images.githubusercontent.com/51150676/211168839-a922aa2a-1600-4cac-8c00-a7402b222973.png">

**Comment by calvincestari** [comment]
Because you haven't narrowed the search path. Try "ApolloTest/API/schema.json", get rid of the ** wildcard paths.

**Comment by EdzonBolivar11** [comment]
Its doing the same 
<img width="1212" alt="Screenshot 2023-01-07 at 14 22 57" src="https://user-images.githubusercontent.com/51150676/211169076-02691fda-5883-4aae-9754-52ca223754d0.png">
<img width="415" alt="Screenshot 2023-01-07 at 14 23 07" src="https://user-images.githubusercontent.com/51150676/211169080-9908952e-853a-44e6-a554-b0fb86246236.png">

**Comment by EdzonBolivar11** [comment]
Its doing the same
<img width="1208" alt="Screenshot 2023-01-07 at 14 24 35" src="https://user-images.githubusercontent.com/51150676/211169123-b5478f52-3455-4a20-b1cb-03ed37ef838a.png">


<img width="512" alt="Screenshot 2023-01-07 at 14 24 38" src="https://user-images.githubusercontent.com/51150676/211169119-fd0bd2f3-0010-4f06-90c6-7ddb171ed0e0.png">

**Comment by calvincestari** [comment]
Did you move the file? If so then put it back where it was. schemaSearchPath is what you need to change. In that last screenshot it still has the ** wildcard path.

That path is you telling the engine where to find the schema json file. It's finding too many because the wildcard search is too broad, narrow that down and it'll get past this error.

**Comment by EdzonBolivar11** [comment]
Do you mean like this?

<img width="526" alt="Screenshot 2023-01-07 at 14 50 57" src="https://user-images.githubusercontent.com/51150676/211169842-7a6739fa-c812-46a8-8054-982e0cdcaba2.png">

This is the structure is the same and the last structure image

**Comment by calvincestari** [comment]
Put the file back into this location:
<img width="300" alt="211168839-a922aa2a-1600-4cac-8c00-a7402b222973" src="https://user-images.githubusercontent.com/146856/211172165-54f59489-d85a-4ca4-8625-03b1b619d3bf.png">

.and use 
```
"schemaSearchPaths" : [
  "ApolloAPI/API/schema.json"
]
```

**Comment by EdzonBolivar11** [comment]
Now I have this. With same structure file and folders
<img width="659" alt="Screenshot 2023-01-07 at 16 24 03" src="https://user-images.githubusercontent.com/51150676/211172508-7af8cdfb-5bdd-444b-8d37-f017050521f3.png">
<img width="400" alt="Screenshot 2023-01-07 at 16 24 28" src="https://user-images.githubusercontent.com/51150676/211172517-7d729966-a8b4-4838-9cd3-4734cc071353.png">

**Comment by calvincestari** [comment]
```
"schemaTypes" : {
  "path": "ApolloTest/API/schema.json",
```
This is incorrect. That is an output path for the schema types module; it cannot be the name of your input schema json file. Use something like `"path" : "ApolloTest/Generated/"`.

The [codegen configuration](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration) documentation explains what all the fields are for, you need to take the time to read it and understand what each is for.

**Comment by EdzonBolivar11** [comment]
It works now

Thank you so much
