### ISSUE TITLE
Subscript GraphQL variable from dictionary crash when Swift modifier used as key.

### ISSUE THREAD

**Issue by SzymonMatysik** [apollographql/apollo-ios#2759]
### Summary

Hey there, great thanks for hard work put into new release!

Recently I've started to migrate from 0.53 to 1.0.5 and have to say - it's not a very easy task to achieve. Now I've stomped on issue that nobody else mentioned before (based on my research). 

Everything was working fine before the migration - I think it's issue related to the codegen feature.
When I got in schema variable in fragment named after Swift's special words `default`, `public`, `private` or else then in generated code it's ` __data["'public'"] }` (apostrophes on each side to escape the special word)
It leads to a problem in getting the value resulting a crash as in subscript.
part of generated file:
```
    public var `public`: GraphQLNullable<Bool> {
      get { __data["`public`"] }
      set { __data["`public`"] = newValue }
    }
```

Maybe we should stripe the apostrophes which are clearly from the Swift requirements not from a schema.

### Version

1.0.5

### Steps to reproduce the behavior

- Make schema with variable in any model named after Swift's special word for example `public: Bool`.
- Generate schema.
- Check string representation of variable in Swift generated file.

### Logs
```
Could not cast value of type 'Swift.Optional<ApolloAPI.GraphQLOperationVariableValue>' (0x15460b190) to 'ApolloAPI.GraphQLNullable<Swift.Bool>' (0x1510a3608).
(lldb) 
```

### Anything else?
As a workaround I've applied direct dictionary lookup for `public` field as follows:
```let lhsPublic: GraphQLNullable<Bool> = lhs.__data["public"]```

**Comment by calvincestari** [comment]
Thanks for the bug report @SzymonMatysik. We'll get this fixed in a patch release; we're planning on releasing `1.0.6` today and `1.0.7` by the end of the week. It'll be in one of those.

**Comment by calvincestari** [comment]
Note that this bug is only apparent on input types, selection sets do not have this issue.

**Comment by calvincestari** [comment]
Adding this to "planned-next" because fixing #2753 will need this to be fixed too before it's all functional.

**Comment by calvincestari** [comment]
@SzymonMatysik this is fixed, available on `main`, and will go out in the next patch release.
