### ISSUE TITLE
Changelog isn't updated

### ISSUE THREAD

**Issue by lilyball** [apollographql/apollo-ios#276]
The CHANGELOG.md file lists v0.6.0 as the latest version, and the releases don't have descriptions, so there appears to be no documentation as to what changed e.g. from 0.7.0 to 0.8.0.

**Comment by kballard** [comment]
Any chance of getting this done? We're looking to upgrade to 0.8.0 (from 0.7.0) and right now we have very little idea as to what the actual changes are, or if there are any backwards-incompatible changes.

**Comment by lilyball** [comment]
At this point the changelog lists 0.9.4 as the latest release, but there's been 3 releases since then.

**Comment by designatednerd** [comment]
This is now up to date with changes for 0.9.5, 0.10.0, and 0.10.1. Please feel free to tag me on a new bug if I forget to do this for the next release 🙃
