### ISSUE TITLE
Apollo SDK integrated through SPM emits documentation reference warnings for comments

### ISSUE THREAD

**Issue by mthormann-dhi** [apollographql/apollo-ios#2766]
### Summary

When integrating Apollo 1.0.5+ (1.0.6 has same issue) as a Swift Package, there are some topic references that are causing warnings in Xcode 14. Two copies of each of these warnings are emitted with each build and are preventing us from achieving a clean build, turning on warnings as errors, etc. Because the source is integrated through SPM, options are limited for suppressing the warnings.

<path>/SourcePackages/checkouts/apollo-ios/Sources/ApolloAPI/InputValue.swift:13:7 Topic reference 'GraphQLOperation/variables-swift.property-4o32c' couldn't be resolved. No local documentation matches this reference.

<path>/SourcePackages/checkouts/apollo-ios/Sources/ApolloAPI/JSONDecodingError.swift:5:40 Topic reference 'JSONDecodable/init(jsonValue:)' couldn't be resolved. No local documentation matches this reference.

### Version

1.0.6

### Steps to reproduce the behavior

- Create an Xcode project
- Integrate Apollo iOS latest as a Swift Package
- Build

Expected: No warnings
Actual: 4 warnings from the 2 files above (InputValue.swift and JSONDecodingError.swift

### Anything else?

<img width="891" alt="Screenshot 2023-01-10 at 2 00 19 PM" src="https://user-images.githubusercontent.com/12616327/211638555-696a9753-ffe0-41fc-a5c5-c02947d4c3b6.png">
<img width="980" alt="Screenshot 2023-01-10 at 2 00 09 PM" src="https://user-images.githubusercontent.com/12616327/211638566-f5241fdc-488a-4251-ac81-ba64b34f2c5b.png">

**Comment by AnthonyMDev** [comment]
That is quite annoying. We can get this fixed in 1.0.7 for sure. @calvincestari, we are going to need to find a way to add a check for this to CI...

**Comment by calvincestari** [comment]
@mthormann-dhi this warning is not output when building for running, testing or profiling right? It's specifically from the "Build Documentation" command - is that linked with your other build steps, i.e.: are you getting this error each time you build?

**Comment by mthormann-dhi** [comment]
@calvincestari It was happening every time I ran, tested, etc. but I found the problem. We had a stray 'Build Documentation' setting to yes in Build Settings .

`RUN_DOCUMENTATION_COMPILER = YES`

Problem is resolved now. Also removed the .docc from Compile Sources as well as it had somehow popped in there. Thx for looking at this!

**Comment by calvincestari** [comment]
That's great news. I'll still go ahead with #2787 to fix the broken links but thanks for following up and letting me know you're past the blocker.
