### ISSUE TITLE
Provide a way to specify Swift Package platforms

### ISSUE THREAD

**Issue by jarrodrobins** [apollographql/apollo-ios#2774]
### Use case

In Apollo 1.0.6, every time I run code generation my `Package.swift` file is rebuilt. This changes the `platforms` parameter to

```
platforms: [
    .iOS(.v12),
    .macOS(.v10_14),
    .tvOS(.v12),
    .watchOS(.v5),
],
```

which is not ideal, as I wish to keep it as the following
```
platforms: [
    .iOS(.v15)
],
```

iOS 12 is ancient and I am using newer methods, and also don't support the other OSes.

### Describe the solution you'd like

Either code generation could simply not overwrite this value each time after initialisation, or allow this to be specified in the `apollo-codegen-config.json` file. 

One possible solution could be something like - 
```
"moduleType" : {
    "swiftPackageManager" : {
        "platforms": [
             {
                 "platform": "iOS",
                 "version": "15.0"
             }
        ]
    }
}

**Comment by calvincestari** [comment]
Thanks @jarrodrobins. Not having this from the start was a miss on our part, we certainly understand the frustration of having this file overwritten after making necessary changes to it. We'll get this included in one of the upcoming versions.

**Comment by calvincestari** [comment]
Hey @jarrodrobins - @AnthonyMDev and I spoke about this earlier today and came to the conclusion that it shouldn't matter what the platform definition is for the shared schema package, which this is, but rather your project package definition that uses the shared schema package as a dependency.

How are you using the generated schema package, or adding code to it, that is iOS 15+ only?

**Comment by jarrodrobins** [comment]
Hey @calvincestari, hope I'm understanding what you mean so apologies if I'm speaking gibberish. 

For "project package definition" - re-reading the migration guide I see there's different sections for "SPM with Package.swift" and "SPM with Xcode Project". To clarify, I'm using the latter, not creating my own Swift package which imports the generated package, in case you were referring to the first option.

To detail my particular set up, essentially I have 
- my main app target which imports...
- ... another framework which does all the Apollo related tasks (running queries and mapping those objects to internal domain objects, etc). This is the target that imports the generated package. 

Both the app and framework set the minimum deployment targets as iOS 15 in Xcode.

It's the scalars that we've added to the generated package that are causing the issue. tldr; one of our scalars is `Country` which uses `String(localized: "Unknown", comment: "....")` in it as a placeholder name if a given country code can't be mapped properly, and that method is iOS 15+. 

Honestly the scalar needs to be cleaned up anyway (probably should have a failable initializer instead, or we could simply just go back to `NSLocalizedString`) but I could see this becoming an issue more generally if we're to add our own code via the Scalars to the package in Apollo 1.0+ but don't have a proper way to set the minimum version.

I hope that answers your question.

**Comment by AnthonyMDev** [comment]
Okay, the key here is that its in your custom scalar code. That does make sense. We probably should do something about this soon. In the mean time, if you just change your module type to `.other` instead of `.swiftPackageManager`, it will function the same, but stop generating your `Package.swft` file. You can then manage the `Package.swift` file manually. You'll just need to make sure that you update the version of the dependency Apollo when you upgrade to newer versions in the future.

**Comment by jarrodrobins** [comment]
Ah good to know. Thanks @AnthonyMDev.

**Comment by calvincestari** [comment]
Thanks for the detail on the custom scalars @jarrodrobins, makes sense.

@AnthonyMDev the cache key methods in schema metadata is another place where custom code can be added that we don't overwrite. Should consider both of these in the same solution.

**Comment by calvincestari** [comment]
We're looking into allowing SPM package.swift file edits in a future minor version. You can watch and track that work in https://github.com/apollographql/apollo-ios/issues/2839.
