### ISSUE TITLE
Do fragments have to be orphans?

### ISSUE THREAD

**Issue by SzymonMatysik** [apollographql/apollo-ios#2780]
### Question

Why in apollo every fragment generated is unrelated to the main type? Is it from the concept?

Suppose we have a `model`:
```
User {
   name
   age
   telephone
}
```
and `fragments`:
```
UserInfo on User {
   name
   age
}
UserContact on User {
   name
   telephone
}
```
(Forcibly simplified examples, do not reflect real usage)

In the generated models, each of `UserInfo` and `UserContact` are different types, where we know exactly that they come from one type: `User`

This generates many complications when we want to reuse a given type.
Please give me some insight why It's done like that and if there any workaround to deal with it in elegant way?

**Comment by AnthonyMDev** [comment]
One of the major points of GraphQL is that you only fetch the data you need at any given time, preventing over-fetching. Each generated fragment is only going to fetch (from either the server or the cache) the data that is defined for that fragment. If you want all of the data at once, just define an operation that selects each of the fields that you want (or includes all of the necessary fragments) and you will get one unified generated model with all of your data as well.

Fragments are meant to be just that -- a fragment of the whole model -- but that doesn't prevent you from fetching all the data you want by creating an operation or fragment that includes them all.

It's worth noting, that the data is stored in our [normalized cache](https://www.apollographql.com/docs/ios/caching/introduction) as one shared object across multiple operations/fragments.

---


> This generates many complications when we want to reuse a given type.
> Please give me some insight why It's done like that and if there any workaround to deal with it in elegant way?

It sounds like you want generated types based on your GraphQL schema types, which is fundamentally a different approach to your data. We've thought about this approach a lot (and I do mean A LOT!), but it doesn't make sense with how GraphQL is utilized today. I do hope to provide some sort of way to do this in the future, but it has a lot of its own downsides and roadblocks.

For instance, all of the fields would have to be optional at all times. For your example above, if we generated a shared `User` model, we have no way of knowing if the `UserInfo` and/or `UserContact` fragments will have been fetched when we generate the model. You may get a `User` back after only fetching one fragment or the other. This means that you're going to have all of your fields be optional and have to unwrap them. With operation/fragment based models, we know that if you fetch the `UserContact` fragment, your model is going to be guaranteed to have fetched all fields on that fragment.

This also becomes much more complicated when you start dealing with `interface` and `union` types. What if you had a fragment on type `Animal`, which is an interface. We don't know if the server is going to return you a `Dog`, `Cat`, `Lizard`, or some other type. So what generated model do we give you? It gets even more complicated when you have something like this:
```graphql
fragment AnimalDetails on Animal {
  id
  species
  ... on Dog {
    name
  }
  ... on Bird {
    wingspan
  }
 ... on Cat {
    favoriteFood
  }
```
What should the generated models look like in this situation?

---

We do want to provide a more elegant way of doing something like what you are suggesting in the future, but it's not really how GraphQL was designed to work, and it's going to require a lot of opinionated decisions about the future of GraphQL client usage. Opinions that are likely not going to ever please everyone at once.
