### ISSUE TITLE
Website links are broken

### ISSUE THREAD

**Issue by JoeFerrucci** [apollographql/apollo-ios#2785]
### Summary

https://github.com/apollographql/apollo-ios/blob/a6414da299fb905aee6416876810a8f5a3b0cd1b/docs/source/get-started.mdx

This page has broken links: https://www.apollographql.com/docs/ios/get-started

Broken links are:
1. https://www.apollographql.com/docs/project-configuration
   - This is a crucial decision to make before configuring code generation. To determine the right option for your project, see [Project Configuration](https://www.apollographql.com/docs/project-configuration)
2. https://www.apollographql.com/docs/code-generation/codegen-configuration
    - Alternatively, you can generate your operations into the package that includes your schema files. For more information, see [Code Generation Configuration](https://www.apollographql.com/docs/code-generation/codegen-configuration).

Which are from the [4. Setup and run code generation](https://www.apollographql.com/docs/ios/get-started#4-setup-and-run-code-generation)'s CocoaPods dropdown.

### Version

Website

### Steps to reproduce the behavior

See summary ^

### Anything else?

I believe the links are just missing the `/ios/` path component after `/docs`

**Comment by calvincestari** [comment]
Thanks for raising the issue @JoeFerrucci, we'll get those fixed.

**Comment by calvincestari** [comment]
I think these may be fixed in either #2732 or #2710. @AnthonyMDev and I will be getting those merged soon and then check the links since they reorganize the docs and links.

**Comment by calvincestari** [comment]
This is fixed and the updates have been deployed already.
