### ISSUE TITLE
Restore ability to use SOCKS proxies for debugging

### ISSUE THREAD

**Issue by casey-chow** [apollographql/apollo-ios#2788]
### Use case

I'm trying to debug our web socket usage over the wire, and am mostly unable to use tools like Proxyman or Charles. SOCKS proxying was previously enabled but seems to have been enabled due to a Starscream upgrade (#1104) that was [reverted in 0.47.0](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md#v0470). 

### Describe the solution you'd like

Re-expose the `useSOCKSProxy` variable.

**Comment by calvincestari** [comment]
Hi @casey-chow 👋🏻 - thanks for raising the issue. I was not aware this had dropped in the Starscream changes. It looks like we'll need to reapply https://github.com/apollographql/apollo-ios/pull/1108 to bring this back. I don't have any immediate objection to doing that; @AnthonyMDev can you think of any reason why we shouldn't?

We are scheduled to rebuild the networking stack later in the year which will completely change things and I can't guarantee it for that major version release though.

**Comment by casey-chow** [comment]
The other thing we're looking at would be to set up a WebSocket client based using URLSessionWebSocketTask, which would give us the benefit of using tools like [Atlantis](https://docs.proxyman.io/atlantis/atlantis-for-ios). I'm guessing if the iOS version support range stays intact that's not going to be much of an option though.

**Comment by winstondu** [comment]
> Hi @casey-chow 👋🏻 - thanks for raising the issue. I was not aware this had dropped in the Starscream changes. It looks like we'll need to reapply #1108 to bring this back. I don't have any immediate objection to doing that; @AnthonyMDev can you think of any reason why we shouldn't?

Please let us know!
