### ISSUE TITLE
Package Plugin CLI reinstall fails after build folder is cleaned

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#2789]
### Summary

When you install the CLI using the , a symlink to it is installed into your source folder. This symlink points to a version of the CLI that gets installed in your build folder. When you clean the build folder, the symlink winds up pointing to something that no longer exists. This bit is expected. 

What's **not** expected is that when you then re-run the "Install CLI" plugin, it does not install the CLI if the symlink is still present, even if the symlink is pointing at nothing.  

### Version

1.0.6

### Steps to reproduce the behavior

1. Install CLI with the Swift Package Plugin
2. Validate that it works by running `./apollo-ios-cli help` and seeing the help printed out. 
3. Clean your build folder, which has the side effect of deleting the CLI binary, but not the symlink that was installed for it. 
4. Attempt to run `./apollo-ios-cli help` again, get `no such file or directory: ./apollo-ios-cli` error
5. Try running swift package plugin again
6. Attempt to run `./apollo-ios-cli help` again, still get `no such file or directory: ./apollo-ios-cli` error instead of reinstall succeeding. 

Expected behavior: After step 5, the CLI in the build folder is regenerated and the symlink is updated if necessary to point to the new binary.

**Comment by calvincestari** [comment]
Hey Ellen. Interesting quirk. Thanks for logging the issue, we'll get it fixed up in a patch release.

**Comment by designatednerd** [comment]
OK, after some further testing, this appears to be an issue where my complete lack of chill was biting me: The CLI _was_ being regenerated in the same place the symlink actually pointed to, I just wasn't seeing the build thing spinning up in the wee tiny top bar of Xcode. If I actually wait until the command finishes and the build completes and the wee build monitor stops spinning, then it's good to go. 

So if you're having this issue, wait until the command finishes running to test this.
