### ISSUE TITLE
GraphQLFragment protocol additions

### ISSUE THREAD

**Issue by Lumyk** [apollographql/apollo-ios#279]
Is it possible to add  ```static let fragmentString: String { get }```  to ```GraphQLFragment``` protocol?

**Comment by martijnwalraven** [comment]
The property has been changed to `fragmentDefinition` in the most recent version, but we could definitely expose it. Out of curiosity, what is your use case for this?

**Comment by Lumyk** [comment]
It would be great if you can add ```fragmentDefinition```.
I use it for customizable query based on fragments.

**Comment by martijnwalraven** [comment]
What do you mean by a customizable query based on fragments? How would that map to the generated types?

**Comment by Lumyk** [comment]
I have my own mapper, and use apollo-codegen for generating fragments, then connect my model with generated fragment and can create custom query

```swift
let fragment = MyModel.fragment(params)
let query: GraphQLQuery  = CustomQuery(fragments: [fragment])
```

All that i need from fragments it's  ```fragmentDefinition``` and ```selections```.
```selections``` already in ```GraphQLSelectionSet``` protocol

**Comment by RolandasRazma** [comment]
@Lumyk I added extra step after apollo-codegen (regex replace) on schema file for similar purpose, guess you can do something similar as a workaround.
