### ISSUE TITLE
Getting No such module 'OrderedCollections' inside ApolloCodegen class

### ISSUE THREAD

**Issue by RajendraNayak** [apollographql/apollo-ios#2790]
Hi All

I am trying to use apollo-ios version 1.0.0 in my iOS app for GraphQL.
I am getting Getting **No such module 'OrderedCollections'** inside **ApolloCodegen** class. 
However **Swift Collections** library is already included in the project.

<img width="1530" alt="Screenshot 2023-01-21 at 8 35 42 PM" src="https://user-images.githubusercontent.com/3063882/213873432-24f7cd6f-dad4-41b2-8a4f-d43e69a996b0.png">

<img width="348" alt="Screenshot 2023-01-21 at 8 36 04 PM" src="https://user-images.githubusercontent.com/3063882/213873425-25041919-28ed-4338-832d-e8121543a69b.png">

Here is my apollo-codegen-config.json

<img width="363" alt="Screenshot 2023-01-21 at 8 43 22 PM" src="https://user-images.githubusercontent.com/3063882/213873373-3274b5e4-50b0-4cf4-bf85-44b43811af9a.png">

Please help me. Thanks in Advance

**Comment by calvincestari** [comment]
Hi - you probably have the `apollo-ios-cli` target linked to your project, you don't need it. See https://github.com/apollographql/apollo-ios/issues/2748.

**Comment by RajendraNayak** [comment]
@calvincestari Thank you so much
