### ISSUE TITLE
can i get iOS latest documents for add schema.json file creation process and latest sample code ?

### ISSUE THREAD

**Issue by MohanVMaxIOS** [apollographql/apollo-ios#2799]
### Question

I have tried ios V1.0 documents to create the project with  add the sdk and create schema.json file but getting some errors and warning xcode 14.0.1 .
Step1: Install the Apollo Swift Package by entering the Apollo iOS Github's repository link (https://github.com/apollographql/apollo-ios.git) in the Add Package Dependency window.

Step2: Up to Next Major 1.0 < 2.0

Step3 : build getting "No such module codegen"

Note : can i get create schema.json file create steps what is required steps need go do.
When use to create this command "apollo schema:download --endpoint=http://hasura.io/learn/graphql --header="Authorization: Bearer <token>"

DEPRECATED: This command will be removed from the `apollo` CLI in 
its next major version. Replacement functionality is available in 
the new Apollo Rover CLI: https://go.apollo.dev/t/migration

**Comment by AnthonyMDev** [comment]
You are using the old `apollo-tooling` CLI, which is deprecated and does not work with v1.0. You need to use the new Apollo iOS CLI. [Here is the documentation on the `fetch-schema` command.](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#fetch-schema)

[Here is a guide on downloading a schema.](https://www.apollographql.com/docs/ios/code-generation/downloading-schema)

[Here is our full 1.0 migration guide.](https://www.apollographql.com/docs/ios/migrations/1.0)
