### ISSUE TITLE
It that anyway to support Datetime type

### ISSUE THREAD

**Issue by wsof401** [apollographql/apollo-ios#280]
This is the schema definition 

![image](https://user-images.githubusercontent.com/3211941/40464157-15899a72-5f4c-11e8-8700-a48fbb1c995e.png)

In the generated code, `insertedAt` is converted as String, Is there any solution for supporting this

**Comment by martijnwalraven** [comment]
You can use the `--passthrough-custom-scalars` to `apollo-codegen` have the code generated with `DateTime`, but that does mean you need to provide a `DateTime` type that conforms to `JSONDecodable` and `JSONEncodable` yourself. See [here](https://github.com/apollographql/apollo-ios/blob/35337500bd01a10a9d12b3d0f8a89e4e7fa5cba8/Sources/Apollo/JSONStandardTypeConversions.swift#L140) for an example.

**Comment by wsof401** [comment]
@martijnwalraven 
Thank your a lot
