### ISSUE TITLE
API.Swifft file not added in my project

### ISSUE THREAD

**Issue by MohanVMaxIOS** [apollographql/apollo-ios#2800]
### Summary

i have tried  used IOS apollographql in my project  i have installed the SDK using SPM with Xcode project in  SDK version 1.0 
my Xcode version 14.0.1.
and i have created schema.json file using apollo CLI in terminal . after that query.graphql created using simple query .

add run script based instruction and code:

# Go to the build root and search up the chain to find the Derived Data Path where the source packages are checked out.
DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"

while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
  if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
    echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
    exit 1
  fi

  DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
done

# Grab a reference to the directory where scripts are checked out
SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/apollo-ios/scripts"

if [ -z "${SCRIPT_PATH}" ]; then
    echo >&2 "error: Couldn't find the CLI script in your checked out SPM packages; make sure to add the framework to your project."
    exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" GraphQL/API.swift

Then Build successfully But when see folder not API.swift file  

<img width="1343" alt="Screenshot 2023-01-30 at 1 36 35 PM" src="https://user-images.githubusercontent.com/121597142/215421551-da67ba7e-a5a0-4f5f-8c35-e2fa6786ed0b.png">
<img width="1335" alt="Screenshot 2023-01-30 at 1 37 00 PM" src="https://user-images.githubusercontent.com/121597142/215421579-11d1b660-b03d-4e46-a8ed-5bfecdcf8522.png">

### Version

1.0 >

### Steps to reproduce the behavior

I have followed those tutorial. 

1.https://www.apollographql.com/docs/ios
2.https://designcode.io/swiftui-advanced-handbook-apollo-graphql-part-1

### Anything else?

can i get sample project code and bit step by step documents with to integrate SDK.

**Comment by AnthonyMDev** [comment]
The tutorial you are following is out of date. It is for the 0.x versions. The 1.0 version of Apollo iOS doesn't generate a single API.swift file. It generates individual files for each of your operations and types. [Please check out our migration guide to learn how to migrate your project to Apollo iOS 1.0.](https://www.apollographql.com/docs/ios/migrations/1.0)
