### ISSUE TITLE
@skip is not working when query has default value

### ISSUE THREAD

**Issue by alexisbronchart** [apollographql/apollo-ios#2802]
### Summary

Fragments annotated with `@skip` are not included in the response when query has default value for the variable skip relies on.

### Version

1.0.6

### Steps to reproduce the behavior

Considering this query:
```
query SomeDetails(
  $id: ID!
  $skipFragment: Boolean = false
) {
  somedata(id: $id) {
    ...SomeFragment @skip(if: $skipFragment)
  }
}
```
and fetching it like so:
```
let skip = false
let query = SomeDetailsQuery(
    id: 42,
    skipFragment: .some(skip)
)
let response = try await apollo.fetch(query: query)

```
then `response.somedata.fragment.someFragment` will always be nil.
It used to work in 0.53.
If I change the skipFragment var definition from `$skipFragment: Boolean = false` to `$skipFragment: Boolean!` then it starts working again as expected.

**Comment by AnthonyMDev** [comment]
I think this is a duplicate of #2690, which has been fixed on the main branch by PR #2794. The next patch release will include this fix. You can rely on the main branch in the mean time!

**Comment by alexisbronchart** [comment]
I can confirm the issue is fixed on `main`! Thanks!

**Comment by calvincestari** [comment]
Great to hear. We've got a couple other issues we want to get out with `1.0.7` but it will be released very soon.
