### ISSUE TITLE
How can I use waitsForConnectivity in Apollo Client?

### ISSUE THREAD

**Issue by migfabio** [apollographql/apollo-ios#2803]
### Question

Looking at the source code of `URLSessionClient`, you do nothing when `urlSession(_ session: URLSession, taskIsWaitingForConnectivity task: URLSessionTask)` delegate callback is called. I need to notify the client that the device might be offline.

I guess I need to subclass `URLSessionClient`, but how can I complete the request with an error here, since I cannot access to `self.tasks`?

Any suggestions?

**Comment by calvincestari** [comment]
Hi @migfabio 👋🏻 

> Looking at the source code of URLSessionClient, you do nothing when urlSession(_ session: URLSession, taskIsWaitingForConnectivity task: URLSessionTask) delegate callback is called.

There is simply no default implementation, you're correct that you would need to subclass it to provide the logic.

> I need to notify the client that the device might be offline.

This is a [`URLSessionTaskDelegate` method](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/2908819-urlsession), the underlying `URLSession` will call this method when the system detects that there is no connectivity.

**Comment by migfabio** [comment]
@calvincestari thanks for your response, but it doesn't really clarify. When I client an `ApolloClient` and then perform a `fetch`, if the connection is waiting for connectivity, how can I notify the UI that the user is offline? for sure the result of the fetch would be a `failure`.

**Comment by calvincestari** [comment]
I think the system should be calling `taskIsWaitingForConnectivity`, not your code. Make sure you're setting `waitsForConnectivity = true` on your `URLSessionConfiguration` before creating the session. Then `URLSession` should call your subclass with the `taskIsWaitingForConnectivity` method when you start a task without connectivity.

_We can continue the conversation here but I'm going to close the issue as their is no action we need to take in our code._
