### ISSUE TITLE
Mock SomeQuery.Data from multiple subtypes

### ISSUE THREAD

**Issue by alexisbronchart** [apollographql/apollo-ios#2804]
### Question

I have some tests that I’m now upgrading to use mocks. Given a query `SomeQuery` I can create mocks for `SomeQuery.Data.Subtype1` and `SomeQuery.Data.Subtype2` but how would I create a mock of `SomeQuery.Data` from the two subtypes mocks?

**Comment by ZsoltMolnarrr** [comment]
If the question is, how to initialise response objects with a certain data for mocking responses, than I am looking for the same answer.

**Comment by calvincestari** [comment]
@ZsoltMolnarrr it sounds like you're looking for our documentation on [how to configure test mocks](https://www.apollographql.com/docs/ios/testing/test-mocks). The migration guide also has a [section](https://www.apollographql.com/docs/ios/migrations/1.0#mocking-operation-models-for-testing) on how that changed from 0.x too if you're familiar with the old pattern of test mocks.

**Comment by calvincestari** [comment]
@alexisbronchart can you share an example of the response data you're trying to mock?

**Comment by AnthonyMDev** [comment]
Your `SomeQuery.Data` type is going to be based off the "Root Query" object, which should have a generated test mock of it's own in a file called `Query+Mock.swift`. So you can make a mock of `TestMock<Query>` and set the subtype objects as values for the properties of the root fields on your `TestMock<Query>` then call `SomeQuery.Data.from(rootQueryMock)`.
