### ISSUE TITLE
App crash installing on real device (dyld[561]: Library not loaded: @rpath/ApolloAPI.framework/ApolloAPI)

### ISSUE THREAD

**Issue by albertoNovoCoinsquare** [apollographql/apollo-ios#2807]
### Question

We are migrating from cocoapods to SPM and we have a crash when install on a real device after update to Apollo to 1.0.6. We're using xCode 14.1

### Project structure
The project is a workspace that contains the following targets:
- One main target
- CocoaPod framework **target A** that contains the apollo schema, operations, etc
- CocoaPod framework **target B** with all the networking and the integration with the Apollo client.

Also right now contains a mix of cocoapods and SPM dependencies. (We're migrating from cocoapods to SPM)

### Apollo configuration
- The **target A** add ApolloAPI using SPM through Xcode.
<img width="800" alt="Screen Shot 2023-02-02 at 3 59 39 PM" src="https://user-images.githubusercontent.com/65198200/216448627-01cda175-f84e-4da8-86e7-31393308d691.png">
<img width="855" alt="Screen Shot 2023-02-02 at 3 59 55 PM" src="https://user-images.githubusercontent.com/65198200/216448735-91cbb9f3-ac48-4be4-b415-aa8983e1d674.png">

- The **target B** add Apollo and ApolloTestSupport dependencies and also has a dependency with the target A.
<img width="903" alt="Screen Shot 2023-02-02 at 4 04 32 PM" src="https://user-images.githubusercontent.com/65198200/216449391-9b78c5bf-6dcb-47a8-b6e6-8c0972fb76b1.png">

### Issue observed
Everything works fine on the simulator but when try to install the app on a real device we get the following crash:
<img width="1073" alt="Screen Shot 2023-02-02 at 4 07 56 PM" src="https://user-images.githubusercontent.com/65198200/216450135-ba2fe58e-06f7-4cc5-bd1e-e7867b26a2d1.png">

Any idea about this issue? Is there something wrong in the configuration? Any help is much appreciated.

**Comment by calvincestari** [comment]
Hi @albertoNovoCoinsquare, it's difficult to know whether the whole configuration is correct from the screenshots.

Is CXApollo.framework a cococapods framework?

> * CocoaPod framework target A that contains the apollo schema, operations, etc
> * CocoaPod framework target B with all the networking and the integration with the Apollo client.

Do you still have Apollo iOS as a dependency in CocoaPods?

**Comment by albertoNovoCoinsquare** [comment]
Hi
There is no dependency with apollo in cocoapods but CXApollo is still a cocoapods framework. I'm going to wait to completely remove cocoapods in order to use the SPM dependency.
Thanks

**Comment by calvincestari** [comment]
> There is no dependency with apollo in cocoapods but CXApollo is still a cocoapods framework.

Is that not the issue then; I don't think you can share dependencies between SPM and CocoaPods? It's worth a try to add Apollo as a CocoaPods dependency and check if the crash is resolved.

**Comment by albertoNovoCoinsquare** [comment]
Hi @calvincestari . That's what i did. For now i keep the cocoapods dependency and everything works fine.
