### ISSUE TITLE
How to initialise decoding error?

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [apollographql/apollo-ios#2808]
### Question

I would like to initialise a decoding error result, to be used as mock response for unit test cases.
Previously on Apollo 0.52 I was able to do the following:
```swift
GraphQLResultError(
  path: .init(arrayLiteral: "fragment", "field"),
  underlying: Apollo.JSONDecodingError.nullValue)
```

What would be the equivalent of this on v1.0.6?

**Comment by calvincestari** [comment]
`GraphQLExecutionError` replaced `GraphQLResultError` in 1.0. Everything else should be the same.

**Comment by calvincestari** [comment]
Closing due to there being no action we can take in Apollo iOS for this issue. If you believe you have a bug related to this issue please comment in this issue again.
