### ISSUE TITLE
Crash when using mocks for Double Nested Arrays

### ISSUE THREAD

**Issue by scottasoutherland** [apollographql/apollo-ios#2809]
### Summary

I have a schema that looks something like this: 

```
type InnerObject { 
    propertyOne: Int!
    propertyTwo: Int!
}

type OuterObject { 
    propertyOne: Int!
    propertyTwo: [[InnerObject!]!]!
}
```

And I have ran codegen for this and created the mocks. When using the mocks in tests, everything compiles fine. However when i set the value of "propertyTwo" two in mocks, and then convert it to a (non-mock) graphQL object using .from(Mock<OuterObject>)  and then try to access "propertyTwo" in code, it crashes with the error
`fatalError("\(Self.self) expected data for entity.")`

### Version

1.0.5

### Steps to reproduce the behavior

- Use a schema with a property of type:
```
[[SomeObject!]!]!
```
- Generate mocks / code from it. 
- Initialize an object for the containing type use `.from(Mock<>)`
- try to access the property of double nested array type.
- Notices the crash

### Anything else?

![Screenshot 2023-02-03 at 8 35 41 PM](https://user-images.githubusercontent.com/48388/216748917-f1b75b24-5ee0-495b-b6e3-74fac3b711d9.png)

Here's what the call stack looks like.

**Comment by calvincestari** [comment]
Thanks for the bug report @scottasoutherland. I can replicate the crash, not sure what's going wrong yet though. I'll get back to you once I've dug into it a bit more.

**Comment by scottasoutherland** [comment]
Any updates or plans to address this soon? We are having to disable some of tests in our migration to Apollo 1.0.6 since there doesn't seem to be an easy work-around.

**Comment by AnthonyMDev** [comment]
I've got a unit test reproducing this now and I'm working on a fix!

**Comment by scottasoutherland** [comment]
Great to hear! Thank you.
