### ISSUE TITLE
how to convert normal string or int values to GraphQLNullable using apollo with swift ?

### ISSUE THREAD

**Issue by MohanVMaxIOS** [apollographql/apollo-ios#2815]
### Question

Need to convert normal swift datatype to apollo datatype query like String to GraphQLNullable using swift .
i have tried like this :

 let name:String = "123"
let nullableString: GraphQLNullable<String> = "\(name )"

Error: Cannot convert value of type 'String' to specified type 'GraphQLNullable<String>'

`       let mohanname:String = "123"
        let nullableString: GraphQLNullable<String> = "\(mohanname ?? "")"
        
        apolloClient.fetch(query: GetLeadDataQuery(name:nullableString)){ result in
            
            print("result=====\(result)")

            
        }`

**Comment by scottasoutherland** [comment]
If `mohanname` is not nullable, you can use  `.some(mohanname)`, if it is you can use `mohanname ?? .none`

**Comment by calvincestari** [comment]
Closing due to there being no action we can take in Apollo iOS for this issue. If you believe you have a bug related to this issue please comment in this issue again.
