### ISSUE TITLE
Request always drop in .failed

### ISSUE THREAD

**Issue by 2jumper3** [apollographql/apollo-ios#2817]
### Question

Hi all! 

I'm trying to understand why apollo request always .failed, instead of in insomnia it work great. I'm looking for interceptors for this, but cant find. 

So, I got perfect worked request from insomnia: 
<img width="898" alt="Снимок экрана 2023-02-08 в 11 57 41" src="https://user-images.githubusercontent.com/45697468/217468793-ae31d445-fb7f-4191-ba45-747488c71593.png">

But in Xcode, I am always dropping to this statement, because of `self.additionalErrorHandler` in `public class RequestChain` always nil
<img width="784" alt="Снимок экрана 2023-02-08 в 11 58 19" src="https://user-images.githubusercontent.com/45697468/217468934-6ca82d0f-5c33-4f95-998a-46320ac09a43.png">

And every time when I'm trying to simulate error with wrong login/password in method: 
<img width="973" alt="Снимок экрана 2023-02-08 в 12 01 40" src="https://user-images.githubusercontent.com/45697468/217469637-4604d903-0903-478a-a9bb-3b05322bbb4e.png">

It always print: 
`Error at path "authLogin)": nullValue`

Correct login/password works great. 

Should I create any instance to provide  `self.additionalErrorHandler` in `public class RequestChain` ? Or this is not my problem - this is backend bug?

**Comment by calvincestari** [comment]
Hi @2jumper3, if you inspect the raw response code and body from both requests are they the same? Is Apollo iOS being returned a `200` status code?

**Comment by calvincestari** [comment]
> I cant understand is it my mistake, or backend.

I don't know what your backend implementation is, so I can't say where the problem is. I suggest looking at the raw response data coming back from the server and that will give you a better idea of how Apollo iOS should be parsing it.

**Comment by 2jumper3** [comment]
@calvincestari is it ok, or I should dig deeper? 
<img width="1400" alt="Снимок экрана 2023-02-08 в 23 48 04" src="https://user-images.githubusercontent.com/45697468/217635863-095b1ea6-3ef1-4e87-b8c3-5892c362be93.png">

**Comment by calvincestari** [comment]
`failure: GraphQLExecutionError` is telling you that there was a problem parsing the response. `path: authSignup` combined with `underlying: ApolloAPI.JSONDecodingError.nullValue` signals that it received a null value when it shouldn't have.

What is the response type of `authSignup`? I suspect it's non-null, i.e.: `!`.

I think Insomnia is just showing you the response and not validating it, therefore it 'looks' correct. Apollo iOS validates all responses to ensure they're type-correct. Receiving a null value when the schema indicates there should always be a value is a valid failure.

**Comment by 2jumper3** [comment]
HI @calvincestari, thanks again for your assist! 

We checked "!", and we remove "!" from `AuthTokenPayload` got: 
![telegram-cloud-photo-size-2-5415830873107972431-y](https://user-images.githubusercontent.com/45697468/217744589-70d7dd23-1fcb-4082-807d-feccf7243493.jpg)
![telegram-cloud-photo-size-2-5415830873107972427-y](https://user-images.githubusercontent.com/45697468/217744666-c9c27b82-c92c-4846-931c-eb459712989f.jpg)


If I understand clearly, it means that input parameters should be non-null, but `AuthTokenPayload` now can be nullable. But the error still exist the same.

**Comment by 2jumper3** [comment]
Hi @calvincestari, and many thanks for your assist! 
We remove "!" and it worked great! 
Thanks again and have a good day.
