### ISSUE TITLE
codegen: Getting Cannot find type 'MockObject' in scope when generating test mock (SwiftUI project)

### ISSUE THREAD

**Issue by otusweb** [apollographql/apollo-ios#2818]
### Summary

I configured the codegen to generate the mocks for the objects in my schema. I then added the generated files to my project.

I get a compilation warning `Cannot find type 'MockObject' in scope`
Looking in the generated code, I don't see MockObject being defined anywhere, nor did I see in the documentation where to find the file.

### Version

1.0.6

### Steps to reproduce the behavior

- add apollo via cocoapod to project
- config for codegen 
``` {
  "schemaName" : "GraphCMSAPI",
  "options" : {
    "cocoapodsCompatibleImportStatements" : true, 
    "pruneGeneratedFiles": true
  },
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "**/*.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "absolute" : {
      "path": "./Generated/GraphCMS/mocks"
      }
    },
    "schemaTypes" : {
      "path" : "./Generated/GraphCMS",
      "moduleType" : {
            "embeddedInTarget": {
                "name": "RockTrainer"
            }
      }
    },
    "operations" : {
      "absolute" : {
      "path": "./Generated/GraphCMS"
      }
    }
  },
  "schemaDownloadConfiguration": {
    "downloadMethod": {
        "introspection": {
            "endpointURL": "https://api-us-east-1.graphcms.com/v2/ck2c5vbdx1n3a01gl6bp32u5v/master",
            "httpMethod": {
                "POST": {}
            },
            "includeDeprecatedInputValues": false,
            "outputFormat": "SDL"
        }
    },
    "downloadTimeout": 60,
    "headers": [],
    "outputPath": "./Generated/GraphCMS/schema.graphqls"
}
}
```
- run `./Pods/Apollo/apollo-ios-cli fetch-schema`
- run `./Pods/Apollo/apollo-ios-cli generate`
- add the graphCMS folder under the generated folder to a swiftUI project

**Comment by calvincestari** [comment]
Hi @otusweb, I think that's probably because it's missing the `ApolloTestMocks` library. See the docs [here](https://www.apollographql.com/docs/ios/testing/test-mocks/#setting-up-test-mocks).
