### ISSUE TITLE
Cannot find type 'MockObject' in scope

### ISSUE THREAD

**Issue by ZsoltMolnarMBH** [apollographql/apollo-ios#2823]
### Question

Hello!

Our project uses CocoaPods. I want to link the generated Mock source files to the build target of our unit tests.
On its own this is pretty easy, I just set the generator to output the files to a directory in our unit test target, and add target membership to these files manually.

The result looks correct (even import statements look fine), but none of the generated files do compile due to not finding any source files those reside in `ApolloTestSupport`.
```
Cannot find type 'MockObject' in scope
Type annotation missing in pattern (@Field)
Cannot find type 'Mock' in scope
```

I tried the following pod configurations for our unit test target, none of them worked:

```
  target `AppUnitTests' do
    inherit! :search_paths
    pod 'SwiftyMocky'
    pod 'Apollo'
  end
```

```
  target 'AppUnitTests' do
    inherit! :search_paths
    pod 'SwiftyMocky'
    pod 'Apollo/ApolloTestSupport'
  end
```

```
  target 'AppUnitTests' do
    inherit! :search_paths
    pod 'SwiftyMocky'
    pod 'Apollo'
    pod 'Apollo/ApolloTestSupport'
  end
```

How can I fix this?

**Comment by calvincestari** [comment]
@ZsoltMolnarMBH, can you add a sample project that demonstrates the issue please.

**Comment by ZsoltMolnarMBH** [comment]
Hello!
An example project has been assembled: https://github.com/ZsoltMolnarMBH/GithubGraphQL

**Comment by calvincestari** [comment]
@ZsoltMolnarMBH thanks for the sample project. I cannot find the reason for that build error but I suspect it's some linking/search path in Xcode. Have you tried creating a pod of your own for the schema and test mocks module? If you try that you'll need to use the `.other` module type output value.

**Comment by ZsoltMolnarMBH** [comment]
Hello @calvincestari !
The suggested code generator config change didn't seem to have any effect.

The compiler error seems to be pretty clear for me. It cannot find `MockObject` inside `Apollo`.
![image](https://user-images.githubusercontent.com/91884137/220982078-d79b860a-a4f3-42fd-bbd9-1b03d4c3d334.png)

It is because this type really is not inside Apollo, but instead inside the ApolloTestSupport sources. Unfortunately the latter doesn't seem to be possible to link against in a CocoaPods environment.

Would it be possible to move test related source files into Apollo build target?

**Comment by calvincestari** [comment]
> The compiler error seems to be pretty clear for me. It cannot find MockObject inside Apollo.

Yes, it is clear but I think with some tweaks to CocoaPods linking or bundling it would be visible since it is in the main app test target, jsut not the linked library test target.

> It is because this type really is not inside `Apollo`, but instead inside the `ApolloTestSupport` sources.

That's correct but CocoaPods bundles all modules together in one which is named the same as the package. Which is why you don't need to import ApolloAPI and only import Apollo. It's also why we have the `cocoapodsCompatibleImportStatements` config property to generate the correct import statements. All this is to say that while it is not technically inside the Apollo module, it should be available in that namespace.

> Would it be possible to move test related source files into Apollo build target?

I'm not sure what you mean here, can you go into a bit more detail please.

**Comment by CcMarioAsk** [comment]
@calvincestari 
Hi, I also encountered the similar problem.
Can u see what the problem.
I submitted the relevant instructions to Apollo community, 5561

**Comment by calvincestari** [comment]
@CcMarioAsk - can you share a link to the other post please.

**Comment by CcMarioAsk** [comment]
> 

https://community.apollographql.com/t/apollo-auto-generate-code-when-compile-getting-more-issues-cannot-find-type-schemaname-in-scope/5661/6

this link
thx very much

**Comment by ZsoltMolnarMBH** [comment]
Hello @calvincestari !

It seems like to me (using CocoaPods), it is not possible to generate code into a testable build target and link this target against Apollo (and ApolloTestSupport).
We keep getting the same compiler error (about `MockObject` and such not found), even with the recommended codegen settings (`cocoapodsCompatibleImportStatements`, `.other` module type).

The idea behind this usecase is the following: we want typesafe mock objects to be used in the application unit tests.

If this is possible in any way, please let me know how should I change the project exactly? (Or maybe is there a part I missed in the documentation?).

**Comment by ZsoltMolnarMBH** [comment]
Hello @calvincestari !
The issue still effects the latest release version.
To summarize the issue again: we generate apollo types into a framework, than the mocks (specifically the `Mock` type from ApolloTestSupport) are not visible for the compiler from the unit test build target.
This makes it impossible for us to use generated mock types when writing unit tests.

Can you give an update on this please?
Please do note: some projects are forced to use CocoaPods.

**Comment by calvincestari** [comment]
I'll take another look at the sample project @ZsoltMolnarMBH.

**Comment by calvincestari** [comment]
@ZsoltMolnarMBH here is a sample project using CocoaPods with unit tests - [CocoaPodsSample.zip](https://github.com/apollographql/apollo-ios/files/11505053/CocoaPodsSample.zip)

I could not get the CocoaPods configuration working with dynamic linking but I think that's a question for CocoaPods not Apollo iOS. Either way, it is entirely possible to use the mock objects in unit tests, as demonstrated.

I'm going to close this issue as I don't think there is anything we can take action on in Apollo iOS for this issue. If you do find out that our podspec configuration is incorrect please post back here and we'll gladly take another look.

**Comment by ZsoltMolnarMBH** [comment]
@calvincestari  Thank you for the help!
The sample project you provided helped.
The key was to use static linking for tests, I never knew this feature of CocoaPods existed.

I know CocoaPods is not a top priority but I adding specific examples about this to the docs could be helpful for many.
