### ISSUE TITLE
Add schema to target

### ISSUE THREAD

**Issue by wlopezvai** [apollographql/apollo-ios#2825]
### Question

Hello, I've been trying to add the generated files automatically to the project but I can't find any help on the documentation. 

I've tried generating the files with the option.moduleType as swiftPackageManager or embeddedInTarget, and created a script that runs before "compile sources" to generate the files, but I'm stuck trying to add it to the target (I have a single target). I'm also using SPM with the Xcode GUI and trying to add it local after the first generate script but I don't know how to use it in the actual project, I've been working manually embedding the files. Can someone put me in the right direction?

**Comment by calvincestari** [comment]
Hi @wlopezvai 👋🏻 

> I've tried generating the files with the option.moduleType as swiftPackageManager or embeddedInTarget

These output different modules and they require different methods to integrate them with your project.
* `swiftPackageManager`: Generates a Swift package that you add to your project as another SPM dependency. If you have an Xcode based project then you can use the SPM UI the same way as you added Apollo as an SPM dependency except this time it will be _local_ package and not from a git repo; you'll also need to link the library to your Xcode targets too. If your project uses a Package.swift file then you will need to manually add it as a dependency and add it to the targets that need it.
* `embeddedInTarget(name:)`: Generates Swift files with no defined module to them. The generated files will be namespaced in a caseless enum to prevent type conflicts but you are responsible for adding all the generated files to your project.

> I'm also using SPM with the Xcode GUI and trying to add it local after the first generate script but I don't know how to use it in the actual project, I've been working manually embedding the files.

It sounds like you want to use the generated SPM package in which case you do not need to manually add any files, only add the generated package and link the library. From there you will need to import the module into whichever Swift file you want to use the generated types in.
