### ISSUE TITLE
Mocking a fragment implemetation 

### ISSUE THREAD

**Issue by iAmericanBoy** [apollographql/apollo-ios#2832]
### Question

Given a query like this:
```Graphql
    query CheckingAccount($accountId: ID!) {
      node(id: $accountId) {
        ... on CheckingAccount {
          header {
            title
            balance
            intrest
           }
          ...ApolloTransferParticipant
        }
      }
    }

    fragment ApolloTransferParticipant on TransferParticipant {
      id
      transferParticipantType
      transferParticipantName
      ... on Account {
        isFunded
      }
    }
```

Is there a way to mock the Account part of this somehow for testing? Im able to mock the Checkign Account without any issues but i'm not finding an init I can give a value for `isFunded` 
Example: 
```Swift
        var mockData = CheckingAccountQuery.Data.init(
            node: CheckingAccountQuery.Data.Node.makeCheckingAccount(
                header: CheckingAccountQuery.Data.Node.AsCheckingAccount.Header(
                  title: "Bank Account", 
                  balance, "$10.00", 
                  interest: "$12.34"),
                id: "12345",
                transferParticipantType: .checking,
                transferParticipantName: "Bank Account"))
```

Granted we are still on a pre 1.0 version so the answer might be use the awesome Mocking in 1.0 but I just wanted to check if a mock like this is even possible?

**Comment by calvincestari** [comment]
Hi - I don't have a definitive answer for you re. 0.x but is there not a corresponding `makeAccount` initializer?

> Granted we are still on a pre 1.0 version so the answer might be use the awesome Mocking in 1.0 but I just wanted to check if a mock like this is even possible?

With the field merging strategy in `1.0` I it should definitely be possible.

**Comment by calvincestari** [comment]
I'm going to close this issue since there isn't anything actionable for us to do here. If you have issue with 1.0 not generating the initializers you expect please do let us know.
