### ISSUE TITLE
Allow custom schema module file generators

### ISSUE THREAD

**Issue by wiedem** [apollographql/apollo-ios#2834]
### Use case

We do not use the standard CLI for code generation but use the possibilities of the `ApolloCodegenLib`.
In the course of this, we would like to be able to influence the generation of the schema module file, which is currently only possible to a very limited extent.

Only the three module types `swiftPackageManager`, `embeddedInTarget` and `other` are currently offered. These module types do not currently allow customization.

In my use cases, for example, we would like to control the generation of the Swift package manifest file ourselves in order to be able to make various adjustments.

### Describe the solution you'd like

Make the `TemplateRenderer` and associated types public and let developers implement their own custom renderers.
By extending the `ModuleType` enum with a new `custom` case having an associated `TemplateRenderer` instance, developers could create fully customized schema module files.

Custom implementations then could look something like this:
```Swift
struct MyTemplateRenderer: TemplateRenderer {
    ...
```

```Swift
let codegenOutput = ApolloCodegenConfiguration.FileOutput(
    schemaTypes: ApolloCodegenConfiguration.SchemaTypesFileOutput(
        path: targetPath,
        moduleType: .custom(MyTemplateRenderer())
    ),
```

**Comment by calvincestari** [comment]
Hi @wiedem 👋🏻 

> We do not use the standard CLI for code generation but use the possibilities of the ApolloCodegenLib.

This shouldn't make any difference, the config file used by the CLI supports the same configuration options as `ApolloCodegenConfiguration`.

> In my use cases, for example, we would like to control the generation of the Swift package manifest file ourselves in order to be able to make various adjustments.

Can you share with me what kind of customizations you're wanting to make to the generated package file?

> Make the TemplateRenderer and associated types public and let developers implement their own custom renderers.
By extending the ModuleType enum with a new custom case having an associated TemplateRenderer instance, developers could create fully customized schema module files.

IMO this will lead to a very frustrating code generation experience for many users. The [SPM module template](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/Templates/SwiftPackageManagerModuleTemplate.swift) may look simple enough but once you get into a more complicated template such as the [operation definition template](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/Templates/OperationDefinitionTemplate.swift) it's very easy to make mistakes. The templates are thoroughly tested so we can make strong guarantees that the code generated will build. We couldn't have that assurance with custom templates. @AnthonyMDev and I have spoken about this and while we don't have a solution yet we do understand the need for it.

If the generated SPM package is very different from what you need then you can also try the `.other` module type which essentially tells the codegen engine that you will be responsible for creating the package and it only needs to put the generated files in the output paths; the difference between `.other` and `.embeddedInTarget` is in the import statements. So this way you can create a completely custom SPM package and still use codegen.

**Comment by wiedem** [comment]
> This shouldn't make any difference, the config file used by the CLI supports the same configuration options as `ApolloCodegenConfiguration`.

Unfortunately, generating the code files (and the schema download) via the CLI deviates from our requirements and build process and would be much more difficult to handle.

> Can you share with me what kind of customizations you're wanting to make to the generated package file?

Regarding the Swift package this includes among others:
- Custom restrictions on the supported platforms and their versions
- Pinning Apollo to a specific version or restricting the version being used to patch versions instead of any version up to the next major update (note that Apollo is not a direct dependency of our project)
- Additional custom target(s) with various extensions for the queries, their types and test-mocks
- Test target for those extensions
- Additional dependencies needed for mentioned extensions

Of course, this can all be achieved with an additional Swift package that covers these extensions and requirements, but on the other hand it is tedious additional work, it is tightly bound to the Apollo implementation and could e.g. be achieved in an easy way with additional targets in the generated Swift package.
The generated code and the extensions would still be cleanly isolated from each other.

> If the generated SPM package is very different from what you need then you can also try the `.other` module type which essentially tells the codegen engine that you will be responsible for creating the package and it only needs to put the generated files in the output paths; the difference between `.other` and `.embeddedInTarget` is in the import statements. So this way you can create a completely custom SPM package and still use codegen.

Thanks for pointing this out. Probably `.other` is actually the method we should use in our case.

> but once you get into a more complicated template such as the [operation definition template](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/Templates/OperationDefinitionTemplate.swift) it's very easy to make mistakes.

Fair enough, I certainly understand the argument.
On the other hand, more flexibility would give developers the opportunity to deliberately deviate from the standard in order to adapt certain things to the sometimes complex projects and their needs.

**Comment by calvincestari** [comment]
> Thanks for pointing this out. Probably .other is actually the method we should use in our case.

Let me know if that satisfies your needs or if you have any issues with it.

> On the other hand, more flexibility would give developers the opportunity to deliberately deviate from the standard in order to adapt certain things to the sometimes complex projects and their needs.

Yes, we do recognize the need to be able to modify the generated code/package. We've other similar request and continue to seek a solution that would satisfy everyone.

**Comment by calvincestari** [comment]
We're looking into allowing SPM package.swift file edits in a future minor version. You can watch and track that work in https://github.com/apollographql/apollo-ios/issues/2839.
