### ISSUE TITLE
XCode 14.3 Beta reveals hundreds of "Non-sendable" type warnings related to Apollo-generated Types

### ISSUE THREAD

**Issue by mdhornet90** [apollographql/apollo-ios#2835]
### Summary

After upgrading to the XCode 14.3 Beta, I see this sort of warning hundreds of times during compilation:

```
Non-sendable type 'FooQuery.Data.Foo?' passed in implicitly asynchronous call to main actor-isolated function cannot cross actor boundary
```

Is there anything specific to the setup I have to change to make sure these generated types conform to `Sendable` or is this in active development against the XCode Beta? Let me know if you need more info

### Version

1.0.7

### Steps to reproduce the behavior

1. Generate GraphQL models per documentation
2. Attempt to reference the models in an isolated async context
3. Observe compiler warning

**Comment by calvincestari** [comment]
Hi @mdhornet90, I haven't tried the 14.3 beta and I don't think @AnthonyMDev has either.

Are you explicitly using Swift Concurrency functions or do these warnings appear even without using the new concurrency features in a project?

**Comment by mdhornet90** [comment]
Generally I'm noticing these kinds of warnings in explicit async contexts. Some examples:
```
        await withThrowingTaskGroup(of: Void.self) { [weak self] group in
            guard let self = self else { return }

            group.addTask {
                // yields warning "Non-sendable type 'FooQuery.Data.Foo?' passed in implicitly asynchronous call to main actor-isolated function cannot cross actor boundary"
                try await self.getFoo()
            }
            ...
       }
```
```
    private func fetchUserData() async throws {
        if let userId = self.user?.id {
            // yields warning "Non-sendable type '[FooQuery.Data.Foo]' returned by call from main actor-isolated context to non-isolated instance method 'fetchFoosByUserId(userId:)' cannot cross actor boundary"
            self.multipleFoos = try await fetchFoosByUserId(userId: userId)
        }
    }
```

`FooQuery.Data.Foo` being an example of Apollo-generated types based on our GQL schema.

**Comment by calvincestari** [comment]
I've downloaded Xcode 14.3 and built both Apollo iOS and a quick sample application that uses it as a dependency but without any Swift Concurrency in it. In both builds there are no concurrency related warnings, so I think this is definitely only appearing in apps that use Apollo iOS + Swift Concurrency.

We've had issues before with the `Sendable` type which were resolved by telling the concurrency system that they're unsafe and not to apply any of the bounds checking during compilation - #2147. I'm not sure if that is what we need here too.

**Comment by AnthonyMDev** [comment]
I think we should consider whether our generated models fulfill the requirements to be safely marked as `Sendable`. It seems on the surface that they do, but are there edge cases there we need to work out? The local cache mutations would likely not be `Sendable` as they are mutable. But immutable data should be theoretically fine to mark `Sendable`. I just don't want to get into a situation where we cause other people to have build errors when using them if there are edge cases where they would not be `Sendable`.

**Comment by kaybutter** [comment]
From the Xcode Beta Release Notes:
> The Xcode “Strict Concurrency Checking” setting is not correctly passed to the compiler. If you set it to “Minimal” (the default), the compiler will still perform “Targeted” checks. (105637789)

So, these warnings are not meant to show up (because not all the features around Sendable checks have been implemented in Swift) and will probably disappear before the final 14.3 release.

**Comment by calvincestari** [comment]
_Note to self:_ Don't think we need a config option for this it should just always output the annotation but make sure it works correctly with iOS 12, which is the minimum we version we support and is a version before Swift Concurrency backport.

**Comment by AnthonyMDev** [comment]
Closed due to inactivity
