### ISSUE TITLE
How can I set custom header to specific request

### ISSUE THREAD

**Issue by wsof401** [apollographql/apollo-ios#284]
Here is some cases we are facing in our app.

1. When user login app, we need add token to specific request header
> Now we build new `apolloClient`, but our token expiration is 15mins, We will build a new client  frequently

2. For some reason,  some custom header should be add to the request.
>  We haven‘t found a good solution for case 2

Is `apollo-ios` support it? 
`URLProtocol` is a solution but not a good one

**Comment by paulemmanuel-garcia** [comment]
Hello,

I'm just starting with Apollo on iOS, so I'm not 100% sure and it might not be the recommended way of doing.

Actually you can initialize the `ApolloClient` with:

```swift
init(url: URL, configuration: URLSessionConfiguration = URLSessionConfiguration.default, sendOperationIdentifiers: Bool = false)
```

So you can set some custom headers with the `URLSessionConfiguration`. This will be done to all your requests though.

Hope it can be helpful.

**Comment by wsof401** [comment]
@paulemmanuel-garcia no, It only worked when the first time you set it

**Comment by jorgelub12** [comment]
Did you found any solution for this?

**Comment by wsof401** [comment]
@jorgelub12 Yes,  A client for addtional headers in memory
