### ISSUE TITLE
Release 0.53.0: Bug Fixing and Security Fixes

### ISSUE THREAD

**Issue by PiDyGB** [apollographql/apollo-ios#2843]
### Question

In our project, we are using version 0.X of the apollo-ios SDK, we would like to know if this version is still supported either for bug fixing or security updates. Thanks a lot.

**Comment by calvincestari** [comment]
Hi @PiDyGB - we haven't set an end-of-life date for 0.x versions yet so yes it is still supported. In practice though it's likely that only blocker-level issues will be addressed; we evaluate these on a case-by-case basis.

I believe we've responded to all issues, either acknowledging or closing them; are there any particular issues that you're watching for updates or waiting on a response for?

**Comment by PiDyGB** [comment]
@calvincestari - Thanks, no, there aren't particular issues, just to correctly plan the migration.

**Comment by calvincestari** [comment]
OK, I'm going to close this issue then.
