### ISSUE TITLE
GraphQL-SSE

### ISSUE THREAD

**Issue by mtirao** [apollographql/apollo-ios#2845]
### Question

Is there any plan to implement GraphQL-SSE?

**Comment by calvincestari** [comment]
Hi @mtirao - no, we have no plans to support GraphQL-SSE. Can you share more details on what the context is that you're needing/asking for it?

**Comment by mtirao** [comment]
Hi @calvincestari I'm working in an app that use subscriptions and this protocol seems to be a little better to handle this type of operations.
