### ISSUE TITLE
Reset store on logout

### ISSUE THREAD

**Issue by mooshee** [apollographql/apollo-ios#2846]
### Question

The React client has a very clear way to cancel pending requests and restore the client on logout https://www.apollographql.com/docs/react/networking/authentication/#reset-store-on-logout.

What's the analog for the ios client?

**Comment by calvincestari** [comment]
> The React client has a very clear way to cancel pending requests and restore the client on logout

I think it's misleading to claim it handles restore on logout for you. The only thing Apollo Client, the library, offers in that code is `client.resetStore()` or `client.clearStore()`, the documentation simply shows you how to use those in the context of login/logout.

The equivalent way to reset/clear the store in Apollo iOS is [`clearCache(callbackQueue:completion:)`](https://www.apollographql.com/docs/ios/docc/documentation/apollo/apollostore/clearcache(callbackqueue:completion:)).

**Comment by mooshee** [comment]
*reset* not *restore*.

Does this also cancel in-flight requests?

**Comment by calvincestari** [comment]
> Does this also cancel in-flight requests?

No, it only clears the cache. Each request through `ApolloClient` should return a `Cancellable` type that can be used to cancel current requests.
