### ISSUE TITLE
Cannot Find type {schema_name} in scope

### ISSUE THREAD

**Issue by shashank0624** [apollographql/apollo-ios#2852]
### Summary

I have installed the Apollo using the Cocoapods, But when i successfully generated the Operation and Schema files and manually add them in the project, 
this is giving the error "Cannot find type {schemaName}' in scope.
![Screenshot 2023-02-24 at 10 23 21 PM](https://user-images.githubusercontent.com/12460819/221246685-8b2f631c-4e9b-4903-9c30-7ec0f6d5aa5e.png)
![Screenshot 2023-02-24 at 10 23 11 PM](https://user-images.githubusercontent.com/12460819/221246713-8c5855ef-6474-464d-84fb-e5b53c0e46e0.png)

### Version

Version 1.0.7

### Steps to reproduce the behavior

The issues is report automatically when you manually add the generated files into the project.

**Comment by calvincestari** [comment]
Hi @shashank0624 - using the `.other` module type makes you responsible for creating the pod container, and it must be named the same as the provided schema name. You shouldn't be manually adding the generated files to your project with the `.other.` module type since you're telling the code generator that the generated types will be available in a module.

If you simply are using CocoaPod to create a dependency on Apollo iOS but want to manually add the generated files then you should use the `.embeddedInTarget(name:)` module type. The benefit of `.other` is that the generated types will be in a module and can therefore be shared between multiple other modules. `.embeddedInTarget(name:)` limits you to using those types within a single module.

**Comment by shashank0624** [comment]
@calvincestari can you please provide me some tutorial how can we create pod container?

**Comment by calvincestari** [comment]
https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by CcMarioAsk** [comment]
Hi @calvincestari 
Successfully solved the previous problem, the problem of schema name. But there is a new error prompt.
<img width="1400" alt="0DDCDC7E-D531-4940-819B-51EA20E98BEC" src="https://user-images.githubusercontent.com/126216074/221457321-0a09ee7e-3d3a-4c62-9936-c70ca4f4793c.png">

**Comment by CcMarioAsk** [comment]
<img width="1400" alt="3AF69FBE-5C33-480E-A8EA-5E69CCC87A5F" src="https://user-images.githubusercontent.com/126216074/221457807-d46b6be2-3c4d-412f-978f-7019f7f67573.png">

**Comment by CcMarioAsk** [comment]
<img width="1400" alt="4E9D9596-A10D-43D2-874E-DA313273E8B3" src="https://user-images.githubusercontent.com/126216074/221458152-0be7b498-e8ea-422f-bbdf-5987c64894b7.png">
<img width="1400" alt="3D635796-4B84-4790-8439-4618BA4BBCC8" src="https://user-images.githubusercontent.com/126216074/221458171-76cabce2-388a-4515-9e2b-0646650b2bdc.png">

**Comment by CcMarioAsk** [comment]
> <img alt="4E9D9596-A10D-43D2-874E-DA313273E8B3" width="1400" src="https://user-images.githubusercontent.com/126216074/221458152-0be7b498-e8ea-422f-bbdf-5987c64894b7.png">

Hi @calvincestari 
Sorry, I have to trouble you again.
After commenting “extension schemaName”, and use BankInfoquery() in the fetch method parameter, can run successfully.

<img width="1044" alt="B840CC1C-CB87-4228-B941-4AF7DB4B109D" src="https://user-images.githubusercontent.com/126216074/221494791-61ddc981-db7d-4333-b7d2-a0d969d8eb43.png">

But got “sessionInvalidated” error.

<img width="1131" alt="D465EC48-B09F-40C2-ABA3-CFF282820718" src="https://user-images.githubusercontent.com/126216074/221494982-a8376e70-61ea-4b7b-994b-dfa63b5c2084.png">
<img width="1140" alt="1F8E32C9-6601-4F85-8F9B-BC8C36E2120A" src="https://user-images.githubusercontent.com/126216074/221494997-b7ba3895-3166-42b8-ab2a-044fd942c13c.png">

**Comment by calvincestari** [comment]
The session is invalidated only when the default interceptor is released. The block for your `fetch` seems correct but it's worth checking that the default interceptor provider is still valid.

Regarding the first problem of `Cannot find 'BankInfoQuery' in scope`, it looks like you're still manually adding the generated files to your project. If you created a pod for the schema module and are using `.other` for the module type you must add that new pod as a dependency in your project just like you added the dependency on Apollo iOS.
