### ISSUE TITLE
How to parse data which is either String or Double from a Key in 1.0.7 version of Apollo

### ISSUE THREAD

**Issue by RajendraNayak** [apollographql/apollo-ios#2855]
Hi Team,
I migrated code from From 0.x to 1.0.7, I am facing one issue could you please help here?

GraphQL Api sends data either in String or Double for this key "time" e.g "time" : "23131313133" or  "time" : 23131313133
Earlier (in version 0.53.0) type of "time" was "any" type so that I could put additional logic to check if it's String or Double like below

<img width="903" alt="Screenshot 2023-02-27 at 3 02 16 PM" src="https://user-images.githubusercontent.com/3063882/221556648-2fbad967-63b4-4f4f-8d14-fe85e31292f3.png">
In above resultMap is [String: Any]

But after upgrading, I don't see an option to check if "time" is String or Double
I want something like this **.field("time", Any.self)** however OutputTypeConvertible supports String, Int, Bool, Float, Double not Any type

Schema

<img width="439" alt="Schema" src="https://user-images.githubusercontent.com/3063882/221558227-345e1e01-171f-43de-a065-a68501af7618.png">

Genearted Files

<img width="1047" alt="Screenshot 2023-02-27 at 3 23 50 PM" src="https://user-images.githubusercontent.com/3063882/221558326-136a4155-2512-4091-84c7-da3fe53f3779.png">

<img width="1151" alt="Screenshot 2023-02-27 at 3 24 17 PM" src="https://user-images.githubusercontent.com/3063882/221558387-ffc59f21-3721-4eb4-9a8b-177a0df01aef.png">

<img width="940" alt="Screenshot 2023-02-27 at 5 29 10 PM" src="https://user-images.githubusercontent.com/3063882/221558434-4e2b8663-e887-4d49-a29a-45cfd7674131.png">

**Comment by calvincestari** [comment]
Hi @RajendraNayak - you can still define that logic to check for `Double` vs. `String`, it just has to be done in a different file now. Take a read through the [Custom Scalars](https://www.apollographql.com/docs/ios/migrations/1.0#custom-scalars) portion of the [1.0 migration guide](https://www.apollographql.com/docs/ios/migrations/1.0/) and it should steer you in the right direction with the example there.

**Comment by RajendraNayak** [comment]
Hi @calvincestari 
Thanks for your reply.

I tried using Custom Scalar like below, however this method is not getting called "public init(_jsonValue value: JSONValue)"
Could you please tell me what went wrong?

<img width="776" alt="Screenshot 2023-03-02 at 2 37 17 PM" src="https://user-images.githubusercontent.com/3063882/222382840-51ad5778-8a57-4c14-91c5-725b52dbdbcc.png">

======================================
public typealias DateTime = Double

extension DateTime: CustomScalarType {
    public var jsonValue: JSONValue {
        debugPrint("Reaching here...")
        return self
    }
    
    public init(_jsonValue value: JSONValue) throws {
        debugPrint("Reaching here...")
        if let value = value as? String {
            let formatter = DateFormatter()
            formatter.dateFormat = FBConstants.DateFormatter.formatterWithTAndSSZ
            self = (formatter.date(from: value)?.timeIntervalSince1970 ?? 0.0) * 1000
        }  else if let value = value as? Double {
            self = value
        }
        self = 0.0
    }
}

======================================
<img width="495" alt="Screenshot 2023-03-02 at 1 49 56 PM" src="https://user-images.githubusercontent.com/3063882/222382874-80434b99-ccd1-40ec-96fc-323bceb3db46.png">

public static var __selections: [ApolloAPI.Selection] { [
            .field("quality", String?.self),
            .field("time", DateTime.self),
            .field("value", String.self),
          ] }

======================================

**Comment by calvincestari** [comment]
> I tried using Custom Scalar like below, however this method is not getting called "public init(_jsonValue value: JSONValue)"

I think you'll find that it is [this implementation, on `Double`](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloAPI/JSONStandardTypeConversions.swift#L58), that is being called because of the use of a `typealias`. We have created extensions for all the [built-in scalar types of the GraphQL spec](https://spec.graphql.org/draft/#sec-Scalars.Built-in-Scalars).

For your code to work you should:
* remove the typealias declaration: ~`public typealias DateTime = Double`~
* change the DateTime definition from an extension to a struct: `struct DateTime: CustomScalarType {`

**Comment by RajendraNayak** [comment]
Hi @calvincestari 

Many thanks for your suggestion & could you please help me more on that ?

I implemented as per your above suggestion however I am getting below error

**Could not cast value of type 'Swift.Int64' (0x7ff865e401f8) to 'AssetHistorySchema.DateTime' (0x105a96540).**

value of **__data** is coming as 

**DataDict(_data: [\"time\": AnyHashable(1677747780001), \"value\": AnyHashable(30), \"quality\": AnyHashable(<null>)], _variables: nil)**

Here is what I implemented

<img width="730" alt="Screenshot 2023-03-03 at 5 47 21 PM" src="https://user-images.githubusercontent.com/3063882/222718827-d811409d-82c3-4729-8488-1fc82c17418e.png">

<img width="1013" alt="Screenshot 2023-03-03 at 5 47 03 PM" src="https://user-images.githubusercontent.com/3063882/222718886-685c80d1-6951-4326-bbff-98bf180af473.png">

 Thanks in Adv

**Comment by RajendraNayak** [comment]
Hi @calvincestari Could you please help me on above query?

**Comment by RajendraNayak** [comment]
Hi @calvincestari  Please help me.

Thanks
Rajendra

**Comment by calvincestari** [comment]
> Upon debugging , I found that control is not coming inside below else if & else part

Your custom scalar initializer is being called though right? If it's not flowing through the  `as? Double` or final `else` then it must be getting processed as a `String`? If that's true then the error message about not being able to cast from `Int64` doesn't make sense.

Your custom scalar logic must be able to handle the data in the type that it presented to you as.

**Comment by calvincestari** [comment]
@RajendraNayak - let's keep the conversion for #2871 here too since they appear to be the same issue.

Did you confirm that you custom scalar code is being called?

**Comment by AnthonyMDev** [comment]
We're having a hard time figuring out what could be going wrong here. Your code looks correct. Is there any way you could create a reproduction in a sample project, or give us access to your project so that we can try to debug this.
