### ISSUE TITLE
ApolloCodegenConfiguration output combination

### ISSUE THREAD

**Issue by martin-muller** [apollographql/apollo-ios#2856]
### Question

Thank you for the work on Apollo 1.0. We've been trying to update Apollo in our project to 1.0 and had some issues with the codegen configuration.

Our setup:

We have a workspace with one iOS app and one package file. The package file defines different products including our GQL network layer. We don't use the Apollo cli to fetch and generate code, we create Swift executable that imports `ApolloCodegenLib` and uses `ApolloSchemaDownloader` and `ApolloCodegen`. We like to have our `.graphql` files and our models in one package, making the structure look something like this:

```other
├── GQLClient
│   ├── Models  // I'd like the generated models here
│   ├── Queries // our .graphql files 
│   ├── Client, custom error, ...
```

### Code generation

Given our described setup, I find the current configuration options puzzling, I managed to find a combination that suits us, but it also doesn't line up with the documentation so Im unsure if it's a bug.

I'm managing my own package, so the `swiftPackageManager` module type is off the table and I don't want my objects to be namespaced ruling out `embeddedInTarget(name:)` as well. This leaves me with the `other` option, however, the documentation for `other` says

```bash
You must specify the name of the module you will create in the `schemaName` property as this will be used in `import`statements of generated operation files.
```

but I don't have a module to import... If I specify `inSchemaModule` for the operations arg, the generated models don't import `schemaName`. Is this behaviour intentional, and can we consider it supported?

Having to go through so much trial and error leads me to my next question, would you consider introducing an overload on `ApolloCodegenConfiguration` with more granular options? Where namespace and imports are controlled directly, rather than being hidden behind a combination of configuration options.

```swift
ApolloCodegenConfiguration(
    input: .init(
        schemaPath: schemaURL.path,
        operationSearchPaths: [queriesURL.appendingPathComponent("*.graphql").path]
    ),
    output: .init(
        path: targetURL.path,
        namespace: "BestNamespace", // optional
        dependencies: ["BestModule1", "BestModule2"], // optional
        testMocks: .absolute(path: mocksURL.path)
    )
)
```

I see there's ongoing work on the codegen configuration (like [https://github.com/apollographql/apollo-ios/issues/2839](https://github.com/apollographql/apollo-ios/issues/2839) which might solve our particular setup), but there's always going to be some esoteric setup that won't be covered by one of the enum cases, the more granular configuration might be useful for complex projects.

**Comment by calvincestari** [comment]
Hi @martin-muller. `.other` sounds like the correct module type for your configuration and `schemaName` in the configuration, in this case, should be the name of the package you are managing.

> Having to go through so much trial and error leads me to my next question, would you consider introducing an overload on ApolloCodegenConfiguration with more granular options? Where namespace and imports are controlled directly, rather than being hidden behind a combination of configuration options.

I'm loathe to extend the configuration and make it more and more complicated, IMO it's way too big already. We understand there are workflows that could be better and that's where you'll see things like #2839 as we keep evolving codegen to support more use cases.
