### ISSUE TITLE
Cannot find ‘***Query’ in scope

### ISSUE THREAD

**Issue by CcMarioAsk** [apollographql/apollo-ios#2859]
### Summary

I integrated Apollo using Cocoapods. 
Pod 'Apollo','~> 1.0.7'

then cd to the directory where apollo-ios-cli is located, and execute init, fetch-schema, generate and other commands respectively.

Then add the automatically generated folders and internal files to the project.

Finally, apollo is called in the project to test the connection. 

But the reference to the automatically generated BankInfoQuery file reported an error, as shown in the following figure: 
<img width="1411" alt="3EC845B9-E469-45FD-AE3A-31D5DDBEB0F8" src="https://user-images.githubusercontent.com/126216074/222028830-beba38c9-5090-4050-bded-0b163b326eec.png">
<img width="1420" alt="A5A13570-9CC2-4051-B8DB-A9501D068366" src="https://user-images.githubusercontent.com/126216074/222028839-8af02cc7-a0bf-44ce-ae25-ca591637bd12.png">

when I removed the extension from the BankInfoQuery file, the error was eliminated. 
![96165019-4C8A-4A56-893B-C6F855B02A56](https://user-images.githubusercontent.com/126216074/222028894-f31094c9-0fb0-4bd5-a1bc-2f8494c1b121.jpeg)
<img width="1427" alt="6DC5CBD8-7A2B-4E23-9A27-9B782299D387" src="https://user-images.githubusercontent.com/126216074/222028904-e19e5088-8103-4094-b19f-08a2d0190039.png">

Does this have any effect on the removal of 'extension schemeName'' from the query.graphql file? Or in what way to prevent it from being generated automatically.
<img width="1051" alt="D65291DD-1284-471E-8B3C-4903EE747666" src="https://user-images.githubusercontent.com/126216074/222028973-22e5d26e-dbbb-46bb-a5db-d4a605e64df2.png">

In addition, if you call it in the way that ‘Fetch a query’ is recorded on https://www.apollographql.com/docs/ios/get-started, there will be an error of URLSessionClientError.sessionInvalidated.

### Version

1.0.7

### Steps to reproduce the behavior

When runing the code.

**Comment by calvincestari** [comment]
When the [`embeddedInTarget(name:)` module type](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#embedded-in-target) is used we wrap the schema module in a caseless enum to prevent type conflicts. In this case you probably need to use `schemaApi.BankInfoQuery()`, and remove the comment around `public extension schemaApi {`
