### ISSUE TITLE
Aliases causing import warnings

### ISSUE THREAD

**Issue by Austinpayne** [apollographql/apollo-ios#2860]
### Summary

Not so much a bug but submitting an issue to track since this will become an error in Swift 6.

When implementing a UUID custom scalar per [the example in the docs](https://www.apollographql.com/docs/ios/custom-scalars#generating-custom-scalar-types) the following warning can be observed:

<img width="623" alt="Screen Shot 2023-03-01 at 10 43 29 PM" src="https://user-images.githubusercontent.com/7528924/222341416-32c012f5-28e8-4795-b362-2c4747d79c66.png">

This is due to the fact that the alias source file imports `Foundation` but the generated source that uses the alias does not. For completeness, this is the source code implemented for the `UUID` type:

```swift
// @generated
// This file was automatically generated and can be edited to
// implement advanced custom scalar functionality.
//
// Any changes to this file will not be overwritten by future
// code generation execution.

import Foundation
import ApolloAPI

public extension QuantumAPI {
    /// Version 4 universally unique identifier
    typealias UUID = Foundation.UUID
}

extension Foundation.UUID: CustomScalarType {
    public init (_jsonValue value: JSONValue) throws {
        guard let uuidString = value as? String, let uuid = UUID(uuidString: uuidString) else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Foundation.UUID.self)
        }
        self = uuid
    }

    public var _jsonValue: JSONValue {
        uuidString
    }
}
```

### Version

1.0.7

### Steps to reproduce the behavior

Define a schema with a UUID custom scalar type and implement that type in terms of `Foundation.UUID`, i.e. follow example in docs: https://www.apollographql.com/docs/ios/custom-scalars#generating-custom-scalar-types

**Comment by AnthonyMDev** [comment]
I'd recommend that you use `@_exported` to export the Foundation type you need to whatever code is importing your Schema types!

Just change `import Foundation` to `@_exported import Foundation.UUID`!
