### ISSUE TITLE
Issue while using universal framework with Apollo installed via cocapods.

### ISSUE THREAD

**Issue by kc-bandari** [apollographql/apollo-ios#2866]
Hi,

I installed Apollo GraphQL using Cocoapods in my framework and facing issues with the universal framework

Here are the details.
My environment details,

```
xCode: 14.2
Mac OS: Ventura (13.2.1)
Apollo framework version: 1.0.7
```

Script used for generating the universal framework

```
#1. After then make a fresh directory directory 
UNIVERSAL_OUTPUTFOLDER=${BUILD_DIR}/${CONFIGURATION}-universal

# make sure the output directory exists
mkdir -p "${UNIVERSAL_OUTPUTFOLDER}"

# 2. Copy Device(arm64) Framework at fresh universal folder location 
cp -a "${BUILD_DIR}/${CONFIGURATION}-iphoneos/${PROJECT_NAME}.framework" "${UNIVERSAL_OUTPUTFOLDER}/"

#3. Copy Sim(x86_64) Frameworks's "MyFramework.swiftmodule" Folder Content & paste it at  Fat(x86_64 + arm64) Frameworks's  "MyFramework.swiftmodule" folder.
SIMULATOR_SWIFT_MODULES_DIR="${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/${PROJECT_NAME}.framework/Modules/${PROJECT_NAME}.swiftmodule/."
if [ -d "${SIMULATOR_SWIFT_MODULES_DIR}" ]; then
cp -R "${SIMULATOR_SWIFT_MODULES_DIR}" "${UNIVERSAL_OUTPUTFOLDER}/${PROJECT_NAME}.framework/Modules/${PROJECT_NAME}.swiftmodule"
fi

# Step 4. Create the universal binary file using lipo and place the combined executable in the copied framework directory
lipo -create -output "${UNIVERSAL_OUTPUTFOLDER}/${PROJECT_NAME}.framework/${PROJECT_NAME}" "${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/${PROJECT_NAME}.framework/${PROJECT_NAME}" "${BUILD_DIR}/${CONFIGURATION}-iphoneos/${PROJECT_NAME}.framework/${PROJECT_NAME}"

# Step 5. Copy output at Project Directory
cp -R "${UNIVERSAL_OUTPUTFOLDER}/${PROJECT_NAME}.framework" "${PROJECT_DIR}"

# Step 6. Open Project Directory
open "${PROJECT_DIR}"
```

The error while using the universal library is
`
Unsupported swift architecture
`

and the "lipo -info" command gives
`
Architectures in the fat file: MyFramework are: x86_64 arm64
`

**FYI**: Only the Apollo framework is installed in my framework

Thanks in Advance.

**Comment by calvincestari** [comment]
Hi @kc-bandari - is this something that was working previously in a 0.x version?

**Comment by kc-bandari** [comment]
Am not sure on "0.x". This is first time am trying and implemented using latest version of GraphQL.

**Comment by calvincestari** [comment]
We have a CI job that ensures that an xcframework can always be built from the library. I'm not sure about trying to do that with Apollo iOS as a CocoaPods dependency. Take a look at the steps we're taking in that job and see if it will give you what you need - https://github.com/apollographql/apollo-ios/blob/main/.circleci/config.yml#L139.

**Comment by kc-bandari** [comment]
I tried with empty workspace with zero code written. And the config file shared looks good.

**Comment by AnthonyMDev** [comment]
I'm not sure what the problem is here, but this looks to likely be something to do with your universal framework bundling process, rather than with Apollo in particular.

We don't really have the time to prioritize trying to investigate what could be the cause of this. Especially when there is currently little reason to think that this is a problem with Apollo specifically.

If you are able to figure out the root cause of this issue and it is in fact something actionable that we can improve in our codebase, please feel free to add more info and re-open this issue, but in the mean time you may have more luck on StackOverflow or another more general purpose help forum. Good luck!

**Comment by kc-bandari** [comment]
Thankyou for quick response. Figured the issue and it is not here. Sorry for that.
