### ISSUE TITLE
Apollo-iOS:1.0.7: Could not cast value of type 'Swift.Int64' to Custom Scalar type

### ISSUE THREAD

**Issue by RajendraNayak** [apollographql/apollo-ios#2871]
### Question

Hi Team, 
I am using 1.0.7 version of apollo-iOS

One of GraphQL Api sends data either in String or Double for this key "time" e.g "time" : "23131313133" or "time" : 23131313133

I implemented Custom Scalar like below however I am getting below error

**Could not cast value of type 'Swift.Int64' (0x7ff865e401f8) to 'AssetHistorySchema.DateTime' (0x105a96540).**

Here is what I implemented

<img width="730" alt="222718827-d811409d-82c3-4729-8488-1fc82c17418e" src="https://user-images.githubusercontent.com/3063882/224223250-2d6911e2-882a-4039-a3d1-3c8a6d24d455.png">

Auto Generated File
<img width="1013" alt="222718886-685c80d1-6951-4326-bbff-98bf180af473" src="https://user-images.githubusercontent.com/3063882/224223332-db74d2aa-f572-4f20-91cd-d6834c3a6534.png">

Upon debugging , I found that control is not coming inside below else if & else part

```
else if let value = value as? Double {
debugPrint("Not Reaching ...here ...Double(value)")
self.x = value
} else {
debugPrint("Not Reaching ...here ...other(value)")
self.x = 0
}
```

value of `__data` is coming as

`DataDict(_data: ["time": AnyHashable(1677747780001), "value": AnyHashable(30), "quality": AnyHashable()], _variables: nil)`

Please help me
Thanks in Adv

**Comment by AnthonyMDev** [comment]
Looks like we are already working on this in #2855. We will pick up the conversation there and continue trying to assist you with this issue.
