### ISSUE TITLE
Migrating to 1.0.7 using Cocoapods - Cannot find GraphQL schema. 

### ISSUE THREAD

**Issue by geeksweep** [apollographql/apollo-ios#2874]
### Question

I am using Xcode 14.1 and am attempting to migrate from 0.40.0 to 1.0.7 for iOS, using cocoapods. I already have a schema.json and API.swift files obviously, so just looking to upgrade. 

I was able to generate the apollo-codegen-config file using the following commands: 

`./Pods/Apollo/apollo-ios-cli init --schema-name schema.json --module-type embeddedInTarget --target-name API.swift`

When running:

`./Pods/Apollo/apollo-ios-cli generate  `

I get the error: 

_Error: A GraphQL schema could not be found. Please verify the schema search paths._

<img width="529" alt="Screen Shot 2023-03-13 at 7 44 54 PM" src="https://user-images.githubusercontent.com/1126840/224856394-75aafe4b-7f51-4e10-9514-744c9bd366a5.png">
<img width="387" alt="Screen Shot 2023-03-13 at 7 45 09 PM" src="https://user-images.githubusercontent.com/1126840/224856396-f56c1e67-8ac7-4a1d-b0d1-ba41b901d3a6.png">

the search paths seem to be set up out of the box but I must be missing something. Any help would be appreciated.

**Comment by calvincestari** [comment]
Hi @geeksweep - it looks like there are two problems:
1. `--schema-name schema.json`, `--schema-name` is not the name of your schema file but the name you want the schema module to be referred to as. It's confusing, which is why we have #2642 to correct it.
2. Since you're using `schema.json` I assume that is the name of your schema file? If so then you will need to change `schemaSearchPaths` to look for the `.json` extension file and not `.graphqls` files. Note though that `.json` is a pretty common filename extension and codegen might find other files that are not schema files which will cause another error. If you're going to use a json schema file then I recommend using an absolute path instead of the glob pattern.

**Comment by geeksweep** [comment]
@calvincestari Thanks for replying so quickly. I am brand new to GraphQL so just trying to figure everything out as I go. 

i made the following changes: 

`./Pods/Apollo/apollo-ios-cli init --overwrite --schema-name Schemas --module-type embeddedInTarget --target-name API.swift`

Below are the results: 

<img width="438" alt="Screen Shot 2023-03-13 at 9 32 50 PM" src="https://user-images.githubusercontent.com/1126840/224869286-d851afae-eb27-4c79-8f07-0604cb2a2e8d.png">
<img width="383" alt="Screen Shot 2023-03-13 at 9 32 56 PM" src="https://user-images.githubusercontent.com/1126840/224869287-3de04ffb-f4e4-4feb-ac8b-878ba4673963.png">

Running the command: 

`./Pods/Apollo/apollo-ios-cli generate `

returns back to the prompt with no errors or echoing of anything changing. I image I am still doing something wrong. I am not sure if the schema.json file needs to be changed now somehow or there is something else I am missing. 

the schema file starts off like this: 

 ```
 "__schema": {
    "description": null,
    "queryType": {
      "name": "Query"
    },
    "mutationType": {
      "name": "Mutation"
    },
    "subscriptionType": {
      "name": "Subscription"
    },
    "types": [
      {
        "kind": "OBJECT"
        ....
```

thanks for the help in advance!

**Comment by calvincestari** [comment]
It looks like your schema search path isn't quite right. Try with the full path to the schema json file, avoid the globstar (**).

I didn't see it the first time but the `name` property of `embeddedInTarget` is also wrong. It should be the name of the target you're adding the files to.

**Comment by geeksweep** [comment]
@calvincestari 

is the absolute path going to work when the app goes live or when someone else works on it with a different path? I see that being a problem later. I think 'Relative to Project' should still work. 

`./Pods/Apollo/apollo-ios-cli init --overwrite --schema-name Schemas --module-type embeddedInTarget --target-name MyAppTarget `

`./Pods/Apollo/apollo-ios-cli generate`

both of those still return to the prompt. 

<img width="659" alt="Screen Shot 2023-03-13 at 10 58 23 PM" src="https://user-images.githubusercontent.com/1126840/224881781-5cec49b9-c636-464a-bc9b-dbd135602a2e.png">

I get a bunch of errors (less than before) about Cannot find type 'GraphQLID' in scope and some other errors but again i'm sure something is still wrong as I get nothing at the prompt.

**Comment by calvincestari** [comment]
> is the absolute path going to work when the app goes live

This configuration is for code generation, which is a development stage workflow. Code generation also only runs on macOS, so this configuration file should not be deployed with your app, it won't be needed there.

> or when someone else works on it with a different path? I see that being a problem later. I think 'Relative to Project' should still work.

Correct, relative paths are better for shared workflows. My suggestion was to get you past the errors at which point you can tweak it for a more generic configuration.

> both of those still return to the prompt.

I'm not sure what you mean by this? Output from the `init` command should be to tell you that a configuration file was created. `generate` should just return to a new line unless there are errors; that output could certainly be improved to state that code generation was successful.

> I get a bunch of errors (less than before) about Cannot find type 'GraphQLID' in scope

Is this when you're building the project in Xcode or when you're running the `init` or `generate` commands?

**Comment by geeksweep** [comment]
@calvincestari 

it returns to the prompt (new line) when i do the generate command. But when building in Xcode is when i get the GraphQLID errors. It looks like most of those are in the API.swift file. Does the generate code automatically write to the API.swift file? I notice that it's also not updating an API method from one of my updated queries. 

I.e. i added "roles" to one of my queries 

```
query searchForMatches($search: SearchUserInput!) {
  usersBySearch(search: $search) {
    users {
      id
      name
      birthday
      photo
      roles {
        id
        name
      }
    }
  }
}
```

but in API.swift i get: 

```
public final class SearchForMatchesQuery: GraphQLQuery {
  /// The raw GraphQL definition of this operation.
  public let operationDefinition: String =
    """
    query searchForMatches($search: SearchUserInput!) {
      usersBySearch(search: $search) {
        __typename
        users {
          __typename
          id
          name
          birthday
          photo
        }
      }
    }
    """
```

The current Xcode errors are: 

Cannot find type 'GraphQLQuery' in scope
Cannot find type 'ResultMap' in scope,...
etc etc 

Am i supposed to import more than just Apollo?

**Comment by calvincestari** [comment]
> But when building in Xcode is when i get the GraphQLID errors. It looks like most of those are in the API.swift file. Does the generate code automatically write to the API.swift file?

I think the key might be in "API.swift" - is that the generated file you got from the 0.x version code generator? If so then it is not compatible with 1.x, you must generate new models. Looking at the config file again the generated models should be going to `./Schemas`; are you getting files generated there that match your schema and operations?

**Comment by AnthonyMDev** [comment]
`ResultMap` is from the 0.x version and has been completely removed in 1.0. If you are getting `Cannot find type 'ResultMap' in scope` errors, it seems like you have some code from the old version of the library still in your repo.

**Comment by ArunVicky001** [comment]
@geeksweep 
how did you solve the issue?
