### ISSUE TITLE
MIgrate SwiftUI preview to 1.0.7

### ISSUE THREAD

**Issue by otusweb** [apollographql/apollo-ios#2876]
### Question

I have a swiftUI app where for previews I used the apollo generated objects initializer that took the value as parameter ie:`WorkoutsForCategoryQuery.Data.Workout.Trainer(id: "1", name: "Bob Trainer", photo: trainerImage)`.

Those initializer have been removed as part of migrating to apollo 1.0.

I read that those initialiser are somewhat available in the testframework, so i added Apollo/ApolloTestSupport to my pod for my main target in hopes to solve my issue.

But now my app won't compile because of `/Users/otusweb/Projects/Rocktrainer/RockTrainerSwift/Generated/GraphCMS/mocks/Asset+Mock.graphql.swift:10:57 'Asset' is ambiguous for type lookup in this context` errors.

How can I use those interface for my swiftUI previews without getting all those errors?

My codegen config:
```
{
  "schemaName": "GraphCMSAPI",
  "options": {
    "cocoapodsCompatibleImportStatements": true,
    "pruneGeneratedFiles": true
  },
  "input": {
    "operationSearchPaths": ["**/*.graphql"],
    "schemaSearchPaths": ["**/*.graphqls"]
  },
  "output": {
    "testMocks": {
      "absolute": {
        "path": "./Generated/GraphCMS/mocks"
      }
    },
    "schemaTypes": {
      "path": "./Generated/GraphCMS",
      "moduleType": {
        "embeddedInTarget": {
          "name": "RockTrainer"
        }
      }
    },
    "operations": {
      "absolute": {
        "path": "./Generated/GraphCMS"
      }
    }
  },
  "schemaDownloadConfiguration": {
    "downloadMethod": {
      "introspection": {
        "endpointURL": "https://api-us-east-1.graphcms.com/v2/ck2c5vbdx1n3a01gl6bp32u5v/master",
        "httpMethod": {
          "POST": {}
        },
        "includeDeprecatedInputValues": false,
        "outputFormat": "SDL"
      }
    },
    "downloadTimeout": 60,
    "headers": [],
    "outputPath": "./Generated/GraphCMS/schema.graphqls"
  }
}
```

**Comment by sgade** [comment]
With the Apollo 1.0 release, the way you define mock objects changed. See the [related documentation](https://www.apollographql.com/docs/ios/testing/test-mocks/#mocking-graphql-responses-with-generated-test-mocks).

In my experience, this is what you want to use for preview objects as well.

**Comment by otusweb** [comment]
I'm indeed using the new mock infrastructure but running into a bunch of compilation issues.
I changed my project to using SPM to import the generated code from the apollo CLI, but now when I try create those mock i'm slowly working through the compiulation issues.
The latest one:
```

    static let trainerImage = Mock<Asset>(handle: "QJ9obgsLTIaambd2tqFh", id: "2")
    static let trainer = Mock<Trainer>(id: "1", name: "Bob Trainer", photo: trainerImage)
    
    static let workouts = [Mock<Workout>(duration: 1500, id: "1",
                                         title: "Abs fun",
                                         trainer: trainer),
                           Mock<Workout>(duration: 1500, id: "2",
                                         title: "Abs fun * 2",
                                         trainer: trainer),
                           Mock<Workout>(duration: 1500, id: "3",
                                         title: "Abs fun * 3",
                                         trainer: trainer)]
    static let queryData = WorkoutsForCategoryQueryData(workouts: WorkoutsForCategoryQuery.Data.from(workouts))
```
=> Argument type '[Mock<Workout>]' does not conform to expected type 'AnyMock'

How do i get this line to work?

**Comment by sgade** [comment]
The creation from a mock always expects a Mock, not data directly. The array is the latter. I suppose the `WorkoutsForCategoryQuery.Data` objects expects other arguments than an array. 

Try creating a `Mock<WorkoutsForCategoryQueryData>` with the correct arguments.

**Comment by AnthonyMDev** [comment]
Mocks should work for you, as @sgade stated. I am a bit confused why you are getting the `=> Argument type '[Mock]' does not conform to expected type 'AnyMock'` error though.

However, the addition of generated initializers for your models is nearly complete and will be in the 1.1 release coming very soon! I think that should resolve your issue as well!

It's being tracked in https://github.com/apollographql/apollo-ios/issues/2551. Currently you can beta test this functionality in the release/1.1 branch. We'd love you to try it out and give us your feedback!

**Comment by otusweb** [comment]
Unfortunately, I tried to update to 1.1 (set the branch to be release/1.1 in Xcode SPM), but the CLI still say that it is version 1.0.7 (I cleared derived data folder, then did "install CLI").
Also, if i run the script to generate the code, I don't see any difference with the code generated with v1.0.7. So I'm assuming it's indeed the wrong version :-(

So I can't generate the code with that version i'm unsure of what the issue is and realize i'm not providing great info on the issue either :-(
![Screenshot 2023-03-21 at 14 23 29](https://user-images.githubusercontent.com/1069914/226619353-8df6f05e-beb7-44a7-a264-904e9ac7ca1b.png)

![Screenshot 2023-03-21 at 14 24 35](https://user-images.githubusercontent.com/1069914/226619552-8c5ebc3a-5fb9-4234-8ecd-2d57f65098d2.png)

**Comment by AnthonyMDev** [comment]
Yes, I haven't bumped the version number yet on the branch, so that's not a good indication.

@otusweb You will need to update your codegen configuration to enable generating initializers currently. I haven't written the docs for this yet, as it's still in progress, but the new config options are on the `ApolloCodegenConfiguration` struct in the `release/1.1` branch.

**Comment by otusweb** [comment]
Thanks, I tried to find the info in the doc and found `selectionSetInitializers` but I don't think i understand enough of the code to know what to do correctly. So for now I moved back to 0.53. I'll wait for the official release of 1.1

Thanks for the help

**Comment by AnthonyMDev** [comment]
1.1 has been released! Examples for how to configure the `selectionSetInitializers` [can be found in our docs here](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#output-options).
