### ISSUE TITLE
invalid type in json write (__swiftvalue)

### ISSUE THREAD

**Issue by Skyzwing** [apollographql/apollo-ios#2882]
### Question

I try to JSONSerialization response data but it’s not work

This is error when code compile JSONSerialization
`invalid type in json write (__swiftvalue)`
This is my code

```
func serialization(data: JSONObject) {
    if let object = try JSONSerialization.data(withJSONObject: data) {
        print(object)
    }
}
```

**Comment by AnthonyMDev** [comment]
Hi @Skyzwing. This doesn't provide enough explanation of the problem for us to assist. Our JSONSerialization is meant to be used internally by our client's networking layer. I'm not exactly sure what context you are using it in here or what data you are passing to it that is causing it to throw an error. Please use our bug reporting template to provide a bug report with clear reproduction steps. You will be much more likely to get the help you need if we have all the relevant information.

Thank you
