### ISSUE TITLE
How to map different response to one structure?

### ISSUE THREAD

**Issue by bhavinbhadani-pie** [apollographql/apollo-ios#2909]
### Question

I want to know how to map different result response to one structure object? Like I am getting same response from different query and type of the response different but the fields are same and I am trying to map it into a single structure. For e.g. `IDQuery.Data.DataByID.ResultData` and `Query.Data.AllData.ResultData` gives the same object data and I am trying to map it into some structure. So, how to do that?

**Comment by AnthonyMDev** [comment]
This is definitely a supported functionality! You'll want to use Named Fragments. [You can read the docs about that here](https://www.apollographql.com/docs/ios/fetching/fragments)!
