### ISSUE TITLE
Using more than one JSON schema

### ISSUE THREAD

**Issue by ilkeyucel** [apollographql/apollo-ios#2911]
### Question

Hello, I migrated SDK to the latest version following the migration guide.

I have two `JSON schema` and when I ran the `./Pods/Apollo/apollo-ios-cli generate`, I got the following error:
` Error: Schema search paths can only include one JSON schema definition.`

What should I do to use 2 JSON schemas in the project?

apollo-ios SDK version: 1.0.7
Xcode version: 14.2
Package manager: Cocoapods

apollo-codegen-config file:
<img width="869" alt="Screenshot 2023-03-29 at 18 50 33" src="https://user-images.githubusercontent.com/111274227/228595524-426bf14a-ac83-46f0-b113-6234d9640af4.png">

Thanks in advance!

**Comment by calvincestari** [comment]
Hi @ilkeyucel - two JSON schema files is not supported so currently there is no way to use both of the JSON files you have. You mentioned migrating though..were you able to use both in the 0.x version? Do the files describe two different GraphQL schemas that you're wanting to merge or is one a schema and the other an extension of it?

**Comment by AnthonyMDev** [comment]
Furthering @calvincestari's response. You can't run codegen over two schemas at the same time. Each Apollo Client and it's corresponding cache is implemented to be used with only one schema at a time. If you want to use two different schemas in your application, you can run codegen twice -- once for each schema -- and then create two separate `ApolloClient` instances to make requests to each of your separate services.

But I think the best approach here is actually to create a supergraph that combines both of your subgraph schemas into a single schema using Graph OS. If you are interested in learning more about this, you can start with [this tutorial](https://www.apollographql.com/tutorials/getting-started-with-graphos).

**Comment by calvincestari** [comment]
Got it @ilkeyucel. That looks like it's doing separate code generation executions though, which is different to using multiple schemas in a single codegen execution. You can do the same today with 1.0 but those build phases will need to change to be using the CLI vs. the deprecated build script.
