### ISSUE TITLE
Inline fragment accessors not working

### ISSUE THREAD

**Issue by yonaskolb** [apollographql/apollo-ios#2915]
### Summary

We're having an issue in the 1.1.0 beta where accessing an inline fragment returns nil, where it used to work.
This model is hydrated using json data and is using the new `RootSelection.init(data: JSONObject, variables: GraphQLOperation.Variables?)`.
It decodes successfully but then accessing a deeply nested property as an inline fragment (using `asNavListItem` below) returns nil.
Looking at the implementation of `_asInlineFragment()` it looks like it relies on `__fullfilled` containing the fragment type, but it doesn't. You can see even the generated property initializer doesn't set that in the `__fullfilled`. 

```swift
@inlinable public func _asInlineFragment<T: SelectionSet>() -> T? {
    guard __data.fragmentIsFulfilled(T.self) else { return nil }
    return T.init(_dataDict: __data)
  }
```
```swift
@usableFromInline func fragmentIsFulfilled<T: SelectionSet>(_ type: T.Type) -> Bool {
    guard let __fulfilledFragments = _data["__fulfilled"] as? Set<ObjectIdentifier> else {
      return false
    }
    return __fulfilledFragments.contains(ObjectIdentifier(T.self))
  }
```

I don't understand how the system works so not sure how to approach it, and may be totally off base with my assumptions.

Our generated type for reference:
```swift
some parent type
...
     public struct Item: ShopAPI.SelectionSet {
          public let __data: DataDict
          public init(_dataDict: DataDict) { __data = _dataDict }

          public static var __parentType: ApolloAPI.ParentType { ShopAPI.Unions.NavListSectionItem }

          public var asNavListItem: AsNavListItem? { _asInlineFragment() }

          public init(
            __typename: String
          ) {
            self.init(_dataDict: DataDict(data: [
              "__typename": __typename,
              "__fulfilled": Set([
                ObjectIdentifier(Self.self)
              ])
            ]))
          }

          /// Section.Body.AsNavListSection.Item.AsNavListItem
          ///
          /// Parent Type: `NavListItem`
          public struct AsNavListItem: ShopAPI.InlineFragment {
            public let __data: DataDict
            public init(_dataDict: DataDict) { __data = _dataDict }

            public typealias RootEntityType = NavAccordion.Section.Body.AsNavListSection.Item
            public static var __parentType: ApolloAPI.ParentType { ShopAPI.Objects.NavListItem }

            public var badge: String? { __data["badge"] }
            public var badgeColor: String? { __data["badgeColor"] }
            public var badgeTextColor: String? { __data["badgeTextColor"] }
            public var backgroundImageApp: String? { __data["backgroundImageApp"] }
            public var href: String? { __data["href"] }
            public var icon: String? { __data["icon"] }
            public var id: ShopAPI.ID { __data["id"] }
            public var isBold: Bool? { __data["isBold"] }
            public var isHeading: Bool? { __data["isHeading"] }
            public var text: String { __data["text"] }
            public var textColor: String? { __data["textColor"] }

            public struct Fragments: FragmentContainer {
              public let __data: DataDict
              public init(_dataDict: DataDict) { __data = _dataDict }

              public var navListItem: ShopAPI.NavListItem { _toFragment() }
            }

            public init(
              badge: String? = nil,
              badgeColor: String? = nil,
              badgeTextColor: String? = nil,
              backgroundImageApp: String? = nil,
              href: String? = nil,
              icon: String? = nil,
              id: ShopAPI.ID,
              isBold: Bool? = nil,
              isHeading: Bool? = nil,
              text: String,
              textColor: String? = nil
            ) {
              self.init(_dataDict: DataDict(data: [
                "__typename": ShopAPI.Objects.NavListItem.typename,
                "badge": badge,
                "badgeColor": badgeColor,
                "badgeTextColor": badgeTextColor,
                "backgroundImageApp": backgroundImageApp,
                "href": href,
                "icon": icon,
                "id": id,
                "isBold": isBold,
                "isHeading": isHeading,
                "text": text,
                "textColor": textColor,
                "__fulfilled": Set([
                  ObjectIdentifier(Self.self),
                  ObjectIdentifier(NavAccordion.Section.Body.AsNavListSection.Item.self),
                  ObjectIdentifier(NavListItem.self)
                ])
              ]))
            }
          }
        }
      }
```

### Version

1.1.0-beta

### Steps to reproduce the behavior

let data: JSONObject = loadJSON()
let model = Model(data: dictionary)
let fragment = model.property.property.asSomethingFragment() // returns nil

**Comment by AnthonyMDev** [comment]
Thanks for the report! I've got a lot of unit tests in place for this behavior, and they are all passing. There must be some edge case we aren't testing in which this bug is appearing, but I'm not able to deduce what that could be from the sample you've given here. In order to track this down, I'm going to need a better reproduction case.

If you are unable to post a more significant sample of your code publicly, do you think you could send me an email with your project or some reproduction case. At the least, I need a schema, the operation and fragment definitions used, and a sample of the JSON you are using to initialize the object. Then I should be able to figure this out.

**Comment by AnthonyMDev** [comment]
Ooooh, you know what, looking at this again, I think I might have an idea what's causing it. I'm going to do some research and see if I can create a reproduction to confirm my suspicions.

**Comment by yonaskolb** [comment]
#2918 fixes the issue, thank you!

**Comment by AnthonyMDev** [comment]
Awesome! Glad to hear that!

**Comment by calvincestari** [comment]
@ay8s - can you discern what is missing for conformance? If you let Xcode add the protocol stubs, what is missing from what's already there?

**Comment by ay8s** [comment]
Realized I didn't check the error below which is likely the cause of the InlineFragment error as asking for the stubs adds ```public typealias RootEntityType = <#type#>```

![Screenshot 2023-04-12 at 10 36 22 AM](https://user-images.githubusercontent.com/1058408/231538764-64abcd58-7052-4b07-9020-3150091bfde6.png)

**Comment by AnthonyMDev** [comment]
This is almost certainly the same issue as @2949 that I'm working on today. I'll let you know when that is resolved @ay8s and you can tell me if it corrects your problems!

**Comment by ay8s** [comment]
My bad, I overlooked that second error. Happy to test it once you've got a solution 👍

**Comment by AnthonyMDev** [comment]
There was previously a bug with the way we calculated `fulfilledFragments`. That bug has been fixed and this issue was closed. @ArunVicky001  The problem you are encountering in your linked comment is unrelated.
