### ISSUE TITLE
How to disable introspection in ios client 

### ISSUE THREAD

**Issue by ygag-minna** [apollographql/apollo-ios#2922]
### Question

How to call introspection disabled apis in iOS client.

**Comment by calvincestari** [comment]
@ygag-minna please provide more detail on what query you're trying to request, the response, what you expect, etc. Working project samples demonstrating the problem help too.

If introspection is disabled on your server the client won't be able to make the query.

**Comment by ygag-minna** [comment]
Thank you for your reply. 

In my iOS app I am able to query to my development server and getting expected responses. But in corresponding production server back end team disabled introspection as per the recommendation (https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/#:~:text=Turning%20off%20introspection%20in%20production,NODE_ENV%20!%3D%3D) 
In production server I am not getting response in my iOS app. Here is code of my client 
```

private lazy var store: ApolloStore = {
    // The cache is necessary to set up the store, which we're going to hand to the provider
    let cache = InMemoryNormalizedCache()
    return ApolloStore(cache: cache)
  }()
    
  private lazy var provider: NetworkInterceptorProvider = {
        
        let configuration = URLSessionConfiguration.default

        let client = URLSessionClient(sessionConfiguration: configuration, callbackQueue: nil)
        return NetworkInterceptorProvider(
          client: client, shouldInvalidateClientOnDeinit: true, store: store)
    }()
    
  // To prevent multiple initialization
  private init() {
      // Intentionally unimplemented...
  }
  func apolloClient() -> ApolloClient {
    let url = URL(string: graphQLType.getURL())!
      provider.graphQLType = graphQLType

    let requestChainTransport = RequestChainNetworkTransport(
      interceptorProvider: provider, endpointURL: url)

    return ApolloClient(
      networkTransport: requestChainTransport,
      store: store)
  }
```
