### ISSUE TITLE
test: Fix `test__performMutation_givenPublishResultToStore_false_doesNotPublishResultsToStore`

### ISSUE THREAD

**Issue by tokizuoh** [apollographql/apollo-ios#2929]
### Summary

`ApolloClientOperationTests.test__performMutation_givenPublishResultToStore_false_doesNotPublishResultsToStore()` is not a valid test for the following reasons and needs to be fixed.

- `NoCache()` is called in the initializer despite the test to check for the presence of cache.
  - https://github.com/apollographql/apollo-ios/blob/10bc14b66ac677a70ad4ec9fe3bd04c82461beed/Tests/ApolloTests/ApolloClientOperationTests.swift#L36
- If I change `publishResultToStore` to true, the test still passes. Essentially, the test should fail because it is cached.
  - https://github.com/apollographql/apollo-ios/blob/10bc14b66ac677a70ad4ec9fe3bd04c82461beed/Tests/ApolloTests/ApolloClientOperationTests.swift#L80
  - I have confirmed that it is failing with the `JSONResponseParsingInterceptor`, but I do not know the detailed cause.
     - https://github.com/apollographql/apollo-ios/blob/10bc14b66ac677a70ad4ec9fe3bd04c82461beed/Sources/Apollo/JSONResponseParsingInterceptor.swift#L64-L69

### Version

1.1.0

### Steps to reproduce the behavior

test `test__performMutation_givenPublishResultToStore_false_doesNotPublishResultsToStore()`.

### Logs

```shell
Error caught by the `JSONResponseParsingInterceptor`.


po error
▿ Variable "review" was not provided.
     ▿ object : 1 element
       ▿ 0 : 2 elements
         - key : "message"
         ▿ value : AnyHashable("Variable \"review\" was not provided.")
           - value : "Variable \"review\" was not provided."
```
```


### Anything else?

_No response_

**Comment by calvincestari** [comment]
@tokizuoh, do you know if this is a regression, i.e.: did it work as expected in a prior version?

**Comment by tokizuoh** [comment]
Thanks for your reply!

No, I don't know if it works with the previous version. I will start looking into that and see what I can find out.

**Comment by tokizuoh** [comment]
## Summary

This is occurring from past versions and is not a regression.

---

I confirmed by reverting back to version 1.0.0, but it appears that unintended behavior is occurring. 
Specifically, when setting the `publishToStore` argument of `ApolloClient.perform` to true and using the default cache in `ApolloStore`, the expected behavior is for the mutation to be cached after execution. However, in reality, the mutation is not cached and results in an error.

### Behavior check for each version (1.0.0-1.1.1)

```diff
diff --git a/Tests/ApolloTests/ApolloClientOperationTests.swift b/Tests/ApolloTests/ApolloClientOperationTests.swift
index e1913cb9..2430241c 100644
--- a/Tests/ApolloTests/ApolloClientOperationTests.swift
+++ b/Tests/ApolloTests/ApolloClientOperationTests.swift
@@ -32,9 +32,11 @@ final class ApolloClientOperationTests: XCTestCase {
   class MockStore: ApolloStore {
     var publishedRecordSets: [RecordSet] = []
 
-    init() {
-      super.init(cache: NoCache())
-    }
+    
+    // Commented out because I want to test that it is cached.
+//    init() {
+//      super.init(cache: NoCache())
+//    }
 
     override func publish(records: RecordSet, identifier: UUID? = nil, callbackQueue: DispatchQueue = .main, completion: ((Result<Void, Swift.Error>) -> Void)? = nil) {
       publishedRecordSets.append(records)
@@ -77,7 +79,7 @@ final class ApolloClientOperationTests: XCTestCase {
 
     // when
     self.client.perform(mutation: mutation,
-                        publishResultToStore: false,
+                        publishResultToStore: true,
                         resultHandler: resultObserver.handler)
 
     self.wait(for: [serverRequestExpectation, performResultFromServerExpectation], timeout: 0.2)
```

| Version | Does it fail with the JSONResponseParsingInterceptor? | Error Description |
| --- | --- | --- |
| 1.1.1 | Yes | 1 |
| 1.1.0 | Yes | 2 |
| 1.0.7 | Yes | 1 |
| 1.0.6 | Yes | 2 |
| 1.0.5 | Yes | 2 |
| 1.0.4 | Yes | 2 |
| 1.0.3 | Yes | 1 |
| 1.0.2 | Yes | 2 |
| 1.0.1 | Yes | 2 |
| 1.0.0 | Yes | 2 |

#### Error Description

https://github.com/apollographql/apollo-ios/blob/794ddd4faa6060234493073e63d92c62dce04d92/Sources/Apollo/JSONResponseParsingInterceptor.swift#L65

##### 1

```
(lldb) po error
    ▿ Variable "episode" was not provided.
      ▿ object : 1 element
        ▿ 0 : 2 elements
          - key : "message"
          ▿ value : AnyHashable("Variable \"episode\" was not provided.")
            - value : "Variable \"episode\" was not provided."
```

##### 2

```
▿ Variable "review" was not provided.
      ▿ object : 1 element
        ▿ 0 : 2 elements
          - key : "message"
          ▿ value : AnyHashable("Variable \"review\" was not provided.")
            - value : "Variable \"review\" was not provided."
```

### What about prior 0.53.0?

I changed the 0.53.0 code as in the following diff and ran the test. I really want it to go into SUCCESS, but it goes into FAILURE, so I consider this unintended behavior.


```diff
diff --git a/Tests/ApolloTests/ApolloClientOperationTests.swift b/Tests/ApolloTests/ApolloClientOperationTests.swift
index 56e40d9e..077c6128 100644
--- a/Tests/ApolloTests/ApolloClientOperationTests.swift
+++ b/Tests/ApolloTests/ApolloClientOperationTests.swift
@@ -49,9 +49,16 @@ final class ApolloClientOperationTests: XCTestCase, CacheDependentTesting, Store
     }
     let performResultFromServerExpectation = resultObserver.expectation(description: "Mutation was successful") { _ in }
 
-    self.client.perform(mutation: mutation, publishResultToStore: false, resultHandler: resultObserver.handler)
+    self.client.perform(mutation: mutation, publishResultToStore: true, resultHandler: resultObserver.handler)
 
     self.loadFromStore(query: mutation) {
+      switch $0 {
+      case .success(let value):
+        XCTAssertNotNil(value.data)  // Expect not to be nil.
+      case .failure(_):
+        XCTFail()  // It comes down to this.
+      }
+
       try XCTAssertFailureResult($0) { error in
         switch error as? JSONDecodingError {
         // expected case, nothing to do

```

**Comment by calvincestari** [comment]
Hi @tokizuoh, I've got PR #2952 up to fix this issue. I think it got broken in the `1.0` release; it's working again and will fail if you set `publishResultToStore` to `true`.

> I have confirmed that it is failing with the JSONResponseParsingInterceptor, but I do not know the detailed cause.

The test was incorrect because the selection set had arguments but when executed there were no values being passed for them so it would silently fail, breaking the interceptor chain and never actually reaching the `CacheWriteInterceptor`. If the `CacheWriteInterceptor` is never called then the test will always 'succeed'.

> NoCache() is called in the initializer despite the test to check for the presence of cache.

This doesn't matter since we're not actually using the backing cache in `MockStore`. The overridden `publish` method and storing it's results is all we care about.

**Comment by tokizuoh** [comment]
Hi @calvincestari.

> This doesn't matter since we're not actually using the backing cache in MockStore. The overridden publish method and storing it's results is all we care about.

Oh! You're right, I misunderstood.
  
I understand that there is no problem with `NoCache` since publish is called in `CacheWriteInterceptor` as follows.

https://github.com/apollographql/apollo-ios/blob/794ddd4faa6060234493073e63d92c62dce04d92/Sources/Apollo/CacheWriteInterceptor.swift#L60-L62

...

Thanks for the fixing in #2952. I really wish I could have fixed it myself, but you were very helpful, thank you.
