### ISSUE TITLE
Version 1.1.0 is not available on CocoaPods

### ISSUE THREAD

**Issue by simonliotier** [apollographql/apollo-ios#2935]
### Summary

Hello, it seems that the version `1.1.0` has not been published on CocoaPods. The last available version is `1.0.7`.

![image](https://user-images.githubusercontent.com/359843/230331850-26f2de12-78db-425f-814e-99345875101c.png)

### Version

1.1.0

### Steps to reproduce the behavior

- Add `pod "Apollo"` to your Podfile.
- Run `pod update`.

The installed version is 1.0.7.

**Comment by calvincestari** [comment]
`1.1.1` is now [available on CocoaPods](https://cocoapods.org/pods/Apollo#changelog). Thanks for raising the issue @simonliotier.
