### ISSUE TITLE
Cannot see `InstallCLI` in Xcode 14.3

### ISSUE THREAD

**Issue by shibotong** [apollographql/apollo-ios#2945]
### Question

Hi, I was trying to generate GraphQL code with cli. I have used this before in Xcode 14.2. After updating to 14.3, when I try to use `./apollo-ios-cli generate`, the command line shows `zsh: no such file or directory: ./apollo-ios-cli`

<img width="655" alt="Screenshot 2023-04-09 at 10 35 35 am" src="https://user-images.githubusercontent.com/44807628/230748310-46b48bd5-4b1f-4385-88ab-5ed3d8cd654f.png">
<img width="396" alt="Screenshot 2023-04-09 at 10 35 49 am" src="https://user-images.githubusercontent.com/44807628/230748315-b596a5ea-d16c-4662-8e55-a9bf565d4d7e.png">

Then I tried to add Apollo in another project, while the `InstallCLI` doesn't exist.
<img width="620" alt="Screenshot 2023-04-09 at 10 36 49 am" src="https://user-images.githubusercontent.com/44807628/230748338-385c65a7-56e7-4b8a-ac2e-86a2c5c22b41.png">

<img width="383" alt="Screenshot 2023-04-09 at 10 36 59 am" src="https://user-images.githubusercontent.com/44807628/230748340-1799f8c6-4c77-445f-b221-f60d91d05612.png">

I'm not sure if its the Xcode issue or other issue

**Comment by calvincestari** [comment]
Thanks for reporting this @shibotong. It's duplicate of https://github.com/apollographql/apollo-ios/issues/2919 which we've left open until we definitively know what the cause/solution is. You should subscribe to that issue for updates.
