### ISSUE TITLE
Issue while making manual cli

### ISSUE THREAD

**Issue by nbnitin** [apollographql/apollo-ios#2959]
### Summary

@_exported @testable import ApolloAPI
           ~~~~~~~~~~       ^
           
[3/9] Linking libApollo-Dynamic.dylib
make: *** [build] Error 1

make build cli -> command in terminal

versio 1.1.2

### Version

1.1.2

### Steps to reproduce the behavior

open terminal

go to download code in 1.1.2 and run command in terminal make build cli 

### Logs

_No response_

### Anything else?

_No response_

**Comment by calvincestari** [comment]
Hi @nbnitin. You're not using the right command, you're missing a `-` between build and `cli`. The command is in the [makefile](https://github.com/apollographql/apollo-ios/blob/main/makefile). Use `make build-cli` and it should work.
