### ISSUE TITLE
Generated code is sometimes incomplete when using @include directive

### ISSUE THREAD

**Issue by alexisbronchart** [apollographql/apollo-ios#2962]
### Summary

Codegen seems to omit some type when using @include directive on top level fragment.

### Version

1.1.2

### Steps to reproduce the behavior

Codegen seems to leave this line incomplete when using @include directive on top level fragment (in the definition of `IfFetchParticularEntity`):

`public typealias RootEntityType = `

```
query SomeQuery(
  $id: ID!
  $fetchParticularEntity: Boolean!
) {
  ...ParticularEntityFragment @include(if: $fetchParticularEntity)
  foo(id: $id) {
    ...SomeFragment
  }
}

```

Codegen doesn't crash or anything but the resulting code can't compile.

### Anything else?

I had no issue in version 1.0.7

**Comment by AnthonyMDev** [comment]
Oh hmmm... thanks for the report. I'm not sure how to reproduce this currently. Could you provide me with your schema and the contents of your fragments? If you can't post them publicly, you could e-mail them to me privately. If that is not possible, please try to give me any info you think is relevant about the shape of your query fragments to help me determine whats triggering this edge case.

**Comment by alexisbronchart** [comment]
Hey sorry for the delay, unfortunately I no longer have access to the code that was producing this issue but I’ll try to repro asap with something else and post my findings!

**Comment by AnthonyMDev** [comment]
PR is up for the fix on this! Thanks for the report!
