### ISSUE TITLE
[CacheKeyInfo] Cache + Alias doesn't work

### ISSUE THREAD

**Issue by wow-such-amazing** [apollographql/apollo-ios#2979]
### Summary

Hey folks!

We have a type in our schema that doesn't have an `id` property, but has an `aggregationId` instead.

We are adding an alias `id` to align it with other identifiers. We are also expecting that this will ensure proper caching of that object.

Our implementation of the `CacheKeyInfo` is the following:
```
enum SchemaConfiguration: ApolloAPI.SchemaConfiguration {
    static func cacheKeyInfo(for type: Object, object: JSONObject) -> CacheKeyInfo? {
        let id: String? = object["id"] as? String ?? object["_id"] as? String
        
        guard let id = id else {
            return nil
        }

        return CacheKeyInfo(id: id)
    }
}
```

However it doesn't work. When I log the `object` I can see that it has an `aggregationId` property, but it doesn't have an `id` property. 

I guess it's legit as we are dealing with raw json as far as I understand. However it's a bit unclear how to approach this. 

My assumption is that we need to add `aggregationId` to the code as well to have it like this:
```
let id: String? = object["id"] as? String ?? object["_id"] as? String ?? object["aggregationId"] as? String
```

But I would like to verify that it works as expected. And if it does then I think it would worth adding a point about alias to the cache documentation 👀 

Cheers!

### Version

1.0.7

### Step 1

Use `SQLiteNormalizedCache` and implement the `CacheKeyInfo` like this:
```
static func cacheKeyInfo(for type: Object, object: JSONObject) -> CacheKeyInfo? {
    let id: String? = object["alias_id"] as? String

    guard let id = id else {
        return nil
    }

    return CacheKeyInfo(id: id)
}
```

### Step 2

Define a fragment that has an `alias_id` alias for some property. For example like this should work:
```
fragment DogFragment on Dog {
    breed {
        ...BreedFragment
    }
}

fragment BreedFragment on Breed {
    alias_id: name
}
```

### Step 3

Fetching data from server works fine and `CacheKeyInfo` is able to retrieve `alias_id`. 

However if we disable the network and rely on cache then we won't be able to retrieve id using `alias_id`.

### Workaround - Edit: Actually not

I thought it is possible to workaround the problem by providing the field name behind the alias. In our case that's `name`:
```
let id: String? = {
    if let id = object["alias_id"] as? String {
        return id
    } else {
        if type.typename == "Breed" {
            return object["name"]
        } else {
            return nil
        }
    }
}()
```

But that didn't work in our project unfortunately.

**Comment by wow-such-amazing** [comment]
Hm, I've been testing the workaround and it doesn't solve my problem actually. I will post updates as soon as I find anything 🕵️

**Comment by wow-such-amazing** [comment]
After investigation it seems like the problem lies in the moment when parent entry is being added to the store. Upon receiving a json `aggregation` is present. But after storing to database `aggregation` is stored as `null`. Not sure why this happens 🤔

**Comment by AnthonyMDev** [comment]
This is actually directly related to an underlying issue that @calvincestari and I were talking about last week. I'm in the process of working on a solution to that. Thank you so much for this issue, as it highlights more use cases which we need to address while resolving this problem. Stay tuned for an update soon!

**Comment by wow-such-amazing** [comment]
@AnthonyMDev I'm still debugging on my side, and it could be actually our local problem 😓 

Basically we have 2 properties to fetch same objects. For example:
```
query Objects {
  Objects {
    recommended {
      ...ObjectFragment
    }
    regular {
      ...ObjectFragment
    }
  }
}
```

And I think it misses the field when being returned through recommended. And probably it messes the database 😢 Need to confirm though 🕵️

**Comment by wow-such-amazing** [comment]
@AnthonyMDev So far looks like our local issue. I removed fetching `recommended` and it now works properly. Will need to find a way on our side to fix this 🤯 

It was a long day 😄 

Thanks for a quick response!

**Comment by calvincestari** [comment]
Re-opening this so we can cater for this edge case in the fix @AnthonyMDev spoke about - https://github.com/apollographql/apollo-ios/issues/2979#issuecomment-1520557028.

**Comment by wow-such-amazing** [comment]
> I think the appropriate workaround right now is as you suggested

@AnthonyMDev  The issue is actually on my side is not about the cache key, but about the fact that same object is fetched within 2 different places. And one of the properties gets overriden 🙃 

So now I probably will need to create a different fragment or maybe use a `skip` or `include` directive to prevent fetching this field when it's being returned as `nil`

**Comment by AnthonyMDev** [comment]
The underlying issue should be resolved now.
