### ISSUE TITLE
Build failures with Apollo pod 0.8.0

### ISSUE THREAD

**Issue by haxie1** [apollographql/apollo-ios#298]
The Apollo 0.8.0 pod is failing to build in our project on our CI system. 

We use `SWIFT_TREAT_WARNINGS_AS_ERRORS=YES` as part of the `xcodebuild` command, but this will fail to build Apollo if we have `inhibit_warnings => true` in the Podfile. 
The failure we get is: 
`.../Apollo-Swift.h -Xcc -working-directory/Users/Shared/A/B/C/Pods
<unknown>:0: error: conflicting options '-warnings-as-errors' and '-suppress-warnings'`.

 If we turn off `inhibit_warnings` in the Podfile for Apollo, the build fails because there are a number of Swift deprecation warnings.

We can get our project to build if we set `SWIFT_TREAT_WARNINGS_AS_ERRORS=NO`, but that removes a layer of safety in our build process. Is there a workaround for this issue, or a fix on the way?

We are using Xcode 9.4 and Swift 4.x and Apollo 0.8.0

**Comment by martijnwalraven** [comment]
I just released 0.9.0, which should fix this.
