### ISSUE TITLE
ApolloTestSupport causes issue after upgrading from 1.0.7 to 1.1.2

### ISSUE THREAD

**Issue by lorderster** [apollographql/apollo-ios#2985]
### Summary

Using Swift Package Manager, after updating from 1.0.7 to 1.1.2, the import of ApolloTestSupport causes the archive process failure.
The build process is still working.

### Version

1.1.2

### Steps to reproduce the behavior

Import ApolloTestSupport in any file, and the following code from TestMock.swift will generate an error:
```swift
#if !COCOAPODS
@_exported @testable import ApolloAPI
@testable import Apollo
#endif


### Logs

```shell
Error: Module 'ApolloAPI' was not compiled for testing
```

**Comment by calvincestari** [comment]
@lorderster - I'm going to close this one and reopen the original issue as there might be others watching that for updates. I'll apply the same labels as we have here.
