### ISSUE TITLE
DefaultValue Code Generation for InputObject When DefaultValue is given from Schema

### ISSUE THREAD

**Issue by hkjlee109** [apollographql/apollo-ios#2997]
### Question

This is neither a bug or feature request but rather a small question/suggestion. 🙂 

Backend team added a new field for an input object. In the schema, it is shown as below.

```
          {
            "name": "sorting",
            "description": null,
            "type": {
              "kind": "ENUM",
              "name": "SortingEnum",
              "ofType": null
            },
            "defaultValue": "ASCENDING"
          },
```

In this case, Apollo Code Gen doesn't set any default value. Looking at the test code, looks like it's an intended behavior.

https://github.com/apollographql/apollo-ios/blob/1.1.3/Tests/ApolloCodegenTests/CodeGeneration/Templates/InputObjectTemplateTests.swift#L466

```swift
  func test__render__given_NullableField_WithDefault__generates_NullableParameter_NoInitializerDefault() throws {
    // given
    buildSubject(fields: [
      GraphQLInputField.mock("nullableWithDefault", type: .scalar(.integer()), defaultValue: .int(3))
    ])

    let expected = """
      public init(
        nullableWithDefault: GraphQLNullable<Int>   ### No default value set.
      ) {
        __data = InputDict([
          "nullableWithDefault": nullableWithDefault
        ])
      }

      public var nullableWithDefault: GraphQLNullable<Int> {
    """
 ```

It's not a big deal. We can just manually set the field when we call this InputObject. eg. `nullableWithDefault = nil`
But the thing is, for this incident, IOS was the only platform having a build break after fetching GraphQL schema.

Web and Android, looks like they are setting the default value as null in this case and had no issue. 
If field is Optional(Nullable) and defaultValue is given in the schema, they ignore the given defaultValue in the schema and defaults it to null.

Wouldn't it be better if we change the expected behavior as below? 🤔 Just for a consistency across platforms.
 
```swift
  func test__render__given_NullableField_WithDefault__generates_NullableParameter_NoInitializerDefault() throws {
    // given
    buildSubject(fields: [
      GraphQLInputField.mock("nullableWithDefault", type: .scalar(.integer()), defaultValue: .int(3))
    ])

    let expected = """
      public init(
        nullableWithDefault: GraphQLNullable<Int> = nil  ### <--- Can this be like this?
      ) {
        __data = InputDict([
          "nullableWithDefault": nullableWithDefault
        ])
      }

      public var nullableWithDefault: GraphQLNullable<Int> {
    """
 ```

**Comment by BobaFetters** [comment]
Hey @hkjlee109 thanks for calling this out! This is something we should update for consistency with the other client platforms and will look to do in an upcoming patch release.

**Comment by hkjlee109** [comment]
Nice! Thanks, guys. 🙂

**Comment by hkjlee109** [comment]
Nice! Thanks, guys. 🙂

**Comment by AnthonyMDev** [comment]
This will be included in the next release!
