### ISSUE TITLE
Allow access to JSON used in deserializing GraphQL structs and GraphQLResultReader subclassing

### ISSUE THREAD

**Issue by xiekevin** [apollographql/apollo-ios#30]
I'm opening this issue to ask whether the following could be supported:

 - Access to the JSON that an struct was de-serialized with
 - Allowing custom deserialization through potentially being able to subclass `GraphQLResultReader`

To give some context, I'm attempting to create a data synchronization layer on top of GraphQL queries. At a high level, I'm storing the original JSON, updating that JSON when queries to the server return new values, alerting GraphQL structs that their properties have changed, and recreating the object using the reader and updated JSON. I've hacked something together to achieve this, namely:

 - made `GraphQLResultReader` initializer public
 - made `responseName` in `Field` public
 - made `currentObject` in `GraphQLResultReader` public

I think there's probably a better way to do what I want with the library's general purpose in mind, and would like to see if something like this would be able to be supported in an official capacity. 

Would either of the above asks be possible to support? If you think that this would be helpful to have, I'm also happy to attempt a PR.

**Comment by martijnwalraven** [comment]
@xiekevin: We definitely want to support caching as part of the framework, so it would be great to hear more about what you are currently doing, and how we can make that work in a more structured way. Design input is very welcome!

My idea is roughly that the resolver function passed to `GraphQLResultReader` when reading from a network response should also be responsible for keeping normalized records, with the right cache key based on the query path or field value (like `id`). These records are then published to a store, and we would define a `Cache` protocol to plug in different caching implementations (more or less key-value, so dealing with records and not whole responses).

The `GraphQLResultReader` abstraction also makes it easy to read from a store (this may be what you're already doing), so that allows you to reload queries from the cache when other responses return new values. We eventually may want to keep track of dependencies, so we only update queries when their associated data changes, but I think it may be ok to reload all queries at first.

**Comment by xiekevin** [comment]
Hi martijn, thanks for the quick response. What you've described is conceptually in line with what I'm doing, but since I was working under the assumption that Apollo-iOS would be a thin data-fetching layer, I built most of the caching / data-sync outside of the framework. That's probably why the structure is bit messier, I hadn't thought of adding integration to the framework itself.

I like the idea of having the resolver update the cache after reading the network response and think it probably makes the most sense to do it there. I am currently using the field value `id` as the cache key as well (since it's unique per node object under a Relay based GraphQL schema). 

Since I've done it outside the framework, I'm updating the cache when the network returns `.Data`, getting the JSON via `currentObject`, and syncing with the cache at that point. With this approach, I recursively form wrappers around all `JSONObject` values that have an `id` field (these are assumed to be object / node values), generating a hierarchy of wrapper objects around the root object, and storing each wrapper individually into the `Cache`.

All the data sync happens through a pub sub implementation that wraps around `NotificationCenter` that listens based off the `id` key. The cache has a mapping of dependencies so that only the objects whose dependencies have changed are refreshed. I hadn't thought about syncing at the query level, so right now all my caching is done at the object / model level.

I use `GraphQLResultReader` to recreate the auto-generated structs using the `init(reader:)` method after updating `objectStack` on the reader to be the `JSONObject` that is generated via the wrappers obtained through the Cache.

I think what you're proposing sounds great. Would the main benefit of cacheing at the query level be that there is just one top level object that needs to be updated? I think in general it sounds like a better approach but would like to understand all the reasons why. Do you have an estimate for when work might start or complete?

**Comment by martijnwalraven** [comment]
Thanks for the detailed response! This is exactly the kind of design discussion I was hoping for.

What you're describing is pretty much what I had in mind. Your `NotificationCenter` wrapper is what I've been calling the `Store`. So `GraphQLResultReader` keeps a map of records, these get filled as we parse objects, and after parsing an entire response the record set is published to the store.

The store is then responsible for merging the new record set with what's already there, and notifying subscribers. It would be great to keep track of dependencies and make this as fine grained as possible, so we don't notify subscribers if their data hasn't changed.

I'm not sure what you mean by:
>  I hadn't thought about syncing at the query level, so right now all my caching is done at the object / model level.
We definitely want to cache at the object level, so maybe you're misunderstanding what I said before. But the idea is that subscribers register an interest in a query, and get notified when any data the query depends on changes. At that point, the query reloads based on the data in the store, through a `GraphQLResultReader` that reads records from the store and follows references when resolving fields.

I'm also not sure about these questions. Could you elaborate on what you mean by 'JSON merging' and 'cacheing at the query level'?

> - Does JSON merging make sense as a data synchronization strategy?
> - Would the main benefit of cacheing at the query level be that there is just one top level object that needs to be updated?

Caching lists is definitely one of the most tricky parts! I don't think skipping objects that miss fields is something you want as a default policy, but a lot of this is application-specific, so we want to make sure we expose the right hooks.

An argument like `first` has no special meaning in GraphQL, so strictly taken, the results of `object(first: 5)` and `object(first: 10)` are unrelated and would be cached separately. So we'd have a list of 5 object references stored under one cache key, and a list of 10 object references stored under another. These are references, so the objects these point to are still shared (if they have an 'id'), but the lists themselves are separate.

So I think the default caching policy wouldn't actually suffer from the problem you're describing. But of course, in many cases we actually want to capture the fact that these lists are part of the same (conceptual) list. If we've already asked for `object(first: 10)`, we would like to avoid hitting the server for `object(first: 5)` for example. And things become even more tricky when we take mutations into account, where we would like to add something to the end of a list for instance.

Apollo Client (for JavaScript) gives you a lot of freedom to configure application-specific behavior, and [exposes functions like `fetchMore` and `updateQueries`](http://dev.apollodata.com/react/cache-updates.html) for this.

I would also highly recommend [this talk](https://www.youtube.com/watch?v=1Fg_QtzI7SU&t=7s) by Joe Savona, who works on Relay at Facebook.

He presents a really nice summary of the lessons they have learned at Facebook, and that includes a conceptual model for how they do caching and deal with paginated lists. I like the `ConnectionController` model he describes, and it seems that could be a good fit for Apollo iOS.

I'm planning on working on this over the next few weeks, and would like to have a basic implementation of caching done by the end of the year. So let's definitely continue this conversation, and maybe there is an opportunity to work together on this, or even adapt some of the code you've been working on.

**Comment by xiekevin** [comment]
Thanks for the thoughtful follow-up, I feel like I'm learning a lot by discussing this thoroughly with you. I feel the general implementation strategy that we've each come up with is identical in most aspects and I think that's a great sign.

As for the discussion around syncing at the query level, I had previously been syncing objects themselves and reloading individual objects using `init(reader: GraphQLResultReader` rather than the top-level `Query` object. Caching was still done at the object level, but your suggestion to reload the query rather than reload objects was a good one and I hadn't thought of that at the time of writing.

To give some more follow up on JSON merging, I've used JSON as the basis of merging or updating records. I wasn't sure how else to do this using object types in Swift since I couldn't figure out a way to set properties dynamically without bridging to use Obj-C's `setValueForKey`.  I've essentially stored all `Records` as `JSONObject`s in my `Store` with the key as an `id`.

I watched the talk by Joe Savona and it mentions a lot of good points and things I hadn't considered and is definitely a good overview of GraphQL best practices--I'll be sure to forward that to my team. You also brought up many good points about caching lists and I do agree and see now that a lot of it is platform or product specific. As you mentioned earlier about exposing the right hooks, it would definitely be great to be able to fine-tune how the updates occur.

With that said, I still have a couple of uncertainties. When caching the two lists separately, `object(first: 5)` itself has no associated `id` key. 
 - How would keys be generated to be consistent and distinct between `object(first: 5)` and `object(first:10)` when they're part of the same object and same property?
 - In the example above, if we're able to generate distinct keys, when reloading the query, how does it know to use the cache key for `objects(first: 10)` or the cache key for `objects(first: 5)` when reloading the list when both are the same property of the same root object (both have id `ID123456789`)?

I do understand that `first: 10` and `first: 5` could conceptually not be the same list, but in this case aren't they guaranteed to be the same (even if we use path as the cache key)? If that's the case, I feel like the problem mentioned would still occur since we wouldn't reliably be able to keep both.

If you have the time to respond to my concerns that would be great and I'm happy to hear that you'll be working on it starting so soon. My implementation is very rough in general so it probably wouldn't be helpful, but would be happy to share if you'd like to take a look!

**Comment by martijnwalraven** [comment]
@xiekevin: Sorry, I've been preoccupied for a few days, but getting back to this now. I hope to have some code to share soon.

To answer your question, fields are not cached based on the response name (that could be an alias), but on a combination of the field name and arguments. The idea here is that fields are basically functions, and different arguments may give different results, so they should be cached separately. In the Star Wars schema for example, you don't want to confuse `height(unit: FOOT)` and `height(unit: METER)`.

This means `object(first: 5)` and `objects(first: 10)` are considered different results and will be cached separately by default. (Of course, the point here is that there is a relationship between these results, and you want a mechanism that allows you to take advantage of it. But that is not the default behavior.)

In general, using `id` as the cache key for an object is just one possibility, and it is often useful to have a fallback strategy. In Apollo Client, the default strategy is actually to use the query path, but you can configure your own `dataIdFromObject` function.  See [this blog post](https://dev-blog.apollodata.com/the-concepts-of-graphql-bc68bd819be3#.i4zkemutq) for a good description of this model.

**Comment by xiekevin** [comment]
Ah, I get it now, that was a great explanation. Thanks for taking the time to help me understand your caching / synchronization strategy. I'll wait for when you have some code to share to give any further thoughts. Please keep me updated when you have new developments to share!

**Comment by martijnwalraven** [comment]
@xiekevin: Hey, I just wanted to mention normalized caching has been merged! Still working on updating the documentation and writing a blog post, but it would be great to get some feedback and see if this covers your use cases.
