### ISSUE TITLE
Watched Query Doesn't Fire When Using Normalised Cache Key

### ISSUE THREAD

**Issue by andykent** [apollographql/apollo-ios#3001]
### Summary

I really Hope this is a genuine bug and not me holding it wrong.

What I am seeing is that when I don't use `cacheKeyInfo(for type: Object, object: JSONObject)` my query watcher fires as expected but as soon as I introduce cacheKeyInfo watchers stop firing at the expected time even though I can see changes showing up in the sqlite cache db.

### Version

1.1.3

### Steps to reproduce the behavior

Here is some reduced code from the project this is happening in. 

Simplified Query:

```gal
query GetScene($sceneId: String!) {
  scene(uuid: $sceneId) {
    id: uuid
    slug
    title

    ...other nested fields...
  }
}
```

The Watcher

```swift
watch(query: GetSceneQuery(sceneId: id), cachePolicy: .returnCacheDataAndFetch) { ... }
```

Fetch triggered elsewhere in the App

```swift
fetch(query: GetSceneQuery(sceneId: id), cachePolicy: .fetchIgnoringCacheData) { ... }
```

The above works exactly as I expected, e.g. calling fetch the watch callback fires whenever a field in the fetched query changes.

As soon as I add in a cache key to normalise the `Scene` type it stops working as expected, example cacheKeyInfo:

```swift
public enum SchemaConfiguration: ApolloAPI.SchemaConfiguration {
  public static func cacheKeyInfo(for type: Object, object: JSONObject) -> CacheKeyInfo? {
    switch type {
      case Objects.Scene:
        return try? CacheKeyInfo(jsonValue: object["id"])
      default: return nil
    }
  }
}
```

With this in place the watch query now only fires on the initial query but not after a fetch that changes the data. However if I check in the sqlite cache db I do see the `Scene:4851fe08-9247-4568-8c9d-b1a2972a05ac` key has been merged with the updated results from the fetch request but this never propagates to the watcher.

### Anything else?

This really feels like a bug but maybe I've mis-understood how the cache keys and watched queries interact?

**Comment by AnthonyMDev** [comment]
I think that this is related to #2984 actually! I'm working on something that I think might correct this. I'll update you as soon as that is released, and you can see if it's resolved yet!

**Comment by andykent** [comment]
oh interesting. Thanks for looking into it and I'm really glad it's not just me. We have had to abandon using `cacheKeyInfo` for now but I can turn it back on and test again when you have something ready.

**Comment by andykent** [comment]
Just reporting back here. I just completed the upgrade to `1.2.0` and as far as I can tell that seems to have resolved this issue.

**Comment by calvincestari** [comment]
Glad to hear that @andykent!
