### ISSUE TITLE
iOS/Xcode 14.2, Apollo Upgrade from 0.53.0 to 1.0.7

### ISSUE THREAD

**Issue by ArunVicky001** [apollographql/apollo-ios#3002]
### Question

Hi 
I have an existing project using an old Apollo build(`0.53.0`) w/cocoapods and am trying to upgrade to `1.0.7`. I followed all the steps here:

https://www.apollographql.com/docs/ios/migrations/1.0/#breaking-changes

using the Xcode project' set up that is outlined in below steps 
1. Install the Apollo iOS pod:
`pod 'Apollo', '~> 1.0'
`2. Created a GraphQL schema file (usually a .json file) that describes your API.
3.In your Xcode project, create a new build phase to generate code.
a. Open your project settings and go to the "Build Phases" tab.
b. Click the plus button in the top-left corner and select "New Run Script Phase".
c. In the script text field, enter the following:
`./Pods/Apollo/apollo-ios-cli generate path/to/schema.graphql --output API --target ios
`
the above command is not working and it throwing me an error like below 

```
Error: Unknown option '--output'
Usage: apollo-ios-cli generate [--path <path>] [--string <string>] [--verbose] [--fetch-schema] [--ignore-version-mismatch]
  See 'apollo-ios-cli generate --help' for more information.
Command PhaseScriptExecution failed with a nonzero exit code

```
also I tired with `./Pods/Apollo/apollo-ios-cli generate path/to/schema.graphql --outputDirectory API --target ios
`
getting same error below 

```
Error: Unknown option '--outputDirectory'
Usage: apollo-ios-cli generate [--path <path>] [--string <string>] [--verbose] [--fetch-schema] [--ignore-version-mismatch]
  See 'apollo-ios-cli generate --help' for more information.
Command PhaseScriptExecution failed with a nonzero exit code
```

please suggest me a right way migrate the library from `0.53.0 to 1.0.7 `

Thank you

**Comment by BobaFetters** [comment]
Hey @ArunVicky001, so the Run Script build phase setup for codegen is not updated or recommended any longer starting with the 1.0 release. If you check out [this](https://www.apollographql.com/docs/ios/migrations/1.0/#step-3-replace-the-code-generation-build-phase) section of the migration guide you will see some info on that.

As for getting your code generation working, you will want to check out the 1.0 documentation for code generation for the proper commands to run for code generation. The basics are that you will need to first create a codegen configuration that is used by the generate command. I recommend reading through the [codegen documentation](https://www.apollographql.com/docs/ios/code-generation/codegen-cli) to see if you can get things working, and if you have further questions let me know.

**Comment by ArunVicky001** [comment]
@BobaFetters Thanks for your response, I have successfully executed the command and it has created the model classes into my project based on the query.
I followed the below steps to add the created folders in my project 

1. In Xcode, right-click on your project in the project navigator and select "Add Files to [Your Project]".
2. Navigate to the folder where your MySchema file is located and select it.
3. Make sure to check the "Copy items if needed" checkbox and select "Create folder references" as the added folder's "Added folders" option.
4. Repeat the same process for your queries folder.
5. Once you have added both folders, make sure to select your project in the project navigator and go to the "Build Phases" tab.
6. In the "Build Phases" tab, expand the "Compile Sources" section and make sure that all of the generated .swift files are listed here. If any files are missing, click the "+" button and add them manually.
7. Finally, make sure to import the necessary classes in any view controllers or other files where you want to use them.

but still I can't able to read the files is that something else should I need to do?

**Comment by ArunVicky001** [comment]
this is my folder structure 
<img width="368" alt="Screenshot 2023-05-11 at 3 07 02 PM" src="https://github.com/apollographql/apollo-ios/assets/34921497/ea40ade6-19b7-4b8c-a37e-d8db0144608d">

I am trying to access `GetInboxUnreadCountQuery` class in my viewController 

<img width="930" alt="Screenshot 2023-05-11 at 3 07 16 PM" src="https://github.com/apollographql/apollo-ios/assets/34921497/65786a5f-8e1c-4206-b772-8fc90dd48802">

like below in my view controller 

<img width="1017" alt="Screenshot 2023-05-11 at 3 09 32 PM" src="https://github.com/apollographql/apollo-ios/assets/34921497/39044360-0d81-4086-8c77-412ff2e19593">

it's not showing could please suggest me the right way to solve this issue?

**Comment by BobaFetters** [comment]
@ArunVicky001 Can you share your `apollo-codegen-config.json` so I can see how to codegen is configured? Also can you point me to where in the documentation you found the steps you listed for adding the files to the project?

**Comment by ArunVicky001** [comment]
`apollo-codegen-config.json` source code 

```
{
  "schemaName" : "MyQuery",
  "options" : {
    "cocoapodsCompatibleImportStatements" : true
  },
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "/Users/vignesh.arunagiri/Documents/XCode/ClientiOS/Schema/schema.json"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : "./MyQuery",
      "moduleType" : {
        "embeddedInTarget" : {
          "name" : "ClientiOS"
        }
      }
    },
    "operations" : {
      "inSchemaModule" : {
      }
    }
  }
}


```

I don't find any documentation to add files in the project in the apollo client iOS. I have searched it and followed the procedures.    

I tried this one too but it's also not accessible 
`MyQuery.GetInboxUnreadCount...`

![Uploading Screenshot 2023-05-11 at 10.41.14 PM.png…]()

here is my sample project please have a look and help to solve the issue. 
 
[ClientiOS.zip](https://github.com/apollographql/apollo-ios/files/11454741/ClientiOS.zip)

**Comment by calvincestari** [comment]
> if you see the screenshot MyQuery folder is not properly adding into the project it's shows "?" beside the folder name

I believe that is the git status of the files in your repo. It has nothing to do with Apollo iOS.

**Comment by ArunVicky001** [comment]
then it's fine, Could you please help me to get the `MYQuery` class accessible in the ViewController? also please check the sample project and suggest me

**Comment by calvincestari** [comment]
The files were not correctly added to the project. If you look at 'Compile Sources' in the 'Build Phases' tab of the project, you'll see that none of the `.swift` files were added to the target. They're not being compiled which means your project doesn't know about them.
<img width="1742" alt="Screenshot" src="https://github.com/apollographql/apollo-ios/assets/146856/11010543-33e3-415b-a743-dfd13397788b">

Remove the MyQuery folder from your project and add it again, then it should look like this:
<img width="1743" alt="Screenshot" src="https://github.com/apollographql/apollo-ios/assets/146856/a7cc4d65-6f55-46d4-919a-fde7d1a14cc5">

Then you can use the `MyQuery` namespace and `GetInboxUnreadCountQuery` within it.

**Comment by ArunVicky001** [comment]
How did you added the MyQuery folder in the project could you please share the steps?

**Comment by ArunVicky001** [comment]
Got it, it should be Create Groups  instead of Create folder references and then manually we need to add those files into the compile sources. 
 
<img width="725" alt="Screenshot 2023-05-11 at 11 20 14 PM" src="https://github.com/apollographql/apollo-ios/assets/34921497/54c3c71d-9c1a-40b9-b449-edcb8e04440f">

**Comment by calvincestari** [comment]
> and then manually we need to add those files into the compile sources.

No, you do not need to manually add them. Xcode will automatically do it.

**Comment by calvincestari** [comment]
I'm going to close this issue as there is nothing actionable for us in Apollo iOS. Your project should work fine once the generated files are correctly added and compiled into the target.

**Comment by ArunVicky001** [comment]
@calvincestari is that the right way to do this, and it's not mentioned anywhere in the documentation. could you please confirm this.    

<< No, you do not need to manually add them. Xcode will automatically do it.

after added the folder into the project I just ran the application and the files are not being added in the compile resources. please verify it again.

**Comment by calvincestari** [comment]
> @calvincestari is that the right way to do this, and it's not mentioned anywhere in the documentation. could you please confirm this.

@ArunVicky001, you need to add the generated files to your project in a way that is suitable for your project and so that they're compiled into the target. We don't include step by step instructions for Xcode because we require that users already have the knowledge to do that.

> after added the folder into the project I just ran the application and the files are not being added in the compile resources. please verify it again.

It sounds like you didn't select the `ClientiOS` target for 'Add to targets:' when adding the files to your project. Adding it to the target is what gets it included in the build step.
<img width="1739" alt="Screenshot 2023-05-11 at 11 00 44 AM" src="https://github.com/apollographql/apollo-ios/assets/146856/715a9f61-c86e-46f0-b7ed-994849337d61">
