### ISSUE TITLE
Ambiguous use of '_set(_:for:)' for generated test mocks

### ISSUE THREAD

**Issue by azilbershtein** [apollographql/apollo-ios#3003]
### Summary

After upgrading to 1.1.3 the use of self. was replace in _set in the test mocks files.
Now we're getting Ambiguous use of '_set(_:for:)' for all kinds of Arrays.
For example this one throw this error:
![Screenshot 2023-05-10 at 17 04 55](https://github.com/apollographql/apollo-ios/assets/64828042/7314ae20-a234-4e7b-8c4b-76f2e5b6d04d)

But I removed the array it compiles
![Screenshot 2023-05-10 at 17 05 26](https://github.com/apollographql/apollo-ios/assets/64828042/a282550c-54f4-4dc2-866f-11eeb19bb1cf)

### Version

1.1.3

### Steps to reproduce the behavior

Generate test mocks

**Comment by BobaFetters** [comment]
Hey @azilbershtein this should be resolved with this [PR](https://github.com/apollographql/apollo-ios/pull/2991) which will go out in our next release, the specific fix was [this line](https://github.com/apollographql/apollo-ios/pull/2991/files#diff-b3d3d639f815a2b3dcee78379825c377b4036869559a53c6eeb302aa1587fccfR70).

**Comment by marcellodepalo** [comment]
same errors after the update to the version 1.1.3

<img width="1276" alt="Screenshot 2023-05-10 at 17 28 46" src="https://github.com/apollographql/apollo-ios/assets/3896672/6edb786b-ba15-4ce9-a607-fa884fd5553f">

**Comment by sgharraph** [comment]
when this will be released?

**Comment by calvincestari** [comment]
We're planning to make a release early next week, probably Monday.

**Comment by calvincestari** [comment]
> same errors after the update to the version 1.1.3

@marcellodepalo, it's merged into `main`, not an official release yet.
