### ISSUE TITLE
Generated test mocks code does not compile

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#3012]
### Summary

If in a type in the schema there is an optional array type, generated test mocks code by using the `testMocks` option does not compile. Instead we get an error `Ambiguous use of '_set(_:for:)' 

```graphql
type SomeSpecialNode implements Node {
  id: ID!
  cars: [Car]
}
```

### Version

1.1.3

### Steps to reproduce the behavior

I was able to reproduce this in a sample project so I have attached it here.

[apollo-codegen-issue (testMocks).zip](https://github.com/apollographql/apollo-ios/files/11473483/apollo-codegen-issue.testMocks.zip)

### Anything else?

I'm running on Xcode 14.3

**Comment by calvincestari** [comment]
Hi @tahirmt - this is resolved already with [the fix](https://github.com/apollographql/apollo-ios/pull/2991/files#diff-b3d3d639f815a2b3dcee78379825c377b4036869559a53c6eeb302aa1587fccfR70) merged into main with PR #2991. It'll go out with the next release, this coming week.
