### ISSUE TITLE
Cannot find query

### ISSUE THREAD

**Issue by SheldonWangRJT** [apollographql/apollo-ios#3014]
### Summary

after reading multiple questions and answers. i still cannot make my auto-gen being successfully read by my project.
 
<img width="726" alt="image" src="https://github.com/apollographql/apollo-ios/assets/18402866/b43f5bbc-7491-4598-bc7d-c1978a491529">

I am using cocoapods with apollo + manual import auto gen files + using 
```
      "moduleType" : {
          "embeddedInTarget": {
              "name": "TG"
          }
      }
```
TG is my project workspace target name.

pls help.

### Version

1.1.3

### Steps to reproduce the behavior

0. cocoapod to install and generate workspacing with apollo
1. download scheme.json from a website that has graphql
2. populate apollo-codegen-config.json
3. auto-gen file with `./Pods/Apollo/apollo-ios-cli generate`
4. open workspace and compiler will not let it compile 
<img width="726" alt="image" src="https://github.com/apollographql/apollo-ios/assets/18402866/b43f5bbc-7491-4598-bc7d-c1978a491529">

**Comment by BobaFetters** [comment]
@SheldonWangRJT When you are using the `embeddedInTarget` module type, all of your generated classes will be namespaced using a caseless enum extension to prevent conflicts. The enum is based on your schema name,  so in order to access and use your query you will need to use code like this: `MySchema.AllTeamsQuery`

Closing this because there is no action needed.

**Comment by SheldonWangRJT** [comment]
Thanks for the quick response! I figured some of the auto-gen files have to be placed at the root directory of the folder. Might worth updating your readme or guide in the website to reflect this.

**Comment by calvincestari** [comment]
> I figured some of the auto-gen files have to be placed at the root directory of the folder.

There is no requirement for the generated files to be placed in any particular folder when using `embeddedInTarget`, it's completely up to you and the needs of your project.

> Might worth updating your readme or guide in the website to reflect this.

The documentation for the [embedded in target](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#embedded-in-target) module type does mention the namespace enum. What changes to the docs do you think would help make this clearer?
