### ISSUE TITLE
Session ID/Cookies issue in Apollo iOS

### ISSUE THREAD

**Issue by thapli9A** [apollographql/apollo-ios#3025]
### Question

So we are using this library and implanted caching as well.
I have a question does apollo internally use session ID/Cookies in that case?

**Comment by calvincestari** [comment]
Hi @thapli9A 👋🏻 - I don't fully understand what you're asking, if you can expand on what you're wanting/expecting it might help me to give a better answer.

* I'm not sure what "implanted caching" means but if you're simply saying that you use the caching feature of Apollo iOS then that's a fairly standard use case.
* As for session IDs and cookies, are you asking if Apollo iOS caches those? If that's your question then the answer is no, only response data sent from the GraphQL server is cached, if you chose to use the appropriate caching policy. If a session ID or cookie is included in that response data then yes it will be cached.
