### ISSUE TITLE
__typename in autogenerated graphql.swift

### ISSUE THREAD

**Issue by psdevss** [apollographql/apollo-ios#3030]
### Question

Hi would like to ask, is it possible to remove __typename in graphql.swift

this is the autogenerated

```
query Animals($animalFilter: AnimalFilter!) {
       animal(animalFilter: $animalFilter) {
          __typename
         animalType {
            __typename
            name
        }
         animalInformation {
            __typename
              animalSize {
                 __typename
                 height
              }
         }
           species
       }
 }

```
this is query .graphql

```
query Animals($animalFilter: AnimalFilter!) {
       animal(animalFilter: $animalFilter) {
          __typename
         animalType {
            name
        }
         animalInformation {
              animalSize {
                 height
              }
         }
           species
       }
 }

```

I'm getting typename in the autogenerated in each object, and receiving this error as a response

Error at path "animal.animalType.__typename)": missingValue

**Comment by psdevss** [comment]
> Hi @psdevss - no there is no way to remove the `__typename` field. They're added during code generation and required by the executor to be able to correctly parse responses into the correct Swift types.
> 
> 
> 
> That error, I believe, is the result of the response from the GraphQL server missing the `__typename` value and the executor throwing an error because it is not an optional field; [the GraphQL spec defines it as `String!`](https://spec.graphql.org/draft/#sec-Type-Name-Introspection).
> 
> 
> 
> Have you inspected the response data being sent back from the GraphLQ server and verified whether `__typename` is present or not? I don't know what GraphQL server implementation you're connecting to, is there a specific reason it cannot send back the field value?

Ahhh it's required. (Just new with graphql) Currently I'm just creating a mock json with no __typename. I guess there will be __typename in every response. Thanks for this info!

**Comment by calvincestari** [comment]
Ah OK. I didn't realize you were working with mocked responses. Glad we get it figured out.
