### ISSUE TITLE
NetworkResponseExecutionSource.DataTransformer Returns `nil` When It Should Not

### ISSUE THREAD

**Issue by asbhat** [apollographql/apollo-ios#3034]
### Summary

Using the subscript for the new `ObjectData`, which uses the `NetworkResponseExecutionSource.DataTransformer`, returns `nil` for integer id fields.

```swift
let value = object._rawData["id"]  // value is Optional(AnyHashable(<<Int>>))

switch value {
case let scalar as ScalarType:
  print(scalar)
case let customScalar as CustomScalarType:
  print(customScalar._jsonValue as? ScalarType)
default: print("nil!")  // prints "nil!"
}

switch value {
case let intID as Int: print(intID)  // this properly prints the int
default:
    print("\(type) could not translate \(value) from \(object)!!")
    return nil
}

```

### Version

v1.2

### Steps to reproduce the behavior

My project is closed, but the API I'm using (which I have no control over) is open.

URL: https://graphql.anilist.co

Example query
```graphql
query MediaDetails($id: Int!) {
  Media(id: $id) {
    id
    updatedAt
  }
}
```

Schema Configuration
```swift
public enum SchemaConfiguration: ApolloAPI.SchemaConfiguration {
    public static func cacheKeyInfo(for type: ApolloAPI.Object, object: ApolloAPI.ObjectData) -> ApolloAPI.CacheKeyInfo? {
        switch type {
        case Objects.Media:
            let value = object._rawData["id"]  // value is Optional(AnyHashable(<<Int>>))

            switch value {
            case let scalar as ScalarType:
                print(scalar)
            case let customScalar as CustomScalarType:
                print(customScalar._jsonValue as? ScalarType)
            default: print("subscript returns nil")  // this line executes
            }

            switch value {
            case let intID as Int: 
                print(intID)  // this properly prints the int
                return CacheKeyInfo(id: String(intID))
            default:
                print("\(type) could not translate \(value) from \(object)!!")
                return nil
            }

        default: return nil
        }
    }
}
```

### Anything else?

https://anilist.github.io/ApiV2-GraphQL-Docs/

Let me know if there's anything else I can add to help!

**Comment by BobaFetters** [comment]
@asbhat Thanks for reporting this and providing the reproduction info! We will take a look at this as soon as we can.

**Comment by BobaFetters** [comment]
The fix for this has been merged into main and will go out with our next release.

@asbhat For context, the issue was essentially the value in the `_rawData` being `AnyHashable<Int64>` instead of just `Int` due to how the `JSONSerialization` class works, so the `ScalarType` casting was failing. The subscript methods for `ObjectData` and `ListData` will now handle this appropriately, however directly accessing `_rawData` will still provide the `Int64` value.

The recommended way to access values on `ObjectData` is through the subscript methods and not through the `_rawData` property which is meant for internal use. So this would be how you would access the data:
```swift
let value = object["id"]
```

**Comment by asbhat** [comment]
Ahh ok thanks for the explanation and the fix! 

I'll stop using the internal API once it gets released 🙂

**Comment by calvincestari** [comment]
> I'll stop using the internal API once it gets released 🙂

@asbhat the pattern we use to designate something is 'internal' is with the leading underscore `_`, or sometimes a double-underscore `__`. Because of the split between the `Apollo` and `ApolloAPI` modules we need to have types/functions public when they're only meant for internal use.
