### ISSUE TITLE
Feature: Persisted Operations Support

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#3044]
Support new Persisted Query feature in Apollo iOS

- [x] Implement generation of persisted operations manifest
- [x] Add new options to codegen
  - [x] Update the code and tests for serializing and deserializing the JSON config file
- [x] Fix computation of identifier hash to respect multi-line/single-line operation configuration.
  - [x] Deprecate queryStringLiteralFormat
- [x] Add a new command to the CLI for generating this file
  - [x] Testing command works
    - [x] Parsing of arguments
    - [x] Input validation
- [x]  ~~PM/Xcode Command Plugin~~
- [x] Documentation
  - [x] Codegen configuration option
  - [x] New CLI command
  - [x] Step-by-step guide or entire new docs page around this feature

**Comment by jimisaacs** [comment]
I feel like I missed this work, is there a description of how this? Is "new Persisted Query feature" related to persisted queries outside of APQ? Does this work include providing a hook to generate your own operation ID string?

**Comment by AnthonyMDev** [comment]
Hey @jimisaacs, this is part of a GraphOS feature that is in private preview. The full end-to-end feature (GraphOS and Router) parts are enterprise-only though of course the Apollo iOS part is open source. When the feature goes public, more documentation and details will be made available.

But this does not include the ability to generate your open operation IDs yet. We're open to doing that, but it's not a huge priority for us at the moment. (We're happy to accept a PR to add that functionality though!)
