### ISSUE TITLE
Duplicate classes are creating when executing the apollo-ios-cli generate

### ISSUE THREAD

**Issue by ArunVicky001** [apollographql/apollo-ios#3050]
### Summary

When I am generating the models by using this comment `./Pods/Apollo/apollo-ios-cli generate` duplicate classes are creating inside Fragments and Interfaces folders 

Example two files are creating in the same `Permissions.graphql.swift` & `ConnectionPermissions.graphql.swift`

<img width="367" alt="Screenshot 2023-05-30 at 10 37 08 PM" src="https://github.com/apollographql/apollo-ios/assets/34921497/4f4c4da0-0dac-4ff4-a353-dcbd8c589f62">

```
query GetQuestions($parent: ID!) {
  getQuestions(parent: $parent) {
    items {
      ...QuestionFact
      __typename
    }
    ...ConnectionPermissions
    __typename
  }
}

fragment Permissions on Permissions {
  canDelete
  canUpdate
  __typename
}

fragment ConnectionPermissions on ConnectionPermissions {
  canCreate
  __typename
}
```

### Version

1.2.0

### Steps to reproduce the behavior

After executing the `./Pods/Apollo/apollo-ios-cli generate` in terminal

**Comment by calvincestari** [comment]
@ArunVicky001 - it looks like those fragments are named the same as the interfaces considering that the named type being used in the fragment definition is the same; `fragment Permissions on Permissions` and `fragment ConnectionPermissions on ConnectionPermissions`.

You must rename the fragments to prevent the conflict.
