### ISSUE TITLE
Needs to be an easier way for migration

### ISSUE THREAD

**Issue by jostster** [apollographql/apollo-ios#3056]
### Question

We are moving from cocoapods Apollo 0.51 to Apollo SPM 1.2.0 and the migration process has been painful. I have so far spent 2 full days trying to get the project to compile. It seems that I need to add `import MyAppAPI` to almost every file that references any GraphQL data object, while in 0.51 it was all Global and just `import Apollo` needed to be imported.
Am I doing something wrong as I couldn't find in the migration to add `import MyAppAPI` to the files.

My config looks like

```
{
  "schemaNamespace" : "MyAppAPI",
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "**/schema.json"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : "./MyApp/Services/GraphQL/MyAppAPI",
      "moduleType" : {
        "swiftPackageManager" : {
        }
      }
    },
    "operations" : {
      "inSchemaModule" : {
      }
    }
  },
  "schemaDownloadConfiguration": {
    "downloadMethod": {
        "introspection": {
            "endpointURL": "URL",
            "httpMethod": {
                "POST": {}
            },
            "includeDeprecatedInputValues": false,
            "outputFormat": "JSON"
        }
    },
    "downloadTimeout": 60,
    "headers": [],
    "outputPath": "./Path/schema.json"
}
}
```

I have then added the generated `Package.swift` for Apollo into my project.

**Comment by AnthonyMDev** [comment]
Thank you for the feedback. We know the 1.0 migration process is pretty heavy. We had to make a lot of fundamental changes to set us up for future success and 1.0 was the time to do that. It sounds like you've already read this, but for anyone else who reads this issue, for general tips on the migration process, please check out our [migration guide](https://www.apollographql.com/docs/ios/migrations/1.0). We aim for future migrations to new versions to be a lot less involved. I actually talk quite a bit about this in our [Apollo iOS Office Hours](https://www.apollographql.com/blog/mobile/ios/office-hours-apollo-ios/) if you're interested in learning more.

---

To address your specific issue, there are other ways of setting up your codegen config to include your generated operations in your main application target. [You can read all about how to configure codegen for your project's specific needs here.](https://www.apollographql.com/docs/ios/project-configuration) But having them in the SPM package we build for you is probably easier in the long run. 

You could configure it to generate the files so you can embed them directly in your application target. However this also has drawbacks. When not using an SPM package, Xcode requires you to manually add files to your targets in your Xcode Project. So you wouldn't need to import your API module all over the place, but every time you add or remove an operation or type, you would need to remember to manually add it to your target.

---

I don't think there is anything actionable for us to change based on this issue, so I'm going to close the issue. Good luck with your migration, and feel free to ask if you have any more specific questions after reading

**Comment by jostster** [comment]
@AnthonyMDev Correct me if I am wrong but as you mentioned embedding directly into the project has the drawbacks of having to manually add the generated files over the SPM approach?

**Comment by AnthonyMDev** [comment]
Yes, that's correct.

**Comment by calvincestari** [comment]
> It seems that I need to add import MyAppAPI to almost every file that references any GraphQL data object, while in 0.51 it was all Global and just import Apollo needed to be imported.

This is because the configuration file is creating a separate SPM module named `MyAppAPI` and that is what needs to be imported wherever it's content is used. Apollo iOS has far better support for modular architectures which is why there are new options for output modules. Previously the generated code would all exist in a single file that you added to your project, making it global through your target namespace.

> Am I doing something wrong as I couldn't find in the migration to add import MyAppAPI to the files.

No, this is standard usage of modules. Exactly the same as when you need to do 'import Foundation'.
