### ISSUE TITLE
Cannot use ApolloTestSupport in unit tests using cocoapods

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#3060]
### Summary

I want to have a dependency to `Apollo/ApolloTestSupport` only on the test target. 

I have my schema generated files in a separate pod and a different pod for the test support that has `Apollo/ApolloTestSupport` as a dependency. But because cocoapods adds the code into the same framework it creates conflicts.

I think ideally `ApolloTestSupport` should be a separate pod.

### Version

1.2.0

### Steps to reproduce the behavior

[ApolloTest.zip](https://github.com/apollographql/apollo-ios/files/11638203/ApolloTest.zip)

**Comment by tahirmt** [comment]
I was able to successfully compile it if I use the `TestMocks` code as a subspace of my schema pod. Which isn't the worst but now because it becomes part of the framework, the imports to my framework are producing warnings that it is ignoring import.

[ApolloTest-successful compile.zip](https://github.com/apollographql/apollo-ios/files/11640498/ApolloTest-successful.compile.zip)

**Comment by tahirmt** [comment]
Looks like it's a cocoapods bug https://github.com/CocoaPods/CocoaPods/issues/7195 rather than Apollo. It's still a blocker

**Comment by AnthonyMDev** [comment]
Ah thanks for bringing this to our attention. @BobaFetters we should note this to be part of the project restructuring. We're likely going to need to make ApolloTestSupport into it's own repo and submodule.

**Comment by BobaFetters** [comment]
@AnthonyMDev Yea I will have to dig into that a little more and see if it needs its own repo

**Comment by tahirmt** [comment]
@AnthonyMDev I was able to get it working by using a separate podspec for `ApolloTestSupport` but since we have `@testable import` for Apollo required, we can't publish it on the specs repo.

**Comment by AnthonyMDev** [comment]
Glad you found a workaround. I might suggest you depend on that as a local dependency as a workaround for now. We'll try to get this resolved with the work for #3064

**Comment by AnthonyMDev** [comment]
This was fixed when we made `ApolloTestSupport` into its own Cocoapod in v1.6. Thanks @BobaFetters
