### ISSUE TITLE
ApolloCache returnCacheDataDontFetch policy has a wrong description

### ISSUE THREAD

**Issue by petarbelokonski** [apollographql/apollo-ios#3061]
### Use case

We have:  https://github.com/apollographql/apollo-ios/blob/759a665fba28b5a2e4fa51897158f9817b99bc03/Sources/Apollo/ApolloClient.swift#L15

We also have:  https://github.com/apollographql/apollo-ios/blob/759a665fba28b5a2e4fa51897158f9817b99bc03/Sources/Apollo/CacheReadInterceptor.swift#L74

So if we use returnCacheDataDontFetch we do not return an empty result as the description suggests but we throw whatever the ApolloStore's load method has passed in the resultHandler closure param. 

### Describe the solution you'd like

I think the description should be updated to specify that an error is thrown.

**Comment by calvincestari** [comment]
Thanks @petarbelokonski - that's an easy enough update to clarify the expected response.
