### ISSUE TITLE
WWDC '23 Suggestions & Discussion Megathread (Macros, SwiftData, Privacy Manifest, & more)

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#3078]
## **Please use this issue instead of creating new issues regarding feature suggestions related to WWDC 2023 announcements.** 

WWDC 2023 introduced a huge number of new features between Swift 5.9, Xcode 15, and iOS 17 (and other platform OSes). We will be exploring how we can utilize these new features in the Apollo iOS client libraries. In order to consolidate discussion and exploration of the opportunities presented by these changes, we will be using this "megathread".

Any discussion that lead to well defined and scoped feature work will have individua issues created.

# Possible Opportunities

_This is list of discussion topics for possible features & improvements to be made. This list is not exhaustive and will be updated as new suggestions are discussed in this thread._

**These are only areas for exploration, a feature suggestion being included on this list does not indicate a commitment to future inclusion in Apollo iOS.**

### Using Macros in Existing Generated Models

Macros could be used to improve readability and reduce the generated source code. Much of the boilerplate that is generated could be"macroized". This would not improve the compiled binary size, as the expanded macros would still contain the necessary source code. Another possible benefit is that we could change the implementation of the expanded macro in future versions without requiring users to re-generate their models. **We need to learn more about the implications this would have on compilation times.**

There were concessions made in the fundamental way the generated code works due to limitations that may be removed by macros. There are possible considerations for rethinking the fundamental structure of the models again to be more powerful. This would likely be part of a future major version.

### Generate Models via Macros
As suggested in #3075, it may be possible to generate an entire model at build time from just passing a graphql file name or definition string into a macro. You would no longer need to run the codegen engine as an additional pre-build step. It would just be expanded from a macro. But something like that would likely require us to really rethink the schema module and all the shared schema types first.

Example:
```swift
#generateGraphql(code: """
    query MyAwesomeQuery($string: String!) {
       ...
    }
""")
```

This would be a significant change, and it's unclear what the precise benefits of this would be. 

- **-** Generated models would not be as easy to look at (you would need to preview the macro expansion for each macro) which could make writing code using them more difficult.
- **+** You could potentially decide where your generated models are located in your source code more easily.
- **?** Sharing schema metadata and schema types across operations could become more complex and confusing. This would likely require a significant rethinking of infrastructure.

### Generate GraphQL Operations from User-Defined models using Macros

Similar to the new `@Model` macro introduced with `SwiftData`, there is a potential for allowing users to build model objects using macros that are then internally converted into GraphQL operation documents. 

_This is a massive departure from the way we do things currently, which is based on pre-defined operations. I’m not sure if this is a viable or productive direction, but it’s worth discussing more deeply._

## [Noncopyable structs and enums](https://github.com/apple/swift-evolution/blob/main/proposals/0390-noncopyable-structs-and-enums.md)

We may be able to use noncopyable types to improve safety and performance in places that currently use manual copy-on-write implementations, such as the `DataDict` storage that backs the generated models. 

_More research is needed on the potential here._

## SwiftData Integrations

Usage of SwiftData for persistence of the normalized cache could unlock many powerful features. We could potentially use SwiftData as the underlying persistence layer, and provide a lot of the value and semantics of SwiftData to GraphQL models.

**This Is exploratory, but is unlikely to be a viable solution. GraphQL normalized caching does not work well with ORM style solutions due to the nature of partial data in selection sets and nullability.**

Ideally, we could create our schema types as SwiftData models (that have all optional properties) and then write some mediation layer that performs GraphQL execution. It is possible we could create our generated selection set models as wrappers around the SwiftData models, but there are likely to be many complications that will arise from this.

One apparent complication is how to structure ORM entities for interfaces and unions. GraphQL’s multiple inheritance through interfaces makes it difficult to map to ORM based entity structures.

## Mergeable Libraries

We will be looking into how to best support mergeable libraries and allow our users to take the best advantage of all the benefits of them.

User's configured library merging in the build settings of their projects. Our initial findings indicate that there is likely nothing actionable that we need to do to allow this. 

**We are seeking feedback on how we can better support users of mergable libraries.** As you implement mergeable libraries, if you hit any roadblocks or encounter situations in which we could make changes to improve our compatibility with this feature, please let us know in this thread!

## Privacy Manifests

We will be doing our due diligence to understand what (if any) privacy reporting the Apollo iOS client needs. Because we do not track any user data directly, it is likely we will have nothing to include in a privacy manifest.

**Question:** If we have nothing to put in a privacy manifest can/should we be including an _empty_ privacy manifest with the repo, or do we not need to have one at all in that case?

**Comment by erneestoc** [comment]
> Generate GraphQL Operations from User-Defined models using Macros
I like this idea. I think the challenge here would be the composition part. It looks like you can't access the members of referenced type in a macro. Would be nice if the macro exposed the syntax tree of the scope it's declared in.

**Comment by TizianoCoroneo** [comment]
It's good to take into account the [considerations made by the Pointfree team](https://forums.swift.org/t/macro-adoption-concerns-around-swiftsyntax/66588) about the dependency on SwiftSyntax that including macros in a library requires. The story around shipping macros alongside a library doesn't seem to be in a good spot currently

**Comment by esreli** [comment]
I understand but :(

**Comment by AnthonyMDev** [comment]
Closing this issue is not an indication that we aren't going to implement any of these features! This was just a discussion thread to get ideas. We've gotten lots of them and will be taking them into account for next year's road map planning!

Thanks to everyone who contributed!
