### ISSUE TITLE
Breaking changes in minor versions

### ISSUE THREAD

**Issue by lhunath** [apollographql/apollo-ios#3087]
### Summary

This is the second time in a short period that the Apollo iOS project has introduced backwards-incompatible breaking changes to the project using a MINOR version bump.

This time, the breaking changes are described here:
- https://www.apollographql.com/docs/ios/migrations/1.3/

Before, the breaking changes were described here:
- https://www.apollographql.com/docs/ios/migrations/1.2/

I have made my worries known at the time as well, since the 1.2 migration guidelines did not include all necessary instructions and were missing some important notes.

However, the issue is bigger, namely:
1. The Apollo iOS project uses semantic versioning, per the recommendations for SPM.
2. The semver guidelines require a MAJOR version bump when backwards-incompatible changes are introduced (ie. changes that will cause breaks in code targeting the prior version): https://semver.org/#spec-item-8
3. The Apollo iOS project has made several changes which are compile-time breakages using MINOR version bumps without incrementing the MAJOR.

This is a violation of the versioning specification. It is important to keep in mind that Xcode relies on packages conforming to the specification for its behaviour: by default, all package dependencies are created using a `upToNextMajorVersion` rule.
This means that Xcode can unpredictably and without any warning or change in code decide independently to update the version of the dependency whenever the MINOR is updated upstream. For instance, developers could be operating on Apollo 1.2.1 while the CI system is building and testing on Apollo 1.3. Both of these versions are 100% correct according to the default SPM versioning rules. However, code that builds fine on one machine will now break on the other.

This is a big issue. Please change your release process and respect the specifications which exist for a reason. I alerted to this fact previously, so this problem could have been avoided with some forethought: https://github.com/apollographql/apollo-ios/issues/3066#issuecomment-1583462897

I understand that sometimes breaking changes are necessary, and sometimes they seem "minor" in scope. You may not like that a bug has been released that requires such a major version bump, tough. That is what the MAJOR version number's job is, nothing else. If you prefer to reduce the frequency of major bumps, I wholly concur, but then I recommend finding an alternative approach or postponing the final solution of the underlying issue. There is only one mechanism for breaking changes, and that is the downstream-collaborative process of bumping majors to alert the necessity for code changes.

I understand the reasoning for the current strategy has already been given:
> We do our best to follow the principles of [Semantic Versioning](https://semver.org/spec/v2.0.0.html) with the caveat that minor versions will sometimes include minor breaking changes. Our definition of a "minor breaking change" is something that can easily be resolved but does not require substantial refactoring of user code. In this example the easy resolution is through the config option to produce the same code as before, which we should have made more public knowledge in the migration guide and changelog.

But this reasoning is simply inadequate and will guarantee that the Apollo iOS project is an unreliable dependency for all downstream users.

### Version

1.3.0

### Steps to reproduce the behavior

- Add an SPM dependency on Apollo iOS using Xcode's default rule `upToNextMajorVersion`.
- Implement an `ApolloInterceptor` targeting Apollo iOS as of 1.2.1.
- Commit your code.
- Hand off to another developer or CI system which checks out your code anew after Apollo has silently released 1.3.0
- Observe on the new system: `Type 'CoreAuthenticatingInterceptor' does not conform to protocol 'ApolloInterceptor'`
- Observe on the original developer's machine: Everything is still fine.

**Comment by AnthonyMDev** [comment]
Hi @lhunath, I started writing up a response to this feedback yesterday, which ended up evolving into a proposal for a formal versioning strategy. We've been intending to document our deviation from SemVer in a more formal and public way for a while. This feedback has prompted me to get that done sooner than later.

I'll have a detailed document proposing our versioning strategy along with our reasoning for it in the next couple of days. 

While I don’t know if the formal definition and reasoning for our versioning will persuade you, I believe it does at least respond to your arguments and feedback.

**Comment by calvincestari** [comment]
> I came here because of this same issue. Not sure if I need to stub out `id` or if this was an oversight during the June 14th change.

@jostster - yes you will need to stub it out. Adding what is detailed in the migration step will suffice, `public var id: String = UUID().uuidString`.

**Comment by oliverfoggin** [comment]
Just came to say this. There is a breaking change in `ApolloInterceptor` requiring an ID that seems to have come from nowhere. 😢

**Comment by JOyo246** [comment]
does id need to be marked public here?

**Comment by AnthonyMDev** [comment]
Yes, `id` will need to be `public`.

**Comment by RamblinWreck77** [comment]
Just my 2c/proposal:

- Change the current "2.0/3.0" roadmap into hero-releases

- Implement strict SemVer per the OP

This lets you have major milestones: "Apollo: Saturn V", "Apollo: Starship" in a fully "decoupled" manner from the semver. So if (what is now Apollo 2.0) "Saturn V" lands in release 2.x.y or 15.x.y, it doesn't matter.
