### ISSUE TITLE
Getting websocket errors while on device with SOCKSProxy enabled

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#3090]
### Summary

Hey, we started seeing issues on the websocket since 1.3. Here is a key message in the logs. 

```
websocket is disconnected: Error Domain=NSPOSIXErrorDomain Code=22 \"Invalid argument\" UserInfo={_kCFStreamErrorCodeKey=22, _kCFStreamErrorDomainKey=1}"
Web socket did disconnect Optional(Apollo.WebSocketError(payload: nil, error: Optional(Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={_kCFStreamErrorCodeKey=22, _kCFStreamErrorDomainKey=1}), kind: Apollo.WebSocketError.ErrorKind.networkError))
```

~at this point I don’t have a clear set of logs but I will add to it as I gather more information but I wanted to start the conversation in case you can see something obvious.~ This seems to occur only with `enableSOCKSProxy` turned on on device. Doesn't seem to matter if I have my phone connected to Charles or not.

### Version

1.3.0

### Steps to reproduce the behavior

Turn on SOCKSProxy

**Comment by tahirmt** [comment]
Looks like this relates to turning on `enableSOCKSProxy` on device. While Charles works in the simulator, enabling SOCKS proxy on device causes the web socket to not connect at all. 

Charles uses a different port for HTTPS proxy vs SOCKS proxy. e.g the default port for HTTPS is 8888 and SOCKS is 8889

By adding the `SOCKSProxy`, `SOCKSPort` and `SOCKSEnabled` options to the config I was able to get it working again. This was part of our fork that I removed as part of 1.2 update. Originally taken from here https://stackoverflow.com/questions/33090087/how-to-inspect-websocket-traffic-with-charlesproxy-for-ios-simulator-devices

```swift
if enableSOCKSProxy {
      let proxyDict = CFNetworkCopySystemProxySettings()
      let socksConfig = CFDictionaryCreateMutableCopy(nil, 0, proxyDict!.takeRetainedValue())
      let propertyKey = CFStreamPropertyKey(rawValue: kCFStreamPropertySOCKSProxy)
        let dict = socksConfig as? [String: Any]
        if let ip = dict?["HTTPSProxy"]  as? String, let port = dict?["HTTPSPort"] as? Int {
            let customSocksConfig = ["SOCKSProxy": ip, "SOCKSPort": port + 1, "SOCKSEnable": 1] as CFDictionary?
            CFWriteStreamSetProperty(outputStream, propertyKey, customSocksConfig)
            CFReadStreamSetProperty(inputStream, propertyKey, customSocksConfig)
        }
    }
```

**Comment by calvincestari** [comment]
Thanks for the issue @tahirmt.

So to clarify, there is no issue with websocket behaviour when `enableSOCKSProxy` is `false`. Is that correct? 
And the resolution to be able to use a SOCKS proxy on device is to enable configuration of the port. Is that correct?

**Comment by tahirmt** [comment]
Yes that's correct. If `enableSOCKSProxy` is `false` everything works as normally.

**Comment by calvincestari** [comment]
OK, the impact of this is going to be pretty low then.

> // assumes SOCKS port will always be 1 higher than the HTTPS port

This might be valid for Charles Proxy only though so we'd need to provide properties for the whole SOCKS proxy config.

**Comment by tahirmt** [comment]
Yeah this code is pretty tied to Charles proxy itself so if we create support in Apollo we’ll need to have things configurable for other tools. But since `enableSOCKSProxy` is public now I want to make sure that people who try to use it have a way to figure out what to do if they encounter a similar issue.

**Comment by calvincestari** [comment]
@tahirmt - I don't think exposing a var just for the on-device SOCKS proxy debugging is a change we need to do right now. I'm going to close this issue and link it to the 2.0 milestone which we'll take another look at when we get to that work.
