### ISSUE TITLE
Correct JSON syntax for testMocks

### ISSUE THREAD

**Issue by gmoraleda** [apollographql/apollo-ios#3097]
### Question

I want to generate testMocks but I'm failing at getting the syntax right.
I couldn't find any valid example.

This is my output block:
```json
  "output": {
    "schemaTypes": {
      "moduleType": {
        "swiftPackageManager": {}
      },
      "path": "./Packages/MyPackage"
    },
    "operations": {
      "inSchemaModule": {}
    },
    "testMocks": {
      "swiftPackageManager": {
        "targetName": "MyPackageTests"
      }
    }
  },
```

**Comment by gmoraleda** [comment]
Found the issue:
```
 "testMocks": {
      "swiftPackage": { <- without "Manager"
        "targetName": "MyPackageTests"
      }
```

Would be great to have some examples in the docs, though.
Closing this issue.

**Comment by calvincestari** [comment]
Yes, there are some inconsistencies in the JSON config and sometimes the default formatting for `encode`/`decode` isn't the most intuitive.
