### ISSUE TITLE
XCode 14.3.1 : Could not find module ‘Apollo’ for target ‘arm64-apple-ios-simulator’; found: x86_64-apple-ios-simulator, x86_64

### ISSUE THREAD

**Issue by ravikanthm36** [apollographql/apollo-ios#3098]
### Summary

Bug report
XCode 14.3.1 : Could not find module ‘Apollo’ for target ‘arm64-apple-ios-simulator’; found: x86_64-apple-ios-simulator, x86_64
Unable to build app against iOS simulator using XCode 14.3.1.

Versions

apollo-ios SDK version: 1.3.0
Xcode version: 14.3.1
Swift version: 5

Using M1 chip machine so I have added arm64 for third Party libraries, here is the attachment for the reference
<img width="639" alt="Screenshot 2023-07-03 at 12 20 07 PM" src="https://github.com/apollographql/apollo-ios/assets/67319136/85d91bcb-657f-43ed-98e9-017a87cdf1fd">

<img width="773" alt="Screenshot 2023-07-03 at 12 18 11 PM" src="https://github.com/apollographql/apollo-ios/assets/67319136/313518c8-ecea-41ad-bdb2-fac64e8c4950">

### Version

1.3.0

### Steps to reproduce the behavior

Just run the application with mentioned above Apollo versions

**Comment by BobaFetters** [comment]
@ravikanthm36 What is the reasoning for excluding the `arm64` architecture? That is the architecture used by Apple Silicon machines, and newer versions of Xcode and the simulators run natively on that architecture unless you run using Rosetta. Were you possibly using an older Xcode version that required running through Rosetta and needed to exclude `arm64` but possibly no longer need to exclude it now that you are on Xcode 14.3.1?

**Comment by ravikanthm36** [comment]
Thank you @BobaFetters, issue got resolved when I run the application in latest Xcode 14.3.1.
