### ISSUE TITLE
Implementing Encryption in Apollo Client's SQLiteNormalizedCache

### ISSUE THREAD

**Issue by ArunVicky001** [apollographql/apollo-ios#3101]
### Question

Dear Apollo Client Support Team,

I am reaching out regarding an issue I encountered while using Apollo Client's `SQLiteNormalizedCache`. After going through related discussions and GitHub threads ([1], [2], [3]), I couldn't find a clear solution to my problem.

My current setup involves using the disk-based caching mechanism provided by `SQLiteNormalizedCache`. However, I have a requirement to enhance the security of the cached data by encrypting the underlying SQLite database file. Unfortunately, it appears that Apollo Client does not offer built-in support for encryption techniques.

I have attempted to explore external libraries such as `CryptoSwift` and `SQLCipher` to achieve database encryption. However, I am unsure how to integrate them effectively with Apollo Client to secure the cached data.

Given this context, I kindly request your guidance and suggestions on how I can implement encryption for the `SQLiteNormalizedCache` in Apollo Client. If there are any recommended approaches or alternative methods to achieve this level of security, I would greatly appreciate your insights.

Thank you in advance for your assistance and support. I look forward to your response and guidance.

[1] - https://github.com/apollographql/apollo-ios/issues/1117
[2] - https://github.com/stephencelis/SQLite.swift/issues/570
[3] - https://github.com/apollographql/apollo-ios/pull/1162

**Comment by calvincestari** [comment]
Hi @ArunVicky001, I see you already found the other issue #1117 where this was discussed previously.

We do recognize the need that some projects may have to encrypt the cached data but it is important to call out that we won't be providing an implementation for data encryption. We've talked about it amongst the team and any solution in Apollo iOS will simply be to provide hooks for users to handle the encryption/decryption of data. Alternatively as mentioned in #1117 it may be a more efficient solution to build a normalized cache on top of a database that supports encryption natively.

We're happy to work with whoever wants to take on that task and contribute the design/PRs to Apollo iOS for review. It's not on our list of priorities at the moment so it may take some time for us to do ourselves. @martinbonnin might be able to offer some advice on how they've enabled data encryption in Apollo Kotlin.

**Comment by ArunVicky001** [comment]
@calvincestari  Thanks for your response it means `InMemoryNormalizedCache` gives native encryption is it?

**Comment by calvincestari** [comment]
No, unfortunately not. None of the caches built by Apollo support encryption. You will need to build your own cache, persisted or in-memory, if you need the data to be encrypted.
