### ISSUE TITLE
How to integrate Apollo iOS SDK 1.x version using cocoapods?

### ISSUE THREAD

**Issue by ravikanthm36** [apollographql/apollo-ios#3103]
### Question

I'm trying to integrate Apollo SDK version 1.x using cocoapods.

I have added **pod "Apollo"** in podfile and successfully downloaded **(Apollo (1.0.7) version)**

Trying to Setup and run code generation (https://www.apollographql.com/docs/ios/get-started#4-setup-and-run-code-generation) using below commands.

./Pods/Apollo/apollo-ios-cli ${Command Name} -${Command Arguments}

Can you please provide the  ${Command Name} -${Command Arguments} to proceed next step 

To Initialize the code generation configuration, I have updated the command as below

./Pods/Apollo/apollo-ios-cli init --schema-namespace GraphQLAPI  --module-type embeddedInTarget --target-name myTestApp         -------- is this correct approach? 

By using SPM, I have completed above steps successfully using below commands

./apollo-ios-cli init --schema-name GraphQLAPI --module-type swiftPackageManager
./apollo-ios-cli generate

How to do equivalent approach when we use cocoapods?

Environment : 
Xcode 14.3.1
iOS 16.4
Swift 5
Apollo SDK 1.0.7 

thanks in advance 

Please let me know if anything missed.

**Comment by BobaFetters** [comment]
@ravikanthm36 So the cli commands will always be the same no matter which approach you take for including the package, the only difference is the location of the CLI executable relative to your project directory. So for instance your call using a SPM implementation is:
`./apollo-ios-cli init --schema-name GraphQLAPI --module-type swiftPackageManager`

The equivalent call for a Cocoapods implementation would be:
`./Pods/Apollo/apollo-ios-cli init --schema-name GraphQLAPI --module-type swiftPackageManager`

So the location of the CLI executable is different but the commands are still the same.

**Comment by ravikanthm36** [comment]
> @ravikanthm36 did you fix this issue?

Yes @ArunVicky001

**Comment by ArunVicky001** [comment]
Basically these two commands will generate `apollo-codegen-config.json` file 

```
./apollo-ios-cli init --schema-name GraphQLAPI --module-type swiftPackageManager

./Pods/Apollo/apollo-ios-cli init --schema-name GraphQLAPI --module-type swiftPackageManager
```

and even after that we can make changes in the config file 

"schemaTypes" : {
      "path" : "./ServerAPI",
      "moduleType" : {
        "embeddedInTarget" : {
          "name" : "MyApp"
        }
      }
    }

moduleType can either embeddedInTarget or swiftPackageManager accordingly the models will be created.  

@BobaFetters I have created the package but after that I have added the package in the Xcode project However I am unable see the classes inside the package, could you please share the exact way to import the package in Xcode project?

**Comment by ArunVicky001** [comment]
@ravikanthm36 Thanks for your response, I can also able to generate models by using pod command but it gives multiple error in the generated models [https://github.com/apollographql/apollo-ios/issues/3106](url) 
hence I am planning to use packages like this tutorial [https://github.com/apollographql/iOSTutorial](url)

after upgrading 1.2.0 version did you get any errors in the models?

**Comment by ravikanthm36** [comment]
@ArunVicky001  Can you ping me(ravikanthm36@gmail.com) in  hangouts, we can discuss there

**Comment by ArunVicky001** [comment]
Sure!!
