### ISSUE TITLE
Apollo client 1.2.0 version pod update gives multiple error 

### ISSUE THREAD

**Issue by ArunVicky001** [apollographql/apollo-ios#3106]
### Summary

Hi Team,

In your current project, I have updated the Apollo Client version from 0.53.0 to 1.2.0. However, after the update, I encounter multiple errors(2599 errors) in the generated model classes. I am currently using Xcode 14.3.1 and Swift 5.

<img width="1383" alt="Screenshot 2023-07-06 at 10 40 20 PM" src="https://github.com/apollographql/apollo-ios/assets/34921497/b1dfe25c-f72b-4651-8ea9-bcdaa6050f6b">

please suggest me how to solve this issues. 

### Version

1.2.0

### Steps to reproduce the behavior

`pod 'Apollo', '1.2.0'`

`./Pods/Apollo/apollo-ios-cli init --schema-name Schema --module-type embeddedInTarget --target-name ApolloClientiOS
`

```
{    
    "schemaName": "MyQuery",   
    "options": {        
        "cocoapodsCompatibleImportStatements": true        
    },
    
    "input": {        
        "operationSearchPaths": [            
            "**/*.graphql"            
        ],
        
        "schemaSearchPaths": [            
            "/Users/vignesh.arunagiri/Documents/XCode/ClientiOS/Schema/schema.json"            
        ]        
    },
    
    "output": {        
        "testMocks": {            
            "none": {}            
        },
        
        "schemaTypes": {            
            "path": "./MyQuery",            
            "moduleType": {                
                "embeddedInTarget": {                    
                    "name": "ClientiOS"                    
                }                
            }            
        },
        
        "operations": {            
            "inSchemaModule": {}            
        }
        
    }
}
```
    

```
./Pods/Apollo/apollo-ios-cli generate
```

**Comment by ArunVicky001** [comment]
it shows error in Fragment, DataDict, FragmentContainer, Apollo.ParentType

**Comment by calvincestari** [comment]
Hi. Are you using SwiftLint in your project? This error looks like a violation of the SwiftLint rule [`identifier_name`](https://realm.github.io/SwiftLint/identifier_name.html#:~:text=Identifier%20Name,too%20long%20or%20too%20short.). You should disable SwiftLint for all generated code files.

**Comment by ArunVicky001** [comment]
yes the issues are coming because of SwiftLint I had disabled the identifier rule, but the new version  I could see this `GraphQLNullable` was added in the generated models it shows so many errors in the existing classes. is that any other way to not using this class? or can we disable the this?

**Comment by calvincestari** [comment]
No, `GraphQLNullable` is needed to be able to support nullability in GraphQL.

**Comment by ArunVicky001** [comment]
okay, if can see the below example I need to pass the array values as an argument of my AnswerCheckboxesInput class init function,  can you please tell me the way to pass the values by using GraphQLNullable because this statement bit confusion 

```
let values: [AnswerCheckboxInput]

public struct AnswerCheckboxesInput: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    items: GraphQLNullable<[AnswerCheckboxInput?]> = nil
  ) {
    __data = InputDict([
      "items": items
    ])
  }

  public var items: GraphQLNullable<[AnswerCheckboxInput?]> {
    get { __data["items"] }
    set { __data["items"] = newValue }
  }
}


AnswerCheckboxesInput(items: values) // here the values shows an error below 
_Cannot convert value of type '[AnswerCheckboxInput]' to expected argument type 'GraphQLNullable<[AnswerCheckboxInput?]>'_

```

**Comment by BobaFetters** [comment]
@ArunVicky001 There is a [post](https://community.apollographql.com/t/optional-array-graphqlnullable-init/6300/3) over on our community forums that talks more about this and links out to the docs for `GraphQLNullable`

**Comment by ArunVicky001** [comment]
`GraphQLNullable` older version it was not there why it's introduced in the newer version?

**Comment by calvincestari** [comment]
> `GraphQLNullable` older version it was not there why it's introduced in the newer version?

The previous Apollo versions used double optionals (`??`) to represent `null` vs `nil` input values. This was unclear to most users, complicates reading and understanding the code in many situations and we found that it led to unintentional errors. `GraphQLNullable` is the new way in 1.0 to provide a clear, albeit more verbose, type to work with nullability in GraphQL.

**Comment by ArunVicky001** [comment]
In the previous version of Apollo client, when we generated the `GraphQLFragment` class, it included both read and write properties. However, in the new version of Apollo client, the models within the `Fragment` only have read-only properties.

This means that in the new version, the properties within the generated Fragment class are only accessible for reading, and you cannot assign new values to those properties directly. The properties are designed to provide access to the data retrieved from the GraphQL server.

version 1.3.0
```
public struct TaskAttributes: SelectionSet, Fragment {

.....
  public var description: String? { __data["description"] }
.....

```

version 0.58.0
```
public struct TaskAttributes: GraphQLFragment {
.......
public var description: String? {
    get {
      return resultMap["description"] as? String
    }
    set {
      resultMap.updateValue(newValue, forKey: "description")
    }
  }
........
```

did you notice this changes?

**Comment by calvincestari** [comment]
@ArunVicky001 all these details are covered in the migration guides. I recommend reading the [migration guide for `1.0`](https://www.apollographql.com/docs/ios/migrations/1.0) first and then the later versions if you're going directly to `1.3`.

**Comment by ArunVicky001** [comment]
I have successfully migrated the my `apollo-client` version from `0.53.0` to `1.3.2` 
but now I am facing some other issues related with the execution older version giving the result, new version is not giving result is it because of the `GraphQLNullable` validation. please correct me if I am wrong/  

could you please see the below code and suggest me the right way to hit the query 

// Sample GraphQL Mutation and Struct Definitions

// 1. Sample GraphQL Mutation - QuestionCreateMutation
```
public class QuestionCreateMutation: GraphQLMutation {
  public static let operationName: String = "QuestionCreate"
  public static let operationDocument: ApolloAPI.OperationDocument = .init(
    definition: .init(
      #"mutation QuestionCreate($input: QuestionCreate) { questionCreate(input: $input) { ...QuestionFact __typename } }"#,
      fragments: [QuestionFact.self, Permission.self]
    ))

  public var input: GraphQLNullable<QuestionCreate>

  public init(input: GraphQLNullable<QuestionCreate>) {
    self.input = input
  }
}
```


// 2. Sample Struct - QuestionCreate
```
public struct QuestionCreate: InputObject {
  public private(set) var __data: InputDict

  public init(_ data: InputDict) {
    __data = data
  }

  public init(
    id: GraphQLNullable<ID> = nil,
    name: String,
    parent: GraphQLNullable<ID> = nil,
    questionType: String,
    boolean: GraphQLNullable<AnswerBooleanInput> = nil,
    checkboxes: GraphQLNullable<AnswerCheckboxesInput> = nil,
    singleselect: GraphQLNullable<AnswerSingleSelectInput> = nil,
    freeform: GraphQLNullable<AnswerFreeFormInput> = nil,
    date: GraphQLNullable<AnswerDateInput> = nil,
    numeric: GraphQLNullable<AnswerNumericInput> = nil
  ) {
    __data = InputDict([
      "id": id,
      "name": name,
      "parent": parent,
      "questionType": questionType,
      "boolean": boolean,
      "checkboxes": checkboxes,
      "singleselect": singleselect,
      "freeform": freeform,
      "date": date,
      "numeric": numeric
    ])
  }

  public var id: GraphQLNullable<ID> {
    get { __data["id"] }
    set { __data["id"] = newValue }
  }
…….
}
```

// Example Usage
```
let createFact = QuestionCreateMutation(input: QuestionCreate(name: QA.question, questionType: "FreeForm", freeform: AnswerFreeFormInput(value: QA.answer)))

 client.perform(mutation: createFact) { result in
   switch result {
   case .success(let graphQLResult):
   case .failureWithError(let error):
      // Handle the failure case here
   }
 }
```
 
usage

 ```
 let createFact = QuestionCreateMutation(input: GraphQLNullable(QuestionCreate(name: QA.question, questionType: "FreeForm", freeform: GraphQLNullable(AnswerFreeFormInput.init(value: QA.answer)))))

client.perform(mutation: createFact) { result in
switch result {
   case .success(let graphQLResult):
   case .failureWithError(let error):
		// failure case is executing 
}
 
```

**Comment by ArunVicky001** [comment]
@calvincestari var toUserAndTeams: UsersAndTeamsValue {
        let userandTeamsDataDict = DataDict(data: [
            "id" : id,
            "name" : name,
            "email" : email,
            "phoneNumber" : phoneNumber,
            "avatar" : avatarURL,
            "userType" : userType,
            "outOfOffice" : outOfOffice,
            "outOfOfficeMessage" : outOfOfficeMessage
        ], fulfilledFragments: Set<ObjectIdentifier>())
        return UsersAndTeamsValue(_dataDict: userandTeamsDataDict)
    }
    
    if you look at the above code what needs to be set as fulfilledFragments value? 
    here this  fulfilledFragments fail when I tried to typecast the UsersAndTeamsValue in the runtime 
    
    could you please suggest the right way to set the values here?

**Comment by calvincestari** [comment]
@ArunVicky001 - I'm away until the 27th. I can help you when I'm back or @BobaFetters might be able to assist.

**Comment by ArunVicky001** [comment]
@BobaFetters please suggest your thoughts

**Comment by BobaFetters** [comment]
@ArunVicky001 if `UsersAndTeamsValue` is your operation then for the fulfilled fragments I believe you will need to do `fullfilledFragments: [ ObjectIdentifier(UsersAndTeamsValue.Data.self) ]`

**Comment by AnthonyMDev** [comment]
You should not ever be using the `init(_data: DataDict)` initializer. This is an internal usage only API. Figuring out exactly what needs to be in the `fulfilledFragments` set is a complicated algorithm that needs to be done perfectly correct in order for your models to function. Which is why you should not be doing that manually.

The JSON initializer you are using in your last post works well, but you have to make sure your json includes valid values for all fields that are expected to be present for the type. That's why it's a throwing initializer. But if your JSON is valid and it doesn't throw, the `fulfilledFragments` are computed for you correctly in that case.

I think the actual safest way for you to do this is using generated initializers. By setting the `selectionSetInitializers` configuration option you can have type safe initializers generated for your models. See documentation here: https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#output-options

**Comment by ArunVicky001** [comment]
@AnthonyMDev I still don't understand how to use `selectionSetInitializers` 
here is my `UsersAndTeamsValue` class 
[UsersAndTeamsValue.graphql.swift.zip](https://github.com/apollographql/apollo-ios/files/12372116/UsersAndTeamsValue.graphql.swift.zip)

```
let jsonObject: JSONObject = [
            "__typename" : "User",
            "id" : id,
            "name" : name,
            "email" : email,
            "phoneNumber" : phoneNumber,
            "avatar" : avatarURL,
            "userType" : userType,
            "outOfOffice" : outOfOffice,
            "outOfOfficeMessage" : outOfOfficeMessage
        ]
        let data = try! UsersAndTeamsValue.init(data: jsonObject)
```

please tell me the way use the `selectionSetInitializers`
