### ISSUE TITLE
Apollo cli introspection header injection

### ISSUE THREAD

**Issue by alessdiimperio** [apollographql/apollo-ios#3107]
### Use case

We are migrating from 0.53.x to 1.3 and are trying to wrap our heads around introspection.

Previously we used the older codegen.sh script from a build phase script to fetch the schema. 
we would download the schema providing an introspection header/key using .env variables source'd in the build phase script.

/run-bundled-codegen.sh schema:download --header="INTROSPECTION_HEADER: ${GRAPHQL_INTROSPECTION_KEY}" --endpoint="${GRAPHQL_ENDPOINT}

When migrating over to v1.3 it seems that introspection is done using a apollo-codegen-config.json file where within you can set the headers and it works as expected.
./Pods/Apollo/apollo-ios-cli --path <path to config>

The problem with this is that it requires that our introspection key is in the config file which will have to be tracked by git if we want it to be available in our Bitrise CI/CD pipeline. Previously we could inject our keys/secrets into the buildphase scripts from a .env file and not have to expose any keys/secrets in our project structure on git.

is there some workaround to this so that we can pass in an undocumented arg for a header?

### Describe the solution you'd like

I would very much like to be able to add a header as an argument when calling the apollo-ios-cli to allow for validated introspection.

./Pods/Apollo/apollo-ios-cli --path <path to config> --header="INTROSPECTION_HEADER: ${GRAPHQL_INTROSPECTION_KEY}"

**Comment by alessdiimperio** [comment]
or if one could inject a key that if passed in as an argument will be added to the default headers 🤷

**Comment by calvincestari** [comment]
Hi @alessdiimperio - unfortunately we don't have support for secrets in the JSON configuration yet which is painful I know.

The only other way would be to change from using the JSON configuration + CLI to invoking code generation directly from code. That way you could read in the secrets via Swift and pass them directly into the codegen functions.

**Comment by calvincestari** [comment]
[Here](https://github.com/apollographql/iOSCodegenTemplate/blob/main/ApolloCodegen/Sources/ApolloCodegen/main.swift) is a project template we had for the older 0.x versions but moved away from it when the CLI was introduced.

I'm going to close this issue since there is already https://github.com/apollographql/apollo-ios/issues/2707 that we have to work against for supporting environment variables in the JSON configuration.
