### ISSUE TITLE
How to convert the generated models into a swift package 

### ISSUE THREAD

**Issue by ArunVicky001** [apollographql/apollo-ios#3109]
Hi 

In your current project, I have updated the Apollo Client version from 0.53.0 to 1.2.0. 

`pod 'Apollo', '1.2.0'`

`./Pods/Apollo/apollo-ios-cli init --schema-name myschema --module-type embeddedInTarget --target-name ApolloClientiOS `

After updating the Apollo Client library, you used the Apollo CLI command `./Pods/Apollo/apollo-ios-cli` `init` to `generate` the models in your source directory. Now, you want to convert the generated models folder into a Swift package.

could you please guide me the procedure to change the modules into a package

**Comment by BobaFetters** [comment]
Transferring this issue to the apollo-ios repo as it is not related to the iOS Tutorial.

As for your question, you need to change you `--module-type` to `swiftPackageManager` documentation on the options available can be found [here](https://www.apollographql.com/docs/ios/code-generation/codegen-cli)

**Comment by ArunVicky001** [comment]
you mean like this? 

`./Pods/Apollo/apollo-ios-cli init --schema-name myschema swiftPackageManager embeddedInTarget --target-name ApolloClientiOS `

**Comment by BobaFetters** [comment]
No it should be `--module-type swiftPackageManager`

**Comment by ArunVicky001** [comment]
`./Pods/Apollo/apollo-ios-cli init --schema-namespace ServerAPI --module-type swiftPackageManager --target-name ApolloClientiOS`

I got this error even after setting cocoapodsCompatibleImportStatements to false. is that anything needs to be changed?   

Error: The codegen configuration has conflicting values: cocoapodsCompatibleImportStatements cannot be set to 'true' when the output schema types module type is Swift Package Manager. Change the cocoapodsCompatibleImportStatements value to 'false', or choose a different module type, to resolve the conflict.


apollo-codegen-config.json

```
{
  "schemaNamespace" : "ServerAPI",
  "options" : {
    "cocoapodsCompatibleImportStatements" : false
  },
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "/Users/vignesh.arunagiri/Documents/MyApp/schema.json"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : "./ServerAPI",
      "moduleType" : {
        "embeddedInTarget" : {
          "name" : "MyApp"
        }
      }
    },
    "operations" : {
      "inSchemaModule" : {
      }
    }
  }
}
```

**Comment by BobaFetters** [comment]
It's exactly as the error states, you can't use both cocoapods and spm, so you need to change the `cocoapodsCompatibleImportStatements` to false or not use the spm module type.

**Comment by ArunVicky001** [comment]
that's what I have changed in my apollo-codegen-config.json, I think thats the place we need to change cocoapodsCompatibleImportStatements to false
