### ISSUE TITLE
How to convert GraphQL query object to Swift.Data type? 

### ISSUE THREAD

**Issue by harshchitrla** [apollographql/apollo-ios#3110]
### Question

I'm trying to implement GraphQL in our existing project where the DAOs have already been written. I do not want to do any changes to the view layer. 

I would like to do changes on the service layer where I would like to convert the result received from the fetch method to the existing DAO. Is there any way we can do that?

**Comment by AnthonyMDev** [comment]
You can definitely use your own view model layer, but I'm not really sure I understand what you want to do by converting to a `Swfit.Data` type.

If you want to use a persistence layer outside of the Apollo normalized cache, you're going to be losing a lot of the benefit of Apollo and GraphQL in general, but you can do it. If you want to convert our result object into your own models, I recommend creating an adapter layer that takes the generated models that are returned from the client's completion handler and initializes your other models directly.

**Comment by AnthonyMDev** [comment]
Since this isn't an actionable item for us, I'm going to close this issue, but I'm happy to continue the discussion and answer any other questions you have.
