### ISSUE TITLE
Mock GraphQL server - Failed to demangle superclass of JSONRequest

### ISSUE THREAD

**Issue by gmoraleda** [apollographql/apollo-ios#3111]
### Question

We are in the process of migrating Apollo from 0.53 to 1.3.
The last remaining piece is getting unit tests working.

We use a mocked server with a mocked network transport (1:1 to the one located in `Apollo/Test/ApolloInternalTestHelpers`).

This approach worked successfully in the past. We mock the server and define the expected operation setting the appropriate mocked result.

Since the migration, our tests have broken.

The app crashes in the `RequestChainNetworkTransport`, while initializing JSONRequest:

```swift
  open func constructRequest<Operation: GraphQLOperation>(
    for operation: Operation,
    cachePolicy: CachePolicy,
    contextIdentifier: UUID? = nil) -> HTTPRequest<Operation> {
    JSONRequest(operation: operation,
                graphQLEndpoint: self.endpointURL,
                contextIdentifier: contextIdentifier,
                clientName: self.clientName,
                clientVersion: self.clientVersion,
                additionalHeaders: self.additionalHeaders,
                cachePolicy: cachePolicy,
                autoPersistQueries: self.autoPersistQueries,
                useGETForQueries: self.useGETForQueries,
                useGETForPersistedQueryRetry: self.useGETForPersistedQueryRetry,
                requestBodyCreator: self.requestBodyCreator)
  }
```

with the following error:
>failed to demangle superclass of JSONRequest from mangled name '\^B\M-y\M^^\^O': subject type x does not conform to protocol GraphQLOperation.

This is the stack trace:

![image](https://github.com/apollographql/apollo-ios/assets/25835012/8acbd713-8b70-416a-8977-227d37c03299)

I would be really grateful for any hint related to this issue.

**Comment by calvincestari** [comment]
This looks like a duplication of #2982 - take a look at [this comment](https://github.com/apollographql/apollo-ios/issues/2982#issuecomment-1622520184).

@gmoraleda - are you seeing warnings like `Class {symbol} is implemented in both {libraryA} and {libraryB}`?
