### ISSUE TITLE
apollo-ios-cli mock code generation fails for string arrays

### ISSUE THREAD

**Issue by Kn3cht** [apollographql/apollo-ios#3130]
### Summary

I tried out the code generation for mock objects and stubled upon an issue related to the `_setList` invocation of the initializer of the generated `MockObjects`. 

For all of those invocations I'm getting the compiler error 
```
Type of expression is ambiguous without more context
```

I alreay read through this related issue: [https://github.com/apollographql/apollo-ios/issues/3023](#3023). However in my case it even fails for string arrays.

Any help / workarounds for the meantime are appreciated.

### Version

v1.3.1

### Steps to reproduce the behavior

Example fragment
```graphql
fragment HumanName on HumanName {
    id
    ...
    maidenNames # [String]
}
```

Generated:
```swift
public extension Mock where O == HumanName {
  convenience init(
    id: String? = nil,
    ...
    maidenNames: [String]? = nil,
  ) {
    self.init()
    _setScalar(id, for: \.id)
    ...
    _setList(maidenNames, for: \.maidenNames) // <- Causing the compiler error
  }
}

```

iOS Version: 15
Xcode Version: 14.3.1

**Comment by calvincestari** [comment]
Thanks for the bug report @Kn3cht. I believe we have a fix for this already in https://github.com/apollographql/apollo-ios/pull/3120 which is merged into `main` but not yet released. We're planning to publish a patch release this week which will include that fix but if you wanted to test it you could point your dependency at the `main` branch and see if it resolves your issue.

**Comment by calvincestari** [comment]
@Kn3cht - the fix I mentioned earlier has just been released in [`1.3.2`](https://github.com/apollographql/apollo-ios/releases/tag/1.3.2). Please try that and let me know whether it resolves your issue.

**Comment by Kn3cht** [comment]
@calvincestari Thx for the fast reply. 
Just updated to v1.3.2 but unfortunately the issue still persists.

**Comment by ski-u** [comment]
I have the same issue for enum (which has String rawValue) arrays with apollo-ios v1.3.2.

<img width="1050" alt="スクリーンショット 2023-07-24 10 47 02" src="https://github.com/apollographql/apollo-ios/assets/37182704/d31dc7fe-ff64-44ef-9c7f-9ddcedb6b4d7">

That enum is like this ↓

```swift
public enum MyEnum: String, EnumType {
  case front = "FRONT"
  case left = "LEFT"
  case right = "RIGHT"
}
```

**Comment by jarrodrobins** [comment]
I am having the same issue. For me, the last working version of Apollo is 1.1.2 as a result of issues with mock generation.

**Comment by BobaFetters** [comment]
Thanks for the additional reports and use cases, we will look into this as soon as we can.

**Comment by BobaFetters** [comment]
The fix for this has been merged into main and will go out with the next patch release. If you would like to verify this fixes the issue for you can try pointing your dependency to `main`.

**Comment by cswelin** [comment]
I've pointed to main and still seeing an error similar to https://github.com/apollographql/apollo-ios/issues/3130#issuecomment-1647090145

> Instance method '_setList(_:for:)' requires that 'GraphQLEnum<GenerateNewRecoveryCodeForAccountError>' conform to 'MockFieldValue'

on the line 
> _setList(errors, for: \.errors)

Enum looks like

```
public enum GenerateNewRecoveryCodeForAccountError: String, EnumType {
  case enrollmentNotFound = "ENROLLMENT_NOT_FOUND"
}

```

**Comment by BobaFetters** [comment]
@cswelin Just to verify, after point to `main` did you re-run code generation? That would be required for the files to be updated.

**Comment by cswelin** [comment]
> @cswelin Just to verify, after pointing to `main` did you re-run code generation? That would be required for the files to be updated.

ah shoot, I missed the codegen package dependencies to point to main, that fixed it thank you.
