### ISSUE TITLE
CLI code generation error when the server schema has types with long names

### ISSUE THREAD

**Issue by oliveira-marcio** [apollographql/apollo-ios#3131]
### Summary

After downloading the server's schema with the Apollo CLI, I'm facing this issue when running the generate command from the CLI:
```
$ ./Pods/Apollo/apollo-ios-cli generate   
Error: cannotCreateFile(at: "/Users/moliveira/ios-apps/iOSApp/LetsGetChecked/ResultsNarrativesAPI/Schema/Objects/ContainerColumnsOrCallToActionBannerOrContainerSectionTwoColumnOrFaqOrSectionComparisonTableOrSectionGridOrSectionHeroOrSectionIconCarouselOrSectionLogosOrSectionOneColumnOrSectionProductCardsOrSectionReviewsOrSectionStepsOrSectionTabbedInformationOrSectionTestimonialCarouselOrSectionTrustpilot.graphql.swift")
```
Other files from schema were properly created with the CLI command but this one failed because this object name has more than 255 characters (the MacOS limitation for file names).

### Version

1.3.1

### Steps to reproduce the behavior

1) Run the CLI `fetch-schema` command to download the server schema (`schema.graphqls`) with some long object inside. Example:
```
type ContainerColumnsOrCallToActionBannerOrContainerSectionTwoColumnOrFaqOrSectionComparisonTableOrSectionGridOrSectionHeroOrSectionIconCarouselOrSectionLogosOrSectionOneColumnOrSectionProductCardsOrSectionReviewsOrSectionStepsOrSectionTabbedInformationOrSectionTestimonialCarouselOrSectionTrustpilot implements Entry {
  sys: Sys!
  contentfulMetadata: ContentfulMetadata!
  linkedFrom(allowedLocales: [String]): ContainerColumnsOrCallToActionBannerOrContainerSectionTwoColumnOrFaqOrSectionComparisonTableOrSectionGridOrSectionHeroOrSectionIconCarouselOrSectionLogosOrSectionOneColumnOrSectionProductCardsOrSectionReviewsOrSectionStepsOrSectionTabbedInformationOrSectionTestimonialCarouselOrSectionTrustpilotLinkingCollections
  internalName(locale: String): String
}
```
2) Run the CLI `generate` command with a `.graphql` operation file in the same downloaded schema file folder

### Logs

```shell
Error: cannotCreateFile(at: "/Users/moliveira/ios-apps/iOSApp/LetsGetChecked/ResultsNarrativesAPI/Schema/Objects/ContainerColumnsOrCallToActionBannerOrContainerSectionTwoColumnOrFaqOrSectionComparisonTableOrSectionGridOrSectionHeroOrSectionIconCarouselOrSectionLogosOrSectionOneColumnOrSectionProductCardsOrSectionReviewsOrSectionStepsOrSectionTabbedInformationOrSectionTestimonialCarouselOrSectionTrustpilot.graphql.swift")
```

**Comment by drjackyl** [comment]
I have the very same problem with types created by Contentful. Those are ridiculously long and I would also like to make Contentful aware of this.

Fortunately, I don't need those types for my queries and I can manually remove them from the schema.

I couldn't find an option to exclude types from the schema in the apollo config, that would help me already. But for those who need to use those types, it's a bad situation.

**Comment by calvincestari** [comment]
Hi 👋🏻 - I don't really have a good answer to this other than the type should be renamed.

I think Apollo Kotlin suffers the same problem but their codegen engine has the ability to include/exclude types based on a regex pattern; Apollo iOS doesn't have that feature. I don't think adding filename length logic to our codegen engine is appropriate because that may cause other issues when the directory paths exceed 255 characters causing the file to be created somewhere else entirely; my answer in that case would be similarly to trim down the directory paths.

A local script to rename the type before codegen could be used but that's tedious and would have to be done before each run of code generation.

> I couldn't find an option to exclude types from the schema in the apollo config, that would help me already. But for those who need to use those types, it's a bad situation.

Yes, when those types are being used the only option is to rename them them. A custom directive would be particularly useful here.

**Comment by oliveira-marcio** [comment]
I was in touch with Contentful support today and they said they just released a fix today to handle those long names (I couldn't test yet because the space I'm consuming doesn't belong to my team so I couldn't refresh the schema yet). Still, these long names are generated by Contentful itself when building the server schema to download. It's not something we could just rename. Anyway, can't the CLI detect those large names during the code generation and try to truncate (or ask for user suggestion) only the filename keeping the object name inside as it is? I think this might mitigate the problem.

**Comment by calvincestari** [comment]
We're deliberating about this within the team but IMO a custom directive is still the correct way to solve this and a few other use cases too.

**Comment by calvincestari** [comment]
We've decided as a team that a custom directive to rename a schema type is the preferred solution.

I've added it to our [Minor Releases](https://github.com/apollographql/apollo-ios/milestone/72) milestone but it has no particular delivery date attached to it. We're always willing to work with community contributions if a feature is needed sooner than we can get to implementing it.

**Comment by AnthonyMDev** [comment]
We're going to track this feature in #3283 which we hope to begin work on shortly.
