### ISSUE TITLE
apollo-ios-cli code generation fails for fragment containing double quotes.

### ISSUE THREAD

**Issue by ji-no** [apollographql/apollo-ios#3134]
### Summary

If the fragment contains double quotes, a compile error will occur because the double quotes are not escaped in the fragmentDefinition of the generated code.

### Version

v1.3.2

### Steps to reproduce the behavior

Example fragment
```
fragment ExampleFragment on Example {
  field(parameter: "value")
}
```
Generated:
```
public struct ExampleFragment: SelectionSet, Example {
  public static var fragmentDefinition: StaticString {
    "fragment ExampleFragment on Example { __typename field( parameter: "value" ) }"
  }
```

**Comment by BobaFetters** [comment]
Thanks for reporting this,  I will take a look at this today.

**Comment by BobaFetters** [comment]
The fix for this has been merged into main and will go out with our next patch release.
