### ISSUE TITLE
./apollo-ios-cli init --schema-namespace [namespace] --module-type [moduletype] is not generating apollo-codegen-configuration.json

### ISSUE THREAD

**Issue by ArunVicky001** [apollographql/apollo-ios#3137]
### Question

Hello Team,

I hope you're doing well. I am facing an issue while trying to integrate the Apollo Client library into my new Xcode project using Swift Package Manager (SPM).

Here are the details of my setup:

```
Xcode version: 14.3.1
Apollo Client version: 1.3.0
```
Package repository: [github.com/apollographql/apollo-ios.git](https://github.com/apollographql/apollo-ios.git)
I followed the instructions provided in this document [link: https://www.apollographql.com/docs/ios/tutorial/codegen-getting-started] to add the Apollo Client package to my project. However, when trying to add the configuration file `apollo-codegen-configuration.json` , I encountered the following error:

Command:
`./apollo-ios-cli init --schema-namespace StarWarsAPI --module-type swiftPackageManager
`

Error:

`zsh: no such file or directory: ./apollo-ios-cli
`
Just to ensure that I have Apollo CLI installed, I ran the command `apollo --version`, and it shows the version as follows:

`apollo/2.34.0 darwin-arm64 node-v18.16.0
`

After some research, I came across this link [link: https://www.npmjs.com/package/apollo-cli?activeTab=dependents], which states that apollo-cli has been renamed to 'apollo'. So, I tried the following commands, but still faced errors:

```
./apollo-ios init --schema-namespace StarWarsAPI --module-type swiftPackageManager
zsh: no such file or directory: ./apollo-ios
```

```
./apollo init --schema-namespace StarWarsAPI --module-type swiftPackageManager
zsh: no such file or directory: ./apollo
```
**Note** other hand I am using apollo-client `pod`, `Apollo Client version: 1.3.0 `
using this command I can able to create 

I can able to create `apollo-codegen-configuration.json` by using below command 

`./Pods/Apollo/apollo-ios-cli init --schema-namespace ApolloSchema --module-type embeddedInTarget --target-name ApolloClient_1.3.0
`

<img width="975" alt="Screenshot 2023-07-24 at 4 57 05 PM" src="https://github.com/apollographql/apollo-ios/assets/34921497/8cdb3cf6-ee67-4aef-845f-8b291fc0f0f0">

Could you please suggest the correct approach to configure the Apollo-Client/apollo/apollo-cli properly in my Xcode project?

Thank you for your assistance.

**Comment by BobaFetters** [comment]
It sounds like you havn't installed the CLI into your project, you can do so by following the instructions [here](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#installation), under the "SPM with Xcode project" dropdown. Running the "Install CLI" plugin mentioned there will install the CLI into your project directory.

The other version of apollo you mentioned and showed in your screenshot looks to be the web version of the apollo client.

**Comment by calvincestari** [comment]
@BobaFetters is correct, the [apollo-tooling](https://github.com/apollographql/apollo-tooling) repo is not for iOS code generation. It was used in the legacy (0.x) versions when we still relied on a Typescript implementation of the code generation engine. We no longer use it in 1.0.

**Comment by ArunVicky001** [comment]
Thanks for your response, I will look into it

**Comment by calvincestari** [comment]
I think we can close this issue. @ArunVicky001 if you still have issues using the correct CLI tool let us know and we'll look into it again.
