### ISSUE TITLE
apollo-ios-cli says my apollo version is an old one

### ISSUE THREAD

**Issue by jostster** [apollographql/apollo-ios#3153]
### Summary

When running apollo-ios-cli commands for fetch-schema and generate it says my CLI version is 1.3.2 but my Apollo version is 1.2.0. Looking in Xcode I can confirm my apollo version is 1.3.2. I have even deleted my DerivedData and tried it again and still says it is 1.2.0.

### Version

1.3.2

### Steps to reproduce the behavior

Update from an older SPM to 1.3.2 and run the following commands.
```sh
#!/usr/bin/env bash
echo "Fetching schema from stage..."
./apollo-ios-cli fetch-schema
echo "Schema fetched!"
echo "Removing old fragment files"
rm Project/Services/GraphQL/ProjectAPI/Sources/Fragments/*
echo "Old fragments removed. Generating new graphql files..."
./apollo-ios-cli generate --ignore-version-mismatch
echo "GraphQL files generated. Renaming fragments to prevent collisions..."
for f in Project/Services/GraphQL/ProjectAPI/Sources/Fragments/*.swift; do mv "$f" "${f/graphql/fragment}"; done
echo "GraphQL generation complete!"
```

### Logs
<img width="124" alt="image" src="https://github.com/apollographql/apollo-ios/assets/278510/37afb850-cf94-4944-926f-4d0a4876460f">

```shell
Old fragments removed. Generating new graphql files...
Warning: Apollo Version Mismatch
We've detected that the version of the Apollo Codegen CLI does not match the version of the
Apollo library used in your project. This may lead to incompatible generated objects.

Please update your version of the Codegen CLI by following the instructions at:
https://www.apollographql.com/docs/ios/code-generation/codegen-cli/#installation

CLI version: 1.3.2
Apollo version: 1.2.0
```

### Anything else?

The CLI is being installed with the xcode plugin install

**Comment by BobaFetters** [comment]
@jostster what does the contents of your `Package.resolved` file look like?

**Comment by jostster** [comment]
@BobaFetters 
```
{
      "identity" : "apollo-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apollographql/apollo-ios.git",
      "state" : {
        "revision" : "97ad4f5b41f003f4f283c5f3386fb773af17aa67",
        "version" : "1.3.2"
      }
    },
    ```

**Comment by BobaFetters** [comment]
Is your dependency being managed through SPM (Package.swift) or through Xcode with SPM? There is likely a stale state somewhere and the location the cli checks its version against varies depending on how the dependency was included. We have seen this report before you can see another discussion [here](https://github.com/apollographql/apollo-ios/issues/2946#issuecomment-1637164917), its possible something like whats described in that comment may help depending on your setup.

**Comment by BobaFetters** [comment]
Also any further info you can provide regarding your project structure etc would be helpful in trying to investigate the issue, or even a sample project that demonstrates the issue.

**Comment by jostster** [comment]
@BobaFetters Thanks so much for that link. I did a search for `apollo-ios-cli` but didn't see that one come up or overlooked it. I do use a workspace like they do and looking into the .xcodeproj it does show a stale version of 1.2.0 in in the project while the workspace shows 1.3.2.

**Comment by BobaFetters** [comment]
No problem, glad you got it sorted out.

**Comment by calvincestari** [comment]
We have an [outstanding PR](https://github.com/apollographql/apollo-ios/pull/3048) related to version checking. I wonder how that would have affected this issue? 🤔

**Comment by BobaFetters** [comment]
That's a good callout, I imagine getting that PR finished and merged in may alleviate the issue since in this case (and other cases) it was related to having a workspace.
