### ISSUE TITLE
Code generation for Contentful server entries with rich-text attributes

### ISSUE THREAD

**Issue by oliveira-marcio** [apollographql/apollo-ios#3155]
### Summary

Hi, I'm working with the Contentful to and I'm trying to perform some GraphQL queries on it. Some of Contentful entries can contain rich-text attributes. For example, if I perform a query like that, where `text` is a rich-text attribute, I'll receive the response like that:
- Query:
```
query testQuery {
  	richTextItemCollection(
        where: {
            internalName_contains: "Optum - Onsite Appointment - LP - How it works - Grid - Support - Text"
        }
    ) {
        items {
            internalName
            normalTextStyle
            text {
              json 
            }
        }
    }
}
```
- Response:
```
{
  "data": {
    "richTextItemCollection": {
      "items": [
        {
          "internalName": "Optum - Onsite Appointment - LP - How it works - Grid - Support - Text",
          "normalTextStyle": "md",
          "text": {
            "json": {
              "nodeType": "document",
              "data": {},
              "content": [...]
            }
          }
        }
      ]
    }
  }
}
```
The problem with CLI code gen is that it's assuming that `text.json` in the query is a String (when actually is an object) as we can see in the generated model:
```
public struct Item: ResultsNarrativesAPI.SelectionSet {
        public let __data: DataDict
        public init(_dataDict: DataDict) { __data = _dataDict }

        public static var __parentType: ApolloAPI.ParentType { ResultsNarrativesAPI.Objects.RichTextItem }
        public static var __selections: [ApolloAPI.Selection] { [
          .field("__typename", String.self),
          .field("internalName", String?.self),
          .field("normalTextStyle", String?.self),
          .field("text", Text?.self),
        ] }

        public var internalName: String? { __data["internalName"] }
        public var normalTextStyle: String? { __data["normalTextStyle"] }
        public var text: Text? { __data["text"] }

        /// RichTextItemCollection.Item.Text
        ///
        /// Parent Type: `RichTextItemText`
        public struct Text: ResultsNarrativesAPI.SelectionSet {
          public let __data: DataDict
          public init(_dataDict: DataDict) { __data = _dataDict }

          public static var __parentType: ApolloAPI.ParentType { ResultsNarrativesAPI.Objects.RichTextItemText }
          public static var __selections: [ApolloAPI.Selection] { [
            .field("__typename", String.self),
            .field("json", ResultsNarrativesAPI.JSON.self),
          ] }

          public var json: ResultsNarrativesAPI.JSON { __data["json"] }
        }
      }
//----------------------
public typealias JSON = String
```
Therefore, when we perform the same query with Apollo we receive a `JSONDecodingError`because it can't properly decode the actual `json` object in the response.

![image](https://github.com/apollographql/apollo-ios/assets/22889345/c322541c-9b9f-435c-b588-54d0f6913aa7)

If we remove the `text` from the query, rerun CLI generate to update the objects, and perform the query again, the response is successfully decoded.

### Version

1.3.1

### Steps to reproduce the behavior

Query any content from Contentful GraphQL API that contains at least an attribute of RichText Document type.

**Comment by BobaFetters** [comment]
@oliveira-marcio Thanks for reporting this, can you also provide a sample schema to go along with the provided query operation that we can use to debug this issue?

**Comment by calvincestari** [comment]
It looks like you should be using a [custom scalar](https://www.apollographql.com/docs/ios/custom-scalars) type for that object. From `public typealias JSON = String` it seems like `ResultsNarrativesAPI.JSON` may already be specified as a custom scalar in the schema. By default all custom scalars are treated as `String` until you provide the custom implementation for it.

**Comment by oliveira-marcio** [comment]
Hey guys, thanks for the info. 
@calvincestari  It seems Contentful generates those custom scalar json types but it's something beyond our control. Actually, it's the first time I'm hearing about custom scalar types. I'll the link you provided me.

@BobaFetters since the schema is large, are you interested in some particular part of it? Also, I'm not sure how much of it I can share since it might contain sensitive information in some metadata.

**Comment by calvincestari** [comment]
> @calvincestari It seems Contentful generates those custom scalar json types but it's something beyond our control. Actually, it's the first time I'm hearing about custom scalar types. I'll check the link you provided me.

Defining it in the schema will be out of your control but writing the custom scalar logic in Swift should certainly be possible in your project. As you're finding out now, it's required to be able to handle that response object. Apollo iOS cannot glean any information on how to parse that object from the schema.

**Comment by BobaFetters** [comment]
@oliveira-marcio Once you have had a chance to go through the docs @calvincestari linked for the custom scalar implementation, which seems like it should solve your issue, let us know if it doesn't solve the problem or there are further questions and if need be we can sort out getting a sample schema to look at.

**Comment by BobaFetters** [comment]
@oliveira-marcio just checking in to see if you were able to resolve this with a custom scalar implementation?

**Comment by oliveira-marcio** [comment]
@BobaFetters Yeah, sure, go ahead. I'm sorry for not getting back to you sooner. I couldn't try the custom scalar yet because of other priorities and I also went on vacation, but reading the docs you sent to me, it really seems the way to go. I'll let you know when I return to the Apollo implementation on our side. Thank you for the support!
