### ISSUE TITLE
Code generation error with Graphene (python)

### ISSUE THREAD

**Issue by intoxicated** [apollographql/apollo-ios#317]
I'm currently using these versions:

apollo/1.4.0 darwin-x64 node-v8.11.1
apollo-codgen 0.20.2
python flask with graphene 2.1.2
Xcode 9.3

OK, for graphql new comer, I feel really frustrating about Apollo ios. First of all, official documentation is out-dated or misguided. Following every steps from the official documentation doesn't really make a project to build with Apollo iOS. 

I have basically two issue. 

First, the build phase script 
```APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift
```
doesn't work. I added Test.graphql with valid query but build failed with 
```
++ exec apollo-codegen generate --schema schema.json --output API.swift
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/Users/R3alFr3e/.nvm/versions/node/v8.11.1/lib/node_modules/apollo-codegen/src/cli.ts:195:17)
    at Object.runCommand (/Users/R3alFr3e/.nvm/versions/node/v8.11.1/lib/node_modules/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/R3alFr3e/.nvm/versions/node/v8.11.1/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/R3alFr3e/.nvm/versions/node/v8.11.1/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/R3alFr3e/.nvm/versions/node/v8.11.1/lib/node_modules/apollo-codegen/lib/cli.js:202:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Command /bin/sh failed with exit code 1
``` 
which I believe .graphql file did not properly insert into command line execution. 
**(this was caused by placing .graphql into subdirectory.. really..?)**

Second, so I decided to call this command manually like following
```
apollo-codegen generate ./Services/GraphQL/Test.graphql --schema schema.json --output API.swift
```
where schema.json was generated from 
```
apollo schema:download --endpoint=http://localhost:8080/graphql schema.json
```
that turned out failed again with
```
error: GraphQL schema file should contain a valid GraphQL introspection query result
```

Now I have no idea how to get process with this errors and documentation doesn't help at all. 
Additionally,  I tried to get schema.json by executing following command line
```
apollo-codegen download-schema http://localhost:8080 --output schema.json
```
which still gave me same error. By the way, I wonder why `apollo schema:download` and `apollo-codegen download-schema` generated two different schema.json?

**Comment by brennantaylor** [comment]
Recommend adding `cd \"${SRCROOT}/${TARGET_NAME}\"`

Also the script you posted is using `find` which would search recursively but for the current working directory. So you can organize your graphql files into as many sub directories you want (we do this in our project without issue) you just need to make sure find is run from an appropriate root directory.

Also it looks like you are mixing usages of apollo cli and apollo-codegen. I'm not sure how compatible they are so you may need to take care you're using the same tool between your schema download and your codegen.

**Comment by designatednerd** [comment]
@intoxicated Can you please try this with the [updated build script that is now in the docs](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step)? Thanks!

**Comment by designatednerd** [comment]
Hey there - since I haven't heard back in a couple weeks, I'm going to close this issue out. Please keep an eye out for some updated stuff going out with `0.13.0` including the ability to use an up-to-date Apollo CLI version. Please open a new issue if you're still running into problems. Thank you!
