### ISSUE TITLE
Find an alternative to CocoaDocs for API documentation

### ISSUE THREAD

**Issue by farktronix** [apollographql/apollo-ios#318]
The iOS documentation at https://www.apollographql.com/docs/ios/api-reference.html has an API reference, but its entire content is "Please see here."

That link goes to http://cocoadocs.org/docsets/Apollo/0.7.0/, which has a link for documentation that points back to http://dev.apollodata.com/ios/: "Documentation can be found here."

**Comment by farktronix** [comment]
It looks like this is just an issue with 0.7.0-alpha.11 and 0.7.0-alpha.10. The documentation shows up if I select any earlier versions on cocoadocs.org

**Comment by farktronix** [comment]
I'm not sure why Cocoadocs doesn't have any of the more recent tags either- 0.8.0 and 0.9.0 aren't showing up on there, and I get a 404 error if I try to go to them directly by changing the URL

**Comment by martijnwalraven** [comment]
Unfortunately, CocoaDocs no longer generates documentation, see [here](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/). So we'll have to find an alternative.

**Comment by farktronix** [comment]
Looks like this is a dup of #171
