### ISSUE TITLE
Use top level fragments rather than nesting duplicates.

### ISSUE THREAD

**Issue by dpettigrew** [apollographql/apollo-ios#3185]
### Use case

I made some fragments and am using them in three different queries. Apollo generates top level types for the fragments, but then also generates nested types within the three Query structs rather than using the top-level ones. So now for my three queries I have four equivalent structs generated. 
It is a pain point, because to create "wrapped" domain response models I have to either define protocols for each fragment and conform the various generated types to the protocols, or make multiple duplicate initializers for each generated (identical) type.
e.g. If Query A uses fragment A, the generated Query A will have its own nested version of fragment A rather than referencing the top-level fragment A.

Also happens for fragments reusing fragments.
e.g. If fragment B uses fragment A, the generated fragment B will have its own nested version of B rather than referencing the top-level fragment A.

### Describe the solution you'd like

Ideally the generated query and fragment structs actually use the generated top-level structs and not generate and use nested duplicates.

This was version 1.07.

**Comment by josipbernat** [comment]
I am also experiencing the same problem and I would be thrilled if there is an option to define top level fragment.

**Comment by AnthonyMDev** [comment]
This is a really complicated feature for us to add, but it's definitely something we've been wanting to do for a long time. In fact it's tracked as a planned feature as #2191 "Hoisted Types". We're hoping to get this into a 1.x minor release sometime this year.
