### ISSUE TITLE
Documentation of fieldCasing incorrect

### ISSUE THREAD

**Issue by iDylanK** [apollographql/apollo-ios#3191]
### Summary

The newly released feature that supports converting field casing to camelCase is not in line with the documentation.

The [documentation](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration/#output-options) shows that the field is named "fieldCasing".

However, it seems that it has to be added as "fieldAccessors".

### Version

1.4

### Steps to reproduce the behavior

n/a

**Comment by BobaFetters** [comment]
@iDylanK Thanks for catching this, looks like part of the documentation was missed when changing the name of the property before final release, will get this updated today.
