### ISSUE TITLE
How to use Mock objects for query response JSON mocking?

### ISSUE THREAD

**Issue by Mordil** [apollographql/apollo-ios#3194]
### Question

The generated mocks are absolutely a godsend, but the docs are glossing over a test condition that I can see _some_ internal helpers for, but aren't public and I'm not sure how I should be writing my tests to support this

We are trying to mock the response of a query, using a `MockNetworkTransport` that the `ApolloClient` calls, and right now they are giant string-based dictionaries that we'd really like to replace with the generated `Mock` objects - but I'm not seeing how to convert the data into a proper `JSONObject` representation that can be serialized to JSON and then resolved by the GraphQL executors.

In some cases, we end up where we get a lot of `missingValue` decoding errors from the `Mock` object, or otherwise it fails to serialize because it's either not a proper `JSONObject` or is still in it's raw Swift representations.

How can we support the following unit test?

```swift
func testAgreementTemplateSyncJobFetchData() async throws {
    let bodyObject = MockApolloQuery.agreementTemplatesResponse.jsonObject
    let store: ApolloStore = .init(cache: InMemoryNormalizedCache())
    let mockNetworkTransport = Socrates.MockNetworkTransport(body: bodyObject, store: store)
    let client: ApolloClient = .init(networkTransport: mockNetworkTransport, store: store)
    let query = AgreementTemplatesQuery()
    let job = AgreementTemplateSyncJob()

    await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) -> Void in
      client.store.load(query) { result in
        defer { continuation.resume() }
        if case .success = result {
          XCTFail("Cache result must not exist for this query")
        }
      }
    }
    try await job.run(using: client)
    let templates = try await withCheckedThrowingContinuation {
      (continuation: CheckedContinuation<[Oracle.AgreementTemplate]?, Error>) -> Void in

      client.store.load(query) { result in
        do {
          let templates = try result.get().data?.agreementTemplates
          continuation.resume(returning: templates)
        } catch {
          continuation.resume(throwing: error)
        }
      }
    }
    XCTAssertNotNil(templates)
    XCTAssertGreaterThan(templates?.count ?? 0, 0)
  }
```

**Comment by AnthonyMDev** [comment]
There is currently no mechanism for converting the mock objects back into the raw JSON, but we've had this request from a few others recently. It's being tracked by issue #3196. Which is on our backlog.

You can build a helper function to do this yourself, in the mean time, it should look similar to the code in the `convert(value:)` function in the referenced issue. (Though I think that example is missing the code to convert custom scalars back to raw json, which is an easy addition.)
