### ISSUE TITLE
Upgrading to 1.4 Codegen no longer generates file at an operationIdentifiersPath

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#3199]
### Summary

I made no changes to my config, and only see deprecations. Upon changing things to remove the deprecations, I also couldn't get anything to output. It's not clear what Im supposed to do, if anything.

### Version

1.4.0

### Steps to reproduce the behavior

Upgrade from 1.3.0 to 1.4.0 using the `apqs` and `operationIdentifiersPath` codegen configuration. A json file should be output at `operationIdentifiersPath` in 1.3.0, but not in 1.4.0.

**Comment by jimisaacs** [comment]
Figured it out, it was `ApolloCodegen.build(with:withRootURL:itemsToGenerate:)`
I don't remember if 1.3.0 had `itemsToGenerate` in the params, but I wasn't passing anything if so.

I had to pass `itemsToGenerate: .all` for 1.4.0 to match 1.3.0

**Comment by jimisaacs** [comment]
If `generateManifestOnCodeGeneration` is supposed to work by allowing generating the manifest with  `itemsToGenerate: .code`, it's not working.

**Comment by BobaFetters** [comment]
@jimisaacs So the option for handling operation manifest generation is now it's own top level configuration for codegen called [`operationManifest`](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration/#operation-manifest-configuration) which takes in a path (previously the operation identifiers path), whether you want the new `persistedQueries` document format or the `legacy` format used by apqs, and whether you would like the manifest to be generated everytime you run the `generate` command of code generation. There is some documentation [here](https://www.apollographql.com/docs/ios/fetching/persisted-queries) that talks about the new persisted queries and the differences as well as the configuration.

The `itemsToGenerate` in the codegen is new options in `1.4.0` to give us the ability to control whether we are generating code, and operation manifest, or both, to allow use to share overlapping work between the two, and set us up for potentially having more fine control in the future of what to generate.

It sounds like maybe our documentation is lacking and we need to look into how we can update/improve it to provide more clarity on these changes/additions.

**Comment by jimisaacs** [comment]
@BobaFetters thanks! Yeah, no mention of itemsToGenerate because it is focused on the provided CLI which we aren't using.

**Comment by BobaFetters** [comment]
@jimisaacs Thanks for calling that out, definitely an oversight on my part. I'll get some documentation added for the `itemsToGenerate` today. Going to go ahead and close this but can re-open if needed.
