### ISSUE TITLE
How to set global time out?

### ISSUE THREAD

**Issue by PandaZhang530** [apollographql/apollo-ios#3206]
### Question

How to set global time out? After much efforts in looking up, i couldn't  found the api to set timeouts for all http requests.

**Comment by PandaZhang530** [comment]
> You should be able to set a global [request timeout value](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1408259-timeoutintervalforrequest) in the session configuration when used in the [initializer for `URLSessionClient`](https://www.apollographql.com/docs/ios/docc/documentation/apollo/urlsessionclient/init(sessionconfiguration:callbackqueue:)).

Did not find a way to initialize with URLSessionClient

> ### Question
> How to set global time out? After much efforts in looking up, i couldn't found the api to set timeouts for all http requests.

Thanks, this works for me.

**Comment by calvincestari** [comment]
> Did not find a way to initialize with URLSessionClient

There is an [example in the documentation](https://www.apollographql.com/docs/ios/networking/request-pipeline#example-apolloclient-setup).
