### ISSUE TITLE
Sample Project for TestMockFileOutput with swiftPackage(targetName:)

### ISSUE THREAD

**Issue by chasemac** [apollographql/apollo-ios#3207]
### Summary

I'm attempting a migration from version 0.x and I was wondering if you had a sample project for `TestMockFileOutput with swiftPackage(targetName:)`?

### Version

1.4

### Steps to reproduce the behavior

Test Mocks are not working I probably configured something wrong and I would like a sample project for reference.

**Comment by BobaFetters** [comment]
@chasemac Here is a sample project that shows how to configure the test mocks for swift package manager, if you can provide some more detail as to what parts of the process were a hang up for you and what docs you maybe looked at which weren't sufficient in explaining the process I can open an issue to make some docs improvements.
[TestMock-Sample.zip](https://github.com/apollographql/apollo-ios/files/12486817/TestMock-Sample.zip)
