### ISSUE TITLE
Synchronously get data from cache

### ISSUE THREAD

**Issue by aanah0** [apollographql/apollo-ios#3209]
### Question

I want to set default value inside my ViewModel from Apollo cache. Can I get data from cache synchronously?

**Comment by AnthonyMDev** [comment]
Hi @aanah0 ! Thanks for opening this Issue. Accessing cache data manually is [documented here](https://www.apollographql.com/docs/ios/caching/cache-transactions). You can also execute a `GraphQLOperation` against only your cached data using the cache policies outlined in our [documentation here](https://www.apollographql.com/docs/ios/fetching/fetching-data#cache-policies).

If nothing in the docs helps with what you're seeing, please consider posting in our [Discord server](https://discord.gg/graphos) or our [Community Forum](https://community.apollographql.com/). The maintainers and other Apollo users are active on those platforms, they're great places to ask for help using Apollo iOS. In an effort to keep our Issues actionable, we're closing this Issue for now but please do feel free to re-open if there's a bug, documentation update, or feature idea that we should consider
