### ISSUE TITLE
Subscriptions are suddenly disabled.

### ISSUE THREAD

**Issue by NakamuraAruto** [apollographql/apollo-ios#3210]
### Summary

I am using the GraphQL AWS AppSync API to subscribe to data.
I have a bug in my iOS app that causes GraphQL subscriptions to become unsubscribable without failure detection.
The server performs the mutation successfully, but the subscription suddenly stops without receiving a failure result on the IOS app side.
I have 3 different subscriptions for my app and only one of them is disabled.
Is it possible to detect the failure?
Also, is there any plan to fix this in a library version update? 
If there is a way to check if a particular subscription is still working, it can be resolved by that means.

### Version

1.0.0-beta.3

### Steps to reproduce the behavior

We do not know the conditions under which it stops.
The case reproduced here was more than 2 hours after the subscription started.
I will post a summary of my code.

Function Code

    static func subscription<T: GraphQLSubscription>(query: T) -> Effect<T.Data?, Self.ApiError> {
        Effect<T.Data?, Self.ApiError>.run { subscriber in
                let subscription = GraphQLClient.client.subscribe(subscription: query) { result in
                    switch result {
                    case .success(let graphQLResult):
				// Result handling
                    case .failure(let error):
				// Error handling
            }
            return AnyCancellable {
                subscription.cancel()
            }
        }
    }

Network Client Code

```
struct GraphQLClient {
    static var client: ApolloClient = {
        let sessionClient = URLSessionClient()
        let cache = InMemoryNormalizedCache()
        let store = ApolloStore(cache: cache)
        let provider = NetworkInterceptorProvider(client: sessionClient, store: store)
        let normalTransport = RequestChainNetworkTransport(
            interceptorProvider: provider,
            endpointURL: URL(string: "https://\(endpoint)/graphql")!
        )
        let wsRequest = makeWebSocketRequestForAppSync(endpoint: endpoint)
        let webSocketClient = WebSocket(request: wsRequest, protocol: .graphql_ws)
        let requestBody = AppSyncRequestBodyCreator(endpoint: endpoint)
        let webSocketTransport = WebSocketTransport(websocket: webSocketClient, store: store, config: .init(requestBodyCreator: requestBody))
        let splitNetworkTransport = SplitNetworkTransport(
            uploadingNetworkTransport: normalTransport,
            webSocketNetworkTransport: webSocketTransport
        )
        return ApolloClient(networkTransport: splitNetworkTransport, store: store)
  }()
}
```

**Comment by calvincestari** [comment]
Hi @NakamuraAruto - 👋🏻 

> Version
> 
> 1.0.0-beta.3
Firstly, if you are still on ver

**Comment by calvincestari** [comment]
> Is there a way to verify from the app client whether a particular subscription is live or not at a particular time?

The websocket should continue to receive the "ka" (heartbeat) messages if the connection is still alive - see the [AppSync documentation](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html).

**Comment by NakamuraAruto** [comment]
@calvincestari 

> The websocket should continue to receive the "ka" (heartbeat) messages if the connection is still alive

I have confirmed that KA messages continue to be received when this problem occurs.
Does this mean that websocket is alive?

I have discovered a new fact.
It turns out that the non-subscribing phenomenon is temporary.
We confirmed that once the phenomenon occurred, data was successfully received six minutes later. The system then worked normally for two minutes, but again no data was received.
There was no change to the subscription ID during this phenomenon.
The `onText` and `write` functions of the WebSocketClient class were used to output logs, but there was no abnormal log output during the problem.

Some questions.

- Can all data reception in WebSocketClient be output using the onText function?
- Are there any data communications that are missed by the onText and write functions?

**Comment by calvincestari** [comment]
> I have confirmed that KA messages continue to be received when this problem occurs.
> Does this mean that websocket is alive?

Yes. This indicates that the websocket is still open and able to receive messages = no error. The next question is why the server stops sending you subscription events after the mutation.

> It turns out that the non-subscribing phenomenon is temporary.
> We confirmed that once the phenomenon occurred, data was successfully received six minutes later. The system then worked normally for two minutes, but again no data was received.
> There was no change to the subscription ID during this phenomenon.

I think this indicates something to do with AppSync rather than Apollo iOS. I do not have enough experience with AppSync to guide you to where the issue might be unfortunately.

> Can all data reception in WebSocketClient be output using the onText function?

I believe so since JSON is the data format and therefore I would expect on the websocket text frames to be used.

> Are there any data communications that are missed by the onText and write functions?

Binary frame messages are output to the `onData` function, but I don't expect those would be used for GraphQL.

> Is there any data destruction inside apollo-ios at the time of binary data processing?

I don't believe so. Something like the "ka" (heartbeat) message is not sent to the end app because they have no use for it but we still process it.

**Comment by NakamuraAruto** [comment]
@calvincestari 

> I think this indicates something to do with AppSync rather than Apollo iOS. 

I also assume that no data was received from AppSync, as no data reception was present in the contents of the websocket communication.
I am investigating on the server side.

Thanks.

**Comment by calvincestari** [comment]
I'm going to close this issue as there doesn't seem to be anything we can act on. If during your investigation you find a bug in Apollo iOS please comment here again and we can reopen the issue.
