### ISSUE TITLE
JSONResponseParcingInterceptor

### ISSUE THREAD

**Issue by alessdiimperio** [apollographql/apollo-ios#3220]
### Question

I am trying to do some optimisations as my UI (mapView) would feel sluggish and while using profiler on iOS realised that JSON Parsing was being performed on the main thread.

This shouldn't be happening right? I mean all the interceptors are running on the main thread. Would we not want the whole chain performed on the background and just return the result on the main thread instead? 
Something fishy is going on and i just wanted to verify this should not be happening. 

![stack](https://github.com/apollographql/apollo-ios/assets/82949084/676bf667-fcb9-42f1-8031-087cd087a6b6)

FYI i follow the advanced network settings with custom 
URLSessionClient(sessionConfiguration: configuration, callbackQueue: .main) 
to override headers etc however the callbackQueue should be called _after_ the chain has processed its interceptors no?

**Comment by calvincestari** [comment]
Hi @alessdiimperio 👋🏻 - what you're seeing is the default behaviour/configuration unfortunately. There has been a similar question before which I answered [here](https://github.com/apollographql/apollo-ios/issues/1651#issuecomment-1640680009). That's still the best way to configure network processing to happen on a background queue.

**Comment by alessdiimperio** [comment]
that was how we had it setup, however we passed in .main instead of nil..... what a difference 🙌 thanks for this...
