### ISSUE TITLE
Why is there no use of async/await in ApolloCodegenLib?

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#3226]
### Question

I understand not wanting to use `async/await` in public client APIs yet, but I'm surprised it hasn't trickled in yet internally in ApolloCodegenLib. 

This question is basically around whether contributions I might make to ApolloCodegenLib using `async/await` would be rejected?

**Comment by jimisaacs** [comment]
I think I might have answered my own question in that `Task` is only available in macOS 10.15, but it seems ApolloCodegenLib is already meant to support only that version. It might be cumbersome to use `if #available(macOS 10.15, *)` everywhere, but I'm thinking, would if the entire process was wrapped in a `Task` and forced to be synchronous right at the build function.

**Comment by calvincestari** [comment]
> Why is there no use of async/await in ApolloCodegenLib?

It's on the roadmap for 2.0 which we simply haven't gotten to yet.

> This question is basically around whether contributions I might make to ApolloCodegenLib using async/await would be rejected?

Unfortunately we won't be including/accepting contributions for Swift Concurrency in any of the 1.x versions. Our stance is that anything like that would simply be band-aid whereas 2.0 is a complete rethink of the networking architecture/stack to have first-class support for modern networking standards.

**Comment by jimisaacs** [comment]
@calvincestari Did you see that this issue is about ApolloCodegenLib? Because what you are mentioning I though was all referring to client code.

**Comment by calvincestari** [comment]
No I didn't notice that I was too quick to answer, apologies. I see Anthony got you the right answer in the PR.
