### ISSUE TITLE
Error when trying to get a cached response [missingValue error]

### ISSUE THREAD

**Issue by jesdvlpr** [apollographql/apollo-ios#3234]
### Question

Hi! I’m using the `returnCacheDataElseFetch` cache policy to store the response from a service that responds correctly. Then, I try to retrieve what has been saved using the `returnCacheDataDontFetch` cache policy but it returns a `missingValue` error. Why can’t I retrieve the response from the cache if the service responded correctly? Thanks

**Comment by calvincestari** [comment]
Hi @jesdvlpr 👋🏻 

> I’m using the `returnCacheDataElseFetch` cache policy to store the response from a service that responds correctly.

Are you manually writing data to the cache or any other custom mechanism to get that data into the cache?

> Then, I try to retrieve what has been saved using the `returnCacheDataDontFetch` cache policy but it returns a `missingValue` error. Why can’t I retrieve the response from the cache if the service responded correctly?

You'll need to provide a reproduction case or more details of the queries and generated models. It's difficult to determine why the error is being returned to you without knowing more about the queries you're making.

**Comment by jesdvlpr** [comment]
Hi @calvincestari 

I'm not sure if this implementation is correct. I would appreciate any help you can provide.

```
class GraphQLService {
        private var lastFetchTime: Date?

        let url = URL(string: "https://my-graphql-server.com/graphql")!

        var apollo: ApolloClient = {
                let cache = InMemoryNormalizedCache()
                let store = ApolloStore(cache: cache)

                let client = URLSessionClient()
                let provider = NetworkInterceptorProvider(store: store, client: client, headers: [:])
                let url = self.url

               let requestChainTransport = RequestChainNetworkTransport(interceptorProvider: provider, endpointURL: url)
               return ApolloClient(networkTransport: requestChainTransport, store: store)
     }()

       func fetchQuery(completion: @escaping (Result<GraphQLResult<Data>, Error>) -> Void) {
              let shouldUseCache = shouldFetchFromCache()
              let cachePolicy: CachePolicy = shouldUseCache ? .returnCacheDataDontFetch : .fetchIgnoringCacheData

              client.fetch(query: MyQuery(), cachePolicy: cachePolicy) { result in
                    switch result {
                         case .success(let graphQLResult):
                              completion(.success(graphQLResult))
                        case .failure(let error):
                             completion(.failure(error))
                   }

                   if !shouldUseCache {
                        self.lastFetchTime = Date()
                   }
        }

        private func shouldFetchFromCache() -> Bool {
               guard let lastFetchTime = lastFetchTime else {
                       return false
               }

              let timeInterval = Date().timeIntervalSince(lastFetchTime)
              return timeInterval < 15 * 60
         }
    }
```

**Comment by calvincestari** [comment]
I see you're using a custom interceptor provider - `NetworkInterceptorProvider`. What is the list of interceptors that it returns from the call to `interceptors(for:)`?

**Comment by jesdvlpr** [comment]
Thanks @calvincestari. I have already discovered the problem and as you indicated, it had a conflict with an interceptor.

**Comment by jesdvlpr** [comment]
Thanks @calvincestari. I have already discovered the problem and as you indicated, it had a conflict with an interceptor.
