### ISSUE TITLE
How I could select name for generated struct?

### ISSUE THREAD

**Issue by YegorLindberg** [apollographql/apollo-ios#3235]
### Question

How I could select name for generated struct? 
My query consists `"data"` that contains big info block. Code generator constantly named struct for this block like "`Data`" that intersects with `Foundation.Data`. 

```
public extension GraphQLApi {
  class ProductsSearchQuery: GraphQLQuery {
    public static let operationName: String = "ProductsSearch"
    public static let operationDocument: ApolloAPI.OperationDocument = .init(
      definition: .init(
        #"query ProductsSearch($search: ProductSearch!) { products(search: $search) { __typename ...Data } }"#,
        fragments: [Data.self]
      ))

    public var search: ProductSearch

    public init(search: ProductSearch) {
      self.search = search
    }

    public var __variables: Variables? { ["search": search] }

    public struct Data: GraphQLApi.SelectionSet {
      public let __data: DataDict
      public init(_dataDict: DataDict) { __data = _dataDict }

```

**Comment by calvincestari** [comment]
Hi @YegorLindberg 👋🏻 

> How I could select name for generated struct?
> My query consists `"data"` that contains big info block.

There is no way to rename the `Data` struct. The nested structs and properties within that though are derived from the query field names and field aliases.

> Code generator constantly named struct for this block like `"Data"` that intersects with `Foundation.Data`.

Is this causing a compilation error?

**Comment by YegorLindberg** [comment]
Yes, it causing a compilation error...

**Comment by YegorLindberg** [comment]
@calvincestari May be you can fix it in next release that way:
If you use the structure inside the class, you can call it like `ProductsSearchQuery.Data`, but not simply `Data`. This will solve that problem. :>
Thank you for answering.

**Comment by calvincestari** [comment]
Could you send me a screenshot of the error please. We haven't had any reports of `Data` conflicting with `Foundation.Data` before and I don't think the generated operations import `Foundation` so I'm confused where the build error is.

Is the build error in a generated file or another file you're creating that imports Foundation and has access to the generated operation? If it's in your own generated file then you will need to fully qualify the name as you mentioned with `Foundation.Data` or `ProductsSearchQuery.Data`.
