### ISSUE TITLE
App crashes on iOS 14.4.1

### ISSUE THREAD

**Issue by matijakregarGH** [apollographql/apollo-ios#3247]
### Summary

On iOS 14.4.1 I'm getting the following exception when running my app
`SIGABRT: Could not cast value of type 'Swift.AnyHashable' (0x...) to 'Swift.String' (0x...).`
when accessing the `key` subscript in the `DataDict` (line 55 `_data[key] as! T`).

This is not the first query that is loaded, but it is a first one that has a more complex structure including fragments and also probably the first query that has an optional property with `nil` assigned .

The `value` linked to the `key` is of type `String?` and the actual value is `nil`.

The same app loading the same data does not crash on iOS 16.6.1 and iOS 17.0.2. 

### Version

1.5.0

### Steps to reproduce the behavior

I have tried to replicate the issue in a demo project, but couldn't do so using the mocking option.

If you can point me in the right direction on how to write a test with loading a JSON file, I'm happy to provide a demo project that replicates the behaviour.

Sorry for not providing more relevant info at the moment.

### Anything else?

Reverting Apollo to 1.4.0 "solves" the issue.

**Comment by jozefb** [comment]
We have found same issue  (we are using version 1.5.2). Based on the investigation, issue is probably related with some change in `JSONResponseParsingInterceptor.swift` where any optional field queried by client that has value Swift.AnyHashable(<null>) in parsed JSON, is represented by `Swift.AnyHashable(nil)` in parsed  GraphQLResponse `DataDict`.  
In older versions such field is not present in in parsed  GraphQLResponse `DataDict`

**Comment by calvincestari** [comment]
Thanks for the issue reports, we'll take a look into this asap.

**Comment by AnthonyMDev** [comment]
Update: I've got a fix for this figured out. I just need to do some clean up of the code and tests to get the PR packaged up nicely. Ran out of time for tonight, but I'll get this finished up tomorrow and a PR in.

We are going to include this in the 1.6.0 release that is coming at the end of the week!

**Comment by AnthonyMDev** [comment]
I've got a PR for the fix up now [here](https://github.com/apollographql/apollo-ios-dev/pull/61).

**Comment by BobaFetters** [comment]
Closed by: https://github.com/apollographql/apollo-ios-dev/pull/61

**Comment by AnthonyMDev** [comment]
There was a minor mistake in that PR. This is now fixed by: https://github.com/apollographql/apollo-ios-dev/pull/68. We'll be putting out a 1.6.1 patch to correct this shortly!
