### ISSUE TITLE
Some feedback on the apollo-ios-dev workflow

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#3252]
### Question

Just some feedback on the https://github.com/apollographql/apollo-ios-dev workflow.

Without proper guidance, it seems to make it difficult to test changes in consuming codebases. i.e..
- fork -> make changes -> point consuming codebase to fork to validate -> Make PR -> Point back to upstream

How can that flow work with apollo-ios-dev?

**Comment by BobaFetters** [comment]
Hey @jimisaacs thanks for the feedback, so for the scenario you are describing to be able to test some changes in a fork before then submitting a PR I think the workflow would look something like:

for `apollo-ios` > make changes > point consuming codebase to fork for validation > fork `apollo-ios-dev` > pull in branch from `apollo-ios` fork > Make PR > point back to upstream

I definitely think there is some documentation I could write, and probably some tooling/scripts I could setup to help make parts of that process easier so I will look into that as well.

The biggest thing would be making sure the forked branch stays up to date with main of the repo its for (in this example `apollo-ios`) and when pulling in the changes into `apollo-ios-dev` that its done with the proper subtree commands, which is all stuff I can document and make some tools/scripts for.

**Comment by BobaFetters** [comment]
Decided on what should be an easier workflow for this situation, have a [PR](https://github.com/apollographql/apollo-ios-dev/pull/91) up with a small overview of it plus a script to help wrap the subtree commands for pushing.
