### ISSUE TITLE
Question about operationDocumentFormat codgen option

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#3253]
### Question

Should excluding the `definition` option from `operationDocumentFormat` also control fragments and not only operations?

**Comment by AnthonyMDev** [comment]
Oh, I think it should. The point of omitting `definition` is for using persisted queries. If you are using persisted queries only, you shouldn't need definitions for fragments or operations at all.

Is this not currently working that way for fragments?

**Comment by jimisaacs** [comment]
No, I still see fragment definitions when using this option to omit them.

**Comment by AnthonyMDev** [comment]
Issue #3282 to track addressing this bug.
