### ISSUE TITLE
Custom Scalar type clashing a ApolloAPI type.

### ISSUE THREAD

**Issue by 215eight** [apollographql/apollo-ios#3258]
### Summary

There is a custom scalar defined in the schema called Object. The generated code creates a typealias called Object which clashes with the ApolloAPI.Object struct.

Is there a way to alias certain types? 

Schema
`scalar Object`

Generated Code 
`public typealias Object = String`

ApolloAPI Object type
```
public struct Object: Hashable {
  public init(
    typename: String,
    implementedInterfaces: [Interface]
  ) {
    self.typename = typename
    self.implementedInterfaces = implementedInterfaces
  }
```

### Version

1.5.0

### Steps to reproduce the behavior

1. Create a schema with custom scalar named Object.

scalar Object

type Foo { 
   bar: Object
}

2. Using the codegen cli, generate the schema using the schema file listed above
3. Open the package / project with the auto-generated code
4. Compile issue will occur due to having two types with the same name.

**Comment by BobaFetters** [comment]
The fix for this has been merged in and will go out with our next release.
