### ISSUE TITLE
Object type in a generated graphql file doesn't use pascal case

### ISSUE THREAD

**Issue by torycons** [apollographql/apollo-ios#3273]
### Summary

Hello there, I have some issue with the code generation.

The object type in generated graphql files don't use pascal case

For example If I use a schema and a query file like this

**Schema File**
```graphqls
type Book {
  name: String!
  sale_location: SaleLocation!
}

type SaleLocation {
  store_name: String!
}
``` 

**Query File**
```graphql
book {
  name
  sale_location {
    store_name
  }
}
```

After I run `./apollo-ios-cli generate` command, the object type don't use pascal case

**BookQuery.graphql.swift**
```swift
public final class BookQuery: GraphQLQuery {
  public struct Data: SelectionSet {
    public var book: Book? { __data["book"] }

    public struct Book: SelectionSet {
      public var name: String { __data["name"] }
      public var saleLocation: Sale_location { __data["sale_location"] }

      // This type should be rendered as SaleLocation
      public struct Sale_location: SelectionSet {
        public var storeName: String { __data["store_name"] }
      }
    }
  }
}

```

I'm not sure this is a bug or it's the intended behavior as this type is generated from the field name.
Should it rendered as the pascal case?

### Version

1.7.0

### Steps to reproduce the behavior

1. Create a new schema
2. Create a query file with a field name in snake case
3. Run cli to generate .swift files
4. Type of object doesn't use pascal case

### Logs

```shell
-
```

### Anything else?

After I looked into the apollo-ios-codegen project and I found that this type name is rendered from the field name in [IR+Formatting.swift (Line 35)](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios-codegen/Sources/ApolloCodegenLib/IR%2BFormatting.swift#L35)

It should be rendered the type with pascal case, if I use `convertToCamelCase()` to convert field name before calling `firstUppercased` but I'm not sure if it's the right way to fix this problem.

**Comment by AnthonyMDev** [comment]
I don't think this is a bug. It's intended that we convert the names to a more "swifty" syntax here be default. I'm unclear what the exact behavior you are hoping for is here.

Can you show me a sample of what you would _like_ to be generated and explain your use case? (ie. is this causing compilation failure, other bugs, or is it a style preference?)

**Comment by torycons** [comment]
It's just a style preference problem. From the generated code in my example, almost all of type names use pascal case except `Sale_location`. I'm not familiar with this name style in Swift language. So that i think it should be generated as `SaleLocation` more than `Sale_location`
