### ISSUE TITLE
Best practices for split caching

### ISSUE THREAD

**Issue by swizzlr** [apollographql/apollo-ios#3275]
### Question

I'd like to cache _some_ queries to disk and some queries to memory. However I'd prefer they share a store, since these objects are part of the same graph. Is there a way to do this? For my current use case I think it would be possible to use separate stores, simply because our current server graph isn't very normalized right now, and our normalization is still occurring in our app code. I do anticipate that changing, however.

Approaches I've considered:
1. Multiple stores, as above. Implement my own custom cache read/write interceptors using request contexts to associate cache location preference, have one of each in the request chain.
2. Custom normalized cache, that internally uses InMemory and SQLite. Read from both (prefer memory then disk if no hit); write to... both? Maybe I make this a bit domain specific and specify upfront the cache keys I want to send to disk?

I'm pretty new to really using Apollo caching. I may have made a fundamental error here, so I apologize if I've missed anything in the docs.

**Comment by AnthonyMDev** [comment]
I think both of these approaches are reasonable. Your second suggestion is what we normally recommend to other who have asked this question in the past.

At some point in the future, we do want to build some better mechanisms for managing a split cache directly into the library, but it's not something we anticipate working on in the near future.

Implementing a custom `NormalizedCache` that uses our cache implementations under-the-hood should be able to get you where you need to be though!
