### ISSUE TITLE
Best practices: handling and retrying errors

### ISSUE THREAD

**Issue by ondrejkorol** [apollographql/apollo-ios#3278]
### Question

Hi Apollo team,

I've been exploring error handling within the Apollo iOS SDK and I'm looking for best practices on handling and retrying specific errors. Specifically, I'm interested in the ideal workflow for catching and retrying:

- Network errors (thrown as `URLSessionClient.URLSessionClientError`)
- Invalid HTTP status codes (e.g., 502 Bad Gateway, thrown as `ResponseCodeInterceptor.ResponseCodeError`)

I'm considering whether a custom Interceptor could be a viable solution, possibly inserted after the `NetworkFetchInterceptor`, to inspect and handle these errors. Could you provide guidance on whether this is a recommended approach, or if there is a preferred pattern to follow? 

Furthermore, if you could provide any examples, that would be immensely helpful. So far I mostly found code snippets for React.

Thank you all for your assistance!

Best regards,
Ondrej

**Comment by calvincestari** [comment]
Hi @ondrejkorol 👋🏻 

> Specifically, I'm interested in the ideal workflow for catching and retrying

There isn't a way to catch the errors because they're never thrown. If you look at where they're used, the error is created and then passed back to the completion with the `failure` result. So any error along the interceptor path goes back to the originating `fetch`, `watch`, `perform`, etc. method that started the request.

Even if you look at the `MaxRetryInterceptor` it's not an automatic retry workflow; it's very naive in that it simply tracks the number of times the request has been started but each 'start' has to originate from the caller.

> I'm considering whether a custom Interceptor could be a viable solution, possibly inserted after the NetworkFetchInterceptor, to inspect and handle these errors.

This will only work for successful requests unfortunately because, as mentioned above, any errors will go back to the caller and the interceptor chain stops advancing.

These are limitations of the current networking architecture and will be changing in the 2.0 release which focuses on the networking stack.

> Could you provide guidance on whether this is a recommended approach, or if there is a preferred pattern to follow?

Can you share more details on the kind of request workflow you're wanting to achieve.

**Comment by ondrejkorol** [comment]
Hi @calvincestari ,

This has been very helpful, thanks!
If possible, I want to double-check my understanding of the error handling process:

1. It seems I cannot use `additionalErrorInterceptor` to retry a failed request as its role is more aligned with error logging and it's not possible to retry the request here. Is this correct?

2. For automatically retrying network errors, my current thought is to implement a custom `NetworkFetchInterceptor` that retries upon failure due to a network error. I'm considering using a delay before retrying the operation, and leveraging `MaxRetryInterceptor` to limit the number of retries. Basically the only change would be: When `sendRequest` fails, I'll check for `URLSessionClient.URLSessionClientError.networkError`, add a delay (good old `dispatch asyncAfter`?) and call `chain.retry(...)` instead of `chain.handleErrorAsync(...)`.
Thanks to `MaxRetryInterceptor`, the request will be retried 2x at max. If all fail, I'll receive `MaxRetryInterceptor.RetryError.hitMaxRetryCount`.

4. To handle specific HTTP errors like a 502, I'm thinking of replacing `ResponseCodeInterceptor` with a custom one that initiates a retry when encountering this status code. Would this be a viable approach?
Check when `response?.httpResponse.isSuccessful == false, response?.httpResponse.statusCode == 502` and call `chain.retry(...)`.

Would you say it's safe to do so? Or do you see any possible issues here.
Looking forward to your insights on this.

Cheers,
Ondrej

**Comment by calvincestari** [comment]
> 1. It seems I cannot use `additionalErrorInterceptor` to retry a failed request as its role is more aligned with error logging and it's not possible to retry the request here. Is this correct?

No, you are correct actually; it looks like you would be able to use the `additionalErrorInterceptor` for this. If an additional error handler is available then that receives the error callback, not the original caller. From there you could call `retry` on the interceptor request chain and the whole chain will start from the beginning. To make this work though you'll need to subclass `DefaultInterceptorProvider` so you can override the `additionalErrorInterceptor` method.

You could probably handle 2 and 3 in the same error interceptor as `handleErrorAsync` receives the original error.

**Comment by AnthonyMDev** [comment]
Discussion can continue here, but since there is no particular action item for the team, we are going to close this issue.
