### ISSUE TITLE
Apollo iOS 1.7 migration guide: `Replace use of main.swift` issue

### ISSUE THREAD

**Issue by ihnatmoisieiev** [apollographql/apollo-ios#3279]
### Question

Hello Team,

I have a following issue with 2 step from the Apollo iOS 1.7 migration guide, [Replace use of main.swift with @main](https://www.apollographql.com/docs/ios/migrations/1.7/#replace-use-of-mainswift-with-main) after adding @main annotation to my `run()` function - `'@main' attribute cannot be applied to this declaration`

I'd really appreciate any help with this issue.

Thanks!

<img width="1160" alt="Screenshot 2023-11-08 at 09 46 43" src="https://github.com/apollographql/apollo-ios/assets/11294008/f63f89b4-87b9-4bdc-9b7b-38fe3d537185">

**Comment by BobaFetters** [comment]
@ihnatmoisieiev The `@main` should only be applied to your `AsyncParsableCommand` struct, not to the functions within the struct. If you remove that from the `run()` function you should be all set.
