### ISSUE TITLE
latest codgen release?

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#3281]
### Question

Looks like you have an apollo-ios 1.7.0 that was released for codegen changes, yet codegen isn't included in that package anymore. Though the actual codegen package is still 1.6.1. Seems like a mistake?

**Comment by BobaFetters** [comment]
There is a 1.7.0 tag on the in the ‘apollo-ios-codegen’ repo [here](https://github.com/apollographql/apollo-ios-codegen/releases/tag/1.7.0) although it looks like I forgot to make the “release” that points to the release notes in the ‘apollo-ios’ repo thanks for calling that out.

**Comment by BobaFetters** [comment]
There is now an official 1.7.0 release for codegen [here](https://github.com/apollographql/apollo-ios-codegen/releases/tag/1.7.0)
