### ISSUE TITLE
Validate `@defer` directive in schema matches GraphQL spec definition

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#3287]
This is in reference to an interesting bug reported on Discord - https://discord.com/channels/1022972389463687228/1174776645358465114/1174776645358465114.

**tl;dr** - AppSync appears to support a version of `@defer` and it's in schemas downloaded from AppSync. Our JS frontend [manually adds the `@defer` directive](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/src/index.ts#L70) to schemas so it can be used in operations. The directive from AppSync differs in that it allows it to be used on `FIELD` locations only.

The work here is to make sure that we're not adding a duplicate directive which would cause schema validation to fail. We also need to make sure that if one exists it's on the [same locations and supports the same arguments](https://github.com/graphql/graphql-js/blob/main/src/type/directives.ts#L159) otherwise we should fail our validation.

**Comment by harryblam** [comment]
For visibility, I'm currently getting the below error when generating my graph in version `1.7.1`, (whereas in `1.7.0` it was working fine). It sounds like this PR may fix that. 

> Error: JavaScriptError: GraphQLSchemaValidationError-There can be only one directive named "@defer".-GraphQLSchemaValidationError@` error when generating my graph on `1.7.1

**Comment by calvincestari** [comment]
I recently made [a change to not duplicate the directive](https://github.com/apollographql/apollo-ios-dev/pull/235), which may be correct for the long-term too, but I still feel we need a check to ensure that any existing defer directive must comply with the RFCs specification of the directive.

**Comment by calvincestari** [comment]
This is done with the merging of https://github.com/apollographql/apollo-ios-dev/pull/403.
