### ISSUE TITLE
We updated to 1.7.1 and ApolloCodegenLib seems to have disappeared...?

### ISSUE THREAD

**Issue by oliverfoggin** [apollographql/apollo-ios#3292]
### Question

I just updated to use 1.7.1 and our code that did the model generation is not working. It seems that SPM can't resolve the `ApolloCodegenLib` that we were using...

```
.product(name: "ApolloCodegenLib", package: "apollo-ios"),
```

I saw something in the logs about introducing a deprecation warning to it but I think we might have missed that.

Should we be creating generated types in a different way now?

Thanks

**Comment by calvincestari** [comment]
Hi @oliverfoggin - this change is detailed in the [`1.6.0` release](https://github.com/apollographql/apollo-ios/releases/tag/1.6.0). We also have [an issue that provides some more context](https://github.com/apollographql/apollo-ios/issues/3240) to the change.

**Comment by calvincestari** [comment]
I'm assuming you are upgrading from a version before 1.6.0?

**Comment by oliverfoggin** [comment]
> I'm assuming you are upgrading from a version before 1.6.0?

Ah, yes that's right. I think we were on 1.3.

I'll take a look at the 1.6.0 notes.

Thanks 🤩
