### ISSUE TITLE
1.7.1 added the SelectionSet init but I can't see any docs around using it. (And why can't we use the mock init?)

### ISSUE THREAD

**Issue by oliverfoggin** [apollographql/apollo-ios#3293]
### Question

How should we be using this new `init`?

I've tried this in a preview but it just crashes the preview...

```
MeetingQuery.Data.Meeting(
	_fieldData: [
		"__typename": "Meeting",
		"id": "abc123",
		"name": "Blob",
		"description": "",
		"userId": "",
		"workspaceId": "",
		"created": "2033-07-01T04:00:50.449Z",
		"lastModified": "2033-07-01T04:00:50.449Z",
	]
)
```

Is the `_fieldData` the right init to use? That doesn't appear to be mentioned anywhere?

On this topic, when creating mocks in tests it give actual code completion for the various properties that are used. Is there any reason why this can't be used in production code (i.e. in Previews)? The `ApolloTestSupport` doesn't work in Prod builds but I'm not sure why we have to resort to String types for this?

**Comment by calvincestari** [comment]
Hi @oliverfoggin

> I can't see any docs around using it

It looks like the only documentation we have for it is on the actual initializer itself at https://github.com/Cookiezby/apollo-ios-dev/blob/main/apollo-ios/Sources/Apollo/SelectionSet%2BJSONInitializer.swift#L7.

> Is the _fieldData the right init to use? That doesn't appear to be mentioned anywhere?

No, generally any underscored function or property is to be considered for internal use only and could change at any time without notice, which could break your code that uses any of them.

Also take note that the extension is on `RootSelectionSet`, not any selection set. So in your example you should find the `init(data:variables:)` function on `MeetingQuery`. This new initializer is meant for initializing an operation based on an entire response, not smaller snippets of data.

> On this topic, when creating mocks in tests it give actual code completion for the various properties that are used. Is there any reason why this can't be used in production code (i.e. in Previews)? The ApolloTestSupport doesn't work in Prod builds but I'm not sure why we have to resort to String types for this?

It sounds like you're wanting the [selection set initializers that were introduced with `1.1.0`](https://github.com/apollographql/apollo-ios/releases/tag/1.1.0). Our web documentation page for that API is currently [broken](https://www.apollographql.com/docs/ios/docc/documentation/apollocodegenlib/apollocodegenconfiguration/outputoptions/selectionsetinitializers) so you'll have to [use the Xcode documentation instead](https://github.com/apollographql/apollo-ios/assets/146856/85254cb1-eb57-4f8f-914f-46fa13cac93f). The [codegen configuration sample also includes it](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#full-codegen-configuration-example), just replace `localCacheMutations` with `operations` and you should get what you're looking for.

**Comment by oliverfoggin** [comment]
Hi @calvincestari thanks for the reply but this doesn't work like you describe.

The only `init` I have on the `MeetingQuery` is to create a query i.e.

`MeetingQuery.init(meetingId: "abc123")`

The init you describe doesn't seem to exist there.

It is the `Meeting` that conforms to `OurGraphAPI.SelectionSet`... which is just a typealias for `SelectionSet & RootSelectionSet` so I would expect `Meeting` to have the `init` you describe.

What we're trying to achieve is to be able to run a `Preview` in Xcode and inject fake data to it to populate the view etc... and still be able to submit an app archive to AppStore Connect.

At the moment we were using the `Mocks` that come with `ApolloTestSupport` but this broke the archive as `ApolloTestSupport` was included in the build when it wasn't compatible.

Ideally we could do something like...

```
Meeting(meetingId: "abc123", name: "Meeting One", description: "This is a meeting")
```

If we have to fall back to JSON then that would be OK at a push but right now we can't do that either.

Our only other option is to demote everything that goes into and comes out of ApolloSDK as just transfer objects to our own data types. But I'm hoping that's not necessary 😅

**Comment by oliverfoggin** [comment]
Looking through the Source code that is in the Apollo 1.7.1 package I'm not sure I can see the `public init` that you linked to on `RootSelectionSet`. Do you know which file it is in? Thanks
