### ISSUE TITLE
ci: Codegen test configurations are being skipped sometimes

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#3295]
It looks like we're not catching all the changes that should trigger the codegen test configuration job in ci; full context is in https://github.com/apollographql/apollo-ios-dev/pull/153#discussion_r1401389716.

**Comment by BobaFetters** [comment]
Looks like based on the linked comment and problem, we may need to just run these everytime because I don't think there is a reliable way to know which specific code changes should be tested by these vs skipped, and currently its just based on directory changes.
