### ISSUE TITLE
I am getting illegal hardware instruction  while generate the apollo file

### ISSUE THREAD

**Issue by KeerthikaChokkalingam** [apollographql/apollo-ios#3296]
### Question

when giving the command : 
./apollo-ios-cli generate
I got the error:
zsh: illegal hardware instruction

**Comment by calvincestari** [comment]
Hi @KeerthikaChokkalingam, it looks like [this kind of issue has been reported before](https://github.com/apollographql/apollo-ios/issues?q=is%3Aissue+%22illegal+hardware+instruction%22+is%3Aclosed). In those cases it was related to a problem during code generation. You'll have to dig a bit deeper or provide a reproduction case.

**Comment by KeerthikaChokkalingam** [comment]
I am getting 
No such module 'ApolloUtils' error
