### ISSUE TITLE
Is there a way to generate only mocks?

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#3297]
### Question

Hello! I am trying to put the codegen in a swift package plugin. I'm creating my own executable using `ApolloCodegenLib` and am wondering if there is a way for me to run codegen for the actual operations and mocks separately. I know I can optionally not generate mocks but can I optionally not generate operations at all? That way I would be able to add two plugins to generate mocks and operations separately for their own packages.

**Comment by calvincestari** [comment]
Hi @tahirmt, no there isn't a way to only generate mocks at the moment. I also don't think this is something we would put effort into unfortunately; it seems a very individual workflow-specific requirement.
