### ISSUE TITLE
Xcode build failed - found bundle with the same identifier

### ISSUE THREAD

**Issue by tt-pkaminski** [apollographql/apollo-ios#3298]
### Question

Our team regularly runs into build failures when switching between running our snapshot tests and running the actual application on the simulator.

It seems like there are duplicate bundle identifiers that are installed whenever you switch between running snapshot tests and the application. I'm guessing this is related to our project set up, but is there anything we can do to reduce the frequency of these errors? A typical fix is to clean the build folder and rebuild the project.

> Simulator device returned an error for the requested operation.
Please try again later. Found bundle at /Users/<redacted>/ Library/Developer/CoreSimulator/Devices/A2AF2221-FC6F-49B8-8EAD-EF60FEC2FF7D/data/Library/Caches/
com.apple.mobile.installd.staging/temp.CJ9hjm/extracted/ Payload/<redacted>.app/Frameworks/Apollo.framework with the same identifier (Apollo) as bundle at /Users/<redacted>/ Library/Developer/CoreSimulator/Devices/A2AF2221-FC6F-49B8-8EAD-EF60FEC2FF7D/data/Library/Caches/
com. apple.mobile.installd.staging/temp.CJ9hjm/extracted/
Payload/<redacted>.app/Frameworks/
Apollo_171E9C48F1D7AD_PackageProduct.framework

**Comment by calvincestari** [comment]
Hi @tt-pkaminski - I don't think we've had reports of this kind of issue before yours. Could you share a bit more detail about your project set up please - thanks.

**Comment by BobaFetters** [comment]
Closing this as we havn't heard anything so assuming it has been resolved. Let us know if its still an issue and you can provide additional information.
