### ISSUE TITLE
Can't able to download schema with apollo-codegen-config.json file Please help me in this

### ISSUE THREAD

**Issue by jmohanr** [apollographql/apollo-ios#3302]
### Summary

When I try to download schema through **./Pods/Apollo/apollo-ios-cli fetch-schema**  this command getting below error

Error: keyNotFound(CodingKeys(stringValue: "key", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "schemaDownloadConfiguration", intValue: nil), CodingKeys(stringValue: "headers", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"key\", intValue: nil) (\"key\").", underlyingError: nil)) 

### Version

1.0.6

### Steps to reproduce the behavior

- Installed Apollo pod into my project 
- then **./Pods/Apollo/apollo-ios-cli init --schema-name SchemaName  --module-type embeddedInTarget --target-name TargetName** with this downloaded the **apollo-codegen-config.json** file
- then edited my apollo-codegen-config file to pass custom headers and base URL Mentioned in links section. and getting error like above.

### Anything else?

{
  "schemaName" : "Ke4Enrolment",
  "options" : {
    "cocoapodsCompatibleImportStatements" : true
  },
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "**/*.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : "./Ke4Enrolment",
      "moduleType" : {
        "embeddedInTarget" : {
          "name" : "Ke4Schema"
        }
      }
    },
    "operations" : {
      "inSchemaModule" : {
      }
    }
  },
  "schemaDownloadConfiguration": {
    "downloadMethod": {
          "introspection": {
              "endpointURL": "<BASE_URL>",
              "httpMethod": {
                  "POST": {}
              },
              "includeDeprecatedInputValues": false,
              "outputFormat": "SDL"
          }
      },
      "downloadTimeout": 60,
      "headers": [
          {"Authorization": "Bearer <Token>"
          },
          {
              "x-api-key": "<Key>"
          }
      ],
      "outputPath": "./graphql/schema.graphqls"
  }
}

**Comment by calvincestari** [comment]
Hi @jmohanr, I think it's the `headers` configuration that is incorrect.

In `1.0.6` and below you had to use the following format for `header` keys:
```
"headers": [ 
  {
    "key": "Authorization",
     "value": "Bearer "
  },
  {
    "key": "x-api-key",
     "value": ""
  }
]
```

From `1.0.7` though you can simply specify `headers` as a dictionary like this:
```
"headers": {
        "Authorization" : "Bearer ",
        "x-api-key" : ""
    }
```

I recommend upgrading to `1.0.7` to be able to use the new format, or even better get on the latest version `1.7.1`.
