### ISSUE TITLE
apollo-ios-xcframework is built twice by Carthage

### ISSUE THREAD

**Issue by CraigSiemens** [apollographql/apollo-ios#3308]
### Summary

When `apollo-ios-xcframework` is added as a dependency using Carthage, it is built two times even though it only produces one framework.

### Version

1.7.1

### Steps to reproduce the behavior

- Add `apollographql/apollo-ios-xcframework` as a Carthage dependency in a project.
- Run `carthage build`
- See that it builds Apollo twice.

### Logs

```shell
*** Building scheme "Apollo" in Apollo.xcworkspace
*** Building scheme "Apollo" in Apollo.xcworkspace
```

### Anything else?

It appears to be caused by there being two schemes in the workspace with the name `Apollo`. Running `xcodebuild -list` in the repo shows the following.
```
Information about project "Apollo":
    Targets:
        Apollo
        ApolloAPI
        ApolloSQLite
        ApolloWebSocket

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        Apollo
        Apollo
        Apollo-Dynamic
        ApolloAPI
        ApolloSQLite
        ApolloTestSupport
        ApolloWebSocket
        InstallCLI
```

One is the shared scheme in the project and the other is autogenerated from the swift package target also called `Apollo`. Carthage then builds each scheme it finds that has the same name as a shared scheme in the project. Since two have the same name, it builds them twice.

A workaround seems to be renaming the scheme before running Carthage, then there's only one listed scheme that matches the name of a shared scheme.

```bash
mv Carthage/Checkouts/apollo-ios-xcframework/Apollo.xcodeproj/xcshareddata/xcschemes/Apollo.xcscheme \
Carthage/Checkouts/apollo-ios-xcframework/Apollo.xcodeproj/xcshareddata/xcschemes/Apollo-Framework.xcscheme
```

Related issue https://github.com/Carthage/Carthage/issues/3358

**Comment by BobaFetters** [comment]
@CraigSiemens Thanks for reporting this, I will take a look at this as soon as I can to see what I can do to resolve it

**Comment by BobaFetters** [comment]
@CraigSiemens Turns out this was a pretty simple fix, PR is up [here](https://github.com/apollographql/apollo-ios-xcframework/pull/9) and it will go out when we do our next release.
