### ISSUE TITLE
VisionOS Support

### ISSUE THREAD

**Issue by bdunay3** [apollographql/apollo-ios#3320]
### Use case

Can we get support for being able to use Apollo on VisionOS? We'd like to be able to run queries against our graph on that Apple platform.

### Describe the solution you'd like

I looked through the code and there isn't anything that's platform specific. Everything Apollo uses is available on VisionOS (with the exception of SQLite), so it shouldn't be more then adding it to the supported platforms list in the Package manifest.

**Comment by AnthonyMDev** [comment]
Yes, I've already started to look into this. I'm actually looking into what it would take to get `SQLite` to support VisionOS as well!

The only other barrier so far is that `Quick/Nimble` doesn't support it yet, so we can't run our unit tests against that platform. Which is not technically blocking us, but I'd like to get that support pushed as well.

**Comment by loganblevins** [comment]
Bumping for visionOS support

**Comment by calvincestari** [comment]
The Nimble dependency update has been done, I believe it's SQLite we're still waiting on.

**Comment by loganblevins** [comment]
@calvincestari Is the SQLite dependency a binary?

**Comment by calvincestari** [comment]
No, we use the [source package](https://github.com/apollographql/apollo-ios/blob/main/Package.swift#L24). visionOS needs to be declared in [their list of supported platforms](https://github.com/stephencelis/SQLite.swift/blob/master/Package.swift#L6) as well as any required changes that comes from enabling that.

**Comment by loganblevins** [comment]
Oh I see. You're simply wrapping the C lib with a Swift frontend. Is there an ETA on this? My options are wait or fork it

**Comment by AnthonyMDev** [comment]
I've got a PR up to add support to SQLite.swift right [here](https://github.com/stephencelis/SQLite.swift/pull/1237). I can't tell you how long until they respond to me, but I did ping them today to ask for some eyes on it.

**Comment by loganblevins** [comment]
Where does this stand? @calvincestari

**Comment by AnthonyMDev** [comment]
We are still waiting on SQLite.swift. As soon as that is merged in, I will finish this up!
