### ISSUE TITLE
When using apollo-ios-pagination, there is an issue where data is not accurately updated when mutations occur.

### ISSUE THREAD

**Issue by ralph-101-dev** [apollographql/apollo-ios#3331]
### Question

When the cached value of a paginated query changes, the `onFetch` method of `AsyncGraphQLQueryPager` is invoked via a watcher. It seems that during this process, the variables are utilized as keys in the `nextPageVarMap` dictionary. If a key already exists, the data is updated; otherwise, a new page is added.

The issue lies in the fact that the Variables of a `GraphQLOperation` are represented as a dictionary, and the values of this dictionary are used as keys. For instance, with a query like:

```swift
Query(
    filter: .init(
        mine: true,
        query: query,
        orderType: latest
    ),
    first: 15,
    after: “123123”
)
```

the variables can result in various keys such as:

* [[mine: true, query: “123213”, orderType: “latest”], 15, 123123]
* [15, [mine: true, query: “123213”, orderType: “latest”], 123123]
* [15, 123123, [mine: true, query: “123213”, orderType: “latest”]]
* …

Converting the Variables dictionary of the Query into an array does not maintain consistent ordering, which leads to the inability to identify the same page consistently, thus resulting in the addition of new pages instead of updating existing ones.

If you are aware of a solution to this issue, please share!

**Comment by Iron-Ham** [comment]
Hi @ralph-101-dev! 
You're 100% correct. I'll open up a PR addressing that shortly. Thanks!
