### ISSUE TITLE
The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.6.0 darwin-x64 node-v10.7.0 seems to be installed. Installing...

### ISSUE THREAD

**Issue by yas375** [apollographql/apollo-ios#334]
It looks like `REQUIRED_APOLLO_CLI_VERSION=1.2.0` in [check-and-run-apollo-cli.sh](https://github.com/apollographql/apollo-ios/blob/0f3c18bbe9eac2f31c7109e6e798ab54de6b6953/scripts/check-and-run-apollo-cli.sh#L2) prevents us from using latest version of Apollo...

In our iOS project at root level we have `package.json` with:

```
{
  "name": "xxx",
  "version": "1.0.0",
  "dependencies": {
    "apollo": "^1.6.0"
  },
  "devDependencies": {},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/xxx/xxx.git"
  },
  "keywords": [],
  "author": "",
  "license": "UNLICENSED",
  "private": true,
  "bugs": {
    "url": "https://github.com/xxx/xxx/issues"
  },
  "homepage": "https://github.com/xxx/xxx#readme"
}
```

Note it required Apollo `1.6.0`.

We have latest (0.9.2) Apollo pod integrated into our project:

```sh
➜  xxx git:(apollo-tweaks)  cat Podfile.lock | grep Apollo
  - Apollo (0.9.2):
    - Apollo/Core (= 0.9.2)
  - Apollo/Core (0.9.2)
  - Apollo
    - Apollo
  Apollo: 39d1adfceb6f262fc58286ec9425fd7c332877fb
```

We do have  code generation build step per recommendation [here](https://www.apollographql.com/docs/ios/installation.html#adding-build-step):

```
APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
  echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
  exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"

$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --queries="$(find . -name '*.graphql')" --schema=./GraphQL/schema.json ./GraphQLAPI.swift
```

And when the build step runs it actually downgrades apollo npm package to 1.2.0:

```
cd /Users/yas/code/xxx/xxx
Queries: ./GraphQL/xxx.graphql
+++ get_installed_version
++++ /Users/yas/code/xxx/node_modules/.bin/apollo -v
+++ version='apollo/1.6.0 darwin-x64 node-v10.7.0'
+++ [[ 0 -eq 0 ]]
+++ echo 'apollo/1.6.0 darwin-x64 node-v10.7.0'
++ INSTALLED_APOLLO_CLI_VERSION='apollo/1.6.0 darwin-x64 node-v10.7.0'
++ are_versions_compatible apollo/1.6.0 darwin-x64 node-v10.7.0 1.2.0
+++ cut -d/ -f2
+++ cut -d. -f1-2
+++ cut -d/ -f2
+++ cut -d. -f1-2
++ [[ 1.6 == \d\a\r\w\i\n\-\x\6\4 ]]
++ echo 'The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.6.0 darwin-x64 node-v10.7.0 seems to be installed. Installing...'
The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.6.0 darwin-x64 node-v10.7.0 seems to be installed. Installing...
++ install_apollo_cli
++ set -e
++ npm install --prefix /Users/yas/code/xxx apollo@1.2.0
+ apollo@1.2.0
added 8 packages from 10 contributors, removed 2 packages, updated 9 packages and audited 2124 packages in 12.714s
found 0 vulnerabilities

++ set +e
++ exec /Users/yas/code/xxx/node_modules/.bin/apollo codegen:generate --queries=./GraphQL/xxx.graphql --schema=./GraphQL/schema.json ./GraphQLAPI.swift
 ›   Warning: apollo update available from 1.2.0 to 1.6.0
[?25l[15:43:18] Scanning for GraphQL queries [started]
```

I assume this is not an intentional behavior, is it?

**Comment by martijnwalraven** [comment]
This is in fact intentional behavior. Because changes to the generated code could break the installed version of the Apollo iOS framework, we pin the CLI version to the version it is known to work with. 

We've always done this for `apollo-codegen`, but I can see how it's becoming inconvenient with the move to the `apollo` CLI because codegen is just one of the features. You can always use a newer global install for other features of course. But we should probably find a way to only depend on the version of `apollo-codegen-swift`.

**Comment by yas375** [comment]
Gotcha. Shouldn't it pin a more recent version of Apollo CLI maybe? It pins 1.2.0 while there is already 1.6.0. And I'm using latest Apollo iOS pod (0.9.2) which was released just a couple of days ago.

**Comment by yas375** [comment]
Also, it looks like it reruns `npm install ...` on every build I do even though it has installed 1.2.0 already. This is what I see in logs on every build:

```
+++ get_installed_version
++++ /Users/yas/code/xxx/node_modules/.bin/apollo -v
 ›   Warning: apollo update available from 1.2.0 to 1.6.0
+++ version='apollo/1.2.0 darwin-x64 node-v10.7.0'
+++ [[ 0 -eq 0 ]]
+++ echo 'apollo/1.2.0 darwin-x64 node-v10.7.0'
++ INSTALLED_APOLLO_CLI_VERSION='apollo/1.2.0 darwin-x64 node-v10.7.0'
++ are_versions_compatible apollo/1.2.0 darwin-x64 node-v10.7.0 1.2.0
+++ cut -d/ -f2
+++ cut -d. -f1-2
+++ cut -d/ -f2
+++ cut -d. -f1-2
++ [[ 1.2 == \d\a\r\w\i\n\-\x\6\4 ]]
++ echo 'The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.2.0 darwin-x64 node-v10.7.0 seems to be installed. Installing...'
The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.2.0 darwin-x64 node-v10.7.0 seems to be installed. Installing...
++ install_apollo_cli
++ set -e
++ npm install --prefix /Users/yas/code/xxx apollo@1.2.0
+ apollo@1.2.0
updated 1 package and audited 2124 packages in 28.9s
found 0 vulnerabilities
```

Let me know if you would prefer me to open a separate issue for this.

**Comment by vandadnp** [comment]
> ++ [[ 1.2 == \d\a\r\w\i\n\-\x\6\4 ]]

@martijnwalraven 

The above is the problem. We have the exact same issue and had to change the script by just returning true from this function:

```bash
are_versions_compatible() {
    return 0
    # [[ "$(cut -d/ -f2 <<< $1 | cut -d. -f1-2)" == "$(cut -d/ -f2 <<< $2 | cut -d. -f1-2)" ]]
}
```

**Comment by chrisco314** [comment]
This is affecting me (everybody really) too, hopefully it can be fixed soon and merged.

**Comment by martijnwalraven** [comment]
This should be fixed in Apollo iOS 0.9.3.

**Comment by ynie** [comment]
Me too. I can still repro this on 0.9.3. Thanks!

**Comment by ynie** [comment]
@martijnwalraven here's my output:


Showing All Messages
warning: The version of Apollo.framework in your project requires Apollo CLI 1.8.x, but apollo/1.2.0 darwin-x64 node-v8.9.4 seems to be installed.


note: Installing apollo@1.8 in your project directory to avoid version conflicts...


npm WARN saveError ENOENT: no such file or directory, open '/Users/ynie/ynie_depot/issue_master/Durian/package.json'


npm WARN enoent ENOENT: no such file or directory, open '/Users/ynie/ynie_depot/issue_master/Durian/package.json'


npm WARN Durian No description


npm WARN Durian No repository field.


npm WARN Durian No README data


npm WARN Durian No license field.


+ apollo@1.8.3


updated 1 package in 2.457s


++ npx --no-install apollo codegen:generate '--queries=./GraphQL/my_repos.graphql


./GraphQL/dashboard_info.graphql


./GraphQL/me_info.graphql


./GraphQL/issue_timeline.graphql' --schema=GraphQL/github_ql_schema.json GraphQL/GitHubGraphQLAPI.swift


 ›   Warning: apollo update available from 1.2.0 to 1.5.0


[?25l[18:01:30] Scanning for GraphQL queries [started]


[18:01:30] Scanning for GraphQL queries (4 found) [title changed]


[18:01:30] Scanning for GraphQL queries (4 found) [completed]


[18:01:30] Loading GraphQL schema [started]


[18:01:30] Loading GraphQL schema [completed]


[18:01:30] Parsing GraphQL schema [started]


[18:01:30] Parsing GraphQL schema [completed]


[18:01:30] Generating query files [started]


[18:01:30] Generating query files with 'swift' target [title changed]


[18:01:30] Generating query files with 'swift' target - wrote 1 files [title changed]


[18:01:30] Generating query files with 'swift' target - wrote 1 files [completed]

**Comment by ynie** [comment]
@martijnwalraven Thanks! How do I check that?

**Comment by martijnwalraven** [comment]
@ynie Look under `node_modules/apollo` in your project directory, and check the version in `package.json`.

**Comment by ynie** [comment]
`{
  "_from": "apollo@1.8",
  "_id": "apollo@1.8.3",
  "_inBundle": false,
  "_integrity": "sha512-rSuIc/bGg//j65ppC25vuyvVVNu6c64LRUpaKzDw5PzCEG6GjEX/yeBUxiEV43GOK1LMxsRyXgCFRWuY6Rt/Gw==",
  "_location": "/apollo",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "apollo@1.8",
    "name": "apollo",
    "escapedName": "apollo",
    "rawSpec": "1.8",
    "saveSpec": null,
    "fetchSpec": "1.8"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/apollo/-/apollo-1.8.3.tgz",
  "_shasum": "c005c898f6ae92861b35fe913a85901c2f2b8fc4",
  "_spec": "apollo@1.8",
  "_where": "/Users/ynie/ynie_depot/issue_master/Durian/Durian",
  "author": {
    "name": "Apollo GraphQL",
    "email": "opensource@apollographql.com"
  },
  "bin": {
    "apollo": "./bin/run"
  },
  "bugs": {
    "url": "https://github.com/apollographql/apollo-cli/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@oclif/command": "^1.4.21",
    "@oclif/config": "^1.6.17",
    "@oclif/plugin-help": "^1.2.11",
    "@oclif/plugin-not-found": "^1.0.9",
    "@oclif/plugin-warn-if-update-available": "^1.3.9",
    "@types/globby": "^8.0.0",
    "@types/lodash": "^4.14.109",
    "@types/react": "^16.3.14",
    "@types/react-dom": "^16.0.5",
    "@types/rimraf": "^2.0.2",
    "apollo-codegen-flow": "0.27.3",
    "apollo-codegen-flow-legacy": "0.27.3",
    "apollo-codegen-scala": "0.27.3",
    "apollo-codegen-swift": "0.27.3",
    "apollo-codegen-typescript": "0.27.3",
    "apollo-codegen-typescript-legacy": "0.27.3",
    "apollo-link": "^1.2.2",
    "apollo-link-http": "^1.5.4",
    "chalk": "^2.4.1",
    "cli-ux": "^4.3.0",
    "decode-html": "^2.0.0",
    "env-ci": "^2.1.0",
    "gaze": "^1.1.3",
    "git-parse": "^1.0.3",
    "git-rev-sync": "^1.12.0",
    "glob": "^7.1.2",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.2",
    "heroku-cli-util": "^8.0.9",
    "listr": "^0.14.1",
    "lodash": "^4.17.10",
    "node-fetch": "^2.1.2",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "rimraf": "^2.6.2"
  },
  "deprecated": false,
  "description": "Command line tool for Apollo GraphQL",
  "devDependencies": {
    "typescript": "^3.0.3"
  },
  "engines": {
    "node": ">=8",
    "npm": ">=6"
  },
  "files": [
    "/bin",
    "/lib",
    "/oclif.manifest.json"
  ],
  "gitHead": "e8d31998beae239ea92e140c670f45412ca0ffd4",
  "homepage": "https://github.com/apollographql/apollo-cli",
  "jest": {
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "testPathIgnorePatterns": [
      "node_modules",
      "lib"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "testEnvironment": "node"
  },
  "license": "MIT",
  "main": "lib/index.js",
  "name": "apollo",
  "oclif": {
    "commands": "./lib/commands",
    "bin": "apollo",
    "plugins": [
      "@oclif/plugin-help",
      "@oclif/plugin-not-found",
      "@oclif/plugin-warn-if-update-available"
    ],
    "repositoryPrefix": "<%- repo %>/blob/master/packages/apollo/<%- commandPath %>"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/apollographql/apollo-cli.git"
  },
  "scripts": {
    "build": "tsc",
    "clean": "rm -rf lib",
    "postpack": "rm -f oclif.manifest.json",
    "prebuild": "npm run clean",
    "prepack": "oclif-dev manifest && oclif-dev readme",
    "prepare": "npm run build",
    "version": "oclif-dev readme && git add README.md"
  },
  "types": "lib/index.d.ts",
  "version": "1.8.3",
  "warnings": [
    {
      "code": "ENOTSUP",
      "required": {
        "node": ">=8",
        "npm": ">=6"
      },
      "pkgid": "apollo@1.8.3"
    },
    {
      "code": "ENOTSUP",
      "required": {
        "node": ">=8",
        "npm": ">=6"
      },
      "pkgid": "apollo@1.8.3"
    }
  ]
}
`

**Comment by martijnwalraven** [comment]
@ynie That seems fine. Can you run `npx --no-install apollo --version` in your project directory to check if it picks up the local version?

**Comment by ynie** [comment]
apollo (master) $ npx --no-install apollo --version
 ›   Warning: apollo update available from 1.2.0 to 1.5.0
apollo/1.2.0 darwin-x64 node-v8.9.4

Thanks! That's what I got.

**Comment by martijnwalraven** [comment]
@ynie That's really weird! `npx --no-install apollo` should pick up the local version over the global one., I just checked. Can you run `which apollo` to see where the global version has been installed?

**Comment by ynie** [comment]
That will be
ynie@MBP apollo (master) $ which apollo
/usr/local/bin/apollo

**Comment by vandadnp** [comment]
We have the same issue. The local version is not picked up and we all had to install it globally even on CircleCI to pick it up

**Comment by martijnwalraven** [comment]
@ynie @vandadnp Can you try `npx --version`? I re-checked, and it does pick up the local version for me.

**Comment by vandadnp** [comment]
@martijnwalraven here is my output for all 3 commands:

```shell
➜ npx --version                    
9.7.1
➜ npx --no-install apollo --version
apollo/1.8.3 darwin-x64 node-v8.11.4
➜ which apollo
/usr/local/bin/apollo
```

**Comment by martijnwalraven** [comment]
@vandadnp Are you running `npx --no-install apollo --version` from your project directory, the directory with `node_modules` with `apollo/` and `.bin/apollo` in it?

**Comment by vandadnp** [comment]
@martijnwalraven yes I am running it from the root directory of our project, where `node_modules` is located

**Comment by martijnwalraven** [comment]
@vandadnp Then I'm really out of ideas, because it does work for me :( Hopefully someone can figure out what is going on here.

**Comment by cczufish** [comment]
bogon:riseon-ipad yushuhui$ npx --version
9.7.1
bogon:riseon-ipad yushuhui$ npx --no-install apollo --version
 ›   Warning: apollo update available from 1.8.3 to 1.9.1
apollo/1.8.3 darwin-x64 node-v9.11.1

**Comment by gaoshanyu** [comment]
I met the same issue. How to fix it?

**Comment by abdullahumer** [comment]
I'm facing the same issue :(

**Comment by abdullahumer** [comment]
```
Abdullahs-iMac:Haraj Swift abdullahumer$ npx -version
6.4.1
Abdullahs-iMac:Haraj Swift abdullahumer$ npx --no-install apollo --version
 ›   Warning: apollo update available from 1.8.3 to 1.9.2
apollo/1.8.3 darwin-x64 node-v8.11.3
Abdullahs-iMac:Haraj Swift abdullahumer$ 
```

**Comment by hao-li** [comment]
```
➜  git:(master) ✗ which apollo
/usr/local/bin/apollo
➜  git:(master) ✗ npx --version
6.4.1
➜  git:(master) ✗ npx --no-install apollo --version
 ›   Warning: apollo update available from 1.8.3 to 1.9.2
apollo/1.8.3 darwin-x64 node-v8.6.0
```

**Comment by hao-li** [comment]
Temporary solution: Manually reinstall the local repositories
```
$ rm -rf node_modules
$ pod install
```

**Comment by Dfmarulanda** [comment]
@hao-li when i do that i receive the following error:
` apollo update available from 1.8.3 to 1.9.2`

**Comment by jessieserrino** [comment]
Have you run `npm install -g apollo`? I had a local version of apollo in my `node_modules`, but it seems like it wants to update the version in `/usr/local/lib/node_modules/apollo`

**Comment by hao-li** [comment]
@Dfmarulanda 
In my case it seems that the version under the project is behind the global version.
So remove the project version and reinstall it, it should install the latest version directly.

By running `npm install -g apollo`, you can ensure that the global version is also up to date, so the two are consistent.

I have updated the temporary solution in the previous answer and added this step, thanks to @jessieserrino

**Comment by skrishnasm** [comment]
I'm seeing this error Apollo CLI requires Node 8 or higher, but v7.4.0 seems to be installed, when trying to build my project. I've checked my node version in my iOS project folder and globally and it is 8.x. I'm using latest version of apollo client for ios ~ 0.9.4. And apollo CLI ~ apollo/2.1.0 darwin-x64 node-v8.11.1. Please advise compatible versions or steps for resolution.

**Comment by rad182** [comment]
downgraded to apollo-ios pod 0.9.3
then `npm install -g apollo@1.8.3`
works for me for now

**Comment by Premal-Khetani** [comment]
Got below in the log and build is fail. 

> +++ get_installed_version
> ++++ /Users/MAC/Desktop/Demo/node_modules/.bin/apollo -v
>  ›   Warning: apollo update available from 1.2.0 to 2.1.8
> +++ version='apollo/1.2.0 darwin-x64 node-v10.4.0'
> +++ [[ 0 -eq 0 ]]
> +++ echo 'apollo/1.2.0 darwin-x64 node-v10.4.0'
> ++ INSTALLED_APOLLO_CLI_VERSION='apollo/1.2.0 darwin-x64 node-v10.4.0'
> ++ are_versions_compatible apollo/1.2.0 darwin-x64 node-v10.4.0 1.2.0
> +++ cut -d/ -f2
> +++ cut -d. -f1-2
> +++ cut -d/ -f2
> +++ cut -d. -f1-2
> ++ [[ 1.2 == \d\a\r\w\i\n\-\x\6\4 ]]
> ++ echo 'The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.2.0 darwin-x64 node-v10.4.0 seems to be installed. Installing...'
> The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.2.0 darwin-x64 node-v10.4.0 seems to be installed. Installing...
> ++ install_apollo_cli
> ++ set -e
> ++ npm install --prefix /Users/MAC/Desktop/Demo apollo@1.2.0
> npm WARN saveError ENOENT: no such file or directory, open '/Users/MAC/Desktop/Demo/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/Users/MAC/Desktop/Demo/package.json'
> npm WARN Demo No description
> npm WARN Demo No repository field.
> npm WARN Demo No README data
> npm WARN Demo No license field.
> 
> + apollo@1.2.0
> updated 1 package and audited 8369 packages in 4.265s
> found 0 vulnerabilities
> 
> ++ set +e
> ++ exec /Users/MAC/Desktop/Demo/node_modules/.bin/apollo codegen:generate --queries=./Demo/GraphQL/GraphQueries.graphql --schema=schema.json API.swift
>  ›   Warning: apollo update available from 1.2.0 to 2.1.8
> [18:25:57] Scanning for GraphQL queries [started]
> [18:25:57] Scanning for GraphQL queries (1 found) [title changed]
> [18:25:57] Scanning for GraphQL queries (1 found) [completed]
> [18:25:57] Loading GraphQL schema [started]
> [18:25:57] Loading GraphQL schema [failed]
> [18:25:57] → ENOENT: no such file or directory, open '/Users/MAC/Desktop/Demo/schema.json'
> Error: ENOENT: no such file or directory, open '/Users/MAC/Desktop/Demo/schema.json'

**Comment by nguyen-nn** [comment]
> downgraded to apollo-ios pod 0.9.3
> then `npm install -g apollo@1.8.3`
> works for me for now

It's worked for me

**Comment by SrdjanSpasojevic** [comment]
I removed the `Apollo` pod from the `PodFile`, removed the pod completely, installed pod again. After that command `npx --no-install apollo --version` doesn't return warning.

**Comment by designatednerd** [comment]
Sounds like this was resolved earlier this year - I'm going to close this issue out, but please open a new issue if you're still having problems!
