### ISSUE TITLE
Unable to generate code

### ISSUE THREAD

**Issue by JBergsee** [apollographql/apollo-ios#3347]
### Question

Is there a max size of the schema file? I am trying to generate code from this file:
http://api-schema-doc.s3-website-eu-west-1.amazonaws.com/schema-beta.json
But the cli "generate" command just tells me JSON Parse error: Unexpected EOF
Is there any way of knowing which line or type that generates the error?

**Comment by calvincestari** [comment]
Hi @JBergsee, there doesn't appear to be anything invalid with the schema format and the length isn't an issue. I was able to generate a simple operation against the schema so I suggest checking that your operation files don't have any formatting issues.

**Comment by JBergsee** [comment]
Thank you @calvincestari !
I have been wasting an entire week on trying to fix the schema, when it was a capital "A" instead of an "a" in an operation file that made the whole thing fail...
I'm extremely grateful for this breakthrough!

**Comment by calvincestari** [comment]
I'm glad we could help and you managed to get it working.
