### ISSUE TITLE
codegen: Append type to generated filenames

### ISSUE THREAD

**Issue by michaelloo** [apollographql/apollo-ios#3354]
### Summary

If you have an `INPUT_OBJECT` type with name `Address`, and a `OBJECT` type with the same name `Address` , you end up with a conflicting `filename` which causes an Xcode compile issue:

> Filename "Address.graphql.swift" used twice: '.../GeneratedFiles/Schema/Objects/Address.graphql.swift' and '.../GeneratedFiles/Schema/InputObjects/Address.graphql.swift'

![Screenshot 2024-03-15 at 11 40 49 am](https://github.com/apollographql/apollo-ios/assets/4216269/ad40802a-c53f-49a5-bb46-6ce826b53b0b)

The struct name are ok because they are nested under different levels:

![Screenshot 2024-03-15 at 11 40 54 am](https://github.com/apollographql/apollo-ios/assets/4216269/bc9c7210-0513-455a-8ca7-19ebb2536c8b)
![Screenshot 2024-03-15 at 11 40 59 am](https://github.com/apollographql/apollo-ios/assets/4216269/5815faf8-53d8-41dd-82cf-3d76b899fcf7)

### Version

1.9.0

### Steps to reproduce the behavior

apollo-codegen-config:
```json
{
  "schemaNamespace" : "GQLSchema",
  "schemaDownload": {
    "downloadMethod": {
        "introspection": {
            "endpointURL": "some.url/graphql",
            "httpMethod": { "POST": {} },
            "includeDeprecatedInputValues": false,
            "outputFormat": "JSON"
        }
    },
    "downloadTimeout": 60,
    "outputPath": "./graphql/"
  },
  "input" : {
    "operationSearchPaths" : ["**/*.graphql"],
    "schemaSearchPaths" : ["**/schema.json"]
  },
  "output" : {
    "testMocks" : { "none" : {} },
    "schemaTypes" : {
      "path" : "./GeneratedFiles",
      "moduleType" : { "embeddedInTarget" : { "name": "XXX" } }
    },
    "operations" : { "inSchemaModule" : {} }
  },
  "options": {
    "cocoapodsCompatibleImportStatements": true,
    "selectionSetInitializers": {
      "localCacheMutations" : true,
      "namedFragments" : true,
      "operations" : true
    }
  }
}
```

I am unable to give you a full view of the schema unfortunately but here are some snippets of it:
```json
      {
        "kind": "OBJECT",
        "name": "Address",
        "description": null,
        "specifiedByUrl": null,
// ...
      {
        "kind": "OBJECT",
        "name": "XXX_Item",
        "description": null,
        "specifiedByUrl": null,
        "fields": [
          {
            "name": "address",
            "description": "...",
            "args": [],
            "type": {
              "kind": "NON_NULL",
              "name": null,
              "ofType": {
                "kind": "OBJECT",
                "name": "Address",
                "ofType": null
              }
            },
            "isDeprecated": false,
            "deprecationReason": null
          }
        ],
// ...
      {
        "kind": "INPUT_OBJECT",
        "name": "XXX_Input",
        "description": null,
        "specifiedByUrl": null,
        "fields": null,
        "inputFields": [
          {
            "name": "address",
            "description": "address",
            "type": {
              "kind": "NON_NULL",
              "name": null,
              "ofType": {
                "kind": "INPUT_OBJECT",
                "name": "address",
                "ofType": null
              }
            },
            "defaultValue": null,
            "isDeprecated": false,
            "deprecationReason": null
          }
        ],
// ...
      {
        "kind": "INPUT_OBJECT",
        "name": "address",
        "description": null,
        "specifiedByUrl": null,
        "fields": null,
// ...
```

If I rename one of the conflicting files, then I am able to get through this error, (e.g.: `AddressInput`).

### Anything else?

Is there a way to specify the output to be in a single file (like it used to be able to do)? Then I can avoid this filename conflict

**Comment by calvincestari** [comment]
I believe this is a known issue @michaelloo, and unfortunately we don't have a workaround that isn't manual at the moment. Xcode really should just be able to handle this to be honest. A solution that works with codegen may have to be adding a name suffix to each file with what kind it is; `AddressInputObject`, `AddressObject`, etc.

**Comment by michaelloo** [comment]
😢 Ah ok... we'll have a script them to rename the file for now after updating the models, thanks for the response!

**Comment by michaelloo** [comment]
Hi @calvincestari , on a somewhat related note, what is the suggested approach if we have the same codebase relying on multiple APIs with different GraphQL schemas? Meaning having multiple `apollo-codegen-config.json` files but the generate code might have filename conflict, e.g.:
```
error: Filename "SchemaConfiguration.swift" used twice: 'some/path/GeneratedFiles/Schema/SchemaConfiguration.swift' and 'some/other/path/GeneratedFiles/Schema/SchemaConfiguration.swift' (in target 'XXX' from project 'XXX')
```

**Comment by calvincestari** [comment]
Apollo iOS is not designed to work with multiple schemas at once and to do so requires a bit of careful configuration.

To resolve the duplicate `SchemaConfiguration.swift` you'll need to generate the schemas into different targets/packages, I believe that should resolve the issue.

**Comment by michaelloo** [comment]
I see, we'll get onto that but this isn't an ideal solution so i've opened a separate feature request [here](https://github.com/apollographql/apollo-ios/issues/3357) 🙏

**Comment by AnthonyMDev** [comment]
A workaround for this is being implemented currently. See #3283 for more info. Once that is released, you'll be able to change the generated names of these types (including file names) to `AddressInputObject` and `AddressType` (or any names you choose).

**Comment by AnthonyMDev** [comment]
The workaround for this in #3283 has been shipped. That is now the suggested solution when dealing with this problem in the future. Closing this issue.
