### ISSUE TITLE
Add Release Notes

### ISSUE THREAD

**Issue by zinthemoney** [apollographql/apollo-ios#336]
Currently, it is hard to find out what's change from release to release. Adding release notes should help.

**Comment by cocojoe** [comment]
I would suggest automating this to some degree, tag PRs with labels that correspond to Change log headers `added, fixed, changed, update, deprecated` against a milestone. Then auto generate the change log based on that.

**Comment by designatednerd** [comment]
I've started adding release notes to each release tag and actually updating [CHANGELOG.md](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md) when we do a release. 

Hopefully that addresses this issue - I'm going to close it out but please feel free to open a new issue if there's more granular information you need!
