### ISSUE TITLE
Investigation: Allow codegen projects to modify generated filenames

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#3361]
Related to https://github.com/apollographql/apollo-ios/issues/3357.

* This configuration must not be possible through the JSON configuration + CLI model.
* This configuration must only be available to codegen that is executed through a custon codegen project, i.e.: calling codegen through code and not CLI.
* The configuration should allow the codegen project to modify the generated filename before output.
* The filename modification must not affect file content, i.e.: type names are not affected.
* The filename modification must not affect file location, i.e.: file path remains the same.

This issue exists mostly to resolve the Xcode quirk of not being able to handle multiple files with the same name even though they are in different paths. Additionally it can help alleviate the existing problem of input type filenames clashing with other object type filenames.

We've been resistant to this type of feature in the past but the difference with this design is that Apollo iOS is not the one to be making the change based on an individual rule, such as prefixing the schema name to filenames, etc. Rather it is the client project that is being given the ability to modify the name.

**Comment by AnthonyMDev** [comment]
The team has discussed this issue and we don't believe it's an appropriate fix for #3557. This would add a lot of complexity to the code generation engine and open up a lot of edge cases for us to deal with going forward.

The correct way to deal with this situation is to put each of your different schema's generated files into _seperate targets_ that are linked against by your application targets.
