### ISSUE TITLE
How should I continue after handleErrorAsync inside a custom ApolloErrorInterceptor?

### ISSUE THREAD

**Issue by avielg** [apollographql/apollo-ios#3368]
### Question

I have an error interceptor, meant to log errors and notify users of my SDK via a delegate.

After I am done with the error inside `handleErrorAsync`, what should I do? Should I:
1. Call `proceedAsync(request:response:interceptor:completion:)`? (Assume no because I can't pass `self` as the interceptor, and the chain is done AFAIU?)
2. Call `chain.handleErrorAsync(request:response:completion:)` to pass the error to any other interceptor? Or will that just cause infinite loop?
3. Do nothing?

Thank you! 🙏

**Comment by calvincestari** [comment]
Hi @avielg - when you receive an error like that it should be considered a terminal error re. the request so no you won't be able to continue from where the error was generated. You'd have to restart the request again.

**Comment by avielg** [comment]
Yeap I think my confusion was due to thinking that the error interceptor is an array like the regular interceptors - thinking that there might be other error interceptor that should also "get their turn" to do something with the error, but since there can only be one - I just need to pass the request to the original caller by calling the `completion` and passing `.failure(error)` - which wasn't initially clear for me. I wonder if it makes sense to have a small example showing this in the docs? Specifically where there are examples to the regular interceptors (https://www.apollographql.com/docs/ios/networking/request-pipeline/#example-interceptors), and the error interceptor is mentioned there, but without an example on usage?

Something like this perhaps?

```swift
class LoggerErrorInterceptor: ApolloErrorInterceptor {
    weak var errorLogger: MyErrorLogger?

    init(errorLogger: MyErrorLogger) {
        self.errorLogger = errorLogger
    }

    func handleErrorAsync<Operation: GraphQLOperation>(
        error: Error,
        chain: RequestChain,
        request: Apollo.HTTPRequest<Operation>,
        response: Apollo.HTTPResponse<Operation>?,
        completion: @escaping (Result<GraphQLResult<Operation.Data>, Error>) -> Void
    ) {
        errorLogger?.requestFailed(response?.httpResponse, withError: error)
        completion(.failure(error))
    }
}
```

**Comment by calvincestari** [comment]
Sure thing @avielg. I've got a PR up at https://github.com/apollographql/apollo-ios-dev/pull/336 to add that, thanks for the suggestion.

**Comment by avielg** [comment]
Amazing thanks!
