### ISSUE TITLE
@defer issue

### ISSUE THREAD

**Issue by HandyappGroup** [apollographql/apollo-ios#3372]
### Summary

I've downloaded the latest version, which technically fixes the @defer issue, but the problem is still exists.

### Version

1.10.0

### Steps to reproduce the behavior

Just try to generate new files using defer version fix. This is the version i've used - [https://github.com/apollographql/apollo-ios/releases/tag/preview-defer.2](url)

### Anything else?

![CleanShot 2024-04-26 at 23 33 10](https://github.com/apollographql/apollo-ios/assets/127151414/beed3fc3-7cea-47ce-ad10-f029abd30abc)

**Comment by calvincestari** [comment]
```
Please update your version of the Codegen CLI by following the instructions at: ...
```

@HandyappGroup this error is correct, and expected. You cannot mix versions. You must install, and use, the CLI that from the dependency version your project is using. This looks like you were using `preview-defer.2` and then changed to `1.10.0` but didn't re-install the CLI.

```
Error: JavaScriptError: GraphQLSchemaValidationError-There can be only one directive named "@defer".-GraphQLSchemaValidationError"
```
As for this error, I suggest fixing the first one and then we can focus on whether this is still relevant and in which version.

**Comment by xLuciferSx** [comment]
HI. I've updated Apollo and CLi version to use preview-defer.2 but still getting the same error.

![CleanShot 2024-04-30 at 23 39 24](https://github.com/apollographql/apollo-ios/assets/10944243/21ea782b-2c6c-4a8c-8c6a-c8fb1a4e9e73)
![CleanShot 2024-04-30 at 23 40 23](https://github.com/apollographql/apollo-ios/assets/10944243/2d84ad7e-c882-4254-83b8-aa4b6a08433a)

**Comment by calvincestari** [comment]
Take a look in your schema for the `@defer` directive definition, it will look like this:
```
directive @defer(label: String, if: Boolean! = true) on FRAGMENT_SPREAD | INLINE_FRAGMENT
```
Make sure there is only one `@defer` directive definition.

**Comment by xLuciferSx** [comment]
> Take a look in your schema for the `@defer` directive definition, it will look like this:
> 
> ```
> directive @defer(label: String, if: Boolean! = true) on FRAGMENT_SPREAD | INLINE_FRAGMENT
> ```
> 
> Make sure there is only one `@defer` directive definition.

Removed defer but throwing now different errors. I am happy to share graphqls file over email for team to have a look.

**Comment by xLuciferSx** [comment]
> > I am happy to share graphqls file over email for team to have a look.
> 
> @xLuciferSx - sure, email it to me ([calvin.cestari@apollographql.com](mailto:calvin.cestari@apollographql.com)) and I'll take a look.

Email sent :)

**Comment by calvincestari** [comment]
Closing as this seems to have been a syntax problem in an operation file. The `graphql-js` error messages are misleading and don't clearly point to the actual problem.
