### ISSUE TITLE
Invalid redeclaration of synthesized property '_id'

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#3376]
### Summary

I have a rather urgent issue that popped up when trying to use the TestSupport sources. I get the following static compiler error on a `MockObject` type:
```
Invalid redeclaration of synthesized property '_id'
```

The reason seems to be that it's a type in our schema that defines both a `_id` and a `id` field, and the codegen outputs that, but Swift doesn't like it.

### Version

1.10.0

### Steps to reproduce the behavior

Run codegen while generating mocks for a type with both `_id` and `id` fields. Then try to use the generated `MockObject` for that type.

### Anything else?

```swift
// @generated
// This file was automatically generated and should not be edited.

import ApolloTestSupport
import MySchema

public class MyGeneratedType: MockObject {
  public static let objectType: ApolloAPI.Object = MyGeneratedSchema.Objects.MyGeneratedType
  public static let _mockFields = MockFields()
  public typealias MockValueCollectionType = Array<Mock<MyGeneratedType>>

  public struct MockFields {
    @Field<MyGeneratedSchema.ID>("_id") public var _id
    @Field<MyGeneratedSchema.ID>("id") public var id
  }
}

public extension Mock where O == MyGeneratedType {
  convenience init(
    _id: MyGeneratedSchema.ID? = nil,
    id: MyGeneratedSchema.ID? = nil
  ) {
    self.init()
    _setScalar(_id, for: \._id)
    _setScalar(id, for: \.id)
  }
}
```

**Comment by jimisaacs** [comment]
See https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#propertyWrapper

**Comment by jimisaacs** [comment]
I think we might be able to use `alias`, looking into it.

**Comment by AnthonyMDev** [comment]
Hmmmm... this is one we haven't seen yet.

I don't think `alias` is going to help here. If I recall correctly, the test mocks use the field names on the schema, they don't pay attention to the aliases for fields in the operation definitions.

@BobaFetters the work you're doing for changing schema type names doesn't apply to changing the names of fields on the types, right? Just the actual type names themselves?

**Comment by jimisaacs** [comment]
@AnthonyMDev actually `alias` seemed to have worked for me. If you feel like this is a bug worth solving please leave this open, or close with documentation guidance for `alias`.

**Comment by jimisaacs** [comment]
The `alias` did this:
```
// @generated
// This file was automatically generated and should not be edited.

import ApolloTestSupport
import MySchema

public class MyGeneratedType: MockObject {
  public static let objectType: ApolloAPI.Object = MyGeneratedSchema.Objects.MyGeneratedType
  public static let _mockFields = MockFields()
  public typealias MockValueCollectionType = Array<Mock<MyGeneratedType>>

  public struct MockFields {
    @Field<MyGeneratedSchema.ID>("aliasedId") public var aliasedId
    @Field<MyGeneratedSchema.ID>("id") public var id
  }
}

public extension Mock where O == MyGeneratedType {
  convenience init(
    aliasedId: MyGeneratedSchema.ID? = nil,
    id: MyGeneratedSchema.ID? = nil
  ) {
    self.init()
    _setScalar(aliasedId, for: \.aliasedId)
    _setScalar(id, for: \.id)
  }
}
```

**Comment by AnthonyMDev** [comment]
Ohhh, okay! I was remembering how that worked incorrectly. Great. That is actually the correct solution to this problem then! Thanks for the update.
