### ISSUE TITLE
Incorrect PR link in release notes for version 1.11.0

### ISSUE THREAD

**Issue by tokizuoh** [apollographql/apollo-ios#3381]
### Summary

Hi,
The PR link for "Add refetchOnFailedUpdates to query watcher" in the [release notes for v1.11.0](https://github.com/apollographql/apollo-ios/releases/tag/1.11.0) is incorrect. It currently points to:

https://github.com/apollographql/apollo-ios/pull/347

But it should be:

https://github.com/apollographql/apollo-ios-dev/pull/347

Please update the link to point to the correct PR.
Thanks.

### Version

1.11.0

### Steps to reproduce the behavior

None

**Comment by calvincestari** [comment]
Done
