### ISSUE TITLE
apollo-ios-cli  deprecated --schema-name 

### ISSUE THREAD

**Issue by erwinagpasa** [apollographql/apollo-ios#3382]
### Summary

./apollo-ios-cli init --schema-name ${MySchemaName} --module-type ${ModuleType}
to
./apollo-ios-cli init --schema-namespace ${MySchemaName} --module-type ${ModuleType}

### Version

latest

### Steps to reproduce the behavior

deprecated --schema-name

**Comment by calvincestari** [comment]
Hi @erwinagpasa, I'm not completely sure what the issue is you're trying to describe but I found two outdated references to the deprecated `--schema-name` and fixed them. If you were trying to report something else please let me know.
