### ISSUE TITLE
Naming conflict with Foundation in Xcode 16

### ISSUE THREAD

**Issue by BrentMifsud** [apollographql/apollo-ios#3392]
### Summary

![Screenshot 2024-06-10 at 5 45 11 PM](https://github.com/apollographql/apollo-ios/assets/18543934/dd60f0cd-85b8-4d98-b751-0f1c2ed4e7f8)

### Version

1.12.2

### Steps to reproduce the behavior

1. Open an app in Xcode 16 with apollo as a dependency
2. compile app
3. see compile errors error

**Comment by calvincestari** [comment]
There's a PR up to fix this already - https://github.com/apollographql/apollo-ios-dev/pull/386.
