### ISSUE TITLE
[Xcode 16] Mutating property of a fragment causes compile time error

### ISSUE THREAD

**Issue by martin-muller** [apollographql/apollo-ios#3398]
### Summary

Mutating property of a fragment annotated with `@apollo_client_ios_localCacheMutation` directive causes the following compile time error in Xcode 16 b1 with Swift 6:

> Setter for 'fragments' is unavailable: mutate properties of the fragment instead.

I had a look around online but don't see mentions of changes to behaviour of modify anywhere, do you know if this is issue in Swift or change will have to be done in apollo?

### Version

1.12.2

### Steps to reproduce the behavior

this issue is reproducible in tests for this project:

- https://github.com/apollographql/apollo-ios-dev/blob/d0f87901c087f5c1d5630884874c7df2f4b508ce/Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift#L1073
- https://github.com/apollographql/apollo-ios-dev/blob/d0f87901c087f5c1d5630884874c7df2f4b508ce/Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift#L1074
- https://github.com/apollographql/apollo-ios-dev/blob/d0f87901c087f5c1d5630884874c7df2f4b508ce/Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift#L1226
- https://github.com/apollographql/apollo-ios-dev/blob/d0f87901c087f5c1d5630884874c7df2f4b508ce/Tests/ApolloTests/Cache/ReadWriteFromStoreTests.swift#L1227

**Comment by AnthonyMDev** [comment]
Thanks for making us aware of this. We'll look into this one ASAP. I haven't seen anything in the Swift 6 language that obviously would cause this, but there must be something that changed here.

**Comment by PSinha1202** [comment]
I am pointing to latest tag 1.15.0 and still see the issue. I expected this to be fixed and ready in latest tags, am I missing something?

**Comment by AnthonyMDev** [comment]
Have you re-run the code generation with the latest version? This fix changes the generated models to remove the warning.
