### ISSUE TITLE
Package Resolution Failed: Invalid Manifest when installing a library with an Apollo dependency

### ISSUE THREAD

**Issue by sa-ma** [apollographql/apollo-ios#3402]
### Question

I don't know if this is the right place to ask this.

I developed a library with Swift Package Manager that uses Apollo for network calls. The problem is that the Swift package manager does not allow the installation of remote packages with a local target [SE-0201 60](https://github.com/apple/swift-evolution/blob/main/proposals/0201-package-manager-local-dependencies.md), this stops me from adding my Swift package to other applications. Apollo Schema uses a local target for adding a schema to the Swift package so there is a conflict. Is there any way around this?

**Comment by calvincestari** [comment]
Hi @sa-ma - I'm not sure whether I understand your issue correctly.

What I _think_ you're describing is that you're trying to distribute your own Swift package that uses Apollo iOS but as a _local_ dependency? To do that you'd need to ensure that any project using _your_ Swift package had already manually cloned the Apollo iOS repo to the path defined in your Package.swift file. This is not the way that Swift packages are meant to be distributed.

Why do you need a local dependency vs. the remote dependency?
