### ISSUE TITLE
Cannot find 'LaunchListQuery' in scope

### ISSUE THREAD

**Issue by conradwt** [apollographql/apollo-ios#3403]
### Summary

In step 5 of Build a project with Apollo tutorial, I'm getting an error when I add the following code to the _init()_ method:

**Implement the query**

```swift
    Network.shared.apollo.fetch(query: LaunchListQuery()) { result in
        switch result {
        case .success(let graphQLResult):
            print("Success! Result: \(graphQLResult)")
        case .failure(let error):
            print("Failure! Error: \(error)")
        }
    }
``` 

Errors:

```
Cannot find 'LaunchListQuery' in scope
Generic parameter 'Query' could not be inferred
```

### Version

1.13.0

### Steps to reproduce the behavior

1. Complete Tutorial Steps 1 - 5

### Logs

```shell
Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
```

### Anything else?

I have tried with Xcode 15.4 on macOS 14.5 without success.

**Comment by calvincestari** [comment]
Hi @conradwt - have you made sure to add `import RocketReserverAPI` to that file? The queries are generated into a separate module so [you'll need to explicitly import it](https://github.com/apollographql/iOSTutorial/blob/main/final/RocketReserver/LaunchListViewModel.swift#L2) before you can use it.
