### ISSUE TITLE
`.editorconfig`

### ISSUE THREAD

**Issue by TizianoCoroneo** [apollographql/apollo-ios#3404]
### Use case

Xcode 16 introduces support for `.editorconfig` files that represent settings like spaces VS tabs, how many spaces per tab, etc…

Today, every time I want to contribute to the Apollo project I have to switch my editor settings back and forth 😁 adopting this standard would solve the issue.

### Describe the solution you'd like

Add a `.editorconfig` file with your preferred settings, so that the editor will pick up on them automatically.
You can see an example implementation in https://github.com/pointfreeco/swift-gen/issues/27

**Comment by BobaFetters** [comment]
@TizianoCoroneo Thanks for the suggestion, this seems like it would be really useful to have so I will look at getting it added sometime this week.
