### ISSUE TITLE
Type 'Operation' has no member 'deferredSelectionSetType' in IncrementalGraphQLResponse

### ISSUE THREAD

**Issue by marcellodepalo** [apollographql/apollo-ios#3415]
### Summary

v1.14.0 is broken
Type 'Operation' has no member 'deferredSelectionSetType' in IncrementalGraphQLResponse

<img width="1239" alt="Screenshot 2024-07-22 at 12 50 05" src="https://github.com/user-attachments/assets/baa9ab8a-d5f1-4377-abae-adca07542f4d">

### Version

1.14.0

### Steps to reproduce the behavior

upgrade package to v1.14.0

**Comment by calvincestari** [comment]
Hi @marcellodepalo, did you find out the problem here? Is 1.14.0 working for you now?
