### ISSUE TITLE
GraphQLError issue

### ISSUE THREAD

**Issue by tkallioras** [apollographql/apollo-ios#342]
I am a bit baffled by the way the framework deals with errors.

For example I have a mutation like that:

```
mutation SignUp($email: String!, $password: String!) {
  signUp(email: $email, password: $password) {
    success
  }
}
```

If I run this mutation through a client, eg Insomnia, omitting lets say the `email` property, I get back the following error:

```
{
	"data": {
		"signUp": null
	},
	"errors": [
		{
			"message": "Database error: email cannot be empty, message: email cannot be empty
			"path": [
				"signUp"
			]
		}
	]
}
```

However if I run the same query with apollo-ios I get `result == nil` (expected) and the error I get is the following: 

`Apollo.GraphQLResultError(path: ["signUp"], underlying: Apollo.JSONDecodingError.nullValue)`

Where is the message of the error?

Additionally, are there any docs explaining the different kind of errors the framework produces?

**Comment by martijnwalraven** [comment]
@tkallioras It sounds like the `signUp` field has not been defined as nullable in your schema, and because according to the spec non-nullable errors bubble up, I would expect the result from the server to be:
```
"data": null
"errors": ...
```
What GraphQL server are you using?

**Comment by martijnwalraven** [comment]
To answer your question, `GraphQLResultError` is produced when there is an error interpreting the response as a valid GraphQL result. Errors sent by the server are returned under `result.errors`.

**Comment by tkallioras** [comment]
I am using the following golang library [https://github.com/vektah/gqlgen/](https://github.com/vektah/gqlgen/ ) (which in turn has borrowed some core functionality from this golang library: [https://github.com/graph-gophers/graphql-go](https://github.com/graph-gophers/graphql-go))

**Comment by martijnwalraven** [comment]
In GraphQL, fields are nullable by default, but you can define them as non-null if you need to. Errors however, lead to a `null` result from the resolver they are thrown from, so these `null` results 'bubble up' until they encounter a field that *is* nullable:
> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. In that case, the path for the error should include the full path to the result field where the error occurred, even if that field is not present in the response.
(http://facebook.github.io/graphql/draft/#sec-Errors)

In your case, you're returning an error for `signUp`, and because `signUp` cannot be `null` the error would be expected to bubble up to `data`.

**Comment by martijnwalraven** [comment]
You can fix this by not making `signUp` non-null. But if it is non-null, it seems the server library you're using does not follow the spec so this should be fixed.

**Comment by designatednerd** [comment]
Since this appears to be an issue on the server side library, I'm going to go ahead and close this issue out. Please feel free to re-open or open a new issue if you're still encountering problems!
