### ISSUE TITLE
Generated code cannot compile when using include directive on field that is selected on interface and implementation

### ISSUE THREAD

**Issue by guillian-balisi** [apollographql/apollo-ios#3424]
### Summary

Apollo is generating some intermediary type `If<name_of_boolean_parameter>` when selecting fields both on an interface type and an type that implements that interface while using the `@include` directive. This `If<name_of_boolean_parameter>` type uses types that are not defined. The generated code does not compile.

### Version

1.14.0

### Steps to reproduce the behavior

This example is based on the final project of https://github.com/apollographql/iOSTutorial/.

Please download the project on my fork here: https://github.com/guillian-balisi/iOSTutorial/. The differences are in https://github.com/guillian-balisi/iOSTutorial/commit/5075b109e7157b1333a982c66886aea119b6bd95, namely:

1. Added some new types in schema
2. Added Foo.graphql query
3. Ran `./apollo-ios-cli generate`

If you download the project and open final/RocketReserver.xcodeproj and try to build, it will fail. 

Please see the generated code for Foo.graphql: https://github.com/guillian-balisi/iOSTutorial/blob/main/final/RocketReserverAPI/Sources/Operations/Queries/FooQuery.graphql.swift.

Compilation fails because there is the `IfIncludeCurrentUserAwards` struct with property [awardingByCurrentUser](https://github.com/guillian-balisi/iOSTutorial/blob/5075b109e7157b1333a982c66886aea119b6bd95/final/RocketReserverAPI/Sources/Operations/Queries/FooQuery.graphql.swift#L128) of type `AwardingByCurrentUser`, but type `AwardingByCurrentUser` does not exist within this namespace.

The workaround we've been using is to move the `@include(if: $includeCurrentUserAwards)` directive off the `awardings` field and on to the `awardingByCurrentUser` field: 

```graphql
query Foo($includeCurrentUserAwards: Boolean = false) {
    postsInfoByIds {
        ... on Post {
            awardings {
                total
            }
        }
        awardings {
            awardingByCurrentUser @include(if: $includeCurrentUserAwards) {   # <---- moved the directive here
                id
            }
        }
    }
}
```

With that the generated code compiles. But we should expect the generated code to compile regardless of where we use the `@include` directive.

**Comment by calvincestari** [comment]
Thanks for reporting the issue @guillian-balisi, I'll take a look at the reproduction case and get back to you shortly.

**Comment by calvincestari** [comment]
Thanks for the reproduction case, I've confirmed it's a valid codegen bug. I'm hoping we can get this into the next release.
