### ISSUE TITLE
apollo-ios-xcframework doesn't add bundle identifier to the Info.plist for the created xcframework

### ISSUE THREAD

**Issue by Karram-Ayman** [apollographql/apollo-ios#3425]
### Summary

The apollo-ios-xcframework does not automatically add a CFBundleIdentifier to the Info.plist files of the created XCFrameworks when using the provided Makefile script. As a result, when you try to link Apollo.xcframework and ApolloAPI.xcframework in an Xcode project using the "Embed and Sign" option, the build may succeed, but a runtime error will occur. This error indicates that ApolloAPI.framework (or Apollo.framework) is missing a CFBundleIdentifier in its Info.plist, which is required for proper framework embedding.

<img width="710" alt="Screenshot 2024-08-14 at 1 16 05 PM" src="https://github.com/user-attachments/assets/4f727a74-0dc4-47ef-b269-fdecd1f2cf3e">

### Version

1.14.1

### Steps to reproduce the behavior

1. Following the make script to create xcframework in https://github.com/apollographql/apollo-ios-xcframework 
2. Add created xcframework to Xcode project link frameworks target with embed & Sign 
3. Run the project 

### Logs

```shell
Payload/MyProject.app/Frameworks/ApolloAPI.framework did not have a CFBundleIdentifier in its Info.plist
```

**Comment by BobaFetters** [comment]
Thanks for the report @Karram-Ayman have a PR up that should resolve this https://github.com/apollographql/apollo-ios-xcframework/pull/18
