### ISSUE TITLE
make build-apollo-xc-framework fail with Error 70 

### ISSUE THREAD

**Issue by Karram-Ayman** [apollographql/apollo-ios#3427]
### Summary

Following creating xcframework from https://github.com/apollographql/apollo-ios-xcframework?tab=readme-ov-file make script fail 9 times out of 10 tries with Error 70  

### Version

1.14.1

### Steps to reproduce the behavior

1. Clone repo 
2. Run make build-apollo-xc-framework

### Logs

```shell
Runing RegisterExecutionPolicyException /Users/a/Library/Developer/Xcode/DerivedData/Apollo-btbrgifwrrzzezcxjrmbkksenqto/Build/Intermediates.noindex/ArchiveIntermediates/Apollo/InstallationBuildProductsLocation/Users/a/Objects/Apollo.o (in target 'Apollo' from project 'Apollo' at path '/Users/a/Downloads/apollo-ios-xcframework-main/apollo-ios/Package.swift')
    cd /Users/a/Downloads/apollo-ios-xcframework-main/apollo-ios
    builtin-RegisterExecutionPolicyException /Users/a/Library/Developer/Xcode/DerivedData/Apollo-btbrgifwrrzzezcxjrmbkksenqto/Build/Intermediates.noindex/ArchiveIntermediates/Apollo/InstallationBuildProductsLocation/Users/a/Objects/Apollo.o

** ARCHIVE SUCCEEDED **

xcodebuild -create-xcframework -output ./build/Apollo.xcframework -framework ./build/iphonesimulator.xcarchive/Products/Library/Frameworks/Apollo.framework -framework ./build/iphoneos.xcarchive/Products/Library/Frameworks/Apollo.framework
error: the path does not point to a valid framework: /Users/a/Downloads/apollo-ios-xcframework-main/build/iphonesimulator.xcarchive/Products/Library/Frameworks/Apollo.framework
make: *** [build-apollo-xc-framework] Error 70
```

### Anything else?

Even though ** ARCHIVE SUCCEEDED ** and build folder is been created with iphoneos.xcarchive and iphonesimulator.xcarchive 
still, failure happen with [build-apollo-xc-framework] Error 70 and xcframework been created

**Comment by BobaFetters** [comment]
Thanks for the report @Karram-Ayman , to help with investigating can you also tell me what version of Xcode/Xcode command line tools you are running?

**Comment by Karram-Ayman** [comment]
Hi @BobaFetters thank you for checking here is my Xcode and command line version 
Xcode 15.1
Build version 15C65

**Comment by Karram-Ayman** [comment]
@BobaFetters I am not sure if this helps but most of the time this works only if I open my terminal and **do not** use the script and call in my terminal step by step sometimes it does the same error but not as often as the script 

I also try to call this before 
`rm -rf ~/Library/Developer/Xcode/Archives/*`

Then
`xcodebuild archive -configuration Release -project "Apollo.xcodeproj" -scheme "Apollo" -destination 'generic/platform=iOS Simulator' -archivePath "./build/iphonesimulator.xcarchive" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES `

Then 
`xcodebuild archive -configuration Release -project "Apollo.xcodeproj" -scheme "Apollo" -destination 'generic/platform=iOS' -archivePath "./build/iphoneos.xcarchive" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES`

Then 
`xcodebuild -create-xcframework -output ./build/Apollo.xcframework -framework ./build/iphonesimulator.xcarchive/Products/Library/Frameworks/Apollo.framework -framework ./build/iphoneos.xcarchive/Products/Library/Frameworks/Apollo.framework`

**Comment by calvincestari** [comment]
Based on the number of [search results](https://www.google.com/search?q=xcodebuild+error+70&rlz=1C5GCEM_enCA1110CA1110&oq=xcodebuild+error+70&gs_lcrp=EgZjaHJvbWUyCQgAEEUYORiABDINCAEQABiGAxiABBiKBdIBCDMzNTBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8) for xcodebuild error 70 I don't think this is apollo-xc-framework specific. It looks like a combination of some other external factors.

**Comment by Karram-Ayman** [comment]
Hi @BobaFetters is there any plan to support building xcframework for `ApolloTestSupport` in https://github.com/apollographql/apollo-ios-xcframework?

**Comment by calvincestari** [comment]
No plans at the moment @Karram-Ayman. If there is enough of a use case and it's of benefit to the large part of the community then we can consider it.

**Comment by Karram-Ayman** [comment]
Thanks for getting back to me @calvincestari

**Comment by BobaFetters** [comment]
@Karram-Ayman I have a PR up to fix another issue, and from what I can tell it also fixes this issue, not 100% sure still what was causing this but once we do another release this should be fixed.

Also we have had some other inquiries about `ApolloTestSupport` support so I am going to look into getting that added as well
