### ISSUE TITLE
Setter for local cache mutation is unavailable, mutate properties of fragment

### ISSUE THREAD

**Issue by PSinha1202** [apollographql/apollo-ios#3428]
### Summary

There seems to be related bug #3398 which was resolved before but when today when I run the Apollo tag 1.15.0 with Xcode 16 beta and swift 5, fragment annotated with @apollo_client_ios_localCacheMutation directive causes compile time error

`Setter for `<nameOfFragments>' is unavailable: mutate properties of the fragment instead.`

Can I get a confirmation if the issue still persist?

### Version

1.15.0

### Steps to reproduce the behavior

update Apollo to latest 1.15.0 
Xcode 16 beta with swift 5 
compile our codebase and found two errors and both related to same fragment those are annotated with @apollo_client_ios_localCacheMutation

**Comment by PSinha1202** [comment]
ahh I see, let me try that and confirm @AnthonyMDev

**Comment by PSinha1202** [comment]
ok so tried the re-run code gen and I get into this error 

Error: typeMismatch(ApolloCodegenLib.ApolloCodegenConfiguration.SelectionSetInitializers, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "options", intValue: nil), CodingKeys(stringValue: "selectionSetInitializers", intValue: nil)], debugDescription: "Unrecognized key found: localCacheMutations", underlyingError: nil))
Finished fetch + codegen

I tried deleting all models to re-run code gen but still seeing the above issue.

**Comment by PSinha1202** [comment]
Sure will try, but as of now I have downgraded to 1.14.1 and re-ran the codeine and it seems to fix my original issue and I am able to compile my code. Will check the 1.15.0 or later version in couple of days.

**Comment by AnthonyMDev** [comment]
Sounds good. This should be resolved. If you are still having issues, let us know and we can re-open the issue.
