### ISSUE TITLE
Suport for OneOf Input Objects

### ISSUE THREAD

**Issue by cabeca** [apollographql/apollo-ios#3430]
### Question

Hello!

I tried to look for it in the Roadmap, and in the issue tracker but I could not find any information about it. Apologies if I missed an obvious place. 
I was wondering if there are any plans to support [`OneOf` Input Objects](https://github.com/graphql/graphql-spec/pull/825) on apollo-ios, now that it has been added to the GraphQL spec. 
Is this addition being considered an if so, do you have any rough timeline for it?

Thanks!

**Comment by cabeca** [comment]
Thank you for the update!

**Comment by ruudk** [comment]
FWIW, it's now officially supported: https://graphql.org/blog/2025-09-04-multioption-inputs-with-oneof/
