### ISSUE TITLE
Directives (`@include`, `@skip` etc) not working with Mocks

### ISSUE THREAD

**Issue by asaadreh-meister** [apollographql/apollo-ios#3449]
### Summary

I use several `include`s and `skip`s in my queries. They are working fine in the app. However, while writing tests for the code, I noticed that any field or fragment marked with `include` is always omitted. I tested it with skip and it was the same. If i leave out the include, the correct object is returned. 

Is this issue known? Is there a workaround? (without having to remove the directives)

### Version

1.15.1

### Steps to reproduce the behavior

My query looks like this:
```
query GetTaskQuery(
    $taskId: Int!,
    $token : String!,
    $loadWithId : Boolean = false,
    $loadWithToken : Boolean = false
) {
    find_task(id: $taskId) @include(if: $loadWithId) {
        ...TaskItemView
    }

    find_task_by_token(token: $token) @include(if: $loadWithToken) {
        ...TaskItemView
    }
}
```
A very basic test is:

```
class TestIncludeQuery: _SyncEngineOperationTestCase {
	func testIncludeQuery() async throws {
		
		let client = MockGraphQLClient(query: givenQueryMock())
		let res = try await client.fetch(
			query: MTApolloClient.GetTaskQuery(
				taskId: 1,
				token: "abc",
				loadWithId: true,
				loadWithToken: false,
				attachmentCursor: nil,
				checklistsCursor: nil,
				customFieldsCursor: nil,
				targetRelationshipsCursor: nil,
				ownerRelationshipsCursor: nil,
				taskLabelsCursor: nil,
				taskSubscriptionCursor: nil,
				workIntervalsCursor: nil,
				customFieldTypesCursor: nil,
				projectRightsCursor: nil,
				activeSectionsCursor: nil
			),
			cachePolicy: .fetchIgnoringCacheCompletely,
			contextIdentifier: nil
		)
		XCTAssertEqual(res.findTask?.id, 1)
	}

	private func givenQueryMock() -> Mock<MeisterTaskQuery> {
		Mock<MeisterTaskQuery>(
			find_task: Mock<Task>(
				id: 1,
				name: "Mock Task",
				token: "abc"
			),
			find_task_by_token: Mock<Task>(
				id: 1,
				name: "Mock Task",
				token: "abc"
			)
		)
	}
}
```

Any field or fragment that has `include` in it is returned as nil in the mocks. In the actual app it works fine.

**Comment by BobaFetters** [comment]
@asaadreh-meister To get the variables properly mapped onto your selection set you should be able to use the [from(_ mock: withVariables:)](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloTestSupport/TestMock.swift#L124) method on your selection set and pass in the variables being used for your include/skip conditions.

A very basic usage of this is shown in [this test](https://github.com/apollographql/apollo-ios-dev/blob/main/Tests/ApolloTests/TestMockTests.swift#L370).

**Comment by BobaFetters** [comment]
Going to go ahead and close this since the above comment should resolve the issue, feel free to comment if this is still an issue and we can reopen and investigate.
