### ISSUE TITLE
"Warning: apollo update available from 1.2.0 to 1.6.0" when apollo 1.6.0 is installed

### ISSUE THREAD

**Issue by coamw2** [apollographql/apollo-ios#345]
I am integrating apollo iOS client into an app following the instructions at https://www.apollographql.com/docs/ios/installation.html

I have apollo 1.6.0 installed (I can see this from "apollo -v" command). However when building, the run script phase gives the messages "Warning: apollo update available from 1.2.0 to 1.6.0" and "Error: Flag --queries expects a value". I have tried the web with no luck, so thought I'd try here. Many thanks.

**Comment by ryanjohndias** [comment]
@coamw2 What was your solution?

**Comment by coamw2** [comment]
@ryanjohndias The warning part can be ignored. The error part was because I did not have any .graphql files in the project. These are the files that contain the queries to be used by the app. Even if you don't have any client queries yet, you need at least 1 .graphql file in your project to prevent the error.
