### ISSUE TITLE
Getting error on installing latest Apollo client (0.9.2) through pod install

### ISSUE THREAD

**Issue by pranita-mindstix** [apollographql/apollo-ios#346]
I have installed latest Apollo - '0.9.2' for my iOS project, but I am getting compile time errors, PFA for the same - 
<img width="666" alt="screen shot 2018-08-08 at 6 00 11 pm" src="https://user-images.githubusercontent.com/8039894/43837138-3a779d0a-9b35-11e8-9733-6b51ac34a3d9.png">

**Comment by martijnwalraven** [comment]
@pranita-mindstix What versions of Xcode/Swift are you using? Apollo iOS only works with the latest versions.

**Comment by pranita-mindstix** [comment]
Swift version 4.0.3 and Xcode - 9.2

**Comment by martijnwalraven** [comment]
@pranita-mindstix Any particular reason you haven't updated to Xcode 9.4 and Swift 4.2? As far as I know, you won't be able to submit apps to the App Store with an older version of Xcode, so there is no reason for us not to limit ourselves to supporting the latest version.

**Comment by pranita-mindstix** [comment]
Ok will give a try after upgrading to newer versions.

**Comment by pranita-mindstix** [comment]
@martijnwalraven I have updated Xcode to 9.4.1 and swift to 4.2. And updated Apollo to 0.9.2
I am getting following error - 

"~/Library/Developer/Xcode/DerivedData/ELX-gvodnmmgcdoqqjbnznyphheabxjy/Build/Products/Dev-iphonesimulator/Apollo/Apollo.framework/check-and-run-apollo-codegen.sh: No such file or directory"

**Comment by martijnwalraven** [comment]
@pranita-mindstix There has been a change to the codegen script because of the switch to a new Apollo CLI, see [here](https://www.apollographql.com/docs/ios/installation.html#adding-build-step) for the correct build script.

**Comment by pranita-mindstix** [comment]
Thanks @martijnwalraven It worked for me :)

I know it may not be the right place but can you please share any links on caching through Apollo in iOS application if you have. I am troubling with caching issue from past few days. I can't see any good documentation on caching in iOS through Apollo graphql library.

**Comment by martijnwalraven** [comment]
@pranita-mindstix I realize the documentation is pretty sparse, but have you seen https://www.apollographql.com/docs/ios/watching-queries.html?

**Comment by pranita-mindstix** [comment]
@martijnwalraven Yes I have checked with the link, but nothing is working in my application.

Thanks for your quick help, I can now install the app with all dependencies exists..

**Comment by antonbremer** [comment]
I am also having trouble trying to update from Apollo 0.8.0 to 0.9.2.
I did change the build script to the new version, but I am getting an error in the build script when it tries to install Apollo CLI:

```Can't find Apollo CLI. Installing...
npm ERR! code ENOLOCAL
npm ERR! Could not install from "<my project directory>" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/antonbremer/.npm/_logs/2018-08-29T12_32_26_049Z-debug.log
Command /bin/sh failed with exit code 1```

Seems it is missing a package.json which indeed is not there in the directory it's looking for.
Is there anything I am doing wrong here? Do I need to get the package.json from somewhere?
