### ISSUE TITLE
Websocket Data Race when stream connection fails

### ISSUE THREAD

**Issue by aaronbarsky** [apollographql/apollo-ios#3466]
### Summary

When stream connection fails triggering doDisconnect, the code to set the callback queue runs concurrently with doDisconnect which reads the callback queue.
<img width="1554" alt="Screenshot 2024-10-29 at 12 01 11 PM" src="https://github.com/user-attachments/assets/c665f6b9-323a-494a-a183-3683d92932c4">

I believe this can be resolved, by moving the assignment of the callback queue before the connect call (line 173 to 170).

### Version

1.13.1

### Steps to reproduce the behavior

It's a race condition, so it's hard to reproduce.
Discovered by running Xcode with the Thread Sanitizer enabled.

**Comment by calvincestari** [comment]
Thanks @aaronbarsky. I can the see potential for the data race here so I've made the change in [PR #529](https://github.com/apollographql/apollo-ios-dev/pull/529). To be honest it makes sense to assign the given queue as early as possible, I'm not sure why it was in that order before.

**Comment by calvincestari** [comment]
@aaronbarsky, this change is merged and will go out with the next release.
