### ISSUE TITLE
High likelihood of identical hash values for GraphQLOperation types

### ISSUE THREAD

**Issue by aim2120** [apollographql/apollo-ios#3467]
### Question

I recently discovered that `GraphQLOperation` hashing does not differentiate operations as much as I thought it would. In fact, if two operations both have no variables, they have the same hash value, even if they're entirely different operation types.

This is due to the way `hash(into:)` is implemented for `GraphQLOperation`
```swift
public extension GraphQLOperation {
  var __variables: Variables? {
    return nil
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine(__variables?._jsonEncodableValue?._jsonValue)
  }
}
```

This seems like an unfortunate design decision. A few questions for the maintainers of the project:
* Is there a particular reasons why there's a high likelihood completely different operations may have the same hash value?
* Would it be viable to change the hash implementation to hash on operation identifiers in addition to the variables (e.g. operation name, ID, type)?

I've already updated my usage of the hash value based on this finding, but wanted to create an issue in case it may affect others.

**Comment by calvincestari** [comment]
Thanks for raising the issue @aim2120. Are you using the hash value from an operation directly that you noticed this?

**Comment by calvincestari** [comment]
@aim2120, the change is merged and will go out in the next release.

**Comment by aim2120** [comment]
Hey @calvincestari, thanks for getting that updated! Yes, I was using the hash value in an interceptor implementation when I noticed the behavior.
