### ISSUE TITLE
If there are many duplicate fields across implemented types, is there a way to access them, and get nil if the type does not have the field?

### ISSUE THREAD

**Issue by JOyo246** [apollographql/apollo-ios#3469]
### Question

In our schema, there are cases where there are many polymorphic types that all have the same field, but one type does not have the type, so it is not placed at the top level of the shared type.

Is there any way to access that field by name, if it exists, but get nil if it does not exist?

This is what I'm currently writing which feels super verbose:

```
extension MyType {
    var someBoolFieldShared: Bool? {
        if let subType1 {
            return subType1.someBoolField
        } else if let subType2 {
            return subType2.someBoolField
        } else if let subType3 {
            return subType3.someBoolField
        } else if let subType4 {
            return subType4.someBoolField
        } else if let subType5 {
            return subType5.someBoolField
        } else if let subType6 {
            return subType6 .someBoolField
        }
        return nil
    }
}
```

**Comment by calvincestari** [comment]
Hi @JOyo246 - there isn't any way within code generation to automatically have this done for you. The best is what you have now in a custom extension unfortunately.
