### ISSUE TITLE
1.15.3 CLI parent type change

### ISSUE THREAD

**Issue by WilliamNumerade** [apollographql/apollo-ios#3477]
### Question

We just upgraded the CLI from 1.9.3 to 1.15.3.
With this update, `__parentType` added `any` to `ApolloAPI.ParentType`, and now we are getting:
`Type 'GraphQL' has no member 'ID'`
and also:
`'ID' is not a member type of enum 'Numerade.NumeradeGraphQL'`

Would appreciate any help getting around this.

**Comment by WilliamNumerade** [comment]
It turns out that the auto-generated ID extension file was not automatically added to the project.

**Comment by calvincestari** [comment]
I think the change you're noticing with `ID` might be from [release `1.12.0`](https://github.com/apollographql/apollo-ios/releases/tag/1.12.0).
> `ID` as a custom scalar (https://github.com/apollographql/apollo-ios/issues/3379): This changes the generation of the built-in GraphQL `ID` scalar to be treated as a custom scalar that can be modified by the user. See PR https://github.com/apollographql/apollo-ios-dev/pull/363.

As for `any` being added to `__parentType` - this shouldn't cause any problems and it is a change to support the existential `any` feature introduced in Swift 5.6.
