### ISSUE TITLE
Migration from 0.53 to 1.15 missing factory methods & alternatives

### ISSUE THREAD

**Issue by bsrz** [apollographql/apollo-ios#3482]
### Question

We migrating our giant code base from 0.53 to 1.15.
There used to be generated factory methods to create types. We used those for tests. For example:
```swift
ButtonsRowFragment(
    buttons: [
        .makeAppPresentation_PrimaryButtonComponent(icon: "time", link: .init(
            unsafeResultMap: InternalLinkFragment(
                text: .init(text: "AppAccountSupport"),
                route: .init(unsafeResultMap: RoutingRouteFragment(
                    page: "AppAccountSupport",
                    params: [:]
                ).resultMap)
            ).resultMap
        )),
        .makeAppPresentation_BorderlessButton(link: .init(
            unsafeResultMap: InternalLinkFragment(
                text: .init(text: "AppAccountSupport"),
                route: .init(unsafeResultMap: RoutingRouteFragment(
                    page: "AppAccountSupport",
                    params: [:]
                ).resultMap)
            ).resultMap
        )),
        .makeAppPresentation_SecondaryButtonComponent(link: .init(
            unsafeResultMap: InternalLinkFragment(
                text: .init(text: "AppAccountSupport"),
                route: .init(unsafeResultMap: RoutingRouteFragment(
                    page: "AppAccountSupport",
                    params: [:]
                ).resultMap)
            ).resultMap
        )),
        .makeAppPresentation_TertiaryCommerceButton(link: .init(
            unsafeResultMap: InternalLinkFragment(
                text: .init(text: "AppAccountSupport"),
                route: .init(unsafeResultMap: RoutingRouteFragment(
                    page: "AppAccountSupport",
                    params: [:]
                ).resultMap)
            ).resultMap
        )),
    ]
)
```

I'm trying to recreate the first button from the example above:

```swift
ButtonsRowFragment.Button(
    _dataDict: ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent(
        icon: "time",
        link: ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link(
            _dataDict: ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.AsAppPresentation_InternalOrExternalLink(
                _dataDict: InternalOrExternalLinkFragment(
                    _dataDict: InternalOrExternalLinkFragment.AsAppPresentation_InternalLink(
                        text: InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Text(text: "AppAccountSupport"),
                        route: InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Route(
                            page: "AppAccountSupport",
                            params: .dictionary([:])
                        )
                    ).__data
                ).__data
            ).__data
        )
    ).__data
)
```
and not matter what I do, `value.asAppPresentation_PrimaryButtonComponent?.link?.asAppPresentation_InternalOrExternalLink` always ends up being nil. I feel like I've tried a ton of permutations but none of them work. I'm clearly missing something. Am I missing something completely obvious? It appears that using `.__data` doesn't cary the typenames over? Are there any docs on how resultMap compares to DataDict?

Any help would be very appreciated 🙌

**Comment by calvincestari** [comment]
Hi @bsrz - it sounds like you're looking for the [Selection Set Initializers](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#selection-set-initializers) feature. This provides an equivalent way to instantiate the generated models.

> and not matter what I do, `value.asAppPresentation_PrimaryButtonComponent?.link?.asAppPresentation_InternalOrExternalLink` always ends up being nil. I feel like I've tried a ton of permutations but none of them work. I'm clearly missing something. Am I missing something completely obvious? It appears that using `.__data` doesn't cary the typenames over? Are there any docs on how resultMap compares to DataDict?

It's recommended to steer clear of the underscored properties/functions, such as the `_dataDict` initializer. While they're public they are meant for internal use and could change without notice.

As an FYI - the reason you're always getting nil is because `DataDict` also contains a `fulfilledFragments` property which needs to be correctly set for the underlying type logic to work correctly. Once you re-generate your models with the selection set initializers you'll be able to see what I'm talking about.

Try that and let me know if it still doesn't resolve your issue.

**Comment by bsrz** [comment]
@calvincestari thank you for the reply.
This is the config I'm working with at the moment:
```json
{
    "schemaNamespace": "GraphQL",
    "operationManifest": {
        "generateManifestOnCodeGeneration": true,
        "path": "../../Generated/operation_ids.json",
        "version": "persistedQueries"
    },
    "experimentalFeatures": {
        "fieldMerging": [
            "all"
        ],
        "legacySafelistingCompatibleOperations": true
    },
    "input": {
        "schemaSearchPaths": [
            "./*.graphqls"
        ],
        "operationSearchPaths": [
            "../**/*.graphql"
        ]
    },
    "options": {
        "pruneGeneratedFiles": true,
        "selectionSetInitializers": {
            "operations": true,
            "namedFragments": true
        },
    },
    "output": {
        "schemaTypes": {
            "moduleType": {
                "other": {}
            },
            "path": "../../Generated/"
        },
        "operations": {
            "inSchemaModule": {}
        },
        "testMocks": {
            "none": {}
        }
    }
}
```

I already have the `selectionSetInitializers` property set to true for operations and named fragments. Is there another property I'm missing?

If you see in the example I posted in the original comment, the inits with DataDict are the only inits available to me except for the ones that have an generated initializer:

| type name | init |
| --------- | ---- |
| ButtonsRowFragment.Button | DataDict |
| ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent | generated init |
| ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link | DataDict |
| ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.AsAppPresentation_InternalOrExternalLink | DataDict|
| InternalOrExternalLinkFragment | DataDict |
| InternalOrExternalLinkFragment.AsAppPresentation_InternalLink | generated init |
| InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Text | generated init |
| InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Route | generated init |

I should mention that some of these types are Union types.
Is there a way to generate initializers for the types that don't have any?

**Comment by calvincestari** [comment]
> I should mention that some of these types are Union types.
> Is there a way to generate initializers for the types that don't have any?

Not at the moment no. I think you might be needing to use the [`asRootEntityType` property](https://www.apollographql.com/docs/ios/development/selection-set-initializers#type-conditions) for those types.

If you're able to share some of the Swift generated types (such as `ButtonsRowFragment.Button`, `ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent`) to my email address (`calvin.cestari@apollographql.com`) I can take a closer look.

**Comment by bsrz** [comment]
> Not at the moment no. I think you might be needing to use the [asRootEntityType property](https://www.apollographql.com/docs/ios/development/selection-set-initializers#type-conditions) for those types.

yeah, so I've tried that too, these are all the tests I've written where the assertions fails because the property is continuously nil

```swift
    func test0() {
        let internalLink = InternalOrExternalLinkFragment.AsAppPresentation_InternalLink(
            text: InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Text(text: "AppAccountSupport"),
            route: InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Route(
                page: "AppAccountSupport",
                params: .dictionary([:])
            )
        )

        let intOrExt = InternalOrExternalLinkFragment(
            _dataDict: internalLink.__data
        )
        let link0 = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.AsAppPresentation_InternalOrExternalLink(
            _dataDict: intOrExt.__data
        )
        let link = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link(
            _dataDict: link0.__data
        )
        let data = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent(
            icon: "time",
            link: link
        )
        let finalButton = ButtonsRowFragment.Button(
            _dataDict: data.__data
        )

        XCTAssertNotNil(finalButton.asAppPresentation_PrimaryButtonComponent?.link?.asAppPresentation_InternalOrExternalLink?.fragments.internalOrExternalLinkFragment)
    }

    func test1() {
        let internalLink = InternalOrExternalLinkFragment.AsAppPresentation_InternalLink(
            text: InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Text(text: "AppAccountSupport"),
            route: InternalOrExternalLinkFragment.AsAppPresentation_InternalLink.Route(
                page: "AppAccountSupport",
                params: .dictionary([:])
            )
        ).asRootEntityType

        let link = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.AsAppPresentation_InternalOrExternalLink(
            _dataDict: internalLink.__data
        ).asRootEntityType

        let finalButton = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent(
            icon: "time",
            link: link
        ).asRootEntityType

        XCTAssertNotNil(finalButton.asAppPresentation_PrimaryButtonComponent?.link?.asAppPresentation_InternalOrExternalLink?.fragments.internalOrExternalLinkFragment)
    }

    func test2() {
        let otherLink = InternalLinkFragment(
            text: InternalLinkFragment.Text(text: "AppAccountSupport"),
            route: InternalLinkFragment.Route(
                page: "AppAccountSupport",
                params: .dictionary([:])
            )
        )

        let link = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.AsAppPresentation_InternalOrExternalLink(
            _dataDict: otherLink.__data
        ).asRootEntityType

        let finalButton = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent(
            icon: "time",
            link: link
        ).asRootEntityType

        XCTAssertNotNil(finalButton.asAppPresentation_PrimaryButtonComponent?.link?.asAppPresentation_InternalOrExternalLink?.fragments.internalOrExternalLinkFragment)
    }

    func test3() {
        let data = DataDict(
            data: [
                "__typename": "AppPresentation_InternalOrExternalLink",
                "text": "AppAccountSupport",
            ],
            fulfilledFragments: [
                ObjectIdentifier(ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.self),
                ObjectIdentifier(ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.AsAppPresentation_InternalOrExternalLink.self),
            ]
        )

        let link = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent.Link.AsAppPresentation_InternalOrExternalLink(
            _dataDict: data
        ).asRootEntityType

        let finalButton = ButtonsRowFragment.Button.AsAppPresentation_PrimaryButtonComponent(
            icon: "time",
            link: link
        ).asRootEntityType

        XCTAssertNotNil(finalButton.asAppPresentation_PrimaryButtonComponent?.link?.asAppPresentation_InternalOrExternalLink?.fragments.internalOrExternalLinkFragment)
    }
```

I've emailed you the full generated code for this type. Let me know if you find anything obvious.

**Comment by calvincestari** [comment]
@bsrz - I've created https://github.com/apollographql/apollo-ios/issues/3486 and https://github.com/apollographql/apollo-ios/issues/3487 to track the issues we discovered while looking through the code you sent.

We can track progress in those issues and I'll reach out to you in email for a workaround until the fixes are in place.
