### ISSUE TITLE
apollo-ios-pagination: `data` arg for callbacks is incorrectly documented with v0.3.0 (RocketReserver fails to build)

### ISSUE THREAD

**Issue by damian0815** [apollographql/apollo-ios#3484]
### Summary

On upgrading the demo RocketReserver app's `apollo-ios-pagination` version to 0.3.0, build fails because the type of the `data` argument has changed in undocumented ways:
```
/Users/<username>/Apollo-PaginationSample-SwiftUI/RocketReserver/LaunchListViewModel.swift:33:26 Cannot convert value of type '(LaunchListQuery.Data) -> CursorBasedPagination.Forward' to expected argument type '(PageExtractionData<LaunchListQuery, LaunchListQuery, PaginationOutput<LaunchListQuery, LaunchListQuery>?>) -> CursorBasedPagination.Forward'

/Users/<username>/Apollo-PaginationSample-SwiftUI/RocketReserver/LaunchListViewModel.swift:40:16 Value of type 'PaginationOutput<LaunchListQuery, LaunchListQuery>' has no member 'launches'
```

### Version

1.9.1 (apollo-ios-pagination 0.3.0, Xcode 15.4)

### Steps to reproduce the behavior

1. Download and open https://github.com/Iron-Ham/PaginationSample-SwiftUI in Xcode
2. In the left panel (Cmd-1), locate the ApolloPagination package dependency, note version 0.1.0. Now build → success.
3. Right click on the package dependency and select `Update Package`. Note that version is now 0.3.0. 
4. Build → failure with above error message

### Logs

```shell
/Users/<username>/Apollo-PaginationSample-SwiftUI/RocketReserver/LaunchListViewModel.swift:33:26 Cannot convert value of type '(LaunchListQuery.Data) -> CursorBasedPagination.Forward' to expected argument type '(PageExtractionData<LaunchListQuery, LaunchListQuery, PaginationOutput<LaunchListQuery, LaunchListQuery>?>) -> CursorBasedPagination.Forward'

/Users/<username>/Apollo-PaginationSample-SwiftUI/RocketReserver/LaunchListViewModel.swift:40:16 Value of type 'PaginationOutput<LaunchListQuery, LaunchListQuery>' has no member 'launches'
```

**Comment by calvincestari** [comment]
Hi @damian0815 - I suggest you [raise this issue directly in the sample project repo](https://github.com/Iron-Ham/PaginationSample-SwiftUI/issues) since it's not owned by Apollo. I'm sure @Iron-Ham is also open to accepting a PR with the relevant update.
