### ISSUE TITLE
Feature Request: Track and check timestamps on .graphql files to avoid slow builds

### ISSUE THREAD

**Issue by chrislconover** [apollographql/apollo-ios#351]
What currently happens:

Currently GraphQL seems to scan and generate code for all .graphql files that it builds.  This triggers an unnecesary complete rebuild of the project even when no model changes have been made. This becomes really long as the project progresses.  

Proposed Solution:

Please check and store timestamps or hashes on .graphql files to avoid regenerating code that hasn't changed, and to then avoid subsequent top to bottom rebuilds when it is not necessary.

**Comment by migonin** [comment]
I've faced same problem.

I have an idea to move Apollo to submodule and compile it manually only when I change it.

**Comment by designatednerd** [comment]
Yes this is absolutely something we need to do - this is related to #579, among others. Definitely planning on improving the "Wait do we need to regenerate things?" logic. 

Don't have an ETA but particularly around SwiftUI this seems like it'd be very helpful.

**Comment by guilhermekrz** [comment]
Any update on this? A considerable part of my build time is being spent on this code generation step. For now, I think I will resort to manually invoking it when necessary

**Comment by designatednerd** [comment]
There are [a few workarounds](https://github.com/apollographql/apollo-ios/issues/147) available on [different issues](https://github.com/apollographql/apollo-ios/issues/143) that are [related to this problem](https://github.com/apollographql/apollo-ios/issues/636). 

Right now dealing with Xcode 11 stuff is my priority since it just hit GM, but I'm going to try to get on this early as part of the [swift codegen project](https://github.com/apollographql/apollo-ios/projects/2).

**Comment by designatednerd** [comment]
[Good workaround to this from an issue on the tooling repo](https://github.com/apollographql/apollo-tooling/issues/1573#issuecomment-539754801)

**Comment by designatednerd** [comment]
I've added documentation of the workaround to the [Advanced Codegen Tips And Tricks](https://www.apollographql.com/docs/ios/installation/#advanced-codegen-tips-and-tricks) section of our documentation. If you're still having issues after setting that up, please file a new issue. Thank you!

(Note that I'm still planning to [add XCFileList generation](https://github.com/apollographql/apollo-ios/issues/636) as part of the Swift Codgen project, but that workaround should get you through until that's up and running)
