### ISSUE TITLE
Installation Apollo iOS error "Command /bin/sh failed with exit code 2"

### ISSUE THREAD

**Issue by KaiZhone** [apollographql/apollo-ios#352]
Hi, 
I am new to the apollographql ios, i have a working project in xcode, so i'm trying to integrate apollo-ios. First i read up on your installation guide :https://www.apollographql.com/docs/ios/installation.html
so i followed the step right up to building the xcode to generate the API.swift but the build fails. I'm using company server's graphql to download the schema but other than that, i followed the installation guide to the letter, i used cocoa pods to install apollo and my apollo version is apollo/1.7.0 darwin-x64 node-v8.11.4.

I think the error line is :

"++ exec /Users/kai/Desktop/GetSuper/node_modules/.bin/apollo codegen:generate --queries= --schema=schema.json API.swift
 ›   Warning: apollo update available from 1.2.0 to 1.7.0
 ›   Error: Flag --queries expects a value
Command /bin/sh failed with exit code 2"

I've also noticed this echo :

"'The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.2.0 darwin-x64 node-v8.11.4 seems to be installed. Installing...'
The version of Apollo.framework in your project requires Apollo CLI 1.2.0,   but apollo/1.2.0 darwin-x64 node-v8.11.4 seems to be installed. Installing...
++ install_apollo_cli
++ set -e
++ npm install --prefix /Users/kai/Desktop/GetSuper apollo@1.2.0
npm WARN saveError ENOENT: no such file or directory, open '/Users/kai/Desktop/GetSuper/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/kai/Desktop/GetSuper/package.json'
npm WARN GetSuper No description
npm WARN GetSuper No repository field.
npm WARN GetSuper No README data
npm WARN GetSuper No license field."

Is it reinstalling the apollo framework? Is that normal?
I hope you can help a newbie out.

P.S i tried to download the schema in the linked of the installation page and it gives me error "Saving schema to schema.json
   → Expected undefined to be a GraphQL schema.", and i'm not really sure why is it using localhost as endpoint nor the linked page explanation so i can't really try to build a new xcode project with another schema to test why is it my project not working.
Also i tried creating new xcode project and download my company's graphql schema and it still gives me the same error. Is it the schema.json the back-end returning me is not valid? Also i downloaded GraphiQL and used my company's graphql address and it is working. I hope these additional information will help. My xcode version is Version 9.4.1 (9F2000)

**Comment by jorgelub12** [comment]
I had the same issue today. I just fixed by adding a .graphql file to my project.

**Comment by KaiZhone** [comment]
Does it need to have anything? Or just a blank . graphql file will do?

**Comment by ashiemke** [comment]
It just needs a filename, doesn't need to contain anything.

**Comment by gidgol** [comment]
hm for me adding the file didn't fix the problem.

**Comment by Premal-Khetani** [comment]
I had the same issue. Any solution?

**Comment by KaiZhone** [comment]
For those people who still have problem with this issue, the fix for me was adding a .graphql file to my project, but it must not be empty, it just have to have a query/mutation call, any call will do, to let the script run through it once and create an API.swift.
