### ISSUE TITLE
Run script, Build fail Error

### ISSUE THREAD

**Issue by mickaelhero** [apollographql/apollo-ios#356]
I installed the pod apollo according to this manual, then at the stage where you have to create a run-time, the build does not work, it returns this error I do not understand why ..

```
    Can't find Apollo CLI. Installing...
npm ERR! Error while executing:
npm ERR! /Applications/Xcode.app/Contents/Developer/usr/bin/git ls-remote -h -t ssh://git@github.com/Project/fitto-ios.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mickaelbelhassen/.npm/_logs/2018-08-21T13_43_18_743Z-debug.log
Command /bin/sh failed with exit code 1
And I do not understand why he talks about git .. Also, the repository `ssh://git@github.com/Project/fitto-ios.git` is my remote repository, it has nothing to do with Apollo.

Here is my run script is the same as the official documentation:

```
    APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --queries="$(find . -name '*.graphql')" --schema=schema.json API.swift
```

**Comment by ashiemke** [comment]
Install the Apollo CLI yourself via `npm install -g apollo`. See https://github.com/apollographql/apollo-cli

Script needs to be fixed.

**Comment by psi-gh** [comment]
Same.

**Comment by stevenyix** [comment]
same.

**Comment by MangaSans** [comment]
So far, I've installed apollo's current version, 1.8.3, in and out of the source folder, and still getting the same error (128).

**Comment by designatednerd** [comment]
Hello, please try the new [docs for setting up the build step](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) that went out with 0.11.0. I'm going to close this issue out, but please feel free to open a new issue if you continue to run into problems. Thank you!
