### ISSUE TITLE
JSON Scalar throws JSONDecondingError.couldNotConvert

### ISSUE THREAD

**Issue by idris** [apollographql/apollo-ios#36]
We have a custom scalar type called JSON, which is used when we want to send unstructured data.
When trying to access that field using Apollo (even just trying to print it), we get the following error:
```
Apollo.JSONDecodingError.couldNotConvert({
    amountChanged = "-1467";
}, Swift.String)))
```

I'm not sure why it would have a problem converting to a String.  Also, how can we get the Dictionary value rather than a String?

This may be somewhat similar to #23.  I tried the proposed solution there (just aliasing `JSON` to `[String : Any?]`) but it gave a bunch of compile errors.

**Comment by martijnwalraven** [comment]
Unfortunately, we don't have real support for custom scalars yet. But I think we should be able to get something working using the `--passthrough-custom-scalars` workaround.

I haven't tested it, but something like this might be a good starting point:

typealias JSON = [String : Any?]

```swift
extension Dictionary: JSONDecodable {
  public init(jsonValue value: JSONValue) throws {
    guard let dictionary = value as? Dictionary else {
      throw JSONDecodingError.couldNotConvert(value: value, to: Dictionary.self)
    }
    
    self = dictionary
  }
}
```

**Comment by ankushkushwaha** [comment]
Any update on this? I have a field which is the type of scalar JSON.  Apollo throws the error 

`Optional(Apollo.GraphQLResultError(path:` ["stage", "0", "parent", "0", "venue"], underlying: Apollo.JSONDecodingError.couldNotConvert(value: {
    city = Monza;
    coordinates = "45.615899,9.279499";
    country = Italia;
    "country_code" = ITA;
    "curves_left" = 4;
    "curves_right" = 7;
    debut = 1950;
    id = "sr:venue:1024";
    laps = 53;
    length = 5793;
    name = "Autodromo Nazionale Monza";
    "url_official" = "http://www.monzanet.it/";
}, to: Swift.String)))`

**Comment by VigneshJeyarajG** [comment]
I got same Error. But i know the reason of error. Our Schema.json and mutation or query generate the API.swift. if Schema.json have a JSON response is treated as String. so Api.swift create [String] type. please check your API.swift. so if your response is [JSON] type. But your API.swift file automatically generate the [String]. so during fetching the data from endpoint response is not converted string. So this error will be Occoured.

Solution is when create a Backend using MUTATION RESPONSE instead of [JSON] type Response.

**Comment by VigneshJeyarajG** [comment]
This is sample response for [JSON]. 
https://i.stack.imgur.com/zxXiz.png 
My sample response is CurrentMissionChallenge is [JSON] type

**Comment by rickycpadilla** [comment]
@VigneshJeyarajG  I was able to solve this in a couple steps:
1) Add `--passthroughCustomScalars` to the build phase like below (see last line):
```sh
APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --queries="$(find . -name '*.graphql')" --passthroughCustomScalars --schema=schema.json API.swift
```
2) Add the `typealias` like @martijnwalraven mentioned a while back, like:
```swift
public typealias CurrentMissionChallenge = [String : Any?]

extension Dictionary: JSONDecodable {
  /// Custom `init` extension so Apollo can decode custom scalar type `CurrentMissionChallenge `
  public init(jsonValue value: JSONValue) throws {
    guard let dictionary = value as? Dictionary else {
      throw JSONDecodingError.couldNotConvert(value: value, to: Dictionary.self)
    }
    self = dictionary
  }
}
```

**Comment by designatednerd** [comment]
Closing this out with @rickycpadilla's [solution](https://github.com/apollographql/apollo-ios/issues/36#issuecomment-452515484) as the present recommended one.

**Comment by aroraenterprise** [comment]
Hey In Swift 5...there is no JSONDecodable/JSONDecodingError. Is there anything you guys are using for this fix.

**Comment by designatednerd** [comment]
@aroraenterprise This is a custom error, not anything thrown by the system. Can you open a new issue with details of the problem you're running into, please?

**Comment by abhilash-linkites** [comment]
Cannot find 'JSON' in scope

**Comment by PareshPatel721** [comment]
I'm using Apollo 1.9.3
So there are no run script needed to be set in build phase
I'm not able to set passThroughCustomScalars in run script as it is not needed while using local package.

Can anyone please help me to solve 
ApolloAPI.JSONDecodingError.couldNotConvert(value: AnyHashable
to: Swift.String)


public typealias JSON = String
