### ISSUE TITLE
swift low alloc

### ISSUE THREAD

**Issue by ytroyan** [apollographql/apollo-ios#364]
I found this issue for all apolo request in swift. 

<img width="1021" alt="screen shot 2018-09-10 at 3 50 54 pm" src="https://user-images.githubusercontent.com/8403604/45298508-60ecc000-b511-11e8-9263-dede05ad6515.png">

**Comment by designatednerd** [comment]
Yeah we've definitely got some memory leak issues - I'm going to close this one as a dupe and track through #230. Thanks very much for including this detail though!
