### ISSUE TITLE
Missing files when installing through cocoapods

### ISSUE THREAD

**Issue by havebeenfitz** [apollographql/apollo-ios#373]
- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [x] good first issue

Just installed apollo to my project according to all guides through Cocoapods (0.9.3). Installed apollo CLI as well (v. 1.9.2) and went through all the steps described in the docs. 

Then I created a .graphql file with subscription type and the API file is generating well, but I get the error `subscriptions are not supported over HTTP, use websockets instead`

So I guess I need to configure the client accordingly, but it seems I'm missing something, there are no such files in the Pod as ApolloWebSocket. What am I doing wrong? Is this a pod related issue? Should I add the ApolloWebSocket manually?

**Comment by SirensOfTitan** [comment]
You need to add `Apollo/WebSocket` to your Podfile, it's an optional sub-spec.

**Comment by havebeenfitz** [comment]
Ok, that makes the question really dumb :) Thanks and sorry for inconvenience
