### ISSUE TITLE
Latest version of apollo-ios does not support Apollo-Cli 1.9.x

### ISSUE THREAD

**Issue by SirensOfTitan** [apollographql/apollo-ios#374]
```
The version of Apollo.framework in your project requires Apollo CLI 1.8.x, but apollo/1.9.2 darwin-x64 node-v8.11.2 seems to be installed.
```

Repro steps:
1. remove local node_modules in iOS directory, if build script installed them.  
2. npm install -g apollo
3. Build iOS app, see issue as reported above.

**Comment by gorbat-o** [comment]
hey,

'npm install -g apollo' solved the warning for me
Also, in the last version 0.9.3, I can't compile anymore the generated files
I had to use the previous version 0.9.2

**Comment by crabman448** [comment]
0.9.3 also doesn't work for me 
![screen shot 2018-09-27 at 18 13 59](https://user-images.githubusercontent.com/7022709/46159679-2dd05d80-c281-11e8-8bbc-ddd2c9149169.png)

**Comment by rubenvde** [comment]
0.9.3 didn't work for me either

**Comment by psi-gh** [comment]
I locally installed apollo 1.8

    npm install --prefix <path_to_source_folder> apollo@1.8

it worked with apollo-ios 0.9.3

**Comment by Dfmarulanda** [comment]
@psi-ghI installed the apollo@1.8 version, but when I try to compile the project I have the following error:
` Apollo update available from 1.8.3 to 1.9.2`

**Comment by crabman448** [comment]
After updating to version 0.9.4 I still have an issue that I can't compile ApolloAPI.swift file

**Comment by SirensOfTitan** [comment]
After the most recent release this works now, closing out.

**Comment by antonbremer** [comment]
@crabman448  me too, 0.9.4 gives me errors:

not found: apollo
Command PhaseScriptExecution failed with a nonzero exit code

Did you manage to solve this?

**Comment by crabman448** [comment]
@antonbremer issue for me was that new CLI generates API.swift in a different way I think. So I was needed to adjust some my GraphQL operations.

**Comment by rad182** [comment]
same 0.9.4 doesn't work for me having some errors
My temporary solution is to downgrade to 0.9.3 and `npm install -g apollo@1.8.3`

**Comment by antonbremer** [comment]
> @antonbremer issue for me was that new CLI generates API.swift in a different way I think. So I was needed to adjust some my GraphQL operations.

Thank you for getting back to me. For myself it doesn't even get to the stage of generating the API.swift unfortunately. I am getting a script error "apollo not found". Version 0.9.2 works fine though, this happens as soon as I upgrade to 0.9.4. Will use 0.9.2 for now, although I'd love to upgrade but I'll wait, hopefully there'll be a more stable version next.

**Comment by allfou** [comment]
> same 0.9.4 doesn't work for me having some errors
> My temporary solution is to downgrade to 0.9.3 and `npm install -g apollo@1.8.3`

Yep, this is the only workaround that worked for me. Downgrade to 0.9.3 in podfile
`pod 'Apollo', '0.9.3'`

Remove module folder from my project root
`rm -rf node_modules`

Manually installed 1.8.3
`npm install -g apollo@1.8.3`

**Comment by tarek903** [comment]
@allfou i've been stuck with building the API.swift for two days , thanks a lot
