### ISSUE TITLE
Add X-APOLLO-OPERATION-NAME and X-APOLLO-OPERATION-ID like Android has

### ISSUE THREAD

**Issue by Ewg777** [apollographql/apollo-ios#375]
- [x] feature

It'd be great to Add X-APOLLO-OPERATION-NAME and X-APOLLO-OPERATION-ID like Android has.

https://github.com/apollographql/apollo-android/blob/6afd0dff6ea8b22d29c304fc166e0443035e5d7a/apollo-runtime/src/main/java/com/apollographql/apollo/internal/interceptor/ApolloServerInterceptor.java#L121

**Comment by designatednerd** [comment]
I think we've got a couple things looking into this - we'll have to make sure those fields were generated but this seems reasonable to add.

**Comment by designatednerd** [comment]
Shipped with 0.13.0!
