### ISSUE TITLE
Add support for Automatic Persisted Queries

### ISSUE THREAD

**Issue by ashiemke** [apollographql/apollo-ios#376]
Add support for APQ: https://www.apollographql.com/docs/guides/performance.html#automatic-persisted-queries

Automate hashing of the query (sha256, see above link), and GET request construction.
Retry with current logic if the query is not found in the cache (above GET returns an error with message == PersistedQueryNotFound)
Add a configuration option to the client that allows this to be enabled (default off).

Can anyone point at a reference implementation so I don't have to reverse-engineer from the above doc?

**Comment by ashiemke** [comment]
Started work on this, but not sure how to test since it's in a single layer (transport), and the star wars server doesn't seem to support it.

Anyone know of a simple server that I can get running to test against?

**Comment by MycujooMats** [comment]
Support for APQ would be great! It would really make things more scale-able and efficient.

**Comment by kcatigbe** [comment]
Is there any movement on adding this as a Feature to Apollo? Would like to see this as we want to optimize our calls as much as possible.

**Comment by Codebear98** [comment]
Just made a PR for this #608 
which support GET for CDN too, fallback to POST if APQs not cache for avoiding 2k length limitation of query string.

**Comment by designatednerd** [comment]
This has shipped with `0.17.0`! If you run into any problems with it, please file a new issue. Thank you!
