### ISSUE TITLE
Local node_modules

### ISSUE THREAD

**Issue by crabman448** [apollographql/apollo-ios#377]
We have 2 subprojects in our workspace. These projects have different schemas, that we can't stitch. Both projects have build phase to create `API.swift` from `schema.json`. And because of the new approach with storing `nod_modules` inside local folder, we have 2 same folders (one for every project). While this is not a big issue it is a bit frustrating I think. Maybe there is a way to specify `workspace` folder as a folder for `node_modules`?
Thanks!

**Comment by designatednerd** [comment]
Yeah this seems like a reasonable request - I'll see what I can do.

**Comment by designatednerd** [comment]
This should now be greatly improved with `0.16.0`, which basically removes any need to use NPM. 

Please check out our [updated installation instructions for setting up a build script](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) for full details. Thank you!

**Comment by crabman448** [comment]
@designatednerd  Thank you for working hard on this library ❤️
