### ISSUE TITLE
Making Models Classes Instead of Structs

### ISSUE THREAD

**Issue by GitMAM** [apollographql/apollo-ios#378]
Is there a way of generating the data models as Classes instead of Structs?

**Comment by attheodo** [comment]
Why do you need classes vs structs?

**Comment by designatednerd** [comment]
@GitMAM Not at the moment, as far as I can tell - I'm still familiarizing myself with the TypeScript codegen stuff but it doesn't seem like it. 

Can you elaborate on why you'd want classes instead of structs?

**Comment by GitMAM** [comment]
@designatednerd  I think it's safe to say that i don't need this anymore. I needed it before because I was using the diffable protocol on the model which only works with classes. Since Apple has introduced diffing in CollectionView in iOS 13, it won't be needed anymore in my use case.

**Comment by designatednerd** [comment]
Got it - I'll close this out. Thank you, and sorry it took so long to get back to you!
