### ISSUE TITLE
Change Promise public class to internal clarification.

### ISSUE THREAD

**Issue by cadizjavier** [apollographql/apollo-ios#382]
Apollo iOS has a custom implementation of Promises that could potentially conflict with existing one in the host project of this dependency and is kinda confusing specifying every time which implementation of `Promise` to use.
I have done a quick look at the source code and it seems that the `Promise` class could be implemented as internal. 
- Is this issue happening to someone else? What is your workaround in your host project?
- Is it desirable to implement this as internal and refactor de `firstly` and `whenAll` public functions into something else? I can definitely give it a try as a Pull Request but need some clarifications about the status of this "issue".

**Comment by js** [comment]
To solve the naming clash you need to specify the module name of the type you want to use, eg `MyApp.Promise` or `ThePromiseLib.Promise`, or `Apollo.Promise` if you want to use Apollo's.

The Promise is exposed in some of the other public API, such as the `DataLoader` so another approach would be needed there if this where to be hidden as you say.

**Comment by cadizjavier** [comment]
Yes, this is exactly what are we doing in our project, specifying the module name which is kinda inconveniente and confusing. We asked ourselves, why we have now an implementation of Promise exposed to us now ?
I see now that you mention that is used for example in `DataLoader` so yes, agree, a refactor to hide this as an implementation detail would be needed.

**Comment by cadizjavier** [comment]
I see now that a `Promise` is returned if we use for example `apolloClient.clearCache()` so `Promise` can't be internal in this case.
Would it make sense to return for the public API only callbacks and keep `Promise` as an internal implementation only for the use of the library ?

**Comment by paulmelnikow** [comment]
What about simply using PromiseKit? It's well tested and as a community we benefit from standardization.

**Comment by designatednerd** [comment]
Woof, yeah that almost certainly should never have been made public- it was built as an internal dependency and not for external use. I may look at doing this as a breaking change, but it's probably going to be a bit lower on my priority list.

**Comment by designatednerd** [comment]
Shipped with `0.16.0`!
