### ISSUE TITLE
graphql apollo fails to run script

### ISSUE THREAD

**Issue by mkamal13** [apollographql/apollo-ios#383]
i followed the tutorial provided by apollo and each time i build to run the script that generate the api file ,i get the following massage:

iphonesimulator/Apollo/Apollo.framework/check-and-run-apollo-cli.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
this is the project:https://github.com/mkamal13/graphqlapollo can any body help?

**Comment by mkamal13** [comment]
no

**Comment by azablotskiy** [comment]
pod update should do the trick ;)

**Comment by moger777** [comment]
I get same issue with 0.9.4 but only when archiving.

**Comment by stNamco** [comment]
Did you set an output file path? if you set that, generating script is executed before compile source.

https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/XcodeBuildSystem/200-Build_Phases/bs_build_phases.html#//apple_ref/doc/uid/TP40002690-BBCCFEDJ

**Comment by designatednerd** [comment]
Please see the updated codegen script setup instructions [here](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) - these have been updated in 0.11.0 and 0.11.1. Gonna close this one out!
