### ISSUE TITLE
Cannot query field "xxx" on type "Query"

### ISSUE THREAD

**Issue by AlYehorov** [apollographql/apollo-ios#384]
After upgrading to version 0.9.4 (was 0.8.0), I can’t add new queries and change another one, always see this error "Cannot query field "xxx" on type "Query" or like that -->> graphql:262: Unknown argument "period" on field "GetReports" of type "Query".

**Comment by budjoskop** [comment]
Hi, have you success to resolve this issue, I'm facing same problem here:
1. Pod are installed, that is okay.
2. Scheme is generated, that is okay.
3. After first build, empty API is build, that is okay. 
4. I've added empty .graphql in Xcode
5. Filled up with the query:
<img width="1265" alt="screen shot 2019-02-23 at 17 26 11" src="https://user-images.githubusercontent.com/31095126/53289030-ce736c80-3790-11e9-99ff-c52ee33bd131.png">
6. Check that query, does it works, yes it works, please check: 
<img width="1469" alt="screen shot 2019-02-23 at 17 25 55" src="https://user-images.githubusercontent.com/31095126/53289039-ee0a9500-3790-11e9-8da6-cb463ad0d7d6.png">
7. Tried to build project for second time, and I got this error: 
Cannot query field "nodes" on type "Query".
Please check:
<img width="1228" alt="screen shot 2019-02-23 at 17 32 54" src="https://user-images.githubusercontent.com/31095126/53289056-17c3bc00-3791-11e9-9058-3ac7c9d7b256.png">

Seems, validate.js and generate.js are having a pb, but I'm not sure, help please :)

**Comment by AshleyDeng** [comment]
I had the same problem but later I found out that I didn't update the `schema.json` after our backend team updates it.

Some suggestions to resolve it are:
- Make sure download the latest `schema.json` from the endpoint you are supposed to communicate with
- Make sure Build Phases include the a step which generates the GraphQL `API.swift` from `xx.graphql`
- Make sure API.swift has declarations of your `query` or `mutation` defined in your `xx.graphql`
- Let the auto complete do the work: the generated `API.swift` will append `Query` or `Mutation` to the class name

**Comment by designatednerd** [comment]
hey @AlYehorov Are you still facing this issue, particularly after applying @AshleyDeng's suggestions?

**Comment by designatednerd** [comment]
Since we haven't heard back on this issue in a couple weeks, I'm going to close this one out. Please feel free to open a new issue if you're still having problems!
