### ISSUE TITLE
Generic parameter 'Mutation' could not be inferred

### ISSUE THREAD

**Issue by JulienLevallois** [apollographql/apollo-ios#388]
Hi ! I got this error with mutation & query too. Do you know why ?
<img width="1215" alt="capture d ecran 2018-10-17 a 13 15 26" src="https://user-images.githubusercontent.com/5727223/47104183-d6ce0080-d20e-11e8-9152-53d397f09fce.png">
<img width="1239" alt="capture d ecran 2018-10-17 a 13 13 15" src="https://user-images.githubusercontent.com/5727223/47104184-d6ce0080-d20e-11e8-9db9-058f4766e7df.png">

Thanks

**Comment by rusty-jules** [comment]
Same issue here. Swift 4.2 Xcode 10

**Comment by danieltran** [comment]
Also getting the same issue trying to perform a mutation on Swift 4.2 Xcode 10.1 and Apollo 0.9.4. Any had any luck resolving?

**Comment by mayuritalaviya** [comment]
Same issue in 'mutation' and 'fetch' with xcode 10. Any one got solution ??

**Comment by kadishmal** [comment]
The following worked for me:

```
let mutationInput = CreateUserSettingsInput(id: username, pauseSync: false, lastSyncDate: Int(NSDate().timeIntervalSince1970))
let mutation = CreateUserSettingsMutation(input: mutationInput)

self.appSyncClient?.perform(mutation: mutation) { (result, error) in
    ...
}
```

**Comment by jxltom** [comment]
It is because the wrong field in result is accessed.

```result.data.yourfield``` is OK but ```result.data.somewrongfield``` will raise this error.

**Comment by juanpdelat** [comment]
@jxltom is right, using the proper field fixed it for me. I believe the error message should be improved.

**Comment by designatednerd** [comment]
Unfortunately the error message is coming from Swift rather than from us. I know Swift has been working to make its error messages from generics a bit less opaque, but there's not a lot we can do about it. 

I'm going to close this one out, but please feel free to open a new issue if you run into any further problems!

**Comment by michaelryannewell** [comment]
There is no result, error, just a response that can be mapped to result or error. The code below highlights the new syntax:

```

let mutationInput = CreateUserSettingsInput(id: username, pauseSync: false, lastSyncDate: Int(NSDate().timeIntervalSince1970))
let mutation = CreateUserSettingsMutation(input: mutationInput)

 self.appSyncClient?.perform(mutation: mutation) { (result) in
         
            do {

                // success value
                
                let success = try result.get()
                print("success: \(success)")
                
                // data errors
                
                let dataErrors = success.errors
                print("errors: \(errors)")
                
                // data
                
                let data = success.data
                print("data: \(data)")
                
                // your field
                
                success.data?.yourField

                // or
                
                data?.yourField


            } catch {
                
                // mutation error
                
                let error = result.mapError({ (error) -> Error in
                    
                    return error
                    
                })
                
                print("error: \(error)")

            }
            
}
```

**Comment by designatednerd** [comment]
Yep - this is also a totally valid way to access the `Result`. Personally I prefer the `switch` way of accessing it as I find it a bit easier to read:

```swift
client.perform(mutation: mutation) { result in
  switch result {
  case .success(let graphQLResult):
    // Deal with GraphQLResult and its data and/or errors properties here
  case .failure(let error): 
    // deal with network errors here 
  }
}
```

**Comment by michaelryannewell** [comment]
> Yep - this is also a totally valid way to access the `Result`. Personally I prefer the `switch` way of accessing it as I find it a bit easier to read:
> 
> ```swift
> client.perform(mutation: mutation) { result in
>   switch result {
>   case .success(let graphQLResult):
>     // Deal with GraphQLResult and its data and/or errors properties here
>   case .failure(let error): 
>     // deal with network errors here 
>   }
> }
> ```

Thank you @designatednerd  I learned something new today!

You can view the result enum for Swift in the docs as Swift > Result 

/// A value that represents either a success or a failure, including an
/// associated value in each case.
public enum Result<Success, Failure> where Failure : Error {

    /// A success, storing a `Success` value.
    case success(Success)

    /// A failure, storing a `Failure` value.
    case failure(Failure)
