### ISSUE TITLE
After clearing SQLite cache, SQLite causes a crash from Statement.swift

### ISSUE THREAD

**Issue by hankhong1205** [apollographql/apollo-ios#397]
Currently, I am having some crashes after clearing SQLite cache and querying again.

```
Thread 15: Fatal error: 'try!' expression unexpectedly raised an error: database is locked (code: 5)
```

And here's the code snippet of how I am configuring ApolloClient and ApolloStore with SQLiteNormalizedCache.

```
let cacheURL: URL = URL.ds.temporarySQLiteFileURL()
let cache = try? SQLiteNormalizedCache(fileURL: cacheURL)
let store = ApolloStore(cache: cache ?? InMemoryNormalizedCache())
client = ApolloClient(networkTransport: MoyaNetworkTransport(), store: store)
```

Multiple queries access to the SQLite cache simultaneously and if I run these queries one by one, it does not crash.

Is there any solution to run multiple queries(read/write) concurrently in Apollo SQLite cache?

**Comment by MagdyZamel** [comment]
are there any updates for this issue?

**Comment by RolandasRazma** [comment]
how are you clearing?

**Comment by designatednerd** [comment]
@hankhong1205 How are you clearing the sqlite cache? My thought is maybe there's some async operation that hasn't finished yet but I'm not super familiar with the sqlite lib to be sure.

**Comment by designatednerd** [comment]
@hankhong1205 You also may want to look at changes in #652 for cache clearing - please let us know if that helps at all!

**Comment by designatednerd** [comment]
Since I haven't heard back on this in a few weeks, I'm going to close it out. If you're still having problems, please open up a new issue. Thank you!
