### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by tspecht** [apollographql/apollo-ios#398]
Hey!

We currently integrated `apollo-ios` into our application. We also wanted to enable caching, unfortunately we had to find that there seems no real cache-expiration when the SQL cache-backend is set. On `apollo-android` for example, this is possible.

I would love some recommendations on the following:
* What is the recommended way to have TTL for cache-entries
* What's the recommended way to fully flush the cache (e.g. in case the user logged out)
* Is it possible to write custom cache-backends to implement these features myself if necessary?

**Comment by Nuke-** [comment]
Hi,

About TTL I'm also investigating this.
The ApolloClient has a clearCache function which should do what you want aka flush cache.

When you init the ApolloClient you can supply it with an ApolloStore which you in turn you can supply with a NormalizedCache.
So it should be possible to implement your own Cache for your use cases.
The default cache is a InMemoryNormalizedCache.

**Comment by designatednerd** [comment]
@tspecht The `ApolloClient.clearCache()` method is the recommended method, although bear in mind that if you're using the SQLite cache there have been a couple reports of issues around this. 

I'm going to close this one out with that as the recommendation, but if you run into other problems around this, please open a new issue. Thank you!
