### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code -Apollo iOS

### ISSUE THREAD

**Issue by Angelzzz** [apollographql/apollo-ios#406]
I am using Apollo GraphQL and my graphql file is 
```
mutation SigninUser($email: String!, $password: String!) {
    signin(email: $email, password: $password) {
        result {
            token
            firstName
            lastName
            profileImage
        }
    }
}
```
while build the Xcode project it shows the error  **Command PhaseScriptExecution failed with a nonzero exit code** and my API.swift file is also empty.
Anyone canyon please help me to findout the solution....

**Comment by tomas-paronai** [comment]
Does your graphql file has the same name as your viewcontroller?

**Comment by designatednerd** [comment]
Hey there - we've recently updated [our instructions for setting up the Codegen build phase](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step), which should address this issue. 

If after following those instructions you're still having problems, please open a new issue. Thank you!
