### ISSUE TITLE
Xcode 10- error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project.

### ISSUE THREAD

**Issue by zoufishanmehdi** [apollographql/apollo-ios#412]
When trying to build the project, I see this error `error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project.` I have tried adding the framework again under link binary with libraries and it's not working. I'm currently using Apollo 0.9.4. 

Build Phase:
APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1 -print -quit)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift

**Comment by arielelkin** [comment]
if you're integrating via Cocoapods, try replacing Apollo's build phase script with:

```shell
sh $PODS_ROOT/Apollo/scripts/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema 'path/to/your/schema.json' --output path/to/the/resulting/ApolloAPI.swift
```

Submitted a PR to update docs here: https://github.com/apollographql/apollo-ios/pull/420

**Comment by romainbiard** [comment]
still not working AFAIK

**Comment by jorgeb12** [comment]
Still not working. Any solutions?

**Comment by oabdelkarim** [comment]
Make sure there is no space in project path.

**Comment by designatednerd** [comment]
Hey all, we've recently updated the [build script phase setup instructions](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) and the scripts so that you should not have to worry about things like whether your path has a space or not. 

I'm going to close this issue out but if you have problems after following those instructions, please open a new issue. Thank you!

**Comment by PhillipFraThailand** [comment]
> ```shell
> path/to/the/resulting/ApolloAPI.swift
> ```

Hey Arieleelkin, I am currently having some issued with the script and I'm trying different stuff out. What do I need to put instead of this line? My script currently looks like this

> $PODS_ROOT/Users/phillipeismark/sandbox/WatchOS6Apollo/Pods/Apollo/scriptscheck-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema '/Users/phillipeismark/sandbox/WatchOS6Apollo/WatchOS6Apollo WatchKit Extension' --output path/to/the/resulting/ApolloAPI.swift

**Comment by romainbiard** [comment]
Apollo version 0.15 is working well with this script:

SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="API/GraphQL/schema.json" API/GraphQL/API.swift

**Comment by PhillipFraThailand** [comment]
> Apollo version 0.15 is working well with this script:
> 
> SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
> cd "${SRCROOT}/${TARGET_NAME}"
> "${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="API/GraphQL/schema.json" API/GraphQL/API.swift

Hey romainbiard thanks for your answer.
I currently have the script in my project and I get this error when I try to run the project.

> /Users/phillipeismark/Library/Developer/Xcode/DerivedData/WatchOS6Apollo-dqrnbgiakvuyxrembpnzikwjposb/Build/Intermediates.noindex/WatchOS6Apollo.build/Debug-watchsimulator/WatchOS6Apollo WatchKit Extension.build/Script-76B59D0F231E5044006FA134.sh: line 4: /Apollo/scripts/check-and-run-apollo-cli.sh: No such file or directory

Do I need to change anything in the script? I have tried to change the variables in the script to the directories paths and stuff but I get the same error.

**Comment by PhillipFraThailand** [comment]
I am starting to suspect that it might have something to do with it being a WatchOS6 project.

If any of you could please take a look at the picture in case anything is off?

![Screen Shot 2019-09-03 at 2 18 53 PM](https://user-images.githubusercontent.com/33216628/64172745-f76a6d80-ce55-11e9-8a29-c582fd4b1bf3.png)

**Comment by PhillipFraThailand** [comment]
I have made a new project that's a normal SwiftUI project for the phone and not the watch.

I am getting these errors:

> 
Showing All Messages
/Users/phillipeismark/sandbox/SwiftUIApollo/Pods/Apollo/scripts/check-and-run-apollo-cli.sh: line 61: npx: command not found

Apollo iOS requires version 2.17.x of the Apollo CLI to be installed either globally or in a local node_modules directory.

Installing apollo@2.17 in your project directory to avoid version conflicts...

/Users/phillipeismark/sandbox/SwiftUIApollo/Pods/Apollo/scripts/check-and-run-apollo-cli.sh: line 76: npm: command not found

Command PhaseScriptExecution failed with a nonzero exit code

And this is the script I am running, I have made no changes to it I just copied directly from the [guide](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step)

**Comment by romainbiard** [comment]
1)Install Homebrew
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

2)Install node and npm
`brew install node npm`

**Comment by PhillipFraThailand** [comment]
> 1)Install Homebrew
> `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
> 
> 2)Install node and npm
> `brew install node npm`

Hey romainbiard, I have installed that and I am getting this warning when I install apollo with npm:

npm WARN ts-node@8.3.0 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself

do you know how to do this?

**Comment by designatednerd** [comment]
@PhillipFraThailand I've answered this question on [your other issue](https://github.com/apollographql/apollo-ios/issues/749) - let's try to keep discussion on that issue for clarity please.
