### ISSUE TITLE
TypeError: Cannot read property 'getQueryType' of undefined

### ISSUE THREAD

**Issue by arielelkin** [apollographql/apollo-ios#414]
```
Using Apollo pod (0.9.4)
Xcode 10.1
iOS 12.1
```

Integrated as per https://www.apollographql.com/docs/ios/installation.html

```
:-1:  ›   Warning: apollo update available from 1.9.2 to 2.1.6
:-1: ++ npx --no-install apollo codegen:generate '--queries=./Apollo/GetProfile.graphql
:-1: ./Apollo/GetLoyaltyDetails.graphql
:-1: ./Apollo/GetEmail.graphql' --schema=schema.json API.swift
:-1:  ›   Warning: apollo update available from 1.9.2 to 2.1.6
:-1: [16:48:00] Loading Apollo config [started]
:-1: [16:48:00] Loading Apollo config [completed]
:-1: [16:48:00] Resolving GraphQL document sets and dependencies [started]
:-1: [16:48:00] Scanning for GraphQL queries (3 found) [title changed]
:-1: [16:48:00] Scanning for GraphQL queries (3 found) [completed]
:-1: [16:48:00] Generating query files [started]
:-1: [16:48:00] Generating query files with 'swift' target [title changed]
:-1: [16:48:00] Generating query files with 'swift' target [failed]
:-1: [16:48:00] → Cannot read property 'getQueryType' of undefined
:-1: TypeError: Cannot read property 'getQueryType' of undefined
:-1:     at TypeInfo.enter (~/project/ios/node_modules/graphql/utilities/TypeInfo.js:142:25)
:-1:     at Object.enter (~/project/ios/node_modules/graphql/language/visitor.js:363:16)
:-1:     at Object.visit (~/project/ios/node_modules/graphql/language/visitor.js:254:26)
:-1:     at getValidationErrors (~/project/ios/node_modules/apollo/lib/validation.js:21:15)
:-1:     at Object.validateQueryDocument (~/project/ios/node_modules/apollo/lib/validation.js:26:30)
:-1:     at Object.generate [as default] (~/project/ios/node_modules/apollo/lib/generate.js:19:18)
:-1:     at Task.task (~/project/ios/node_modules/apollo/lib/commands/codegen/generate.js:98:64)
:-1:     at Promise.resolve.then.then.skipped (~/project/ios/node_modules/listr/lib/task.js:167:30)
```

Also tried running passing `--passthroughCustomScalars`: 
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --queries="$(find . -name '*.graphql')" --passthroughCustomScalars --schema=schema.json API.swift

But I got the same issue. 

Please advise!

**Comment by cdtschange** [comment]
same error

**Comment by IainDelaney** [comment]
Exact same setup, same error.

**Comment by mlomeli** [comment]
Me three.

**Comment by lokae0** [comment]
To expand on @mlomeli's comment- I was also getting this error until I moved `schema.json` into the source file root directory (where the AppDelegate file is located).

**Comment by daehn** [comment]
@lokae0 this fixed it for me as well.

**Comment by ricsantos** [comment]
I have this same error with an empty project and similar settings (except Apollo 0.9.5).

Surely if `schema.json` was in the wrong location it should show an error saying so, instead of this stack trace?

**Comment by the-scott-davis** [comment]
Moving the schema file to the same directory as the AppDelegate.swift file resolved the error for me as well.

**Comment by michaelnisi** [comment]
Missing schema should exit with helpful error message instead of, for example:

```
+ apollo@1.9.2
…
[18:28:30] Loading Apollo config [started]
[18:28:30] Loading Apollo config [completed]
[18:28:30] Resolving GraphQL document sets and dependencies [started]
[18:28:30] Scanning for GraphQL queries (2 found) [title changed]
[18:28:30] Scanning for GraphQL queries (2 found) [completed]
[18:28:30] Generating query files [started]
[18:28:30] Generating query files with 'swift' target [title changed]
[18:28:30] Generating query files with 'swift' target [failed]
[18:28:30] → Cannot read property 'getType' of undefined
TypeError: Cannot read property 'getType' of undefined
…
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by krin-san** [comment]
I got the same error because I downloaded schema.json via GraphQL in-browser playground and it's structure and size was completely different to one you get when download it via `apollo schema:download` command.

**Comment by designatednerd** [comment]
@krin-san Which one worked and which one didn't?

**Comment by krin-san** [comment]
@designatednerd, the latter one, downloaded using `apollo schema:download` command

**Comment by michaelnisi** [comment]
Tooling should really report more details with its errors – these seem generic.

**Comment by designatednerd** [comment]
Yeah unfortunately I think that's a TypeScript error - I'll see if there's a way to get more details on these in the future though

**Comment by designatednerd** [comment]
Anyone on this thread: Has this improved since `0.13.0` swapped out the underlying CLI?

**Comment by designatednerd** [comment]
Hey all - since I haven't heard back from anyone on this, I'm going to close this one out. If you're still running into problems, please open a new issue. Thank you!
