### ISSUE TITLE
Update to Swift 4.2

### ISSUE THREAD

**Issue by AttilaTheFun** [apollographql/apollo-ios#425]
A user has already created a PR to update the library to Swift 4.2:
https://github.com/apollographql/apollo-ios/pull/408
Can you accept that PR?

**Comment by jtrainer** [comment]
Is there any update on this ticket or associated PR?

**Comment by AttilaTheFun** [comment]
@jtrainer @martijnwalraven @NeelSarwal Can we please merge one of these PRs? I just signed the Meteor contributor agreement and created my own PR. Swift 5 is almost out and this still hasn't been updated past Swift 4 which is pretty ridiculous.

https://github.com/apollographql/apollo-ios/pull/469

**Comment by NeelSarwal** [comment]
@AttilaTheFun Sorry, I'm actually not apart of the Apollo Team, just a fellow user who wants this to be bumped. Would really like to get this in.

**Comment by designatednerd** [comment]
We've now even been updated to Swift 5! Going to close this one out.
