### ISSUE TITLE
two different classes with the same information

### ISSUE THREAD

**Issue by Dfmarulanda** [apollographql/apollo-ios#429]
Hey
Do you know if its possible to associate two different classes with the same information? The autogenerated code created two instances of the same class from two final different classes. I don't want to create a implementation for each; but, as the generated code is FINAL, I cannot extend or typealias of that classes.

**Comment by paulmelnikow** [comment]
Can you use [a fragment](https://www.apollographql.com/docs/ios/fragments.html)?

**Comment by designatednerd** [comment]
@paulmelnikow, the correct solution here would be to use a Fragment.

If you've got any follow up questions, please feel free to stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) - I'm gonna close this question out. Thank you!
