### ISSUE TITLE
Definition conflict when generate API.swift and use of mutation

### ISSUE THREAD

**Issue by michelekorell** [apollographql/apollo-ios#430]
Actually I use a very large graphql schema definition for healthcare HL7 FHIR resources. When I try to add mutation inside my .graphql definitions, after build I found for a double declaration for the same variable.

For the following graphql schema :

```graphql
query GetSubjectTransfusions ($subject: String!) {
    Transfusions(subject: $subject) {
        resourceType
        entry {
            resource {
                ...ProcedureDetail
            }
        }
    }
}

mutation CreateTransfusion($proc: Procedure_Input!) {
    CreateOrUpdateTransfusion(resource: $proc) {
        ...ProcedureDetail
    }
}

fragment ProcedureDetail on Procedure {
    resourceType
    id
    status
    code {
        text
    }
}
```
I found a lot of these double declaration inside API.swift :
```swift
/// The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
  public var id: Swift.Optional<String?> {
    get {
      return graphQLMap["id"] as! Swift.Optional<String?>
    }
    set {
      graphQLMap.updateValue(newValue, forKey: "id")
    }
  }

  /// The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
  public var id: Swift.Optional<Element_Input?> {
    get {
      return graphQLMap["_id"] as! Swift.Optional<Element_Input?>
    }
    set {
      graphQLMap.updateValue(newValue, forKey: "_id")
    }
  }
```
I've tried to figure out why the generation of API add two times inside the declaration of the Procedure_Input resource :
```swift
public struct Procedure_Input: GraphQLMapConvertible 
```
My development environment is:
 - Xcode 10.1 (10B61)
 - target: iOS 12.1 
 - Apollo client: Cocoapods at version 0.9.4
 - npm: apollo/2.1.9 on node-v10.11.0

In the attached files you can find the schema.json reference file, the whole API.swift and local graphql schema: [GraphQL_schema.zip](https://github.com/apollographql/apollo-ios/files/2743933/GraphQL_schema.zip)

Thanks

**Comment by designatednerd** [comment]
@michelekorell Are you still seeing these issues with 0.11.1? Would love to know before I go spelunking.

**Comment by michelekorell** [comment]
Hello, actually we put in standby the project, tomorrow I have some time to check and I give you an answer. Thanks a lot to ask for some news 👍

**Comment by michelekorell** [comment]
Hello, after some test it seem to be ok with 0.11.1 I didn't found anymore duplicated values. But i had a lot of problems to generate code with proposed build step because actually i'm working with nvm
Finally i resolve my problems by switching on node 8 and running manually apollo codegen command.

Thanks for all!
