### ISSUE TITLE
CLI Parser doesn't handle unrecognized options well

### ISSUE THREAD

**Issue by mrackwitz** [apollographql/apollo-ios#432]
I mistyped the option `--passthroughCustomScalars` as `--passthrough-custom-scalars`. This yield a rather confusing error:
```
›   Error: Unexpected arguments: Generated/API.swift
```
 
Only after I have removed this argument, I could see what was going on:
```
$ git status
On branch feature/use-graphql-date
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    new file:   --passthrough-custom-scalars/Foo.graphql.swift
    new file:   --passthrough-custom-scalars/Types.graphql.swift
    new file:   --passthrough-custom-scalars/Bar.graphql.swift
```

So the unknown option was treated as argument.

**Comment by designatednerd** [comment]
Yeah unfortunately at the moment this is probably more of a problem with our [apollo-tooling](https://github.com/apollographql/apollo-tooling) repo than here, as this is handled in typescript - Can you please open an issue there and close this one out please?

**Comment by designatednerd** [comment]
@mrackwitz We've upgraded to a new version of the CLI with version 0.13.0 - is that still causing issues? If it is, I'd still recommend opening an issue on the Tooling repo, but it'd be helpful to know.

**Comment by designatednerd** [comment]
Since I haven't heard back in this issue for a couple weeks, I'm going to close it out. If you're still having issues, in this particular case I'd recommend opening an issue on `apollo-tooling`, though be aware of #682 where i'm taking suggestions for Swift codegen.
