### ISSUE TITLE
API.swift file is empty

### ISSUE THREAD

**Issue by vlad57** [apollographql/apollo-ios#438]
iOS: 12.1
Xcode: 10.1
Swift: 4.2

Hi guys, 

I have a problem with the implementation of Apollo. I tried 3 days with success, but when I tried with the new project I failed. I can generate de API.swift file when I'm building the first time but when I'm adding *.graphql files it doesn't generate the code in API.swift from *.graphql files. 

I attach the screenshots with my configuration. 

Thanks by advance,

<img width="1418" alt="capture d ecran 2019-01-21 a 00 35 37" src="https://user-images.githubusercontent.com/18573676/51446620-052f1080-1d15-11e9-8b80-43aa81e3ea52.png">
<img width="1416" alt="capture d ecran 2019-01-21 a 00 38 34" src="https://user-images.githubusercontent.com/18573676/51446622-052f1080-1d15-11e9-8cbf-ddb6de6c1a6f.png">
<img width="1416" alt="capture d ecran 2019-01-21 a 00 39 02" src="https://user-images.githubusercontent.com/18573676/51446623-052f1080-1d15-11e9-91c1-dca12fe583bc.png">

**Comment by paulmelnikow** [comment]
Probably it’s not finding your graphql files. Are they inside the folder for your target?

**Comment by vlad57** [comment]
That's right. I left them at the root of directory, I forgot to put them in the target directory... 

Thank you very much !
