### ISSUE TITLE
Installing via CocoaPods: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [apollographql/apollo-ios#441]
1. Create a new Objective-C macOS project using Xcode 10
2. Add Podfile
3. pod install
4. Open workspace
5. Build app

Result: linker command failed with exit code 1

```
ld: warning: Could not find auto-linked library 'swiftFoundation'
ld: warning: Could not find auto-linked library 'swiftDarwin'
ld: warning: Could not find auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find auto-linked library 'swiftIOKit'
ld: warning: Could not find auto-linked library 'swiftQuartzCore'
ld: warning: Could not find auto-linked library 'swiftCore'
ld: warning: Could not find auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find auto-linked library 'swiftObjectiveC'
ld: warning: Could not find auto-linked library 'swiftDispatch'
ld: warning: Could not find auto-linked library 'swiftCoreData'
ld: warning: Could not find auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find auto-linked library 'swiftXPC'
ld: warning: Could not find auto-linked library 'swiftMetal'
ld: warning: Could not find auto-linked library 'swiftAppKit'
ld: warning: Could not find auto-linked library 'swiftCoreImage'
Undefined symbols for architecture x86_64:
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by paulmelnikow** [comment]
Are you having this problem with other pods too, e.g. Alamofire or PromiseKit?

**Comment by jordanhbuiltbyhq** [comment]
I haven't tried other pods. Both of those are Swift 2 which isn't supported in Xcode 10, any others you'd like me to try?

**Comment by jordanhbuiltbyhq** [comment]
Hmm. I just have pod 'PromiseKit', Installing PromiseKit (6.7.1), but when I open the workspace I get
The target “PromiseKit” contains source code developed with Swift 2.x. This version of Xcode does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

**Comment by paulmelnikow** [comment]
It sounds like something is wrong with your Cocoapods installation.

**Comment by jordanhbuiltbyhq** [comment]
Hm. Are you able to perform the steps to reproduce and build without error?

**Comment by designatednerd** [comment]
@jordanhbuiltbyhq Hi! Sorry for the long radio silence. We've recently updated our [setup steps for the build phase](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step), and particularly the CocoaPods one is way simpler. Please give that a try, and open a new issue if you're still running into the same problems. Thank you!
