### ISSUE TITLE
Codegen requires all objects to implement equatable.

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#442]
I'm pretty sure it's because of `public typealias ResultMap = [String : Any?]`. Because `Any?` is not Equatable. If it was `[String : AnyHashable?]`, this wouldn't be a problem. In reality, the objects should already be generated with equatable.

I'm generally concerned about the code quality codegen provides and would greatly appreciate an alternative solution.

**Comment by jimisaacs** [comment]
An alternative solution would be, do only use codegen for the queries, not the responses.

**Comment by koenpunt** [comment]
> In reality, the objects should already be generated with equatable.

I definitely agree, would make usage with IGListKit a lot more convenient.

**Comment by SirensOfTitan** [comment]
> I definitely agree, would make usage with IGListKit a lot more convenient.

We make very heavy usage of IGListKit in our app, so had to have this.  I ended up using a little Sourcery template to codegen Equatable for Apollo's entire generated API.  See below:
https://gist.github.com/SirensOfTitan/5f9feb2dca067e4b4152609e1851c028

... I am not sure if my work is 100% correct, but it works in practice pretty well.  I'd be willing to setup a PR for the official codegen client once the Meteor folks hire their fulltime iOS engineer.

**Comment by designatednerd** [comment]
@SirensOfTitan Hi I'm the fulltime iOS engineer who was (finally) hired, let me know if I can be of help here!

**Comment by jimisaacs** [comment]
Hello @designatednerd! I haven't looked at what is being generated in a while, but if it's still the same, then I'd assume what I put in the issue description is still relevant. There's some higher level difficulties I have had with the codegen, but those would be off topic here, as this issue is pretty explicit.

**Comment by designatednerd** [comment]
We are going to have a few changes landing soonish, but I'll put this in to take a look at when we're dealing with that.

**Comment by kimdv** [comment]
I think we also should consider autogenerate the `Hashable` interface

**Comment by designatednerd** [comment]
Yes `Hashable` is definitely happening in addition to equatable - I've been doing that in some behind the scenes stuff prepping for updated codegen

**Comment by kevinmbeaulieu** [comment]
@designatednerd Is this still coming or do we still need someone to pick up the work for this?

**Comment by designatednerd** [comment]
Yes! Please follow along with the [Codegen Project](https://github.com/apollographql/apollo-ios/projects/2) to see where things are at - working on that at the same time as a few other things though.

**Comment by ts95** [comment]
What's the status on this? 🙂

**Comment by designatednerd** [comment]
Coming along! Codegen itself got blocked for a bit so I shifted to working on the networking stack, but once that's out I'll be back on Codegen and auto-Equatable conformance is definitely a big goal.

**Comment by ts95** [comment]
Awesome 🙌 With auto Equatable and Hashable conformance it would be a lot easier to implement diffing for table views and collection views

**Comment by designatednerd** [comment]
Yes, aboslutely!

**Comment by alizx** [comment]
looking forward to it

**Comment by pavm035** [comment]
Any updates when this will be released?

**Comment by alizx** [comment]
This simple thing basically makes working with apollo codegen pain in the neck!

**Comment by calvincestari** [comment]
Hi 👋🏻 - this issue should be resolved in 1.0. 1.0 is currently in alpha releases with a full 1.0 release in H2 2022. Please take a look at the [latest alpha](https://github.com/apollographql/apollo-ios/releases) and let us know if this is still an issue for you.

**Comment by jimisaacs** [comment]
Happy to see this issue resolved 👍
