### ISSUE TITLE
Code generation build phase script error when adding 'Apollo/WebSocket' cocoapod

### ISSUE THREAD

**Issue by zoufishanmehdi** [apollographql/apollo-ios#445]
I added `pod 'Apollo/WebSocket'` to my Podfile which required a newer version of Apollo. After using pod update 'Apollo/WebSocket', Apollo updated from 0.8.0 to 0.9.5. and Starscream 3.0.6 got installed. Now when I run build in Xcode, I keep seeing the following error: 

`find: /Users/zoufmehdi/Library/Developer/Xcode/DerivedData/Healthie-adbzyybfvvcneaboeastjqennmqn/Build/Products/Debug-iphoneos/Starscream: No such file or directory
error: Please update your code generation build phase script to use the new Apollo CLI, see https://www.apollographql.com/docs/ios/installation.html#adding-build-step`

Below you will find my code generation build phase script:
`APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate '**/*.graphql' --schema schema.json --output API.swift`

Any idea? When I reverted to Apollo 0.8.0 and it worked fine again.

**Comment by martijnwalraven** [comment]
If you follow the instructions at https://www.apollographql.com/docs/ios/installation.html#adding-build-step, you will find an updated build script you can copy/paste that invokes `check-and-run-apollo-cli.sh` instead of `check-and-run-apollo-codegen.sh`. That should make your build work again.
