### ISSUE TITLE
Errors when trying to update to Apollo 0.9.5

### ISSUE THREAD

**Issue by zoufishanmehdi** [apollographql/apollo-ios#447]
I updated to Apollo 0.9.5, removed the previous schema.json and API.swift file, and regenerated the schema in order to re-add these two files to my Xcode project (Xcode 10.1). However, I'm still getting tons of errors saying 'Value of type query has no member..' in files where I'm parsing results from these queries. Please refer to the screenshot below. Also, I copied the new code generation script from the documentation. I have tried many things and I'm not sure how to fix this at this point. I'm pretty stuck and would really appreciate any input. Thank you!

<img width="531" alt="screen shot 2019-01-30 at 11 13 14 am" src="https://user-images.githubusercontent.com/12058032/52008062-d3991080-249d-11e9-9771-7833ddbb5c6b.png">

**Comment by martijnwalraven** [comment]
Hmmm, those errors could be due to changes in the handling of fragments. Could you try adding `--mergeInFieldsFromFragmentSpreads` to the `check-and-run-apollo-cli.sh` invocation in your build phase script?

**Comment by zoufishanmehdi** [comment]
I modified my script to include `--mergeInFieldsFromFragmentSpreads` as you can see below. 

`APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --queries="$(find . -name '*.graphql')" --mergeInFieldsFromFragmentSpreads --schema=schema.json API.swift`

I removed schema.json and API.swift file and readded those files based on the new schema. I'm seeing 130 errors instead of 230+ but they say 'use of unresolved or undeclared identifier...Query or Input' as you can see below. 

<img width="332" alt="screen shot 2019-01-30 at 3 40 52 pm" src="https://user-images.githubusercontent.com/12058032/52011428-e9123880-24a5-11e9-96a3-55c6141b8ca5.png">

**Comment by martijnwalraven** [comment]
Have there been changes to your schema or to `.graphql` files? It seems not all operations have code generated for them.

**Comment by zoufishanmehdi** [comment]
I asked a web dev and he said no changes were made to the schema. I only added three `.graphql` files but it was all working fine in Apollo 0.8.0

**Comment by martijnwalraven** [comment]
Can you see if operations from specific `.graphql` files are missing from `API.swift`? Maybe these aren't found by `$(find . -name '*.graphql')`?

What does the script output look like?

**Comment by martijnwalraven** [comment]
Good to hear!
