### ISSUE TITLE
Shared Apollo Client and Cache for cross-platform code

### ISSUE THREAD

**Issue by patgoley** [apollographql/apollo-ios#448]
Hey there,

First of all thanks for a sweet library! I am attempting to write a cross-platform application and would like both Swift and JS code to share the same Apollo Client and local cache. I don't think I'm the first person to think of this based on this article from the Apollo Medium page:

https://blog.apollographql.com/one-graphql-client-for-javascript-ios-and-android-64993c1b7991

Presumably, my native and JS code share the native client/cache (apollo-ios) which is injected into the JS environment. There's one main problem doing this, with a few possible solutions that I see. The problem is that Apollo iOS _only_ accepts generated Swift types for queries/mutations, so I'm not sure how my JS is going to translate it's queries into those. Possible solutions:

1. Use a GraphQL string instead of native types conforming `GraphQLOperation`. It would be easy to generate the query string in JS and pass to the native client, but it doesn't appear that Apollo iOS supports string-based queries. It's all based around native query and mutation types. We can't make a dynamic `GraphQLOperation` type because we wouldn't have a static type to supply for the `Data` associatedtype which is used to parse the response etc.

2. Use a JavaScript ApolloClient, but inject it with the native Apollo store or cache object. In theory, this could work, but it's not clear on initial investigation if the native and JS store/cache implement the exact same interface. Perhaps it's close enough that with a little glue code I can make them interchangeable. 

I know the Apollo team has thought about this based on the article above. Is there an official way to do this, or should I plan on doing one of the options above? Thank you so much for your time!

**Comment by martijnwalraven** [comment]
We actually discussed both options back in the days :) Both will require significant work though, just as a warning. We never got around doing this as intended, and it's not currently on any roadmap.

As for 1), the idea would be that we'd relax the current associated `Data` type and allow you to use a dynamic operation with a `JSONObject` result. There is some code for this in place already, [`GraphQLResponseGenerator`](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/GraphQLResponseGenerator.swift) allows you to read a result (either from the network or from the cache) as JSON instead of constructing native types.

**Comment by patgoley** [comment]
Thanks for the quick reply! 

I've done some more digging and think I might have a workable approach for option #2, but let me know what you think. Both the Swift and JavaScript libraries have an interface called `NormalizedCache` which seems to store cache data under arbitrary keys. While the JS Apollo store seems to use an in-memory implementation, I'm thinking I can inject an implementation that defers to the native `SQLiteNormalizedCache` type. Their API's are not exactly the same but do look to be translatable with a bit of glue. Of course, I'm not deeply familiar with either library, so I don't know if this would achieve total cache parity between the environments or what other side effects it may have.

Any insight you can offer is greatly appreciated. I'm happy to take this to the JS repository if that's more appropriate. Thanks again!

**Comment by patgoley** [comment]
After some more thought, I have a simpler solution. Since I have very few native queries and many queries in JS, I'm just going to use `apollo-client` and `apollo-cache-persist` in the JS environment. Native code will call into JS wrapper object through simple method calls, which will make queries against the JS Apollo client. It seems like getting native and JS clients working against a shared cache could be a rabbit hole, so better for me to just optimize for the environment that needs the client more.

Thanks for your help!
