### ISSUE TITLE
Subscriptions- websocket ping error

### ISSUE THREAD

**Issue by zoufishanmehdi** [apollographql/apollo-ios#449]
I set up a subscription and I'm seeing this error message. I don't see much information about it online but I can see that my websocket is connected. 

`Apollo.WebSocketError.ErrorKind.unprocessedMessage("{\"type\":\"ping\",\"message\":1548959702}"))` 

`func fetchSubscriptionNotes(conversationId: String)  {
        var conversationMessages: [ConversationMessage] = []
        print("subscription notes convo id \(conversationId)")
        apollo.subscribe(subscription: OnNoteAddedSubscriptionSubscription(conversationId: conversationId)) { (result, apolloError) in
            if let errorFound = apolloError {
                print("ERROR \(errorFound)")
        }
      }
    } `

**Comment by designatednerd** [comment]
It looks like your server is sending an occasional ping to ensure your app is still connected. Are you using an Apollo server or a different server?

**Comment by designatednerd** [comment]
Since I haven't heard back from OP in a couple weeks, I'm going to close this out. If you're still having problems, feel free to reopen or open a new issue. Thank you!

**Comment by mustafauskuplu** [comment]
@zoufishanmehdi did you solve your issue? I'm having the same problem.

**Comment by designatednerd** [comment]
@mustafauskuplu There's now [a convenience method for pinging a websocket](https://github.com/apollographql/apollo-ios/blob/master/Sources/ApolloWebSocket/WebSocketTransport.swift#L97) - you'll probably still get that unprocessed message error but you should be able to discard it.

**Comment by mustafauskuplu** [comment]
@designatednerd It seems that method is using Starscream's:

`public func write(ping: Data, completion: (() -> ())?)`

But there is another function for pong response in Starscream lib:

`public func write(pong: Data, completion: (() -> ())?)`

These functions call the same method but using different "opcode" values.

1. Shouldn't I use pong function? (But it seems it is not exposed through Apollo).
2. Have you encountered this behavior before? My subscription is waiting for totally another data but I'm getting just a ping.

**Comment by designatednerd** [comment]
I'll admit my understanding of WebSocket stuff is a bit hand-wavy - this lib got built before I joined the team.  I can definitely look at exposing the pong function as well if needed - do you mind opening a new issue on this though?

**Comment by mustafauskuplu** [comment]
@designatednerd  I am new with WebSockets too. Thanks for following up on this issue. Before creating the new issue, I will contact the back-end side and learn some details about the implementation.

Because I believe, if back-end implementation is a "common" one, instead of relying on manual ping/pong handling, it should be automatic. What do you think?

I'll analyze both Starscream and Apollo SDKs a little bit more too to make sure I'm on the right path. I will open a new issue based on my findings.

**Comment by designatednerd** [comment]
Sounds like a plan. Thanks!
