### ISSUE TITLE
Subscriptions- not able to use actioncable protocols instead of graphql-ws to make iOS app work with ActionCable

### ISSUE THREAD

**Issue by zoufishanmehdi** [apollographql/apollo-ios#454]
Hi! I tried to edit `private final let protocols = ["graphql-ws"]` to `["actioncable-v1-json", "actioncable-unsupporteduse"]` in `WebSocketTransport.swift` file in order to use action cable protocols being used on the server. However, I'm getting errors when doing that. How can I conform to action cable protocols to make my iOS app work with Action Cable?

**Comment by zoufishanmehdi** [comment]
I explain the issue in more detail here: https://stackoverflow.com/questions/54576125/integrate-apollo-subscriptions-on-ios-with-action-cable-being-used-on-the-backen

**Comment by JosephHosf** [comment]
Facing the same issue. @zoufishanmehdi any luck in finding a solution?

**Comment by designatednerd** [comment]
Looks like the person behind #634 is going to be taking a look at this problem - @zoufishanmehdi do you mind if we close this issue out and let that one be the representative issue?

**Comment by designatednerd** [comment]
The poster behind #634 seems to have run straight into a brick wall with this. It doesn't seem like there's a great way to support multiple web socket protocols without quite a bit more work.

Unfortunately that's not really a priority for Apollo at the moment, so I'm going to close this out, but I'd be happy to work with anyone interested in putting a PR together for this.

**Comment by Nealsoni00** [comment]
Hi, I'm experiencing the same issue. Does anyone know if there has been any progress on enabling actionable subscriptions for iOS? I'm trying to connect a graphql-Ruby server to the apollo-ios client and am experiencing an issue with the handshake. 

Is there a workaround other than using silent push notifications? Does anyone have examples of his workaround updating the client-side cache?

**Comment by designatednerd** [comment]
We still do not support this protocol.
