### ISSUE TITLE
Seed ApolloStore with Subscription Results

### ISSUE THREAD

**Issue by Nomad-Go** [apollographql/apollo-ios#457]
I wan't to keep my cache up to date with Subscriptions. I can't quite figure out the syntax to write the results of a subscription into the cache. I have a subscription in the form of:

```
subscription DeviceFromVendorIdentifier($vendorId: uuid) {
    device_ios(where: {identifierForVendor: {_eq: $vendorId}}) {
        ...DeviceGraph
    }
}

fragment DeviceGraph on device_ios {
    id
    name
}
```

My Swift code to use the subscription look like this.

```swift
let vendorID = <the_id>
let deviceSubscription = DeviceFromVendorIdentifierSubscription(vendorId: vendorID)

let apolloClient = //Configured ApolloClient with web sockets and an ApolloStore

apolloClient.subscribe(subscription: deviceSubscription, resultHandler: { (p_results, p_error) in
    if let error = p_error {
        print(error)
    }else if let data = p_results?.data {
        let promise = apolloClient.store.withinReadWriteTransaction { (transaction) in
            do {
                try transaction.updateObject(ofType: DeviceSubscriptionFromVendorIdentifierSubscription.Data.self, withKey: "id", { (data: inout DeviceSubscriptionFromVendorIdentifierSubscription.Data) in
                    quickLog(title: "Data", message: "\(data)")
                })
            }catch{
                print("Error")
            }
        }
    }else{
        print("No Error, No results")
    }
})
```

This code always get caught with the error `Missing value` thrown from the `.updateObject` function.

Some notes and more context. 

I start the subscription on app launch. Do I need to seed the Cache with at least one record first? I think the `Missing` value error is trying to tell me it can't find anything in the cache to update. Because it can't find anything to update I never get the opportunity to insert?

Also, my data is from a PostgresDB where all objects have a unique primary key of `id`. Because of this I initialize the `ApolloStore` like this:

```swift
let cache = try SQLiteNormalizedCache(fileURL:<file_url>)
let store = ApolloStore(cache: cache)
store.cacheKeyForObject = self.objects(_:)

private func objects(_ object: JSONObject) -> JSONValue? {
   return ["id"]
}
```

I love this library and want to keep learning about it so I might be able to contribute.

**Comment by martijnwalraven** [comment]
```
withKey: "id"
```

Not sure if this solves all your issues, but this needs to be the actual key (so the value of `id` for a particular object).

**Comment by Nomad-Go** [comment]
@martijnwalraven Thank you, I missed that. What do I do if I have nothing cached? This is the first call to my API on App launch. Also, I just read [this article](https://blog.apollographql.com/the-concepts-of-graphql-bc68bd819be3) about caching. Super helpful but i'm still uncertain about Cache Normalization. Just specifying "id" as a cache value does not seem to be enough because of collisions between tables on my DB. The article suggest appending the `__typename` to the id. Would it then look something like this:

```swift
let cache = try SQLiteNormalizedCache(fileURL: <file_url>)
let store = ApolloStore(cache: cache)
store.cacheKeyForObject = self.objects(_:)

private func objects(_ object: JSONObject) -> JSONValue? {
    guard let objectType = object["__typename"] as? String else {
        return nil
    }
    let key = "\(objectType):id"
    return key
}
```  

So two questions.

1) Do I need to make a field in by actual DB that can save values in the form of <__typename>:<id> and somehow populate them on creation at the DB level?

2) How do I refer to the id (or id(s) of objects) of the subscription?

Thank you.

**Comment by Nomad-Go** [comment]
Ok, so I had to download an SQLite inspector and inspect actual app data to really get what is going on with caching. Looks like I mis understood @martijnwalraven a second time.

I can see my cache is successfully normalized when I make the cache keys like this:
```swift
let cache = try SQLiteNormalizedCache(fileURL: <file_url>)
let store = ApolloStore(cache: cache)
store.cacheKeyForObject = self.objects(_:)

func objects(_ object: JSONObject) -> JSONValue? {
    guard let objectType = object["__typename"] as? String, let id = object["id"] as? Int else {
        return nil
    }
    let key = "\(objectType):\(id)"
    return key
}
```
Still looking to figure out how to write the initial results of a subscription into the cache.

**Comment by Nomad-Go** [comment]
Ok, figured it out. The Apollo library internally takes the Query you want to write to the cache and figures out its type, cache key and variables. You have to do this for a subscription. Working code looks like this:

```swift
let vendorID = <the_id>
let deviceSubscription = DeviceFromVendorIdentifierSubscription(vendorId: vendorID)

let apolloClient = //Configured ApolloClient with web sockets and an ApolloStore

self.apolloClient.subscribe(subscription: deviceSubscription, resultHandler: { (p_results, p_error) in
    if let error = p_error {
        quickLog(error)
    }else if let results = p_results?.data?.deviceIos  {
        //Freaking JS world tryign to make promises a thing here in native land. JK I love async/await!! Brign on Swift 5
        let promise = self.apolloClient?.store.withinReadWriteTransaction { (transaction) in
            do {
                //This is key! You have to ge the key (lol) for this subscription from this global helper function in the Apollo library. I had to make the function public.
                let cacheKey = rootCacheKey(for: deviceSubscription)
                //It's easy to miss the variables piece as it's an optional value that defaults to nil
                try transaction.updateObject(ofType: DeviceSubscriptionFromVendorIdentifierSubscription.Data.self, withKey: cacheKey, variables: deviceSubscription.variables, { (data: inout DeviceSubscriptionFromVendorIdentifierSubscription.Data) in
                    data.deviceIos.append(contentsOf: results)
                })
            }catch{
                print(error)
            }
        }
    }else {
       print("Empty Subscription")
    }
})
```

**Comment by knutaa** [comment]
Hi, I ended up doing something like the following - mostly for a trial and not really proven in production:

   // subscribe (here NewPostSubscription)
   // whenever new data
   // 0. within a ReadWrite transaction
   // 1. Query the cache for the data (here: AllPostQuery)
   // 2. Create a new instance of the query object
   // 3. Add the new instance to the query result

   newPostSubCancel = client?.subscribe(subscription: NewPostSubscription(), resultHandler: { (result, error) in
      if let result = result,
         let newPost = result.data?.newPost?.fragments.postDetails {
        _ = store.withinReadWriteTransaction { transaction in
          try transaction.update(query: AllPostsQuery()) { (data: inout AllPostsQuery.Data) in
            let post = AllPostsQuery.Data.Post(id: newPost.id, ...)           
            data.posts?.append(post)
          }
        }
      }
   })

**Comment by designatednerd** [comment]
@Nomad-Go Were you able to resolve your issues with the above suggestions, or are there additional problems?

**Comment by designatednerd** [comment]
Since I haven't heard back from OP in a couple weeks, I'm going to close this out - please open a new issue if you're still having problems!
