### ISSUE TITLE
How to handle multiple environments?

### ISSUE THREAD

**Issue by MaxGoh** [apollographql/apollo-ios#460]
I'm using Apollo iOS for my application. I'm trying to simplify the development process, how can I manage multiple environments; development, staging and production?

It would be awesome if someone could provide an example.

Thank you

**Comment by Nomad-Go** [comment]
Ideally your backend resources have all three environments. In this case your backed is a GraphQL API. 

You should store some sort of state in you application that represents the backend environment that you are testing. I persist this state in `NSUserDefaults`. Then when my app launches I can gather environment variables that represent the desired backend environment and initalize the Apollo client with those variables. 

As for your iOS code your app on the app store should be your production app with the master branch of your repository representing that release. Test flight should be backed by a branch in your repo called staging. Finally, when developing you should be on a feature branch or just a development branch. You issue and merge pull requests from feature/develop -> Staging -> master as your release progress through testflight and then the app store.
