### ISSUE TITLE
JSON deserialization: option to allow fragments not set

### ISSUE THREAD

**Issue by ruipfcosta** [apollographql/apollo-ios#462]
I'm experimenting Apollo by running a very simple query to get data from my server, but I'm getting the following error:

```
Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
```

This is likely caused by the missing option `.allowFragments` when deserializing the JSON response, but is there any way to specify this through Apollo? 

Thanks!

**Comment by designatednerd** [comment]
There's not a way to set it directly at the moment - can you talk a little bit about why you need this? In theory this shouldn't be necessary but of course theory and practice are two different things 🙃

**Comment by designatednerd** [comment]
Since I haven't heard back on this question in a couple weeks, I'm going to close it out. If you've got further questions, please feel free to stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) anytime!
