### ISSUE TITLE
Builds are broken by enum cases with the same (textual) lowercase representation 

### ISSUE THREAD

**Issue by ataibarkai** [apollographql/apollo-ios#463]
The GraphQL API I'm building against contains an enum with different cases which have the same (textual) lowercase representation (as an aside, this was the result of deprecating a PascalCase naming convention in favor of a SCREAMING_CASE naming convention -- but it doesn't really matter much, because this kind of configuration is legal under the GraphQL spec):
<img width="163" alt="playground_-_https___www_doximity_com_graphql_720" src="https://user-images.githubusercontent.com/746397/53517048-94e97c80-3a82-11e9-8d1b-fa88f3aab155.png">

The generated Apollo code fails to compile due to a naming collision:
<img width="360" alt="doximityendpointgraphqlapi_swift_720" src="https://user-images.githubusercontent.com/746397/53517084-ae8ac400-3a82-11e9-9fd7-99854fc387f3.png">

---

https://github.com/apollographql/apollo-ios/issues/72 seems related, but there are resolutions of this specific issue which are much less drastic (and which are also non-breaking, because they would only affect already-broken code).

For example, you could use the original GraphQL name only in the presence of collisions (`case Employment`, `case EMPLOYMENT`), suffix colliding cases with their original name (e.g. `case employment_Employment`, `case employment_EMPLOYMENT`),  etc.

**Comment by designatednerd** [comment]
Ooh, hairy one! I'll have to take a look at some options for handling this.

**Comment by cczufish** [comment]
you try to fix it with GraphQL aliases: https://graphql.github.io/learn/queries/#aliases

if you want query: 👍

#查看动态点赞数据
query FeedLikes($id:ID!,$limit:Int){
feed(id:$id){
id
likesCount
commentsCount
created_at
likes(limit:$limit){
id
name

nickname
created_at
avatar(size:THUMBNAIL)
roles

}
}
}

you can write your query code :

#查看动态点赞数据
query FeedLikes($id:ID!,$limit:Int){
feed(id:$id){
id
likesCount
commentsCount
created_at
likes(limit:$limit){
id
name

nickname
created_at
avatar(size:THUMBNAIL)
empireHero:roles

}
}
}

**Comment by designatednerd** [comment]
Aliases are indeed very helpful for name collisions between fields, but as far as I know you can't use them to rename enum cases.

**Comment by Mountainbrussells** [comment]
Any progress on this?

**Comment by designatednerd** [comment]
This will go into the updated codegen outlined in #939

**Comment by designatednerd** [comment]
Closing this out since it's actually built - this will ship with the [Swift Codegen Phase 1 Alpha milestone](https://github.com/apollographql/apollo-ios/milestone/23) - please follow progress on that milestone to see when this is actually going to ship as alpha.
