### ISSUE TITLE
Update using newest Starscream for subscriptions

### ISSUE THREAD

**Issue by fassko** [apollographql/apollo-ios#465]
I'm using GraphQL subscriptions and noticed that old version of https://github.com/daltoniam/Starscream websockets library is being used. I'm one of the maintainers of that library.

I can update the version where it's needed, but I would need some help with testing it.
Any tips & tricks?

Related to #60

**Comment by fassko** [comment]
It seems that in Cartfile there is newest version, but not in podspec.

**Comment by MaxOstPM** [comment]
@fassko Hi! Can you please help me? I don't understand for sure if subscription is working in Apollo Client. Seems that needed method is implemented but nothing happened, also could found any documentation for Apollo Subscriptions!
Waiting for response!
Best regards,
Max!

**Comment by fassko** [comment]
@MaxOstPM 

Yeah documentation about subscriptions is missing, I totally agree.

To create a subscription I was using these resources:
https://github.com/hasura/graphql-engine/issues/503
https://stackoverflow.com/questions/51720378/how-to-implement-graphql-subscription-using-apollo-ios-client

I can't share my project because it ties down to closed source project GraphQL scheme.

**Comment by fassko** [comment]
In general everything works (except it doesn't build for other platforms than iOS but for that there is another issue #386 )

With this issue and PR I created I just wanted to update Starscream library which is being used for subscriptions. I'm actually one of maintainers of Starscream library.

**Comment by MaxOstPM** [comment]
@fassko I have a problem with a cancelation of subscription. When I want to reopen subscription, after I have canceled it, I'm receiving only errors, and no response

**Comment by fassko** [comment]
@MaxOstPM hard to tell anything without an example. Anyways I think this is out of the scope of this issue.
