### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by kukkadapukarthik** [apollographql/apollo-ios#474]
++ npx --no-install apollo codegen:generate '--includes=./PostTableViewCell.graphql
./PostListViewController.graphql' --schema=schema.json --target=swift API.swift
 ›   Warning: apollo update available from 1.8.3 to 2.6.0.
 ›   Error: Unexpected argument: API.swift
 ›   See more help with --help
Command /bin/sh failed with exit code 2

/*Run script was
APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --includes="$(find . -name '*.graphql')" --schema=schema.json --target=swift API.swift*/

**Comment by designatednerd** [comment]
Hi there! We've recently updated our [setup steps for the codegen build phase](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step). Please give those updated steps a shot, and open a new issue if you are still running into problems. Thank you!
