### ISSUE TITLE
long number -> Apollo.JSONDecodingError.couldNotConvert

### ISSUE THREAD

**Issue by Developer-iOS-OSX** [apollographql/apollo-ios#476]
Hi All!  
It is real data from server:

<img width="380" alt="Screenshot 2019-03-22 at 17 17 25" src="https://user-images.githubusercontent.com/7106523/54828996-829be080-4cc6-11e9-984c-f796415f9467.png">
I see error in XCode, Help me please?:

```
Apollo.JSONDecodingError.couldNotConvert(value: {
    debtGas =     {
        070021301740 = "4505.57";
        070021353805 = "2067.07";
        070101802037 = "2260.18";
        070117503360 = "90173.66";
        071001000970 = "2299.81";
        071802006331 = "211193.59";
        073021240691 = "9584.1";
        073330741078 = "0.01";
        074000057111 = "13516.8";
        074200871663 = "630.36";
        074440406719 = "2908.22";
        077770418806 = 323;
```

**Comment by michaelnisi** [comment]
You should transport these Floats as Strings, rounding is not fun.

**Comment by designatednerd** [comment]
I have to agree with @michaelnisi's recommendation - float precision is a hell of a thing, especially around some of the limitations of JS. 

Going to close this as the official recommendation, but please hit up our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) if you have any further questions. Thank you!
