### ISSUE TITLE
User-friendly localizedDescription from query fetch Error

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [apollographql/apollo-ios#477]
I'm fetching a query in Apollo and the result handler provides an optional result and error object.

`apollo.fetch(query: SampleQuery()) { (result, error) in`

If the error is non-nil I present this error's `localizedDescription` to the user (and if it's not then I check if the result's errors is not empty and use the first error's `localizedDescription`). At times the user can be shown a very unfriendly message from that outer error, such as 

> Received error response (500 internal server error): {"errors":[{"message":"Context creation failed: Invalid app info headers.","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}

It seems this is the case when the error is a `GraphQLHTTPResponseError`. Could we get a friendly `localizedDescription` out of these errors?

**Comment by designatednerd** [comment]
@jordanhbuiltbyhq - I think I saw some changes around this recently - can you let us know how this is working for you on version 0.11.1 or higher?

**Comment by designatednerd** [comment]
Since I haven't heard back here in a couple of weeks, I'm going to close this issue out. If you're still having problems with newer versions of Apollo, please open a new issue. Thank you!
