### ISSUE TITLE
How to use objective C?

### ISSUE THREAD

**Issue by lizhuhuan** [apollographql/apollo-ios#490]

**Comment by victormihaita** [comment]
Maybe this will help: 
https://stackoverflow.com/questions/27995691/how-to-import-and-use-swift-pod-framework-in-objective-c-project
* And enjoy the 1st of April UI from StackOverflow :)

**Comment by MrBoog** [comment]
I'm also looking for an alternative written by OC.  I just don't really want to import swift right now since that might increase the size of our App.. (lots of our users are under iOS12.0)

**Comment by designatednerd** [comment]
Hello - @victormihaita is about correct, although you'd probably also need to create some kind of swift wrapper within your project that was `@objc` annotated. We are not planning on directly supporting Obj-C at this time. 

Going to close this question out.
