### ISSUE TITLE
Unable to Deploy App after upgrading Apollo 0.10.0

### ISSUE THREAD

**Issue by kcarriedo** [apollographql/apollo-ios#500]
Deployment error after upgrading apollo, `App Store Connect Operation Error
Invalid Bundle. The bundle at '/Frameworks/Apollo.framework' contains disallowed file 'Frameworks'.`

Xcode: 10.2 
Swift: 5 
Apollo build: 0.10.0

**Comment by kcarriedo** [comment]
It appears to be building nested frameworks. Was able to workaround it by removing the nested framework and deploy.
![image](https://user-images.githubusercontent.com/323828/55525185-1a51e500-565e-11e9-9c0a-d1db70141f91.png)

**Comment by martijnwalraven** [comment]
@tonyarnold Do you know what might be going on here?

**Comment by xploit42** [comment]
What version of apollo codegen do you use with this apollo 0.10.0?

And did you see a changelog somewhere?

Thanks

**Comment by tonyarnold** [comment]
@martijnwalraven looks like I've enabled `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` in `Workspace-Packaging.xcconfig`. Setting it to `NO` should solve the problem.

@kcarriedo can you try this on your local copy of the project and verify that it works?

**Comment by martijnwalraven** [comment]
@tonyarnold Thanks for your help, unfortunately this is an area I haven't been able to keep up with :) Could this be related to https://github.com/apollographql/apollo-ios/issues/485#issuecomment-479362202 as well?

**Comment by tonyarnold** [comment]
That's OK - I'll pull together a PR for this. 

#485 is a separate issue - I've commented over there to try to get some more info.
