### ISSUE TITLE
Don't want to pass optional parameters in Query

### ISSUE THREAD

**Issue by bpollock-vida** [apollographql/apollo-ios#502]
Intended outcome:

Given:

Query {
   fooQuery(argOne: String, argTwo: String) {
      bar
   }
}
I want to only pass the arguments I have values for:
FooQuery(argTwo: "someString")

Actual outcome:
Swift compiler will complain with 'missing argument for parameter argOne in call'

The Apollo-client generated constructor is
public init(argOne: String?, argTwo: String?)

How to reproduce the issue:

Create a query with two optional arguments
Include Apollo-client and type generation in an iOS Xcode project
Try to pass one argument into the query in Xcode
Versions
System:
OS: macOS 10.14.2
Binaries:
Node: 11.9.0 - ~/.nvm/versions/node/v11.9.0/bin/node
Yarn: 1.13.0 - /usr/local/bin/yarn
npm: 6.5.0 - ~/.nvm/versions/node/v11.9.0/bin/npm
Browsers:
Chrome: 73.0.3683.86
Safari: 12.0.2
npmGlobalPackages:
apollo-codegen: 0.20.2
apollo: 2.4.4

Don't think these are relevant ^

Xcode: 10.1
Swift: 4.2
pod 'Apollo', '= 0.9.0'

I think these are relevant ^

**Comment by designatednerd** [comment]
I think that would require us providing a default value of `nil` for optional parameters, which I don't really want to do as I'd like people to explicitly tell us if they don't want to use a particular parameter by passing `nil`.

Would making an extension within your code that wrapped your desired behavior in a `convenience init` work for you?

**Comment by designatednerd** [comment]
Since I haven't heard back from OP in a couple weeks, I'm going to close this question out with my suggestion of making a `convenience init` as the official one. Please feel free to stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) if you have more questions!

**Comment by karramAyman** [comment]
@designatednerd Could you please add more details about this solution.

**Comment by designatednerd** [comment]
Sure. If the generated init for a struct is: 

```swift
public init(argOne: String?, argTwo: String?)
```

Then you can make convenience inits like this: 

```swift
extension YourStruct {
    
    public init(argOne: String?) {
        self.init(argOne: argOne, argTwo: nil)
    }
    
    public init(argTwo: String?) {
        self.init(argOne: nil, argTwo: argTwo)
    }
    
    public init() {
        self.init(argOne: nil, argTwo: nil)
    }
}
```
