### ISSUE TITLE
Cancellation logic causing non-determinism when invoking result handler.

### ISSUE THREAD

**Issue by coreygrunewald** [apollographql/apollo-ios#514]
Hello,

We are seeing some non-deterministic behavior in a unit test from cancelling a `.fetch()` call with a cache policy of `.returnCacheDataAndFetch`.

Most of the time, our result handler callback is never called. I'm assuming this is because we are hitting this line in the `FetchQueryOperation`: https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloClient.swift#L192.

Occasionally, we see our result handler callback is invoked, most likely hitting this line: https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloClient.swift#L206. Even though the task is in a cancelled state, the result handler is still invoked with a result.

I think the cancellation logic can be improved by:
1. Always invoking the result handler in the case of a task being cancelled. By not invoking the result handler, the caller could be stuck in a waiting state, etc.
2. When the result handler is invoked, if the task is cancelled, pass a specific Error instance, with no result, signaling to the user that the operation was cancelled.

Does this make sense? Am I missing any context around how cancellation should work? Any insight or feedback would be much appreciated, thank you!

**Comment by michaelnisi** [comment]
You should be able to use [Operation’s](https://developer.apple.com/documentation/foundation/operation/1408085-completionblock) `completionBlock: (() -> Void)?` for cleanup, it should get called after the operation is finished, successfully or not.

Another thought. Considering that a cancelled operation doesn’t *really* have a result and cancellation isn’t *really* an error, how about introducing  a new cancellation handler `cancellationHandler: (() -> Void)?` for signalling to interested objects without changing the API? From what I understand from reading the code, always calling the result handler for cancelled operations would be a breaking change.

But it should be deterministic, of course, never calling the result handler when cancelled.

**Comment by michaelnisi** [comment]
Forget the first part, `Cancellable` doesn’t expose `completionBlock`.

**Comment by designatednerd** [comment]
@coreygrunewald Are you still seeing this issue on 0.11.1 or higher? We've added some methods which should be helpful for this, but I'm not positive it'd totally fix the whole issue here. Let me know what happens after you upgrade. Thanks!

**Comment by designatednerd** [comment]
Since I haven't heard back on this for a couple weeks, I'm going to close this issue out. Please open a new issue if you're seeing this on newer versions of our SDK. Thank you!
