### ISSUE TITLE
Public initializers for auto-generated code

### ISSUE THREAD

**Issue by amol-c** [apollographql/apollo-ios#52]
Hi,

Can we have public initializers for auto-generated code.

It becomes very tedious to write unit test and creating Mocks for the models.

Based off of the discussion here.

https://github.com/apollographql/apollo-ios/pull/49

Thanks.

**Comment by martijnwalraven** [comment]
You'll be happy to hear we just released Apollo iOS 0.6.0-beta.1, which includes memberwise initializers (or type-specific factory methods) for generated models. Make sure to use `npm install -g apollo-codegen@next` until it is out of beta.
