### ISSUE TITLE
Code generation fails when adding a new query or mutation

### ISSUE THREAD

**Issue by GenaroMarmolejo** [apollographql/apollo-ios#521]
I have been working with apollo client for iOS for a while, I have my queries and mutations in different files (as it is supposed to be) and it have generated the API.swift file correctly all this time, until yesterday that I added a new mutation to one of my files.

After I added this new mutation, the other queries are not being generated, thus the API.swift file is empty now. If I delete that query the API.swift is created correctly. 

I verified the syntax of the new query and I also tested it on the Apollo playground and it works fine, also if I add it to a new .graphql file it compiles fine (but given the project logic, structure and architecture this is not a viable workaround).

It doesn't show an error when it fails, it just empties the API.swift file, so I asume that it isn't because of a bad written query.

**Comment by Aldoukfm** [comment]
I have the exact same issue. How did you manage to solve it?

**Comment by GenaroMarmolejo** [comment]
I had a "," after the last attribute of my query.

For example I had something like:
`query contries {
countries {
name,
capital,
flagURL,
}
}`

The weird thing is that I had another queries with the "," at the end and it didn't caused me any issue before. But check if you have something like that, delete it and check if it generates the API file (maybe it may be another syntax issue).
