### ISSUE TITLE
Type  does not conform to protocol 'Hashable'

### ISSUE THREAD

**Issue by kukkadapukarthik** [apollographql/apollo-ios#533]
while I am using enums in grpahql, API.swift file generated but the following error shown on API.Swift file.

Type 'CountryCode' does not conform to protocol 'Hashable'
Do you want to add protocol stubs?

**Comment by designatednerd** [comment]
Weird, that certainly shouldn't be the case. Can you give more details about the enum - are all cases unique, are they all backed by strings, etc?

**Comment by designatednerd** [comment]
I'm going to close this one out since there hasn't been any response in a couple of weeks - if you do have more information, please feel free to reopen or file a new issue. Thank you!
