### ISSUE TITLE
Config for cache list object from query

### ISSUE THREAD

**Issue by vtamnh14** [apollographql/apollo-ios#535]
Hi Apollo,
I have a query like that
"query ListPriceRanges($limit: Int, $nextToken: String) {\n  listPriceRanges(limit: $limit, nextToken: $nextToken) {\n    __typename\n    items {\n      __typename\n      id\n      maxPrice\n      minPrice\n    }\n    nextToken\n  }\n}"

apolloClient?.cacheKeyForObject = { $0["id"] }

But after getting response success, I try to get it from cache but the cache is empty.
Please help me, How can I config for a cache of this case?

Thanks,

**Comment by designatednerd** [comment]
Hey @vtamnh14 - can you let us know how you're setting up your client so we can get a clearer idea of which cache you're using?

**Comment by designatednerd** [comment]
Since I haven't heard back here in a couple weeks, I'm going to close this one out. If you're still running into problems, please feel free to reopen this issue with more details or open a new one. Thank you!
