### ISSUE TITLE
Subscriptions create retain cycle

### ISSUE THREAD

**Issue by DarkDust** [apollographql/apollo-ios#536]
I've seen retain cycles and then leaked ApolloClient instances when using subscriptions. The WebSocketClient still being alive and trying to reconnect was causing issues for me.

The cycle seems to happen like this:

* ApolloClient.subscribe calls `ApolloClient.send(operation:, context:, handlerQueue:, resultHandler:)`
* Here, a closure is created [which captures `self`](https://github.com/apollographql/apollo-ios/blob/0586b33a720ae6e296c0b68ff94f65a4ffa45f64/Sources/Apollo/ApolloClient.swift#L161).
* This closure is passed around and ultimately [stored indirectly by `WebSocketTransport.subscribers`](https://github.com/apollographql/apollo-ios/blob/0586b33a720ae6e296c0b68ff94f65a4ffa45f64/Sources/ApolloWebSocket/WebSocketTransport.swift#L243) via [WebSocketTask](https://github.com/apollographql/apollo-ios/blob/0586b33a720ae6e296c0b68ff94f65a4ffa45f64/Sources/ApolloWebSocket/WebSocketTransport.swift#L274).
* The retain cycle is now closed (see image below).
* Since this task/cancellable is returned as a `@discardable`, I didn't make any use of it yet. It gets deallocated and the information to break the cycle is thus lost.

The cycle is broken if the `Cancellable` returned has its `cancel()` called. But I think that the cycle must not occur in the first place, for example by using a weak reference to `self` in `ApolloClient.send(operation:, context:, handlerQueue:, resultHandler:)`.

In the memory debugger, it looks like this (the highlighted Swift closure context is the one in `ApolloClient.send`):

<img width="596" alt="Screen Shot 2019-05-07 at 12 12 36" src="https://user-images.githubusercontent.com/1636077/57292175-72e32a80-70c1-11e9-9176-35bf18c48640.png">

**Comment by designatednerd** [comment]
Ha, that's the most classic retain cycle diagram I've ever seen. I'll try to look into this.

**Comment by designatednerd** [comment]
I started to dig into this and I'm going to close this out as stale - there have been significant improvements to the `WebSocket` implementation since this was filed (primarily ripping out the Promises implementation which seems to have been a big part of this problem).

If you're still seeing problems with retain cycles in web sockets using `0.17.0`, please file a new issue with updated details. Thank you!
