### ISSUE TITLE
 Set a strict version number for the `SQLite` dependency

### ISSUE THREAD

**Issue by shamilton-pandora** [apollographql/apollo-ios#537]
Using a strict version number of the SQLite dependency on 'Apollo/SQLite' would help the issue of having swift compatibility across versions. Right now we need to migrate back to 0.9.5 but can't because the SQLite dependency will auto pull the latest patch version. This latest patch version contains XCode 10.2 updates that are not backwards compatible with Xcode 10.1. So we are stuck.

**Comment by designatednerd** [comment]
This is definitely a good idea going forward. I'll look to include this in a future release.

**Comment by designatednerd** [comment]
Shipping with 0.12.0!
