### ISSUE TITLE
Multiple subscriptions over the same client

### ISSUE THREAD

**Issue by aivcec** [apollographql/apollo-ios#538]
I've been using apollo in my ios project and so far I had no issues with mutations and queries. But subscriptions leave me a bit perplexed.

During my initial attempts, Apollo seemed to open a subscription and I was able to receive data just fine. But I now realized that only the initial subscription on my apollo client works and all the later subscriptions never receive any events. 

That leaves me unable to dynamically open and close a subscription on the same client, as well as not allowing me to listen to multiple subscriptions at the same time. 

I confirmed that all the subscriptions themselves are valid, and each of them receives events IF they are the first subscription I subscribe to. Its just that the WebSocketTransport implementation only seems to work with the first subscription that arrives.

Is my scenario possible to achieve with the current version or is this a feature that still needs to be fully implemented?

EDIT: I should also note that I am using only one graphql subscription type, and the subscriptions I am connecting on are based on subfields of that one subscription.

**Comment by aivcec** [comment]
The framework works fine, the issue was on the backend.

**Comment by arnasledev** [comment]
what issue you had? I'm facing the same problem
