### ISSUE TITLE
Result enum in Result.swift overrides default Swift 5 implementation

### ISSUE THREAD

**Issue by jonnyjorvik** [apollographql/apollo-ios#547]
The `Result` type enum declared in `Result.swift` overrides the new Swift 5 implementation, meaning you have to explicitly specify `Swift.Result` in files that `import Apollo`.

**Intended outcome:** 
I can use `Swift.Result` without the `Swift` namespace in a file that imports Apollo.

**Actual outcome:**
I have to explicitly specify `Swift.Result`

**How to reproduce the issue:**
Create a new `swift` file and `import Apollo`. Create a function that accepts a closure as its only argument, whose parameter is of type `Result<String, Error>`.

**Comment by designatednerd** [comment]
Yeah I'm definitely going to be working on this - the original implementation is from well before Swift 5.

**Comment by designatednerd** [comment]
Shipping with 0.12.0!
