### ISSUE TITLE
Query with null field in Swift language

### ISSUE THREAD

**Issue by khacdai37** [apollographql/apollo-ios#548]
I want query the categories with parent = null but It sill return parent != null in result.
This's I want to
`query ParentCategories {
  categories(where: { parent : null }) {
    id
    name
}
`
I try with
`query ParentCategories($where: CategoryWhereInput) {
  categories(where: $where) {
    id
    name
}`

Swift: 

`var filter = CategoryWhereInput()    

filter.parent = nil

apollo.ParentCategories(where: filter)
`
but it's not work.

**Comment by designatednerd** [comment]
Can you give a bit more context here? I've got a few questions: 

- What, precisely is not working - is it not building, is it not returning the correct data, or something else?
- What is `apollo` here, your `ApolloClient`? 
- What's the full name of the query class, something like `ParentCategoriesQuery`? 
- How are you sending your query to the server, with `fetch`? 
- It looks like `CategoryWhereInput` is a type that you've generated, is that correct? 
- Is it possible to instantiate it like `let filter = CategoryWhereInput(parent: nil)`?

**Comment by designatednerd** [comment]
Hi, since I haven't heard back on this issue in a couple weeks, I'm going to close it out. Please feel free to reopen with more info!
