### ISSUE TITLE
Pod loading version 0.3.1

### ISSUE THREAD

**Issue by petersuwara** [apollographql/apollo-ios#55]
I have setup my pod file use Appolo. The latest version 0.5.4, but Cocoapods using my pod file is loading Appolo 0.3.1.

When will the pod be updated with the latest version ?

**Comment by martijnwalraven** [comment]
@petersuwara: The pod is always up to date with the latest release, so 0.5.4 right now. But Cocoapods won't install new versions automatically, you'll have to run `pod update`.

**Comment by petersuwara** [comment]
@martijnwalraven thanks very much. I realised this a little after I posted. Will close the issue.

Thanks for the good work.
