### ISSUE TITLE
ApolloStore is not public on ApolloClient

### ISSUE THREAD

**Issue by hariszaman** [apollographql/apollo-ios#554]
Following the instructions here for the direct access to cache of the store.
https://www.apollographql.com/docs/ios/watching-queries. 

But the variable "store" on "ApolloClient" is not publicly available making the method "withinReadTransaction" unavailable.

This should be made public to be accessible from outside of Apollo

**Comment by hariszaman** [comment]
Can anybody comment on this issue?

**Comment by designatednerd** [comment]
I would recommend [using the Client's initializer that allows you to pass in a store](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloClient.swift#L52) - that way you can hang onto the store separately so you can watch the queries. 

Does that help?

**Comment by designatednerd** [comment]
Since I haven't heard back in a couple weeks, I'm going to go ahead and close this issue out. Feel free to reopen or open a new issue if you're still encountering problems. Thank you!

**Comment by hariszaman** [comment]
Thank you for your help. I was using the same method but an older version of Apollo that didn't have store as public variable on client. After the update I can access it and everything works fine.
