### ISSUE TITLE
Deprecated enum cases

### ISSUE THREAD

**Issue by crabman448** [apollographql/apollo-ios#558]
In our schema some enum cases were deprecated. And even if these case are not used in the project, `Api.swift` shows warnings like on the screenshot. Is it possible somehow to avoid that on the client side without creating a new enum in the schema?
![Screenshot 2019-05-30 at 11 38 43](https://user-images.githubusercontent.com/7022709/58623998-7be5a700-82cf-11e9-806b-5b26e302981f.png)

**Comment by designatednerd** [comment]
Changes to the codegen going out with `0.18.0` will allow you to not generate enum values for deprecated cases by passing an `--omitDeprecatedEnumCases` flag. Will close this out once that ships.

**Comment by designatednerd** [comment]
Shipped!

**Comment by crabman448** [comment]
Yay! Thanks 🚀
