### ISSUE TITLE
BUG: Writing to cache not throwing execution errors

### ISSUE THREAD

**Issue by AnthonyMDev** [apollographql/apollo-ios#567]
When there is an error executing a write to the cache, the error is being suppressed, even though the function is meant to throw.

In `ApolloStore.swift` on line 246, it should use `await()` instead of `wait()`.

**Comment by designatednerd** [comment]
@AnthonyMDev Wanna put a PR together for this one? Would love to see this with a test that confirms an error is actually being thrown.

**Comment by AnthonyMDev** [comment]
I would love to, but my companies policy requires me to submit a form for approval on open source libraries we contribute to. I'm sending in that form today, so hopefully I'll be able to start contributing shortly. I'll get a test and a fix in place as soon as that goes through.

**Comment by designatednerd** [comment]
Godspeed with the bureaucracy

**Comment by AnthonyMDev** [comment]
I've been approved to contribute so I'll get a unit test and PR out to you today!
