### ISSUE TITLE
Build failed with Xcode 11.0 beta (11M336w) + Swift 5.1

### ISSUE THREAD

**Issue by MKGitHub** [apollographql/apollo-ios#568]
Please fix ASAP!

**Comment by dannymout** [comment]
This is the error I get attempting to build using Xcode 11.

```
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/dannym/Developer/surface/surface/Carthage/Checkouts/apollo-ios/Apollo.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 6:
2019-06-06 19:55:00.342 xcodebuild[7784:234738]  DTDeviceKit: deviceType from 64f481d3d4948f8046c2e41329f2bb83a71381e4 was NULL
2019-06-06 19:55:00.360 xcodebuild[7784:234668] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-14855.18/IDEFoundation/ProjectModel/Containers/IDEContainer.m:553
Details:  Error: Mismatch between existing container extension: <DVTExtension 0x7fbc18651f10: Folder (Xcode.IDEFoundation.Container.Folder) v0.1 from com.apple.dt.IDEFoundation> and requested container extension: <DVTExtension 0x7fbc18110260: Swift User Managed Package Folder (Xcode.IDEFoundation.Container.SwiftPackageUserManagedFolder) v0.1 from com.apple.dt.IDE.IDESwiftPackageSupport> for file path: <DVTFilePath:0x7fbc1bc05ef0:'/Users/dannym/Developer/surface/surface/Carthage/Checkouts/apollo-ios/Configuration'>
Object:   <IDEContainer>
Method:   +_retainedContainerAtFilePath:fileDataType:workspace:options:error:
Thread:   <NSThread: 0x7fbc18001870>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
  4   _dispatch_client_callout (in libdispatch.dylib)
  5   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
  6   DVTDispatchBarrierSync (in DVTFoundation)
  7   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
  8   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
  9   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 10   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 11   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 12   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 13   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
 14   -[IDEFileReference _recalculateReferencedContainer] (in IDEFoundation)
 15   -[IDEFileReference referencedContainer] (in IDEFoundation)
 16   -[IDEContainer _resolveFileReference:] (in IDEFoundation)
 17   __67-[IDEContainer initWithFilePath:extension:workspace:options:error:]_block_invoke.414 (in IDEFoundation)
 18   -[_DVTTimeSlicedMainThreadUnorderedUniquingWorkQueue _processWorkItemsWithDeadline:] (in DVTFoundation)
 19   -[DVTTimeSlicedMainThreadWorkQueue _processWithDeadline:] (in DVTFoundation)
 20   -[_DVTTimeSlicedMainThreadActiveWorkQueues _processWorkQueuesOnDeadline] (in DVTFoundation)
 21   __NSFireDelayedPerform (in Foundation)
 22   __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ (in CoreFoundation)
 23   __CFRunLoopDoTimer (in CoreFoundation)
 24   __CFRunLoopDoTimers (in CoreFoundation)
 25   __CFRunLoopRun (in CoreFoundation)
 26   CFRunLoopRunSpecific (in CoreFoundation)
 27   +[DVTKVOConditionValidator waitForCondition:sourceObject:keyPathAffectingConditionBlock:timeout:] (in DVTFoundation)
 28   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
 29   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 30   main (in xcodebuild)
 31   start (in libdyld.dylib)
```

**Comment by MKGitHub** [comment]
Yeah the workspace will crash, but the projects can open. But then there are other compiler errors.
In cases like this it is quite abvious that a new version of Xcode/Swift would break. Just download and compile…

**Comment by dannymout** [comment]
@MKGitHub I'm not using cocoapods, so it's not a workspace... that's the error I get trying to build the framework w/carthage.

**Comment by MKGitHub** [comment]
@dannymout You get the workspace even with Carthage. Try to open and compile the workspace and all the projects manually – what happens?

**Comment by blommegard** [comment]
Open `Apollo.xcworkspace` in Xcode 10 and remove the reference to the `Configurations` folder in the bottom of the Project Navigator. Xcode 11 seems to have problems with that reference for some reason.
When removed Xcode 11 will build the project just fine without errors.

**Comment by MKGitHub** [comment]
No need to open it in Xcode 10 since you have Xcode 11 installed and set as current, switching back and forth is a pian in the …
Just edit the "contents.xcworkspacedata" and remove the file reference to the "Configurations" section.

**Comment by MKGitHub** [comment]
But Version 11.0 beta 3 (11M362v) break again…

**Comment by designatednerd** [comment]
Hey @MKGitHub @dannymout @blommegard are y'all still having these issues with lib version 0.13.0 and Xcode 11 b4? I was at least able to get the library building and passing tests on b4 yesterday, but it'd be helpful to know if you're still seeing problems (and if you are, if you're building with Carthage, Cocoapods, or something else).

**Comment by MKGitHub** [comment]
Building with Carthage = still problems

**Comment by MKGitHub** [comment]
> Hey @MKGitHub @dannymout @blommegard are y'all still having these issues with lib version 0.13.0 and Xcode 11 b4? I was at least able to get the library building and passing tests on b4 yesterday, but it'd be helpful to know if you're still seeing problems (and if you are, if you're building with Carthage, Cocoapods, or something else).

Building with Carthage = still problems

**Comment by designatednerd** [comment]
@MKGitHub Couple questions: 

- What libs are you trying to build, just `Apollo` or also `ApolloSQLite` and/or `ApolloWebSocket`? 
- What are the errors that you are receiving?

**Comment by blommegard** [comment]
Hi @designatednerd 

Everything seems to build just fine in Xcode 11 b4 as you said.

The problem now is when archiving using Carthage and seems to be related to this known issue in b4:
```
Targets that contain Swift code with the Enable Bitcode build setting set to Yes fail to link correctly when built with the Archive action. (52804818)
Workaround: Add a custom build setting with the name LD_VERIFY_BITCODE, and set it to NO. Make a note to yourself to delete this custom build setting once this issue is resolved.
```

Discussed here as well: https://github.com/Carthage/Carthage/issues/2825

**Comment by designatednerd** [comment]
@blommegard Thanks for sharing that link - gotta love beta season! 

@MKGitHub Any info on the issues you're having, or were the the same as @blommegard's?

**Comment by MKGitHub** [comment]
@designatednerd Same same, can you make a beta branch with the fix?

**Comment by designatednerd** [comment]
@MKGitHub @blommegard Correct me if I'm wrong, but the way I'm reading that I think you have to apply that at the application level, not at the library level

**Comment by designatednerd** [comment]
I'm going to close this out since we haven't seen new issues with b5 around this. If you're seeing issues with anything beyond b4, please open a new issue. Thank you!

**Comment by blommegard** [comment]
@designatednerd Yes, you are correct! 👍
