### ISSUE TITLE
GET request could be a fetch option

### ISSUE THREAD

**Issue by dmandarino** [apollographql/apollo-ios#570]
We are not able to use GET request as a fetch option like we do in others platforms. So, when we want to fetch information from an API that only allows this method, it fails. Also, we are not able to help API with cache, as most of them don't implement a specific header to allow cache with POST.

**Comment by dmandarino** [comment]
This was done in issue #572

**Comment by designatednerd** [comment]
Yep! Holding off on closing this until it gets released 🤓

**Comment by designatednerd** [comment]
Shipped with 0.11.0!
