### ISSUE TITLE
Codegen should handle Int32 JS limit better

### ISSUE THREAD

**Issue by CraigSiemens** [apollographql/apollo-ios#573]
On iOS `Int` defaults to `Int64` but Apollo Server only accepts `Int32`. If you try passing a int larger that what can fit in a `Int32`, Apollo Server will fail with an internal server error.

```
Int cannot represent non 32-bit signed integer value: 123412341234
```

**Comment by js** [comment]
Sadly the GraphQL spec specified that [integers should be 32 bits](https://graphql.github.io/graphql-spec/June2018/#sec-Int), because Javascript I suppose…

If the codegen was change to use Int32 it would be correct, but UX/ergonomics wise it would a regression as most interoperability with existing code would suffer, since most swift code would use `Int` and would have to attempt to convert it to `Int32`. Not sure what is worst, a `EXC_BAD_INSTRUCTION` crash or an http error if it doesn't fit into 32 bits?

**Comment by designatednerd** [comment]
I agree with @js - It'd be a pretty significant hit to usability to switch from `Int` to `Int32`. I might see if there's a way to add some kind of assertion failure or something though.

**Comment by designatednerd** [comment]
Any kind of validation on this is going to have to wait until we're doing codegen in Swift

**Comment by kevinmbeaulieu** [comment]
> Any kind of validation on this is going to have to wait until we're doing codegen in Swift

@designatednerd Do you mean for technical reasons or just prioritization? It'd be possible to add something like `assert(someInt.leadingZeroBitCount > 32)` to the getters/setters of `GraphQLInt`-type fields, right?

**Comment by designatednerd** [comment]
Mostly prioritization. It'd likely also add some significant overhead to add that validation on every single setter for `Int` properties, so I'd like to come up with a strategy that lets us do this a bit more cleanly. I think this'll be easier once the codegen is moved to swift, tbh.

**Comment by AnthonyMDev** [comment]
We've made the decision not to make the change to `Int32` for input values in the `1.0` release. The ergonomics/usability concerns came into consideration, but we also recognize that the 32 bit integer limitation is pretty artificial. Though this is a defined part of the specification, any server implementation in a language that handles 64 bit integers would have no problem accepting them from a client. By making this change, we would be imposing that limitation on everyone in a way that's not very flexible.

Furthermore, as @js questioned, we feel that the field error on a network response is a more desirable failure path than a runtime crash here.

We don't believe that changing this to use `Int32` is what benefits the majority of developers using our client most of the time. If you really want this change, please comment here and let us know! If there is support for it, I'd be willing to make this a configuration during code generation that you can opt into!
