### ISSUE TITLE
 Help with codegen swift

### ISSUE THREAD

**Issue by boardmain** [apollographql/apollo-ios#577]
hi all
im unable to create the code for this query
`
{
  search_cooker_near_user(args: {distance_kms: 100, userlocation: {type: "Point", coordinates: [44.712586, 10.232267]}}, limit: 10, offset: 0, order_by: {distance: asc}) {
    cooker {
      name
      photo
    }
    distance
    position
  }
}
`
codegen ignore it

can some one help?

**Comment by designatednerd** [comment]
@boardmain Does that query work in other GraphQL clients? If not, there are tools like [GraphiQL](https://github.com/graphql/graphiql) that can help you get that query sorted. 

If it does work in other clients, please let me know - that's a bug.

**Comment by designatednerd** [comment]
Hello! Since I haven't heard back on this question in a couple weeks I'm going to close it out - please feel free to reopen or open a new issue if you're still having problems!
