### ISSUE TITLE
Serializing an array using a `JSONObject` and `GraphQLResultReader`

### ISSUE THREAD

**Issue by attheodo** [apollographql/apollo-ios#58]
Hey,

I am in a position where I need to bridge the two worlds between custom, native objects and Apollo generated objects.

So at some point one of my native objects has a `[LinkedIdentity]?` property where `linkedIdentity` is actualy a `typealias` to Apollo's generated `GetLinkedIdentitiesQuery.Data.Me.LinkedIdentity.Record` struct.

This native object is getting serialized using Alamofire and custom serializers. So at some point I also need to serialize the `[LinkedIdentity]?` array from the received json representation that Alamofire gives me.

I know I am supposed to initialise a `GraphQLResultReader` at some point so I am doing something like `let graphQLResultReader = GraphQLResultReader(rootObject: linkedIdentitiesArray as! JSONObject)`

How can I utilize this `graphQLResultReader` object to return me `[LinkedIdentity]` ?

**Comment by martijnwalraven** [comment]
I'd like to better understand your use case before recommending a solution. `GraphQLResultReader` isn't really meant to be used directly, so maybe there is a better way of doing what you want.

> This native object is getting serialized using Alamofire and custom serializers. So at some point I also need to serialize the [LinkedIdentity]? array from the received json representation that Alamofire gives me.

Do you mean deserialized? Is the idea that have a blob of JSON and want to deserialize this into your own custom objects, which include a reference to `[LinkedIdentity]?`?

Does this JSON come from a GraphQL server? If so, why can't you use a query for this? Or does it come from somewhere else?

Why does the custom object need to contain `GetLinkedIdentitiesQuery.Data.Me.LinkedIdentity.Record` then,  instead of another custom object that isn't tied to a particular query response?

**Comment by attheodo** [comment]
Hey @martijnwalraven 

yes, sorry, I mean deserialized.

Here's the scenario: We have a core view controller that uses a custom-written `Album` object. This is getting deserialized by Alamofire which executes the GraphQL query to fetch the JSON. Currently we cannot afford to migrate this controller to Apollo so we need to stick with our custom `Album` model for a while.

In the meantime, we started using Apollo for some of our new features. One of which is a managing a list of `LinkedIdentity` objects, which like I mentioned is a `typealias` for an Apollo auto-generated model. 

Now currently, this `Album` object needs to include an array of `LinkedIdentity` as one of its properties. It needs to be of that type because related view controllers (created after experimenting with Apollo) expect it to be that way. 

So what we're trying to achieve here is have the `Album` object deserialize all its current properties the traditional, Alamofire way, but deserialize its `[LinkedIdentity]?` array, which is an Apollo-generated model, using `GraphQLResultReader` or something similar. 

Due to the struct chaining and significant use of fragments in `LinkedIdentity`, manually trying to deserialize `[LinkedIdentity]` using Alamofire's way will be too much work so we're thinking whether we can utilize some parts of the Apollo stuck to just deserialize that particular property of the model.

Does that make sense?

**Comment by martijnwalraven** [comment]
I see. That sounds like a complicated setup :) So hopefully it is temporary. You also miss out on features like caching of course.

Like I said, `GraphQLResultReader` isn't really meant to be used in this way, but I think something like this should work:

```swift
let reader = GraphQLReader(rootObject: ["linkedIdentities": linkedIdentitiesArray])
let linkedIdentities: [LinkedIdentity]? = try reader.optionalList(for: Field(responseName: "linkedIdentities"))
```

(Instead of `["linkedIdentities": linkedIdentitiesArray]`, you could also just pass in the JSON object that has the `linkedIdentities` field.)

**Comment by attheodo** [comment]
@martijnwalraven I guess I also have to modify my custom GraphQL query string to include `__typename` everywhere?

**Comment by martijnwalraven** [comment]
You may also want to think about using a fragment for `LinkedIdentity`, because in general you don't really want other parts of your app to rely on query-specific types.

**Comment by martijnwalraven** [comment]
Yes, `__typename` is required.

**Comment by attheodo** [comment]
@martijnwalraven I think I am getting closer. I've modified the query appropriately but I am getting a deserialization error from Apollo: https://gist.github.com/attheodo/7ea10fbc8ebc3c2857cfc372d9981a30

```
 let reader = GraphQLResultReader(rootObject: representation as! JSONObject)
 let linkedIdentities: [LinkedIdentity]? = try! reader.optionalList(for: Field(responseName: "selected_identities"))
```

Here `representation` is the whole JSON response and I am querying the reader for `selected_identities` which is the part I am interested in. 

Since you have the experience, maybe you have any idea on what's going wrong based on the error?

**Comment by martijnwalraven** [comment]
From your output it seems 'selected_identities' is not actually an array, but an object with a 'records' field.

**Comment by attheodo** [comment]
@martijnwalraven right, my bad. I had to drill down into `records` path. But hey, it worked 🎉

You just saved me at least a days work man. Thanks so much!
