### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by mohammedshahid** [apollographql/apollo-ios#593]
Hi Guys, 

Is there support for Swift 5 , if not please mention if it's in the timeline.
We want it to support SWIFT ABI in our app, which helps in reduction of app size.

**Comment by designatednerd** [comment]
@mohammedshahid: Yes! The lib is actually already migrated but a step got missed with updating the swift version in the Podspec. When #592 is merged, that should stop the whining from CocoaPods.

**Comment by designatednerd** [comment]
This is merged to master and will officially be released (probably early next week) with 0.11.0. Gonna close this one out.
