### ISSUE TITLE
support for swift package manager within xcode 11

### ISSUE THREAD

**Issue by acarrera94** [apollographql/apollo-ios#616]
As of Xcode 11 (which is currently in beta) swift package manager is embedded into xcode. 

I can add apollo ios as a dependency no problem but there is an issue while building. The script refers to "FRAMEWORK_SEARCH_PATHS". 

**Intended outcome**
Be able to use SPM within xcode to generate code. 

**Actual outcome**
> error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project.

I can change the script in Build Phases to:
``` 
SEARCH_FRAME_PATH="${FRAMEWORK_SEARCH_PATHS//\ }"
APOLLO_FRAMEWORK_PATH="$SEARCH_FRAME_PATH/../../../SourcePackages/checkouts/apollo-ios/scripts"
if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --queries="$(find . -name '*.graphql')" --schema=schema.json API.swift


```
also note that `FRAMEWORK_SEARCH_PATHS` is empty in build settings
This works, but it seems we need a new bash variable for swift package manager. 

**How to reproduce the issue**
add apollo ios to the project using xcode swift package manger dependencies and build.

**Comment by acarrera94** [comment]
Possibly related: https://github.com/apollographql/apollo-ios/issues/615

**Comment by designatednerd** [comment]
@acarrera94 Can you try it with the changes to the build script which were merged in #610 please and let me know the result?

**Comment by rygood** [comment]
The framework now gets added to the the project; but it still has issue building. See attached.
<img width="1381" alt="Screen Shot 2019-07-10 at 11 05 52 AM" src="https://user-images.githubusercontent.com/99569/60982745-b5fe8b80-a306-11e9-8a30-5e13bce4ba12.png">

**Comment by designatednerd** [comment]
Hmm, I bet there's a few things missing a `Foundation` import... I'll take a look!

**Comment by designatednerd** [comment]
Looks like #620 should address the foundation imports issue - let me know if there are still some missing!

**Comment by hfabisiak** [comment]
How should the script in build phases look like if I'm using Swift Package Manager and app is targeted for macOS and iOS?

**Comment by designatednerd** [comment]
@hfabisiak It *should* be able to use the same build phase as the carthage/drag-n-drop one [in the documentation](https://www.apollographql.com/docs/ios/installation/#if-youre-not-integrating-apollo-using-cocoapods). If it doesn't work can you please open a new issue?

**Comment by tyrong** [comment]
@designatednerd hey what was the outcome of this? Using the same build phases script from, still getting error `echo` "error: Couldn't find Apollo.framework in`

**Comment by designatednerd** [comment]
@tyrong Mind opening a new issue on that?
