### ISSUE TITLE
Generate Apollo GraphQL API script fails for project not using CocoaPods

### ISSUE THREAD

**Issue by gabrielvincent** [apollographql/apollo-ios#619]
The Run Script Phase necessary to compile the `schema.json` file and generate the API.swift file fails with the error:  
```Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project.```

I found that there is an extra space in the script that makes it fail. After removing the space, the build happens successfully:

This:
```bash
APOLLO_FRAMEWORK_PATH ="$(eval find ${QUOTED_FRAMEWORK_SEARCH_PATHS} -name "Apollo.framework" -maxdepth 1)"
```

Has to be changed to:
```bash
APOLLO_FRAMEWORK_PATH="$(eval find ${QUOTED_FRAMEWORK_SEARCH_PATHS} -name "Apollo.framework" -maxdepth 1)"
```

**Comment by designatednerd** [comment]
🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️

Have I mentioned recently I suck at bash? Oh wait, [yes I have](https://speakerdeck.com/designatednerd/thinking-outside-the-box-with-swift-package-manager-hacking-with-swift-live-bath-uk-july-2019?slide=31)!

I'll fix this in my open docs PR, good catch.
