### ISSUE TITLE
Regenerate API docs in markdown

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#622]
Our API docs used to point to CocoaDocs, which has been deprecated. We need to find a new way to output our documentation in Markdown to match our existing documentation style - it looks like [SourceDocs](https://github.com/eneko/SourceDocs) might be the way to go, but any other suggestions are welcome.

**Comment by kimdv** [comment]
I have used [Jazzy](https://github.com/realm/jazzy). 
It takes documentation from the code a generate a nice site. 💪

**Comment by designatednerd** [comment]
Yeah Jazzy's great if there's not already a system in place since it does all the CSS/HTML/JS stuff for you. 

However, we've got a system through our website that translates Markdown and puts it straight into the [iOS Docs site](https://www.apollographql.com/docs/ios/) automatically, so generating markdown is the preferred way to go for this project.

**Comment by designatednerd** [comment]
Opened a [PR on SourceDocs](https://github.com/eneko/SourceDocs/pull/20) to get the full behavior we're looking for.

**Comment by designatednerd** [comment]
Shipped with 0.13.0!
