### ISSUE TITLE
GET is not working in 0.11.0

### ISSUE THREAD

**Issue by dmandarino** [apollographql/apollo-ios#623]
GET method released in `0.11.0` is not passing variables correctly, so it always fails when you have a variable in your query.

**Comment by designatednerd** [comment]
@dmandarino Can you please give an example of how it's failing - is it a more complex variable that's not working or is it just a single variable?

**Comment by dmandarino** [comment]
@designatednerd Yes, of course! Sorry about it. 
I've just opened a PR proposing a solution. #624.

When we use GET with queryVariable the class `GraphQLGETTransformer` makes a cast of ```self.body.jsonObject[self.variablesKey] as? [String: AnyHashable]```. But if always fails and return the url as if there weren't any variable.

So the request fails and returns a BadRequest, as the server is expecting for variable such as ID.

```["Received error response (400 bad request): {\"errors\":[{\"message\":\"Variable \\\"$id\\\" of required type \\\"ID!\\\" was not provided```

**Comment by designatednerd** [comment]
Yeah that makes more sense. If you can add tests around that, it'd be super helpful.

**Comment by dmandarino** [comment]
Hi @designatednerd, do you have any idea will be the next release with this fix? 
I can't use 0.11.0 because of this error and I really need this GET feature :/

**Comment by designatednerd** [comment]
Will be in 0.12.0 - you can point Carthage or Cocoapods at the specific commit where this is fixed if you're really stuck in the meantime!
