### ISSUE TITLE
Update required Apollo CLI version to latest

### ISSUE THREAD

**Issue by interstateone** [apollographql/apollo-ios#637]
[scripts/check-and-run-apollo-cli.sh](https://github.com/apollographql/apollo-ios/blob/master/scripts/check-and-run-apollo-cli.sh#L2) specifies version 1.9.x of the Apollo CLI tools as a requirement of running codegen. The current version of this package is [2.15.0](https://www.npmjs.com/package/apollo). I would expect that the required version of apollo-ios is closer to the latest version (at least the same major version), in order to avoid potential issues due to using a later version in some contexts like downloading a schema and an older version for codegen. I don't have any evidence that this is occurring, and in fact it seems to work when used like this, but I'd like to rule it out. This would also avoid warnings about version mismatches emitted by check-and-run-apollo-cli.sh when the developer performs the most likely installation step to download a schema, which is `npm install apollo` without specifying a version.

**Comment by designatednerd** [comment]
Yeah absolutely this needs to get updated - I'm waiting for a couple changes to land in the Swift codegen on the CLI and then I'm going to update it. The CLI made some pretty significant changes while Apollo was a bit shorthanded on the iOS side, but that's why they hired me 😁

**Comment by designatednerd** [comment]
This was addressed by #647, and will ship with 0.13.0. I'll close this out as soon as that version ships.

**Comment by designatednerd** [comment]
This has shipped with 0.13.0!
