### ISSUE TITLE
"Downloading a schema" documentation is unclear which version of Apollo CLI should be used

### ISSUE THREAD

**Issue by interstateone** [apollographql/apollo-ios#638]
https://www.apollographql.com/docs/ios/downloading-schema/

The command provided on this page is `apollo schema:download`, and there aren't any details about what version to install here or on the [apollo-tooling](https://github.com/apollographql/apollo-tooling) page that's linked to.

It's not clear if the version that's used for downloading the schema is important or not (similar to #637), but following the installation steps given by apollo-tooling in order to download a schema will lead to scripts/check-and-run-apollo-cli.sh emitting warnings about a version mismatch when it generates code.

**Comment by designatednerd** [comment]
I can't say with 100% certainty but I would strongly suspect using the same version of the CLI as you're using to generate the code is probably going to run the smoothest.

**Comment by designatednerd** [comment]
I'm going to close this out as #637 has gotten us back on track with the current `apollo-tooling` CLI client. 

In the future if there's any divergence, I stand by `using the same version of the CLI as you're using to generate the code is probably going to run the smoothest.`
