### ISSUE TITLE
Remove graphql Test data from final Framework.

### ISSUE THREAD

**Issue by jtwigg** [apollographql/apollo-ios#64]
Can we remove the test graphql data from the framework?
Looks like it snuck in there.

![screen shot 2017-02-24 at 3 48 39 pm](https://cloud.githubusercontent.com/assets/1237233/23325257/f88bee06-faa8-11e6-9bca-7037800ca0c6.png)

**Comment by martijnwalraven** [comment]
Going to close this issue, because I believe this has been fixed in the latest version.
