### ISSUE TITLE
Clearing SQLite cache leaves traces of information

### ISSUE THREAD

**Issue by ZevEisenberg** [apollographql/apollo-ios#650]
Steps to reproduce:

1. Include the SQLite cache subspec in your Podfile like this: 
   ```ruby
   pod 'Apollo'
   pod 'Apollo/SQLite’
   ```
1. Create an Apollo Client like this:
    ```
   let store = ApolloStore(cache: try SQLiteNormalizedCache(fileURL: someURL))
   let client = ApolloClient(networkTransport: someTransport, store: store)
   ```

1. Run the app.
1. Before making any requests, observe the size of the cache SQLite file on disk. It’s probably about 20 KB.
1. Make some GraphQL requests.
1. Observe that the SQLite file has grown, let’s say to 100 KB.
1. Call `client.clearCache()`, which calls `store.clearCache()`, which calls `clearRecords()` on the SQLite cache, which calls `try db.run(records.delete())`.
1. Observe the size of the cache on disk. **It is still about 100 KB, possibly slightly larger, which is unexpected.**
1. Open the SQLite file in an SQLite editor, or dump the contents by opening the file with `sqlite3` in the command line, and calling `.dump`. Confirm that the file is empty.
1. Open the SQLite file in a hex editor such as [0xED](https://www.suavetech.com/0xed/). Observe that, in between large patches of repeated 0s, some of the original cached data remains.

This information is likely only accessible to someone with jailbreak-level access to a device, but it still constitutes leaking potentially sensitive information. I think it would be smart to do a more complete deletion of the data. The two ways that come to mind are:

1. Delete the SQLite file. I tried doing this in my app, but it looks like either the SQLite library or SQLiteNormalizedCache don't like that, and I get a disk I/O error on Statement.swift:211 in `return try! failableNext()`. I also get this log in the console when deleting the cache from my app code:
   ```
   2019-07-19 20:34:44.567841-0400 MY_APP_NAME[32035:887909] [logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/zeisenberg/Library/Developer/CoreSimulator/Devices/459E64B9-C609-4DDB-B3B1-BEBB1F0CFD30/data/Containers/Data/Application/4546EB4D-6DE7-4239-838D-C7BF9C0015E6/Library/Caches/ApolloGraphQLCache.sqlite
   2019-07-19 20:34:44.567963-0400 MY_APP_NAME[32035:887909] [logging] invalidated open fd: 6 (0x11)
   ```
   So, it looks like we'll have to handle the database file a little more carefully if we go this route, closing the old connection before opening a new one. This is likely what I'll do as a workaround if a fix doesn't show up in Apollo in time.
1. Use the [`VACUUM;`](https://www.sqlite.org/lang_vacuum.html) SQLite command. This clears out the information, but it's also likely the slower of these two options.

**Comment by designatednerd** [comment]
Optional support for `VACUUM;` has shipped with 0.13.0 - please open a new issue if there are any additional problems. Thank you!
