### ISSUE TITLE
Can not build project, run script fails

### ISSUE THREAD

**Issue by Dino4674** [apollographql/apollo-ios#656]
I am following instructions on: https://www.apollographql.com/docs/ios/installation/

I installed newest Apollo pod (0.12.0)
I installed apollo version 1.9.0 so that I don't get another version installed locally in my Xcode project.

I added new run script phase as described but I am getting this issue:

```
 Warning: apollo update available from 1.9.0 to 2.16.0.
++ npx --no-install apollo codegen:generate --target=swift '--includes=./*.graphql' --localSchemaFile=schema.json API.swift
 ›   Warning: apollo update available from 1.9.0 to 2.16.0.
 ›   Error: Unexpected arguments: --localSchemaFile=schema.json, API.swift
 ›   See more help with --help
```

I tried multiple Apollo pod versions and Apollo CLI versions and can not make it to work.
What is the current working Apollo pod/CLI version? Thanks

**Comment by designatednerd** [comment]
Ah yeah - you need the 1.9.x version until `0.13.0` is released. [Here is the documentation as of when `0.12.0` was released](https://github.com/apollographql/apollo-ios/blob/0.12.0/docs/source/installation.md#adding-a-code-generation-build-step) - that should work a lot better. 

Sorry, updated those docs at the same time as I updated stuff that's going out with 0.13.0 but it's not shipped yet!

**Comment by Dino4674** [comment]
Thanks for the response!
I got it working now and have API.swift file generated. Only difference was in the run script.
I can continue my GraphQL tutorial now :D

**Comment by designatednerd** [comment]
Hooray! I'm going to leave this open until 0.13.0 ships for anyone else who runs into the same problem

**Comment by rafalur** [comment]
@designatednerd I'm facing same issue. When do you plan to release 0.13.0?

**Comment by designatednerd** [comment]
Shooting for tomorrow (23 July), but that depends on finishing up a couple PRs that are tagged with the `0.13.0` tag - those same instructions should get you up and running as well.

**Comment by dmandarino** [comment]
Same here

**Comment by designatednerd** [comment]
@dmandarino Are you able to build with the [instructions from 0.12.0](https://github.com/apollographql/apollo-ios/blob/0.12.0/docs/source/installation.md#adding-a-code-generation-build-step)?

**Comment by dmandarino** [comment]
@designatednerd this one worked for me. But I had to uninstall apollo, install 1.9. Then, using those [instructions from 0.12.0](https://github.com/apollographql/apollo-ios/blob/0.12.0/docs/source/installation.md#adding-a-code-generation-build-step) it worked. But if I update apollo to 2.14 it doesn't work. Also, if I follow [this Apollo's doc](https://www.apollographql.com/docs/ios/installation/) it doesn't work as well.

**Comment by designatednerd** [comment]
Yeah this one's on me - in the future I'll make sure to leave old docs up, especially around build stuff, until the new stuff ships. Got a couple more things I'm going to try to shove in 0.13.0 tomorrow morning but then I'm shipping it and everything will be on the same page.

**Comment by designatednerd** [comment]
0.13.0 is now available! Closing this out, please open a new issue if you're still having problems with 0.13.0!
