### ISSUE TITLE
Build issues with 0.13.0

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#661]
@victormihaita was reporting some issues in #660 that I think are different than the main issue in that thread. This is his build script:

```
QUOTED_FRAMEWORK_SEARCH_PATHS=\"$(echo $FRAMEWORK_SEARCH_PATHS | tr -d '"' | sed -e 's/ \//" "\//g')\"

APOLLO_FRAMEWORK_PATH="$(eval find ${QUOTED_FRAMEWORK_SEARCH_PATHS} -name "Apollo.framework" -maxdepth 1 -print | head -n 1)"

if [ -z "${APOLLO_FRAMEWORK_PATH}" ]; then
  echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
  exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
"${APOLLO_FRAMEWORK_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./*.graphql --localSchemaFile="Sources/API/Generated/schema.json" --passthroughCustomScalars Sources/API/Generated/API.swift
```

He also [says](https://github.com/apollographql/apollo-ios/issues/660#issuecomment-514227975):
> I get the same error by modifying the build phase. We have many .graphql files and it used to work before updating the pod and the build phase.

**Comment by designatednerd** [comment]
@victormihaita Can you add a couple details: 

- Are you using Carthage or drag-n-drop to integrate? Instructions for [Cocoapods](https://www.apollographql.com/docs/ios/installation/#if-you-are-integrating-apollo-using-cocoapods) are pretty obviously different so I'm assuming that's not how you're integrating, but if you are, you should definitely follow those instructions instead. 
- What is the exact error you're getting? There were a couple different ones referred to in the other issue and I'd like to be clear on what's not working for you.

**Comment by victormihaita** [comment]
I don't use Carthage and the error is:
```
 It looks like there are 0 files associated with this Apollo Project. This may be because you don't have any files yet, or your includes/excludes fields are configured incorrectly, and Apollo can't find your files. For help configuring Apollo projects, see this guide: https://bit.ly/2ByILPj
Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
Generating query files with 'swift' target [failed]
→ No operations or fragments found to generate code for.
Error: No operations or fragments found to generate code for.
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:61:39)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:86:46)

```

**Comment by designatednerd** [comment]
@victormihaita Are you using the manual integration then? 

If you add an `echo $(pwd)` right before the last line, are you getting the correct directory that holds (directly or indirectly) all of your GraphQL files?

**Comment by victormihaita** [comment]
I get the root path to my project if I run `echo $(pwd)`
- My .graphql files are  the root project under this path:
`Root/Sources/Architecture/Data/GraphQL`

**Comment by victormihaita** [comment]
I found the issue. If I switch to this it will work:
`--includes=./Sources/Architecture/Data/GraphQL/*.graphql`

**Comment by victormihaita** [comment]
But in my case, the GraphQL folder includes other folders that have .graphql files.
If I include this: `--includes=./Sources/Architecture/Data/GraphQL/*.graphql` it's not going to work, because the .graphql file is still under a child folder.

**Comment by victormihaita** [comment]
so the issue is that the script is not searching under the child folders, and instead is finding only the direct .graphql files in a directory

**Comment by designatednerd** [comment]
Hm - I don't think that's intended behavior, I'm pretty sure the glob is supposed to search child directories as well. I'll ping the CLI team and see what I can figure out.

**Comment by JakeDawkins** [comment]
Hi @victormihaita 👋 Can you try changing your glob to use `**` like `--includes=./Sources/Architecture/Data/GraphQL/**/*.graphql`? 

I _think_ that's the issue you're having. The glob you have only searches that one folder, the `**` is to search all folders under that path. 

Alternatively, you could probably also use `--includes=./**/*.graphql` or `--includes=**/*.graphql` as long as there are no stray graphql lying around the project.

**Comment by victormihaita** [comment]
@JakeDawkins All the solutions that you provided worked. Thank you :) 
@designatednerd Thanks for the support. Keep up the great work!

**Comment by designatednerd** [comment]
Updated the glob in #662 to make sure it searches recursively

**Comment by designatednerd** [comment]
Gonna close this out since that's now merged to master and live in the documentation. Please feel free to reopen if you run into further issues!
