### ISSUE TITLE
Can't access result from mutation

### ISSUE THREAD

**Issue by akhilpothana** [apollographql/apollo-ios#663]
I am trying to make a simple mutation to register a user. When I call `.perform(mutation: GraphQLMutation)`, it works and a user is created in the database. I'm trying to now get information back from the server using the code below.

```
import Apollo

let userRegistrationInfo = RegisterMutation(email: email, name: fullName, username: username, uid: uid)
                ApolloClass.shared.client.perform(mutation: userRegistrationInfo) { result in
                    print(result?.data?.register?.id)
                }
```

When I only access and print `result` in my mutation call, this is the data I get back, so I know I'm getting something: 

> success(Apollo.GraphQLResult<JoinMi.RegisterMutation.Data>(data: Optional(JoinMi.RegisterMutation.Data(resultMap: ["register": Optional(["id": Optional("cjygbypjn59zt08668k7ktf6b"), "token": Optional("5jG6jbgb5dVy4ilrBLceKHCZmrS2"), "username": Optional(""), "name": Optional(""), "__typename": Optional("User")])])), errors: nil, source: Apollo.GraphQLResult<JoinMi.RegisterMutation.Data>.Source.server, dependentKeys: Optional(Set(["MUTATION_ROOT.register(email:helo@helo.com,name:,uid:5jG6jbgb5dVy4ilrBLceKHCZmrS2,username:).username", "MUTATION_ROOT.register(email:helo@helo.com,name:,uid:5jG6jbgb5dVy4ilrBLceKHCZmrS2,username:).name", "MUTATION_ROOT.register(email:helo@helo.com,name:,uid:5jG6jbgb5dVy4ilrBLceKHCZmrS2,username:).id", "MUTATION_ROOT.register(email:helo@helo.com,name:,uid:5jG6jbgb5dVy4ilrBLceKHCZmrS2,username:).__typename", "MUTATION_ROOT.register(email:helo@helo.com,name:,uid:5jG6jbgb5dVy4ilrBLceKHCZmrS2,username:)", "MUTATION_ROOT.register(email:helo@helo.com,name:,uid:5jG6jbgb5dVy4ilrBLceKHCZmrS2,username:).token"]))))

But when I try to access any of the data (e.g. `result?.data?.register?.id`) I get this error: 
> Generic parameter 'Mutation' could not be inferred

Here's my mutation: 
```
mutation register($email: String!, $name: String, $username: String, $uid: String!) {
    register(email: $email, name: $name, username: $username, uid: $uid) {
        id
        name
        username
        token
    }
}
```

This is ApolloClass:
```
import Foundation
import Apollo

class ApolloClass {
    static let shared = ApolloClass()
    
    private(set) lazy var client = ApolloClient(url: URL(string: "...")!)
    
}
```

There has to be something I'm missing in the way I'm trying to access the contained data

**Comment by casey-chow** [comment]
Are you on 0.13.0? If so, see [release notes](https://github.com/apollographql/apollo-ios/releases/tag/0.13.0):

> - SUPER-BREAKING: Updated a ton of completion closures that could use it to use Result instead of optional parameter / optional error. (#644). There are a few details to this one to be particularly aware of:
>      -   If you see a bunch of Swift build errors that are claiming Generic Parameter "Query" could not be inferred, that means you need to update your completion closure to take the single Result<Parameter, Error> parameter instead of the two (Parameter?, Error?) parameters.

**Comment by akhilpothana** [comment]
> Are you on 0.13.0? If so, see [release notes](https://github.com/apollographql/apollo-ios/releases/tag/0.13.0):
> 
> > * SUPER-BREAKING: Updated a ton of completion closures that could use it to use Result instead of optional parameter / optional error. (#644). There are a few details to this one to be particularly aware of:
> >   
> >   * If you see a bunch of Swift build errors that are claiming Generic Parameter "Query" could not be inferred, that means you need to update your completion closure to take the single Result<Parameter, Error> parameter instead of the two (Parameter?, Error?) parameters.

Ugh this must be it. I was reading the notes earlier in relation to a build issue I was having and totally missed this bullet point. I will try this out. Thank you!

**Comment by designatednerd** [comment]
@akhilpothana please let me know if this worked!

**Comment by designatednerd** [comment]
Given that this is covered in the release notes for `0.13.0`, I'm gonna close this one out. Please reopen if you're still having problems!

**Comment by akhilpothana** [comment]
@designatednerd sorry! yes that was the issue. All fixed!

**Comment by designatednerd** [comment]
Awesome, thanks for letting us know!
