### ISSUE TITLE
upload Multi Part file 

### ISSUE THREAD

**Issue by emanShedeed** [apollographql/apollo-ios#677]
![Screen Shot 2019-07-29 at 8 53 09 AM](https://user-images.githubusercontent.com/42905983/62030900-6107b400-b1e6-11e9-8c10-8541ca406eb1.png)
![Screen Shot 2019-07-29 at 8 54 36 AM](https://user-images.githubusercontent.com/42905983/62030913-68c75880-b1e6-11e9-98ff-3ff26c351c7b.png)
how can I send graphql file to the mutation and how it expects string?

**Comment by designatednerd** [comment]
Right now this is not supported - the multi-part file upload is following [the GraphQL multi-part request spec](https://github.com/jaydenseric/graphql-multipart-request-spec) where you'd need to create a separate mutation for just the `profile_image`. 

I am going to tag this as an enhancement though - it does seem like a reasonable thing to add support for, I just need to look a bit deeper into *how* to do that.

**Comment by designatednerd** [comment]
OK I *think* with #707 this should now be supported way better. Please take a look at that PR and let me know if you have questions.

**Comment by designatednerd** [comment]
Significant improvements to both this and the documentation have shipped with `0.15.0`. If you're still having problems after upgrading, please open a new issue. Thank you!
