### ISSUE TITLE
Version too old for Codegen to work

### ISSUE THREAD

**Issue by halonsoluis** [apollographql/apollo-ios#680]
In check-and-run-apollo-cli.sh the required version of Apollo is set to 1.9, this version is not aware of some of the changes done in the CLI. Is just too old.

> 
>    3.8066s   warning: Installing apollo@1.9 in your project directory to avoid version conflicts...
>    0.0002s   + apollo@1.9.2
>    0.0004s   added 22 packages from 13 contributors and audited 8442 packages in 2.857s
>    0.0001s   found 128 high severity vulnerabilities
> ++ npx --no-install apollo codegen:generate --target=swift '--includes=../External/graphql/**/*.graphql' --localSchemaFile=../External/graphql/schema.json --passthroughCustomScalars --mergeInFieldsFromFragmentSpreads ../Generated/graphql/
>  ›   Warning: apollo update available from 1.9.2 to 2.16.3.
>  ›   Error: Unexpected arguments: 
>  ›   --localSchemaFile=../External/graphql/schema.json, ../Generated/graphql/

Updating this line to 2.16 fixes the issues:

> ++ npx --no-install apollo codegen:generate --target=swift '--includes=../External/graphql/**/*.graphql' --localSchemaFile=../External/graphql/schema.json --passthroughCustomScalars --mergeInFieldsFromFragmentSpreads ../Generated/graphql/
>    2.9272s   Generate Apollo is enabled, commencing...
>    0.0058s   Loading Apollo Project [started]
>    0.0007s   Loading Apollo Project [completed]
>    0.0003s   Generating query files [started]
>    1.3724s   Generating query files with 'swift' target [title changed]
>    0.0001s   Generating query files with 'swift' target - wrote 81 files [title changed]

**Comment by designatednerd** [comment]
Hello! This should have been addressed in `0.13.0` - what version are you using, and how are you integrating it?

**Comment by halonsoluis** [comment]
It looks like I'm used an old version (0.11.1). 
Just noticed when trying to create a PR.

**Comment by designatednerd** [comment]
OK! If this is working for you with `0.13.0`, do you mind closing this out?

**Comment by halonsoluis** [comment]
Tested, Working, closed 😉
Thanks for such a fast support 💪🏻
