### ISSUE TITLE
Error when using useGETForQueries

### ISSUE THREAD

**Issue by mariorsjr** [apollographql/apollo-ios#683]
Developing for WatchOS 6, when I use 
`private lazy var networkTransport = HTTPNetworkTransport(
        url: URL(string: self.graphQLEndpoint)!,
        useGETForQueries: true
    )`
`private(set) lazy var client = ApolloClient(networkTransport: self.networkTransport)`

I am receiving the following error when I try to fetch: 
`... /Pods/Apollo/Sources/Apollo/GraphQLGETTransformer.swift, line 50`

**Comment by mariorsjr** [comment]
The issue was in another file of my project. 
Sorry for that

**Comment by designatednerd** [comment]
No worries, thanks for closing it for me 😄
