### ISSUE TITLE
Apollo iOS Guide

### ISSUE THREAD

**Issue by JakeTorres** [apollographql/apollo-ios#684]
URL: https://www.apollographql.com/docs/ios/initialization/#example-advanced-client-setup

// MARK: - Retry Delegate

extension Apollo: HTTPNetworkTransportRetryDelegate {

  func networkTransport(_ networkTransport: HTTPNetworkTransport,
                        receivedError error: Error,
                        for request: URLRequest,
                        response: URLResponse?,
                        retryHandler: @escaping (_ shouldRetry: Bool) -> Void) {
    // Check if the error and/or response you've received are something that requires authentication
    guard UserManager.shared.requiresReAuthentication(basedOn: error, response: response) else {
      // This is not something this application can handle, do not retry.
      shouldRetry(false)
    }
    
    // Attempt to re-authenticate asynchronously
    UserManager.shared.reAuthenticate { success in 
      // If re-authentication succeeded, try again. If it didn't, don't.
      shouldRetry(success)
    }
  }
}

where can I get the "UserManager" ,can't get it in Apollo?

**Comment by designatednerd** [comment]
As the top of that section says: `This code assumes you've got the following external classes:`. This is something the example code is assuming you are providing on your end. 

You're not the first person to ask about this, I'll make it clearer in the docs.

**Comment by designatednerd** [comment]
Updated to read `This code assumes you've got the following classes in your own code (these are **not** part of the Apollo library):`

**Comment by JakeTorres** [comment]
get it, thanks 
maybe I can do it from Alamofire

**Comment by designatednerd** [comment]
I don't think Alamofire provides those classes either - since those are logic that's specific to your app, they'd usually be coming from your own code.

**Comment by JakeTorres** [comment]
I get other problem that "(lldb) po error.localizedDescription
"Error at path \"getCurrPositionList.data.pagerInfo.total)\": couldNotConvert(value: 0, to: Swift.String)""
same api web is work but iOS not with swift request!

**Comment by designatednerd** [comment]
That's likely related to something that's going to go in with #402 if you're using `--passthroughCustomScalars`. Right now it's trying to convert everything to a `String` but it is valid GQL to have the underlying value be an `Int`. That PR will allow correct parsing of things returned as an `Int`.

**Comment by JakeTorres** [comment]
Sript phase: SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --passthroughCustomScalars --localSchemaFile="schema.json" API.swift

I do it in: JSONStandardTypeConversions
typealias Long = Int64
extension Long: JSONDecodable, JSONEncodable {
    public init(jsonValue value: JSONValue) throws {
        guard let number = value as? NSNumber else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Int64.self)
        }
        self = number.int64Value
    }
    
    public var jsonValue: JSONValue {
        return self
    }
}

but run API.Swift get an error: Use of unresolved identifier 'Long'

who can tell me what wrong with that?

**Comment by designatednerd** [comment]
@JakeTorres You should not need to create a separate `typealias`, in theory the codegen should treat `Long` as a custom scalar and generate code for it.

Do you mind moving this thread over to our [Spectrum chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) and tagging me on there? We can take a look at some possibilities of what's going wrong. Thank you!

**Comment by JakeTorres** [comment]
thanks a lot! I create a new file and custom the Long class, everything is ok when  get it in API.swift and run it

public class Long: JSONDecodable, JSONEncodable {
    required public init(jsonValue value: JSONValue) throws {
        guard let _ = value as? Int64 else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Int64.self)
        }
        guard let _ = value as? Int32 else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Int32.self)
        }

    }

    public var jsonValue: JSONValue {
        return self
    }
}

as above, Can this solve the problem?

**Comment by designatednerd** [comment]
You should not have to create a file for the `Long` class,  the codegen should create that custom scalar for you. If you create a file for it, it will probably conflict with the generated code. 

Please ask any further questions on our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts). Thank you!
