### ISSUE TITLE
Perform mutation: Returning GraphQLSelectionSet in a generic way

### ISSUE THREAD

**Issue by gmoraleda** [apollographql/apollo-ios#694]
I'm trying to create a function to retrieve the correct `Mutation` according to different cases in an enum.
I'm having problems declaring it in a generic way. This is the function where I switch the parameter `type` and return the appropriate function.

```swift
internal func link(files: [String], type: NeededDocument) -> Single<GraphQLSelectionSet> {
        let userId = UserManager.sharedInstance.userId!
        switch type {
        case .driversLicense:
            let mutation = AddDriversLicenseDocumentsMutation(cnId: userId, files: files)
            return Apollo.sharedInstance.perform(mutation: mutation)
        case .incomeProof,
             .incomeProofFreelancerFirst,
             .incomeProofFreelancerSecond,
             .businessRegistration:
            let mutation = AddProofOfIncomeDocumentsMutation(cnId: userId, files: files)
            return Apollo.sharedInstance.perform(mutation: mutation)
        case .additionalIncome:
            let mutation = AddProofOfOtherIncomeDocumentsMutation(cnId: userId, files: files)
            return Apollo.sharedInstance.perform(mutation: mutation)
        }
    }
```

I wrote an RxSwift wrapper around Apollo using the same signature for `perform` and `fetch`:
```swift
internal func perform<Mutation: GraphQLMutation>(mutation: Mutation, context: UnsafeMutableRawPointer? = nil, queue: DispatchQueue = DispatchQueue.main) -> Single<Mutation.Data>
```

If my return type for the link function is `Single<GraphQLSelectionSet>`, I get an error saying that it cannot convert `AddDriversLicenseDocumentsMutation.Data` / `AddProofOfIncomeDocumentsMutation.Data` / `AddProofOfOtherIncomeDocumentsMutation.Data` to `GraphQLSelectionSet`, although if I check the mutations, `Data` conforms to `GraphQLSelectionSet`.

If I try to define the return type as `GraphQLOperation.Data`, the compiler says that **Associated type 'Data' can only be used with a concrete type or generic parameter base.**

Is there a way to abstract the return type from different mutations?

**Comment by designatednerd** [comment]
So it looks like the `link` method doesn't have a generic type the way the `perform` method does, so it can't return `Mutation.Data` directly . What happens if you change the signature to: 

```swift
internal func link<Mutation: GraphQLMutation>(files: [String], type: NeededDocument) -> Single<Mutation.Data> {
```

**Comment by gmoraleda** [comment]
It complains: Mutation is not used in the function signature :-(

**Comment by designatednerd** [comment]
That seems real weird, since it returns `Single<Mutation.Data>` - did you update the return value as well?

**Comment by gmoraleda** [comment]
Yes, I did:
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/25835012/62566787-1511da80-b88a-11e9-8cfa-8db780033515.png">

**Comment by designatednerd** [comment]
What's going on with the `->` character there? is that a custom operator?

**Comment by gmoraleda** [comment]
Is just the font type ([FiraCode](https://github.com/tonsky/FiraCode)). Sorry about that :-)

**Comment by designatednerd** [comment]
OK! just wanted to rule that out as a possibility. 

I just realized why that won't work though: Because it'd require you to know what the mutation was when you called the function, which is explicitly what you don't want.

I'm still not sure why `Single<GraphQLSelectionSet>` doesn't work, the `associatedType` declaration indicates that `Data` must conform to `GraphQLSelectionSet. I'll have to take another look in the morning.

**Comment by designatednerd** [comment]
Apologies, I got sidetracked today. Will take a look in the morning!

**Comment by gmoraleda** [comment]
No worries. We got it working writing a second perform function, where we return `GraphQLSelectionSet`:
```swift
    internal func performMutation<Mutation: GraphQLMutation>(mutation: Mutation, context: UnsafeMutableRawPointer? = nil, queue: DispatchQueue = DispatchQueue.main) -> Single<GraphQLSelectionSet>
```
It's redundant, but it works... 🤷‍♂ 
Our link function now looks like this:

```swift
    internal func link(urls: [URL?], type: NeededDocument) -> Single<GraphQLSelectionSet> {
        guard let userId = UserManager.sharedInstance.userId else { return Single.error(Error.invalid(message: "invalid user id")) }
        let paths = urls.compactMap { $0?.absoluteString.split(separator: "?").first }.map { String($0) }

        switch type {
        case let .signature(dealId):
            guard let path = paths.first else { return Single.error(Error.invalid(message: "invalid path")) }
            let mutation = SignDealMutation(cnId: userId, dealId: dealId, file: path)
            return Apollo.sharedInstance.performMutation(mutation: mutation)

        case .driversLicense:
            let mutation = AddDriversLicenseDocumentsMutation(cnId: userId, files: paths)
            return Apollo.sharedInstance.performMutation(mutation: mutation)

        case .incomeProof,
             .incomeProofFreelancerFirst,
             .incomeProofFreelancerSecond,
             .businessRegistration:
            let mutation = AddProofOfIncomeDocumentsMutation(cnId: userId, files: paths)
            return Apollo.sharedInstance.performMutation(mutation: mutation)

        case .additionalIncome:
            let mutation = AddProofOfOtherIncomeDocumentsMutation(cnId: userId, files: paths)
            return Apollo.sharedInstance.performMutation(mutation: mutation)
        }
    }
```

I still wonder why returning `Mutation.Data` doesn't conform to `GraphQLSelectionSet`...

**Comment by designatednerd** [comment]
Ah nice! I suspect there's some awkwardness with the compiler just not quite putting all the generics and protocols together without that little bit of help you're giving it to get it to go "OH, _that_'s what you're trying to do!"

I'm going to close this out since there's now a workaround available.

**Comment by gantaa** [comment]
@gmoraleda.  Thanks for this thread.  Would you mind sharing the body of your `performMutation` function?  I am trying to write similar `performQuery` and `performMutation` utils.  How are you able to return `Single<GraphQLSelectionSet>` if the `GraphQLSelectionSet` doesn't exist until after an asynchronous GQL operation (in success callback)?

**Comment by gmoraleda** [comment]
Here you are @gantaa:
```swift
public func perform<Mutation: GraphQLMutation>(mutation: Mutation, publishResultToStore: Bool = true, queue: DispatchQueue = DispatchQueue.main) -> Single<Mutation.Data> {
    return Single.create(subscribe: { observer -> Disposable in
        let cancellable = self.apolloClient.perform(mutation: mutation, publishResultToStore: publishResultToStore, queue: queue, resultHandler: { result in
            switch result {
            case let .success(response):
                self.success(response: response, operationName: mutation.operationName, observer: observer)
            case let .failure(error):
                observer(.failure(error))
            }
        })

        return Disposables.create {
            cancellable.cancel()
        }
    })
}

public func success<Element: GraphQLSelectionSet>(response: GraphQLResult<Element>, operationName: String, observer: (SingleEvent<Element>) -> Void) {
    // ResultMap
    if
        let data = response.data,
        let mutationResultMap = data.resultMap[operationName.lowercasedFirstLetter()] as? ResultMap,
        let errors = mutationResultMap["errors"] as? [String],
        errors.isEmpty == false
    {
        observer(.failure(Error.failure))
        return
    }

    // Success
    if let data = response.data {
        observer(.success(data))
    }
}
```
