### ISSUE TITLE
Cached responses yield `412 Precondition Failed`

### ISSUE THREAD

**Issue by davidmuzi** [apollographql/apollo-ios#70]
I created an app using Githubs API, and noticed that the default cache policy was preventing all but the first request to succeed.  

Failed response:
```
<NSHTTPURLResponse: 0x610000039940> { URL: https://api.github.com/graphql } { status code: 412, headers {
    "Access-Control-Allow-Origin" = "*";
    "Access-Control-Expose-Headers" = "ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval";
    "Cache-Control" = "private, max-age=60, s-maxage=60";
    "Content-Length" = 0;
    "Content-Security-Policy" = "default-src 'none'";
    "Content-Type" = "text/html;charset=utf-8";
    Date = "Thu, 09 Mar 2017 14:27:52 GMT";
    Etag = "\"4853e207b0ae85065437a2f600a2d1aa\"";
    Server = "GitHub.com";
    Status = "412 Precondition Failed";
    "Strict-Transport-Security" = "max-age=31536000; includeSubdomains; preload";
    Vary = "Accept, Authorization, Cookie, X-GitHub-OTP";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = deny;
    "X-GitHub-Request-Id" = "CF6E:32C5:2B947BF:3797DE8:58C16668";
    "X-RateLimit-Limit" = 200;
    "X-RateLimit-Remaining" = 195;
    "X-RateLimit-Reset" = 1489072275;
    "X-XSS-Protection" = "1; mode=block";
} }
```

If I set `configuration.requestCachePolicy = .reloadIgnoringLocalCacheData` the issue goes away

https://github.com/davidmuzi/graphql-ios-presentation/blob/2-queries/Projects/Projects/MasterViewController.swift#L25 (edited)

The httpBody and requestHeaders appear identical before the sessionTask is executed

**Comment by martijnwalraven** [comment]
See ongoing discussion at the [GitHub forum](https://platform.github.community/t/executing-a-request-again-results-in-412-precondition-failed/1456).

We should probably either disable HTTP caching by default or find a way to deal with `412` responses ourselves.

**Comment by davidmuzi** [comment]
Will be addressed on Github https://platform.github.community/t/executing-a-request-again-results-in-412-precondition-failed/1456/10?u=davidmuzi
