### ISSUE TITLE
Unable to conform to `NetworkTransport`

### ISSUE THREAD

**Issue by sashaweiss** [apollographql/apollo-ios#701]
In a very weird situation, feels like a Swift type-checker bug - I am unable to conform to the `NetworkTransport` protocol.

Using Apollo 0.14.0, Xcode 10.2.1, in a Swift 5 project, the following code:

```swift
class Foo: NetworkTransport {
    func send<Operation>(operation: Operation, completionHandler: @escaping (Result<GraphQLResponse<Operation>, Error>) -> Void) -> Cancellable where Operation : GraphQLOperation {
        return EmptyCancellable()
    }
}
```

is getting a "Type 'Foo' does not conform to protocol 'Network Transport'" error - but the signature in that snippet was autogenerated by the "insert stubs" quickfix after creating the empty `Foo` class.

![image](https://user-images.githubusercontent.com/9013117/62737534-dc3a4880-b9e4-11e9-9916-2891463e9a73.png)

![image](https://user-images.githubusercontent.com/9013117/62737571-ea886480-b9e4-11e9-9df6-57904d80a0fb.png)

I wonder if this is related to the fact that `NetworkTransport` specifies an `Operation` type parameter that's implicitly constrained by its usage in the `GraphQLResponse` parameter to the `send` method, but not explicitly constrained? I tried tweaking it in my local (Pod-installed) copy of Apollo, as well as playing with the Swift versions, but having no luck.

Any ideas?

**Comment by sashaweiss** [comment]
Update: I was shadowing an Apollo type:
```swift
public protocol Cancellable: Apollo.Cancellable {}
```
in an (apparently misguided) attempt to "re-export" as part of the Pod I'm writing..._not doing_ that seems to fix this problem, which tbh makes sense since `Cancellable` is part of the signature of `send`.

Doing:
```swift
class Foo: NetworkTransport {
    func send<Operation>(operation: Operation, completionHandler: @escaping (Result<GraphQLResponse<Operation>, Error>) -> Void) -> Apollo.Cancellable where Operation: GraphQLOperation {
        return EmptyCancellable()
    }
}
```
works.

**Comment by designatednerd** [comment]
@sashaweiss Thanks for posting your solution!
