### ISSUE TITLE
Xcode 10 server bot: Apollo iOS requires version 2.16.x of the Apollo CLI to be installed either globally or in a local node_modules directory.

### ISSUE THREAD

**Issue by gaoshanyu** [apollographql/apollo-ios#702]
I tried use Xcode server bot for CI, but bot response me Apollo missing: 

> Apollo iOS requires version 2.16.x of the Apollo CLI to be installed either globally or in a local node_modules directory.

I can use Xcode to build my project succeed, please help to find the root cause, thank you so much.

Environment:
Xcode: 10.3

```
➜  ~ swift --version
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.7.0

➜  ~ apollo --version
apollo/2.16.1 darwin-x64 node-v10.15.0
```

I use CocoaPods to manage the framework:
```
pod 'Apollo', '~> 0.13.0'
pod 'Apollo/SQLite'
```

Apollo Api Generate Script:
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
TARGET_PATH="${SRCROOT}/MyApp/Networking/ApolloAPI/GraphQL"
cd "${TARGET_PATH}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=*.graphql --localSchemaFile="schema.json" ../API.swift
```

**Comment by designatednerd** [comment]
It should give you a warning about that and then try to install it locally - does it refuse to install locally? If so, maybe give `npm install apollo -g` a try on the Xcode bots machine.

**Comment by gaoshanyu** [comment]
@designatednerd Hi Ellen, thank you for the very quickly reply. I did use the command for my iMac which I used for Xcode Server Bot: 
`
> $ npm install -g apollo
`

It's different with `npm install apollo -g`? I'll try it again.

The detail error log as the picture:
<img width="731" alt="Screen Shot 2019-08-09 at 11 25 21 PM" src="https://user-images.githubusercontent.com/10546774/62815793-65ba5980-bb50-11e9-88ff-ec8ccde27968.png">

**Comment by gaoshanyu** [comment]
The Swift version of my project is 4.2.

And a warm warning, CLI apollo@2.17.2 cannot work well with apollo-ios@0.14.0 with Xcode 10.3 and Swift 4.2, I've got too many duplicate errors with them, so I downgrade apollo-ios to 0.13.0 with CLI apollo@2.16.1.

**Comment by gaoshanyu** [comment]
@designatednerd Hi Ellen, I get the same error after command `npm install apollo -g` for the Xcode Server Bot.

**Comment by gaoshanyu** [comment]
@designatednerd Hi Ellen, good news, my bot is working after I add `export PATH=$PATH:/usr/local/bin` on the first line of Apollo Api Generate Script, the full script as below:

```
export PATH=$PATH:/usr/local/bin
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
TARGET_PATH="${SRCROOT}/MyApp/Networking/ApolloAPI/GraphQL"
cd "${TARGET_PATH}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=*.graphql --localSchemaFile="schema.json" ../API.swift
```

Thanks!

**Comment by designatednerd** [comment]
OK cool - glad that helped. Be aware though, Apollo [switched to Swift 5 a few releases ago](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md#v0100), so I can't make you any guarantees about how anything after that release is going to work with 4.2. 

I'm going to close this issue since you were able to find a workaround. Thanks for sharing your path to figuring it out, that'll be helpful for others running into similar issues!
