### ISSUE TITLE
How use now URLSessionConfiguration with ApolloClient?

### ISSUE THREAD

**Issue by Cleversou1983** [apollographql/apollo-ios#711]
let configuration = URLSessionConfiguration.ephemeral
configuration.httpAdditionalHeaders = [
                "Authorization" : "Bearer \(AppParameters.authorizationBearer)"
 ]

Passing a configuration is no longer supported (it's a shame, it worked perfectly), how can I achieve this now? Thanks...

**Comment by designatednerd** [comment]
You should be able to hand that configuration to your `URLSession` that you can hand to the client.  This feature is merged but not released yet, it's going to go out with `0.15.0`
