### ISSUE TITLE
Apollo iOS Developer Survey [until 6 September!]

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#723]
Hey everyone! I'm doing a survey of the people using the Apollo iOS SDK to try and get a better grip on current uses and pain points, as well as get some feedback on ideas I'm looking at for the future. This is going to allow myself and the Apollo team to prioritize some future work and help get a long-term roadmap hammered out. 

[Here is the link to the survey](https://docs.google.com/forms/d/e/1FAIpQLSdriz2smdX3xz4H3KddENdHSD_qGzqNePT4QsA1v9LTZG_p9A/viewform?usp=sf_link) - you only need to fill it out once. You'll be asked to sign in to Google to prevent duplicate responses, but we'll only collect your personal information if you opt-in. 

Most of the required answers are multiple-choice, and there are several free form fields you can fill out at whatever length you'd like<sup>1</sup> to give more granular feedback. I'd super, super appreciate it if you could take some time to fill this out in the next couple weeks - I'll be leaving this open through at least September 6th. 

If you run into problems with the survey, please let us know in the comments. Thank you!

<sup>1</sup>: _For the sake of my sanity, please try to limit yourselves to something shorter than [_Infinite Jest_](https://www.goodreads.com/book/show/6759.Infinite_Jest)._

**Comment by koenpunt** [comment]
> Roughly how many users are using apps that you build with the Apollo iOS SDK (or will be by the end of September, 2019)? *

Do you mean monthly users?

**Comment by designatednerd** [comment]
Yes! I'll update that question

**Comment by designatednerd** [comment]
This survey is now closed. I'll be going through the answers and stuff this week to try and hammer out a longer term roadmap. I'll try to share any interesting bits that I find!
