### ISSUE TITLE
How to completely clear cache?

### ISSUE THREAD

**Issue by Cleversou1983** [apollographql/apollo-ios#725]
Hi there, I'm using: ApolloRequestObject.shared.privateClient.clearCache() (a singleton for the my private client) to clear the cache when the user logout, on login I'm trying using:
apollo.fetch(query: query, cachePolicy: .fetchIgnoringCacheCompletely)

But both ways doesn't work, only when I restart the simulator....

Thanks for your help!

**Comment by designatednerd** [comment]
Couple questions: 

- What kind of cache are you using, in-memory or SQLite? 
- Does the same issue happen on a device, or just in the simulator?

**Comment by Cleversou1983** [comment]
@designatednerd 

- I'm using the default caching
- It happens both in the simulator and on a device

When the user log-in, I search for user info and grab the token, when de user logout and login with a different account, the user data doesn't change...

**Comment by designatednerd** [comment]
if you're using CocoaPods, I'd try throwing a breakpoint into the `clearCache` method to see if it's actually getting called - that might at least help figure out what's going on (or not).

**Comment by Cleversou1983** [comment]
I've put the breakpoint and yes, it's being called... 

        ApolloRequestObject.shared.privateClient.clearCache().andThen { (_) in            
            DispatchQueue.main.async {
                Defaults.removeAll()
                self.performSegue(withIdentifier: self.segueToCheck, sender: nil)
            }            
        }

**Comment by Cleversou1983** [comment]
Other thing I've noticed here, the server provides me an access token, first time I log in, it works, then I logout, log in again, grab another token and the data doesn't update, I used this token in Altair, and has the same cache problem... Maybe it's a server side problem? Thanks for your help!

**Comment by Cleversou1983** [comment]
Nevermind, it was a backend problem... Thanks a lot anyway!

**Comment by designatednerd** [comment]
Thanks for letting us know!

**Comment by hondyCoding** [comment]
@Cleversou1983 , Thanks for saving me a lot of time.
