### ISSUE TITLE
Crash when uploading - JSONEncodable error

### ISSUE THREAD

**Issue by victormihaita** [apollographql/apollo-ios#728]
When trying to upload file using the mutation I get into an JSONEncodable error: 
![Screenshot 2019-08-21 at 11 23 26](https://user-images.githubusercontent.com/43206741/63415792-edcd1880-c406-11e9-98c0-71cc3b41cd34.png)

This is the mutation that I use:
```
mutation CreateUserArtwork($data: UserArtworkCreateInput!, $userId: ID!) {
    createUserArtwork(data: $data) {
        ...PublicArtworkInfo
        ...PrivateArtworkInfo
    }
}
```

The `UserArtworkCreateInput` contains one parameter of type Upload which has the following format when the mutation is performed: 
![Screenshot 2019-08-21 at 11 27 31](https://user-images.githubusercontent.com/43206741/63415922-24a32e80-c407-11e9-9c5c-37f29067967d.png)

I use `--passthroughCustomScalars` in the build phase and I define the `Upload` as: `public typealias Upload = GraphQLFile`

**Comment by designatednerd** [comment]
This is a bit of a limitation of uploading at the moment - you need to pass the upload in as one of the root parameters, so you will need to split up `Data` into its individual parameters. 

Please check out the [docs I recently added after some changes to uploading](https://www.apollographql.com/docs/ios/mutations/#uploading-files), and please let me know if you have further questions. Thank you!

**Comment by designatednerd** [comment]
Since I haven't heard back on this one in a couple weeks, I'm going to close this out. Please feel free to reopen if you're still having issues, or open a new issue. Thank you!
