### ISSUE TITLE
HTTPNetworkTransport still using completion handler blocks

### ISSUE THREAD

**Issue by diegoventura** [apollographql/apollo-ios#732]
The latest release (`0.15.0`) introduced the ability to use a `URLSession` instead of a `URLSessionConfiguration`, this allows using a background session on the `HTTPNetworkTransport`. 

However, `HTTPNetworkTransport` [is still using](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/HTTPNetworkTransport.swift#L108) completion handler blocks, which are not supported in a background session, instead of using a delegate for that.

Do you have any plans to change this behavior so `HTTPNetworkTransport` is always using a delegate instead of completion handler blocks?

**Comment by designatednerd** [comment]
Remind me why a completion handler can't be used in a background session? I thought when you got the background wakeup call you got a completion block to fire when your action had completed.

**Comment by diegoventura** [comment]
I thought it too, but when I'm getting the following crash when fetching the query.

```

**Comment by designatednerd** [comment]
Blargh. Will take a look when I get back.

**Comment by diegoventura** [comment]
👋 any update on this?

**Comment by designatednerd** [comment]
Not at the moment - I think we're probably going to have to add some additional protocol methods to make this work correctly, and I'm in the middle of about 14 other things. Would be more than happy to look at a pull request if you've got more time!

**Comment by kroussevrb** [comment]
This is very important, as Apple is going to reject apps that have a Share extension that starts uploads configured without a background session.

**Comment by designatednerd** [comment]
@kroussevrb Thanks for the heads up - again, I'm swamped with a couple other things but would be more than happy to look at a PR if you have some time!

**Comment by MaxDesiatov** [comment]
TWIMC, I've just released [ApolloAlamofire](https://github.com/graphql-community/ApolloAlamofire) 0.6.0, which is updated for Apollo 0.19.0 and allows using an Alamofire delegate for the Apollo transport.

**Comment by kroussevrb** [comment]
This is great, now the only thing missing is a pure Apollo solution for those of us who can't afford to import Alamofire as a dependency. I am aware of the suggestion to submit a PR for that but I don't know if  I will be able to get around to it (or even if I do, not sure it will be the best solution as I am not familiar with Apollo's source code)

**Comment by ethan021021** [comment]
Any update on this functionality? :)

**Comment by designatednerd** [comment]
Gonna be a bit - I've been doing some exploration around this and some other restructuring of the networking stack for HTTP recently, but I need to get it more stable before I write up a CFP.

**Comment by ethan021021** [comment]
@designatednerd Right on! Thanks so much for the quick reply. Love this SDK and everything about Apollo!

**Comment by kroussevrb** [comment]
I rewrote the network transport to be able to handle this but my implementation is very specific to our project, so can't help out here.

**Comment by designatednerd** [comment]
Hi folks, I finally got something that will work with a background session functional. Please check out #1163, I would love your feedback.

**Comment by designatednerd** [comment]
This has (finally) shipped with `0.27.0`. Thanks to all for your patience!

**Comment by preetirani** [comment]
Hey Can anyone please share the right way of configuring apollo for the background task to work. earlier i was using 0.21.0 for all foreground tasks and now updated to 0.27.0 so as to hit api from background.
Any example would be helpful. I just want to know what all needs to be done for the background to work.

**Comment by designatednerd** [comment]
Hi! You can pass the background session configuration you receive from the system into a `URLSessionClient`, since that takes a session configuration. Then, you pass that client into the initializer for `HTTPNetworkTransport`. 

Does that help?

**Comment by diegoventura** [comment]
You also have to implement the background session delegates to handle download progress and response.

**Comment by designatednerd** [comment]
@diegoventura are you talking about the delegates on `UIApplication`? We cover [a lot of delegate methods](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/URLSessionClient.swift#L111) in `URLSessionClient`

**Comment by preetirani** [comment]
import Foundation
      import Apollo

      // MARK: - Singleton Wrapper

     class Network {

    static var cachedShared: Network?

    static var shared: Network {
        guard cachedShared == nil else {
            return cachedShared!
        }

        cachedShared = Network()
        return cachedShared!
    }

    static func resetShared() {
        cachedShared = nil
    }

    var networkTransport: HTTPNetworkTransport {
        let configuration = URLSessionConfiguration.default
            configuration.httpAdditionalHeaders = [
                "Custom-Authorization": "Bearer \(AuthenticationToken.current?.token ?? "")",
                "IS-MOBILE-APP": "true"
            ]
        let url = URL(string: Constant.urlString)!
        let client = URLSessionClient(sessionConfiguration: configuration)
        return HTTPNetworkTransport(url: url, client: client)
    }

    // Use the configured network transport in your Apollo client.
    private(set) lazy var apollo = ApolloClient(networkTransport: self.networkTransport)
     }


This is code I am using to instantiate apollo client.
@designatednerd how did we get background session from system ?

**Comment by designatednerd** [comment]
[Here's all of Apple's documentation about how to get a background session](https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background). You'll probably want to make your `networkTransport` var a function that takes the `URLSessionConfiguration` as a parameter.
