### ISSUE TITLE
GenericScalar type generates as String

### ISSUE THREAD

**Issue by DmitryVanyshkin** [apollographql/apollo-ios#733]
Server of my app use JWT for authorization. So, when I perform mutation to verify token, I recieve field with GenericScalar type. The main problem that Apollo-ios recognise it as String and throws error when parces response. 
<img width="383" alt="Снимок экрана 2019-08-22 в 23 57 04" src="https://user-images.githubusercontent.com/43039535/63549246-b65e8900-c538-11e9-8125-f9f595c27b2b.png">
<img width="484" alt="Снимок экрана 2019-08-22 в 23 57 16" src="https://user-images.githubusercontent.com/43039535/63549296-ca09ef80-c538-11e9-992e-86ab77a51147.png">
<img width="390" alt="Снимок экрана 2019-08-22 в 23 57 25" src="https://user-images.githubusercontent.com/43039535/63549278-c4140e80-c538-11e9-8594-03c2a7b3e752.png">

**Comment by Greensource** [comment]
Exact same issue for me. In my opinion, regarding the GenericScalar definition, Apollo SDK should generate a var of type `Any` instead of `String`.

**Comment by designatednerd** [comment]
For clarity when I look into this when I get back: Are you using the `passthroughCustomScalars` option with Codegen, or not? If you try the opposite of what you're doing now, does that make things better or worse? 🙃

**Comment by DmitryVanyshkin** [comment]
I didn't have this option, but with `passthroughCustomScalars` it makes a lot of errors, such as "Use of undeclared type 'GenericScalar"
<img width="563" alt="Снимок экрана 2019-08-24 в 11 09 12" src="https://user-images.githubusercontent.com/43039535/63634477-9d042c80-c65f-11e9-9f04-d5dc22aa9541.png">
<img width="703" alt="Снимок экрана 2019-08-24 в 11 08 39" src="https://user-images.githubusercontent.com/43039535/63634470-88279900-c65f-11e9-8748-a9e2cea43195.png">
<img width="696" alt="Снимок экрана 2019-08-24 в 11 08 52" src="https://user-images.githubusercontent.com/43039535/63634474-8fe73d80-c65f-11e9-8445-02d6e7eb9268.png">

**Comment by koenpunt** [comment]
For `passthroughCustomScalars` to work you have to define the type yourself. 

Could be as simple as;

```swift
struct GenericScalar: JSONDecodable, JSONEncodable {
  public init(jsonValue value: JSONValue) throws {
    switch value {
    case let string as String:
        self = string
    case let int as Int:
        self = String(int)
    default:
        throw JSONDecodingError.couldNotConvert(value: value, to: String.self)
    }
  }

  public var jsonValue: JSONValue {
    return self
  }
}
```

You can see the default type conversions here; 
https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/JSONStandardTypeConversions.swift

**Comment by koenpunt** [comment]
Or for the `DateTime` scalar;

```swift

public typealias DateTime = Date

extension Date: JSONDecodable, JSONEncodable {
    public init(jsonValue value: JSONValue) throws {
        guard let string = value as? String else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Date.self)
        }

        let dateFormatter = DateFormatter()
        let locale = Locale(identifier: "en_US_POSIX")
        dateFormatter.locale = locale
        dateFormatter.timeZone = TimeZone(identifier: "UTC")
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z"

        if let data = dateFormatter.date(from: string) {
            self = data
        } else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Date.self)
        }
    }

    public var jsonValue: JSONValue {
        let dateFormatter = DateFormatter()
        let locale = Locale(identifier: "en_US_POSIX")
        dateFormatter.locale = locale
        dateFormatter.timeZone = TimeZone(identifier: "UTC")
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z"

        return dateFormatter.string(from: self)
    }
}

```

**Comment by DmitryVanyshkin** [comment]
Oh, I prefer to not use `GenericScalars`, but when I try to do @koenpunt's suggestions they work
