### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code . (Xcode 10.3 )

### ISSUE THREAD

**Issue by pradipwalghude** [apollographql/apollo-ios#736]
Showing Recent Messages
Command PhaseScriptExecution failed with a nonzero exit code

Facing the same issue with Xcode 10.2 .
I have used below script. Please correct me if I am wrong.
Below error facing in swift 5.0 and Xcode 10.3 . Please help me asap

APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift

**Comment by designatednerd** [comment]
Yeah this is unfortunately a [known issue](https://github.com/apollographql/apollo-ios/issues/386#issuecomment-507247115) - please see that link for a detailed explanation. Seems like you already found a workaround though!

**Comment by designatednerd** [comment]
Since I haven't heard back on this one in a couple weeks I'm going to close it out as stale - please feel free to reopen or file a new issue if a different version of either Xcode or Apollo has come out since this was filed.

**Comment by pradipwalghude** [comment]
Facing same issue with XCode 10.3 .
It is working with XCode 10.1 but not working with latest XCode version.

**Comment by designatednerd** [comment]
Hey Pradip, Can you please open a new issue with the following details: 

- Xcode version
- Which dependency manager you are using, Carthage, Cocoapods, or Swift Package Manager
- A copy of the error text you are receiving

And then I'll work with you on that issue to figure out what's going on. Thank you!
