### ISSUE TITLE
Apollo Websocket gives 4000 error

### ISSUE THREAD

**Issue by DmitryVanyshkin** [apollographql/apollo-ios#740]
Good afternoon! Using Apollo GraphQL and Apollo WebSocket in my app. So, when I'm trying to connect to websocket it disconnects immediately, then reconnects and thar repears again.
So, i recieve result with failure and error such this one:
<img width="305" alt="Снимок экрана 2019-08-28 в 17 45 33" src="https://user-images.githubusercontent.com/43039535/63866274-a53fcd00-c9bb-11e9-8998-bde3f32f45fc.png">

**Comment by DmitryVanyshkin** [comment]
@designatednerd small update until I try to user your solution.

**Comment by DmitryVanyshkin** [comment]
Sorry, I was rather retarded. That was token problem, not WebSocket library

**Comment by designatednerd** [comment]
Thank you for letting us know @DmitryVanyshkin!
