### ISSUE TITLE
Unable to Compile Apollo version 0.15.0 with Xcode 10.2 no API.swift file is created.

### ISSUE THREAD

**Issue by SandeepZap** [apollographql/apollo-ios#741]
Using Apollo version 0.15.0
Npm version 6.10.3
Node version v12.9.1

**Not able to compile the project with Legacy Build System and New Build System**

> > ›   Warning: apollo update available from 1.9.2 to 2.18.0.

> ++ npx --no-install apollo codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.json API.swift
>  ›   Warning: apollo update available from 1.9.2 to 2.18.0.
>  ›   Error: Unexpected arguments: --localSchemaFile=schema.json, API.swift
>  ›   See more help with --help
> Command /bin/sh failed with exit code 2

**Comment by designatednerd** [comment]
It looks like you need to update your local version of the Apollo CLI - 2.x has a different set of arguments than 1.x did.

**Comment by SandeepZap** [comment]
Update Apollo CLI version has fixed this issue

**Comment by designatednerd** [comment]
Cool, thanks for letting us know!
