### ISSUE TITLE
Command PhaseScriptExecution failed due to "No such file or directory" caused by space

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [apollographql/apollo-ios#743]
My macOS project is located in /Volumes/Macintosh HD/.... which is a different volume than my current volume (working in Catalina). I'm seeing an error trying to build the project:

> Command PhaseScriptExecution failed with a nonzero exit code
> Script-1771858A1DFDCDED00CC36C8.sh: line 2: /Volumes/Macintosh: No such file or directory

A space in the path breaks the run script. I'm using:
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
```

**Comment by designatednerd** [comment]
Oof, I thought I'd validated `PODS_ROOT` fixed that but apparently it didn't. Whee! I'll see what I can figure out.

**Comment by jordanhbuiltbyhq** [comment]
That gets the full path, though it is still failing to find the file at that location the way that's formatted.

```
PODS_ROOT_ESCAPED=$(printf %q "$PODS_ROOT")
SCRIPT_PATH="${PODS_ROOT_ESCAPED}/Apollo/scripts"
echo "SRCROOT: ${PODS_ROOT_ESCAPED}"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
```

logs

```
SRCROOT: /Volumes/Catalina\ -\ Data/Users/jordan/Downloads/projectname/Pods
line 6: /Volumes/Catalina\ -\ Data/Users/jordan/Downloads/projectname/Pods/Apollo/scripts/check-and-run-apollo-cli.sh: No such file or directory
```

**Comment by designatednerd** [comment]
So I have a couple questions: 

- Does the file actually exist at that path when you go to it from Finder?
- If it does, when you drag the file from the Finder into Terminal, how does the path differ from what you're seeing in the output here?

**Comment by jordanhbuiltbyhq** [comment]
Yes. It appears exactly the same. Strange. Confirmed I can directly cd into that location.
/Volumes/Catalina\ -\ Data/Users/jordan/Downloads/projectname/Pods/Apollo/scripts/check-and-run-apollo-cli.sh

**Comment by designatednerd** [comment]
Well that's damned weird. Especially if you can `cd` over to it. I assume `6` is the last line of this script?

Just for funsies, what happens if you hardcode that path - does it work or fail?

**Comment by jordanhbuiltbyhq** [comment]
So it's failing on the `cd` line, and then also failing on the last line. Even when I hardcode the path to that folder, the same one I can `cd` into via Terminal.

Could it be a permissions issue accessing it in the different volume?

**Comment by designatednerd** [comment]
that's certainly what i'm thinking - what do you get when you `ls -la` after `cd`'ing into that volume in the terminal?

**Comment by jordanhbuiltbyhq** [comment]
```
total 16
drwxr-xr-x  4 Jordan  staff   128 Sep 12 21:29 .
drwxr-xr-x  6 Jordan  staff   192 Sep 12 21:29 ..
-rwxr-xr-x  1 Jordan  staff  3040 Sep 12 21:29 check-and-run-apollo-cli.sh
-rwxr-xr-x  1 Jordan  staff   181 Sep 12 21:29 check-and-run-apollo-codegen.sh
```

**Comment by designatednerd** [comment]
Weird, read and execute permissions both appear to be global, although maybe there's something where it's not working because it's on a different volume? 

What happens when you try to execute it directly from your Catalina partition (rather than from your Mojave partition)? 

Overall I think "Running this from a different volume" is going to be somewhat of an edge case, though 😄

**Comment by jordanhbuiltbyhq** [comment]
That's fair! 😛 If I move it over to my current partition then build/run it works without issue. (even without the prinf)

**Comment by designatednerd** [comment]
OK. Mind if we close this out?

**Comment by jordanhbuiltbyhq** [comment]
That'd be ok with me.
