### ISSUE TITLE
Tests fails to build on fresh checkout

### ISSUE THREAD

**Issue by js** [apollographql/apollo-ios#748]
I get 30 build errors or so for the StarwarsAPI target when I build the tests, all in API.swift, they're all in the form of:
[...]/apollo-ios/Tests/StarWarsAPI/API.swift:585:58: Value of optional type '[HeroAndFriendsNamesWithIDsQuery.Data.Hero.Friend?]?' must be unwrapped to refer to member 'filter' of wrapped base type '[HeroAndFriendsNamesWithIDsQuery.Data.Hero.Friend?]'

I also see the generated code changed after I built at what seems to be the same locations as the build errors
```
-          return (resultMap["friends"] as? [ResultMap?]).flatMap { (value: [ResultMap?]) -> [Friend?] in value.map { (value: ResultMap?) -> Friend? in value.flatMap { (value: ResultMap) -> Friend in Friend(unsafeResultMap: value) } } }
+          return (resultMap["friends"] as? [ResultMap?]).flatMap { (value: [ResultMap?]) -> [Friend?] in value.map { (value: ResultMap?) -> Friend? in value.flatMap { (value: ResultMap) -> Friend in Friend(unsafeResultMap: value) } } }.filter({
+            Friend.possibleTypes.contains($0.__typename)
+          })
```

So I suspect this is some NPM trickery?
My globally installed apollo bin is slightly behind being `apollo/2.17.1 darwin-x64 node-v10.15.3`, but isn't it supposed to yell at me if that's the wrong version and/or install the correct version? I forget how that works…

**Comment by designatednerd** [comment]
In theory this should be fixed by `2.17.4` - I'm not sure why it wouldn't be updating, though. Potentially because you're using a global instead of a local install? 

We're working on getting ourselves out of node hell fwiw

**Comment by designatednerd** [comment]
@js Were you able to ever get another look at this?

**Comment by designatednerd** [comment]
Since I haven't heard back on this in a couple weeks, I'm going to close it out. If you run into a similar problem, please open a new issue. Thank you!
