### ISSUE TITLE
When trying integrate Apollo using SPM inside Xcode Unit tests will not compile.

### ISSUE THREAD

**Issue by dallasjohnson** [apollographql/apollo-ios#754]
I have been able to get it to run the app but my unit tests target for my app will not compile.
The error seems to be caused by:
`CompileSwift normal i386 (in target 'ApolloWebSocket' from project 'Apollo')`

If I remove this import from the ApolloWebSocket classes then it creates more errors since `ApolloWebSocket` and `SplitNetworkTransport` need the Apollo module.

I'm running Xcode Version 11.0 beta 6 (11M392r) on Catalina.

**Comment by designatednerd** [comment]
Hi @dallasjohnson - I'll see if I can repro. In the meantime can you give any further details on that error, or is that all the compiler's giving you? 

Are you actively using the `ApolloWebSocket` target in your project?

**Comment by designatednerd** [comment]
@dallasjohnson I was able to get this building on the GM on both Catalina and ~Mojito~ Mojave. Can you let me know how things are different on your end? 

[SPMTest3.zip](https://github.com/apollographql/apollo-ios/files/3598169/SPMTest3.zip)

**Comment by designatednerd** [comment]
Since I haven't heard anything back on this and Xcode 11's final edition has come out, I'm going to close this issue out. If you're still having problems with this, please open a new issue. Thank you!
