### ISSUE TITLE
Code generation with IBDesignable causes continuous rebuilds

### ISSUE THREAD

**Issue by aaronjensen** [apollographql/apollo-ios#76]
When using the codegen as a prebuild step along with a component that has `@IBDesignable` we see continuous rebuilds in Xcode. My guess is that Xcode sees a file touch/change and triggers a rebuild, which touches the file which triggers a rebuild, etc. Maybe if the codegen snippet only touched the file if it actually made changes it'd stop the loop?

**Comment by martijnwalraven** [comment]
Hmmm, that sounds plausible, but is there any way you can verify this before we make the change? That would probably require comparing the newly generated code to the code on disk before we overwrite it.

**Comment by aaronjensen** [comment]
Sorry, I verified by disabling the code generation step and it stopped looping.

**Comment by martijnwalraven** [comment]
Thanks. Then we'll keep this open as an issue to tackle. Any chance you'll be able to work on a pull request for this?

**Comment by designatednerd** [comment]
I've seen issues with this around `@IBDesignable` all over the place. One workaround that I've found which works consistently is ironically the thing Apple used to make you do with `IBDesignable` in early betas of it: Put all your `IBDesignable` objects in their own framework. That way, only that framework has to rebuild when the designables are reloading. 

I'll definitely be looking into a way to reduce unnecessary rebuilds though!

**Comment by designatednerd** [comment]
I've added documentation of a workaround to the [Advanced Codegen Tips And Tricks](https://www.apollographql.com/docs/ios/installation/#advanced-codegen-tips-and-tricks) section of our documentation. If you're still having issues after setting that up, please file a new issue. Thank you!

(Note that I'm still planning to [add XCFileList generation](https://github.com/apollographql/apollo-ios/issues/636) as part of the Swift Codegen project, but that workaround should get you through until that's up and running)
