### ISSUE TITLE
New mutation not generating in API.swift

### ISSUE THREAD

**Issue by adamirowe** [apollographql/apollo-ios#768]
I added a new mutation that was working fine in xCode 10.3, but when the project is built using xCode 11.0 (any iteration) the added mutation, nor its input, are no longer generated.

I am on an older version of the pod (`0.10.1`) with apollo-cli at `1.9.2`. Everything I've read indicates this is the correct version of the pod to use.

Nothing else has changed in our setup besides a new version of xCode. Do I need to update the pod for xCode11?

**Comment by adamirowe** [comment]
For reference, the mutation file is getting added in the 
`npx --noinstall apollo codegen:generate '--queries'`
command.

I am also getting the following warning message - `Warning: apollo update available from 1.9.2 to 2.17.2`

**Comment by adamirowe** [comment]
I should also mention that I did try to upgrade to a newer version of the pod in another branch before coming back to this branch.

**Comment by designatednerd** [comment]
I would double-check the Build Phase Run Script you're using against the [current one for CocoaPods](https://www.apollographql.com/docs/ios/installation/#if-you-are-integrating-apollo-using-cocoapods) -  the previous one was relying on a few assumptions about where frameworks would be that the current one is not relying on. 

The current version of the lib is `0.15.3`, but there are [a number of breaking changes](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md) that happened in those new versions, so you may want to get this version working first before going through what changed.

**Comment by adamirowe** [comment]
Alright, just realized what was going on. Mutation had been amended to not request anything back as payload, which was breaking the generation script apparently (but not failing at that point). Adding a trivial payload property to the mutation got it working again.

Now to upgrade the pod to the 20th century...
