### ISSUE TITLE
Upload Multi part file

### ISSUE THREAD

**Issue by emanShedeed** [apollographql/apollo-ios#775]
Using Apollo (0.15.1)
<img width="925" alt="Screen Shot 2019-09-19 at 3 02 40 PM" src="https://user-images.githubusercontent.com/42905983/65246396-c7c29300-daee-11e9-98ef-51dbd6b287db.png">
mutation addRoom($roomImages:[Upload!],$moveID:ID!,$name:String!,$dimension:String!,$description:String!,$budget:Float!){
    addRoom(data: {
            moveID:$moveID
            name:$name
            dimension:$dimension
            description:$description
            budget:$budget
            roomImages:$roomImages
            }){
        status
        message
    }
}
what is wrong here ?

**Comment by designatednerd** [comment]
The primary issue is that because `Upload` is a scalar that's a `String` under the hood, the mutation needs to take an array of Strings which will be replaced by the `upload` function by the array of files. 

The secondary issue is you need to use the `upload` instead of the `perform` function. 

For reference, [here is the documentation with an example of how to upload files](https://www.apollographql.com/docs/ios/mutations/#uploading-files). 

Anything else I can help with here, or can we close this out?

**Comment by emanShedeed** [comment]
I just follow the doc and an error request time out is appearing here is the code
<img width="907" alt="Screen Shot 2019-09-20 at 7 51 23 AM" src="https://user-images.githubusercontent.com/42905983/65302444-81674580-db7b-11e9-9dda-e78abb4993be.png">

**Comment by designatednerd** [comment]
Hey Eman, a request timeout indicates that your server is not responding quickly enough. 

You will want to a) Check the request timeout being set on your `URLSession` if you're using a custom one (it's using the default session with all its presets if you're not passing one in) and b) work with the team working on your server to see what issues are occurring on their end that are causing a response not to be sent.

**Comment by victormihaita** [comment]
@designatednerd Do you think that in the near future we will have the functionality to use a mutation with an object parameter that includes a file to upload? Or at least to have the file and the object in the same time as parameters?

**Comment by designatednerd** [comment]
Not in the near future - right now fixing codegen is a higher priority, to be honest. There's some stuff I'd need to look at with the mutation generation in general that *may* help this, but I don't want to give false hope that this is getting addressed anytime soon.

**Comment by designatednerd** [comment]
I'm gonna close this out as there hasn't been activity in the last couple of weeks and there is documentation of what you should need to do in order to upload files at the moment. If you've got further questions, please open a new issue. Thanks!
