### ISSUE TITLE
Building for Mac Catalyst is not supported by the legacy build system.

### ISSUE THREAD

**Issue by cczufish** [apollographql/apollo-ios#783]
when I try ipad app transfer to Mac app

Building for Mac Catalyst is not supported by the legacy build system.

**Comment by designatednerd** [comment]
@cczufish I don't believe this has to do with Apollo directly, it has to do with which build system you're using on your project. Please go to `File > Workspace Settings` and check what's set up there.

**Comment by cczufish** [comment]
> @cczufish I don't believe this has to do with Apollo directly, it has to do with which build system you're using on your project. Please go to `File > Workspace Settings` and check what's set up there.

building setting -> supported platforms  -> macOS

**Comment by designatednerd** [comment]
I was referring to the build system setting shown here: 
<img width="535" alt="Screen Shot 2019-09-24 at 9 44 49 AM" src="https://user-images.githubusercontent.com/1976498/65522187-015d1a80-deb0-11e9-9339-d7ccc38844e5.png">

My guess is that your `Build System` in `Shared Workspace Settings` is `Legacy Build System` given the error you're receiving. Click that drop-down to switch to the new build system.

**Comment by designatednerd** [comment]
@cczufish did that fix your issue?

**Comment by designatednerd** [comment]
Since I haven't heard back in a couple weeks, I'm going to close this out. If you're still having problems, please feel free to re-open or file a new issue. Thank you!
