### ISSUE TITLE
Improve How We Get Node Binaries

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#791]
As (extensively) discussed in #766, including the binaries for codegen in the repo will bloat the repo over the long term. While this is better than Node Hell, it's still not great as a long-term solution. 

We need to evaluate a few of the suggested ideas for this, including: 

- A separate GH repo which can be added as an SPM/Carthage/Pod dependency (concern: Is this just moving the repo bloat problem to another repo people have to download anyway?)
- Downloading from an artifact repository, like an S3 bucket (concern: What happens when users can't connect to that bucket after installation, killing their entire build?)
- Downloading from GH releases (concern: How can we test this before a new version is released?)

**Comment by zzal** [comment]
While we’re here, why not leaving the "iOS" terminology in favour of something more relevant. Like "apollo-swift" of "apollo-for-macOS-iOS-iPadOS-watchOS-tvOS".
Just saying.

**Comment by designatednerd** [comment]
@zzal I don't believe that's relevant to this issue - if you'd like to start a longer discussion about that please open a new issue (short answer: The lib itself is already just `Apollo`, and renaming the repo comes with a pile of issues that I don't think are worth the semantic clarity).

**Comment by designatednerd** [comment]
@koenpunt see #855

**Comment by designatednerd** [comment]
Shipped!
