### ISSUE TITLE
Error when parsing enum value in Apollo Swift Codegen

### ISSUE THREAD

**Issue by an-indya** [apollographql/apollo-ios#793]
Here is my graphql file:
```
fragment CourseDetails on Course {
  id
  title
  description
    activity_library {
        id
        title
        status {
            id
            status
        }
    }
}
```
I am using Cocoapods and I followed all the steps including the script in the Build Phase. However, I am getting this error when building - `Cannot convert value of type 'CourseDetails.ActivityLibrary.Status.Type' to expected argument type 'JSONDecodable.Type`

The API.swift file generates the enum like this

```
public enum Status: RawRepresentable, Equatable, Hashable, CaseIterable, Apollo.JSONDecodable, Apollo.JSONEncodable {
  public typealias RawValue = String
  case inProgress
  case completed
  /// Auto generated constant for unknown enum values
  case __unknown(RawValue)

  public init?(rawValue: RawValue) {
    switch rawValue {
      case "in_progress": self = .inProgress
      case "completed": self = .completed
      default: self = .__unknown(rawValue)
    }
  }

  public var rawValue: RawValue {
    switch self {
      case .inProgress: return "in_progress"
      case .completed: return "completed"
      case .__unknown(let value): return value
    }
  }

  public static func == (lhs: Status, rhs: Status) -> Bool {
    switch (lhs, rhs) {
      case (.inProgress, .inProgress): return true
      case (.completed, .completed): return true
      case (.__unknown(let lhsValue), .__unknown(let rhsValue)): return lhsValue == rhsValue
      default: return false
    }
  }

  public static var allCases: [Status] {
    return [
      .inProgress,
      .completed,
    ]
  }
}
```

Any idea how to resolve this?

**Comment by designatednerd** [comment]
Yeah that's bizarre - as you can see from the very first line of declaration, it *does* conform to `Apollo.JSONDecodable`. Do you mind sending your schema over so I can get a look on my end?

**Comment by designatednerd** [comment]
Oh wait! I think I may see the problem. There's two different `Status` things going on here: The enum value and the name of the class. Try using an alias in the innermost part of the query like so:

```graphql
activity_library {
        id
        title
        activityStatus: status {
            id
            status
        }
    }
```

I *think* that will unconfuse the compiler, since it'll cause the codegen to rename that class so it doesn't collide with the enum.

**Comment by an-indya** [comment]
That fixed it!!! Thank you so much!

**Comment by designatednerd** [comment]
hooray! mind if I close out this issue then?

**Comment by an-indya** [comment]
Yes sure.
