### ISSUE TITLE
Unable to find codegen script for macOS

### ISSUE THREAD

**Issue by philfi** [apollographql/apollo-ios#795]
Have a macOS target that is used infrequently and just noticed that its failing the codegen step because it can't find the script in Apollo.framework. The specific error message is `...Build/Products/Debug/Apollo-macOS/Apollo.framework/check-and-run-apollo-cli.sh: No such file or directory`

Compared the contents of Apollo.framework between the macOS build product with the contents of the iOS build product and I only see the codegen scripts in the iOS version? Not sure if I'm doing something wrong or if there is an issue, thanks in advance for any assistance!
For context we're running Apollo `0.10.1` in XCode 11.

**Comment by designatednerd** [comment]
Hm, that shouldn't be the case - the script should be there but it would be in a different place, but that should have been accounted for in a difference in the setup instructions for mac apps at the time. 

I'd advise taking a look at what was in the `docs/source/installation.md` file when the `0.10.1` tag was created - that would give you a better idea of the script we were advising at that point, and also the differences in where to look for iOS/macOS

**Comment by philfi** [comment]
ah yes I see that it should be a different path: https://github.com/apollographql/apollo-ios/blob/47e33163a2b0f5415135d16cac9d29e453a04be2/docs/source/installation.md
thanks!
