### ISSUE TITLE
Terminated due to signal 9

### ISSUE THREAD

**Issue by barrettbreshears** [apollographql/apollo-ios#80]
I have a basic query that looks like this:
`query AllOpportunities{
    opportunity{
        account_score
        activity_score
        age
        attractiveness_score
        buyer_count
        company_name
        deal_size_factor
        employee_factor
        energy_score
        fit_score
        industry_factor
        mass_score
        opportunity_id
        opportunity_score
        revenue_factor
        size_factor
        stages_completed_count
    }
    
}
`
`apollo.fetch(query: AllOpportunitiesQuery()) { (result, error) in
            
            print(result)
           `
When executing the query I get the following error:
<img width="1133" alt="screen shot 2017-04-12 at 11 02 25 am" src="https://cloud.githubusercontent.com/assets/2055070/24964651/d91a9338-1f6f-11e7-949d-94ce54735b86.png">

Followed by a terminated app due to signal 9
<img width="348" alt="screen shot 2017-04-12 at 11 02 36 am" src="https://cloud.githubusercontent.com/assets/2055070/24964672/e809193c-1f6f-11e7-83af-7050a84d6007.png">

I'm running version 0.5.6 with swift 3.1, Xcode 8.3.1 and used pods to import the apollo framework

**Comment by martijnwalraven** [comment]
Is there any way you can create a minimal project that reproduces this issue? I've tried to reproduce it, but all the tests for version 0.5.6 still run on Xcode 8.3.

**Comment by barrettbreshears** [comment]
I will try today and let you know thanks

**Comment by martijnwalraven** [comment]
Going to close this issue for lack of response, but feel free to reopen it if you can reproduce this on the latest version.
