### ISSUE TITLE
Question: Should Pods/Apollo/scripts/apollo be a preserved path?

### ISSUE THREAD

**Issue by cltnschlosser** [apollographql/apollo-ios#800]
Right now when you pod install the extracted cli gets deleted and has to be extracted again. This isn't a huge issue, but is there any reason that the `apollo` directory isn't preserved?

**Comment by designatednerd** [comment]
Ooh, good question. The main reason is that when a new version of the CLI is included, we *want* to nuke the old one, but there's already code in the `run-bundled-codegen` script to handle that. Let me muck around with it a bit and see what I can figure out.

**Comment by designatednerd** [comment]
OK I tried this out and it looks like that's not really possible with the behavior of `preserve_paths` - It only preserves the paths *after* re-pulling. The [docs](https://guides.cocoapods.org/syntax/podspec.html#preserve_paths) say that the preserved paths are "Any file that should not be removed after being downloaded." - as far as I can tell, the "after being downloaded" part is the issue - it appears at a certain point during the `pod install` / `pod update` process

You can check the `update/preserve-paths` branch to see this in action.

**Comment by designatednerd** [comment]
@cltnschlosser Does this answer your question or do you have an alternate suggestion?

**Comment by cltnschlosser** [comment]
Yeah, thanks for looking into this!

**Comment by designatednerd** [comment]
Cool - FYI for anyone looking at this in the future, I'm deleting the branch
