### ISSUE TITLE
Different/wrong path in script for archiving using SPM

### ISSUE THREAD

**Issue by cbiggin** [apollographql/apollo-ios#801]
I'm using the SPM and for the most part, the directions listed [here](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) are correct. For compiling/running on your device and simulator, they work fine.

However when archiving to upload to the AppStore (ie, `Xcode -> Product -> Archive`), it fails.

In the script phase, instead of:

    cd "../../SourcePackages/checkouts/apollo-ios/scripts"

I have to do:

    cd "../../../../../SourcePackages/checkouts/apollo-ios/scripts"

This resolves the script finding problem, but even with this, I am getting `No such module ApolloWebSocket` & `No such module Apollo` error messages.

Because of this, I cannot upload to Testflight and while not an immediate issue, this soon will be. Is anybody else experiencing this? Am I doing something blatantly wrong here (and I would be more than happy to find out I was)?

The only thing I do _slightly_ differently is that I have my `.graphql` files (and some others) in a sub-folder called `Apollo` (with the script adjusted accordingly)... but I don't think this is the issue.

**Comment by cbiggin** [comment]
Here are the ${BUILD_ROOT} variables:

Simulator/device:

    /Users/colin/Library/Developer/Xcode/DerivedData/OBFUSCATED_PRODUCT_NAME_DIRECTORY/Build/Products

Archive:

    /Users/colin/Library/Developer/Xcode/DerivedData/OBFUSCATED_PRODUCT_NAME_DIRECTORY/Build/Intermediates.noindex/ArchiveIntermediates/PRODUCT_NAME/BuildProductsPath

**Comment by designatednerd** [comment]
Errrrgh that's really obnoxious. It looks like everything is moved to a totally different root folder on archiving. I need to figure out a way to get the checkout path but there doesn't seem to be an env variable for it, nor does there seem to be one for the root of the derived data directory....

As a temporary fix you can use this to determine if it's building or archiving: 

```bash
if [ "${ACTION}" == "build" ]; then
  cd "../../SourcePackages/checkouts/apollo-ios/scripts"
else 
  cd "../../../../../SourcePackages/checkouts/apollo-ios/scripts"
fi
```

**Comment by designatednerd** [comment]
@cbiggin Please see #802 for a more permanent solution

**Comment by cbiggin** [comment]
OK, that fixes the script execution. But I'm still getting `No such module ApolloWebSocket` & `No such module Apollo` error messages.

Typically when you get those messages, you need to update your frameworks path but how can you put a search-path to the SPM in there?

**Comment by designatednerd** [comment]
Weird - which targets are you using? In theory Xcode should do all that work for you automagically

**Comment by designatednerd** [comment]
I'm gonna close this out since the main issue has been solved - @cbiggin if you're still having `No such module` issues after doing a `Clean Build Folder`, please open another issue and we'll try to figure out what's going on.

**Comment by CesarAdan1** [comment]
Hello I have this problem in the splitnetworktransport.swift 
it says import Apollo.  No such module 'Apollo'
I don`t know how I can fix that. I really don´t know where to edit or configure this.

Kind regards

**Comment by designatednerd** [comment]
Hey @CesarAdan1 - Can you open a new issue please with information including: 
- What version of the iOS SDK are you using? 
- What package manager are you using to integrate it? 

Thank you!
