### ISSUE TITLE
NVM not in the run script path

### ISSUE THREAD

**Issue by levous** [apollographql/apollo-ios#803]
code gen run script failed with: "env: node: No such file or directory"

I struggled with this all day.  First of all, it had worked in Xcode 11 Beta.  When I upgraded to release Xcode 11, the script began failing.  

I tried both Carthage and Swift Package Manager.  Eventually, I found I could run successfully copy the execution line from build output and run the script in terminal.  By adding the following at the top of the run script, it works.  

`export NVM_DIR=$HOME/.nvm
[[ -s $HOME/.nvm/nvm.sh ]] && source $HOME/.nvm/nvm.sh
[[ -s $(brew --prefix nvm)/nvm.sh ]] && source $(brew --prefix nvm)/nvm.sh`

This is in my .bashrc file and sourced from my .bash_profile so I am not sure why Xcode is not picking it up.

**Comment by designatednerd** [comment]
@levous What version of the library are you using? What is your build phase run script? There have been some changes recently so I want to see if those might be the source of your issues.

**Comment by designatednerd** [comment]
I *think* this might be related to a change I just snuck into #806 - previously the `PATH` didn't necessarily hit the included node binary, now it does. Try checking that branch (`update/sha`) out and seeing if that fixes your problem.

**Comment by designatednerd** [comment]
@levous That change shipped with `0.16.1` if you wanna give it a shot

**Comment by lucasecf** [comment]
@designatednerd just to let you know that I had exactly the same issue on version `0.16.0`, and updating to `0.16.1` like suggested fixed it 👍

**Comment by designatednerd** [comment]
Cool - @levous if I don't hear back from you in the next day or two I'll close this out, but would love to hear if you got it working.

**Comment by designatednerd** [comment]
Would still love to hear back but I'm gonna close this out as fixed in `0.16.1` unless I hear otherwise.
