### ISSUE TITLE
.shasum file contains absolute path that differs between computers

### ISSUE THREAD

**Issue by interstateone** [apollographql/apollo-ios#805]
The .shasum file used by Apollo 0.16 has content like this:  `13febaa462e56679099d81502d530e16c3ddf1c6c2db06abe3822c0ef79fb9d2  /Users/USER/APP_NAME/TARGET_NAME/../Pods/Apollo/scripts/apollo.tar.gz`

We commit the Pods/ directory to our project repo. Because the tarball path is absolute it'll differ between machines that check out the project and run the build phase. This means that the path in the .shasum file is changing as we work on our project and so we need to choose from: manually revert the change, accept that the file will be in our diffs, gitignore it, etc.

I was thinking this tarball path could be relative to PODS_ROOT when it's been integrated with CocoaPods, which should avoid the root cause of different project checkout paths on different computers. Would need to make sure a change for this doesn't affect the other ways of integrating Apollo. Wondering if you have a preferred way to solve this?

**Comment by designatednerd** [comment]
The problem with making it a relative path is that the full path comes back from the `shasum` method. In theory we could just drop the path and only have the raw `shasum`, but I'd have to do some mucking around with that. 

Personally my strategy if I were checking Pods in (which I normally do) would be to `gitignore` the `.shasum` file - that way each computer building is able to check that it has the correct version locally. 

Would love to hear thoughts on whether you agree with this strategy.

**Comment by interstateone** [comment]
Ah, I see, thanks for explaining. I think I'd prefer to drop the path that shasum outputs then (ignoring a file in a dependency directory seems like a very specific and uncommon thing to do when integrating), but gitignoring the file is fine as a workaround.

**Comment by designatednerd** [comment]
OK - lemme see what I can do for the next version

**Comment by designatednerd** [comment]
@interstateone OK That wasn't as bad as I feared - #806 has this change.

**Comment by interstateone** [comment]
That's awesome, thanks for such a quick turnaround!

**Comment by designatednerd** [comment]
Luckily I am procrastinating from doing something significantly more difficult

**Comment by designatednerd** [comment]
This is now merged and ready to go out with 0.16.1, hopefully in the next day or so (I'd like to also get #804 in there as well). Will leave open until that ships.

**Comment by designatednerd** [comment]
Shipped with `0.16.1`! (pushing to `pod trunk` now, will be a few minutes before that whole folderol finishes)
