### ISSUE TITLE
How to clear cache for a single query?

### ISSUE THREAD

**Issue by koenpunt** [apollographql/apollo-ios#813]
I'm having a list of users that I follow, and they can be unfollowed from that overview;

![image](https://user-images.githubusercontent.com/351038/66217037-d7cd9b80-e6c6-11e9-8e39-a6fb02bd3706.png)

And that does update the cache for the individual item, but not for the list.

Is there a way to clear the cache for a specific query? Or should I be able to remove the updated item from the cache?

I've been looking at `store.withinReadWriteTransaction`

And what I want to achieve is something like;

```swift
let query = UserFollowingQuery(userId: "123")
store.withinReadWriteTransaction { transaction in
  try transaction.write(data: nil, forQuery: query)
}

**Comment by designatednerd** [comment]
"Clearing the cache for a single query" isn't really possible, but you're on the right track for direct cache access to manipulate the cache if need be. [Here's our documentation for updating results based on a query](https://www.apollographql.com/docs/ios/watching-queries/#update) - does that help fill in the blanks?

**Comment by designatednerd** [comment]
@koenpunt Anything else I can help with here, or do you mind if I close this issue out?

**Comment by designatednerd** [comment]
Since I haven't heard back from @koenpunt for a while I'm going to close this one out - please feel free to re-open if you need more help.
