### ISSUE TITLE
Use of undeclared type 'Result' Error ! Xcode 10.1

### ISSUE THREAD

**Issue by AhmedShammala** [apollographql/apollo-ios#815]
Hi All ,
i need help in this errors there is conflict in result type seem and other , i spent 2 day searching for solution with no luck 
it's only work if i downgrade to : 0.10.0 -> but it will get me new error `"Please update your code generation build phase script to use the new Apollo CLI"`

**Xcode** : 10.1
**Swift** : 4.2

any help will be appreciated
![image](https://user-images.githubusercontent.com/11911318/66378268-c41e7f80-e9bb-11e9-98ef-665515c0501c.png)

**Comment by AhmedShammala** [comment]
with **SQLite** and **Alamofire**  

![image](https://user-images.githubusercontent.com/11911318/66379373-faf59500-e9bd-11e9-88ee-028e617c96eb.png)

**Comment by AhmedShammala** [comment]
@designatednerd  please advice

**Comment by designatednerd** [comment]
Hi Ahmed - `Result` is a type which was added to the Swift Standard Library in Swift 5.0, and which we adopted in [version `0.13.0`](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md#v0130). In theory as long as you're on Swift 5 or higher, you should be able to compile with `Result` as it's part of the stdlib and not Foundation (although as you'll see in the release notes I linked, there will be other things you need to replace). 

Can you please double-check what version of Swift you are using in your project? If it's 4.x, you'll need to downgrade until you can update your project to Swift 5.

**Comment by AhmedShammala** [comment]
Thanks @designatednerd  for you replay , yes it's 4.2 for sure but i don't why latest swift 5 from apollo installed in cocopods while i  set this 
![image](https://user-images.githubusercontent.com/11911318/66547364-c1e92c00-eb47-11e9-8ae9-ef38ffb44437.png)


but as you see in my Question above if i downgrade there is new error pops up 

"`Please update your code generation build phase script to use the new Apollo CLI`"

Thanks for you taking time to answer me .

**Comment by designatednerd** [comment]
Hey Ahmed, I would recommend looking on GitHub at the tag for whatever version you're using - the setup instructions included in `docs/source/installation.md` *should* have the appropriate installation instructions for that version. Unfortunately there have been a number of changes to those instructions recently, so looking at the one specifically tied to the version you're using is my best advice.

**Comment by designatednerd** [comment]
@AhmedShammala Do you mind if we close this issue out since we've isolated your issue, or is there anything else I can help with here?

**Comment by AhmedShammala** [comment]
@designatednerd  Thanks , yes you can close this issue for now .
