### ISSUE TITLE
Support for semantic versioning

### ISSUE THREAD

**Issue by cameroncooke** [apollographql/apollo-ios#816]
Hi, Just wanted to ask if support for semantic versioning is being considered, given that is what SwiftPM uses for versioning? I note that quite a few minor releases have had breaking changes. Usually only major releases would have breaking API or semantic changes between releases. 

With the current versioning scheme, consumers of this package especially via SwiftPM might assume minor versions are safe to upgrade but based on recent updates would be a false assumption.

**Comment by designatednerd** [comment]
Hi Cameron - we are following SemVer in that any release with a `0.x` prefix is considered unstable and can include breaking changes in minor versions. I've added [a note about this to our setup instructions](https://www.apollographql.com/docs/ios/installation/#installing-the-apollo-framework) (see the bit below the "choose package options" screenshot) to make sure people are aware of this when they begin set up.

I do have a goal of getting us to a 1.0 release and to the more traditional use of SemVer, but there is a LOT of stuff that needs to be stabilized before we can get there, unfortunately. 

Does this answer your question?

**Comment by cameroncooke** [comment]
That makes sense, this library has been around for quite a while so had assumed it was already fairly stable. Updating the instructions will certainly help, thanks. Do you have a broad roadmap?

**Comment by designatednerd** [comment]
Yeah unfortunately there was a decent period of time where things weren't moved forward, so we're playing a bit of catch-up now.

I recently created a [ROADMAP.md](https://github.com/apollographql/apollo-ios/blob/master/ROADMAP.md) document with information about current plans. I do not have a specific point yet at which I want to call things a 1.0, but that'll come into focus as I get more stuff nailed down. 

Anything else I can help with or can we close this issue out?

**Comment by designatednerd** [comment]
Hey @cameroncooke Anything else I can help with here or do you mind if we close this out?

**Comment by cameroncooke** [comment]
Thanks so much. Yes of course you could close this issue.

**Comment by designatednerd** [comment]
You bet, thanks!
