### ISSUE TITLE
run-bundled-codegen.sh: No such file or directory Xcode

### ISSUE THREAD

**Issue by salman-ikonami** [apollographql/apollo-ios#819]
I want to integrate Apollo in Xcode And facing some issues while building phase script cocoa pod 

<img width="748" alt="Screen Shot 2019-10-09 at 3 25 05 PM" src="https://user-images.githubusercontent.com/56077512/66474541-f2c75380-eaaa-11e9-9c78-021f54a23afa.png">

**Comment by salman-ikonami** [comment]
help Apolo iOS Client

**Comment by designatednerd** [comment]
Hi Salman, what version of the iOS client are you using? If you're using a version older than `0.16.0`, the setup instructions would be different.

**Comment by salman-ikonami** [comment]
@designatednerd  the issue is resolved now , I was placing schema.json file in a right place in Xcode directories but Xcode was not placing schema.json in a right place it only shows that file is in right directory but on the back side Xcode place file In wrong directory.

**Comment by designatednerd** [comment]
OK - thanks for letting us know. Do you mind if we close this issue out?
