### ISSUE TITLE
Apollo Pod integration file count

### ISSUE THREAD

**Issue by taher-mosbah** [apollographql/apollo-ios#822]
Hello,
We are integrating Apollo latest version using Pods, doing a `find . -type f | wc -l` on `Pods/Apollo` shows 15402 files, most of those are type script source files.

The issue is, as we are committing Pods folder this is slowing down our CI build considerably, especially when cloning the project.

Is there any other ways to integrate the project without having to include all those files ?

Best,

**Comment by designatednerd** [comment]
Hey Taher, I would advise git-ignoring the `Pods/Apollo/scripts/apollo` folder if you're having issues around this. 

This is the folder that all the binaries and typescript are automatically unzipped into by the `run-bundled-codegen.sh` script. The script is set up such that as long as your CI machine has the `apollo.tar.gz` file in `scripts`, it should be able to unzip it locally.

**Comment by taher-mosbah** [comment]
thanks for your answer @designatednerd that worked great !
