### ISSUE TITLE
Apollo 0.16.1 not compiling: JSONObject not unwrapped

### ISSUE THREAD

**Issue by lillybeans** [apollographql/apollo-ios#823]
![image](https://user-images.githubusercontent.com/4432093/66580173-f7901400-eb4b-11e9-8cd1-583e822f793f.png)

Hi there, could you please push a fix for this issue?

**Comment by designatednerd** [comment]
Hi Lilly, I'm not seeing this issue either in our CI server or locally. Can you please share: 

- What version of Swift are you building with?
- What version of Xcode are you using?

**Comment by kevinjameshunt** [comment]
Hi I also see this issue in both XCode 11 and 10.3 using Swift 4.

**Comment by designatednerd** [comment]
The current version of Apollo supports Swift 5 and above. You will need to use a version prior to `0.13.0` in order to use it with Swift 4.

**Comment by lillybeans** [comment]
@designatednerd Thank you for your help!

**Comment by designatednerd** [comment]
@lillybeans You're welcome - do you mind if we close this out since we figured out what the problem was?

**Comment by designatednerd** [comment]
I'm gonna go ahead and close this out, please open a new issue if you're having related problems. Thank you!
