### ISSUE TITLE
Can we get a new apollo-ios release that uses the latest codgen?

### ISSUE THREAD

**Issue by cltnschlosser** [apollographql/apollo-ios#835]
Would like to pick up the performance fixes from https://github.com/apollographql/apollo-tooling/issues/1554

**Comment by designatednerd** [comment]
Yep, that'll be `0.17.0` - need to run a bunch of tests on a couple things before I release. Sorry, I've had an awful cold for the last week and it's basically brought progress on that to a grinding halt.

**Comment by designatednerd** [comment]
Shipped!
