### ISSUE TITLE
Eliminating Deprecated Enum Values from Code Gen

### ISSUE THREAD

**Issue by bornbnid** [apollographql/apollo-ios#840]
We are looking for a solution when updating or eliminating old enum values. Currently we've marked them deprecated, which the schema picks up on. However, in Xcode these values are still generated as part of the enums and simply marked with Xcode warnings. I'd like to remove the deprecated values instead for two reasons:
1) I want to take advantage of the Swift CaseIterable ability to use allCases to give me a list of values. Currently this would include the deprecated values as well.
2) This keeps a large number of warnings in the generated code file, which I can't fix because it'll will just get overridden the next time we run the Generate Apollo GraphQL API run script phase.

Ideally we'd love if there was a flag or some other way of removing these deprecated values. Thanks!!

**Comment by designatednerd** [comment]
I think having this as a flag would be a really good idea - we could also probably have an `allNonDeprecatedCases` property to help with point 1 even if you don't care about warnings in the generated code.

**Comment by designatednerd** [comment]
This has shipped with `0.18.0`!

**Comment by bornbnid** [comment]
Amazing turn around time. Thank you!

**Comment by designatednerd** [comment]
haha thank @kevinmbeaulieu, he got to it way faster than I would have 😄

**Comment by bornbnid** [comment]
Huge thanks @kevinmbeaulieu!!!
