### ISSUE TITLE
Documentation: mismatch between documentation and behaviour of cache policy

### ISSUE THREAD

**Issue by ybreleur** [apollographql/apollo-ios#841]
Hi!

We may have just encountered a mismatch between the documentation and the actual behavior of the `returnCacheDataDontFetch` Cache Policy [0].

Here is what we have until now:
- the inline documentation[1] and the `Fetching Queries` documentation [2] explain that "This policy will return nil when cached data is not available";
- but it seems that the test in [3], however, expects the JSONDecodingError.missingValue error to be the result of an empty cache;
- the point above seems to be discussed in the PR#644[4] in the comments for the file: “Tests/ApolloCacheDependentTests/FetchQueryTests.swift” and documented in the releases note for the version 0.13.0 as a “Super-Breaking” changes

In the case where our observations are correct, and if the solution resides in the update of the documentation, we then would like to submit a PR to your approval.

Could we please have your insight on this?

Thank you very much, have a nice day!

[0] https://github.com/apollographql/apollo-ios/blob/4f15a417776fabb19847ac6481e6fea6efdf6398/Sources/Apollo/ApolloClient.swift#L13

[1] 
https://github.com/apollographql/apollo-ios/blob/4f15a417776fabb19847ac6481e6fea6efdf6398/Sources/Apollo/ApolloClient.swift#L12

[2] https://github.com/apollographql/apollo-ios/blob/master/docs/source/fetching-queries.md#specifying-a-cache-policy

[3] https://github.com/apollographql/apollo-ios/blob/4f15a417776fabb19847ac6481e6fea6efdf6398/Tests/ApolloSQLiteTests/CachePersistenceTests.swift#L109

[4] https://github.com/apollographql/apollo-ios/pull/644/files#r304442780

**Comment by designatednerd** [comment]
Thanks for the detailed report! I need to look at what's going on there but I suspect one of the changes led to incorrect behavior that I accidentally reinforced in a test when I was still getting the hang of things.

**Comment by designatednerd** [comment]
@ybreleur Yeah looking at the discussion it was the docs that were wrong. I've updated this as part of a larger update of the caching documentation in #851 - please take a look at that, I plan to close this issue out once that's merged, so I'd appreciate any feedback!

**Comment by designatednerd** [comment]
@ybreleur Feel free to leave comments on the closed PR if you have 'em. I'm going to close this out as addressed since this is now merged.
