### ISSUE TITLE
Error On Compile 

### ISSUE THREAD

**Issue by ashishpatelmi** [apollographql/apollo-ios#844]
ConferencePlanner-frqygtzmfongvpbnhaogiwthbrko/Build/Intermediates.noindex/ConferencePlanner.build/Debug-iphonesimulator/ConferencePlanner.build/Script-551E324E1E83FE9800F32DDA.sh: line 10:  Xcode/DerivedData/ConferencePlanner-frqygtzmfongvpbnhaogiwthbrko/Build/Products/Debug-iphonesimulator/Apollo/Apollo.framework/check-and-run-apollo-codegen.sh: No such file or directory

**Comment by koenpunt** [comment]
Have a look here: https://www.apollographql.com/docs/ios/installation/#cocoapods-run-script

The script should be `run-bundled-codegen.sh`, not `check-and-run-apollo-codegen.sh`.

**Comment by designatednerd** [comment]
@ashishpatelmi Yep, Koen is correct. Did updating to the current run script fix your problem?

**Comment by designatednerd** [comment]
Since I haven't heard back on this issue in a couple weeks, I'm going to close it out. Please reopen if you're still having issues with the same version, or if you're having issues with a newer version, open a new issue. Thank you!
