### ISSUE TITLE
Carthage build of 0.18.0 links to TSAN library

### ISSUE THREAD

**Issue by bwhiteley** [apollographql/apollo-ios#859]
A carthage build of 0.18.0 produces an Apollo library that is linked against 
libclang_rt.tsan_iossim_dynamic.dylib. Is this intentional? It is breaking our app builds. 

```
$ echo 'github "apollostack/apollo-ios" ~> 0.18' > Cartfile
$ carthage bootstrap --platform ios
*** No Cartfile.resolved found, updating dependencies
*** Fetching apollo-ios
*** Checking out apollo-ios at "0.18.0"
*** xcodebuild output can be found in /var/folders/4r/5rcyrj_55nsf7c73sprfyn7r0000gr/T/carthage-xcodebuild.lZesA3.log
*** Building scheme "Apollo" in Apollo.xcworkspace
*** Building scheme "ApolloSQLite" in Apollo.xcworkspace
*** Building scheme "ApolloWebSocket" in Apollo.xcworkspace
$ otool -L Carthage/Build/iOS/Apollo.framework/Apollo 
Carthage/Build/iOS/Apollo.framework/Apollo:
	@rpath/Apollo.framework/Apollo (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1670.10.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	@rpath/libclang_rt.tsan_iossim_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1670.10.0)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 1100.2.255)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 0.0.0)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 0.0.0)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 0.0.0)
$
```

**Comment by designatednerd** [comment]
Ugh, Carthage, you’re killing me. Nope, not intentional. 

Will fix in the morning on the repo but since I’m AFK you can fix if go into `Carthage/Checkouts/Apollo-iOS`, open `Apollo.xcworkspace` and uncheck the thread sanitizer in the Run option for the Apollo scheme (and ApolloWebSocker and ApolloSQLite schemes if you’re using those), then running `carthage build` again.

**Comment by designatednerd** [comment]
Out as `0.18.1`. Thanks for reporting!

**Comment by Benuuu** [comment]
@designatednerd should we be concerned that TSAN was firing quite often?

**Comment by designatednerd** [comment]
It's [on my list of things to look into](https://github.com/apollographql/apollo-ios/issues/600) - I'm gonna be mostly tied up with GraphQL summit next week, but week after I should be able to take a run at it. If you can leave some details in that thread about where, specifically, it was firing a ton for you, I'd appreciate it.

Would love any help from the community if folks have time though!
