### ISSUE TITLE
Using meteor and apollo/graphQL together.

### ISSUE THREAD

**Issue by cerupcat** [apollographql/apollo-ios#86]
We're currently using meteor-ios, but are considering migrating or slowly adding in apollo/graphQL into our app. How would authentication work where it can be shared across both and is there a way for data to be shared as well? Any insights on how to run both at the same time where a user may need to be logged in through both?

**Comment by martijnwalraven** [comment]
I don't know of anyone who has attempted to use Meteor iOS and Apollo iOS together, but there is a [Meteor integration package for Apollo](http://dev.apollodata.com/core/meteor.html) that allows you to pass in a login token through a `meteor-login-token` header. You may be able to use the server part of that and set the token on the header yourself from Apollo iOS.

There is no easy way to share data, the store formats and APIs are pretty different. But you could use data from both in your UI of course.

**Comment by cerupcat** [comment]
Thanks @martijnwalraven. I'll take a look to see how passing a `meteor-login-token` in the header works. Is there already an example for that?

**Comment by martijnwalraven** [comment]
There is documentation on [adding additional headers](http://dev.apollodata.com/ios/initialization.html#adding-headers), although we still need to make this more flexible so you don't have to create a new client when the token changes.
