### ISSUE TITLE
Incorrect cache keys being generated

### ISSUE THREAD

**Issue by parrotbait** [apollographql/apollo-ios#860]
Apollo version: 0.18.0
Xcode: 11.0

The original issue occurred as I had a mutation on a type, 'Merchant' in my case. I was changing the email address in the mutation, the mutation result returns the new email along with the id and typename of the Merchant object but the internal Apollo store was not reflecting this result but returning stale data. If I forced a refresh of the cache from remote the cache is updated. 

After much debugging I resolve that the root cause is from the types `cacheKeyForObject` receives. Depending on the types a cache key is generated with or without embedded double quotes.

My `cacheKeyForObject` closure looked like the following:
```
client.cacheKeyForObject = { (object) in
  if let id = object["id"], let type = object["__typename"] {
      return [type, id]
  }
  // No id or typename, don't do caching
  return nil
}
```

What I'm seeing is sometimes the following cache key is generated:
```
Optional(\"Merchant\")_Optional(\"29448d02-0567-4ea1-bf31-xxxxxxxxxx\").email
```

Other times I got back:
```
Optional(Merchant)_Optional(29448d02-0567-4ea1-bf31-xxxxxxxxxx).email
```

Because the cache key is used as the basis for many matching operations (such as `!dependentKeys.isDisjoint(with: changedKeys)`) the embedded quotes causes any string matching and set unions to incorrectly fail. Thus some watchers were returning stale data from the store.

I think I've tracked down why it happens. I receive into my cacheKeyForObject closure different types for the `id` and `typename` in the JSONObject. When the version with quotes is generated both are of type `String`.

When there's an id of type `__NSCFString` and the __typename of `NSTaggedPointerString` I don't get back quotes. It looks to me that these types are coming directly from a network call but I hadn't time to properly unravel the callstack to truly verify this.

The returned values from `cacheKeyForObject` are used in `cacheKey(for object: JSONObject)`. So eventually `String(describing: $0)`is the culprit, it interprets the types differently, returning quotes or not.

The workaround for now, for me at least, is to do an intermediate copy of the id & type before returning to Apollo. 
```
client.cacheKeyForObject = { (object) in
  if let id = object["id"], let type = object["__typename"] {
      if let idStr = id as? String, let typeStr = type as? String {
          return [String(describing: idStr), String(describing: typeStr)]
      }
      return [id, type]
  }
  // No id or typename, don't do caching
  return nil
}
```

As __NSCFString and NSTaggedPointerString both can be optionally casted to String this means that at least a string is being returned to Apollo and all cache keys at least will have the quoted version. String matching works and the internal store is correctly updated. 

I'm not entirely sure what the correct fix is here. Perhaps just a documentation issue, I don't like that cacheKeyForObject has branching and logic in it. Open to ideas on this one, if it could be fixed in the library that would be great too. I'm concerned that this same issue may also exist elsewhere, hopefully it's just here.

**Comment by designatednerd** [comment]
Woof, yeah, that's getting wayyyy too deep into the internals of how everything's working. 

What about using: 

```swift
client.cacheKeyForObject = { (object) in
  if 
    let id = object["id"] as? String,
    let type = object["__typename"] as? String {
      return [id, type]
  }
  // No id or typename, don't do caching
  return nil
}
```

That should require you to get strings back, and allow you to avoid all of the nonsense with optionals or needing `String(describing:)`.

**Comment by parrotbait** [comment]
Both `NSTaggedPointerString` and `__NSCFString` were succesfully casting to `String` which surprised me and why I added in the extra `String(describing:`.

I debated your suggestion earlier too but also thought that as object can have id and __typename as `Any` then is there a chance that `as? String` will return nil whereas `String(describing:` internally will actually return valid string? 
So I would be incorrectly saying to apollo to not cache even though later on the string creation is a success.

For example, `String(describing:` [works with `CustomStringConvertible` protocols ](https://developer.apple.com/documentation/swift/string/2427941-init)
id could be a [`UUID` type](https://developer.apple.com/documentation/foundation/uuid) and conforms to `CustomStringConvertible` but would fail the cast to String but would succeed with `String(describing:` 
So I decided to let it fall through to return the [Any, Any]` in the case it may actually work internally in Apollo.

**Comment by designatednerd** [comment]
`__typename` should definitely always be a `String`.

From the [docs on GraphQL ID](https://graphql.org/learn/schema/#scalar-types) (emphasis mine):

> **The ID type is serialized in the same way as a String**; however, defining it as an ID signifies that it is not intended to be human‐readable.

You'll also notice that within this library, we've got [`GraphQLID` as a typealias of `String](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/GraphQLInputValue.swift#L104).

I think part of the confusion is that `JSON` is basically an abstraction over a dictionary, which is why you see so much stuff with `Any`. I'm planning on [moving parsing and codegen to using `Coadable`](https://github.com/apollographql/apollo-ios/issues/467) as part of the Swift Codgen project, which I think will make this distinction start to go away.

**Comment by parrotbait** [comment]
Ah ok got it thanks. 
I still have the issue with `NSTaggedPointerString ` and `__NSCFString` correctly casting to String and then incorrectly generating the string within Apollo so the intermediate String copy I do now needs to stay to resolve that issue. Just casting to a string doesn't resolve - though I need to double check that.

**Comment by designatednerd** [comment]
I *think* that's an issue related to using `String(describing:)` so this strategy would help, but let me know what your follow-up investigation finds.

**Comment by designatednerd** [comment]
@parrotbait Any luck?

**Comment by parrotbait** [comment]
Sorry - hectic at $dayjob, will get on this first thing next week

**Comment by parrotbait** [comment]
Ok I tried the solution you suggested above. Works well and is cleaner than the one I had. 

Thanks!

**Comment by designatednerd** [comment]
OK cool - I'll take a look at it. Thank you!
