### ISSUE TITLE
Upload file in iOS Apollo Client issue

### ISSUE THREAD

**Issue by salman-ikonami** [apollographql/apollo-ios#861]
mutation uploadFile($file:Upload!,$business_id:String!){

uploadFile(file: $file,business_id: $business_id)

}

how to upload single png image on GraphQl server using iOS Apollo Client

**Comment by designatednerd** [comment]
Hi Salman, please check out the [upload documentation](https://www.apollographql.com/docs/ios/mutations/#uploading-files) and let me know how that goes.

**Comment by salman-ikonami** [comment]
I don't understand the documentation regarding file upload (the code which is given in documentation is not working)

 
**My Cede**

//1. this is my mutation which takes Upload type object 

mutation uploadFile($file:Upload!,$business_id:String!){

uploadFile(file: $file,business_id: $business_id)

}



//2 but I can't get any Upload type object in my swift code instead I am getting string rather then Upload Object

       guard
            let fileURL = Bundle.main.url(forResource: "a",
                                          withExtension: "txt"),
            let file = GraphQLFile(fieldName: "file",
                                   originalName: "a.txt",
                                   mimeType: "text/plain", // <-defaults to "application/octet-stream"
                fileURL: fileURL) else {
                    // Either the file URL couldn't be created or the file couldn't be created.
                    return
        }


client.perform(mutation: UploadFileMutation(file: <String>, business_id: <String>))

**Comment by salman-ikonami** [comment]
<img width="642" alt="Screen Shot 2019-10-25 at 10 42 27 AM" src="https://user-images.githubusercontent.com/56077512/67545873-2abdd000-f714-11e9-8f2f-6066a2baac6a.png">

**Comment by salman-ikonami** [comment]
file is taking string but I want file to be Data

**Comment by salman-ikonami** [comment]
like in android we have to define this  in build.gradel
 customTypeMapping = [
                "Upload": "com.apollographql.apollo.api.FileUpload"
        ]

**Comment by salman-ikonami** [comment]
swift is not recognizing Upload type

**Comment by designatednerd** [comment]
You need to use [the `upload` method](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/ApolloClient.swift#L172) rather than the `perform(mutation)` method on `ApolloClient`. Under the hood, that replaces the `String` that's expected in the codegen'd initializer with the file data. 

The iOS client doesn't support type mapping (yet), so it will not work the same as the Android client.

**Comment by salman-ikonami** [comment]
<img width="935" alt="Screen Shot 2019-10-26 at 5 39 22 PM" src="https://user-images.githubusercontent.com/56077512/67619652-8f158800-f817-11e9-930d-cde5f78a5879.png">

**Comment by salman-ikonami** [comment]
upload function is not available in my Apollo iOS Client, how can get this upload function

**Comment by designatednerd** [comment]
You will likely need to check what version of the client you are using and upgrade - the upload function was added in [`0.13.0`](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md#v0130). The current version of the library is now `0.18.1`.

**Comment by salman-ikonami** [comment]
<img width="1016" alt="Screen Shot 2019-10-27 at 9 56 57 AM" src="https://user-images.githubusercontent.com/56077512/67629949-a2206a80-f8a0-11e9-8af7-0c3bf8898094.png">

**Comment by salman-ikonami** [comment]
my Apollo iOS Version is 0.13.0 but still I am not getting upload function in Apollo

**Comment by designatednerd** [comment]
Apologies, the basic upload functionality was added in `0.13.0`, but that method was not added to the main `ApolloClient` class until `0.15.0`.

**Comment by salman-ikonami** [comment]
can you provide some demo iOS application (github link) that uses Apollo iOS client for the guidance?

**Comment by designatednerd** [comment]
Not at the moment, but I'm going to be working on an updated sample app over the next few weeks - I will try to work with our team to add something that showcases this.

**Comment by salman-ikonami** [comment]
How to config Apollo Client to Upload file?



This is my Apollo Client which is working. How to modify this client to be able to upload file ?

    static let apolo: ApolloClient = {
        let config = URLSessionConfiguration.default
        config.httpAdditionalHeaders = ["x-token": "\(GlobalData.token)"]
        let url = URL(string: endPoint)!
        return ApolloClient(networkTransport: HTTPNetworkTransport(url: url))
    }()

**Comment by salman-ikonami** [comment]
<img width="1267" alt="Screen Shot 2019-11-01 at 3 58 33 PM" src="https://user-images.githubusercontent.com/56077512/68020528-9548b000-fcc0-11e9-87e0-ab40dfd0a600.png">

Error While Uploading File

**Comment by designatednerd** [comment]
I would double check the name of the property that you're setting for the file - the `fieldName` in the `GraphQLFile` initializer should be what your field is called when it goes to the server. I *think* from looking at the generated code it should be `"file"` rather than `"salman"`. 

The error is definitely coming from your server, but it makes sense that if the `file` field doesn't have anything in it, that would be the error returned.

**Comment by salman-ikonami** [comment]
This is my Apollo iOS Client V0.13 but in v 0.19 this code is not working, What is the alternative code for this in v0.19 

 let config = URLSessionConfiguration.default
        //config.httpAdditionalHeaders = ["Authorization": "Bearer \(BearerToken)"]
        config.httpAdditionalHeaders = ["x-token": "\(GlobalData.token)"]
        let url = URL(string: endPoint)!
        let apolloTokenClient = ApolloClient(networkTransport: HTTPNetworkTransport(url: url, configuration: config))

**Comment by designatednerd** [comment]
The `HTTPNetworkTransport` takes a `URLSession` rather than a `URLSessionConfiguration` now. You will need to pass that config to a `URLSession` and then pass that session through to the `HTTPNetworkTransport` initializer: 

```
let config = URLSessionConfiguration.default
config.httpAdditionalHeaders = ["x-token": "(GlobalData.token)"]
let url = URL(string: endPoint)!
let session = URLSession(configuration: config)
let apolloTokenClient = ApolloClient(networkTransport: HTTPNetworkTransport(url: url, session: session))
```

**Comment by designatednerd** [comment]
@salman-ikonami Did that help?

**Comment by DeekshaApptunix** [comment]
@designatednerd 

I  am uploading image like this 

if let imageData = userImgVew.image?.jpegData(compressionQuality: 0.8) {
            let file = GraphQLFile(fieldName:"file", originalName:"file.png", mimeType: "image/png", data:imageData)

 let uploadData = UpdateUserProfileMutation(userId:id, userImage:file.originalName, userDetail: userDict)
        apollo.upload(operation:uploadData,files: [file])

But getting following error

createReadStream is not a function

**Comment by designatednerd** [comment]
Hey @DeekshaApptunix, let's focus discussion on your issue at #938. 

Since I haven't heard back from @salman-ikonami in several weeks, I'm going to close this issue out. Note that I'm going to be adding an uploading section to the new tutorial (hopefully before the end of the year), hopefully that'll help make some of this stuff clearer. 

Salman, please feel free to reopen this issue if you're still having problems. Everyone else, please open a new issue. Thank you!

**Comment by DiwakarThapa** [comment]
@designatednerd I am having a problem in uploading an image in ios apollo client. after I upload an image I get a **GraphQlError "createReadStream is not a function".**  . I could not figure out what has gone wrong ? 
**Mutation** 
```
mutation UploadPhoto($input: UploadPhotoInput){
  uploadClientPhoto(input: $input){
    photo
  }
}
**Type Detail** 
```
type UploadPhotoInput {
photo: Upload
}
6:20
type UploadPhotoResponse {
photo: String
}
```
```
**This code is not working** 
```
class Network {
  static let shared = Network()
 
  private lazy var networkTransport = HTTPNetworkTransport(url: URL(string: "http://192.168.10.29:5001/graphql")!, session: .init(configuration: URLSessionConfiguration.default))
   
  private(set) lazy var apolloCient = ApolloClient(networkTransport: networkTransport)
}

if let data = singlePhoto.image.jpegData(compressionQuality: 0.8) {
          let name = UUID().uuidString
          let file = GraphQLFile(fieldName: "\(name)", originalName: "\(name).png",mimeType: "image/png" ,data: data)
          
          let uploadInput = UploadPhotoInput(photo: file.originalName)
          let uploadMutation = UploadPhotoMutation(input: uploadInput)
//
          Network.shared.apolloCient.upload(operation: uploadMutation, context: nil, files: [file]) { (result) in
            switch result {
            case .success(let success):
              print(success.data)
            case .failure(let error):
              print(error.localizedDescription)
            }
          }
          
        }
```
