### ISSUE TITLE
Code sign failure after 0.16.1 update

### ISSUE THREAD

**Issue by diegoventura** [apollographql/apollo-ios#865]
👋 

I'm having issues with codesign after migrating Apollo client to 0.16.1. 

I can build and run normally on the simulator, but when archive and trying to install it on a device, I'm getting a `This application’s bundle identifier does not match its code signing identifier.` error when running on a device and `Code signing "Apollo.framework" failed.` when trying to archive manually. Distribution logs didn't help that much 😞.

It seems that there were some issues with codesign back in 2016 which seems to be resolved already.

Let me know if you need any further information.

Thanks

**Comment by designatednerd** [comment]
Hi Diego, what dependency manager are you using - Cocoapods, Carthage, SPM?

**Comment by diegoventura** [comment]
Hey! I’m using Carthage and already updates the run script phase to us the one bundled on the checkout folder.

I also tried to update to 0.18.1 but no success.

**Comment by designatednerd** [comment]
Have you followed the [Carthage instructions around setting up a build phase to work around a submission bug](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos)? I believe that issue is also related to other signing problems.

**Comment by designatednerd** [comment]
@diegoventura Any luck?

**Comment by diegoventura** [comment]
👋 

Sorry for the late response (weekend+meetings)

Yes! I followed steps 4-9 and it worked. Previously we were embedding `Apollo.framework` on the main target + adding it to the input files on `run phase script`. Now I'm trying to figure out why it was working before.

Thanks for the help!

**Comment by designatednerd** [comment]
Ah, my favorite phrase of bug hunting: "How did this EVER work?!"

Glad you were able to get it fixed up!
