### ISSUE TITLE
Update to Swift 5.1.1 for Xcode 11.2

### ISSUE THREAD

**Issue by MaruthiBasava** [apollographql/apollo-ios#870]

**Comment by designatednerd** [comment]
Hi! Xcode 11.2 has not yet been released, it's still in Beta (as of....21.44 PST on 28 October) . 

I'm assuming it will be soon since iOS 13.2 just got released today, but support on our end will need to wait until 11.2 hits the MAS.

**Comment by designatednerd** [comment]
@MaruthiBasava Final version is finally out - I'm able to do stuff like add `Identifiable` conformance without issue in 11.2 (which was added in Swfit 5.1). Is there anything specific you are seeing problems with on the final version of Xcode 11.2?

**Comment by designatednerd** [comment]
The only change I've been able to find is updating the tooling version for Swift Package Manager to 5.1 - this will ship with `0.20.0`.

**Comment by designatednerd** [comment]
Shipped!
