### ISSUE TITLE
No ability to customize Content-Type header

### ISSUE THREAD

**Issue by spencer-microsoft** [apollographql/apollo-ios#875]
We need to be able to set the "Content-Type" header as "application/json; charset=utf-8", but the client is hardcoded to set "Content-Type" as "application/json".

This header is set [here](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/HTTPNetworkTransport.swift#L377) and overwritten for multi-part requests, but we need this charset added to the header for non-multi-part requests.

**Comment by koenpunt** [comment]
There's the `HTTPNetworkTransportPreflightDelegate` which you can implement to modify or add additional headers;

```swift
class GraphQLClient {
    init() {
        let transport = HTTPNetworkTransport(url: "https://...", delegate: self)
        let client = ApolloClient(networkTransport: transport)
        // ....
    }
}

extension GraphQLClient: HTTPNetworkTransportPreflightDelegate {
    func networkTransport(_ networkTransport: HTTPNetworkTransport, shouldSend request: URLRequest) -> Bool {
        return true
    }

    func networkTransport(_ networkTransport: HTTPNetworkTransport, willSend request: inout URLRequest) {
        request.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
    }
}
```

**Comment by designatednerd** [comment]
Yep @koenpunt is exactly correct, that's where you should make this change.

**Comment by designatednerd** [comment]
@spencer-microsoft Did this help you out?

**Comment by designatednerd** [comment]
Since I haven't heard back and there is a definite way to do this, I'm going to go ahead and close this issue out. Please reopen if you are still having problems after trying the above suggestions. Thank you!

**Comment by spencer-microsoft** [comment]
Confirmed that works, thanks!
