### ISSUE TITLE
NetworkTransport's new `client*` property requirements require setters?

### ISSUE THREAD

**Issue by cysp** [apollographql/apollo-ios#877]
The `clientName` and `clientVersion` requirements that have been added to the `NetworkTransport` protocol are marked as requiring both getters and setters, is that intentional? 
The upshot of requiring setters is that conforming implementations must expose those fields as externally mutable properties of at least as high visibility as the type itself, which they probably don't want to do.

I've modified that protocol locally to only require getters and everything compiles so if there's no reason to require the setter, I'm happy to raise a PR reducing the requirement to just the getter. 🙂

```diff
diff --git i/Sources/Apollo/NetworkTransport.swift w/Sources/Apollo/NetworkTransport.swift
index 44adee10..09f2806d 100644
--- i/Sources/Apollo/NetworkTransport.swift
+++ w/Sources/Apollo/NetworkTransport.swift
@@ -12,10 +12,10 @@ public protocol NetworkTransport: class {
   func send<Operation>(operation: Operation, completionHandler: @escaping (_ result: Result<GraphQLResponse<Operation>, Error>) -> Void) -> Cancellable
   
   /// The name of the client to send as the `"apollographql-client-name"` header.
-  var clientName: String { get set }
+  var clientName: String { get }
   
   /// The version of the client to send as the `"apollographql-client-version"` header
-  var clientVersion: String { get set }
+  var clientVersion: String { get }
 }
 
 public extension NetworkTransport {
```

**Comment by designatednerd** [comment]
Hey Scott, this was an explicit architectural decision to support being able to change the property after initialization. The anticipated use case is something like this:

I'm running an A/B test, and I want to make sure I can identify which of the A/B buckets the current user is in when I call my GQL API, but I can't get the information of _which_ bucket this user should be in without first calling my GQL API. 

Without the ability to set after instantiation, I'd have to completely tear down and rebuild my `ApolloClient` almost immediately after setting it up, or I'd have to use separate client instances to get the A/B bucket information and then do the rest of my calls.

This is certainly not a default setup, but particularly in larger companies, this is a frequent enough situation that I think it's worth explicitly exposing this with a setter.  

Does that make sense? Or do you have alternate thoughts on downsides of exposing the setter?

**Comment by cysp** [comment]
Ah, okay. That makes sense, and I can certainly see how it could be desirable to modify the client identifiers at runtime, so I think this becomes a question of program design and if you want to impose that requirement on all implementors of `NetworkTransport` or if it's okay for that use case to be met by providing mutable properties on the _`HTTPNetworkTransport`_ implementation, which would allow the properties to be changed at runtime for users of that implementation
without requiring all `NetworkTransport`s to similarly have to support runtime changes.

The trade-off there would be that client code would have to keep a reference to the instantiated `HTTPNetworkTransport` and would set the properties on that rather than accessing it through `ApolloClient.networkTransport`. (Alternatively, client code could access `.networkTransport` and type-cast, but that's a bit yuck.)

I don't personally have the requirement to modify those identifiers at runtime so it's hard for me to say whether that would be an acceptable solution or alternatively if the requirement is common enough that it makes sense to require that all network transports support it. 🙃

**Comment by designatednerd** [comment]
At this point all of our internally-built network transports (including `WebSocketTransport` and `SplitNetworkTransport`) do support the ability to re-set these properties, so to me that makes it reasonable to say that having a setter is a requirement of the protocol. 

I think it would help to understand what you see as the disadvantage of making this settable beyond the general principle of not wanting to make more things public than necessary. I definitely agree that's a good principle, but I think in this case it seems like we're setting the expectation that this is resettable on all batteries-included implementations, so it's reasonable to say that it ought to be resettable on custom implementations. 

What's your take on that?

**Comment by cysp** [comment]
I feel like the question of making it a requirement that custom transports support changing this at runtime is related to but not answered by the fact that all of the first-party transports do support it. I think that making it a requirement of the protocol requires answering the question "should consumers of `ApolloClient` be able to mutate `client.networkTransport.clientId` or is that advanced functionality that it's okay to require additional code for?".
As the provider of this library, it's certainly Apollo's prerogative to answer that in whichever way you choose, and if the answer is yes then this protocol definition makes total sense. 🙂 

You're right, my opinion on this is driven by the principle of exposing the least API surface area as possible, but its subtly different to the property being public because it requires implementors to provide additional functionality which they might not even be able to provide. The websocket transport actually seems like at least a partial point against making this functionality required because the documentation indicates that it's not able to provide full support for changing the values at runtime and that changes will only take effect at the next reconnection, some time in the future.

As I said though, if Apollo want consumers to be able to twiddle those values through `ApolloClient` then this is the right protocol definition and I'll just have to add support for it in my custom network transport (implemented for authorisation injection before the introduction of `RequestCreator` and the retry delegate).

**Comment by designatednerd** [comment]
It could be worth seeing if the batteries-included implementations cover what you're looking for now, we've made a large number of improvements there. 

I would like to keep this as a requirement for all implementations. If we're going to tell users (and do by implementing in all batteries-included classes) that they should be able to change these properties, then this should be a requirement of the class.

**Comment by cysp** [comment]
Cool, no worries then 🙂

**Comment by designatednerd** [comment]
Thank you!
