### ISSUE TITLE
Save graphql type in UserDefaults

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-ios#886]
Hello,
How can  we save graphql type into userdefaults ?
Iam trying the following

     static var defaultSelectedCity: CityDetails? {
        get {
            if let decoded = UserDefaults.standard.object(forKey: "selected-city") as? Data {
                // NSKeyedUnarchiver.unarchiveObject(with: decoded) as! JSONObject

                do {
                    let decodedCityObject = try NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(decoded) as? CityDetails
                    return decodedCityObject
                } catch {
                    return nil
                }
            }

            return nil
        }
        set {
            do {
                let encodedData: Data = try NSKeyedArchiver.archivedData(withRootObject: newValue?.jsonObject , requiringSecureCoding: false)
                UserDefaults.standard.set(encodedData, forKey: "selected-city")
                UserDefaults.standard.synchronize()
            } catch {
                UserDefaults.standard.set(nil, forKey: "selected-city")
                UserDefaults.standard.synchronize()
            }
        }
    }

But saving  failes

**Comment by designatednerd** [comment]
Unfortunately `JSONObject` can't be serialized directly by a keyed archiver at this time, since the current version doesn't conform to `Codable`. That's coming, but I don't have a timeline quite yet. 

In this instance what I'd do as a workaround is create a `Codable` object that takes our generated object in a convenience initializer with the same properties. 

It's annoying, but for now it's probably faster than trying to make `JSONObject` dump out serialized JSON, since it's only set up for deserialization rather than serialization.

**Comment by designatednerd** [comment]
Unfortunately `JSONObject` can't be serialized directly by a keyed archiver at this time, since the current version doesn't conform to `Codable`. That's coming, but I don't have a timeline quite yet. 

In this instance what I'd do as a workaround is create a `Codable` object that takes our generated object in a convenience initializer with the same properties. 

It's annoying, but for now it's probably faster than trying to make `JSONObject` dump out serialized JSON, since it's only set up for deserialization rather than serialization.

**Comment by designatednerd** [comment]
@sam961 did that answer your question?

**Comment by designatednerd** [comment]
Since I haven't heard back on this one in several months, I'm going to close this issue out. @sam961, please feel free to reopen if you have further questions - anyone else, please open a new issue. Thank you!

**Comment by pallaviashim7** [comment]
@designatednerd Is this feature out yet?

**Comment by pallaviashim7** [comment]
@designatednerd I have the same question. Do we still need to do the workaround as you mentioned above?

**Comment by designatednerd** [comment]
Yes, the workaround is still necessary

**Comment by joshuazmiller** [comment]
Not having an offline cache, plus not having a way to encode/decode a result using `Codable` (which could be used to easily store/restore the data via `UserDefaults`) is in my case a major limitation of Apollo iOS that I wish was disclosed early on.

When I read about Apollo's caching functionalities I wrongly believed that this included the ability to persist cache between opens, that it supported some form of offline caching fallback, and also assumed that codegen would produce `Codable` compatible results. I really hope this makes it onto the roadmap and that these limitations are disclosed more clearly as it sucks to realize these limitations after so much time and investment integrating with Apollo.

> In this instance what I'd do as a workaround is create a Codable object that takes our generated object in a convenience initializer with the same properties.

Can you kindly provide a code snippet of what this might look like for a nested object? Thank you.

**Comment by designatednerd** [comment]
There is a `SQLiteNormalizedCache` available that persists between sessions [if you add the `ApolloSQLite` dependency](https://www.apollographql.com/docs/ios/caching/#sqlite-cache), and provides some offline functionality (it does not sync changes after reconnect). 

> Can you kindly provide a code snippet of what this might look like for a nested object? Thank you.

So for example if you have some structure like this: 

```swift
class SomeType {
   let id: GraphQLID
   let isbn: String
   let nested: NestedType
   class NestedType {
      let id: GraphQLID
      let name: String
   }
}
```

You can declare the following codable structs with convenience initializers:

```
struct NestedCodableType: Codable {
  let id: GraphQLID
  let name: String

  enum CodingKeys: CodingKey {
     case id
     case name
  }

  init(_ nested: SomeType.NestedType) {
    self.id = nested.id
    self.name = nested.name
  }
}

struct SomeCodableType: Codable {
   let id: GraphQLID
   let isbn: String
   let nested: NestedCodableType 

  enum CodingKeys: CodingKey {
    case id
    case isbn
    case nested
  }

   init(_ someType: SomeType) {
      self.id = someType.id
      self.isbn = someType.isbn
      self.nested = NestedCodableType(someType.nested)
   }
}
```

**Comment by joshuazmiller** [comment]
> There is a SQLiteNormalizedCache available that persists between sessions if you add the ApolloSQLite dependency, and provides some offline functionality (it does not sync changes after reconnect).

Thank you for the pointer. You are right, this does help a ton with caching between sessions. And thank you for the snippet too.
