### ISSUE TITLE
Cannot debug view hierarchy after updating from 0.15.1 to 0.20.0

### ISSUE THREAD

**Issue by JimRoepcke** [apollographql/apollo-ios#912]
Using Xcode 11.1.

I updated my project from Apollo 0.15.1 to 0.20.0, and now when I try to debug the view hierarchy, I get this:

![image](https://user-images.githubusercontent.com/39997/69108825-b9c7ba80-0a2a-11ea-9157-ee6dc49958ff.png)

![image](https://user-images.githubusercontent.com/39997/69108845-c3512280-0a2a-11ea-9c34-615176f07858.png)

I have a separate commit in my git repo for JUST the changes to Apollo. If I check out the commit before these changes, I can use the view hierarchy debugger. If I check out the commit with this update, it breaks again. I have tried this several times to be sure it wasn't a fluke.

I have submitted a bug report at Apple (FB7454708).

**Comment by designatednerd** [comment]
Wow, that's *really* bizarre. A few questions to try to figure out WTF is happening here: 

- What dependency manager are you using?
- Is this happening on one machine or multiple machines?
- Are you on 11.2.1 for Xcode or another version?

**Comment by JimRoepcke** [comment]
Xcode 11.1. I’ll upgrade to 11.2.1 tomorrow.

Only using Xcode 11’s SPM support.

So far I’ve only tried one machine.

**Comment by designatednerd** [comment]
OK - I'd say it's worth upgrading to 11.2.1 and checking if you're still seeing this behavior, then trying an alternate machine to see if maybe something weird is going on in your local machine

If both of those are still showing the problem and you're willing to share the repo with me, please drop me an email at ellen at apollographql dot com.

**Comment by JimRoepcke** [comment]
Same issue with 11.2.1.

**Comment by JimRoepcke** [comment]
Removing the Apollo dependency from my App target's project fixed the problem. I still have an Apollo in a framework target in a separate project, but I wasn't actually using Apollo in my app target so this wasn't needed.

**Comment by designatednerd** [comment]
I'm not sure why it only would have showed up now, but is it possible you had a circular dependency between the your framework, the app, and the Apollo framework? That'd definitely cause a lot of miscellaneous Xcode freakouts.

**Comment by designatednerd** [comment]
@JimRoepcke Is this issue still present in Xcode 11.3? There were apparently a couple weird bugs in 11.2, wondering if this was one of them.

**Comment by JimRoepcke** [comment]
@designatednerd I haven't updated to Xcode 11.3 yet. I don't have the issue anymore though because I removed the Apollo dependency from my app and limited it to the framework.

Regarding your other question... to make a circular dependency the framework would have to depend on the app right? I'm not sure how it could have built if that was the case.

**Comment by designatednerd** [comment]
🤔Yeah, I suppose that's right. May have been throwing darts at the wall a bit with that thought - I know there's a lot of weeeeeird behaviors that have to happen to make the view debugger work.

**Comment by designatednerd** [comment]
Since this hasn't had any movement in a couple months, I'm going to go ahead and close this out. @JimRoepcke if you've got anything else I can help with, please feel free to reopen. Anyone else with a similar problem, please open a new issue. Thank you!
