### ISSUE TITLE
Apollo does not support anonymous operations

### ISSUE THREAD

**Issue by SagarUnagar** [apollographql/apollo-ios#915]
Hello,

I'm trying to integrate Apollo with my iOS application. While following the steps from the doc I faced one issue in run script section and that is: **Apollo does not support anonymous operations**. I also looked around the same issue on this repo but I can't able to solve my problem.

![apollo error](https://user-images.githubusercontent.com/16893693/69335192-5f289b80-0c82-11ea-9b95-ab23941efb6f.png)

Here are my project structure and run script,

![project stucture and run script](https://user-images.githubusercontent.com/16893693/69335232-77001f80-0c82-11ea-9080-5d539ef3a34e.png)

_userRegistration.graphql_ contain,

![graphql file](https://user-images.githubusercontent.com/16893693/69335403-e5dd7880-0c82-11ea-9e12-2f386655332b.png)

Any help would be appreciated!

**Comment by kimdv** [comment]
Hi! 

You need to add a query like this

```
mutation UserRegistration {
/// You query
}
```

Thus, a name for the query after the `mutation` or `query`

**Comment by SagarUnagar** [comment]
Thank you @kimdv! It works. 💯

**Comment by deve-yunush-1** [comment]
type Mutation{
     UserRegistration(
//your query
)
}
