### ISSUE TITLE
Memory leak after uploading big string

### ISSUE THREAD

**Issue by IvanovDeveloper** [apollographql/apollo-ios#92]
I take image and decode it to base64 string. Then I will sent it to server. After uploading to server, occure big memory leak, as a result of which the application crashes.

**Comment by IvanovDeveloper** [comment]
Will soon I will upload the stack trace file

**Comment by IvanovDeveloper** [comment]
https://www.dropbox.com/s/3mf4ul4rg40kndf/Memory%20leak%20-%20IvanovDeveloper.trace.zip?dl=0

**Comment by martijnwalraven** [comment]
@IvanovDeveloper: I'm not sure what I'm looking at here. What makes you think the leak is caused by Apollo iOS? Did you trace it back to any particular parts of the codebase?

**Comment by IvanovDeveloper** [comment]
Leak happened inside apollo iOS. Tomorrow I will try investigate this moment more detail

**Comment by martijnwalraven** [comment]
Going to close this for now, but feel free to reopen if it is still an issue in the latest version.
