### ISSUE TITLE
How to modify URLSessionConfiguration on ApolloClient

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [apollographql/apollo-ios#922]
With the [recent change resolving retain cycles](https://github.com/apollographql/apollo-ios/pull/854#issuecomment-545673975) our ApolloClient is going out of scope and being deallocated. We were using a computed property on our singleton class because we specify an `x-auth-token` in the URLSessionConfiguration 's `httpAdditionalHeaders` which can change throughout the lifecycle of the app. If they log out and log into a different account we can't continue using the same `x-auth-token` in the ApolloClient, so it was easy for us to create an instance for each request to ensure it would always be correctly configured. With this change we need to rethink this. Is there a way to modify the client's network transport's session's configuration's `httpAdditionalHeaders` or how would you propose fixing this?

I thought we could still create a new one but store it in a non-computed property on the class but this doesn't work for some reason, fetches never call the result handler.

Thanks!

    private var storedApollo: ApolloClient? //must be held onto strongly
    var apollo: ApolloClient {
        get {
            let configuration = URLSessionConfiguration.ephemeral
            if let authToken = RestNetworking.shared.authToken {
                configuration.httpAdditionalHeaders?["x-auth-token"] = authToken
            }
            
            let url = RestNetworking.shared.urlComponents.url!.appendingPathComponent("graphql")
            let transport = HTTPNetworkTransport(url: url, session: URLSession(configuration: configuration))
            
            storedApollo = ApolloClient(networkTransport: transport)
            return storedApollo!
        }
    }

**Comment by designatednerd** [comment]
I would recommend using the [pre-flight delegate method which allows you to modify the request rather than using the session configuration](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/HTTPNetworkTransport.swift#L24) to modify the auth token if it's changing on a regular basis rather than trying to futz with constantly recreating it.

**Comment by jordanhbuiltbyhq** [comment]
That'll do the trick thanks for the quick response!
