### ISSUE TITLE
Cannot Convert Apollo GraphQL Date to String using Explicit Typealias in Swift IOS

### ISSUE THREAD

**Issue by onizam95** [apollographql/apollo-ios#925]
can someone please guide how to map Apollo.Date to Simple String in Swift because the type Alias is giving the redeclaration error if i use the
"public typealias Apollo.Date = String"

Please not that i have to use --passThroughCustomScalars so have to parse the GraphQL Date as well now.
Any help would be appreciated

Enivironment 
XCODE 11.2.1 
SWIFT 4.2
pod 'Apollo', :git => 'https://github.com/apollographql/apollo-ios.git'

**Comment by designatednerd** [comment]
Hey @onizam95 Which version of the apollo pod are you using? If you're not specifying in your `Podfile` directly, it should be readable in your `Podfile.lock`. 

One thing to be aware of: We've gone to supporting Swift 5 since [version `0.10.0`](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md#v0100), so it's possible there might be some weird issues happening if you're using a more recent version of the library with Swift 4.2.

**Comment by onizam95** [comment]
@designatednerd  it gets it from the master release branch whichever is the latest version. i did because when we had some issue with swift 4  migrations. 
and it is basically when i write this specific code : 
"public typealias Apollo.Date = String"

because if i Write only Date = String it converts the Original Swift Date

**Comment by designatednerd** [comment]
@onizam95 What I'm saying is you should be able to  omit the `typealias` entirely. Where you were previously putting `public typealias Apollo.Date = String`, you should be able to delete it and not replace it with anything.

**Comment by onizam95** [comment]
No i can't  do that when i am passing --passThroughCustomScalar i need to handle Apollo.Date otherwise it gives errors during build

**Comment by designatednerd** [comment]
OK - is there a chance you could send me your schema and a query that uses a date? Maybe I can figure out what's going on. You can either upload here or email ellen at apollographql dot com.

**Comment by onizam95** [comment]
Please find below the schema function , also please note that multiple clients are using this schema (android,webb apps) i am just having this issue in swift 

 {
              "args": [
                {
                  "defaultValue": null,
                  "description": null,
                  "name": "billDate",
                  "type": {
                    "kind": "SCALAR",
                    "name": "Date",
                    "ofType": null
                  }
                },
                {
                  "defaultValue": null,
                  "description": null,
                  "name": "systemId",
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "SCALAR",
                      "name": "ID",
                      "ofType": null
                    }
                  }
                }
              ],
              "deprecationReason": null,
              "description": null,
              "isDeprecated": false,
              "name": "gridBillUrl",
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              }
            },

**Comment by onizam95** [comment]
@designatednerd  any update?

**Comment by designatednerd** [comment]
Hey @onizam95 - sorry, I lost this thread a while back. I'll try to take another look but can you please send me your full schema? If you don't want to post it here you can email it to ellen at apollographql dot com

**Comment by onizam95** [comment]
sure @designatednerd i'll email it to you

**Comment by designatednerd** [comment]
@onizam95 I'm sorry it's been a while since I've gotten back to you, but you may want to try something from #1019 and try namespacing your types.

**Comment by onizam95** [comment]
@designatednerd  Thanks for the mention. i'll take a look into it and get back to you.

**Comment by onizam95** [comment]
@designatednerd  just Checked yes the namespace flag and then assigning typealias in NameSpace extension fixes the conflicts but Now everywhere in the code the Graphql Type and object needs to be accessed with complete Namespace. 

Thanks I'll now close this issue
