### ISSUE TITLE
Apollo Web Socket reconnected correctly but subscriptions not working.

### ISSUE THREAD

**Issue by arnaumartifont** [apollographql/apollo-ios#928]
I have this situation:
1- Subscribe to subscriptions.
2- Receiving data from subscriptions (working).
3- Minimize iPhone app (goes to background).
4- (waiting 10s or so).
5- Maximize iPhone app (comes to foreground).
6- If i check in subscription reference I find -> "websocket close 1005 (no status)" error from Web Socket.
7- Checking Web Socket it says its reconected = true, no errors & contains the graphql subscriptions references.
8- Receiving data from subscriptions (not working).
<img width="523" alt="Screenshot 2019-11-27 at 10 20 46" src="https://user-images.githubusercontent.com/9613200/69711075-b6a28d80-1100-11ea-9604-f391c970358f.png">

**Comment by designatednerd** [comment]
Innnnteresting. Does the list of subscribers include the id of your parsing handler when you come back from the background, or is there a `weak self` somewhere in there? I'm thinking maybe something got deallocated or unsubscribed when you went to the background.

**Comment by arnaumartifont** [comment]
Yes it contains the ID, and no I don't have weak references to the subscriptions neither the classes using them, the only references I have to these subscriptions are the optionals  "Cancellable? ".

**Comment by designatednerd** [comment]
Is there any point at which you're calling `cancel` on the `Cancellable`?

Are the `UICollectionViewCell`s holding on to the subscription, or is the `UIViewController`? If it's the cells, it's possible something's getting reset when the cell is recycled.

**Comment by arnaumartifont** [comment]
No, I checkered that and the cancel method is not called.
To simplify it for now, The first scenario i found this situation is only a UIViewController, without any CollectionView just a map and some views, and the controller have that Cancellable reference to the subscription.

**Comment by designatednerd** [comment]
Oof. Yeah, I've got no idea in that case. Could you send me either your project (or a sample if your actual project is not project) at ellen at apollographql dot com?

**Comment by arnaumartifont** [comment]
That will be a bit complicated, i'll do some testing to see if I can figure something out, I'll reach you back if I find something or I can prepare a project example with the problem.

**Comment by arnaumartifont** [comment]
I Can share that, from the Cancellable, sequenceNumber = 12 (I understand that is the key to reference it) I have that information, but checking the websocket reference (like the first image I shared it) the subscribers/subscriptions dictionaries doesn't contain the key ="12", I see other keys that are short numbers as well. 

I can mention another thing, there are subscriptions that are working, the only difference is that are being used with RxSwift.

<img width="524" alt="Screenshot 2019-11-27 at 13 04 53" src="https://user-images.githubusercontent.com/9613200/69729110-0e9fbb00-1126-11ea-9dcb-3c9dd8526900.png">

**Comment by designatednerd** [comment]
Interesting - if you check for the websocket error and then restart the subscription when you come back from the background if there is an error, does that work? Maybe there's something that's calling one of the various unsubscribe methods under the hood when the subscription gets cancelled that I'm missing in the code.

**Comment by arnaumartifont** [comment]
Yes, if I do re-subscribe again after it came from background it works.

**Comment by designatednerd** [comment]
OK. There's definitely something killing your connection when you go to the background - `1005` is the "Lost network connection" error in NSURLSession, but I'm not sure why that's terminating the subscription when it's set up to reconnect. I'd have to take a considerably deeper look at your code to see what's going on, particularly given that it's working with Rx. 

Anyway, at least from a standpoint of getting things working, is checking the error and then reconnecting if needed a sufficient workaround for this issue?

**Comment by arnaumartifont** [comment]
Okay thanks, yes I have them working now just checking if there is an error, so no issue for now with that workaround, I will do some testing with a singleton instance class without Rx (I'm sure that will work as the Rx part has nothing to hold from Apollo like the cancellable), maybe is the ViewController causing the trouble over the Cancellable instance.

**Comment by designatednerd** [comment]
Yeah, without taking a deeper look at your code there's not a great way to be sure, but I'll keep an eye out for issues around this in the future. Do you mind if we close this one out?

**Comment by designatednerd** [comment]
Since I haven't heard back in a couple weeks, I'm going to close this issue out. Please open a new issue if you're experiencing similar problems. Thank you!
