### ISSUE TITLE
Best practice for shared query subsets?

### ISSUE THREAD

**Issue by rnystrom** [apollographql/apollo-ios#93]
I'm using the GitHub GraphQL API + Apollo to query Issues and Pull Requests. Requesting both requires a different object, so I have two queries, which means Apollo creates two different queries: [IssueQuery](https://github.com/rnystrom/Freetime/blob/master/gql/API.swift#L17) and [PullRequestQuery](https://github.com/rnystrom/Freetime/blob/master/gql/API.swift#L476).

I need to take these models and generate the same view models from them, and so far find it a little tedious to basically write the same code twice (sharing as many functions as possible) since both queries share the exact same types but are namespaced to the root query.

For example: 

[IssueQuery.Data.Repository.Issue.Label](https://github.com/rnystrom/Freetime/blob/master/gql/API.swift#L282-L293) 
vs
[PullRequestQuery.Data.Repository.PullRequest.Label](https://github.com/rnystrom/Freetime/blob/master/gql/API.swift#L323-L335).

I can't use fragments since the [IssueTimelineItem](https://developer.github.com/v4/reference/union/issuetimelineitem/) and [PullRequestTimelineItem](https://developer.github.com/v4/reference/union/pullrequesttimelineitem/) don't have any unions (right?).

Here is my [issue query](https://github.com/rnystrom/Freetime/blob/master/gql/Issue.graphql) and [pull request query](https://github.com/rnystrom/Freetime/blob/master/gql/PullRequest.graphql).

I'm a GraphQL noob and just picking things up for the first time, also super impressed w/ this project and hoping to learn enough that I can contribute back to it.

**Comment by rnystrom** [comment]
Looks like I overlooked [this type](https://developer.github.com/v4/reference/union/issueorpullrequest/)

**Comment by ermik** [comment]
Freetime has gone a long way.
