### ISSUE TITLE
apollo.watch() method getting called repeatedly , how to cancel it or release it ? 

### ISSUE THREAD

**Issue by jainamOx** [apollographql/apollo-ios#931]
I have added one watcher with a use of below methods GraphQLManager.shardGraphQLManager.watchDataFromQuery() method  //GraphQLManager.swift 
and  
self.apollo.watch(query: query, cachePolicy: CachePolicy.fetchIgnoringCacheData) //ApploClient.swift

but this watcher been called repeatedly 

is there any method through we can remove or cancel previous watcher before assigning new one ?

**Comment by kimdv** [comment]
You have to save the return value from `let cancellable = self.apollo.watch(query: query, cachePolicy: CachePolicy.fetchIgnoringCacheData)`

Then later you can do `cancellable.cancel()`

**Comment by jainamOx** [comment]
Thanks @kimdv  , .cancel() working fine for me .
