### ISSUE TITLE
How to define the rules for type convert

### ISSUE THREAD

**Issue by jzhw0130** [apollographql/apollo-ios#94]
@martijnwalraven 

Server define a type 'Date', the format is '2017-06-06' or 1496736244000, (string or int).
Generate the scheme.json by apollo-codegen download-schema, the type is 'Date', too

Generate the API.swift by apollo-codegen generate , the type convert to 'String' automatically. Then data decode will throw exception when server format is int(1496736244000).  Because it can not convert 'Int' to 'String'..

Now I have to change the API.swift manually, from 'String' to 'Int'. But it is not good,  I have to do it many times when scheme changes...

Could you tell me the best way to solve the problem?

Thanks a lot

Jing

**Comment by cerupcat** [comment]
Did you find a solution for this? I'm also looking how to automatically create Date types during apollo codegen.

**Comment by martijnwalraven** [comment]
@cerupcat @jzhw0130: You should be able to pass `--passthrough-custom-scalars` to `apollo-codegen` to avoid generating a `typealias` to `String` for custom scalars. You can then add your own alias and conversion code, see [here](https://github.com/apollographql/apollo-ios/issues/23#issuecomment-261697349) for an example.

**Comment by cerupcat** [comment]
Awesome, thanks! Will take a look.

**Comment by jzhw0130** [comment]
@cerupcat  I just modify the scheme.json manually to solve the problem

**Comment by cerupcat** [comment]
Thanks @jzhw0130. I don't think that would work for us since we share the schema file across platforms and it gets auto generated when we make changes. Will be giving the other solution a try when we get back to that part.

**Comment by shehang** [comment]
@jzhw0130 & @cerupcat Do you guys found a way to solve this?
I tried modifying the scheme.json file but it doesn't work.
Having trouble Decoding & Encoding DateTime type to Date in typealias.

Any help is appreciated.

**Comment by designatednerd** [comment]
I've (finally) added some actual documentation and an example for this with #1474 - would appreciate any feedback.
