### ISSUE TITLE
CodeGen issues when upgrading from 10.1 -> 15.3

### ISSUE THREAD

**Issue by yashrao99** [apollographql/apollo-ios#943]
I wanted to take more advantage of the features that you guys have released, and upgraded our codebase from 10.3 -> 15.3. Running into some codegen issues...

##### npm apollo version: 2.21.1

I have read the cocoapod version of codegen here: https://www.apollographql.com/docs/ios/installation/#advanced-codegen-tips-and-tricks

after a fresh `pod install`, I looked into `{SCRIPTS_PATH}/` and I only see two files `check-and-run-apollo-cli.sh` and `check-and-run-apollo-codegen.sh`. The latter tells me to go to the website above ^^ and check out the new script.

The new script calls `run-bundled-codegen.sh` which I do not see in the Apollo/scripts folder.

I then try to use `check-and-run-apollo-cli.sh`, which I have been using on 10.1. It begins building, but then every single query in my current API.swift complains 

### Type 'Query' does not conform to protocol 'GraphQLOperation'

It offers to add protocol stubs, which adds the class variable `operationName` but it is not initialized, and therefore won't build. Plus since is this dynamically generated everytime, this would be waste.

I saw a similar issue here.. https://github.com/apollographql/apollo-ios/issues/769

I was unable to get past this protocol issue, and I am assuming it is surrounding the codegen script.

Any help would be greatly appreciated!

**Comment by yashrao99** [comment]
Current codegen script

```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./*.graphql --localSchemaFile="schema.json" API.swift
```

**Comment by designatednerd** [comment]
Hey @yashrao99 - Can you please try running `pod repo update` and then reinstalling? That should get you the most recent version of our library (`0.20.0`), which includes the `run-bundled-codegen` script referred to in our current documentation.

**Comment by yashrao99** [comment]
hey @designatednerd - thank you for such a fast response.

I did `pod repo update`, updated my pod to `0.20.0`, updated the script to the provided one from website, and I am still running into the 

#### Type 'Query' does not conform to protocol 'GraphQLOperation`

**Comment by designatednerd** [comment]
Are you getting that error from the CLI, or from Xcode directly? What happens when you click on the error - where does it bring you?

**Comment by designatednerd** [comment]
Aha! I forgot about this but it's mentioned in the issue you linked: This is one of the consequences of changing to the `Result<T, Error>` that's built-in to swift rather than a `(T, Error)` tuple. Please see the [0.13.0 release notes](https://github.com/apollographql/apollo-ios/blob/master/CHANGELOG.md#v0130) for further details, but basically you have to update the incoming parameters from: 

```swift
method { object, error in 
}
```
to 
```swift
method { result in 
}

**Comment by yashrao99** [comment]
@designatednerd I have already done that for all my queries!

**Comment by designatednerd** [comment]
OK, so back to my first thought: When you get those errors and you click on them, where does it take you?

**Comment by yashrao99** [comment]
@designatednerd It takes me to the API.swift file

**Comment by yashrao99** [comment]
<img width="421" alt="Screen Shot 2019-12-11 at 12 40 13 AM" src="https://user-images.githubusercontent.com/32831099/70605185-d7fa8380-1bae-11ea-9921-181014ff8db0.png">

**Comment by designatednerd** [comment]
Wow that's deeply weird if that's not being generated. When you look at that particular operation's code, is the property there? If it is, what happens if you clean your build folder and rebuild? 

If it's not, could you send me the `.graphql` file for that operation and your schema so I can try to repro on my end?

**Comment by yashrao99** [comment]
No the property is not there, I have the option to manually add it using the auto-fix in XCode, but all that does is add

```
class X {
  var operationName: String
}
```

which then complains about the variable not being initialized since it's neither optional nor force-unwrapped.

I have tried cleaning build folder, deleting the API.swift file in favor of generating a new one but then I can't get passed buildtime since the existing queries in codebase are unrecognizable. 

Yes I can send you, where can I send this?

**Comment by designatednerd** [comment]
ellen at apollographql dot com - One thing I would double-check is that your codegen build phase is set up to happen **before** the compile phases, otherwise changes won't pick up properly for reasons you're seeing.

**Comment by yashrao99** [comment]
Just sent the email! Thank you again for the help

**Comment by designatednerd** [comment]
@yashrao99 and I chatted quite a bit and it's still not entirely clear what's screwed up in his environment, but he was able to get code to regenerate in a separate project.

Yashas, since we've found you a workaround, is it okay if we close this out?

**Comment by designatednerd** [comment]
Since I haven't heard back in a couple weeks, I'm going to go ahead and close this out. If you're having similar problems, please open a new issue and we'll try to get to the bottom of it. Thank you!
