### ISSUE TITLE
Crash in ApolloClient init

### ISSUE THREAD

**Issue by francybiga** [apollographql/apollo-ios#946]
After updating Apollo to 0.20.0 (I was using 0.17.0), I get a crash in `ApolloClient.init` method.

The precise error is `Apollo outlined init with copy of NetworkTransport`.

The peculiar thing is that, after performing a Derived Data and project clean, the crash goes away but returns later.

Does anyone else has the same problem?

![Screenshot 2019-12-12 at 10 05 08](https://user-images.githubusercontent.com/244899/70698171-361a8a00-1cc7-11ea-9c60-60ed50f32168.png)

**Comment by designatednerd** [comment]
I have never seen this before, for what it's worth. Do you have either thread sanitizer or Address sanitizer turned on in your code?

**Comment by RuiAAPeres** [comment]
I haven't seen this happening either. 😞

**Comment by francybiga** [comment]
@designatednerd no, I only have the Main Thread Checker active.

In the last days the problems didn't happen again, so I don't have any additional details. If it will resurface I'll try to provide additional infos.

**Comment by designatednerd** [comment]
I wonder if this is related to the issue in #945 that was resolved by the release of Xcode 11.3 - did the problems stop happening when you upgraded?

**Comment by ApplePrima** [comment]
No, I’m still using 11.2.1

**Comment by francybiga** [comment]
No, I’m still using 11.2.1

**Comment by designatednerd** [comment]
@francybiga Any further updates on this? If you're not still seeing crashes we should probably close this out as an Xcode Gremlin™

**Comment by francybiga** [comment]
I’ve been on holiday since Christmas so I didn’t try a lot but It didn’t happen on latest working weeks so I think is ok to close it.
Thank you for your support! 👍🏻
