### ISSUE TITLE
Make more stuff use `Equatable` and conditional conformance

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#950]
#948 pointed up something we haven't changed since conditional conformance landed - we really need to be taking better advantage of it, especially comparing things that implement `Equatable`.

**Comment by natew** [comment]
Any updates on this? Seems fairly simple and would save us re-writing every model (is there some simple way to copy a struct and make it equatable for now?)

**Comment by designatednerd** [comment]
Yep, will be working on this as part of the Swift Codegen project. You can see an outline of the plan in #939 and follow the process of that project [here](https://github.com/apollographql/apollo-ios/projects/2).

**Comment by alizx** [comment]
Any update on this?

**Comment by AnthonyMDev** [comment]
We still plan to work on this, but it is dependent upon a lot of other work in progress right now. For the time being, it's best for you to manually implement `Equatable` in extension on your generated models. There are a lot of questions around _what_ makes models equal, and we have to provide a lot of complex functionality for configuring that.

**Comment by AnthonyMDev** [comment]
This was just merged into the branch for the 1.0 release. We are currently in public Alpha, and beta should be starting July 1st!
