### ISSUE TITLE
Add docs for using auto-persisted queries

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#951]
As requested in #767

**Comment by tpsantos** [comment]
Hi, 
I want to add auto-persisted queries in my project, but I have a problem with `operationIdentifiers` after `enableAutoPersistedQueries: true`. 

Can you help me? Do you have a forecast to the doc?

Thanks.

**Comment by designatednerd** [comment]
@tpsantos What is the issue you're running into?

**Comment by tpsantos** [comment]
@designatednerd After that added the `enableAutoPersistedQueries: true` and `sendOperationIdentifiers: true`, the Apollo is crashing because not find the `operationIdentifiers` (RequestCreator in line 52).

How I add the `operationIdentifiers`, this should be automatic?

**Comment by designatednerd** [comment]
You need to make sure that you're passing an `--operationIdsPath` option to the codegen - otherwise the identifiers won't get generated when the operation code is generated, and you will see that crash.

**Comment by tpsantos** [comment]
@designatednerd It's worked, thank you!

**Comment by designatednerd** [comment]
Now available!
