### ISSUE TITLE
Using Fragments returns nil

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-ios#959]
we are using fragments on our query like this : 
`  products{
...TestModel
       }`

`fragment TestModel on OurModelOnServer{
    id
   name
   description
    price
   out_of_stock
}`

`TestModel ` is an array of items and it returns array of nil items like this : [nil,nil,nil]

But when i take the keys outside the fragment like the following : 
`  products{
    id
   name
   description
    price
   out_of_stock
       }`
then it works...

Knowing that we are using fragments on  many queries and it is working except on a new query that is created recently 
**PS: the new query is built on a new structure...my colleague @habib786 will reply what is changed in the below comments**

**Comment by habib786** [comment]
I'm the backend developer and I am focusing on the keys that are sent from the client side. 
I added a loop to check what keys they asked for and I'm publishing only these keys from the mongo. 
So now we have an issue, when I check for the keys using fragments, I can only get the fragments **name** like **TestModel** instead of its keys. 

Can you please help us how to get the keys using fragment on the client side? 

Here is the response that I get once fragment is used on the client side. 
```
[ '__typename', 'products.__typename', 'products.Test' ]
```

And here is the response if they don't use fragments.
```
keys [
   '__typename',
   'products.__typename',
   'products.id',
   'products.name',
   'products.description',
   'products.price',
   'products.out_of_stock'
]
```

I just want the keys instead of fragment name when they use fragments.

**Comment by designatednerd** [comment]
The fragment should also be sent - on the generated query, you should see a `queryDocument` property that would look something like this:

```swift
public var queryDocument: String { return operationDefinition.appending(TestModel.fragmentDefinition) }
```

I'm confused by what this means:

> `TestModel` is an array of items and it returns array of nil items like this : [nil,nil,nil]

`products` should return an array of `TestModel` items. if `TestModel` itself is an array, there may be something else happening here.

**Comment by sam961** [comment]
`  fetchProductsV2(params:{category: $catIDs,events:$eventsIDs,gender:$gender,limit:$limit,offset:$offset}) {
    
        products{
          ...Test
        }
}`

fragment Test on ProductQuery{
    id
   name
   description
    price
   out_of_stock

}

**Comment by sam961** [comment]
```
fetchProductsV2(params:{category: $catIDs,events:$eventsIDs,gender:$gender,limit:$limit,offset:$offset}) {
        products{
          ...Test
        }
}

fragment Test on ProductQuery{
    id
   name
   description
    price
   out_of_stock
}
```

Iam using this in the .graphql  file

On the mobile side ... iam handling it in this way :
 ```
 guard let products = response.data?.fetchProductsV2?.products else {
                                               return
                                           }
}
```

The result  for products is : 
**[nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil]**

when I dont use the fragment like this it works : 

```
fetchProductsV2(params:{category: $catIDs,events:$eventsIDs,gender:$gender,limit:$limit,offset:$offset}) {
        products{
               id
               name
              description
             price
             out_of_stock
        }
}
```
What could be the issue ?

**Comment by designatednerd** [comment]
I tried doing something similar to what you're doing with our Star Wars API's `Review` query, and I was able to get it to work just fine, so I'm not sure what's going on here.

Can you tell what the JSON is that's coming in from the network that results in the big bunch of `nil` objects vs. the JSON that's resulting in actual objects? My sneaking suspicion is they're using different keys.

**Comment by habib786** [comment]
@designatednerd 
The results are array of nil/null objects

```
results = [ null, null, null ... ]
```
The results are null because there is a key inside these objects as `price` which is null from the db and this key is also mandatory in graphql schema, if it doesn't exists or its value is null then it will return null/nil in response. 

Only issue is in calling a query. 

Can you share you client side query? I want to understand how do you call the fragments and query.

Thank you for your response.

**Comment by designatednerd** [comment]
Sure. The file I added this to is the [CreateReviewForEpisode.graphql file](https://github.com/apollographql/apollo-ios/blob/master/Tests/StarWarsAPI/CreateReviewForEpisode.graphql). The GraphQL looks like this: 

```graphql
query AllReviews {
  reviews(episode: NEWHOPE) {
    ...ReviewResponse
  }
}

fragment ReviewResponse on Review {
  stars
  commentary
}
```


<details>
<summary>Generated Query code (click to expand)</summary>

```swift
public final class AllReviewsQuery: GraphQLQuery {
  /// The raw GraphQL definition of this operation.
  public let operationDefinition =
    """
    query AllReviews {
      reviews(episode: NEWHOPE) {
        __typename
        ...ReviewResponse
      }
    }
    """

  public let operationName = "AllReviews"

  public let operationIdentifier: String? = "c3c31d441e395d5f8431190f654933c43cd09a3311c07c491a422f71f1777636"

  public var queryDocument: String { return operationDefinition.appending(ReviewResponse.fragmentDefinition) }

  public init() {
  }

  public struct Data: GraphQLSelectionSet {
    public static let possibleTypes = ["Query"]

    public static let selections: [GraphQLSelection] = [
      GraphQLField("reviews", arguments: ["episode": "NEWHOPE"], type: .list(.object(Review.selections))),
    ]

    public private(set) var resultMap: ResultMap

    public init(unsafeResultMap: ResultMap) {
      self.resultMap = unsafeResultMap
    }

    public init(reviews: [Review?]? = nil) {
      self.init(unsafeResultMap: ["__typename": "Query", "reviews": reviews.flatMap { (value: [Review?]) -> [ResultMap?] in value.map { (value: Review?) -> ResultMap? in value.flatMap { (value: Review) -> ResultMap in value.resultMap } } }])
    }

    public var reviews: [Review?]? {
      get {
        return (resultMap["reviews"] as? [ResultMap?]).flatMap { (value: [ResultMap?]) -> [Review?] in value.map { (value: ResultMap?) -> Review? in value.flatMap { (value: ResultMap) -> Review in Review(unsafeResultMap: value) } } }
      }
      set {
        resultMap.updateValue(newValue.flatMap { (value: [Review?]) -> [ResultMap?] in value.map { (value: Review?) -> ResultMap? in value.flatMap { (value: Review) -> ResultMap in value.resultMap } } }, forKey: "reviews")
      }
    }

    public struct Review: GraphQLSelectionSet {
      public static let possibleTypes = ["Review"]

      public static let selections: [GraphQLSelection] = [
        GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
        GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
        GraphQLField("stars", type: .nonNull(.scalar(Int.self))),
        GraphQLField("commentary", type: .scalar(String.self)),
      ]

      public private(set) var resultMap: ResultMap

      public init(unsafeResultMap: ResultMap) {
        self.resultMap = unsafeResultMap
      }

      public init(stars: Int, commentary: String? = nil) {
        self.init(unsafeResultMap: ["__typename": "Review", "stars": stars, "commentary": commentary])
      }

      public var __typename: String {
        get {
          return resultMap["__typename"]! as! String
        }
        set {
          resultMap.updateValue(newValue, forKey: "__typename")
        }
      }

      /// The number of stars this review gave, 1-5
      public var stars: Int {
        get {
          return resultMap["stars"]! as! Int
        }
        set {
          resultMap.updateValue(newValue, forKey: "stars")
        }
      }

      /// Comment about the movie
      public var commentary: String? {
        get {
          return resultMap["commentary"] as? String
        }
        set {
          resultMap.updateValue(newValue, forKey: "commentary")
        }
      }

      public var fragments: Fragments {
        get {
          return Fragments(unsafeResultMap: resultMap)
        }
        set {
          resultMap += newValue.resultMap
        }
      }

      public struct Fragments {
        public private(set) var resultMap: ResultMap

        public init(unsafeResultMap: ResultMap) {
          self.resultMap = unsafeResultMap
        }

        public var reviewResponse: ReviewResponse {
          get {
            return ReviewResponse(unsafeResultMap: resultMap)
          }
          set {
            resultMap += newValue.resultMap
          }
        }
      }
    }
  }
}
```
</details>

<details>
<summary>Generated fragment code (click to expand)</summary>

```swift
public struct ReviewResponse: GraphQLFragment {
  /// The raw GraphQL definition of this fragment.
  public static let fragmentDefinition =
    """
    fragment ReviewResponse on Review {
      __typename
      stars
      commentary
    }
    """

  public static let possibleTypes = ["Review"]

  public static let selections: [GraphQLSelection] = [
    GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
    GraphQLField("stars", type: .nonNull(.scalar(Int.self))),
    GraphQLField("commentary", type: .scalar(String.self)),
  ]

  public private(set) var resultMap: ResultMap

  public init(unsafeResultMap: ResultMap) {
    self.resultMap = unsafeResultMap
  }

  public init(stars: Int, commentary: String? = nil) {
    self.init(unsafeResultMap: ["__typename": "Review", "stars": stars, "commentary": commentary])
  }

  public var __typename: String {
    get {
      return resultMap["__typename"]! as! String
    }
    set {
      resultMap.updateValue(newValue, forKey: "__typename")
    }
  }

  /// The number of stars this review gave, 1-5
  public var stars: Int {
    get {
      return resultMap["stars"]! as! Int
    }
    set {
      resultMap.updateValue(newValue, forKey: "stars")
    }
  }

  /// Comment about the movie
  public var commentary: String? {
    get {
      return resultMap["commentary"] as? String
    }
    set {
      resultMap.updateValue(newValue, forKey: "commentary")
    }
  }
}
```
</details>

<details>
<summary>Test Case (click to expand)</summary>

```swift
func testParsing() {
    let json = [
        "reviews": [
          [
            "__typename": "Review",
            "stars": 10,
            "commentary": "This is awesome!"
          ],
          [
            "__typename": "Review",
            "stars": 5,
            "commentary": "This is OK!"
          ]
        ]
      ]
    
    let queryResponse = try AllReviewsQuery.Data(jsonObject: json)
    XCTAssertEqual(queryResponse.reviews?.count, 2)
    
    for review in queryResponse.reviews! {
      guard let review = review else {
        XCTFail("Review was nil!")
        return
      }
      XCTAssertEqual(review.__typename, "Review")
    }
}
```

</details>

Test case passes without issue and when I breakpoint it,  each review shows the correct type.

**Comment by designatednerd** [comment]
@habib786 @sam961 Any luck figuring out what was going on here?

**Comment by sam961** [comment]
actually the issue still exist.
we are working on this query without fragments until we finish releasing a new version then we will come back to investigate more in the issue since we cannot work without fragments

**Comment by designatednerd** [comment]
OK - we'll leave this open a bit, I'd like to come back to this because I'd like to understand what's going on here. For my own info, what graphQL server are you using?

**Comment by designatednerd** [comment]
@sam961 Were you ever able to figure out what on earth was going on here?

**Comment by sam961** [comment]
Hello @designatednerd 
Actually the issue is still and we leaved it and get back to work with the old way.
But we are planning to work and figure out the issue asap since this approach is faster than the old one we are using.
We can close the issue for now and open it when we work on it

**Comment by designatednerd** [comment]
OK sounds like a plan!
