### ISSUE TITLE
Fragment across multiple schemas...

### ISSUE THREAD

**Issue by Cleversou1983** [apollographql/apollo-ios#965]
Hello there! I've modified the build script to make use of two schemas (one public, and the other, private)... It work's fine, I'm facing a little problem though... In both schemas, I'm using the ProductFragment, for example... When I put in public GraphQL folder only, I get an error saying that the my fragment is not recognized in private (makes sense), but when a copy of the fragment on the private GraphQL folder, it says that the redeclaration is invalid (make sense too)... Is there a way to share a fragment in both APIs of mine? The only thing that works is to make another fragment, but different name, but this way, I lost the benefit of the fragment... Thanks a lot!!!

SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"

cd "${SRCROOT}/${TARGET_NAME}/API/PublicAPI"  
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift  --includes=GraphQL/*.graphql --localSchemaFile=schemaPublic.json PublicAPI.swift

cd "${SRCROOT}/${TARGET_NAME}/API/PrivateAPI"  
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift  --includes=GraphQL/*.graphql --localSchemaFile=schemaPrivate.json PrivateAPI.swift

**Comment by Cleversou1983** [comment]
![Captura de Tela 2020-01-07 às 17 39 38](https://user-images.githubusercontent.com/34983085/71927683-c936ca80-3174-11ea-897b-f5dcd1c64eba.png)

**Comment by designatednerd** [comment]
Yeah, this is a limitation of using two different schemas in the same project. In theory you could use namespacing but then you'd have `API1.ProductFragment` and `API2.ProductFragment` and you still wouldn't be able to use them interchangeably. 

My thought would be to use different names for the fragments in public and private, then have both conform to a protocol you define outside of the API:

```swift
protocol SharedProductFragment {
   // whatever common properties these have
}

extension PublicProductFragment: SharedProductFragment {}
extension PrivateProductFragment: SharedProductFragment {}
```

**Comment by Cleversou1983** [comment]
Hello @designatednerd ! I was doing that way and thought maybe there's a better way... The only problem I'm getting is a fragment whose other fragment is part of it. I've made the protocol and the extension, declared a variable with the same name, and set it as the protocol type, still no success... Do you have any clue? Thanks a lot!

`typealias ID                        = String

protocol UserFragmentProtocol {
    var id              : ID { get set }
    var name            : String? { get set }
    var email           : String  { get set }
    var indicationCode  : String? { get set }
    var birthDate       : String? { get set }
    var phone           : String? { get set }
    var genre           : String? { get set }
    var avatar          : AttachmentFragmentProtocol { get }
}

protocol AttachmentFragmentProtocol {
    var url         : String? { get set }
//    var variant     : String? { get set }
}



// MARK: - Extensions
extension UserFragment: UserFragmentProtocol {}

extension AttachmentFragment: AttachmentFragmentProtocol {}
`

The error I'm getting is: Type 'UserFragment' does not conform to protocol 'UserFragmentProtocol'
![Captura de Tela 2020-01-08 às 23 14 50](https://user-images.githubusercontent.com/34983085/72031920-b1427200-326c-11ea-85af-ac5425acc518.png)

**Comment by Cleversou1983** [comment]
@designatednerd It almost worked using protocols... But I'm having a hard time to make it work when the variable inside the structure is of a fragment... I've attached an image with my protocols and the query definition, if I uncomment those commented lines, I get an error saying the object doesn't conform to the protocol... Can you help me please? Thanks a lot!!!
![help](https://user-images.githubusercontent.com/34983085/72036074-7e05e000-3278-11ea-9f52-fd4893ec2852.png)

**Comment by Cleversou1983** [comment]
PS: although the queries on the image are saying AvatarFragment and AttachmentFragment, on my queries on the project, I'm using the correct name: PrivateAvatarFragment and PrivateAttachmentFragment

**Comment by designatednerd** [comment]
You probably need to use associated types here, since the actual type of each thing is different (ie, the type being passed in isn't the protocol type, it's the underlying concrete type). So something like 

```swift
protocol UserFragmentProtocol {
   associatedType Attachment: AttachmentFragmentProtocol
   // everything else the same
  var avatar: Attachment
}
extension AttachmentFragment: AttachmentFragmentProtocol {}
extension UserFragment: UserFragmentProtocol {
   typealias Attachment: AttachmentFragment
}
```

**Comment by Cleversou1983** [comment]
Hello, @designatednerd ! Thanks for your reply... Unfortunately I couldn't make it work, as you can see on the attached image... ('I've put on the image my query and fragment as well) 
![help2](https://user-images.githubusercontent.com/34983085/72093153-9d415380-32f2-11ea-9569-fef3dfdff140.png)
Thanks again!

**Comment by designatednerd** [comment]
What's the suggested fix on that error? Also, do all those need to be `get set` instead of just `get`?

**Comment by Cleversou1983** [comment]
You're right, those are mean to be only `get`... I've attached the suggested fix... Thanks!
![error3](https://user-images.githubusercontent.com/34983085/72094321-f27e6480-32f4-11ea-97a5-bc1ef3886a67.png)

**Comment by designatednerd** [comment]
Yah you don't need to redeclare `avatar`, you just need to add the `typealias`.

**Comment by Cleversou1983** [comment]
Yes! But that’s the XCode suggestion...

**Comment by Cleversou1983** [comment]
Hello, @designatednerd ! 
I think there's no workaround on that issue, right? Thanks!

**Comment by Cleversou1983** [comment]
At the playground it worked, but I think the problem is how the Fragment structure is defined by Apollo... Thanks very much, I really appreciate your help! <3 

public struct UserFragment: GraphQLFragment {
  /// fragment UserFragment on User {
  ///   __typename
  ///   id
  ///   name
  ///   email
  ///   indicationCode
  ///   birthDate
  ///   phone
  ///   genre
  ///   avatar {
  ///     __typename
  ///     ...PrivateAvatarFragment
  ///   }
  /// }
  public static let fragmentDefinition =
    "fragment UserFragment on User { __typename id name email indicationCode birthDate phone genre avatar { __typename ...PrivateAvatarFragment } }"

  public static let possibleTypes = ["User"]

  public static let selections: [GraphQLSelection] = [
    GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
    GraphQLField("id", type: .nonNull(.scalar(GraphQLID.self))),
    GraphQLField("name", type: .scalar(String.self)),
    GraphQLField("email", type: .nonNull(.scalar(String.self))),
    GraphQLField("indicationCode", type: .scalar(String.self)),
    GraphQLField("birthDate", type: .scalar(String.self)),
    GraphQLField("phone", type: .scalar(String.self)),
    GraphQLField("genre", type: .scalar(String.self)),
    GraphQLField("avatar", type: .object(Avatar.selections)),
  ]

  public private(set) var resultMap: ResultMap

  public init(unsafeResultMap: ResultMap) {
    self.resultMap = unsafeResultMap
  }

  public init(id: GraphQLID, name: String? = nil, email: String, indicationCode: String? = nil, birthDate: String? = nil, phone: String? = nil, genre: String? = nil, avatar: Avatar? = nil) {
    self.init(unsafeResultMap: ["__typename": "User", "id": id, "name": name, "email": email, "indicationCode": indicationCode, "birthDate": birthDate, "phone": phone, "genre": genre, "avatar": avatar.flatMap { (value: Avatar) -> ResultMap in value.resultMap }])
  }

  public var __typename: String {
    get {
      return resultMap["__typename"]! as! String
    }
    set {
      resultMap.updateValue(newValue, forKey: "__typename")
    }
  }

  public var id: GraphQLID {
    get {
      return resultMap["id"]! as! GraphQLID
    }
    set {
      resultMap.updateValue(newValue, forKey: "id")
    }
  }

  public var name: String? {
    get {
      return resultMap["name"] as? String
    }
    set {
      resultMap.updateValue(newValue, forKey: "name")
    }
  }

  public var email: String {
    get {
      return resultMap["email"]! as! String
    }
    set {
      resultMap.updateValue(newValue, forKey: "email")
    }
  }

  public var indicationCode: String? {
    get {
      return resultMap["indicationCode"] as? String
    }
    set {
      resultMap.updateValue(newValue, forKey: "indicationCode")
    }
  }

  public var birthDate: String? {
    get {
      return resultMap["birthDate"] as? String
    }
    set {
      resultMap.updateValue(newValue, forKey: "birthDate")
    }
  }

  public var phone: String? {
    get {
      return resultMap["phone"] as? String
    }
    set {
      resultMap.updateValue(newValue, forKey: "phone")
    }
  }

  public var genre: String? {
    get {
      return resultMap["genre"] as? String
    }
    set {
      resultMap.updateValue(newValue, forKey: "genre")
    }
  }

  public var avatar: Avatar? {
    get {
      return (resultMap["avatar"] as? ResultMap).flatMap { Avatar(unsafeResultMap: $0) }
    }
    set {
      resultMap.updateValue(newValue?.resultMap, forKey: "avatar")
    }
  }

  public struct Avatar: GraphQLSelectionSet {
    public static let possibleTypes = ["Attachment"]

    public static let selections: [GraphQLSelection] = [
      GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
      GraphQLFragmentSpread(PrivateAvatarFragment.self),
    ]

    public private(set) var resultMap: ResultMap

    public init(unsafeResultMap: ResultMap) {
      self.resultMap = unsafeResultMap
    }

    public init(url: String? = nil, id: GraphQLID, variant: String? = nil) {
      self.init(unsafeResultMap: ["__typename": "Attachment", "url": url, "id": id, "variant": variant])
    }

    public var __typename: String {
      get {
        return resultMap["__typename"]! as! String
      }
      set {
        resultMap.updateValue(newValue, forKey: "__typename")
      }
    }

    public var fragments: Fragments {
      get {
        return Fragments(unsafeResultMap: resultMap)
      }
      set {
        resultMap += newValue.resultMap
      }
    }

    public struct Fragments {
      public private(set) var resultMap: ResultMap

      public init(unsafeResultMap: ResultMap) {
        self.resultMap = unsafeResultMap
      }

      public var privateAvatarFragment: PrivateAvatarFragment {
        get {
          return PrivateAvatarFragment(unsafeResultMap: resultMap)
        }
        set {
          resultMap += newValue.resultMap
        }
      }
    }
  }
}

**Comment by designatednerd** [comment]
Could you be more specific about what part of the structure you think is causing the issue? I'm not sure what part is the issue from the raw code.

**Comment by Cleversou1983** [comment]
I have no clue... I thought that might be something about the structure, because the structure created by hand in your example worked fine, the structure generated by Apollo doesn't work, but I know it's something about the avatar fragment type...

**Comment by Cleversou1983** [comment]
Hi, @designatednerd ! I don't wanna bother you with that matter, but I've attached a project with the query, schema and a test in the ViewController file, if you have time to take a look... I really appreciate your help, and I've tried everything, that's why I'm looking for help... Thanks a lot, Ellen!

[testfragment.zip](https://github.com/apollographql/apollo-ios/files/4049780/testfragment.zip)

**Comment by Cleversou1983** [comment]
I'm still striving to make a workaround on this... I'was checking the generated code for the userFragment and looks like the "problem" is with the avatar definition
![Captura de Tela 2020-01-13 às 14 35 01](https://user-images.githubusercontent.com/34983085/72278115-18b44500-3612-11ea-8dff-ad30fb377792.png)

**Comment by designatednerd** [comment]
Thank you for sending the test project, that was super-helpful! I think the biggest issue is the `fragments` object is making everything a hell of a lot harder than it needs to be, because you have to dive several layers deep in order to get to the object you're trying to share. 

I did eventually get it compiling with the following structure: 

```swift
// The actual fragment that has the URL
protocol AttachmentFragmentProtocol {
    var url: String? { get }
}

extension PrivateAvatarFragment: AttachmentFragmentProtocol {}

// The thing that has the fragment that has the URL
protocol AttachmentFragmentHolder {
    associatedtype Attachment: AttachmentFragmentProtocol
    
    var attachmentFragment: Attachment { get }
}

extension UserFragment.Avatar.Fragments: AttachmentFragmentHolder {
    typealias Attachment = PrivateAvatarFragment

    var attachmentFragment: PrivateAvatarFragment {
        return self.privateAvatarFragment
    }
}

// The thing that has the the thing that has the fragment that has the URL
protocol AttachmentFragmentOuterHolder {
    associatedtype AttachmentHolder: AttachmentFragmentHolder
    var fragments: AttachmentHolder { get }
}

extension UserFragment.Avatar: AttachmentFragmentOuterHolder {
    typealias AttachmentHolder = UserFragment.Avatar.Fragments
}

protocol UserFragmentProtocol {
    associatedtype AttachmentContainer: AttachmentFragmentOuterHolder
    
    var id: String { get }
    var name: String? { get }
    var email: String { get }
    var indicationCode: String? { get }
    var birthDate: String? { get }
    var phone: String? { get }
    var genre: String? { get }
    var avatar: AttachmentContainer? { get }
}

extension UserFragment: UserFragmentProtocol {
    typealias AttachmentContainer = UserFragment.Avatar
}
```

This obviously isn't ideal, but it'd at least get you to where you need to be.

**Comment by designatednerd** [comment]
@Cleversou1983 Is there anything else I can help with here?

**Comment by Cleversou1983** [comment]
Hi, Ellen! Sorry for the lack of feedback. Your solution worked perfectly! Thanks a lot! Best regards! Cleverson

**Comment by designatednerd** [comment]
Cool, I'm going to go ahead and close this issue out then. If you're experiencing similar problems, please open a new issue. Thank you!
