### ISSUE TITLE
Installation docs point to broken GraphQL formatter link

### ISSUE THREAD

**Issue by theolampert** [apollographql/apollo-ios#970]
Installation docs point to broken formatter link:

> please use [the GraphQL Formatter tool](http://toolbox.sangria-graphql.org/format

**Comment by designatednerd** [comment]
Oof, unfortunately it appears the primary maintainer of Sangria passed away last year and his Heroku account has now gone through whatever he'd prepaid. I'll reach out to the folks who took over the project and see what I can find out - that was definitely the best formatter I'd seen.

**Comment by theolampert** [comment]
@designatednerd I'm sorry to hear that. Let me know if I can help out in someway.

**Comment by designatednerd** [comment]
If you happen to see another formatter that works well, let me know. Haven't heard back from that team yet.

**Comment by designatednerd** [comment]
Fixed via #996
