### ISSUE TITLE
Offline sync Feature

### ISSUE THREAD

**Issue by pjcau** [apollographql/apollo-ios#973]
HI
I am looking for an ios client, and i have seen that there is only Apollo. I read the documentation and tried your "frontpage" example. I have a question. To keep having persistent objects offline I have to use sqlitecache. All is well, ok. But if now I have to make changes offline, the problem is that the mutation logic is on the server, the only thing that would be interesting is to have a queue of operations to send when connected again. The concept is offline sync.
Infact on AWS AppSync service we have a "AppSyncClient" that processes both offline and online mutations, and mutations are queued for processing even while the client is offline, so this count represents a good measure of the number of mutations that have yet to be successfully sent to the service, regardless of the state of the network.
Have you think about it? Have you know a simple way to implement it?

**Comment by designatednerd** [comment]
Offline sync adds an order of magnitude of complication (possibly several) to what we're trying to provide, and I don't think it's something we'll be providing as first party. We have way, way too much on deck already to open the **enormous** can of worms that is offline sync. 

Sorry to be a downer but I still have deep scars from the last time I implemented a sync engine 😛

**Comment by pjcau** [comment]
OK, I'm fine with that is something you want to delegate. Do you already have something implementable in your architecture to which I can hook to manage this feature? 
I have seen that also on Android from this point of view the architecture of the clients is shared, since you do not have the offline sync. Since we want to delegate, and we are starting a big full stack / multi platforms project so if we had your delegate contact person to make a call to understand if it can be done together and then leave it in the Apollo community. Can you help us in this?

**Comment by designatednerd** [comment]
You are welcome to build whatever you'd like as a separate library, but I'd caution you that the codegen rewrite outlined in #939 is going to involve some significant architectural changes and you may want to wait until at least the first couple parts of that land later this year before proceeding, because otherwise there'll be some massively breaking changes when it lands.

**Comment by theolampert** [comment]
Offline sync is difficult to get right and often different for everyone, I can understand the hestation to bake that into this library. 

@pjcau I managed to achieve this using a combination of [direct cache access](https://github.com/apollographql/apollo-ios/blob/master/docs/source/caching.md#direct-cache-access) and a [persistent task queue](https://github.com/lucas34/SwiftQueue) for queueing up mutations and running them when the app comes back online. My use case isn't so complicated however so your mileage may vary.

**Comment by designatednerd** [comment]
> Offline sync is difficult to get right and often different for everyone

We're not far into the decade but this is already a candidate for understatement of the decade 😃

**Comment by designatednerd** [comment]
I'm going to go ahead and close this out, since I'm making the executive decision that we're not going to include this as part of the core library because it's *way* too much work that gets away from the core of what we're trying to do. 

You're more than welcome to work on your own solution for this. Best of luck with that!

**Comment by pgawlowski** [comment]
@theolampert - hey, 
Can You share your solution in more detail? Here or on priv if you wish. I am trying to achieve sth similar and I'm stucked a little bit.
