### ISSUE TITLE
Can Apollo generator perform mutation on a scalar value?

### ISSUE THREAD

**Issue by dchohfi** [apollographql/apollo-ios#974]
Hi,
I'm trying to generate code with the following mutation:

```
mutation MagicLinkEmail($email: String!) {
  magicLinkEmail(email: $email)
}
```

The graphql scheme is defined as:
`magicLinkEmail(email: String!): Boolean`

The generator is giving errors when it tries to generate files when returning scalar values.
I'm doing something wrong? It works o GraphiQL Workspace.

**Comment by designatednerd** [comment]
> The generator is giving errors when it tries to generate files when returning scalar values.

Can you share the exact errors you're getting? 

Also, have you tried using the  `--passthroughCustomScalars` flag?

**Comment by dchohfi** [comment]
thank you for your response, had some issues on my side when fetching schema.
