### ISSUE TITLE
Error in "Loading schema for Unnamed Project" tvOS

### ISSUE THREAD

**Issue by ChernyshTaras** [apollographql/apollo-ios#980]
Hello!

I  tried to generate API.swift, but had error. I found the same[ issue](https://github.com/apollographql/apollo-ios/issues/757) and followed by [appolo's instruction](https://www.apollographql.com/docs/ios/installation/#installing-the-apollo-framework). It didn't help me fix this bug. Please, help me!

> **" Error: Error in "Loading schema for Unnamed Project": Error: Unable to read file schemaTV.json. ENOENT: no such file or directory, open 'schemaTV.json'"**

tvOS
xcode 11.3
swift 5.0
Cocoapods

**Comment by ChernyshTaras** [comment]
I found out that my `test.qraphql` contained object that didn't contain in `schema.json`. So I couldn't map schema. I changed `schema.json` and it fixed this problem.

**Comment by designatednerd** [comment]
@ChernyshTaras Thanks for sharing the solution for anyone else running into this problem!
