### ISSUE TITLE
HTTPNetworkTransport delegate is strong ref

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#994]
not sure if it's intended but `HTTPNetworkTransport` delegate is strong ref. 
If delegate have ref to `ApolloClient` you get into retain cycle.

`ApolloClient` -> `HTTPNetworkTransport` -> delegate ¬
    ^-------------------------------------------------+

**Comment by designatednerd** [comment]
@RolandasRazma Did you see #990? I believe that addresses this.

**Comment by RolandasRazma** [comment]
ah, yes, sorry, should have searched first, exactly what I wanted
